### ISSUE TITLE
目前该程序支持gpt4 模型吗

### ISSUE THREAD

**Issue by M0Cube** [Chanzhaoyu/chatgpt-web#1003]
如果已经购买chatgpt plus 或者申请成功后能直接用吗

**Comment by loutian** [comment]
可以， 我用的plus，配置gpt-4直接用

**Comment by shenmirenQUQ** [comment]
> 可以， 我用的plus，配置gpt-4直接用

你开通了plus之后，需要申请gpt-4的api再使用吗？
我开通plus之后再配置gpt-4报错

**Comment by shenmirenQUQ** [comment]
> 可以， 我用的plus，配置gpt-4直接用

undefined
[ChatGPT error 404: {
"error": {
"message": "The model: gpt-4 does not exist",
"type": "invalid_request_error",
"param": null,
"code": "model_not_found"
}
}
]

**Comment by loutian** [comment]
用accessToken登录，   api登录的需要等审批通过才行

**Comment by shenmirenQUQ** [comment]
> 用accessToken登录， api登录的需要等审批通过才行

明白了，感谢，我就是怎么开通了也不行😂

**Comment by tu95** [comment]
> 用accessToken登录， api登录的需要等审批通过才行

只有使用API的时候选择模型才能生效，使用token的时候设置gpt-4，问他：你是谁，他的回答还是gpt3.5。如果你是网页端上选中gpt-4，你问他，它会告诉你他是gpt4。

**Comment by tu95** [comment]
> 用accessToken登录， api登录的需要等审批通过才行

使用token的时候，无法选择模型版本。我实测使用token，并且加上--env OPENAI_API_MODEL=gpt-4。问他：你是谁，他的回答还是gpt3.5。
如果你是网页端上选中gpt-4，你问他，它会告诉你他是gpt4。

**Comment by loutian** [comment]
我docker部署的， docker-compose.yaml里配置 OPENAI_API_MODEL: gpt-4， 然后网页问题是什么模型，他回答就是GPT-4， 如果我不配这个变量， 他就回答是3.5

**Comment by shenmirenQUQ** [comment]
> 我docker部署的， docker-compose.yaml里配置 OPENAI_API_MODEL: gpt-4， 然后网页问他是什么模型，他回答就是GPT-4， 如果我不配这个变量， 他就回答是3.5
> 
> > > 用accessToken登录， api登录的需要等审批通过才行
> > 
> > 
> > 使用token的时候，无法选择模型版本。我实测使用token，并且加上--env OPENAI_API_MODEL=gpt-4。问他：你是谁，他的回答还是gpt3.5。 如果你是网页端上选中gpt-4，你问他，它会告诉你他是gpt4。

我也测试过了，我用accessToken登陆问他是什么版本，他说他是gpt-4的
