### ISSUE TITLE
如何确认成功调用了GTP4模型？

### ISSUE THREAD

**Issue by maosancai** [Chanzhaoyu/chatgpt-web#1004]
我已经申请到gtp4的8k的api接口了，用docker部署的，环境变量加上了OPENAI_API_MODEL=gpt-4 ，项目可以正常运行，但是我问ai他是哪个版本的时候，他回答 

我是一个基于OpenAI GPT-3模型的人工智能助手。截至我的知识更新（2021年9月1日），最新版本是GPT-3。关于后续的版本，例如4.0版本之类的信息，我无法提供。

然后让他画图他也画不了，这样子和3.5的模型有什么区别吗？还是说我的配置方式不对？

**Comment by assassinliujie** [comment]
看你的openai的requst日志
![%8PI@L71AJW8UDZ$5I~CL)C](https://user-images.githubusercontent.com/68693675/228429895-d491648f-8e45-48e3-a249-c0a63cd73b65.jpg)
以及api功能并不全，具体查看官方文档
以及“我是一个基于OpenAI GPT-3模型的人工智能助手。截至我的知识更新（2021年9月1日），最新版本是GPT-3。关于后续的版本，例如4.0版本之类的信息，我无法提供。”这句话不能构成没有调用的依据，他不知道自己是多少

**Comment by mm519897405** [comment]
看输出速度就行了，3.5比4.0快很多

**Comment by eschervr-dev** [comment]
> 看你的openai的requst日志
> ![%8PI@L71AJW8UDZ$5I~CL)C](https://user-images.githubusercontent.com/68693675/228429895-d491648f-8e45-48e3-a249-c0a63cd73b65.jpg)
> 以及api功能并不全，具体查看官方文档
> 以及“我是一个基于OpenAI GPT-3模型的人工智能助手。截至我的知识更新（2021年9月1日），最新版本是GPT-3。关于后续的版本，例如4.0版本之类的信息，我无法提供。”这句话不能构成没有调用的依据，他不知道自己是多少

这个日志在哪里看？

**Comment by assassinliujie** [comment]
> > 看你的openai的requst日志
> > ![%8PI@L71AJW8UDZ$5I~CL)C](https://user-images.githubusercontent.com/68693675/228429895-d491648f-8e45-48e3-a249-c0a63cd73b65.jpg)
> > 以及api功能并不全，具体查看官方文档
> > 以及“我是一个基于OpenAI GPT-3模型的人工智能助手。截至我的知识更新（2021年9月1日），最新版本是GPT-3。关于后续的版本，例如4.0版本之类的信息，我无法提供。”这句话不能构成没有调用的依据，他不知道自己是多少
> 
> 这个日志在哪里看？

你从哪拿的api key啊，就在那个后台https://platform.openai.com/

**Comment by maosancai** [comment]
> 看你的openai的requst日志 ![%8PI@L71AJW8UDZ$5I~CL)C](https://user-images.githubusercontent.com/68693675/228429895-d491648f-8e45-48e3-a249-c0a63cd73b65.jpg) 以及api功能并不全，具体查看官方文档 以及“我是一个基于OpenAI GPT-3模型的人工智能助手。截至我的知识更新（2021年9月1日），最新版本是GPT-3。关于后续的版本，例如4.0版本之类的信息，我无法提供。”这句话不能构成没有调用的依据，他不知道自己是多少

找到了，的确是4.0的，谢谢
