### ISSUE TITLE
accessToken可以用gpt-4模型吗

### ISSUE THREAD

**Issue by JPmorganA** [Chanzhaoyu/chatgpt-web#1005]

**Comment by pepperdog999** [comment]
可以啊，在模型参数那里配置gpt-4

**Comment by JPmorganA** [comment]
> 可以啊，在模型参数那里配置gpt-4

好的，非常感谢

**Comment by Timoshao** [comment]
docker run -d --name chatgpt-web -p 3002:3002  -e OPENAI_API_MODEL=gpt-4 -e OPENAI_ACCESS_TOKEN=你的token chenzhaoyu94/chatgpt-web
 我这样调用了GPT-4 但是感觉调用之后回复速度比3.5慢

**Comment by JPmorganA** [comment]
>  docker run -d --name chatgpt-web -p 3002:3002  -e OPENAI_API_MODEL=gpt-4 -e OPENAI_ACCESS_TOKEN=你的token chenzhaoyu94/chatgpt-web
> 
>  我这样调用了GPT-4 但是感觉调用之后回复速度比3.5慢 
> 
> 

好的谢谢，我听说可能是因为参数要比3.5多很多的原因才导致会比3.5慢

**Comment by tu95** [comment]
> docker run -d --name chatgpt-web -p 3002:3002 -e OPENAI_API_MODEL=gpt-4 -e OPENAI_ACCESS_TOKEN=你的token chenzhaoyu94/chatgpt-web 我这样调用了GPT-4 但是感觉调用之后回复速度比3.5慢

这样启动的还是gpt3.5-turbo。很简单，你问一下你是谁，他的回答还是gpt3.5。如果你是网页上选中gpt-4，你问他，它会告诉你他是gpt4。

**Comment by tu95** [comment]
> docker run -d --name chatgpt-web -p 3002:3002 -e OPENAI_API_MODEL=gpt-4 -e OPENAI_ACCESS_TOKEN=你的token chenzhaoyu94/chatgpt-web 我这样调用了GPT-4 但是感觉调用之后回复速度比3.5慢

似乎不能生效。我按照您的方式启动，问他：你是谁。他的回答还是gpt3.5。如果你是网页上选中gpt-4，你问他，它会告诉你他是gpt4。

**Comment by JPmorganA** [comment]
> > docker run -d --name chatgpt-web -p 3002:3002 -e OPENAI_API_MODEL=gpt-4 -e OPENAI_ACCESS_TOKEN=你的token chenzhaoyu94/chatgpt-web 我这样调用了GPT-4 但是感觉调用之后回复速度比3.5慢
> 
> 
> 
> 似乎不能生效。我按照您的方式启动，问他：你是谁。他的回答还是gpt3.5。如果你是网页上选中gpt-4，你问他，它会告诉你他是gpt4。

我不是plus用户，不过有白名单，用token方式确实是这样，我让它给我写个贪吃蛇小游戏它写不出来，我用api方式就能写出来

**Comment by tu95** [comment]
> 

我的操作有失误。
使用token并设置OPENAI_API_MODEL: gpt-4是可以的，我之前失败是因为使用非plus的token。
谢谢您！
