### ISSUE TITLE
Feature Request: 添加多伦对话次数的限制

### ISSUE THREAD

**Issue by DIYer22** [Chanzhaoyu/chatgpt-web#1007]
不少同事懒得点新建对话, 或者不清楚对话的机制, 一直在一个对话页面问不同的问题, 持续好多轮不同话题的对话, 导致消耗巨大的 token 数, 非常浪费, 以及 ChatGPT 受到无关上下文干扰, 回答的质量变差.

所以希望添加一个可配置变量, 用来限制单次对话的轮数, 超过限制轮数后, UI界面上也提醒用户需要 "新建对话".

**Comment by assassinliujie** [comment]
我有个小建议，直接限制他的使用量，等他超了发现今天用不了了第二天就知道要用new chat了（
