### ISSUE TITLE
根据readme提示部署到centos后，ip+1002端口访问不动，ip+3002端口也访问不到，希望予以解答，谢谢

### ISSUE THREAD

**Issue by fxxxchao** [Chanzhaoyu/chatgpt-web#1008]
1、本地已经测试过没问题
2、本地的项目打包后传到了服务器
3、根据提示分别部署了前端和服务端项目

但是都无法正常访问，希望予以解答，感谢🙏

![image](https://user-images.githubusercontent.com/39323781/228437774-5c819420-16d0-443d-8363-69d6c4ba8187.png)

**Comment by fxxxchao** [comment]
[root@ser231869596322 ~]# netstat -lnpt |grep 3002
tcp6       0      0 :::3002                 :::*                    LISTEN      12561/node     

服务端口已启动

**Comment by mcqnby** [comment]
服务器端口开了么

**Comment by fxxxchao** [comment]
[root@ser231869596322 src]# netstat -lnpt |grep 1002
tcp        0      0 0.0.0.0:1002            0.0.0.0:*               LISTEN      15700/node   

前端的端口也在

**Comment by xccloveny** [comment]
防火墙

**Comment by fxxxchao** [comment]
防火墙/安全组设置的问题，已解决
