### ISSUE TITLE
response有数据但是前端无法渲染出文字是为什么

### ISSUE THREAD

**Issue by MichaelCS00** [Chanzhaoyu/chatgpt-web#101]
![image](https://user-images.githubusercontent.com/33749624/220840948-e97fc343-9c05-47fe-b425-b032ddf5ac3a.png)

**Comment by Chanzhaoyu** [comment]
更新你的版本

**Comment by MichaelCS00** [comment]
> 更新你的版本
master 更新到 2.7.1 已经正常，stream分支不行

**Comment by Chanzhaoyu** [comment]
`stream` 还有问题没有解决，先用 `main` 分支吧

**Comment by MichaelCS00** [comment]
> `stream` 还有问题没有解决，先用 `main` 分支吧

好的，感谢
