### ISSUE TITLE
请问各位朋友，代码里怎么判断回答结束呢？

### ISSUE THREAD

**Issue by rocket2023** [Chanzhaoyu/chatgpt-web#1010]
![image](https://user-images.githubusercontent.com/127300906/228444771-2f79575e-30fe-4ff8-92b6-d430c3fba7e1.png)

**Comment by daniel-8642** [comment]
接口返回的json里面有个finish_reason字段，"finish_reason":""的时候是还在生成，"finish_reason":"stop"是最后一个包。
