### ISSUE TITLE
端口更改

### ISSUE THREAD

**Issue by culilaren** [Chanzhaoyu/chatgpt-web#1012]
为啥改不了这个默认端口？怎么改都不行

**Comment by fxxxchao** [comment]
本地还是服务器

**Comment by culilaren** [comment]
本地

**Comment by culilaren** [comment]
我用unraid 自带的xml部署，不论填不填ports，都是3002
![image](https://user-images.githubusercontent.com/111490317/228453286-0e671d3f-adcf-4fcd-8587-9f9124ccee3c.png)
![image](https://user-images.githubusercontent.com/111490317/228453571-401b797e-c18c-489b-98d9-0a546cb72dbe.png)
