### ISSUE TITLE
docker build失败了

### ISSUE THREAD

**Issue by wydweb** [Chanzhaoyu/chatgpt-web#1013]
![image](https://user-images.githubusercontent.com/29632638/228450518-62c02744-1af3-4cf0-b32f-5f20f37117b2.png)
第一步build就失败了，提示以下
=> ERROR [stage-2 8/9] COPY --from=frontend /app/dist /app/public 
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::swpjqmlcs17z8jgqr7wfoxajm: "/app/dist": not found
这要怎么办呢，请各位大哥支个招，我的是reacknerd的垃圾vps512M

**Comment by wydweb** [comment]
感谢回复，我也试了分1.5G的交换也是不行，构建docker要好多内存😓，我现在只能用nohuo pnpm dev & tail -f nohup.out的方式放后台运行，不过现在好像终端关了它也一起关了😢

**Comment by fzucs** [comment]
我也是1g小鸡，所以我直接用docker-compose了，build至少得2g起吧

**Comment by rocket2023** [comment]
同样的情况
