### ISSUE TITLE
我开启了上下文但是好像不生效

### ISSUE THREAD

**Issue by qyjgg** [Chanzhaoyu/chatgpt-web#1018]
![image](https://user-images.githubusercontent.com/44860826/228474148-3fcb3eb8-9cf5-45a6-ac20-44861b04a6e1.png)

**Comment by inlmcn** [comment]
api的好像一直都不可以

**Comment by qyjgg** [comment]
> api的好象都不能
不对啊  之前让它续写代码是可以的我记得很清楚

**Comment by inlmcn** [comment]
accessToken把

**Comment by qyjgg** [comment]
> 你用的什么版本，我的一直都是不可以的，现在还OK？

现在不行了 之前我是可以的

**Comment by qyjgg** [comment]
> 你用的什么版本，我的一直都是不可以的，现在还OK？

我现在是最新版本

**Comment by qianlei90** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/5654791/228498982-657f5629-a3dc-4f74-a109-28099a3ae36a.png">
同样不行 🌚

**Comment by thiner** [comment]
API在3.24前是可以的，部署了3.24的代码之后就不行了

**Comment by devyujie** [comment]
+1，docker版

**Comment by mcqnby** [comment]
我试了下把TIMEOUT_MS设为0就可以了

**Comment by di-photos** [comment]
API模式在升级2.10.8后确实存在上下文不生效问题（之前可行），按楼上同学把TIMEOUT_MS设为0解决了。

**Comment by mason0510** [comment]
@di-photos 我设置为0了 不行
