### ISSUE TITLE
请问能否支持使用azure openai的key呢，azure最新API接口已经兼容了openai官方接口

### ISSUE THREAD

**Issue by zhangqitao1** [Chanzhaoyu/chatgpt-web#1019]
https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=rest-api

**Comment by zhangqitao1** [comment]
curl $OPENAI_API_BASE/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview \
  -H "Content-Type: application/json" \
  -H "api-key: $OPENAI_API_KEY" \
  -d '{"messages":[{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": "Does Azure OpenAI support customer managed keys?"},{"role": "assistant", "content": "Yes, customer managed keys are supported by Azure OpenAI."},{"role": "user", "content": "Do other Azure Cognitive Services support this too?"}]}'

**Comment by stulzq** [comment]
可以使用我这个项目 https://github.com/stulzq/azure-openai-proxy

**Comment by jebouruama** [comment]
> 可以使用我这个项目 https://github.com/stulzq/azure-openai-proxy

太好了，找了半天终于找到了，马上去试试

**Comment by PeterDaveHello** [comment]
👉 #855
