### ISSUE TITLE
我的无法正常返回信息

### ISSUE THREAD

**Issue by qyjgg** [Chanzhaoyu/chatgpt-web#102]
![image](https://user-images.githubusercontent.com/44860826/220852660-f75e0d70-eff6-43fd-93e5-dc106bbf822b.png)

**Comment by qyjgg** [comment]
有遇到这种问题的吗   api我都更换过了  问题依旧

**Comment by Chanzhaoyu** [comment]
- 版本
- 控制台-网络返回截图

**Comment by qyjgg** [comment]
已经解决了   重新部了下就好了
