### ISSUE TITLE
请问是否支持GPT4.0

### ISSUE THREAD

**Issue by billconan2017** [Chanzhaoyu/chatgpt-web#1020]

**Comment by hncboy** [comment]
accesstoken 和 apiKey 都支持，OPENAI_API_MODEL

**Comment by tu95** [comment]
> OPENAI_API_MODEL

能请教一下您是如何使用gpt4的吗？
我是plus用户，可以在网页使用gpt4，但是没有gpt4 api。
我使用docker部署，使用token，增加OPENAI_API_MODEL: gpt-4，部署完你问他，你是谁，他回答是3.5turbo。
如果是plus的试用版gpt4，你问他，它会回答我是gpt4。
按照文档来看，OPENAI_API_MODEL选项只有使用API时才生效。

**Comment by hncboy** [comment]
#632 你看chatgpt后台的对话窗口是不是显示 gpt-4

**Comment by tu95** [comment]
> #632 你看chatgpt后台的对话窗口是不是显示 gpt-4

我的操作有失误。
使用token并设置OPENAI_API_MODEL: gpt-4是可以的，我之前失败是因为使用非plus的token。
谢谢您！

**Comment by xccloveny** [comment]
> OPENAI_API_MODEL
你只是plus用户，能使用GPT-4？我是指付费了20美刀，成为plus，就能使用4的api?

**Comment by xccloveny** [comment]
@tu95 
你只是plus用户，能使用GPT-4？我是指付费了20美刀，成为plus，就能使用4的api?

**Comment by hncboy** [comment]
> @tu95 你只是plus用户，能使用GPT-4？我是指付费了20美刀，成为plus，就能使用4的api?

plus 支持 AccessToken 模式的 gpt-4，不是 ApiKye 的 gpt-4.

**Comment by darvsum** [comment]
@hncboy  你测试过AccessToken多长时间过期吗？ 过期了有什么办法重新获取
