### ISSUE TITLE
前端构建后生成的js文件较大，导致打开页面加载慢

### ISSUE THREAD

**Issue by JasonYFY** [Chanzhaoyu/chatgpt-web#1021]
前端构建后生成的js文件较大（1.5M），导致打开页面加载慢，有什么方案解决吗？除了使用CDN外

**Comment by llybood** [comment]
使用nginx代理,打开gzip,压缩一下

**Comment by JasonYFY** [comment]
> 如果使用了nginx代理,可以打开gzip,对js文件进行压缩传输

感谢大佬，有效果

**Comment by mcqnby** [comment]
> 如果使用了nginx代理,可以打开gzip,对js文件进行压缩传输

学到了！
