### ISSUE TITLE
开启上下文模式，无法连续提问

### ISSUE THREAD

**Issue by mcqnby** [Chanzhaoyu/chatgpt-web#1023]
![image](https://user-images.githubusercontent.com/70184446/228488180-b2ac4fb4-1eef-4b93-949b-9e855bb29484.png)

**Comment by idsunb** [comment]
好像是不能连续提问了

**Comment by mcqnby** [comment]
把延迟设为0就可以了

**Comment by xueguizheng** [comment]
> 

延迟在哪？

**Comment by cy948** [comment]
> 把延迟设为0就可以了

您好，请问这个延迟设置在哪呢？
