### ISSUE TITLE
favicon和session加载失败

### ISSUE THREAD

**Issue by Usongkam** [Chanzhaoyu/chatgpt-web#1026]
![network](https://user-images.githubusercontent.com/41718340/228524380-adbd4491-c72d-4b57-aecd-01dcb02beb6e.png)

原本运行很正常，这两天突然出现这个问题。大陆访问会提示：
POST https://***/session net::ERR_CONNECTION_RESET
GET https://***/favicon.svg net::ERR_CONNECTION_RESET
翻墙访问正常。

但是试了一下ip并没有被墙，不同端口的其它服务都还在正常工作，而且从图片上来看并不是所有包都fail。是因为favicon.svg调用了外部链接吗，还是什么其它原因呢？

**Comment by Andy-qinyuhai** [comment]
域名被墙了吧

**Comment by Usongkam** [comment]
好吧，好像确实域名被墙了，加载出来的都是缓存。
