### ISSUE TITLE
只要发送邮件，就会自动将服务停了

### ISSUE THREAD

**Issue by cssjidi** [Chanzhaoyu/chatgpt-web#1027]
只要发送邮件，就会自动将服务停了。
用得是QQ邮箱。
而且停止是没有任何的错误提示。
<img width="238" alt="image" src="https://user-images.githubusercontent.com/8515692/228534165-300d6dbd-57a5-487c-9258-bd130a159cba.png">

**Comment by Fugitive844** [comment]
你用的是加了登陆功能的那个吧，那里面有个bug，发送邮件代码没有try catch，发送邮件异常会导致服务挂掉

**Comment by Kerwin1202** [comment]
我记得改过了，瞎写不会崩，最新版，只要是 smtp 都可以 不一定 qq

**Comment by cssjidi** [comment]
> 我记得改过了，瞎写不会崩，最新版，只要是 smtp 都可以 不一定 qq
