### ISSUE TITLE
希望网页可以添加暗黑模式与系统匹配。

### ISSUE THREAD

**Issue by JarvanDing** [Chanzhaoyu/chatgpt-web#103]
习惯看暗黑模式了。感谢

**Comment by Chanzhaoyu** [comment]
下个版本更新，已经在做了，和多语言一起

**Comment by JarvanDing** [comment]
![image](https://user-images.githubusercontent.com/31558141/221120873-b9315df1-ed29-4cc5-bbf1-2ce3e6865435.png)
请问这个新的ui吗？除了字体变淡，没有什么变化，而且字体淡化看的很不舒服了，还有暗黑模式是不是还没上线呢，还是说我的问题呢？

**Comment by Chanzhaoyu** [comment]
你强制刷新下浏览器缓存试下，黑暗模式还没上线

**Comment by Chanzhaoyu** [comment]
这个才是刚刚更新正常效果：

### 效果

#### Code
![code](https://user-images.githubusercontent.com/24789441/221119753-03defc0b-27d7-4d07-ae19-09ddf5cdf0fb.png)
---

### Other
![image](https://user-images.githubusercontent.com/24789441/221118891-45cc7d4f-535f-4186-98ed-6e11a9400410.png)

**Comment by JarvanDing** [comment]
我强制刷新也不行，用无痕模式打开还是不行，我是用docker打包运行的，然后用nginx反代。

**Comment by Chanzhaoyu** [comment]
我用 `docker` 运行个试一下

**Comment by Chanzhaoyu** [comment]
已适配
