### ISSUE TITLE
ACCESS_TOKEN 无法输出完整内容，具体如图，api的时候没有这个问题

### ISSUE THREAD

**Issue by justincnn** [Chanzhaoyu/chatgpt-web#1030]
每次都只能输入开头的几个字，然后就结束了。

![截屏2023-03-29 20.47.17.png](https://img1.imgtp.com/2023/03/29/tMUHzNEZ.png)

**Comment by hncboy** [comment]
看下控制台网络请求有继续输出吗。

**Comment by hncboy** [comment]
> > 看下控制台网络请求有继续输出吗。
> 
> 你好，请问在vps上如何看控制台有没有继续输出？

看下浏览器控制台网络请求，如果没有输出的话，试着重启下后台试试。

**Comment by justincnn** [comment]
> > > 看下控制台网络请求有继续输出吗。
> > 
> > 
> > 你好，请问在vps上如何看控制台有没有继续输出？
> 
> 看下浏览器控制台网络请求，如果没有输出的话，试着重启下后台试试。

你好，谢谢指导，
看了下，没有输出，重启docker也也是一样的，

**Comment by 502387174** [comment]
API我也遇到这个问题了

**Comment by 502387174** [comment]
![image](https://user-images.githubusercontent.com/23000950/228573595-e48c5333-614d-4cfd-84be-5b495d79d643.png)

**Comment by justincnn** [comment]
> ![image](https://user-images.githubusercontent.com/23000950/228573595-e48c5333-614d-4cfd-84be-5b495d79d643.png)

你输出的内容比我多，哈哈，我就几个字符，心碎掉了

**Comment by assassinliujie** [comment]
> 每次都只能输入开头的几个字，然后就结束了。
> 
> ![截屏2023-03-29 20.47.17.png](https://camo.githubusercontent.com/e40c306f33fc42c6d78f57cf63ce57cac3ef8055b674fba46dc12efc2c224f9f/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30332f32392f744d55487a4e455a2e706e67)

回退下版本或者更新下版本，按理说我已经修复了，只有中间版本有这个问题

**Comment by assassinliujie** [comment]
> ![image](https://user-images.githubusercontent.com/23000950/228573595-e48c5333-614d-4cfd-84be-5b495d79d643.png)

这个是服务器网络问题

**Comment by maosancai** [comment]
不是服务器网络问题，我在同一个服务器同时部署了3.5和4.0，3.5的回答是完整的，4.0就出现这种问题，重建容器都不行

**Comment by 502387174** [comment]
我用的最新的代码，自己用docker构建的，还是一样的问题~

**Comment by rht-fsang** [comment]
有解决方法了吗，各位大佬

**Comment by 502387174** [comment]
> 有解决方法了吗，各位大佬

最新版本的没问题了，你试一下

**Comment by rht-fsang** [comment]
> > 有解决方法了吗，各位大佬
> 
> 最新版本的没问题了，你试一下

我找到原因了，是因为gpt4太慢了，项目设置的接口超时为30秒，我改成60秒就没问题了

**Comment by nikissXI** [comment]
> 不是服务器网络问题，我在同一个服务器同时部署了3.5和4.0，3.5的回答是完整的，4.0就出现这种问题，重建容器都不行

我也是
