### ISSUE TITLE
请问vps的docker安装chatgpt，如何修改index文件？

### ISSUE THREAD

**Issue by justincnn** [Chanzhaoyu/chatgpt-web#1032]
ls了下，根本找不到文件，

在chatgpt-web下也是空文件夹

![ikxSZy.png](https://i.328888.xyz/2023/03/29/ikxSZy.png)

**Comment by jkhcc11** [comment]
> 

1、如果你是拉取的公共镜像，那么进入docker 里面修改，`docker  exec -it 你的容器名称 /bin/sh` 
2、如果你是本地编译的镜像，直接修改文件后，再build 即可

**Comment by justincnn** [comment]
> 1、如果你是拉取的公共镜像，那么进入docker 里面修改，`docker exec -it 你的容器名称 /bin/sh`
> 2、如果你是本地编译的镜像，直接修改文件后，再build 即可

可以了，感谢，
it小白学点新东西有点力不从心呀
