### ISSUE TITLE
请问大家知道购买了gpt plus 以后，gpt4.0 的api是如何获取的呢

### ISSUE THREAD

**Issue by M0Cube** [Chanzhaoyu/chatgpt-web#1036]
我目前只能通过accessToken 方式使用gpt4.0 
如果直接更改 OPENAI_API_MODEL=gpt-4 则会报错
undefined
[ChatGPT error 404: {
"error": {
"message": "The model: gpt-4 does not exist",
"type": "invalid_request_error",
"param": null,
"code": "model_not_found"
}
}
]

**Comment by Timoshao** [comment]
GPT4的API是单独申请的，如果没通过只能用OPENAI_ACCESS_TOKEN的方式。
不过我感觉GPT-4比GPT-3.5慢很多。

**Comment by mcqnby** [comment]
> GPT4的API是单独申请的，如果没通过只能用OPENAI_ACCESS_TOKEN的方式。 不过我感觉GPT-4比GPT-3.5慢很多。

access_token在哪里拿到的啊

**Comment by Timoshao** [comment]
> > GPT4的API是单独申请的，如果没通过只能用OPENAI_ACCESS_TOKEN的方式。 不过我感觉GPT-4比GPT-3.5慢很多。
> 
> access_token在哪里拿到的啊

![image](https://user-images.githubusercontent.com/108260847/228711593-d6a63089-6cb3-4cc5-b607-2ee1c6fca843.png)
项目中有介绍的

**Comment by mcqnby** [comment]
> > > GPT4的API是单独申请的，如果没通过只能用OPENAI_ACCESS_TOKEN的方式。 不过我感觉GPT-4比GPT-3.5慢很多。
> > 
> > 
> > access_token在哪里拿到的啊
> 
> ![image](https://user-images.githubusercontent.com/108260847/228711593-d6a63089-6cb3-4cc5-b607-2ee1c6fca843.png) 项目中有介绍的

谢谢 拿到了！

**Comment by 2258550147** [comment]
我找的这个人买的4.0api，微信bdpmqq
