### ISSUE TITLE
GPT-4为什么比GPT-3.5感觉回复慢很多

### ISSUE THREAD

**Issue by Timoshao** [Chanzhaoyu/chatgpt-web#1037]
使用OPENAI_ACCESS_TOKEN 同时部署了GPT-4和GPT-3，
同样的问题，明显感觉GPT-4回复比GPT-3.5慢很多。GPT-4类似一个字一个字的回复，GPT-3.5则是很流畅的回复
各位大佬，请问是哪里需要调整优化吗？
![image](https://user-images.githubusercontent.com/108260847/228708942-f5f037e6-ed0b-4e1e-9854-c959c6c4d449.png)
![image](https://user-images.githubusercontent.com/108260847/228708974-47c0db43-379a-46b0-9814-321e70296be7.png)

**Comment by mcqnby** [comment]
![image](https://user-images.githubusercontent.com/70184446/228710515-0a6a18bb-22e6-43f6-94fe-211c44b9a713.png)
![image](https://user-images.githubusercontent.com/70184446/228710568-68eb54bd-6b6e-4b16-8c5b-8bf2eee139b3.png)

**Comment by Timoshao** [comment]
> ![image](https://user-images.githubusercontent.com/70184446/228710515-0a6a18bb-22e6-43f6-94fe-211c44b9a713.png) ![image](https://user-images.githubusercontent.com/70184446/228710568-68eb54bd-6b6e-4b16-8c5b-8bf2eee139b3.png)
哦 感谢解惑 非常感谢
