### ISSUE TITLE
我购买了plus会员，但是gpt-4的access_token配置后只能同时一个人使用。另一个人就会有如下报错，是我配置错误吗

### ISSUE THREAD

**Issue by M0Cube** [Chanzhaoyu/chatgpt-web#1038]
undefined
[ChatGPT error 429: {"detail":{"message":"You have sent too many requests to the model. Please try again later.","code":"model_cap_exceeded","clears_in":5076}}]

**Comment by Timoshao** [comment]
正常，一个问题没回复完毕的时候 不允许新的提问。而且你登陆ChatGPT后台 也能看到所有的回复记录
API模式没这种问题。

**Comment by ludashi2020** [comment]
> undefined [ChatGPT error 429: {"detail":{"message":"You have sent too many requests to the model. Please try again later.","code":"model_cap_exceeded","clears_in":5076}}]

最好是一人一号，然后登录类似这样的官网反代https://chat.openai.yt，不用翻就能原汁原味体验官网的功能了。
