### ISSUE TITLE
TimeoutError: OpenAI timed out waiting for response  长回复内容断开 响应超时设置了600000

### ISSUE THREAD

**Issue by yigeimuya** [Chanzhaoyu/chatgpt-web#1039]
响应超时设置了600000ms，但前端提问不到2分钟，还是会断开，断开后不记得之前的内容。长内容基本100%复现，例如让写一篇10000字的文章。短回复不会

TimeoutError: OpenAI timed out waiting for response
    at file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24
    at new Promise ()
    at pTimeout (file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatReplyProcess (file:///app/build/index.mjs:104:22)
    at async file:///app/build/index.mjs:219:5

![image](https://user-images.githubusercontent.com/129144058/229310189-eefbd688-fb70-4df6-8176-689036c663c7.png)
![image](https://user-images.githubusercontent.com/129144058/229310266-a9cce8d1-e743-426e-a2cf-9fcff94c182d.png)
![image](https://user-images.githubusercontent.com/129144058/229310266-a9cce8d1-e743-426e-a2cf-9fcff94c182d.png)
![image](https://user-images.githubusercontent.com/129144058/229310433-42ce15b3-817b-4111-88fe-604bd65c8388.png)

**Comment by M0Cube** [comment]
我是.env文件里改了如下配置就不中断了
# timeout
TIMEOUT_MS=600000

**Comment by ConnerHua** [comment]
我回答两句就中断了，回答不完整

**Comment by ConnerHua** [comment]
修改了timeout 好像可以回答完整了，继续测试中

**Comment by devyujie** [comment]
> 我是.env文件里改了如下配置就不中断了
> 
> ```
> # timeout
> TIMEOUT_MS=600000
> ```

可行
