### ISSUE TITLE
输出不完整，就几个字就停了，但是连接未断

### ISSUE THREAD

**Issue by 502387174** [Chanzhaoyu/chatgpt-web#1040]
拉去最新镜像和拉最新代码自己docker部署都试过了不行，是不是和我使用腾讯云代理地址有关系哦~
![image](https://user-images.githubusercontent.com/23000950/228715600-b9314e50-246c-4079-a165-562fd0f93191.png)

**Comment by maosancai** [comment]
> 

如果是境外的服务器要怎么设置呢？是在控制台设置还是在docker里面设置呢？我用的docker部署的，也出现这种情况

**Comment by wangpre** [comment]
docker 部署的，通过nginx反向代理，要怎么设置呢？
<img width="419" alt="image" src="https://user-images.githubusercontent.com/53291931/229021347-35264e7e-d753-4630-8910-bc501a54c338.png">

**Comment by zhangsanproject** [comment]
> 检查一下请求路径上的 执行超时 设置的太短了， 腾讯云函数是在 函数管理 -> 函数配置 -> 编辑 -> 执行超时时间 境外vps自己看下软件的配置文件

就是这个原因，我用的阿里云的云函数，修改完就可以了

**Comment by AreChen** [comment]
> docker 部署的，通过nginx反向代理，要怎么设置呢？ <img alt="image" width="419" src="https://user-images.githubusercontent.com/53291931/229021347-35264e7e-d753-4630-8910-bc501a54c338.png">

估计是keepalive_timeout
