### ISSUE TITLE
后端接口地址配置项咋写，求解

### ISSUE THREAD

**Issue by itsevin** [Chanzhaoyu/chatgpt-web#1046]
手动打包说要修改根目录下 .env 文件中的 VITE_GLOB_API_URL 为实际后端接口地址，我是直接在服务器pnpm prod运行的后端，它显示在3002端口运行，然后这个配置项到底要怎么改？我填/api和http://127.0.0.1:3002都不行，访问前端是500，求解

**Comment by xiaosaaaa** [comment]
修改端口号的位置在chatgpt-web-2.10.8/vite.config.ts，如果你是拿服务器搭建的，那么将127.0.0.1换成你的服务器ip

**Comment by PDPENG** [comment]
同样遇到了500问题，题主解决了么？

**Comment by itsevin** [comment]
VITE_GLOB_API_URL=/api

VITE_APP_API_BASE_URL=http://我的官网ip:3002

我是部署在服务器
配置我又改成这样还是不行
咋写qwq

**Comment by PDPENG** [comment]
不对不对，题主你和我犯了一样的错误，我第一次也看错了，注意 要改的 IP 是在 `VITE_GLOB_API_URL` 也就是第一行的位置，改掉 `/API` 而不是下面的 `VITE_APP_API_BASE_URL` ，这里拼接请求的是 ip + 后端服务地址，所以一定注意改掉第一个 而不是第二行！！

> VITE_GLOB_API_URL=/api
> 
> VITE_APP_API_BASE_URL=[http://我的官网ip:3002](http://%E6%88%91%E7%9A%84%E5%AE%98%E7%BD%91ip:3002)
> 
> 我是部署在服务器 配置我又改成这样还是不行 咋写qwq

不对不对，题主你和我犯了一样的错误，我第一次也看错了，注意 要改的 IP 是在 `VITE_GLOB_API_URL` 也就是第一行的位置，改掉 `/API` 而不是下面的 `VITE_APP_API_BASE_URL` ，这里拼接请求的是 ip + 后端服务地址，所以一定注意改掉第一个 而不是第二行！！

**Comment by zhangsanproject** [comment]
> 不对不对，题主你和我犯了一样的错误，我第一次也看错了，注意 要改的 IP 是在 `VITE_GLOB_API_URL` 也就是第一行的位置，改掉 `/API` 而不是下面的 `VITE_APP_API_BASE_URL` ，这里拼接请求的是 ip + 后端服务地址，所以一定注意改掉第一个 而不是第二行！！
> 
> > VITE_GLOB_API_URL=/api
> > VITE_APP_API_BASE_URL=[http://我的官网ip:3002](http://%E6%88%91%E7%9A%84%E5%AE%98%E7%BD%91ip:3002)
> > 我是部署在服务器 配置我又改成这样还是不行 咋写qwq
> 
> 不对不对，题主你和我犯了一样的错误，我第一次也看错了，注意 要改的 IP 是在 `VITE_GLOB_API_URL` 也就是第一行的位置，改掉 `/API` 而不是下面的 `VITE_APP_API_BASE_URL` ，这里拼接请求的是 ip + 后端服务地址，所以一定注意改掉第一个 而不是第二行！！

感谢，就是这么修改，如果修改完还不行，记得检查一下服务器的3002端口是否打开了

**Comment by itsevin** [comment]
成功了感谢
