### ISSUE TITLE
对话历史编辑和 Prompt 商店增强

### ISSUE THREAD

**Issue by Cirn09** [Chanzhaoyu/chatgpt-web#1047]
### 对话历史编辑

目前 ChatGPT 对话上下文是通过每次都将上下文发送到服务器实现的，那我们是否可以通过编辑已经发送的内容（包括用户发送内容和 ChatGPT 回复内容）伪造对话历史以达成某些 Prompt 的效果？

目前可以通过导出对话、编辑后导入的方法实现这个功能，但我希望能直接在 Web 界面完成。

### Prompt 商店

如果我的理解没有错误，现在 Prompt 商店在添加了 Prompt 后，需要使用时还是需要手动复制粘贴，比较长的 Prompt 还需要点开编辑才能看到完整全文。

我认为可以添加一个“使用”按钮，点击后直接将 Prompt 复制到输入框中。

进一步结合上面的对话历史功能，实现包含对话历史的 Prompt，点击“使用”后直接创建一端对话历史。

**Comment by xiaosaaaa** [comment]
请输入/

**Comment by Cirn09** [comment]
> 请输入/

好！在 Prompt 商店页加个提示可能会更好一些
