### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by sdxy0506** [Chanzhaoyu/chatgpt-web#1048]
你好，我在service/.env里面配置了AUTH_SECRET_KEY，但是我打开页面的时候并没有登录，直接就能用了。我是使用的docker build -t chatgpt-web . 后，再docker run xxxx的方式运行的，是我哪里配置不对么？

**Comment by MekaYangyi** [comment]
我也是这样

**Comment by sdxy0506** [comment]
来信已收到，谢谢！
