### ISSUE TITLE
docker部署一直fetch failed，本地运行正常

### ISSUE THREAD

**Issue by zhanghw96** [Chanzhaoyu/chatgpt-web#1049]
同样的代码，用本地部署的方式可以正常使用，回答问题（用腾讯云云函数做的代理不支持流式输出）也可以。用docker部署后，页面访问正常，回答问题就一直fetch failed
我的改动
改了docker-compose.yml的 API接口地址（用我腾讯云的云函数地址）OPENAI_API_BASE_URL 和OPENAI_API_KEY
还在service中加了个.env的文件配置了API接口地址（用我腾讯云的云函数地址）OPENAI_API_BASE_URL和OPENAI_API_KEY

docker运行就是按照作者给的代码输入的（如下）

先进入项目路径
然后 docker build -t chatgpt-web .
再前台运行
docker run --name chatgpt-web --rm -it -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key chatgpt-web

![3P`@KZJEF~_`)F G1TE%%~9](https://user-images.githubusercontent.com/32092823/228747154-e1a0b0ce-373f-4f2b-9de7-9c436bb84a81.png)

**Comment by nagaame** [comment]
没有通过代理或者代理不可用

**Comment by zhanghw96** [comment]
> 没有通过代理或者代理不可用
本地运行可以使用，所以我确定我的代理是能用的（我本地电脑没用魔法上网），能帮我看下是我哪里配置出问题了吗

**Comment by nagaame** [comment]
> > > > 没有通过代理或者代理不可用
> > > > 本地运行可以使用，所以我确定我的代理是能用的（我本地电脑没用魔法上网），能帮我看下是我哪里配置出问题了吗
> > 
> > 
> > docker运行的时候，直接用--env flag加上API地址试试，类似这样
> > ```shell
> > docker run --name chatgpt-web --rm -it -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key --env OPENAI_API_BASE_URL=example.com/api  chatgpt-web
> > ```
> 
> 可以了，感谢大佬，能说下是为什么吗？我明明在代码里配置了OPENAI_API_BASE_URL的值（前面有说到），为什么docker运行就不生效

`docker`直接`run`的话，就要这样加上环境变量，如果你是`docker-compose`的话，直接修改`docker-compose.yaml`相关的环境变量就可以了

**Comment by zhanghw96** [comment]
> docker-compose

非常感谢您的回答

**Comment by zhanghw96** [comment]
> > > > > 没有通过代理或者代理不可用
> > > > > 本地运行可以使用，所以我确定我的代理是能用的（我本地电脑没用魔法上网），能帮我看下是我哪里配置出问题了吗
> > > 
> > > 
> > > docker运行的时候，直接用--env flag加上API地址试试，类似这样
> > > ```shell
> > > docker run --name chatgpt-web --rm -it -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key --env OPENAI_API_BASE_URL=example.com/api  chatgpt-web
> > > ```
> > 
> > 
> > 可以了，感谢大佬，能说下是为什么吗？我明明在代码里配置了OPENAI_API_BASE_URL的值（前面有说到），为什么docker运行就不生效
> 
> `docker`直接`run`的话，就要这样加上环境变量，如果你是`docker-compose`的话，直接修改`docker-compose.yaml`相关的环境变量就可以了

非常感谢您的回答
