### ISSUE TITLE
删除后也能够删除chatgpt那边的会话

### ISSUE THREAD

**Issue by AJHIAUNncnfbg** [Chanzhaoyu/chatgpt-web#105]
观察到在我们这边开启一个新会话后，chatgpt也会新开，
那么我们删除、甚至重命名的时候，是否也能够影响到chatgpt那边？
类似于https://github.com/acheong08/ChatGPT/wiki/V1 中的change_title和delete_conversation方法

**Comment by Chanzhaoyu** [comment]
这个暂时无法支持
