### ISSUE TITLE
想问下大佬，里面的webSocket的作用是什么，好像并没有用到聊天内容的传输

### ISSUE THREAD

**Issue by JasonYFY** [Chanzhaoyu/chatgpt-web#1051]
看了浏览器的请求url，有一个webSocket连接，但是好像没用到聊天内容的传输，想问问大佬有什么作用，可以去掉吗？因为有些浏览器对webSocket连接不兼容，导致打不开页面

**Comment by cd547** [comment]
没看到

**Comment by JasonYFY** [comment]
![image](https://user-images.githubusercontent.com/31659735/228783446-504de085-8821-487d-84f5-180560109e4e.png)
![image](https://user-images.githubusercontent.com/31659735/228783724-e0521734-a95c-48c0-8d45-5baa6e1c12bd.png)

**Comment by cd547** [comment]
![微信截图_20230330174840](https://user-images.githubusercontent.com/17153612/228798500-dec07f56-45f2-4963-a0f9-595e8d1bbc12.png)
我没有的，我是用他提供的railway部署的，看你那个ip好像是谷歌云的服务器

**Comment by JasonYFY** [comment]
> ![微信截图_20230330174840](https://user-images.githubusercontent.com/17153612/228798500-dec07f56-45f2-4963-a0f9-595e8d1bbc12.png) 我没有的，我是用他提供的railway部署的，看你那个ip好像是谷歌云的服务器

难道是部署方式的问题？我看看怎么禁用

**Comment by JasonYFY** [comment]
知道问题的原因了，我用了pnpm dev启动项目的-开发模式，用生产模式启动就行了
