### ISSUE TITLE
想请问一下，我在根目录执行完pnpm build为何没有产生dist文件夹？

### ISSUE THREAD

**Issue by yzq497259225** [Chanzhaoyu/chatgpt-web#1052]

**Comment by mcqnby** [comment]
先pnpm install

**Comment by ximeicuc-git** [comment]
想问下npm run build时出现这个error是哪个的问题啊？

**Comment by ximeicuc-git** [comment]
![image](https://user-images.githubusercontent.com/70133835/231408818-beed832c-2a16-425b-8e99-a96a64cc87a3.png)

**Comment by leefurong** [comment]
同问~
