### ISSUE TITLE
请求添加一个简单的后台管理

### ISSUE THREAD

**Issue by 6uu1** [Chanzhaoyu/chatgpt-web#1053]
# 希望能够保存提问日志，以及关键词检测和拦截，最好能加上禁止滥用用户使用用户（id标识或者ip?）

起因是这样子的，好心搭了个公开的公益站，然后没两天就被墙了，我以为是正常现象，然后又隔几天，账号被封了，说是违反条款，我寻思着也就用了api而已啊。直到我前两天冲浪的时候发现我的公益站被某些恶心的人一直问政治敏感和涩情关键词。。。。。。还出来炫耀。。。。。。我是希望能够让不会芳抢的人都能用到的，所以没有设置密码

**Comment by plutotree** [comment]
这个本来就不适合公开的

**Comment by hugoyue** [comment]
要这么搞，岂不是被卖号卖疯了，这个项目只适合个人

**Comment by rocket2023** [comment]
有后台，qq群：204311814
