### ISSUE TITLE
有人在使用gpt4模型的时候遇到这个问题吗？使用获得gpt-4 api权限账号的key，选择gpt4模型，部署之后还是gpt3.5

### ISSUE THREAD

**Issue by rht-fsang** [Chanzhaoyu/chatgpt-web#1054]

**Comment by yeswzq** [comment]
大佬也是刚升级了plush获取到的gpt4 api? 还是怎样的？

**Comment by rht-fsang** [comment]
> 各位大佬也是刚刚升级了plush获取到的gpt4 api？还是怎么样的？

我是账号申请gpt4的api权限通过了

**Comment by yeswzq** [comment]
> > 大佬也是刚升级了plush获取到的gpt4 api? 还是怎样的？
> 
> 你也会遇到了这个问题吗?

不是呢~ 我是accessToken。。 我plus 的accessToken 设置了OPENAI_API_MODEL:gpt-4 ，不行。 大佬你知道咋回事吗？

**Comment by JPmorganA** [comment]
> > > > 大佬也是刚升级了plush获取到的gpt4 api? 还是怎样的？
> 
> > > 
> 
> > > 
> 
> > > 你也会遇到了这个问题吗?
> 
> > 
> 
> > 不是呢~ 我是accessToken。。 我plus 的accessToken 设置了OPENAI_API_MODEL:gpt-4 ，不行。 大佬你知道咋回事吗？
> 
> 
> 
> 不知道，我看很多人用toeken成功的，你可以去别的issue下看看
我也是白名单，这个要在api不能用token

**Comment by JPmorganA** [comment]
> > > > 大佬也是刚升级了plush获取到的gpt4 api? 还是怎样的？
> 
> > > 
> 
> > > 
> 
> > > 你也会遇到了这个问题吗?
> 
> > 
> 
> > 不是呢~ 我是accessToken。。 我plus 的accessToken 设置了OPENAI_API_MODEL:gpt-4 ，不行。 大佬你知道咋回事吗？
> 
> 
> 
> 不知道，我看很多人用toeken成功的，你可以去别的issue下看看


在环境变量那里，你用api，并且把模型换成gpt-4试试不要用token

**Comment by JPmorganA** [comment]
直接问它是什么模型它都会回答是GPT3，你让它用python写个贪吃蛇小游戏，能写出来就是4，写不出来就3.5

**Comment by rht-fsang** [comment]
> 

我刚刚试了一下，gpt3.5的模型也能写出来

**Comment by JPmorganA** [comment]
你问它你是谁就会回答了，我这里3.5的会说自己是基于3.5，4的就没说，贪吃蛇那个要换一种问法：我不懂python，但是我们想开发一个贪吃蛇的小游戏，你可以帮我实现吗？如果可以，请回复ok，然后开始给出对应的代码实现

**Comment by JPmorganA** [comment]
![image](https://user-images.githubusercontent.com/124872854/228803828-3c1e696a-be38-482b-a0de-4d3aa703872b.png)还有一种方法就是看openai的后台，用量哪里，那里会使用了api key的话会明确显示是用的什么模型

**Comment by rht-fsang** [comment]
> ![image](https://user-images.githubusercontent.com/124872854/228803828-3c1e696a-be38-482b-a0de-4d3aa703872b.png)还有一种方法就是看openai的后台，用量哪里，那里会使用了api key的话会明确显示是用的什么模型

好的，谢谢。我去看一下

**Comment by plutotree** [comment]
1. 先确认下配置内容；
2. 再确认下日志内容；

我的直接问他是谁，4的话会直接回答是4

**Comment by rht-fsang** [comment]
> 

谢谢你的回答，我在openai账号后台看到使用的是gpt4，但是我直接问他不会回答是gpt4
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/83858861/228998655-17321e86-52fb-4d90-b7c5-177a3020cf9c.png">

**Comment by plutotree** [comment]
> openai账号后台看到

是要确认下`OPENAI_API_MODEL`参数是不是设置为`gpt-4`

**Comment by rht-fsang** [comment]
> > openai账号后台看到
> 
> 是要确认下`OPENAI_API_MODEL`参数是不是设置为`gpt-4`

是的，我看其他人接到gpt4后也有这个问题，问他还是说gpt-3模型

**Comment by tankxiaodi** [comment]
我也有这个问题, 我是在同一台机器上同时部署了3.5和4. 就会出现访问4也是3.5

后来我独立部署之后就好了.

**Comment by Heliangyuan** [comment]
我目前也遇到了这个问题，我是通过openai库调用的chatgpt，以前用的是3.5，apikey升级后现在用的是4。如今还没有解决，很难受，有大佬有解决方案嘛
![Uploading chat-5.png…]()
