### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by zyyyyyy456** [Chanzhaoyu/chatgpt-web#1055]
为啥会报这个

**Comment by daniel-8642** [comment]
fetch failed 这个是指连接失败，

建议先仔细看项目README，在日志和控制台找出错误提示，看README中，搜索Issues里面有没有同样的问题。这些做完过后再新开issue哦

记得带上错误信息。单纯这些信息没法解决你项目的问题。

**Comment by 1205129045x** [comment]
我也经常这样，有时候好好的，突然问一个问题就这样了，我怀疑是免费的代理不行

**Comment by ooiikaka1** [comment]
默认免费代理？怎么关闭？
