### ISSUE TITLE
发送对话时报一个FetchError错误

### ISSUE THREAD

**Issue by MS666666** [Chanzhaoyu/chatgpt-web#1056]
<img width="681" alt="Snipaste_2023-03-30_02-58-33" src="https://user-images.githubusercontent.com/44149537/228784932-2ca0739d-b301-4286-97cd-80bec912d103.png">

![image](https://user-images.githubusercontent.com/44149537/228785247-8f861762-b233-4440-901a-d5dcdff02baa.png)
求大佬帮忙看一下如何解决！

**Comment by nagaame** [comment]
Ref: issue https://github.com/Chanzhaoyu/chatgpt-web/issues/1049

**Comment by nagaame** [comment]
> > 参考：问题#1049
> > 我开了一个Clash for Windows桌面版的代理，为啥还是连接错？

Perhaps the terminal proxy was not set up successfully. Enter this command to set up the proxy.
 `set HTTP_PROXY=http://user:password@proxy.domain.com:port`

example:

`set HTTP_PROXY=http://192.168.1.100:8080`

and https proxy

`set HTTPS_PROXY=http://192.168.1.100:8088`
