### ISSUE TITLE
dockerfile build 报错？

### ISSUE THREAD

**Issue by rocket2023** [Chanzhaoyu/chatgpt-web#1059]
![image](https://user-images.githubusercontent.com/127300906/228805937-da9c6988-31ae-41f0-bb68-131d398347cd.png)

**Comment by daniel-8642** [comment]
错误应该的你的pnpm的版本和node.js 的版本不匹配，提示里面写了是pnpm要求v16.14，你安装的好像是v16.13。
考虑升一下node.js 的版本，如果有其他项目有依赖的话，考虑一下nvm

**Comment by rocket2023** [comment]
> 

它是dockerhub里node容器里面的，跟我宿主机环境没关系，而且我主机环境的node是16.19版本！

**Comment by rocket2023** [comment]
![image](https://user-images.githubusercontent.com/127300906/228999151-7166cef1-5f05-43b5-befe-8fb6751ad262.png)
我把基础镜像改了这个，就正常构建了！！！

**Comment by jeff-hong** [comment]
> ![image](https://user-images.githubusercontent.com/127300906/228999151-7166cef1-5f05-43b5-befe-8fb6751ad262.png) 我把基础镜像改了这个，就正常构建了！！！

老哥，怎么改的，教教我，我的情况和你的一模一样
![image](https://user-images.githubusercontent.com/53889843/229275887-a2e0881a-6df9-4ed6-a31d-1b1ffc21f602.png)

**Comment by SimZhou** [comment]
> ![image](https://user-images.githubusercontent.com/127300906/228999151-7166cef1-5f05-43b5-befe-8fb6751ad262.png) 我把基础镜像改了这个，就正常构建了！！！

光改Frontend的基础镜像不够，
我把三个基础镜像都从lts改成16.19.1就好了。
