### ISSUE TITLE
对话报错AbortController is not defined

### ISSUE THREAD

**Issue by vpsad** [Chanzhaoyu/chatgpt-web#1061]
![image](https://user-images.githubusercontent.com/83330547/228828657-64f6c230-d51e-4b5b-ab95-1d07570deb98.png)
nodejs版本：v16.20.0
项目版本：最新版

**Comment by vpsad** [comment]
> 升级一下node版本到18看看

有没有其他的解决方法呢？如果要换18版本的话我必须将服务器gcc升级到8.5以上版本，这会造成服务器不稳定，出现其他bug。如果想稳定使用，还得重装服务器镜像为最新版linux。

**Comment by mydaoyuan** [comment]
抱歉，我以为是服务端的报错。 服务端是安装了对应的npm包。

这个错误通常发生在使用了不支持AbortController的浏览器中，因为AbortController是一个比较新的API，所以某些旧版本的浏览器可能不支持它。如果你想要在这些浏览器上使用AbortController，可以考虑使用polyfill或者使用其他类似的停止请求的方法。如果你确定你的浏览器支持AbortController，那么可能是因为代码中没有正确引入该API，可以检查一下引入的方式是否正确。

以上回答来自 ai

https://www.npmjs.com/package/abortcontroller-polyfill  看看这个库

**Comment by vpsad** [comment]
> 

我使用的是最新版的EDGE浏览器，根据AI的回答，应该是项目代码问题。以下是AI的回答：

**Comment by vpsad** [comment]
> 抱歉，我以为是服务端的报错。 服务端是安装了对应的npm包。
> 
> 这个错误通常发生在使用了不支持AbortController的浏览器中，因为AbortController是一个比较新的API，所以某些旧版本的浏览器可能不支持它。如果你想要在这些浏览器上使用AbortController，可以考虑使用polyfill或者使用其他类似的停止请求的方法。如果你确定你的浏览器支持AbortController，那么可能是因为代码中没有正确引入该API，可以检查一下引入的方式是否正确。
> 
> 以上回答来自 ai
> 
> https://www.npmjs.com/package/abortcontroller-polyfill 看看这个库
我使用的浏览器是EDGE最新版，支持这个API，而根据AI的回答，似乎应该是这个项目代码问题？

这个错误的原因是在你的代码中的 AbortController 没有被正确地定义，导致无法访问它。一种解决方法是在你的代码中添加一个 Polyfill 来定义 AbortController。

首先，确保你已经正确地安装了 polyfill 模块。然后在代码中添加以下代码：

import 'abortcontroller-polyfill/dist/polyfill-patch-fetch';
这将添加一个 polyfill，它将定义 AbortController 以及其他一些全局变量。这个 polyfill 是基于 Promise 和 fetch 的，因此需要安装相应的模块。

如果你想在使用 XMLHttpRequest 时使用 AbortController，那么应该使用 polyfill-library 这个模块，它可以为 XMLHttpRequest 添加 abort 方法，并自动定义 AbortController。

在代码中添加以下代码：

require('polyfill-library/polyfills/abort-controller/polyfill');
require('polyfill-library/polyfills/fetch/polyfill');
这应该可以解决错误，并正确地定义 AbortController。

**Comment by JamesBobo** [comment]
同问
