### ISSUE TITLE
关于pc端网页输出代码中注释的字体显示不清的问题

### ISSUE THREAD

**Issue by fzucs** [Chanzhaoyu/chatgpt-web#1062]
电脑网页显示的代码中注释部分字体很小，再加上斜体的关系，就显得模糊。而手机端刚刚好。我是用docker-compose部署的，浏览器缩放比也正常。用了edge和chrome都是一样的情况。大家也有这种情况吗，还是只是我的有问题
![pc](https://user-images.githubusercontent.com/100392795/228831855-5c4bdb65-25d1-444d-b0f2-0c7b29d24222.png)
![sj](https://user-images.githubusercontent.com/100392795/228831872-48751668-7d08-489a-b3c0-72d86d102cc5.jpg)

**Comment by daniel-8642** [comment]
这个有可能和浏览器的配置有关，可以试试吧项目字体稍微调大一点的呢

**Comment by kof8855** [comment]
换一个1080p的显示器
