### ISSUE TITLE
.env.example 文件不生效 

### ISSUE THREAD

**Issue by lovekekelove** [Chanzhaoyu/chatgpt-web#1063]
![image](https://user-images.githubusercontent.com/34187793/228865177-31841c05-d446-411c-b311-9da5e1ad7f59.png)
 打印数据中没有配置信息！

**Comment by lovekekelove** [comment]
已解决

**Comment by daniel-8642** [comment]
解决了麻烦点一下关闭  : )

**Comment by mcqnby** [comment]
当然不生效，这是个示例文件，要改成.env
