### ISSUE TITLE
ERROR [frontend 8/8] RUN pnpm run build  

### ISSUE THREAD

**Issue by zhanghw96** [Chanzhaoyu/chatgpt-web#1064]
进入项目目录后运行 docker build -t chatgpt-web .（作者给的示例），报错ERROR [frontend 8/8] RUN pnpm run build  

![MZNQ2BH%_ P4`%MJBW~(95P](https://user-images.githubusercontent.com/32092823/228895152-c4173838-65b4-4c13-bc85-d45d7ec960a2.png)

**Comment by rht-fsang** [comment]
服务器内存不够，前端打包失败，找不到dist文件

**Comment by zhanghw96** [comment]
> 服务器内存不够，前端打包失败，找不到dist文件

感觉不像。看了下服务器内存监控，最多的时候才跑了60%，试了好几次，一直这样

**Comment by rht-fsang** [comment]
> > 服务器内存不够，前端打包失败，找不到dist文件
> 
> 感觉不像。看了下服务器内存监控，最多的时候才跑了60%，试了好几次，一直这样
是的，我踩过坑了。你打镜像之前把前端包dist打好

**Comment by zhanghw96** [comment]
> > > 服务器内存不够，前端打包失败，找不到dist文件
> > 
> > 
> > 感觉不像。看了下服务器内存监控，最多的时候才跑了60%，试了好几次，一直这样
> > 是的，我踩过坑了。你打镜像之前把前端包dist打好

解决了，也是用你的思路，我本地pnpm dev正常，pnpm  run build 报错了。处理了下报错，服务器运行docker build -t chatgpt-web .就正常了。这点属实没想到，自己挖的坑，感谢
