### ISSUE TITLE
反向代理 自建的话有教程么？

### ISSUE THREAD

**Issue by justincnn** [Chanzhaoyu/chatgpt-web#1067]
需要什么样的条件，第三方的总觉得有点不大放心，而且怕哪天突然停服了，
很没安全感

**Comment by bigSmartisan** [comment]
> 需要什么样的条件，第三方的总觉得有点不大放心，而且怕哪天突然停服了， 很没安全感

点第一个反向代理提供者查看他的仓库，找到v4那个仓库，就是他开源的反向代理。

**Comment by jurieo** [comment]
https://hub.docker.com/r/zu1k/chatgpt-reverse-proxy

**Comment by justincnn** [comment]
> > 需要什么样的条件，第三方的总觉得有点不大放心，而且怕哪天突然停服了， 很没安全感
> 
> https://github.com/acheong08/ChatGPT-Proxy-V4

这个需要plus才能用？目前还是免费版呀，

**Comment by justincnn** [comment]
> https://hub.docker.com/r/zu1k/chatgpt-reverse-proxy

感谢，这个docker有说明文件么？就一个dock，是图形化的界面？

**Comment by jurieo** [comment]
> > https://hub.docker.com/r/zu1k/chatgpt-reverse-proxy
> 
> 感谢，这个docker有说明文件么？就一个dock，是图形化的界面？

你可以先pull下来研究下。多动手吧

**Comment by justincnn** [comment]
> > > https://hub.docker.com/r/zu1k/chatgpt-reverse-proxy
> > 
> > 
> > 感谢，这个docker有说明文件么？就一个dock，是图形化的界面？
> 
> 你可以先pull下来研究下。多动手吧

在vps上pull了，但是运行不起来，如果有github就好了，还能交流

**Comment by Dragonborn123** [comment]
chatgptproxyAPI,项目名是叫这个

**Comment by TxT168** [comment]
> https://hub.docker.com/r/zu1k/chatgpt-reverse-proxy

docker运行后，访问地址出现1020错误

**Comment by xiaodou435** [comment]
> > > https://hub.docker.com/r/zu1k/chatgpt-reverse-proxy
> > 
> > 
> > 感谢，这个docker有说明文件么？就一个dock，是图形化的界面？
> 
> 你可以先pull下来研究下。多动手吧

却文档支持啊

**Comment by hua-chen-404** [comment]
https://github.com/x-dr/chatgptProxyAPI
