### ISSUE TITLE
ios手机端访问，在深色模式下，显示错乱

### ISSUE THREAD

**Issue by sk163** [Chanzhaoyu/chatgpt-web#1068]
ios手机端访问，在深色模式下，显示的有错乱问题，尤其是菜单、设置等界面

**Comment by sk163** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/2271609/229081339-da882635-cef5-41df-b159-ee2cbcd7aad2.png">

**Comment by fzucs** [comment]
我的是正常的
![sj](https://user-images.githubusercontent.com/100392795/229107128-a64a6b31-ff4e-4d49-bc5a-19661125a4e1.jpg)

**Comment by sk163** [comment]
> 

您点一下左上角的菜单再看看呢？

**Comment by fzucs** [comment]
也是正常的，目前还没有出现过问题，我用docker-compose部署的
![sj1](https://user-images.githubusercontent.com/100392795/229132840-cf188d34-174b-4717-8c8f-7a549235db4e.jpg)

**Comment by sk163** [comment]
奇怪了~我放在k8s里了，我再检查一下，多谢您~
