### ISSUE TITLE
出错时连续对话中断

### ISSUE THREAD

**Issue by zhangzq** [Chanzhaoyu/chatgpt-web#1071]
在连续对话中，如果出错（比如网络异常等各种错误），继续对话时就不会附带之前的记录了，重启一个新对话，连续对话被中断。

**Comment by koovier** [comment]
我这里出现 

undefined
[fetch failed]

**Comment by buzilong** [comment]
有人解决吗这个问题

**Comment by wangpre** [comment]
同样遇到了，要求回答1000字，中途断了，让他继续，结果他不知道上面说了啥

**Comment by x-hanzh** [comment]
TIMEOUT_MS设置的长一点，2分钟足够@wangpre
