### ISSUE TITLE
如何默认就关闭携带聊天记录的功能？

### ISSUE THREAD

**Issue by oabu** [Chanzhaoyu/chatgpt-web#1076]
如题：如何默认就关闭携带聊天记录的功能？
就是
![image](https://user-images.githubusercontent.com/20899149/229022743-1553381c-3156-493e-a086-b5050a1ceda5.png)

**Comment by guohaomeng** [comment]
参考这个试试 #742 

[怎么把连续对话的开关设置为默认关闭](https://github.com/Chanzhaoyu/chatgpt-web/issues/742)
