### ISSUE TITLE
接口改了么，今天3.31号测试时 fetch failed的了

### ISSUE THREAD

**Issue by jindc123** [Chanzhaoyu/chatgpt-web#1079]
undefined
[fetch failed]

**Comment by KaranaLJX** [comment]
我也遇到了，用代理https://bypass.duti.tech/api/conversation时报错  at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:46:15) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:443

**Comment by star2k** [comment]
+1

**Comment by liang-x-j** [comment]
+1

**Comment by jonneychyou** [comment]
+1

**Comment by MAXHONG** [comment]
+1

**Comment by antiblahblah** [comment]
> 内置代理被全球DNS污染， 修改host或者自建dns修正
> 
> ```
> 104.21.8.183 bypass.duti.tech
> ```

请问是改本机的hosts还是部署所在服务器的hosts？两者都试过了，没有效果。

**Comment by appotry** [comment]
> > 内置代理被全球DNS污染， 修改host或者自建dns修正
> > ```
> > 104.21.8.183 bypass.duti.tech
> > ```
> 
> 请问是改本机的hosts还是部署所在服务器的hosts？两者都试过了，没有效果。

修改运行chatgpt-web的服务器，个人测试可用的

**Comment by ahlkddhfklh** [comment]
fetch failed
我也是这个提示

**Comment by antiblahblah** [comment]
> > > 内置代理被全球DNS污染， 修改host或者自建dns修正
> > > ```
> > > 104.21.8.183 bypass.duti.tech
> > > ```
> > 
> > 
> > 请问是改本机的hosts还是部署所在服务器的hosts？两者都试过了，没有效果。
> 
> 修改运行chatgpt-web的服务器，个人测试可用的

没太看懂原理，如果我的域名是www.abc.com ,hosts需要添加如下行么？
104.21.8.183 www.abc.com

谢谢！

**Comment by nagaki09** [comment]
> 104.21.8.183 bypass.duti.tech

请问railway上部署的要怎么修改呀

**Comment by antiblahblah** [comment]
> > > > > 内置代理被全球DNS污染， 修改host或者自建dns修正
> > > > > ```
> > > > > 104.21.8.183 bypass.duti.tech
> > > > > ```
> > > > 
> > > > 
> > > > 请问是改本机的hosts还是部署所在服务器的hosts？两者都试过了，没有效果。
> > > 
> > > 
> > > 修改运行chatgpt-web的服务器，个人测试可用的
> > 
> > 
> > 没太看懂原理，如果我的域名是www.abc.com ,hosts需要添加如下行么？ 104.21.8.183 [www.abc.com](http://www.abc.com)
> > 谢谢！
> 
> 是的，类似这样

谢谢，请教下这是什么原理呢？把我的域名指向这个ip会不会有数据流过去的风险？

**Comment by wuzhendong123** [comment]
> 

解决了我的问题

**Comment by gygy** [comment]
> 内置代理被全球DNS污染， 修改host或者自建dns修正
> 
> ```
> 104.21.8.183 bypass.duti.tech
> ```

有效

**Comment by antiblahblah** [comment]
> > > > > 内置代理被全球DNS污染， 修改host或者自建dns修正
> > > > > ```
> > > > > 104.21.8.183 bypass.duti.tech
> > > > > ```
> > > > 
> > > > 
> > > > 请问是改本机的hosts还是部署所在服务器的hosts？两者都试过了，没有效果。
> > > 
> > > 
> > > 修改运行chatgpt-web的服务器，个人测试可用的
> > 
> > 
> > 没太看懂原理，如果我的域名是www.abc.com ,hosts需要添加如下行么？ 104.21.8.183 [www.abc.com](http://www.abc.com)
> > 谢谢！
> 
> 是的，类似这样

想起来了，程序内置了代理去cross wrap验证，懂啦，谢谢！

**Comment by hjhhr** [comment]
今天04.01号，修改了104.21.8.183 bypass.duti.tech，也是无效的，还有其他什么办法吗？

**Comment by acheong08** [comment]
- https://github.com/Chanzhaoyu/chatgpt-web/pull/1085

**Comment by acheong08** [comment]
Please update! The old domain name has been snatched before I could renew it!

**Comment by shenhuan2021** [comment]
> 今天04.01号，修改了104.21.8.183 bypass.duti.tech，也是无效的，还有其他什么办法吗？

172.67.157.165 bypass.duti.tech用这个

**Comment by acheong08** [comment]
> 172.67.157.165

This is not my IP! Someone has taken over the domain name. They might log tokens

**Comment by fbigun** [comment]
新部署的使用access token无法使用

**Comment by faithererer** [comment]
> 

我也是，按照修改host的方法，好了一会，然后又不行了报错`[request to https://bypass.duti.tech/api/conversation failed, reason: socket hang up]`

**Comment by acheong08** [comment]
Use https://bypass.churchless.tech/api/conversation

**Comment by pengfeiu** [comment]
> Use https://bypass.churchless.tech/api/conversation

请问大佬，如何自建UnofficialProxyAPI代理服务

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT-Proxy-V4
