### ISSUE TITLE
前端解析的parent_id是否有问题？

### ISSUE THREAD

**Issue by tangjiahua** [Chanzhaoyu/chatgpt-web#108]
![image](https://user-images.githubusercontent.com/34268885/220938838-7f193ef5-0be7-4e1a-994d-76b3ea071d94.png)

这部分前端代码里面的conversationOptions里面的赋值，parentMessageId为什么用data.id？

data的数据结构长这样：
![image](https://user-images.githubusercontent.com/34268885/220938486-6ea08364-011a-4ff1-a660-704a6a9afc37.png)

里面data.parentMessageId是有value的，为何会用data.id而不是data.parentMessageId赋值给parentMessageId?

**Comment by Chanzhaoyu** [comment]
你再思考下~

**Comment by tangjiahua** [comment]
请问如果对话是这样的话，user在左边，gpt在右边，

**Comment by tangjiahua** [comment]
> 你再思考下~

请问是否是这样：假设对话是这样，左边为user，右边是gpt

**Comment by Siri-Li** [comment]
是一账号多用户

**Comment by Chanzhaoyu** [comment]
不带参数的第一个提问会被标记成一个新的会话，当前返回信息的 `ID` 是下一条你发送消息的参数，也就是下一条回复的 `parentMessageID`，如此反复

**Comment by tangjiahua** [comment]
> 不带参数的第一个提问会被标记成一个新的会话，当前返回信息的 `ID` 是下一条你发送消息的参数，也就是下一条回复的 `parentMessageID`，如此反复

谢谢大佬！理解了 :D
