### ISSUE TITLE
你好，提问没有回应，知道什么原因吗？

### ISSUE THREAD

**Issue by zhangyuqing1994** [Chanzhaoyu/chatgpt-web#1081]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/26161083/229076532-9bee8ab1-c75d-41b6-8221-a13d6359d29f.png">

**Comment by fsloky** [comment]
反向代理好像崩了，我沒有改過設置本來一直正常，今天發現連接不了，應該是代理掛了。

**Comment by zhangyuqing1994** [comment]
> 设置了 apiBaseUrl ？应该是你设置错了

你好 你值得是那个地址设置错了

**Comment by zhangyuqing1994** [comment]
> 反向代理好象崩了，我没有改过设置本来一直正常，今天发现连接没了，应该是代理挂了。

和我这个一样吗？
我是docker启动的，通过nginx 80代理出去的 现在回复 就提示上述的问题

**Comment by Jesn** [comment]
今天下午崩了 ![image](https://user-images.githubusercontent.com/5728274/229086511-d2597c55-f71f-44f8-ba08-85e0495081f4.png)

**Comment by zhangyuqing1994** [comment]
![image](https://user-images.githubusercontent.com/26161083/229087063-ec004089-59ac-4125-8bce-7f76a3080bdb.png)

是配置不对吗 这里是默认的 我改成了OPENAI_API_BASE_URL: https://api.openai.com

**Comment by zhangyuqing1994** [comment]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/26161083/229087274-0164ed44-3a6e-484e-90a5-532da5de7743.png">
我修改了OPENAI_API_BASE_URL: https://api.openai.com/ 现在提示这个

**Comment by zhangyuqing1994** [comment]
FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: Invalid SOCKS proxy details were provided
 是不是这个接口又问题啊  还是我们配置不对

**Comment by Jesn** [comment]
切换一个代理地址
```
API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation
```

**Comment by zonzpoo** [comment]
能不用代理吗？
