### ISSUE TITLE
docker 打包失败

### ISSUE THREAD

**Issue by Kuyybi-fanchao** [Chanzhaoyu/chatgpt-web#1084]
小弟刚开始学习使用docker打包（笔记本操作系统为MacOS），今天在使用docker打包的时候一直在报错，查了很多地方没有找到解决方法，初步怀疑是docker环境的from不够，有知道的兄弟望不吝赐教，感谢
<img width="1080" alt="截屏2023-03-31 10 00 15" src="https://user-images.githubusercontent.com/12005368/229098103-9699446a-8699-4f10-aaf1-b02a1b4f1c4b.png">
<img width="1266" alt="截屏2023-03-31 09 58 11" src="https://user-images.githubusercontent.com/12005368/229098130-ed3bf5f3-b1e9-4516-b9a9-32b5af0c77cf.png">

**Comment by woodchen-ink** [comment]
把打包错误内容发给chatgpt，他会给你回答的

**Comment by woodchen-ink** [comment]
还有，路径不要带中文

**Comment by Kuyybi-fanchao** [comment]
> 把打包错误内容发给chatgpt，他会给你回答的

昨晚搞了一个晚上，使用chatGPT给我解决方案，但是给出的解决方案最后都没有用，docker也重装过，也没用

**Comment by Kuyybi-fanchao** [comment]
> 还有，路径不要带中文

这个我试一下哈，路径上中文的问题我倒是没有注意
