### ISSUE TITLE
刚更新2.71竟然进不去页面了，一直停留在加载页面。

### ISSUE THREAD

**Issue by melivn** [Chanzhaoyu/chatgpt-web#109]
不知道咋回事，2.71一直停留在加载页面。恢复到2.70又正常了。

**Comment by Siri-Li** [comment]
后端service没启动

**Comment by Chanzhaoyu** [comment]
你们都不用睡觉的吗

**Comment by melivn** [comment]
> 后端service没启动

我确认启动了啊，参数检查也是正确的。

**Comment by Chanzhaoyu** [comment]
清空下浏览器缓存或者用 `ctrl+f5` 强制刷新下

**Comment by L-WESLEY** [comment]
我更新到2.72也是一直加载中，按F12显示/package.json?import什么的

**Comment by Chanzhaoyu** [comment]
> 我更新到2.72也是一直加载中，按F12显示/package.json?import什么的

部署方式或者截图给我看下

**Comment by melivn** [comment]
![image](https://user-images.githubusercontent.com/52886192/221143660-b6d8a8e2-56f0-41a4-af90-51847311dca7.png)
![image](https://user-images.githubusercontent.com/52886192/221144094-d253916d-d7bf-474b-a466-f97b2931caeb.png)
我是用宝塔部署的，2.70前的版本上述设置都能正常运行。之后的版本都一直加载中。

**Comment by Chanzhaoyu** [comment]
> 

你这个运行的是开发环境吧，后面版本并没有修改环境这一块的内容哦

**Comment by L-WESLEY** [comment]
<img width="1595" alt="iShot_2023-02-24_17 50 54" src="https://user-images.githubusercontent.com/56422820/221148620-82848586-381f-4b19-9914-593c16b4e3d0.png">
<img width="1395" alt="iShot_2023-02-24_17 51 32" src="https://user-images.githubusercontent.com/56422820/221148631-faa74c9d-88db-4787-9e60-bf5d08d6408b.png">
<img width="784" alt="iShot_2023-02-24_17 51 57" src="https://user-images.githubusercontent.com/56422820/221148635-301587f9-1234-46bb-8107-1e68bc7c5012.png">

用的是宝塔进行部署。2.7.0就没有任何问题，2.7.1跟2.7.2就会一直在加载中，然后如图所示这样，不知道是哪里的问题

**Comment by melivn** [comment]
这个问题是2.71以及后续版本才发生的。

**Comment by Chanzhaoyu** [comment]
明白了，因为 `2.7.1` 之后我添加了 `packages` 中的当前版本显示，出现这个原因的情况是你们的前端代码都是运行的开发环境。

你们只需要运行 `pnpm build`，使用 `dist` 里面的文件运行网页就好了。

**Comment by L-WESLEY** [comment]
我这边构建老是报错，那我如果把setting下的vue文件显示版本的代码注释掉应该就可以了吧

**Comment by Chanzhaoyu** [comment]
> 我这边构建老是报错，那我如果把setting下的vue文件显示版本的代码注释掉应该就可以了吧

理论上是的，构建报错事你修改过代码没有通过验证吧，可以运行 pnpm build-only

**Comment by melivn** [comment]
> 我这边构建老是报错，那我如果把setting下的vue文件显示版本的代码注释掉应该就可以了吧

确实可以使用这个方法解决。已经测试成功了。不过还是希望大佬在后续版本中解决下“package.json”这个文件引用造成的问题。
