### ISSUE TITLE
提个建议，前端访问价值很慢

### ISSUE THREAD

**Issue by MAXHONG** [Chanzhaoyu/chatgpt-web#1093]
可以压缩前端吗，我看基本上加载网页出来要5秒以上，vue文件居多，首次访问有点慢，不轻快，谢谢！

**Comment by MAXHONG** [comment]
![image](https://user-images.githubusercontent.com/7971940/229159038-22505a24-7429-48d5-bada-1ff3b998001a.png)

**Comment by leealu** [comment]
> ![image](https://user-images.githubusercontent.com/7971940/229159038-22505a24-7429-48d5-bada-1ff3b998001a.png)

一样·第一次打开很慢

**Comment by luckywangxi** [comment]
这个PR解决了https://github.com/Chanzhaoyu/chatgpt-web/pull/1082

**Comment by leealu** [comment]
> 这个PR解决了#1082

移动端新建关闭的那个并没有解决~
