### ISSUE TITLE
一个聊天会话中，如果其中一个回答出现错误，之前的聊天记录就会丢失

### ISSUE THREAD

**Issue by nikissXI** [Chanzhaoyu/chatgpt-web#1094]
我调教好了bot后，后面有一个回答提了个报错，然后他就忘了之前是谁了
报错意思是只能同时有一个会话生成，我这个网页跟同事一起用，所以有这个情况
但是记录会丢失是为啥，如果有网络超时之类的报错也会丢失聊天记录
使用的是access token登录

**Comment by choury** [comment]
而且多点几次重新生成，记录也会丢失……

**Comment by 1205129045x** [comment]
同问，我用的也是access token，有时候翻墙忘记开了，问了个问题就说network error，然后之前的聊天内容他就不记得了
