### ISSUE TITLE
请教如何设置多个密码？

### ISSUE THREAD

**Issue by ikashana** [Chanzhaoyu/chatgpt-web#1096]
AUTH_SECRET_KEY要怎么添加分隔符设置多个密码，不太熟悉，折腾了一下没成功。

**Comment by LeoLeeYM** [comment]
将 ./service/src/index.ts 的
`process.env.AUTH_SECRET_KEY !== token`
修改成
`!process.env.AUTH_SECRET_KEY.split('分隔符').includes(token)`。

然后将 ./service/src/middleware/auth.ts 的
`Authorization.replace('Bearer ', '').trim() !== AUTH_SECRET_KEY.trim()`
修改成
`!AUTH_SECRET_KEY.split('分隔符').includes(Authorization.replace('Bearer ', '').trim())`

可以实现简单的分隔符多个密码。

**Comment by StruggleYang** [comment]
希望可以大佬能支持多密码AUTH_SECRET_KEY，加别名 @Chanzhaoyu 
```
AUTH_SECRET_KEY
   - user1:key1
   - user2:key2
   - user3:key3
```
并针对用户限制次数
