### ISSUE TITLE
有无相关的QQ或微信群组呀，沟通交流方便一些

### ISSUE THREAD

**Issue by webwalker** [Chanzhaoyu/chatgpt-web#1098]
RT

**Comment by imdingtalk** [comment]
开源项目最好的交流方式就是issue

**Comment by kkxs888** [comment]
![65c70073ca8cb44600207ba99638b49](https://user-images.githubusercontent.com/110708228/229993820-421a4f8e-0517-495b-92e8-571a371b3392.jpg)
