### ISSUE TITLE
无法查看api余额

### ISSUE THREAD

**Issue by fangyuan99** [Chanzhaoyu/chatgpt-web#1099]
![image](https://user-images.githubusercontent.com/62874116/229261634-231e2cb8-4119-4390-9589-425753629f9f.png)
如题，余额显示为0，但是实际上还有很多

**Comment by Timoshao** [comment]
刚看了 我的正常

**Comment by liusanp** [comment]
4月1号到期了吧

**Comment by fangyuan99** [comment]
> 4月1号到期了吧

没有啊，对话是正常的，就是余额查不到

**Comment by 52Lxcloud** [comment]
基本都是4.1过期，查询为0，但是对话还能正常使用

**Comment by 52Lxcloud** [comment]
基本都是4.1过期，查询为0，但是对话还能正常使用
![IMG_0394](https://user-images.githubusercontent.com/48159191/229264267-93493a8e-e5cc-4246-b21f-95f6c13e163f.jpeg)

**Comment by fangyuan99** [comment]
> 基本都是4.1过期，查询为0，但是对话还能正常使用 ![IMG_0394](https://user-images.githubusercontent.com/48159191/229264267-93493a8e-e5cc-4246-b21f-95f6c13e163f.jpeg)

那明天就不能用了么

**Comment by 52Lxcloud** [comment]
大几率应该是这样，或者是没法新建APi，但是账户也没额度了

**Comment by 52Lxcloud** [comment]
> > 基本都是4.1过期，查询为0，但是对话还能正常使用![IMG_0394](https://user-images.githubusercontent.com/48159191/229264267-93493a8e-e5cc-4246-b21f-95f6c13e163f.jpeg)
> 
> 那明天就不能用了



> > 基本都是4.1过期，查询为0，但是对话还能正常使用![IMG_0394](https://user-images.githubusercontent.com/48159191/229264267-93493a8e-e5cc-4246-b21f-95f6c13e163f.jpeg)
> 
> 那明天就不能用了

大几率应该是这样，或者是没法新建APi，但是账户也没额度了

**Comment by herobrine19** [comment]
https://github.com/herobrine19/openai-billing
查余额

**Comment by fangyuan99** [comment]
好像现在官方对余额信息做了加密了，看有没有大佬能逆向了
