### ISSUE TITLE
请问一下这个通过网页accesstoken的话，支不支持chatgpt plus呢

### ISSUE THREAD

**Issue by yeenjie123456** [Chanzhaoyu/chatgpt-web#110]
我这边订阅了chatgpt plus，但我不确定这个是否使用的是plus的模型（虽然好像确实没啥区别）😂

**Comment by Chanzhaoyu** [comment]
`Pllus` 比较稳定和快一点吧，怎么开的，国外信用卡？

**Comment by Siri-Li** [comment]
> `Pllus` 比较稳定和快一点吧，怎么开的，国外信用卡？


我这有会员，你拿去开发测试

**Comment by Chanzhaoyu** [comment]
> 

感谢哈，快把微信号删了，小心信息泄露。

**Comment by Chanzhaoyu** [comment]
> 

感谢哈，快把微信号删了，小心信息泄露。

**Comment by Chanzhaoyu** [comment]
@Siri-Li  我把你信息删了，不要透露微信到公共平台

**Comment by Siri-Li** [comment]
好的

**Comment by ludashi2020** [comment]
> `Pllus` 比较稳定和快一点吧，怎么开的，国外信用卡？

更新刚刚试了下，Plus有阿尔法版本可使用，输出速度快的一批，写的代码也更棒

首先在这注册虚拟信用卡账号：https://depay.depay.one/web-app/register-h5?lang=zh-cn

然后到 https://www.depay.one/?lang=zh-cn下载APP，ios无外区账号下载内测版

登录app后点左上角“申请卡”，然后选择卡片类型，Lite卡（10U开卡费），标准卡（0开卡费）需要KYC

不想传身份证的就选择Lite卡，我选择的标准卡

然后一步一步操作传身份证后大概10分钟系统会自动审核ok。

然后充值usdt再兑换成usd激活卡片，激活后卡就可以用了

登录 https://chat.openai.com/chat 日本IP和美国IP登录有开通plus权限，左下角点Plus开通

开通页面填美国的免税地址，这里可以生成：https://www.meiguodizhi.com/

我填的免税州Alaska，然后生成地址，信息挨个填上开通就行了

CVV码在app首页的CVV安全码里可以找到。

**Comment by tangjiahua** [comment]
> 

招行全币种信用卡应该可以用吧？20刀一个月可真是太贵了

**Comment by Chanzhaoyu** [comment]
如果真的有需求的话，20刀还是可以掏一掏的

**Comment by yeenjie123456** [comment]
> > 
> 
> 招行全币种信用卡应该可以用吧？20刀一个月可真是太贵了

不行，所有中国大陆发行的银行卡全部拒付

**Comment by yeenjie123456** [comment]
> > `Pllus` 比较稳定和快一点吧，怎么开的，国外信用卡？
> 
> 更新刚刚试了下，Plus有阿尔法版本可使用，输出速度快的一批，写的代码也更棒
> 
> 首先在这注册虚拟信用卡账号：https://depay.depay.one/web-app/register-h5?lang=zh-cn
> 
> 然后到 https://www.depay.one/?lang=zh-cn下载APP，ios无外区账号下载内测版
> 
> 登录app后点左上角“申请卡”，然后选择卡片类型，Lite卡（10U开卡费），标准卡（0开卡费）需要KYC
> 
> 不想传身份证的就选择Lite卡，我选择的标准卡
> 
> 然后一步一步操作传身份证后大概10分钟系统会自动审核ok。
> 
> 然后充值usdt再兑换成usd激活卡片，激活后卡就可以用了
> 
> 登录 https://chat.openai.com/chat 日本IP和美国IP登录有开通plus权限，左下角点Plus开通
> 
> 开通页面填美国的免税地址，这里可以生成：https://www.meiguodizhi.com/
> 
> 我填的免税州Alaska，然后生成地址，信息挨个填上开通就行了
> 
> CVV码在app首页的CVV安全码里可以找到。

是的我就是depay卡开的😂但是也很随缘，我觉得就是要ip好，机场ip就是不行，我用的Google one vpn反正

**Comment by ShiinaRinne** [comment]
我试了一下，不支持切模型，这里发送的消息在openai打开会显示是default model

对比legacy和default，似乎就是model的参数不一样
我尝试在代码里找了找，只看见个unofficial的啥啥api，没学过node和前后端这些，后端调试都不会开，没找到具体发送这个请求的地方xd
![image](https://user-images.githubusercontent.com/45081750/221499438-59dddb43-6e98-4e50-b89d-552636f14ce1.png)
![image](https://user-images.githubusercontent.com/45081750/221499885-7ee54607-e9b2-4e75-9c66-379050f71dd7.png)

**Comment by ShiinaRinne** [comment]
emmm好像也没必要切……default就是plus专用的(我为什么要想着去切一下legacy……)

**Comment by ShiinaRinne** [comment]
一开始我还真想着研究一下看看怎么切换，补个pr，结果还没开始就结束了

**Comment by Chanzhaoyu** [comment]
> 一开始我还真想着研究一下看看怎么切换，补个pr，结果还没开始就结束了

没关系，贡献者第一排的席位还空着好多。

**Comment by ShiinaRinne** [comment]
hhh其实我并没有专门学过前后端，只是以前和别人做网站玩的时候摸了一段时间，根据经验参照已有的代码，改点简单的东西还可以，基础知识都没有，大范围改动就有些痴人说梦了

**Comment by ShiinaRinne** [comment]
结论应该就是支持plus了，截止现在，默认情况下会使用更好的模型(default＞legacy)，但暂时不支持切换

**Comment by ludashi2020** [comment]
> 结论应该就是支持plus了，截止现在，默认情况下会使用更好的模型(default＞legacy)，但暂时不支持切换

如何使用plus订阅呢？plus有专门的assesToken吗？

**Comment by ShiinaRinne** [comment]
开通之后直接就可以了，原本的token也可直接使用

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/221559435-5c3f6797-7102-4c12-b002-bba75570fa18.png)
![image](https://user-images.githubusercontent.com/45081750/221559415-62eadcc6-5293-4813-8150-80b4eeb01d9b.png)

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/221560267-6e264194-ec14-4e5d-800b-632f119684e3.png)
但是现在发现对于一些比较长的回答好像会出错，我这里报跨域问题， 后端chat-api.xxx，前端chat.xxx，
`xxxxxx has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
`POST api/chat-process net::ERR_FAILED 504`

**Comment by yeenjie123456** [comment]
> 结论应该就是支持plus了，截止现在，默认情况下会使用更好的模型(default＞legacy)，但暂时不支持切换

那就好😂😂😂

**Comment by hnuzhoulin** [comment]
请问开通chatgpt plus的话，使用api访问是不是模型比普通用户的不一样？
比如现在普通用户直接web使用会比api访问明显模型更优秀。

还是说开通plus只是速度更快以及不需要排队？其他的都一样？

**Comment by wejudging** [comment]
> 这里

nginx怎么配置啊，我也老报 network error

**Comment by ShiinaRinne** [comment]
> nginx怎么配置啊，我也老报 network error

```
location / {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://127.0.0.1:3002;
      
      proxy_buffering off;
      chunked_transfer_encoding on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 60;
    }
```

**Comment by wejudging** [comment]
> location / {
>       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>       proxy_set_header Host $http_host;
>       proxy_redirect off;
>       proxy_pass http://127.0.0.1:3002;
>       
>       proxy_buffering off;
>       chunked_transfer_encoding on;
>       tcp_nopush on;
>       tcp_nodelay on;
>       keepalive_timeout 60;
>     }

谢谢，已解决！！！

**Comment by ShiinaRinne** [comment]
> 请问开通chatgpt plus的话，使用api访问是不是模型比普通用户的不一样？ 比如现在普通用户直接web使用会比api访问明显模型更优秀。
> 
> 还是说开通plus只是速度更快以及不需要排队？其他的都一样？

api访问的应该就是default的  https://github.com/Chanzhaoyu/chatgpt-web/issues/110#issuecomment-1446216671

以及plus有两个模型，之前是default和turbo
现在是default和legacy
![image](https://user-images.githubusercontent.com/45081750/222088549-5203b9ab-59c7-4c66-9c8d-39ea8f623322.png)
![image](https://user-images.githubusercontent.com/45081750/222088586-04a4326b-7782-4cd2-aa7c-2688c2fbf140.png)

**Comment by ShiinaRinne** [comment]
![J4$W_GFN8L(F67WTOO{`}0A](https://user-images.githubusercontent.com/45081750/225180428-bf3612a7-938c-42ef-8fd1-46120d661e0b.png)

现在有GPT4了！看来切换模型需要提上日程了√

**Comment by ShiinaRinne** [comment]
[ChatGPT-HLSL_Toon_Shading.md](https://github.com/Chanzhaoyu/chatgpt-web/files/10975163/ChatGPT-HLSL_Toon_Shading.md)

只是速度比较慢。试了下得2分钟才能生成完，不方便多次测试和调整
