### ISSUE TITLE
ChatGPTUnofficialProxyAPI(网页 accessToken) 是不是已经无法在使用了？

### ISSUE THREAD

**Issue by Timoshao** [Chanzhaoyu/chatgpt-web#1100]
GPT-4用的是accessToken 现在这种方式是不是已经无法在使用了？

**Comment by Moximxxx** [comment]
可以啊 我刚试了一下 只不过反向代理得换一下 原先那个暂时不能用了

**Comment by zytops** [comment]
只是token一两天就过期了，要换有点麻烦。

**Comment by sundi117** [comment]
> 可以啊 我刚试了一下 只不过反向代理得换一下 原先那个暂时不能用了

求一个反代地址，大佬~~

**Comment by Moximxxx** [comment]
> 你去 readme 里面看那个 社区代理 默认是第一个 你换成第二个就行

**Comment by Moximxxx** [comment]
> > 可以啊 我刚试了一下 只不过反向代理得换一下 原先那个暂时不能用了
> 
> 求一个反代地址，大佬~~

你去readme里面看那个社区代理 默认的反代是第一个 你换成第二个试一下

**Comment by sdlkhfksl** [comment]
用的好好的

**Comment by Timoshao** [comment]
> 用的好好的

大佬用的哪个代理，我用 https://api.pawan.krd/backend-api/conversation 很不稳定，十个提问7个报错

**Comment by pengfeiu** [comment]
反向代理能自己搭建

**Comment by Timoshao** [comment]
> 代理能自己搭建

大佬 指条明路 怎么搞？

**Comment by sdlkhfksl** [comment]
> 反向代理能自己搭建

有教程吗？

**Comment by ahlkddhfklh** [comment]
> > 用的好好的
> 
> 大佬用的哪个代理，我用 https://api.pawan.krd/backend-api/conversation 很不稳定，十个提问7个报错
> 

重新部署即可

**Comment by yuanyang77** [comment]
如何自已部署一个反向代理？

**Comment by Timoshao** [comment]
> 如何自已部署一个反向代理？

https://github.com/linweiyuan/go-chatgpt-api
这个开源项目 自己搭建反代使用token
