### ISSUE TITLE
请教一个问题accessToken出现一两天就失效，需要手动替换，有什么好的解决方法。我使用源码部署的。

### ISSUE THREAD

**Issue by zytops** [Chanzhaoyu/chatgpt-web#1102]
请教一个问题accessToken出现一两天就失效，需要手动替换，有什么好的解决方法。我使用源码部署的。

**Comment by hhniao** [comment]
你的accesstoken哪来的?

**Comment by hhniao** [comment]
为什么我只有apikey

**Comment by necopp** [comment]
建议使用python 定时抓取，然后在服务器上写好脚本，定时替换下，再build一下

**Comment by nikissXI** [comment]
我的用了一个月都没过期

**Comment by zqclair** [comment]
请教一下哈，accessToken部署，那个反代的是怎么弄？
