### ISSUE TITLE
vercel部署后出现这种500错误 https://vercel.com/

### ISSUE THREAD

**Issue by CallMeChou** [Chanzhaoyu/chatgpt-web#1104]
![image](https://user-images.githubusercontent.com/63540671/229267377-54e03b7a-10cd-428f-9afe-c4a5d5583446.png)

**Comment by oldfishoh** [comment]
> ![image](https://user-images.githubusercontent.com/63540671/229267377-54e03b7a-10cd-428f-9afe-c4a5d5583446.png)
> 

解决了吗 我也是同样的问题

**Comment by roboger** [comment]
一样 解决吗

**Comment by roboger** [comment]
一样 没有解决，
