### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by zrmomo** [Chanzhaoyu/chatgpt-web#1105]
undefined
[request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 108.160.165.212:443]
请问 本地部署测试出现这个回复 是啥原因呢QAQ

**Comment by hhniao** [comment]
要梯子, 你有梯子吗?

**Comment by codePigPig** [comment]
我开了魔法，使用java代码访问api也可以，但是用这个chatgpt-web，也会出现connect ETIMEDOUT，并且目前不知道为什么讷，希望指定下，谢谢
