### ISSUE TITLE
gpt-4模型调用不了，已经开通了Plus

### ISSUE THREAD

**Issue by Mpynl** [Chanzhaoyu/chatgpt-web#1112]
undefined
[ChatGPT error 404: {
"error": {
"message": "The model: gpt-4 does not exist",
"type": "invalid_request_error",
"param": null,
"code": "model_not_found"
}
}
]

**Comment by soapmancn** [comment]
作者都没说支持GPT4 😄

**Comment by soapmancn** [comment]
[你可以看看这个项目，不光支持了GPT-4,](https://github.com/n3d1117/chatgpt-telegram-bot) DALL·E和Whisper模型也支持

**Comment by pzcn** [comment]
开通plus只是在官方网页上能用，api还是要申请进入白名单的。而且这个项目是支持gpt4的

**Comment by chenjibin** [comment]
你的openai账号没有拿到gpt4使用的权限，得排队等待官网给你授权才行

**Comment by linyu0219** [comment]
> 

这个是api的gpt4 楼主
想要的是plus接口的gpt4

**Comment by linyu0219** [comment]
> [你可以看看这个项目，不光支持了GPT-4,](https://github.com/n3d1117/chatgpt-telegram-bot) DALL·E和Whisper模型也支持

这个是api接口的gpt4，楼主需要的是plus的gpt4。 我也想要
