### ISSUE TITLE
充值plus后还是同样问题

### ISSUE THREAD

**Issue by Graypango** [Chanzhaoyu/chatgpt-web#1117]
undefined
[ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": null
}
}
]

**Comment by salary300w** [comment]
是api余额没有了 一般是有效期到了

**Comment by WackyGem** [comment]
注意下，免费配额到期了，即使是升级到Plus，  api仍然是不能使用的，我只能自己重新注册了个账户再单独升级到plus

**Comment by Graypango** [comment]
好的 非常感谢！！！

**Comment by bzbwqz** [comment]
绑卡没找对地方,去platform.openai.com里面billing绑卡，API就可以用。
ChatGPT plus和API的账号一样，但使用场景不同。
