### ISSUE TITLE
关于代码块的markdown渲染

### ISSUE THREAD

**Issue by AJHIAUNncnfbg** [Chanzhaoyu/chatgpt-web#112]
![image](https://user-images.githubusercontent.com/120219591/221070236-5e2dc2fe-2a4b-4885-9fe9-f8fb3d1a8ae1.png)

代码块没有渲染

**Comment by Chanzhaoyu** [comment]
`2.7.2` 已修复

**Comment by Chanzhaoyu** [comment]
<img width="865" alt="dog" src="https://user-images.githubusercontent.com/24789441/221118891-45cc7d4f-535f-4186-98ed-6e11a9400410.png">

**Comment by Chanzhaoyu** [comment]
<img width="854" alt="c" src="https://user-images.githubusercontent.com/24789441/221119753-03defc0b-27d7-4d07-ae19-09ddf5cdf0fb.png">
