### ISSUE TITLE
头像图片修改

### ISSUE THREAD

**Issue by Nycnz1314** [Chanzhaoyu/chatgpt-web#1121]
请问对话框里人物的头像怎么修改啊，我是小白，有什么简单方法吗

**Comment by WanXi7634** [comment]
你可以上传一张图片到图床里，然后复制图床中的链接再替换一下头像就行了。

**Comment by qingci2024** [comment]
img里面改就好了

**Comment by Cp0204** [comment]
重复问题，
![you-are-not-prepared](https://user-images.githubusercontent.com/5239753/229327758-1295d127-ce73-490c-af33-6b5686f9d1ef.png)
