### ISSUE TITLE
mongo

### ISSUE THREAD

**Issue by cssjidi** [Chanzhaoyu/chatgpt-web#1124]
<img width="444" alt="image" src="https://user-images.githubusercontent.com/8515692/229298737-5d3f860b-2ec0-4903-82e2-bd9833f3dc0f.png">
mongo.ts不加dotenv.config()就会导致获取不了MONGODB_URL

**Comment by aohun** [comment]
请问这个dotenv.config()要添加到哪里？

**Comment by aohun** [comment]
我在mongo.ts中添加如下const dotenv = require('dotenv');
dotenv.config()

**Comment by cssjidi** [comment]
> 
我加了就不会，可能你没有重启把，npm run dev我这边会运行不了，直接黑屏没任何提示，npm start需要停了再运行
