### ISSUE TITLE
跪求增加请求队列功能

### ISSUE THREAD

**Issue by nikissXI** [Chanzhaoyu/chatgpt-web#1126]
搭了一个跟几个同事一起用，但是如果另一个人在生成回答就会出现如图的报错，可以弄一个请求队列吗，让它按顺序一个个处理，最好就加一个小提示，前面还有多少个请求在处理（就是告诉使用者在排队），就不要返回报错了
<img width="902" alt="638318e2b89a00db2ba6df4532222d1" src="https://user-images.githubusercontent.com/31379266/229301505-0156429b-57df-4caf-8f02-40c1b67a911b.png">

**Comment by Jxells** [comment]
同求
