### ISSUE TITLE
开源的 Java 后台以及前端管理端界面

### ISSUE THREAD

**Issue by hncboy** [Chanzhaoyu/chatgpt-web#1127]
项目目前基于群主发布 2.10.8 版本前端代码。将原本 node 的改为 Java 后台实现。实现了基于 AccessToken 和 ApiKey 的流式对话。管理后台目前只提供了基本的查询功能，查看消息列表、敏感词列表、限流列表、聊天室列表。

Java 后台代码：https://github.com/hncboy/chatgpt-web-java
管理端代码：https://github.com/hncboy/chatgpt-web-admin

**Comment by AlwaysZmx** [comment]
666

**Comment by mcqnby** [comment]
大佬牛批！

**Comment by xueguizheng** [comment]
> 项目目前基于群主发布 2.10.8 版本前端代码。将原本 node 的改为 Java 后台实现。实现了基于 AccessToken 和 ApiKey 的流式对话。管理后台目前只提供了基本的查询功能，查看消息列表、敏感词列表、限流列表、聊天室列表。
> 
> Java 后台代码：https://github.com/hncboy/chatgpt-web-java 管理端代码：https://github.com/hncboy/chatgpt-web-admin

哇草，大佬牛逼！！！！

**Comment by huangfengjing** [comment]
厉害，重要的是开源精神可嘉
