### ISSUE TITLE
各位大佬。GPT3.5现在一分钟只能调用60次吗？

### ISSUE THREAD

**Issue by zichen-fujianwangluo** [Chanzhaoyu/chatgpt-web#1128]
经常显示
Rate limit reached for default-gpt-3.5-turbo in organization org-pDONw0vsbNExgP2REsop5Ewz on requests per min. Limit: 60 / min. Please try again in 1s. Contact support@openai.com if you continue to have issues
这个错误 各位大佬有解决的方法吗？
这个是通过什么来判断调用次数的 KEY？ IP？
我这边免费开放的使用用户居多 所以经常出现此错误 大意就是GPT3.5一分钟只能调用60次

**Comment by Ftrybe** [comment]
绑卡

**Comment by zichen-fujianwangluo** [comment]
> 绑卡

都是绑卡的账号 不知道什么情况 上个月还好好的 这个月就出现这个问题
