### ISSUE TITLE
使用railway部署，TypeError: fetch failed，这个错误，到底该怎么改呀

### ISSUE THREAD

**Issue by zhouwei713** [Chanzhaoyu/chatgpt-web#1131]
POST https://bypass.duti.tech/api/conversation {
body: {
action: 'next',
messages: [ [Object] ],
model: 'text-davinci-002-render-sha',
parent_message_id: '1c1d35b7-6cba-4290-a45c-d5b51517ae65'
},
headers: {
Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJyb2RnZXJlbGJlcnQ4ODM1QG91dGxvb2suY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsidXNlcl9pZCI6InVzZXItdlliRFMyOUZTQmRzSndjSUFBVW1DQ1RWIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJhdXRoMHw2M2Y2MDQ3MDFkYmQ1YzBmYWU2MDIzZGEiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjgwMzA1NjQ1LCJleHAiOjE2ODE1MTUyNDUsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.ylTgmwcsLMePt467-Y-99mOapSQqR6M2RfiGfnmJN4XXMdk-PPUJNdMQBgafGFj82x5k1NazzruS4LGNa98DefL0W5VJlLtvbAvhq1F_vVMVCCqZG2GRnSEldG0os05G3lTltCtcgNemEwyE4TWbh0FcdvkpZI5xMcGgWc-lB7aQVrZ1Bl1PZhd6dBh3WO6_6TWpMf-XNv5G4YcgZnBjmpo-S-HMBMkNFwLw7AeBhMSnxdH-_6y0IWgzxyEYuhB9L9MLk-z8QU_-QdMu4Xiuq-KwJiQKmB2dzX72GekMJDp0Ezcb5ACB2LMIxDQ8Qthas9SVq3M4GMMN7GIwsR7FDQ',
Accept: 'text/event-stream',
'Content-Type': 'application/json'
}
}
TypeError: fetch failed
at Object.fetch (node:internal/deps/undici/undici:11413:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:46:15) {
cause: Error: connect ECONNREFUSED 127.0.0.1:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 443
}
}
 ELIFECYCLE  Command failed.

**Comment by wyg-lucas** [comment]
同问，我也遇到了这个问题

**Comment by zhouwei713** [comment]
好像知道原因了，先关闭

**Comment by gonyua** [comment]
你怎么解决的，我用docker-compose方式部署，网页输入问题也一直报TypeError: fetch failed
