### ISSUE TITLE
请问最低内存配置是多少

### ISSUE THREAD

**Issue by dee1024** [Chanzhaoyu/chatgpt-web#1134]
没用过这个框架，请问最低内存配置是多少，为什么我在微软Azure云的1G内存虚拟机上跑不起来，剩余内存一下清零了，系统卡死。

**Comment by doveppp** [comment]
我也是Azure的1h1g  用docker可以跑起来

**Comment by dee1024** [comment]
> 

请问你用的也是体验的最低配置吗？

**Comment by doveppp** [comment]
> 

对

**Comment by dee1024** [comment]
> 
> chatgpt-web@2.10.8 type-check /app
> vue-tsc --noEmit
> chatgpt-web@2.10.8 build-only /app
> vite build
vite v4.2.0 building for production...
transforming...
一直卡在这里10几分钟不动，cpu、内存都基本被用满了，请教下可能是什么原因呢

**Comment by doveppp** [comment]
不用build  直接pull镜像运行就行

**Comment by dee1024** [comment]
> 

谢谢耐心解答。docker不太熟悉，最后一个问题：
我查看本地镜像仓库如下：
`docker images
REPOSITORY                 TAG          IMAGE ID       CREATED      SIZE
chenzhaoyu94/chatgpt-web   latest       3fea392d9bf8   2 days ago   243MB`
然后执行启动命令：
`docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=xxxxxxxxxxx   chatgpt-web`
但是出现异常：
`Unable to find image 'chatgpt-web:latest' locally
docker: Error response from daemon: pull access denied for chatgpt-web, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`
请问是什么问题呢？

**Comment by doveppp** [comment]
docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=xxxxxxxxxxx  3fea392d9bf8   
或者
docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=xxxxxxxxxxx  chenzhaoyu94/chatgpt-web

**Comment by dee1024** [comment]
> docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=xxxxxxxxxxx 3fea392d9bf8 或者 docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=xxxxxxxxxxx chenzhaoyu94/chatgpt-web

可以了，thx。
