### ISSUE TITLE
BAI CHAT  提供错误的API密钥 | Incorrect API key provided

### ISSUE THREAD

**Issue by KevinGeneration** [Chanzhaoyu/chatgpt-web#1135]
各位今天有遇到这个问题吗，我周五 2023.3.31还是一切正常的，今天一早起来用这个就显示错误了，请问是什么原因，是否有措施可以解决这个问题

**Comment by zhuxindong** [comment]
账号被OpenAI封了而已

**Comment by KevinGeneration** [comment]
我身边很多人都是今天被封了，是BAI CHAT本身的API出了问题吧？ 我用CHAT GPT或者其他GPT都是OK的

**Comment by lyp88997** [comment]
一样的，我用cloudflare搞的反代   今天下午就封了

**Comment by zhuxindong** [comment]
> 我身边很多人都是今天被封了，是BAI CHAT本身的API出了问题吧？ 我用CHAT GPT或者其他GPT都是OK的

bai chat是啥？不都是调的OpenAI接口吗？

**Comment by sdlkhfksl** [comment]
没有被封，我可以官方网页登录，但是用搭建网站也报错
