### ISSUE TITLE
可不可以添加一个公告功能

### ISSUE THREAD

**Issue by doveppp** [Chanzhaoyu/chatgpt-web#1137]

**Comment by Dragonborn123** [comment]
类似官网那种提示还是弹窗公告？可以自己加哇

**Comment by luckywangxi** [comment]
Cf app啊

**Comment by doveppp** [comment]
我不太懂前端  可否简单告知下如何操作？

**Comment by fzucs** [comment]
直接问chatgpt，让它帮你写
![image](https://user-images.githubusercontent.com/100392795/229337152-aeb9f7ad-8850-4dc5-9c21-602971faff9b.png)
