### ISSUE TITLE
查询余额功能好像失效了

### ISSUE THREAD

**Issue by AlwaysZmx** [Chanzhaoyu/chatgpt-web#1138]
在设置里没法查询余额了

**Comment by Dragonborn123** [comment]
接口问题

**Comment by chenxinstepone** [comment]
> 接口问题

有解决的办法吗

**Comment by devyujie** [comment]
估计官方换接口了

**Comment by mcqnby** [comment]
是的，好像现在查不到余额了

**Comment by quzard** [comment]
接口是同一个，但是不允许用api key来调用这个接口了

"Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret."

**Comment by chenxinstepone** [comment]
还有一个很奇怪的现象，我今天用备用的gmail账号申请了一个OpenAI的账号，申请成功了，但是显示出来赠送的api为0元，但是gpt-3.5的端口和whisper的端口都是正常调用的，不知道是什么情况，或者是他们今天进行了调试出bug了。
<img width="733" alt="未命名1680420155" src="https://user-images.githubusercontent.com/36954700/229338717-43e4060f-48f9-4f48-a5a8-2beceaf2460a.png">

**Comment by herobrine19** [comment]
https://github.com/herobrine19/openai-billing
目前还可以用这个接口

**Comment by cd547** [comment]
难道 开发用的api key不能作为验证了?必须用sess-开头的会话级别的key？

**Comment by mcqnby** [comment]
> 难道 开发用的api key不能作为验证了?必须用sess-开头的会话级别的key？

Ref: #1152

**Comment by TsingYi1263** [comment]
> 
余额显示0说明你用来注册的手机号曾经注册过不送免费额度，但apikey还能用 不知道为什么

**Comment by chenxinstepone** [comment]
> > 
> 
> 余额显示0说明你用来注册的手机号曾经注册过不送免费额度，但apikey还能用 不知道为什么

过了那一天就显示正常了，还是5的免费额度

**Comment by herobrine19** [comment]
可以直接用这个查
https://github.com/herobrine19/openai-billing

**Comment by chenxinstepone** [comment]
> 可以直接用这个查 https://github.com/herobrine19/openai-billing

谢谢，之前已经在用了
