### ISSUE TITLE
交流一下用ChatGPTUnofficialProxyAPI的问题

### ISSUE THREAD

**Issue by gefeiyanga** [Chanzhaoyu/chatgpt-web#114]
#### 在ChatGPTUnofficialProxyAPI，accessToken的前提下遇到了一些问题:

- accessToken 存在过期时间，过期了难道要手动登录重新获取后更新？
- 一个accessToken同一时间只能响应一个问题，如何处理并发呢？多个accessToken又无法继承上下文，意味着一定程度上，为了并发，需要accessToken数量成线性增加，太浪费了。
- 想要一定程度的最大利用一个accessToken，可以“错峰”，“一个一个”问问题，但是只有在新问题响应超时后，才知道这个accessToken刚刚在响应别的问题（这个和官网不一样，官网立刻就会告知同一段时间只能问一个问题）。

**在以上前提下，关于并发，想听听大家意见**

**Comment by Chanzhaoyu** [comment]
充钱解决一切问题，用 `accessToken` 限制过多，只能自用玩一玩，保持连接的话过期时间还是很可观的。

**Comment by gefeiyanga** [comment]
> 充钱解决一切问题，用 `accessToken` 限制过多，只能自用玩一玩，保持连接的话过期时间还是很可观的。

plus账户可以解决“同一时间只能响应一个问题”的问题？

**Comment by Chanzhaoyu** [comment]
> > 充钱解决一切问题，用 `accessToken` 限制过多，只能自用玩一玩，保持连接的话过期时间还是很可观的。
> 
> plus账户可以解决“同一时间只能响应一个问题”的问题？

响应不知道，反应更快和稳定那是肯定的

**Comment by gefeiyanga** [comment]
> 

![image](https://user-images.githubusercontent.com/30728843/221121785-4e0e7a40-1911-43fd-8172-ca6f821092b4.png)
应该不能

**Comment by zzb16888** [comment]
plus也不可以多线路我记得

**Comment by ludashi2020** [comment]
> 充钱解决一切问题，用 `accessToken` 限制过多，只能自用玩一玩，保持连接的话过期时间还是很可观的。

能不能增加一个用户使用自己的邮箱和账号登录，这样他们使用自己的`accessToken`，是不是可以解决这个问题呢？

**Comment by gefeiyanga** [comment]
> plus也不可以多线路我记得

是的，刚刚确认了，不行

**Comment by gefeiyanga** [comment]
> > 充钱解决一切问题，用 `accessToken` 限制过多，只能自用玩一玩，保持连接的话过期时间还是很可观的。
> 
> 能不能增加一个用户使用自己的邮箱和账号登录，这样他们使用自己的`accessToken`，是不是可以解决这个问题呢？

这个有的讨论了，在某些方面确实解决了并发问题，但是前提是他有账号

**Comment by Chanzhaoyu** [comment]
> > > 充钱解决一切问题，用 `accessToken` 限制过多，只能自用玩一玩，保持连接的话过期时间还是很可观的。
> > 
> > 
> > 能不能增加一个用户使用自己的邮箱和账号登录，这样他们使用自己的`accessToken`，是不是可以解决这个问题呢？
> 
> 这个有的讨论了，在某些方面确实解决了并发问题，但是前提是他有账号

那个 python 项目实现了，但是没有透露方法。去用那个项目做后端呗。

**Comment by gefeiyanga** [comment]
> > > > 充钱解决一切问题，用 `accessToken` 限制过多，只能自用玩一玩，保持连接的话过期时间还是很可观的。
> > > 
> > > 
> > > 能不能增加一个用户使用自己的邮箱和账号登录，这样他们使用自己的`accessToken`，是不是可以解决这个问题呢？
> > 
> > 
> > 这个有的讨论了，在某些方面确实解决了并发问题，但是前提是他有账号
> 
> 那个 python 项目实现了，但是没有透露方法。去用那个项目做后端呗。

python的和node的一样吧，用邮箱登录，然后拿accessToken，这也不能解决多用户的问题吧

**Comment by tangjiahua** [comment]
accessToken 存在过期时间，过期了难道要手动登录重新获取后更新？
一个accessToken同一时间只能响应一个问题，如何处理并发呢？多个accessToken又无法继承上下文，意味着一定程度上，为了并发，需要accessToken数量成线性增加，太浪费了。
想要一定程度的最大利用一个accessToken，可以“错峰”，“一个一个”问问题，但是只有在新问题响应超时后，才知道这个accessToken刚刚在响应别的问题（这个和官网不一样，官网立刻就会告知同一段时间只能问一个问题）。
