### ISSUE TITLE
回复无法携带上下文

### ISSUE THREAD

**Issue by jwdstef** [Chanzhaoyu/chatgpt-web#1140]
![~ C)NS5UL(M`3WQZ)IK7XGE](https://user-images.githubusercontent.com/3320789/229330708-61c80a6a-601e-4ddc-8283-0db41078d812.jpg)

最新版本为什么开着上下文 怎么继续的时候 没有接上
![4{R4` A@X9PX4{3G7U{9MWP](https://user-images.githubusercontent.com/3320789/229330651-0a36cb99-14cc-4e72-b7a2-cff3530c5edb.png)
延迟已经设置为0了

**Comment by legical** [comment]
使用docker搭建的，也遇到了这种情况

**Comment by baotangyin** [comment]
我是把超时设置成2分钟以上，120000就好了

**Comment by mason0510** [comment]
不起作用

**Comment by rocket2023** [comment]
2.10.8开始，到同步2.10.9为止。 api方式依然不带上下文，access_token正常携带上下文
