### ISSUE TITLE
使用ACCESS_TOKEN会被封号吗

### ISSUE THREAD

**Issue by jeff-hong** [Chanzhaoyu/chatgpt-web#1141]

**Comment by iamflowerdog** [comment]
我身边三位朋友都在用 ACCESS_TOKEN，暂时都没有被封号

**Comment by krxiaoyu** [comment]
我发现用AWS的vps都无法正常访问chatgpt，请问你们是用谁家的vps，或者socks5代理

**Comment by Fugitive844** [comment]
> 我发现用AWS的vps都无法正常访问chatgpt，请问你们是用谁家的vps，或者socks5代理

买腾讯或者阿里云的轻量级服务器，32块钱一个月。选美国节点

**Comment by krxiaoyu** [comment]
收到，感谢
