### ISSUE TITLE
请教下关于模型的问题

### ISSUE THREAD

**Issue by guoang** [Chanzhaoyu/chatgpt-web#1143]
作者在 README 里提到：

> ChatGPTAPI 使用 gpt-3.5-turbo-0301 通过官方OpenAI补全API模拟ChatGPT（最稳健的方法，但它不是免费的，并且没有使用针对聊天进行微调的模型）

我想知道现在直接通过 [chat.openai.com/chat](chat.openai.com/chat) 访问的话，它背后的模型不是 gpt-3.5-turbo 吗？

https://platform.openai.com/docs/models/gpt-3-5 这份文档里提及的所有 GPT-3.5 的模型看起来没有比 gpt-3.5-turbo 更优的了，所以  [chat.openai.com/chat](chat.openai.com/chat) 使用的模型实际上并没有在 API 开放？而是作者提到的其他 “针对聊天进行微调的模型”？有名字吗？

**Comment by hughli-git** [comment]
chat.openai.com/chat 页面打开时，有个请求是 `https://chat.openai.com/backend-api/models` ，返回值为（我的是免费版，没有充Plus）：
```
{"models":[{"slug":"text-davinci-002-render-sha","max_tokens":4097,"title":"Turbo (Default for free users)","description":"The standard ChatGPT model","tags":[],"qualitative_properties":{}}]}
```
同样，对话的API，发给 `https://chat.openai.com/backend-api/conversation` 请求的结构：
```
{"action":"next","messages":[{"id":"*********","author":{"role":"user"},"content":{"content_type":"text","parts":["*********"]}}],"parent_message_id":"*********","model":"text-davinci-002-render-sha","timezone_offset_min":-480}
```

所以ChatGPT免费网页用的模型是 `text-davinci-002-render-sha` , 从一个评测[https://github.com/saschaschramm/chatgpt](https://github.com/saschaschramm/chatgpt) 看起来，不如 `gpt-3.5-turbo`，但差不多。
Plus用的模型是 `text-davinci-002-render-paid`

**Comment by guoang** [comment]
懂了，感谢

> chat.openai.com/chat 页面打开时，有个请求是 `https://chat.openai.com/backend-api/models` ，返回值为（我的是免费版，没有充Plus）：
> 
> ```
> {"models":[{"slug":"text-davinci-002-render-sha","max_tokens":4097,"title":"Turbo (Default for free users)","description":"The standard ChatGPT model","tags":[],"qualitative_properties":{}}]}
> ```
> 
> 同样，对话的API，发给 `https://chat.openai.com/backend-api/conversation` 请求的结构：
> 
> ```
> {"action":"next","messages":[{"id":"*********","author":{"role":"user"},"content":{"content_type":"text","parts":["*********"]}}],"parent_message_id":"*********","model":"text-davinci-002-render-sha","timezone_offset_min":-480}
> ```
> 
> 所以ChatGPT免费网页用的模型是 `text-davinci-002-render-sha` , 从一个评测https://github.com/saschaschramm/chatgpt 看起来，不如 `gpt-3.5-turbo`，但差不多。 Plus用的模型是 `text-davinci-002-render-paid`
