### ISSUE TITLE
部署到云服务器 500

### ISSUE THREAD

**Issue by yigeimuya** [Chanzhaoyu/chatgpt-web#1144]
应该是后端接口没填对，请问各位大佬这里应该填什么？假设我的域名是www.abc.com的话，VITE_GLOB_API_URL的值应该是：
http://www.abc.com吗？还是 www.abc.com/api还是什么？

![image](https://user-images.githubusercontent.com/129144058/229339723-edc2c6b3-036c-4169-a4e2-875431141e0a.png)

**Comment by dallascao** [comment]
同问

**Comment by mcqnby** [comment]
同问

**Comment by oldfishoh** [comment]
同问 咋设置都是500啊

**Comment by 3339588491** [comment]
the same question
