### ISSUE TITLE
在服务器上装了vpn，不设置代理用不了

### ISSUE THREAD

**Issue by M41698K** [Chanzhaoyu/chatgpt-web#1146]
在服务器上装了vpn，不设置代理用不了，但是设置代理的话，vpn也没有告诉用什么代理和端口号，如何解决？

**Comment by M41698K** [comment]
已经解决

**Comment by TuringWWS** [comment]
请问怎么解决？遇到同样的问题

**Comment by M41698K** [comment]
> 请问怎么解决？遇到同样的问题

主要原因就是容器里面的网络跟外边的网络隔离了，可以让容器里面的网络可以用到系统本身的网络，network_mode: "host"，这样设置，就可以了。
