### ISSUE TITLE
关于提示盗版接口的问题

### ISSUE THREAD

**Issue by yxandam** [Chanzhaoyu/chatgpt-web#1147]
您好，我使用自己的key部署后，提示，                             非常抱歉地告诉您，您现在正在访问的是盗用接口的网站，该网站没有得到授权使用。我们强烈建议您前往我们的来源网站，它是免费的，而且没有使用限制。请访问以下网址以获得更好的使用体验: 我们希望您在使用上述推荐网站时能够享受到更好的服务和保障。 请问这个如何修改呢，或者大家遇到过吗

**Comment by Chanzhaoyu** [comment]
这不是本项目的代码，你用的第三方一件脚本吧。

**Comment by yxandam** [comment]
好的，感谢
