### ISSUE TITLE
请问如何修改403的提示文字和图片？谢谢

### ISSUE THREAD

**Issue by leealu** [Chanzhaoyu/chatgpt-web#1148]
就是设定密码了以后那个页面

**Comment by Chanzhaoyu** [comment]
`src/views/chat/Permission.vue`

**Comment by Chanzhaoyu** [comment]
> > `src/views/chat/Permission.vue`
> 
> 你确定这个文件能改那个图片吗？我没找到改的地方·4033个字都没找到~

图片是 `svg` 文件，在 `icons` 文件夹

**Comment by leealu** [comment]
> > > `src/views/chat/Permission.vue`
> > 
> > 
> > 你确定这个文件能改那个图片吗？我没找到改的地方·4033个字都没找到~
> 
> 图片是 `svg` 文件，在 `icons` 文件夹

好的我找找，谢谢，那个未经授权的字还有上面的403提示，在哪里改呢

**Comment by Chanzhaoyu** [comment]
> 

搜索 `unauthorizedTips` ，删除直接用中文也行

**Comment by leealu** [comment]
> unauthorizedTips

unauthorizedTips这个在哪里，我直接删了unauthorizedTips还是{{ $t('common.unauthorizedTips') }}整个删了？这个设定值如果不删除在哪里修改
