### ISSUE TITLE
请教一个问题，为何message数据要放到localstorage，这样不会无限制增加导致超过限制吗

### ISSUE THREAD

**Issue by fucheng830** [Chanzhaoyu/chatgpt-web#1154]
![image](https://user-images.githubusercontent.com/9291065/229364942-ebdb119b-bdb1-4e8c-b821-1b1a4205ecb0.png)
另外打字机效果是不是有更好的实现呢？

**Comment by ourcss** [comment]
朋友你自建以后，首次访问慢吗？大约几秒呢
