### ISSUE TITLE
继续无法联系上下文，已选择上下文模式

### ISSUE THREAD

**Issue by Suaig** [Chanzhaoyu/chatgpt-web#1157]
发生条件：当上一个输出到极限之后自动停止，再叫他继续的时候无法继续。问有什么需要帮助。

**Comment by baotangyin** [comment]
试试把TIMEOUT_MS 超时参数设置成两分钟以上看看

**Comment by youzeliang** [comment]
貌似我也遇到了这个问题。用着用着。然后就不会去联系上下文了
