### ISSUE TITLE
请求报undefined：443，求助

### ISSUE THREAD

**Issue by Ser-MingShao** [Chanzhaoyu/chatgpt-web#1158]
![image](https://user-images.githubusercontent.com/67584847/229391650-7833888a-6e7d-49ee-82d9-a62bb7d0982d.png)
用OPENAI_API_KEY请求也是443
![image](https://user-images.githubusercontent.com/67584847/229391720-c798191a-88cb-4747-835a-e488f051049b.png)
OPENAI_ACCESS_TOKEN请求也是443
![image](https://user-images.githubusercontent.com/67584847/229391820-7b117db4-8c6d-49ba-998b-8996123516c9.png)

**Comment by Saktawdi** [comment]
部署服务器走没走代理？国内网络用不了openAI的

**Comment by Ser-MingShao** [comment]
我在window本地开了代理的，只可能是配置文件没配置好，但是配置太多了又不知道哪里出了问题

**Comment by hjkl950217** [comment]
可能是网络问题，我部署在railway上面的，有时都会遇到这个情况。重新部署一下又好了
