### ISSUE TITLE
API余额今天不能显示了，是我个例？

### ISSUE THREAD

**Issue by cd547** [Chanzhaoyu/chatgpt-web#1160]
在server下的对应文件有个fetchBalance函数里面添加了console.log,查看了一下railway日志报错：AxiosError: Request failed with status code 403

**Comment by cvpv** [comment]
是的，该接口目前无法查询

**Comment by cvpv** [comment]
#1138

**Comment by luckywangxi** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/pull/1152
已解决
