### ISSUE TITLE
项目推荐

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#1161]
项目的初衷只是为了让自己能够跳过限制使用 `ChatGPT`，并且打击一下那些一个页面输入框就拿去卖钱的狗屎项目，却受到超出预期的关注。总结起来，也许只是因为一个 “早” 字。

感谢 [@transitive-bullshit] 和 [@acheong08] 的很棒的项目，因为有你们才有这个项目的开始。

感谢所有赞助者的慷慨。

感谢所有贡献者的奉献。

短短几个月的时间，从 `accessToken` 和 `gpt-3` 到现在的 `gtp-3.5-tubo` 和 `gpt-4`，经历了翻天覆地的变化。这个项目也许也完成了它早期的目的。

繁花似锦，花开锦簇。如果你使用纯 `API` 的方式，你可能更应该看看下面这些更优秀的仓库：

- [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web) by [@Yidadaa]
- [chatgpt-demo](https://github.com/ddiu8081/chatgpt-demo) by [@ddiu8081]
- [chatgpt-vercel](https://github.com/ourongxing/chatgpt-vercel) by [@ourongxing]
- [chatbot-ui](https://github.com/mckaywrigley/chatbot-ui) by [@mckaywrigley]
- [chatgpt-plus](https://github.com/zhpd/chatgpt-plus) by [@zhpd]

关注我的抖音号～ 🤣

<img src="https://user-images.githubusercontent.com/24789441/229400196-bf4db830-fb89-491a-9de8-ebf3590c53b7.jpg" style="width: 200px" />

**Comment by transitive-bullshit** [comment]
Amazing work, @Chanzhaoyu 🔥 

Are you part of our [ChatGPT Hackers Discord](https://www.chatgpthackers.dev) btw? @acheong08 and I are admins over there && would love to have you join us 😄

**Comment by Chanzhaoyu** [comment]
P.S. 有个小小的请求，如果可以的话可以帮忙关注下我的抖音账号吗，有时候可能下班想开个前端直播玩一玩，但是粉丝数量不够，开不了。

<img src="https://user-images.githubusercontent.com/24789441/229400196-bf4db830-fb89-491a-9de8-ebf3590c53b7.jpg" style="width: 200px" />

**Comment by Chanzhaoyu** [comment]
> Amazing work, @Chanzhaoyu 🔥
> 
> Are you part of our [ChatGPT Hackers Discord](https://www.chatgpthackers.dev) btw? @acheong08 and I are admins over there && would love to have you join us 😄

I just joined 🤪

**Comment by ventusoon** [comment]
I love you~！

**Comment by huaccf** [comment]
已经关注大佬了

**Comment by wejudging** [comment]
已经关注大佬了！！！

**Comment by Cp0204** [comment]
dongguan 老铁，有空吃饭

**Comment by zhpd** [comment]
已经关注大佬，赞一个！这个项目也是参照你的项目摸索开发的，希望大佬帮忙推下，感谢👍  https://github.com/zhpd/chatgpt-plus

**Comment by ludashi2020** [comment]
大佬威武，感谢开源项目开发者。

**Comment by smanx** [comment]
大佬，这个项目有没有考虑过接入new bing

**Comment by ludashi2020** [comment]
> P.S. 有个小小的请求，如果可以的话可以帮忙关注下我的抖音账号吗。有时候下班想开个前端直播玩一玩，但是粉丝数量不够开不了，放心不会骚扰到你们。
> 
> ![](https://user-images.githubusercontent.com/24789441/229400196-bf4db830-fb89-491a-9de8-ebf3590c53b7.jpg)

已关注

**Comment by xywlxywl** [comment]
已经关注您，但是无法与您私信呀？

**Comment by yorunning** [comment]
作者格局真高！！

**Comment by zaiMoe** [comment]
有没有可能大家拉一起搞，上面的每个项目都看了，都有各自的优点，作为成年人，都想要

**Comment by Equim-chan** [comment]
十分感谢作者。理解这个项目存在的一些历史包袱，所以我也 [fork](https://github.com/Equim-chan/chatgpt-web) 了一份来方便自用。

主要改进：
* 上下文持久化 (通过 keyv/postgres)
* 消息编辑
* prompt 支持 markdown 渲染
* 基于 passwd 文件的多用户
* 用户维度的聊天记录持久化
* 自定义 temperature、top-p、AI 名称

**Comment by Saktawdi** [comment]
互联网正因为有你这样的大佬开源，才会更多姿多彩

**Comment by luuziiyoo** [comment]
关注了

**Comment by caiyunfan2** [comment]
其它项目虽然也不错，但是还是你的这个项目的代码架构好，很有二次开发的欲望。

**Comment by wang-xiaowu** [comment]
吃水不忘挖井人
我写了份文档，如何零成本从0到1，开发并上线一个对接了openai的机器人，希望一起学习
https://wang-xiaowu.github.io/posts/2a9d73ff/

**Comment by Ziqi-Yang** [comment]
> P.S. 有个小小的请求，如果可以的话可以帮忙关注下我的抖音账号吗。有时候下班想开个前端直播玩一玩，但是粉丝数量不够开不了，放心不会骚扰到你们。
> 
> ![](https://user-images.githubusercontent.com/24789441/229400196-bf4db830-fb89-491a-9de8-ebf3590c53b7.jpg)

自信点老哥！

**Comment by Yidadaa** [comment]
你好，我是 chatgpt-next-web 作者，能否通过我主页邮箱加微信联系一下我？

chatgpt-next-web 是受此项目影响而开始着手开发的，有很多有趣的问题，我们可以一同探讨下。

**Comment by Chanzhaoyu** [comment]
> 已经关注大佬，赞一个！这个项目也是参照你的项目摸索开发的，希望大佬帮忙推下，感谢👍 https://github.com/zhpd/chatgpt-plus

赞👍

**Comment by hanxu1355146559** [comment]
https://github.com/acheong08/EdgeGPT
这是一个很好的new bing的逆向工程项目,使用python来运行.
是否有考虑过在此前端加入一个切换到newbing的选项.
个人感觉chatgpt更偏向自己思考,newbing更偏向实时联网,资料汇总.

**Comment by fucheng830** [comment]
作者这个项目非常好，希望对这个项目感兴趣正在做二次开发的同学，可以加我微信：fucheng，一起聊一下共同解决一些问题或者对接一些商业机会，感谢大佬的贡献！

**Comment by itjohy** [comment]
请问楼主为什么本地搭建后运行发送信息提示访问失败request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 是哪里弄错了吗

**Comment by clayboby** [comment]
吃水不忘挖井人，同源商业项目，带GPT4
https://www.vivi-chat.com/#/chat
很快挺好用
关注一波公众号，应该经常有白嫖活动。也是这个开源项目加后端改的。过来谢谢。后端用的quarkus+jdk17了，最后后端比前端耗时。

**Comment by tiamohf** [comment]
我是第一个提issues的😁

**Comment by tiamohf** [comment]
想做一个聚合平台，类似POE.COM的，大家有没有项目分享

**Comment by liuliangsir** [comment]
@tiamohf cc [ChatALL](https://github.com/sunner/ChatALL)
