### ISSUE TITLE
配置环境还是报错

### ISSUE THREAD

**Issue by 110130xwq** [Chanzhaoyu/chatgpt-web#1164]
为什么我配置环境了怎么还是报错

**Comment by Chanzhaoyu** [comment]
创建一个 `service/.env` 文件，把需要的变量从 `.env.example` 复制进去。

还有，你的 `key` 暴露了。

**Comment by 110130xwq** [comment]
是在service下面创建文件吗？对于文件名有要求吗？创建好之后将service/.env.env.example里的变量copy过去就可以了吗？

**Comment by Chanzhaoyu** [comment]
是的，`README.md` 中有写。变量文件 `.env` 需要真实环境需要自己创建。`.env.example` 是示例文件。
