### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by kuoniya** [Chanzhaoyu/chatgpt-web#1167]
You exceeded your current quota, please check your plan and billing details.
调用接口是不是G了

**Comment by dashug** [comment]
api方式的话，你的额度消耗完了吧

**Comment by Chanzhaoyu** [comment]
部份 `API` 4月1日就清零了

**Comment by kuoniya** [comment]
确实我的api使用频繁，估计调整完额度之后不足了,其他账号正常
