### ISSUE TITLE
当我们自己输入带有img标签的问题的时候，会被当作图片加载

### ISSUE THREAD

**Issue by AJHIAUNncnfbg** [Chanzhaoyu/chatgpt-web#117]
![image](https://user-images.githubusercontent.com/120219591/221150873-1a96adbd-6153-447f-83a5-cf64506fa0bf.png)
![image](https://user-images.githubusercontent.com/120219591/221150897-3fdb2da5-dbe4-4971-8be8-5ca97d7a2400.png)

**Comment by AJHIAUNncnfbg** [comment]
我也是复制代码过来的时候发现的

**Comment by Chanzhaoyu** [comment]
点击左下角设置按钮查看下版本

**Comment by AJHIAUNncnfbg** [comment]
是2.7.2的
![image](https://user-images.githubusercontent.com/120219591/221151923-5c2ea7dc-dfeb-4275-a458-21d79559d716.png)

**Comment by Chanzhaoyu** [comment]
好的，感谢反馈

**Comment by Chanzhaoyu** [comment]
已修复
