### ISSUE TITLE
用Access Token部署的Railway，前一段时间好好的，后面提示 undefined [fetch failed]。重新部署问题依旧

### ISSUE THREAD

**Issue by gimgoo** [Chanzhaoyu/chatgpt-web#1173]
如题，用Access Token部署的Railway，前一段时间好好的，后面问问题，一发问题就马上提示 undefined [fetch failed]。重新部署问题依旧，更换了 Access Token 也没用

**Comment by enmoe** [comment]
我试了下，其实只需要添加个代理服务器就可以了

**Comment by sdlkhfksl** [comment]
加反代即可

**Comment by 18639522576** [comment]
> 我试了下，其实只需要添加个代理服务器就可以了

不是默认包含了代理服务器吗？

**Comment by HolmesZhao** [comment]
我自己用 cf pages 创建了一个直接就被拒绝了🤣

**Comment by evanstark** [comment]
同问，我也遇到这个问题了

**Comment by enmoe** [comment]
> > 加反代即可
> 
> 好啊，如何加反代理？我在docker-compose.yml增加了ip地址还不行 ![image](https://user-images.githubusercontent.com/15230663/230090149-020446f7-dbed-4946-994a-8ab335c125ca.png)

自建的反代过不了cloudflare的验证吧

**Comment by enmoe** [comment]
> 我自己用 cf pages 创建了一个直接就被拒绝了🤣

自建的反代过不了CF的验证吧如果用accesstoken的话

**Comment by HolmesZhao** [comment]
> 如果用accesstoken的话

所以说这个反代只能用作 api 使用对吗? accesstoken 的话必须用国外服务器做反代?
