### ISSUE TITLE
回答不是逐字显示而是等待半天后全部显示（题主没脑子没有翻到最下面的问题总结，劳烦大家了）

### ISSUE THREAD

**Issue by qizishuo** [Chanzhaoyu/chatgpt-web#1175]
大佬们问一下，我这个提问后接口总是得等半天然后全部显示答案，不是一个字一个字的逐字打印

**Comment by Fugitive844** [comment]
首页就有说明：
Q: 前端没有打字机效果？

A: 一种可能原因是经过 Nginx 反向代理，开启了 buffer，则 Nginx 会尝试从后端缓冲一定大小的数据再发送给浏览器。请尝试在反代参数后添加 proxy_buffering off;，然后重载 Nginx。其他 web server 配置同理。

**Comment by Cp0204** [comment]
> > 首页就有说明： Q: 前端没有打字机效果？
> > A: 一种可能原因是经过 Nginx 反向代理，开启了 buffer，则 Nginx 会尝试从后端缓冲一定大小的数据再发送给浏览器。请尝试在反代参数后添加 proxy_buffering off;，然后重载 Nginx。其他 web server 配置同理。
> 
> 大佬可以了太棒了你

拜托凡事先看文档，翻issues

**Comment by Hihayni** [comment]
very good

**Comment by superen7527** [comment]
都不看首页readme?高估这一届了。

**Comment by Justsenger** [comment]
现在的年轻人太急躁
