### ISSUE TITLE
Access Token部署，GPT-4回复中断

### ISSUE THREAD

**Issue by Timoshao** [Chanzhaoyu/chatgpt-web#1176]
GPT-4回复

![image](https://user-images.githubusercontent.com/108260847/229457908-0d526cd0-07a8-4115-991b-8801b1d82b09.png)
GPT-4日志
![image](https://user-images.githubusercontent.com/108260847/229458463-51cd331e-ce06-424a-8bcc-e69dc9d88e48.png)

GPT-3.5回复
![image](https://user-images.githubusercontent.com/108260847/229458087-f68bd615-c8e9-45ac-a3ba-1a8393f0dd2c.png)

**Comment by iknow2333** [comment]
2.10.9有这个问题，回退2.10.8就好了

**Comment by Chanzhaoyu** [comment]
升级包导致的，我已经回退了。
