### ISSUE TITLE
有关token方式

### ISSUE THREAD

**Issue by superen7527** [Chanzhaoyu/chatgpt-web#1178]
1.目前是手动获取token，大概一个月过期，能否使用账号密码的方式自动获取？

2.api和token这两个只能在部署的时候填写，能不能在网页上实时修改？这样比较方便

3.如果是独立token意味着只有自己用，能否多端同步记录而不是本地？(只是问问，需求不大)

4.我觉得token方式没必要舍弃，个人使用还是很方便的。除非大规模泛滥，当然这只是我的建议，如果作者不想维护了我也理解。

另外 关于使用token必须使用社区的反向代理，这是为了绕过cf使用web的api吧？目前只有这2个大佬的接口但是太多人用了，issue找了几个也都不能用。不过两个大佬怕官方封都没有开源，不知道如何自建这些反向代理接口？(不需要开源，有执行文件就行，有没有知道的帮忙回答下？找了好久没找到，感谢)

**Comment by gitlily1** [comment]
https://github.com/acheong08/ChatGPT-Proxy-V4
