### ISSUE TITLE
提示词异常无法下载

### ISSUE THREAD

**Issue by qyjgg** [Chanzhaoyu/chatgpt-web#1179]
![image](https://user-images.githubusercontent.com/44860826/229464706-2382617f-b7dd-4f8e-bb3c-53c4422d4e0a.png)

**Comment by fzucs** [comment]
网络问题，挂个代理就好了

**Comment by Chanzhaoyu** [comment]
这个是 GitHub 文件，可能那个地址你访问不到。

**Comment by qyjgg** [comment]
> 这个是 GitHub 文件，可能那个地址你访问不到。

我是部署在美国的vps  也会有这个问题吗
