### ISSUE TITLE
密钥验证是什么？

### ISSUE THREAD

**Issue by 110130xwq** [Chanzhaoyu/chatgpt-web#1180]
![image](https://user-images.githubusercontent.com/119826600/229465374-f14b138a-dd3c-4a5c-8de4-dbb607721dd6.png)这个验证用什么验证，求大佬解决

**Comment by xiaosaaaa** [comment]
在你部署的时候，会让你填写你自己的密码，我估计你没改默认配置，那就应该是xxx

**Comment by 110130xwq** [comment]
还真的是哎，谢啦
