### ISSUE TITLE
感觉模型突然变笨了？

### ISSUE THREAD

**Issue by kid715778238** [Chanzhaoyu/chatgpt-web#1186]
上周五的时候都有详细的出处和分析后的结果，现在输入和之前一样的内容，得到的不如之前的详细，而且好多引用的信息也没有了。
请问如何可以提高模型智商，或者是使用正版API的教程，有大佬可以帮帮忙吗，thx~

**Comment by Chanzhaoyu** [comment]
你把 systemMessage 修改具体点，看是否会更具体点？
