### ISSUE TITLE
日志中不打印聊天记录了，想保留这个功能，但没翻到源码

### ISSUE THREAD

**Issue by lhlxx2010** [Chanzhaoyu/chatgpt-web#119]
发现新的版本日志不打印记录了，想保留此功能但找不到源码？可以告知一下位置，我自己修改一下，谢谢！

**Comment by Chanzhaoyu** [comment]
后台可以自己用 global.console.log 打印

**Comment by lhlxx2010** [comment]
> 后台可以自己用 global.console.log 打印

 谢谢！

**Comment by JarvanDing** [comment]
麻烦问一下怎么打印呢？我砍了  docker里面没有运行日志，日志在哪里看呢？

**Comment by Chanzhaoyu** [comment]
> 麻烦问一下怎么打印呢？我砍了 docker里面没有运行日志，日志在哪里看呢？

把文件里的 `debug` 打开

**Comment by xieyusi9** [comment]
@Chanzhaoyu 请详细描述一下如何操作？docker如何实现日志中显示聊天记录

**Comment by hnuzhoulin** [comment]
> > 麻烦问一下怎么打印呢？我砍了 docker里面没有运行日志，日志在哪里看呢？
> 
> 把文件里的 `debug` 打开

./service/src/chatgpt/index.ts:47:      debug: true,
./service/src/chatgpt/index.ts:75:      debug: true,

搜索到这两个地方都已经是true了，直接拉容器运行的时候还是没有日志。还有哪个文件啊？感谢感谢 @Chanzhaoyu
