### ISSUE TITLE
自发的请求

### ISSUE THREAD

**Issue by ysun** [Chanzhaoyu/chatgpt-web#1190]
请问，为什么启动前端之后，每个一小段时间，它就会自发的去请求openAI的接口？如图所示
不知道是不是会浪费API 流量

![image](https://user-images.githubusercontent.com/1448148/229532283-6ac45dc3-0894-46d3-965d-7152f89b74da.png)

**Comment by JPmorganA** [comment]
你这是被端口扫描了吧，要设置密码，以及改index.html中的网页标题

**Comment by ysun** [comment]
> 你这是被端口扫描了吧，要设置密码，以及改index.html中的网页标题

这个项目没有能设置密码的功能哈？ 需要自己写登录？

**Comment by JPmorganA** [comment]
环境变量那里不是有吗？

AUTH_SECRET_KEY 访问权限密钥，可选

改这个环境变量就可以了

**Comment by ysun** [comment]
> 

@JPmorganA 哦~~~棒，没注意看完readme，感谢感谢。
另外一个小问题，我在service/.env 里面设置变量感觉不工作，包括设置API_KEY，我都是把变量通过docker --env 参数传递。
请问，如果那个.env如何让它工作起来？

**Comment by JPmorganA** [comment]
我也一直很纳闷这个问题，所以我就直接用docker compose了，需要什么环境变量就直接在上面改了
