### ISSUE TITLE
最新版似乎没法携带历史消息了？

### ISSUE THREAD

**Issue by xzqiaochu** [Chanzhaoyu/chatgpt-web#1194]
我是docker compose部署的，api key模式。从昨天更新最新版本后，似乎对话记不住之前的消息了（不管是否开启输入框左边的按钮）
我不清楚是不是自己的问题
![image](https://user-images.githubusercontent.com/41484968/229544524-e0d5fb87-4a46-4856-a33b-9c8c453577f5.png)

**Comment by xzqiaochu** [comment]
补充：这种现象只在ChatGPT的没有说完的情况下存在。
就是说，如果一个问题所需的字数很多，ChatGPT没有一次性说完，让他“继续”，他就忘记了前文

**Comment by xzqiaochu** [comment]
与 #978 是同一个问题

**Comment by cvpv** [comment]
我也有这个问题，请问是否解决

**Comment by xzqiaochu** [comment]
我后来的解决方式是：把超时时间设置为0（禁用超时）
