### ISSUE TITLE
我怎么改你的头像和名称啊，这个用户的默认设置在哪个目录里面哈

### ISSUE THREAD

**Issue by jjiikkkk** [Chanzhaoyu/chatgpt-web#1195]
我怎么改你的头像和名称啊，这个用户的默认设置在哪个目录里面哈

**Comment by Chanzhaoyu** [comment]
`store/modules/user/helper.ts`

**Comment by Grand2018** [comment]
> `store/modules/user/helper.ts`
大神， 请教下 403 提示在哪里修改？

**Comment by Chanzhaoyu** [comment]
> > `store/modules/user/helper.ts`
> > 大神， 请教下 403 提示在哪里修改？

你全局搜索下，403 图片是个 svg 文件
