### ISSUE TITLE
把AI搞蒙了

### ISSUE THREAD

**Issue by huajiao238** [Chanzhaoyu/chatgpt-web#1198]
把AI搞蒙了

https://user-images.githubusercontent.com/73993056/229570822-36720482-929b-4545-8d85-642e61926a0b.mp4

**Comment by refgd** [comment]
聊天发送的上下文并不在本地, 而是在服务器上面, 所以你修改本地的文字, 并没对上下文数据修改

**Comment by huajiao238** [comment]
> 聊天发送的上下文并不在本地, 而是在服务器上面, 所以你修改本地的文字, 并没对上下文数据修改

你的是，我的接口是自己写的

![微信截图_20230404101056](https://user-images.githubusercontent.com/73993056/229668747-70e13a4b-7483-49eb-95f2-abb0e9985824.png)
