### ISSUE TITLE
答案返回错误{"message":"Unexpected number in JSON at position 4","data":null,"status":"Fail"}

### ISSUE THREAD

**Issue by qq562934992** [Chanzhaoyu/chatgpt-web#1205]
{"message":"Unexpected number in JSON at position 4","data":null,"status":"Fail"}

**Comment by Chanzhaoyu** [comment]
用的 `Token` 吧，你用最新代码会不会有问题？

**Comment by hjkl950217** [comment]
插个眼，我也是用的`AcessToken`访问的。更有在更新新版，等待测试

**Comment by Lamply** [comment]
#1170 同样的问题，更新到 2.10.9 版本后出现的，刚试了用 `main` 分支最新代码也有这个问题

**Comment by mlaecn** [comment]
在 chatgpt下index.js中加入

```javascript
function isJSON(str){
	if (str === '') {
		return false;
	}

	try {
		JSON.parse(str);
		return true;
	} catch (e) {
		console.log("no json data: "+str)
		return false;
	}
}
``` 
![image](https://user-images.githubusercontent.com/39699775/234746560-72311b1a-58e2-4187-8567-9bc3433477dd.png)
将convoResponseEvent提到全局变量，在图片位置增加
```javascript
if (isJSON(data))
{
    convoResponseEvent = JSON.parse(data);
}
```
