### ISSUE TITLE
railway部署很方便，一键成功，但是后续怎么使用啊纯小白

### ISSUE THREAD

**Issue by HXLYTT** [Chanzhaoyu/chatgpt-web#1206]
部署完后完全不知道怎么访问我的web项目

**Comment by zqclair** [comment]
> 点击项目，右上角setting设置，Generate Domain 生成域名，也可以绑定自己的域名，直接访问对应域名就行

我部署好了，用自己域名可以访问，但是没连上GPT的服务。我是用的那个accessToken模式，有个反代的怎么设置？

**Comment by brucelau1987cn** [comment]
一键部署得国内使用 容易被封
