### ISSUE TITLE
123

### ISSUE THREAD

**Issue by webwalker** [Chanzhaoyu/chatgpt-web#1207]
RT

**Comment by time-river** [comment]
白嫖也不是这样白嫖的。
自己开发啊

**Comment by fzucs** [comment]
作者不搞商业化，自己搞吧

**Comment by hjkl950217** [comment]
这个得自己开发吧，或是你留个联系方式，付费给作者开发？

**Comment by xingke2023** [comment]
不建议白嫖

**Comment by webwalker** [comment]
不明是非不要乱评价，我是这公司内部用的，我只提供VPN转发流量，
因为是免费的，所以如果要长久，肯定是每个人要付费，但是和官网的TOKEN是一样的价格

**Comment by webwalker** [comment]
另外我说的收费版本，是指我花钱买作者的，不是说免费白嫖

**Comment by webwalker** [comment]
- 官方的需要翻墙，不是每个人都可以的，而且大部分的VPN即便能翻墙，但也用不了openai
- 公司用这个你觉得合法吗？ 
<img width="528" alt="企业微信截图_78c7d058-9f45-46a5-a103-8c54c198edf6" src="https://user-images.githubusercontent.com/3665580/230288390-58ef91e5-71f6-4b9e-b053-2c24a13d69d7.png">

**Comment by caiyunfan2** [comment]
自己开发吧，我也打算开发一个类似的功能，不然一群狐朋狗友乱玩猫娘，坑我的账户

**Comment by cd547** [comment]
这个项目下有关于通过railway，云部署项目。根本就不需要什么vpn就可以使用了，我已经用了快一个月，完全免费，也没有被封杀过。再说了，你这个标题“有收费版本吗？急需按token收费的版本”，本来就有嫌疑，怪不得别人。你要这功能，只能靠自己（开发/找/...），作者基本明确不会做的。再说做这个功能并不难。

**Comment by webwalker** [comment]
> 

嗯，我打算自己写了，花不了几个时间
