### ISSUE TITLE
docker build成功了，在run时候也成功了，docker ps也已经在运行 ip+端口号，拒绝链接怎么办？

### ISSUE THREAD

**Issue by xueguizheng** [Chanzhaoyu/chatgpt-web#1208]
这个问题困扰我了三天了，端口也开放了，docker ps 也显示在运行：
![image](https://user-images.githubusercontent.com/67084439/229684286-4ccd5d87-7f35-448d-86b5-1a1db81b9cc3.png)
日志也已经显示运行：
![image](https://user-images.githubusercontent.com/67084439/229684357-092e1beb-779d-4453-8586-e1c2be34d292.png)
但是 ip+端口号就访问不了，请问大神这到底是咋回事呢？
![image](https://user-images.githubusercontent.com/67084439/229684585-2d5ef6ac-2bad-46e1-b8df-edf41d19b06d.png)

**Comment by yanpengfei-git** [comment]
我的在电脑上正常，用手机也是这

**Comment by JPmorganA** [comment]
你试一下开代理访问看下能访问吗？如果能那就是你IP或者端口被墙了

**Comment by xueguizheng** [comment]
> 

感谢大佬，已经解决了，开放端口有延迟的原因。

**Comment by xueguizheng** [comment]
> 你试一下开代理访问看下能访问吗？如果能那就是你IP或者端口被墙了

之前图便宜买了个垃圾服务器不行，这次换成阿里云就好了

**Comment by xueguizheng** [comment]
> 我的在电脑上正常，用手机也是这

应该就是端口开放的原因，或者防火墙

**Comment by CcCcaidan** [comment]
我也遇到这个问题，docker部署成功，在云服务器里面crul 127.0.0.1:3002是能够正常返回Html页面的，但是在外网就不行，用的腾讯云，已经放开了3002端口TCP。。。。
