### ISSUE TITLE
stream分支的Docker镜像

### ISSUE THREAD

**Issue by Suyknow** [Chanzhaoyu/chatgpt-web#121]
目前github上已有分main和stream（以及dev）分支。
但是docker hub上，只有main一个tag，希望stream分支也能同步打包并push到github。

**Comment by Chanzhaoyu** [comment]
这个分支目前有问题，暂不合并或者推送

**Comment by Chanzhaoyu** [comment]
`2.8.0` 版本将合并 `stream` 模式，请关注

**Comment by chenyuxiangyes** [comment]
感谢！期待docker的stream模式。

**Comment by Chanzhaoyu** [comment]
已合并

**Comment by Suyknow** [comment]
> 已合并

谢谢，已经在用了！
