### ISSUE TITLE
docker-compose配置使用服务器本机代理无法访问

### ISSUE THREAD

**Issue by LightlyBlue** [Chanzhaoyu/chatgpt-web#1210]
在docker-compose配置文件中，将HTTP_PROXY参数设置为127.0.0.1:10808，服务器上clash监听端口10808，但是无法正常使用，提示如下
<img width="816" alt="image" src="https://user-images.githubusercontent.com/51265410/229689344-3ca9eade-28fc-4789-adeb-a780a5bf3b9d.png">

**Comment by xiaohuangtx** [comment]
127.0.0.1会指向容器本身而非宿主机，如果要用127.0.0.1的话你需要把容器的网络改为host模式

**Comment by LightlyBlue** [comment]
> 
你好，我的配置如下，但还是在执行”docker-compose up -d“时只能启动chatgpt-web容器，nginx容器无法正常启动，请问该如何解决呢
<img width="843" alt="image" src="https://user-images.githubusercontent.com/51265410/229751978-f364857e-e428-44ef-9fb7-63320c0e3ac9.png">

**Comment by LightlyBlue** [comment]
> 127.0.0.1会指向容器本身而非宿主机，如果要用127.0.0.1的话你需要把容器的网络改为host模式

你好，我的配置如下，但还是在执行”docker-compose up -d“时只能启动chatgpt-web容器，nginx容器无法正常启动，请问该如何解决呢
<img width="735" alt="image" src="https://user-images.githubusercontent.com/51265410/229753395-92b90893-9fee-4432-899b-04736d9848fb.png">

**Comment by brucelau1987cn** [comment]
> 

VPS更新
apt-get install sudo （如果以下报错，请先安装sudo）
sudo passwd root
apt update –y
apt-get update --allow-releaseinfo-change
apt install -y curl
sudo apt upgrade
sudo apt update
1、安装 Docker 及 Docker-compose
•	安装Docker
apt-get update && apt-get install -y wget vim
#国外机：curl -sSL https://get.docker.com/ | sh
#国内机：curl -sSL https://get.daocloud.io/docker | sh
#开机自动启动：
systemctl start docker
systemctl enable docker
•	安装 Docker-compose
#国外机：
sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
#国内机
curl -L https://get.daocloud.io/docker/compose/releases/download/v2.1.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
2、安装 Nginx Proxy Manager
Nginx Proxy Manager 是一款基于Docker 的反代神器，强烈推荐使用。
•	创建目录
mkdir -p data/docker_data/npm
cd data/docker_data/npm
•	创建 docker-compose.yml 文件
nano docker-compose.yml
•	在文件中填入以下内容，然后 Ctrl+X 保存，按 Y 退出
•	建议提前做好文件拷贝到服务器
version: "3"
services:
app:
image: 'jc21/nginx-proxy-manager:latest'
restart: unless-stopped
ports:
# These ports are in format <host-port>:<container-port>
- '80:80' # Public HTTP Port
- '443:443' # Public HTTPS Port
- '81:81' # Admin Web Port
# Add any other Stream port you want to expose
# - '21:21' # FTP
environment:
DB_MYSQL_HOST: "db"
DB_MYSQL_PORT: 3306
DB_MYSQL_USER: "npm"
DB_MYSQL_PASSWORD: "npm"
DB_MYSQL_NAME: "npm"
# Uncomment this if IPv6 is not enabled on your host
# DISABLE_IPV6: 'true'
volumes:
- ./data:/data
- ./letsencrypt:/etc/letsencrypt
depends_on:
- db

db:
image: 'jc21/mariadb-aria:latest'
restart: unless-stopped
environment:
MYSQL_ROOT_PASSWORD: 'npm'
MYSQL_DATABASE: 'npm'
MYSQL_USER: 'npm'
MYSQL_PASSWORD: 'npm'
volumes:
- ./data/mysql:/var/lib/mysql

运行
docker-compose up -d
通过 IP:81 来访问 Nginx Proxy Manager ，具体的反代操作我们接下来会讲，请先记住初始账户和密码
Email:  admin@example.com
Password:  changeme
3、安装 ChatGPT-web
创建目录
mkdir -p data/docker_data/chatgpt
cd data/docker_data/chatgpt
创建 docker-compose.yml 文件
nano docker-compose.yml
•	在文件中填入以下内容，然后 Ctrl+X 保存，按 Y 退出
•	建议提前做好文件拷贝到服务器
version: '3'

services:
app:
image: chenzhaoyu94/chatgpt-web:main
restart: unless-stopped
ports:
- 3002:3002
environment:
OPENAI_API_KEY: xxxxxx
创建完成后，运行
docker-compose up -d
报错再用一次这个命令
docker-compose up -d --remove-orphans
然后就可以通过 IP:3002 来访问 ChatGPT
4、反代 ChatGPT
前面是用 IP:3002 来访问ChatGPT，我们可以通过反代的方式实现域名访问，并配置 SSL 证书，就像前面的演示网址一样。接下来就来进行反代操作，用到第二步中搭建的 Nginx Proxy Manager
用 IP:81 打开 Nginx Proxy Manager，第一次登录以后需要修改用户和密码，请自行配置打开 Proxy Hosts -> 点击右上角 Add Proxy Hosts -> 按照图中进行配置 -> 颁发 SSL 证书并开启强制Https 访问 -> 点击 Save 保存

   
至此，就完成反代的工作，接下来就可以用刚才解析的域名访问 ChatGPT 了。
5、版本更新操作
docker-compose down 命令停止当前运行的容器。
docker-compose pull 命令拉取最新的镜像版本。
docker-compose up -d 命令重新启动容器（如果镜像有更新，将自动使用最新的镜像）。
Docker空间不够（no space left on device）
docker system prune --all --force –volumes
docker system prune -a

6、安装错误处理
6.1 E: Sub-process /usr/bin/dpkg returned an error code (1)错误
cd /var/lib/dpkg/
sudo mv info/ info_bak           # 现将info文件夹更名
sudo mkdir info                  # 再新建一个新的info文件夹
sudo apt-get update             # 更新
sudo apt-get -f install            # 修复
sudo mv info/* info_bak/         # 执行完上一步操作后会在新的info文件夹下生成一些文件，现将这些文件全部移到info_bak文件夹下
sudo rm -rf info                  # 把自己新建的info文件夹删掉
sudo mv info_bak info            # 把以前的info文件夹重新改回名

/var/lib/dpkg/lock-frontend 错误
rm –rf /var/lib/dpkg/lock
