### ISSUE TITLE
OpenAI 回复消息过长后报响应超时。

### ISSUE THREAD

**Issue by yangbinmao** [Chanzhaoyu/chatgpt-web#1211]
回复消息过长后报响应超时。OpenAI timed out waiting for response，我应该怎么去处理这个问题喃。是梯子的问题吗？

**Comment by x-hanzh** [comment]
TIMEOUT_MS设置长点，我给了2分钟

**Comment by yangbinmao** [comment]
> TIMEOUT_MS设置长点，我给了2分钟

我设置了18000都还是没有用。会是这个问题吗？

**Comment by GitHubChrisChen8035** [comment]
> > TIMEOUT_MS设置长点，我给了2分钟
> 
> 我设置了18000都还是没有用。会是这个问题吗？

18000的单位是毫秒，也就是18秒，建议60000（一分钟）以上

**Comment by x-hanzh** [comment]
> > TIMEOUT_MS设置长点，我给了2分钟
> 
> 我设置了18000都还是没有用。会是这个问题吗？

是这个问题，参考这个issue #904 ,把TIMEOUT_MS设置为0。
