### ISSUE TITLE
无法用腾讯cos的文件地址下载提示词。

### ISSUE THREAD

**Issue by JianGangLi** [Chanzhaoyu/chatgpt-web#1213]
因部分网络无法直接下载github的提示词json文件，然后上传到cos，结果还是提示
<img width="435" alt="image" src="https://user-images.githubusercontent.com/72450155/229703472-d9cb8eab-d298-4c9f-ac1b-c0b30f0fc8e3.png">

**Comment by fzucs** [comment]
我也是，上传到自己的vps也没用

**Comment by JianGangLi** [comment]
> 我也是，上传到自己的vps也没用

七牛云可以

**Comment by xueguizheng** [comment]
> > 我也是，上传到自己的vps也没用
> 
> 七牛云可以

大佬上传到七牛云，是不是直接复制他那个外连接就行了，但是外连接有效性时长最多24小时，也不能每24小时维护一次吧。

**Comment by JianGangLi** [comment]
24小时是你复制的临时链接吧？你复制永久链接。如果都是24小时，没人用他家的了。

**Comment by JianGangLi** [comment]
> > > 我也是，上传到自己的vps也没用
> > 
> > 七牛云可以
> 
> 大佬上传到七牛云，是不是直接复制他那个外连接就行了，但是外连接有效性时长最多24小时，也不能每24小时维护一次吧。

24小时是你复制的临时链接吧？你复制永久链接。如果都是24小时，没人用他家的了。

**Comment by xueguizheng** [comment]
> > > > 我也是，上传到自己的vps也没用
> > > 
> > > 
> > > 七牛云可以
> > 
> > 
> > 大佬上传到七牛云，是不是直接复制他那个外连接就行了，但是外连接有效性时长最多24小时，也不能每24小时维护一次吧。
> 
> 24小时是你复制的临时链接吧？你复制永久链接。如果都是24小时，没人用他家的了。

永久链接在哪复制的，，没找到呢。。。

**Comment by JianGangLi** [comment]
> > > > > 我也是，上传到自己的vps也没用
> > > > 
> > > > 
> > > > 七牛云可以
> > > 
> > > 
> > > 大佬上传到七牛云，是不是直接复制他那个外连接就行了，但是外连接有效性时长最多24小时，也不能每24小时维护一次吧。
> > 
> > 24小时是你复制的临时链接吧？你复制永久链接。如果都是24小时，没人用他家的了。
> 
> 永久链接在哪复制的，，没找到呢。。。

![Screenshot_2023-04-05-20-49-02-04_fab32b241c9ab51b0e057c943b753947.jpg](https://user-images.githubusercontent.com/72450155/230085283-254d0030-dc45-4d23-90d8-eabb4d4dd2b9.jpg)

空间里文件复制外链就行，我反而没找到你点的临时外链在哪儿

**Comment by xueguizheng** [comment]
> > > > > > 我也是，上传到自己的vps也没用
> > > > > 
> > > > > 
> > > > > 七牛云可以
> > > > 
> > > > 
> > > > 大佬上传到七牛云，是不是直接复制他那个外连接就行了，但是外连接有效性时长最多24小时，也不能每24小时维护一次吧。
> > > 
> > > 
> > > 24小时是你复制的临时链接吧？你复制永久链接。如果都是24小时，没人用他家的了。
> > 
> > 
> > 永久链接在哪复制的，，没找到呢。。。
> 
> ![Screenshot_2023-04-05-20-49-02-04_fab32b241c9ab51b0e057c943b753947.jpg](https://user-images.githubusercontent.com/72450155/230085283-254d0030-dc45-4d23-90d8-eabb4d4dd2b9.jpg)
> 
> 空间里文件复制外链就行，我反而没找到你点的临时外链在哪儿

详情里。。

**Comment by JianGangLi** [comment]
> 复制外链，会弹出这个框，有时效，最大24小时
> ![image](https://user-images.githubusercontent.com/67084439/230093450-d3594493-e23b-41b0-ab17-b5a7c385b403.png)
> 

你空间设置为私有了？ 请设置成公有空间

**Comment by xueguizheng** [comment]
> > 复制外链，会弹出这个框，有时效，最大24小时
> > ![image](https://user-images.githubusercontent.com/67084439/230093450-d3594493-e23b-41b0-ab17-b5a7c385b403.png)
> 
> 你空间设置为私有了？ 请设置成公有空间

大佬，这个设置我放到downloadUrl上，本地可以正常添加，但是再部署到云服务器就不能添加这是为啥。。好奇怪啊！

**Comment by JianGangLi** [comment]
> > > 复制外链，会弹出这个框，有时效，最大24小时
> > > ![image](https://user-images.githubusercontent.com/67084439/230093450-d3594493-e23b-41b0-ab17-b5a7c385b403.png)
> > 
> > 你空间设置为私有了？ 请设置成公有空间
> 
> 大佬，这个设置我放到downloadUrl上，本地可以正常添加，但是再部署到云服务器就不能添加这是为啥。。好奇怪啊！

我没有理解你的意思，你是docker吗？docker改文件需要重新编译

**Comment by JianGangLi** [comment]
> > > 复制外链，会弹出这个框，有时效，最大24小时
> > > ![image](https://user-images.githubusercontent.com/67084439/230093450-d3594493-e23b-41b0-ab17-b5a7c385b403.png)
> > 
> > 你空间设置为私有了？ 请设置成公有空间
> 
> 大佬，这个设置我放到downloadUrl上，本地可以正常添加，但是再部署到云服务器就不能添加这是为啥。。好奇怪啊！

我没理解，你是什么平台，什么版本，另外提示什么？

**Comment by xueguizheng** [comment]
在服务器上提示这个，本地导入成功，
![image](https://user-images.githubusercontent.com/67084439/230105433-1fc476ad-b9f4-478b-a7bc-64f556ab225b.png)

**Comment by JianGangLi** [comment]
> 在服务器上提示这个，本地导入成功，
> ![image](https://user-images.githubusercontent.com/67084439/230105433-1fc476ad-b9f4-478b-a7bc-64f556ab225b.png)
> 

如果你修改过json文件，你先在网上找个json格式转换网址，试试看是否报错。 七牛云可以下载的，前提是你的json文件是正确的，常见的是英文双引号和中文双引号一样了

**Comment by xueguizheng** [comment]
> > 在服务器上提示这个，本地导入成功，
> > ![image](https://user-images.githubusercontent.com/67084439/230105433-1fc476ad-b9f4-478b-a7bc-64f556ab225b.png)
> 
> 如果你修改过json文件，你先在网上找个json格式转换网址，试试看是否报错。 七牛云可以下载的，前提是你的json文件是正确的，常见的是英文双引号和中文双引号一样了

没有问题的，我在本地可以下载成功，换成服务器就不行了，可能是我服务器原因吧

**Comment by JianGangLi** [comment]
> > > 在服务器上提示这个，本地导入成功，
> > > ![image](https://user-images.githubusercontent.com/67084439/230105433-1fc476ad-b9f4-478b-a7bc-64f556ab225b.png)
> > 
> > 如果你修改过json文件，你先在网上找个json格式转换网址，试试看是否报错。 七牛云可以下载的，前提是你的json文件是正确的，常见的是英文双引号和中文双引号一样了
> 
> 没有问题的，我在本地可以下载成功，换成服务器就不行了，可能是我服务器原因吧

如果你说的本地是浏览器下载，那么没有参考意义，我猜想是作者这个下载请求带了某个参数，导致只有七牛云刚好符合。   而你七牛云无法下载，就检查json文件是否正确。

**Comment by JianGangLi** [comment]
> > > 在服务器上提示这个，本地导入成功，
> > > ![image](https://user-images.githubusercontent.com/67084439/230105433-1fc476ad-b9f4-478b-a7bc-64f556ab225b.png)
> > 
> > 如果你修改过json文件，你先在网上找个json格式转换网址，试试看是否报错。 七牛云可以下载的，前提是你的json文件是正确的，常见的是英文双引号和中文双引号一样了
> 
> 没有问题的，我在本地可以下载成功，换成服务器就不行了，可能是我服务器原因吧

另外七牛云重新上传同名文件，需要更新下cdn缓存，不然还是老版本文件

**Comment by JianGangLi** [comment]
> > > 在服务器上提示这个，本地导入成功，
> > > ![image](https://user-images.githubusercontent.com/67084439/230105433-1fc476ad-b9f4-478b-a7bc-64f556ab225b.png)
> > 
> > 如果你修改过json文件，你先在网上找个json格式转换网址，试试看是否报错。 七牛云可以下载的，前提是你的json文件是正确的，常见的是英文双引号和中文双引号一样了
> 
> 没有问题的，我在本地可以下载成功，换成服务器就不行了，可能是我服务器原因吧

你直接发送你的七牛云文件地址给我就知道了，还有你始终没有说自己是什么平台

**Comment by xiaomenggit** [comment]
直接把这个json文件放在服务器根目录，然后下载地址改成这个地址

**Comment by xueguizheng** [comment]
> 直接把这个json文件放在服务器根目录，然后下载地址改成这个地址

我放到了服务器nginx目录里，并把域名改成了https，但是把下载地址改成这个还是不行，，你们可以试着访问一下：https://xueguizheng.top/prompt.json    这个是也是没错的，我用postman请求也没问题，就是放到代码里就不行了，求救啊大佬！！
