### ISSUE TITLE
为什么部署在本地打开还是三个点半天加载不出来？

### ISSUE THREAD

**Issue by qkmc-rk** [Chanzhaoyu/chatgpt-web#1216]
![image](https://user-images.githubusercontent.com/18748765/229717895-7a25c5bf-6e65-44ae-92db-7bb455a7cf91.png)
![image](https://user-images.githubusercontent.com/18748765/229717998-9ed1b0b0-752e-41ce-b714-7e14fe1d5b82.png)

**Comment by hjkl950217** [comment]
可能是网络问题，我昨晚也遇到类似的情况。原因是因为和外网通讯时非常慢，拉取一些js耗时很长。 待JS拉取完毕后，页面就可以用了

**Comment by qkmc-rk** [comment]
> 可能是网络问题，我昨晚也遇到类似的情况。原因是因为和外网通讯时非常慢，拉取一些js耗时很长。 待JS拉取完毕后，页面就可以用了

好谢谢

**Comment by qkmc-rk** [comment]
> 可能是网络问题，我昨晚也遇到类似的情况。原因是因为和外网通讯时非常慢，拉取一些js耗时很长。 待JS拉取完毕后，页面就可以用了

好谢谢
