### ISSUE TITLE
[OpenAI] 提供错误的API密钥 | Incorrect API key provided

### ISSUE THREAD

**Issue by suddenlyTW** [Chanzhaoyu/chatgpt-web#1217]
出现这个问题，怎么解决

**Comment by fishslidenas** [comment]
用的是AccessToken吗？如果是，那就是Token失效了

**Comment by lu-kaijie** [comment]
失效了整个过程要重来一遍嘛还是替换一下AccessToken就行

**Comment by berlin32** [comment]
一样出现这个问题，官网页面看key被删除了，重建就可以了，但是每天被删一遍就很难受，有人知道为什么嘛？

**Comment by ltinerary** [comment]
今天又看了一下，发现官网把获取获取token的方法【[https://chat.openai.com/api/auth/session】，](https://chat.openai.com/api/auth/session%E3%80%91%EF%BC%8C)改成了post请求
![4eb8df303c08be9d8264ac05ef350f1](https://user-images.githubusercontent.com/79144923/231619505-573ab17d-ebef-42d8-b345-b0bf3fb66178.png)

**Comment by iFoxox** [comment]
AccessToken过期，如果出现调用https://chat.openai.com/api/auth/session出现RefreshAccessTokenError，直接上chatGPT发起一个会话，自己查看控制台请求找到里面的AccessToken
