### ISSUE TITLE
Open AI 已经沦陷，有没有简化的对接Azure OpenAI的项目呢

### ISSUE THREAD

**Issue by charlesjosn** [Chanzhaoyu/chatgpt-web#1222]

**Comment by xingke2023** [comment]
[charlesjosn](https://github.com/charlesjosn)
你有Azure OpenAI接口吗，我可以提供编码支持

**Comment by charlesjosn** [comment]
是的  我有Azure openAi 接口和资源以及blob，但是可能无权限公开此信息 @xingke2023

**Comment by panhuanghe** [comment]
@xingke2023 大佬我这边有接口   可以share一个给你用  能否完善一下Azure openAi的项目

**Comment by cypggs** [comment]
同求，我也申请下来了

**Comment by cypggs** [comment]
> 同求，我也申请下来了

azure openai 配合https://github.com/haibbo/cf-openai-azure-proxy   ，直接可以当openai key用，几乎适配所有客户端；
这个可以哦

**Comment by xingke2023** [comment]
> @xingke2023 大佬我这边有接口   可以share一个给你用  能否完善一下Azure openAi的项目 

我帮你完善 感谢share
