### ISSUE TITLE
能不能用docker pull命令来部署

### ISSUE THREAD

**Issue by PWMFI** [Chanzhaoyu/chatgpt-web#1223]

**Comment by brucelau1987cn** [comment]
我是个菜鸟，说错了勿喷，我使用docker-compose运行得，
只有更新才用到类似得命令
1.docker-compose down 命令停止当前运行的容器。
2.docker-compose pull 命令拉取最新的镜像版本。
3.docker-compose up -d 命令重新启动容器（如果镜像有更新，将自动使用最新的镜像）。
你那个我真不知道干什么的
