### ISSUE TITLE
是否考虑在前端网页中增加设置API的功能？

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [Chanzhaoyu/chatgpt-web#1225]
几点好处：
1、有API的朋友，可以通过我搭建的WEB服务，用他自己的API免科学上网访问ChatGPT（这也是本项目的初衷）
2、即使被扫描端口也不会造成扣费、滥用的情况
3、给每个需要访问的朋友一个独立的API（前提是TA不再二次分享），降低封号的可能

以上

**Comment by JPmorganA** [comment]
可以用作者之前推荐的其他人的项目#1164

**Comment by JPmorganA** [comment]
可以用作者推荐的其他人的项目，在这里#1161

**Comment by JPmorganA** [comment]
[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)这个项目就可以实现你的需求，在设置里填入访问密码就是用你的APIkey，不填的话就可以在下面填自己的APIkey进行使用

**Comment by imcaptor** [comment]
感觉这个可以向ChatGPT-Next_Web对齐一下，确实比较有用。
我们很多同事都是有自己的账号，可以生成key，platform.openai.com可以访问。
但是官网不让访问。

这个项目有两个优点比较看重：
1.导入提示词。
2.历史聊天记录。
3.可以直接导出成长图。

**Comment by Justsenger** [comment]
我也希望可以出一个这样的设置。

**Comment by 3339588491** [comment]
> [chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)这个分支项目也是可以的，只要在部署的时候环境变量里不填入apikey，输入自己的邮箱号进入后就可以在设置中填写自己的key或者token还可以改模型，记录各自账号的聊天记录

这个项目本地部署报错：

h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9
    return (connectionString.startsWith('mongodb://') ||
                             ^


TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9:30)
    at ConnectionString (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:85:34)
    at parseOptions (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\connection_string.js:204:17)
    at MongoClient (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\mongo_client.js:46:50)
    at <anonymous> (h:\001ChatWeb\009\chatgpt-web-main\service\src\storage\mongo.ts:9:16)
    at Object.<anonymous> (h:\001ChatWeb\009\chatgpt-web-main\service\src\storage\mongo.ts:163:23)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.F (H:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\@esbuild-kit+cjs-loader@2.4.2\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)

Node.js v18.15.0
 ELIFECYCLE  Command failed with exit code 1.

这怎么解决呢？

**Comment by JPmorganA** [comment]
> > [chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)这个分支项目也是可以的，只要在部署的时候环境变量里不填入apikey，输入自己的邮箱号进入后就可以在设置中填写自己的key或者token还可以改模型，记录各自账号的聊天记录
> 
> 
> 
> 这个项目本地部署报错：
> 
> 
> 
> h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9
> 
>     return (connectionString.startsWith('mongodb://') ||
> 
>                              ^
> 
> 
> 
> 
> 
> TypeError: Cannot read properties of undefined (reading 'startsWith')
> 
>     at connectionStringHasValidScheme (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9:30)
> 
>     at ConnectionString (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:85:34)
> 
>     at parseOptions (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\connection_string.js:204:17)
> 
>     at MongoClient (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\mongo_client.js:46:50)
> 
>     at <anonymous> (h:\001ChatWeb\009\chatgpt-web-main\service\src\storage\mongo.ts:9:16)
> 
>     at Object.<anonymous> (h:\001ChatWeb\009\chatgpt-web-main\service\src\storage\mongo.ts:163:23)
> 
>     at Module._compile (node:internal/modules/cjs/loader:1254:14)
> 
>     at Object.F (H:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\@esbuild-kit+cjs-loader@2.4.2\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
> 
>     at Module.load (node:internal/modules/cjs/loader:1117:32)
> 
>     at Module._load (node:internal/modules/cjs/loader:958:12)
> 
> 
> 
> Node.js v18.15.0
> 
>  ELIFECYCLE  Command failed with exit code 1.
> 
> 
> 
> 这怎么解决呢？

一些环境变量没设置你用docker compose就好了，参考如下配置

services:
  app:
    image: kerwin1202/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 13002:3002
    depends_on:
      - database
    environment:
      # 二选一
      OPENAI_API_KEY: xxx
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: xxx
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:xxxx@database:27017'
      # 网站是否开启注册
      REGISTER_ENABLED: true
      # 开启注册之后 网站注册允许的邮箱后缀 如果空 则允许任意后缀
      REGISTER_MAILS: '@qq.com,@sina.com,@163.com'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: xxx
      # 开启注册之后 超级管理邮箱
      ROOT_USER: xxx
      # 开启注册之后 网站域名 不含 / 注册的时候发送验证邮箱使用
      SITE_DOMAIN: http://127.0.0.1:13002
      # 开启注册之后 发送验证邮箱配置
      SMTP_HOST: smtp.exmail.qq.com
      SMTP_PORT: 465
      SMTP_TSL: true
      SMTP_USERNAME: xxx
      SMTP_PASSWORD: xxx
    links:
      - database

  database:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: xxxx
      MONGO_INITDB_DATABASE: chatgpt
      
volumes:
  mongodb: {}

**Comment by JPmorganA** [comment]
13002可以改为自己想用的端口，MONGODB_URL: 'mongodb://chatgpt:xxxx@database:27017'
这里的xxx填的就是下面
MONGO_INITDB_ROOT_PASSWORD: xxxx
这里设置的密码

**Comment by 3339588491** [comment]
> > > [chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)这个分支项目也是可以的，只要在部署的时候环境变量里不填入apikey，输入自己的邮箱号进入后就可以在设置中填写自己的key或者token还可以改模型，记录各自账号的聊天记录
> > 
> > 
> > 这个项目本地部署报错：
> > h:\001ChatWeb\009\chatgpt-web-main\service\node_modules.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9
> > ```
> > return (connectionString.startsWith('mongodb://') ||
> > 
> >                          ^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > TypeError: Cannot read properties of undefined (reading 'startsWith')
> > ```
> > at connectionStringHasValidScheme (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9:30)
> > 
> > at ConnectionString (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:85:34)
> > 
> > at parseOptions (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\connection_string.js:204:17)
> > 
> > at MongoClient (h:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\mongo_client.js:46:50)
> > 
> > at <anonymous> (h:\001ChatWeb\009\chatgpt-web-main\service\src\storage\mongo.ts:9:16)
> > 
> > at Object.<anonymous> (h:\001ChatWeb\009\chatgpt-web-main\service\src\storage\mongo.ts:163:23)
> > 
> > at Module._compile (node:internal/modules/cjs/loader:1254:14)
> > 
> > at Object.F (H:\001ChatWeb\009\chatgpt-web-main\service\node_modules\.pnpm\@esbuild-kit+cjs-loader@2.4.2\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
> > 
> > at Module.load (node:internal/modules/cjs/loader:1117:32)
> > 
> > at Module._load (node:internal/modules/cjs/loader:958:12)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Node.js v18.15.0
> >  ELIFECYCLE  Command failed with exit code 1.
> > 这怎么解决呢？
> 
> 一些环境变量没设置你用docker compose就好了，参考如下配置
> 
> services: app: image: kerwin1202/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可 ports: - 13002:3002 depends_on: - database environment: # 二选一 OPENAI_API_KEY: xxx # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL AUTH_SECRET_KEY: xxx # 超时，单位毫秒，可选 TIMEOUT_MS: 60000 # mongodb 的连接字符串 MONGODB_URL: 'mongodb://chatgpt:xxxx@database:27017' # 网站是否开启注册 REGISTER_ENABLED: true # 开启注册之后 网站注册允许的邮箱后缀 如果空 则允许任意后缀 REGISTER_MAILS: '@qq.com,@sina.com,@163.com' # 开启注册之后 密码加密的盐 PASSWORD_MD5_SALT: xxx # 开启注册之后 超级管理邮箱 ROOT_USER: xxx # 开启注册之后 网站域名 不含 / 注册的时候发送验证邮箱使用 SITE_DOMAIN: http://127.0.0.1:13002 # 开启注册之后 发送验证邮箱配置 SMTP_HOST: smtp.exmail.qq.com SMTP_PORT: 465 SMTP_TSL: true SMTP_USERNAME: xxx SMTP_PASSWORD: xxx links: - database
> 
> database: image: mongo ports: - '27017:27017' expose: - '27017' volumes: - mongodb:/data/db environment: MONGO_INITDB_ROOT_USERNAME: chatgpt MONGO_INITDB_ROOT_PASSWORD: xxxx MONGO_INITDB_DATABASE: chatgpt
> 
> volumes: mongodb: {}

非常感谢! 我试试看。但是我更想使用本地调试成功然后部署到服务器，如果不行就用docker compose

**Comment by GitHubChrisChen8035** [comment]
已经有大佬实现（虽然也不难），支持一下
https://github.com/Chanzhaoyu/chatgpt-web/issues/1342#issue-1659951517
