### ISSUE TITLE
railway上面部署之后运行报错。

### ISSUE THREAD

**Issue by sdlkhfksl** [Chanzhaoyu/chatgpt-web#1227]
[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error

请教下如何解决，谢谢！
![屏幕截图 2023-04-04 195450](https://user-images.githubusercontent.com/97817853/229783880-417f9e49-7a8a-481a-84a0-d472a37f332a.jpg)

**Comment by Chanzhaoyu** [comment]
你在本地跑一下查看日志，可能是你帐号被封了。
