### ISSUE TITLE
自己弄好多细节不会，弄了个交流群，大家技术讨论 加connection-image 我来拉你

### ISSUE THREAD

**Issue by yyx20202020** [Chanzhaoyu/chatgpt-web#1228]
自己搞好多部清楚的，一起来弄吧。。准备搞个部署问题的解决文档出来

**Comment by yyx20202020** [comment]
v: connection-image   备注：GPTWEB项目

**Comment by MoonHuan** [comment]
你被加好友过于平凡，请发个二维码到邮箱:seeyyy@qq.com

**Comment by Chanzhaoyu** [comment]
有社区的交流群，你在 issues 中搜索下。

**Comment by yyx20202020** [comment]
> 你被加好友过于平凡，请发个二维码到邮箱:[seeyyy@qq.com](mailto:seeyyy@qq.com)

可以加啊。。

**Comment by rocket2023** [comment]
qq群:  204311814
