### ISSUE TITLE
大佬们，提示词库如何换源，修改呀。。不挂代理没法在线下载呀。

### ISSUE THREAD

**Issue by xueguizheng** [Chanzhaoyu/chatgpt-web#1229]
![image](https://user-images.githubusercontent.com/67084439/229842626-e8e86d4f-e98f-4b28-be02-e1ae7f6aefa1.png)
大佬们你们自己的提示词库downloadUrl是在哪搞的？

**Comment by Chanzhaoyu** [comment]
这个其实就是 GitHub 项目，你可以把文件换成国内可以访问的地址。

**Comment by xueguizheng** [comment]
> 这个其实就是 GitHub 项目，你可以把文件换成国内可以访问的地址
你好大佬，要是我手动维护一个提示库的话，需要啥？七牛云？阿里云oss这种？

**Comment by xueguizheng** [comment]
> 点旁边那个链接，进去选择对应那个json文件，复制json内容然后手动添加也可以呀。

但是客户麻烦呀，还得是在线好办，我想的是自己维护一个，不知道咋弄

**Comment by xueguizheng** [comment]
> 点旁边那个链接，进去选择对应那个json文件，复制json内容然后手动添加也可以呀。

但是别人觉着麻烦呀，我想自己维护一个在线的，不知道咋弄

**Comment by xueguizheng** [comment]
> > > 点旁边那个链接，进去选择对应那个json文件，复制json内容然后手动添加也可以呀。
> > 
> > 
> > 但是别人觉着麻烦呀，我想自己维护一个在线的，不知道咋弄
> 
> 你要搞在线的，那你确保你的json文件的url地址能正常访问到不就行了？ 不就替换个url的事情吗。gitee上建个库，定期拉取同步github上的这个，自己随便怎么维护更新都可以呀。

我用的七牛云，本地可以添加，然后服务器上部署完了就不行。。很奇怪
