### ISSUE TITLE
如果你还不会部署该项目，请看看我的快速部署指南，也许可以帮到你

### ISSUE THREAD

**Issue by James-handsome** [Chanzhaoyu/chatgpt-web#1230]
https://github.com/James-handsome/chatGPT-Deploy

**Comment by James-handsome** [comment]
快速部署指南 https://github.com/James-handsome/chatGPT-Deploy

**Comment by suyaoyong** [comment]
用vercel和netlify或者railway不是一键部署吗？最多填一下环境变量吧。
