### ISSUE TITLE
手机上无法切换成移动端模式

### ISSUE THREAD

**Issue by LeoLeeYM** [Chanzhaoyu/chatgpt-web#1231]
手机上无法切换成移动端模式，在电脑上减少窗口宽度会自动变成移动端布局，但是在手机上不行。
而且在F12里使用“响应式”模式也无法切换，求解

**Comment by Chanzhaoyu** [comment]
是否你手机默认浏览器的 UA 还是 PC 模式，你用微信打开测试下就知道了。
