### ISSUE TITLE
再次刷新网页后历史记录获取不到

### ISSUE THREAD

**Issue by aohun** [Chanzhaoyu/chatgpt-web#1234]
第一次访问会调用接口查询历史记录，再次刷新页面，控制台报错。
![image](https://user-images.githubusercontent.com/37433539/229951941-19d08391-0f70-4b93-9b71-e537b5e86267.png)

src/views/chat/index.vue 查看源码是此处uuid未获取到
![image](https://user-images.githubusercontent.com/37433539/229952032-e64279fd-d20c-4ad7-8914-f9f52a39263f.png)

**Comment by Kerwin1202** [comment]
可以点进去看看 提供下大概位置

<img width="830" alt="image" src="https://user-images.githubusercontent.com/16319833/230625547-c38e2179-8b6f-4f3d-a76a-e589b5b034c5.png">
