### ISSUE TITLE
如何切换到gpt3.5或4呢? 问了ChatGPT和自己搭建的项目,发现差别挺大

### ISSUE THREAD

**Issue by EthanDCX** [Chanzhaoyu/chatgpt-web#1236]
![image](https://user-images.githubusercontent.com/18240991/229958788-be4259af-93ca-40c5-8989-9e3332c44688.png)
![image](https://user-images.githubusercontent.com/18240991/229958867-e94f7a9c-98f1-484b-ad16-9a9ed0a984e4.png)

问了一些其他问题,感觉gpt3和3.5差距还是挺大

**Comment by yoyosbg** [comment]
> api默认就是3.5，但确实是不如官网的3.5，你可以采用accesstoken的方式去部署，就和官网的一样了，但是可能有封号的风险。

是不是回答国产， 然后输入“继续”，也像断片了

**Comment by EthanDCX** [comment]
> > api默认就是3.5，但确实是不如官网的3.5，你可以采用accesstoken的方式去部署，就和官网的一样了，但是可能有封号的风险。
> 
> 是不是回答国产， 然后输入“继续”，也像断片了

是的,感觉没有上下文分析能力

**Comment by xiaosaaaa** [comment]
你是不是把联系上下文的按钮给关了

**Comment by ottocsb** [comment]
> > > api默认就是3.5，但确实是不如官网的3.5，你可以采用accesstoken的方式去部署，就和官网的一样了，但是可能有封号的风险。
> > 
> > 
> > 是不是回答国产， 然后输入“继续”，也像断片了
> 
> 是的,感觉没有上下文分析能力

回答过长导致上下文丢失需要设置timeout变量

**Comment by yoyosbg** [comment]
> 你是不是把联系上下文的按钮给关了
开着的。就是输入框旁边的时钟按钮。

**Comment by yoyosbg** [comment]
> > > > api默认就是3.5，但确实是不如官网的3.5，你可以采用accesstoken的方式去部署，就和官网的一样了，但是可能有封号的风险。
> > > 
> > > 
> > > 是不是回答国产， 然后输入“继续”，也像断片了
> > 
> > 
> > 是的,感觉没有上下文分析能力
> 
> 回答过长导致上下文丢失需要设置timeout变量

怎么设置，具体是哪一个变量呢

**Comment by xiaosaaaa** [comment]
在你配置api的地方，好像有个timeout吧，不知道说的对不对

**Comment by MataSong** [comment]
我用的就是accesstoken，如何切换到4呢？ 我本身账号开通了4的  @xiaosaaaa

**Comment by yoyosbg** [comment]
> 在你配置api的地方，好像有个timeout吧，不知道说的对不对

想就是默认的
# timeout
TIMEOUT_MS=100000

**Comment by Onicc** [comment]
api效果确实不如官网，同样的描述让他写一段代码，api总是写错，官网一写就对，难顶
