### ISSUE TITLE
关于 多用户管理 功能的开发计划

### ISSUE THREAD

**Issue by Cyberbolt** [Chanzhaoyu/chatgpt-web#1237]
我打算基于该项目，使用 FastAPI 开发 **多用户管理功能**。目的是实现使用多个账号访问该网站，每个账号进行单独的 Tokens 消耗统计（仅仅是统计，并不打算接入支付功能），并支持调整账号的使用限额。

如果后期实现该功能，可以接受 PR 吗？

**Comment by Cyberbolt** [comment]
或者将 **多用户管理功能** 作为该项目的一个扩展，用户可以自行选择是否安装

**Comment by oabu** [comment]
[www.abu.me](url)
已经实现了

**Comment by Cyberbolt** [comment]
> [www.abu.me](http://www.abu.me)
> 已经实现了

你这是商用吧，又不是开源的

**Comment by Easyzhoudongyue** [comment]
期待大佬

**Comment by 3339588491** [comment]
等待大佬

**Comment by tjsky** [comment]
https://github.com/moeakwak/chatgpt-web-share/
这个项目应该已经实现了你的需求，可以看一下可用不

**Comment by Cyberbolt** [comment]
> 

感谢分享，但这个项目是用于共享 ChatGPT Plus 账号，不是官方 API。官方 API 更稳定

**Comment by Cyberbolt** [comment]
> https://github.com/moeakwak/chatgpt-web-share/ 这个项目应该已经实现了你的需求，可以看一下可用不

感谢分享，但这个项目是用于共享 ChatGPT Plus 账号，不是官方 API。官方 API 更稳定

**Comment by liut** [comment]
见 #1279

**Comment by zhouyuanh** [comment]
希望可以支持，不然每个人的聊天都能看的到，无法进行隔离
