### ISSUE TITLE
我配置了nginx，就发现从服务器返回的对话信息不是完整的，造成转json的时候就报错了，通过ip和端口号是可以正常访问的，是nginx哪里配置的不对吗

### ISSUE THREAD

**Issue by tomtry610** [Chanzhaoyu/chatgpt-web#1242]
server {
        listen 80;
        server_name  abc.xyz;
        charset utf-8;
        error_page   500 502 503 504  /50x.html;
        location / {
                        root /usr/share/nginx/html;
                try_files $uri /index.html;
        }

        location /api {
                        proxy_set_header   X-Real-IP $remote_addr; #转发用户IP
                        proxy_pass http://127.0.0.1:3002;
        }

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

**Comment by weibinke** [comment]
增加一句： proxy_buffering off，我是这样解决的。

# 代理转发到ChatGPT页面
        location / {
        proxy_pass http://localhost:3002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        }
