### ISSUE TITLE
默认反向代理的配置问题

### ISSUE THREAD

**Issue by netuseradministrator** [Chanzhaoyu/chatgpt-web#1243]
请问下如何在源码里去除默认的反向代理，我自己的服务器是国外的，不需要配置反代就可以正常去请求opeai的域名，想问下.env的代理设置为空的情况下，怎么在源代码里删除默认的代理

**Comment by netuseradministrator** [comment]
亲测以后，即使是纯真的国外vps，在.env中将API_REVERSE_PROXY=https://chat.openai.com/backend-api/conversation，也就是不使用任何代理，直接带着accesstoken去请求，也是拒绝访问。

**Comment by netuseradministrator** [comment]
所以图方便图免费想用accesstoken，还是用配置好的反向代理

**Comment by zhengmz** [comment]
我设置 `API_REVERSE_PROXY: "https://chat.openai.com/backend-api/conversation"`，报403错误，使用默认就可以
