### ISSUE TITLE
请教下我用railway部署的ui，但是没有打字机效果，是为什么

### ISSUE THREAD

**Issue by doherty88** [Chanzhaoyu/chatgpt-web#1249]
我后台连的是azure的api，用的ishadows/azure-openai-proxy做的proxy，其他都正常，就是gpt返回的结果没有打字机效果，不知道为什么

**Comment by x-hanzh** [comment]
> 我后台连的是azure的api，用的ishadows/azure-openai-proxy做的proxy，其他都正常，就是gpt返回的结果没有打字机效果，不知道为什么

看常见问题，反向代理api配置proxy_buffering off;
![image](https://user-images.githubusercontent.com/21056895/230259117-1ae2c8e0-d5c5-4eb8-8c68-863f113f6d3d.png)

**Comment by zhaobudaomingzi** [comment]
你好，我想请问一下你是怎么将原项目分开成前端和后端的？
