### ISSUE TITLE
怎么内置prompts

### ISSUE THREAD

**Issue by shuaiplus** [Chanzhaoyu/chatgpt-web#1250]
![image](https://user-images.githubusercontent.com/100134295/230099088-3643ccb2-f56b-42e9-b566-0d3e3c046e13.png)
w
这个好像不开代理下载不了，我想把它弄成别人不用下载也能用的，怎么操作

**Comment by PeterDaveHello** [comment]
Try GitHub Proxy?

➡️ https://ghproxy.com/https://raw.githubusercontent.com/PlexPt/awesome-chatgpt-prompts-zh/main/prompts-zh.json

**Comment by FishGiter** [comment]
> 谢谢，我明白你的意思了，但我更想完成的是把prompts内置在服务器上，用户一打开就能用的那种

**Comment by xiaomenggit** [comment]
把prompts  json格式的文件发布在服务器根目录，替换下载链接为这个地址

**Comment by chenggb123** [comment]
我也想知道怎么才能内置一些官方自定义的prompt，可以让用户自己下载
