### ISSUE TITLE
docker的镜像拉不下来,有其他人是这样吗

### ISSUE THREAD

**Issue by xinyun777** [Chanzhaoyu/chatgpt-web#1252]

**Comment by water-root** [comment]
试试挂上代理后，再拉镜像

**Comment by xinyun777** [comment]
> 试试挂上代理后，再拉镜像

老哥,我拉其他的没挂代理也可以的,你这边都是挂代理拉的吗

**Comment by James-handsome** [comment]
一看就会的快速部署指南 https://github.com/James-handsome/chatGPT-Deploy

**Comment by hieivip** [comment]
> 一看就会的快速部署指南 https://github.com/James-handsome/chatGPT-Deploy

我用的宝塔 有没有教程，总感觉有问题，又说不上来。  通过宝塔建立docker ，代码应该怎么放，没用过docker
