### ISSUE TITLE
建议把API_REVERSE_PROXY设置反向代理的默认值去掉

### ISSUE THREAD

**Issue by 765741668** [Chanzhaoyu/chatgpt-web#1253]
有时间把这个默认值去掉吧，因为我本身就部署在美国，不走反向代理了，响应嘎嘎快，基本上秒回答。如果硬编码了，就很伤，一般几秒到10几秒才回复一下，太难熬了。不然每次更新镜像，都需要改下源码，对于有需要走代理的，在配置里面配置一个默认的就行了，没必要硬编码写死，或者使用作者推荐的那两个地址，再或者自建代理服务器啥的都可以。

**Comment by Eobravo** [comment]
请问现在怎么禁用反向代理？

**Comment by lkeai2007** [comment]
你不用代理的话，走的是默认的代理吧

**Comment by xiaosaaaa** [comment]
大部分人需要走代理，默认没什么问题，不能因为你所代表的少数人不需要就更改，你嫌麻烦我还嫌麻烦呢，没毛病吧？

**Comment by tjsky** [comment]
反代主要目的不是解决IP地区限制的问题的，
而是为了解决当较大量访问时，被CF验证的问题，
即使是美国家宽，一旦访问量大了，openai很可能就抛出CF的人机验证
直连是没法过验证的

**Comment by huaccf** [comment]
请教一下，如果我是使用api_key的模式，本地端走socks  是不是也可以不需要这个反代

**Comment by tjsky** [comment]
> 请教一下，如果我是使用api_key的模式，本地端走socks 是不是也可以不需要这个反代

API模式下，不涉及`API_REVERSE_PROXY`

**Comment by huaccf** [comment]
> > 请教一下，如果我是使用api_key的模式，本地端走socks 是不是也可以不需要这个反代
> 
> API模式下，不涉及`API_REVERSE_PROXY`

谢谢

**Comment by 52Lxcloud** [comment]
> 

你自己拉一份下来用ci/cd同步更新不就好了

**Comment by Mr-Cong** [comment]
部署在美国就不需要代理了吗？不对吧，代理的作用是绕过cloudflare人机验证，跟你在哪个地区没有关系

**Comment by HaanJam** [comment]
不看文档吗？使用API_KEY是和OPENAI_API_BASE_URL联系在一起的，默认就是走官方的接口

> 你应该首先使用 API 方式
使用 API 时，如果网络不通，那是国内被墙了，你需要自建代理，绝对不要使用别人的公开代理，那是危险的。
使用 accessToken 方式时反向代理将向第三方暴露您的访问令牌，这样做应该不会产生任何不良影响，但在使用这种方法之前请考虑风险。
使用 accessToken 时，不管你是国内还是国外的机器，都会使用代理。默认代理为 [acheong08](https://github.com/acheong08) 大佬的 https://bypass.churchless.tech/api/conversation，这不是后门也不是监听，除非你有能力自己翻过 CF 验证，用前请知悉。[社区代理](https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy)（注意：只有这两个是推荐，其他第三方来源，请自行甄别）

**Comment by 765741668** [comment]
> 反代主要目的不是解决IP地区限制的问题的， 而是为了解决当较大量访问时，被CF验证的问题， 即使是美国家宽，一旦访问量大了，openai很可能就抛出CF的人机验证 反代是为了绕过CF的验证 大部人在日常使用下是会比较频繁的遇到这个问题的。
> 
> 不过倒是可以做个关闭反代的选项，毕竟运气好的话，确实可能一直不会遇到CF的验证

嗯，是这个意思，并且也只有access_token模式也才会使用到这个，因为是硬编码写死了一个默认值的，这样的话就算没配置也会走代理。自己用的，并没有共享出去，没有超量访问的问题，自己玩的话几秒提一个问题就已很不错了，谁能做到10秒提5个问题，别说响应了，等它打完字都很久了。想着就没必要走代理了，那样太慢了，想改到配置里默认配置一个而已，并不是说就不要代理了，走不走代理由自己决定嘛

**Comment by cvpv** [comment]
> 
我也觉得，你fork一份自己修改更好

**Comment by qy8502** [comment]
我也请求去掉，使用warp的sock5代理可以直接走cf访问。而且购买了plus后还是使用accessToken效果更好。

**Comment by qy8502** [comment]
哪怕我赋值一个NONE也行呀

**Comment by qy8502** [comment]
> 有时间把这个默认值去掉吧，因为我本身就部署在美国，不走反向代理了，响应嘎嘎快，基本上秒回答。如果硬编码了，就很伤，一般几秒到10几秒才回复一下，太难熬了。不然每次更新镜像，都需要改下源码，对于有需要走代理的，在配置里面配置一个默认的就行了，没必要硬编码写死，或者使用作者推荐的那两个地址，再或者自建代理服务器啥的都可以。

你可以这样使用官方的
API_REVERSE_PROXY: https://chat.openai.com/backend-api/conversation

但是美国服务器也会1020。
我现在的问题美国服务器上使用WARP代理配置了也不行
SOCKS_PROXY_HOST: 127.0.0.1
SOCKS_PROXY_PORT: 31303
