### ISSUE TITLE
提问后，回答到一半就停了

### ISSUE THREAD

**Issue by lrfdehao** [Chanzhaoyu/chatgpt-web#1255]
求助一下，问了个回答比较长的问题，但回答了一半就终止了，请问下有最大回复字符串的配置吗？

nginx的外层配置是这样的，不知道会不会有影响？还是说是其它的原因：
```
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   300;
    types_hash_max_size 40960;
    proxy_cache off;
    proxy_buffering off;
    chunked_transfer_encoding on;
```

![image](https://user-images.githubusercontent.com/49232515/230254291-f1267b59-dec6-4c95-878f-c81e8fdb4d78.png)

**Comment by x-hanzh** [comment]
> 

#904 参考这篇，更改TIMEOUT_MS为0，重启服务

**Comment by lrfdehao** [comment]
好的，谢谢老哥，看到了
