### ISSUE TITLE
我用docker build 构建完了之后，然后在run 为什么还要加配置参数 --env，程序不自动读取.env配置文件？

### ISSUE THREAD

**Issue by xueguizheng** [Chanzhaoyu/chatgpt-web#1256]
请问大佬们，我用docker build 构建完了之后，然后在run 为什么还要加配置参数 --env，程序不自动读取.env配置文件吗？.env里不是有配置吗，为啥还要加上 --env OPENAI_API_KEY=  不明白，求大佬解惑。。

**Comment by BruceHan98** [comment]
程序会自动读取.env配置文件，但是每次修改.env配置文件时会重新构建镜像，而通过--env修改环境变量能避免重新构建镜像

**Comment by xueguizheng** [comment]
> 程序会自动读取.env配置文件，但是每次修改.env配置文件时会重新构建镜像，而通过--env修改环境变量能避免重新构建镜像

我修改了.env  我直接 在docker build  然后 run的时候不加 --env能行吗？

**Comment by BruceHan98** [comment]
> 

当然可以

**Comment by BruceHan98** [comment]
> > 程序会自动读取.env配置文件，但是每次修改.env配置文件时会重新构建镜像，而通过--env修改环境变量能避免重新构建镜像
> 
> 我修改了.env 我直接 在docker build 然后 run的时候不加 --env能行吗？

可以

**Comment by BruceHan98** [comment]
你用的哪个版本？在有几个版本中`.env`文件在构建镜像时被排除了，最新版已经修复该问题，可以去看看这个[PR](https://github.com/Chanzhaoyu/chatgpt-web/pull/877)，解决方法就是在`.dockerignore`文件加一行`!.env`

**Comment by xueguizheng** [comment]
> 你用的哪个版本？在有几个版本中`.env`文件在构建镜像时被排除了，最新版已经修复该问题，可以去看看这个[PR](https://github.com/Chanzhaoyu/chatgpt-web/pull/877)，解决方法就是在`.dockerignore`文件加一行`!.env`

最新版，我已经吧 .dockerignore 里面的service里的.env又打开了
