### ISSUE TITLE
建议反馈：希望回答问题的时候可以向上滚动网页

### ISSUE THREAD

**Issue by freedomspiritJohn** [Chanzhaoyu/chatgpt-web#1257]
GPT回答问题的时候无法向上滚动网页

希望可以优化一下，和GPT官网的一样。这样可以在回答问题的时候专心查看文字或以前的答案
![GIF 2023-4-6 11-23-22](https://user-images.githubusercontent.com/129288685/230264877-de692fb7-94f2-42b3-9793-844a90e4943d.gif)

**Comment by Chanzhaoyu** [comment]
这个不是我的项目，是别人二次开发的，建议找作者。

**Comment by freedomspiritJohn** [comment]
> 这个不是我的项目，是别人二次开发的，建议找作者。

是的，但是因为您是一次开发者，二次的都是直接克隆项目，所以只要您这修改这个问题，这些网站在更新代码的时候就都会改过来了

**Comment by Chanzhaoyu** [comment]
> > 这个不是我的项目，是别人二次开发的，建议找作者。
> 
> 是的，但是因为您是一次开发者，二次的都是直接克隆项目，所以只要您这修改这个问题，这些网站在更新代码的时候就都会改过来了

这个已经改过了的
