### ISSUE TITLE
使用access token登录，使用GPT4模型，回答不完整

### ISSUE THREAD

**Issue by nikissXI** [Chanzhaoyu/chatgpt-web#1259]
GPT3.5模型能完整输出回答
![image](https://user-images.githubusercontent.com/31379266/230290750-95fc536c-aeb4-4ff0-b12d-05b1bc5049df.png)
GPT4模型输出一部分就没了，去官网的网页是能正常完整输出的
![image](https://user-images.githubusercontent.com/31379266/230290622-bc3b64e4-d636-4f25-bcf0-3ad171b3316d.png)
GPT4回答一半挂了后去官网能看到一个提示，结果是有完整输出的
![image](https://user-images.githubusercontent.com/31379266/230291012-96b71c63-5f8f-4e12-915b-1eab37d5a883.png)
![image](https://user-images.githubusercontent.com/31379266/230291346-e4651c64-d392-4894-9817-2f622bfe3404.png)

**Comment by Chanzhaoyu** [comment]
`GPT-4` 比较慢，或者你把超时时间设长点

**Comment by nikissXI** [comment]
> `GPT-4` 比较慢，或者你把超时时间设长点

请问需要设置多久，已经设置在120000了。
而且也不应该超时吧，从回答到停止回答整过过程也就大概10秒

**Comment by Sunzhen0402** [comment]
求助大佬，借楼问一句，使用gpt4的access token除了替换环境变量中的OPENAI_ACCESS_TOKEN还需要做啥啊

**Comment by nikissXI** [comment]
> 换环境变量中的OPENAI_ACCESS_TOKEN还

model改成gpt4
