### ISSUE TITLE
有人碰到这个问题吗？Unexpected non-whitespace character after JSON at position 756

### ISSUE THREAD

**Issue by lhlxx2010** [Chanzhaoyu/chatgpt-web#1261]

**Comment by lhlxx2010** [comment]
<img width="436" alt="a0203f7b6e119eabfbdc8d76b5110dd" src="https://user-images.githubusercontent.com/74414383/230311000-3b9875ae-8fd6-4d10-812c-28477d1d61a1.png">

**Comment by Chanzhaoyu** [comment]
获取下最新代码试试？
