### ISSUE TITLE
安卓手机飞书和手机钉钉客户端无法打开chatgpt-web页面地址

### ISSUE THREAD

**Issue by xqm2023** [Chanzhaoyu/chatgpt-web#1262]
安卓手机飞书和手机钉钉客户端无法打开chatgpt-web页面地址，但是在手机自带浏览器、手机微信上都能打开，咨询飞书技术那边说是js高阶语法报错，不兼容安卓chrome webview内核 版本75，意思是和手机飞书自带浏览器不兼容。
然后需要改代码才适配，看下个版本中会不会修复？

**Comment by ottocsb** [comment]
应该修复不了，内核太低了，so为啥要在客户端内打开，浏览器使用不ok吗，隔壁有个飞书的机器人直接接入
