### ISSUE TITLE
咱们这个项目有自动压缩上文的功能吗

### ISSUE THREAD

**Issue by ScalaFirst** [Chanzhaoyu/chatgpt-web#1263]
如题，玩一会角色扮演，token开销就有点大了。

**Comment by JPmorganA** [comment]
用API的话那就可以用这个[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)，作者之前推荐过的，带压缩

**Comment by caiyunfan2** [comment]
> 

这个我也看过了，确实做的很好，但是我要选一个项目做二次开发的话，还是想选现在这个。现在这个项目前后端分离，我把后端改成java也方便。Vue的前端我也比较喜欢

**Comment by caiyunfan2** [comment]
> 用API的话那就可以用这个[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)，作者之前推荐过的，带压缩

next的项目架构看不懂，纯ts把react和后端都嵌进去，太难懂了

**Comment by wujt1084** [comment]
求啊
