### ISSUE TITLE
有人遇到答案回答不全的情况吗？比如写一篇作文，回答了一半就停住了，内容长一些的回答都是这样。

### ISSUE THREAD

**Issue by ruokay1212** [Chanzhaoyu/chatgpt-web#1265]
简短的问题能够回答完整，回答的内容长一些就会突然停止住，不回答了，明显没有回答完整，这是啥情况？

**Comment by yung5133** [comment]
我的也是这样

**Comment by ruokay1212** [comment]
> 

感谢，确实可以了~

**Comment by ruokay1212** [comment]
> 可能是因为TIMEOUT_MS这个环境变量的默认时间太短了，我之前也是这样，改成900000就行了

感谢，确实可以了~

**Comment by cyberkow** [comment]
比较菜，请问是修改哪个文件？我是用docker的。

**Comment by JPmorganA** [comment]
> 比较菜，请问是修改哪个文件？我是用docker的。
同docker的话，docker run的时候在chatgpt-web前面加上--env TIMEOUT_MS=900000就可以了，就像这样

docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=your_api_key --env TIMEOUT_MS=900000 chatgpt-web

**Comment by JPmorganA** [comment]
> 比较菜，请问是修改哪个文件？我是用docker的。

用docker的话，docker run的时候在chatgpt-web前面加上--env TIMEOUT_MS=900000就可以了，就像这样
docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=your_api_key --env TIMEOUT_MS=900000 chatgpt-web

**Comment by cyberkow** [comment]
> > 比较菜，请问是修改哪个文件？我是用docker的。
> 
> 用docker的话，docker run的时候在chatgpt-web前面加上--env TIMEOUT_MS=900000就可以了，就像这样 docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=your_api_key --env TIMEOUT_MS=900000 chatgpt-web

非常感谢，我是用宝塔里面生成的，现在在找里面的配置文件改。

**Comment by cyberkow** [comment]
> 比较菜，请问是修改哪个文件？我是用docker的。

已经找到，宝塔-docker-目录 app/build/index.mjs, 搜索timeout_ms, 将 （timeout_ms=3*1e3) 改成（timeout_ms=3*900000).
docker菜鸟，目前发现这样改可以。

**Comment by JPmorganA** [comment]
> 比较菜，请问是修改哪个文件？我是用docker的。
> 


这个环境变量是改超时时间的单位是毫秒，时间到了就不会再继续输出了，只要本身不出问题设置多大都没关系

**Comment by cyberkow** [comment]
> > 比较菜，请问是修改哪个文件？我是用docker的。
> 
> 这个环境变量是改超时时间的单位是毫秒，时间到了就不会再继续输出了，只要本身不出问题设置多大都没关系

是的，就是一直没有想到是这个节点出问题，一直想改 env里面的VITE_GLOB_OPEN_LONG_REPL，方向性错误。
感谢JPmorganA的热心，还有楼主的正确方向。

**Comment by nikissXI** [comment]
> > > 比较菜，请问是修改哪个文件？我是用docker的。
> > 
> > 
> > 这个环境变量是改超时时间的单位是毫秒，时间到了就不会再继续输出了，只要本身不出问题设置多大都没关系
> 
> 是的，就是一直没有想到是这个节点出问题，一直想改 env里面的VITE_GLOB_OPEN_LONG_REPL，方向性错误。 感谢JPmorganA的热心，还有楼主的正确方向。

VITE_GLOB_OPEN_LONG_REPL是什么变量？
