### ISSUE TITLE
docker 内连不上代理

### ISSUE THREAD

**Issue by InfraBackend** [Chanzhaoyu/chatgpt-web#1267]
FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 172.17.0.1:1080

我用的也是宿主机ip，应该没错啊，求指点

**Comment by water-root** [comment]
和你的情况一样，我是把容器的网络模式设置为host，代理直接写http://localhost:port，就可以正常运行了

**Comment by civetming** [comment]
> 

怎么把容器的网络模式设置为host

**Comment by Lockeysama** [comment]
如果是 macos 的话，得用 docker.for.mac.host.internal 才行

**Comment by civetming** [comment]
> 和你的情况一样，我是把容器的网络模式设置为host，代理直接写[http://localhost:port，就可以正常运行了](http://localhost:port%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C%E4%BA%86)

你好请问怎么解决的

**Comment by water-root** [comment]
> > 和你的情况一样，我是把容器的网络模式设置为host，代理直接写[http://localhost:port，就可以正常运行了](http://localhost:port%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C%E4%BA%86)
> 
> 你好请问怎么解决的

在docker-compose.yml文件中加入network_mode: "host"

**Comment by civetming** [comment]
> > > 和你的情况一样，我是把容器的网络模式设置为host，代理直接写[http://localhost:port，就可以正常运行了](http://localhost:port%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C%E4%BA%86)
> > 
> > 
> > 你好请问怎么解决的
> 
> 在docker-compose.yml文件中加入network_mode: "host"

version: '3'

services:
  app:
    container_name: chatgpt-web
    image: chenzhaoyu94/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: 
      # 二选一
      OPENAI_ACCESS_TOKEN:
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL:
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL:
      # 反向代理，可选
      API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation
      # 访问权限密钥，可选
      AUTH_SECRET_KEY:
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST:
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT:
      # Socks代理用户名，可选，和 SOCKS_PROXY_HOST & SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_USERNAME:
      # Socks代理密码，可选，和 SOCKS_PROXY_HOST & SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_PASSWORD:
      # HTTPS_PROXY 代理，可选
      HTTPS_PROXY: 
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

我加里面报错了  请问具体在哪里 谢谢大佬

**Comment by James-handsome** [comment]
一看就会的快速部署指南 https://github.com/James-handsome/chatGPT-Deploy

**Comment by lemonwan** [comment]
修改docker-compose.yaml文件内容，新增如下内容
<img width="729" alt="image" src="https://user-images.githubusercontent.com/23022365/232173107-4c25d650-9385-4630-8fff-ac43f5400048.png">
配置好HTTPS_PROXY，然后保存修改，最后重启你的docker容器。前提是你的宿主机已经开通了代理哈，个人推荐clash。
