### ISSUE TITLE
小白 不知道如何部署 到自己服务器

### ISSUE THREAD

**Issue by Apple-ljj** [Chanzhaoyu/chatgpt-web#1269]
小白 不知道如何部署 到自己服务器，有没有大神可以做一份教程

**Comment by zaiMoe** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/issues/1230

**Comment by moeik** [comment]
打包了docker
```
docker run --name chatweb -d -p 8080:8080  --env AUTH_SECRET_KEY=<YOUR PASSWORD> --env OPENAI_API_KEY=<YOUR OPENAI API KEY> jucore/chatgpt_web
```

**Comment by smartfat** [comment]
> 打包了docker
> 
> ```
> docker run --name chatweb -d -p 8080:8080  --env AUTH_SECRET_KEY=<YOUR PASSWORD> --env OPENAI_API_KEY=<YOUR OPENAI API KEY> jucore/chatgpt_web
> ```

小白问一下，这个运行后如何修改里面的配置文件

**Comment by dqzboy** [comment]
源码一键构建部署：[支持centos7、Ubuntu](https://github.com/dqzboy/ShellProject/tree/main/ChatGPT/ChatGPT-WEB)

**Comment by fzucs** [comment]
我也是小白，我觉得docker-compose最方便

**Comment by necopp** [comment]
**我来写一个docker-compose部署的教程吧，小白也可可以，当然我也是小白**，
 第一步_:安装docker 你只需要复制命令行执行即可，
命令行:安装命令如下：

**curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun**
也可以使用国内 daocloud 一键安装命令：

**curl -sSL https://get.daocloud.io/docker | sh**
上面的命令选一个执行
第二步 安装docker-compose
**curl -L https://get.daocloud.io/docker/compose/releases/download/v2.4.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose**

将可执行权限应用于二进制文件：

$ sudo chmod +x /usr/local/bin/docker-compose
创建软链：

$ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
测试是否安装成功：

$ docker-compose version
cker-compose version 1.24.1, build 4667896b
第三步，在你的服务器找一个地方，创建一个docker-compose.yml文件把如下内容复制进去
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 127.0.0.1:3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: sk-xxx
      # 二选一
      OPENAI_ACCESS_TOKEN: xxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: xxx
      # API模型，可选，设置 OPENAI_API_KEY 时可用，https://platform.openai.com/docs/models
      # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, code-davinci-002
      OPENAI_API_MODEL: xxx
      # 反向代理，可选
      API_REVERSE_PROXY: xxx
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: xxx
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: xxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: xxx
      # HTTPS 代理，可选，支持 http，https，socks5
      HTTPS_PROXY: http://xxx:7890

**说明**:如果你的服务器在国内，你还没有代理ip，那我推荐你这样配置
    **# API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://openai.1rmb.tk**
  
      **# 反向代理，可选
      API_REVERSE_PROXY: https://openai.1rmb.tk/api/conversation
上面这个社区代理也可以换成其他，还可以自己搭建，github上有其他大佬发了。**
**好了再说你不会，你去吃老八蜜汁小汉堡吧。**

**Comment by necopp** [comment]
不好意思哈 忘记最后一步。cd到你的yml文件目录 然后docker-compose up -d

**Comment by zhangyongsen** [comment]
> 不好意思哈 忘记最后一步。cd到你的yml文件目录 然后docker-compose up -d
你好，我成功部署了网页，但是显示时间超时，我按照这个配置，请问是需要服务器翻墙吗？
![Uploading 451b77c
![Uploading 8c699fb537b79a93815f0e5584db725.png…]()
e8efaa4e25541a15c287d2a5.png…]()

**Comment by zhangyongsen** [comment]
![451b77ce8efaa4e25541a15c287d2a5](https://user-images.githubusercontent.com/72311727/230864736-d2d596aa-f03d-48c4-a6cf-f8c5ae17529d.png)

**Comment by zhangyongsen** [comment]
![8c699fb537b79a93815f0e5584db725](https://user-images.githubusercontent.com/72311727/230864762-4dd238df-7314-4b50-91ad-790cdf4cdf5b.png)
