### ISSUE TITLE
每小时最大请求数这个一般设置多少？

### ISSUE THREAD

**Issue by leealu** [Chanzhaoyu/chatgpt-web#1271]
如题，怎么设置会流畅使用，但是不会用超？

**Comment by Chanzhaoyu** [comment]
这个是用来限制别人使用的，自用不需要吧

**Comment by leealu** [comment]
> 这个是用来限制别人使用的，自用不需要吧

对，我就是要限制别人，公用

**Comment by GavinZJZhang** [comment]
官方限制20次每分钟

**Comment by Chanzhaoyu** [comment]
默认无限制，看你自己设定。不过别人换节点就能摆脱。

**Comment by leealu** [comment]
> 默认无限制，看你自己设定。不过别人换节点就能摆脱。

那有没有能用户名或者其他限制的
