### ISSUE TITLE
docker部署了，出现这个问题怎么解决呀？

### ISSUE THREAD

**Issue by MataSong** [Chanzhaoyu/chatgpt-web#1273]
ChatGPT error 429: {
"error": {
"message": "Your account is not active, please check your billing details on our website.",
"type": "billing_not_active",
"param": null,
"code": null
}
}

**Comment by leslieeilsel** [comment]
openai 账号问题，跟此项目无关

**Comment by MataSong** [comment]
谢谢 已解决了。  @leslieeilsel

**Comment by huangwb8** [comment]
@MataSong 大佬怎么解决的，是绑定了信用卡吗？
