### ISSUE TITLE
大家千万别用，这个工具盗key，我1号就发现使用了2美金，我马上改了KEY ，KEY就只填写到了这个上面

### ISSUE THREAD

**Issue by kuaiyun33** [Chanzhaoyu/chatgpt-web#1275]
大家千万别用，这个工具盗key，我1号就发现都没使用既然消费了1.2美金，我马上改了KEY ，KEY就只填写到了这个上面，首先我有PULS会员，我根本就没用KEY，5号我上后台发现既然每天都在消费1-2美金左右，6号我把我KEY又换掉没填这个上面6号消费为0.01，所以我很肯定是这个盗KEY。我有一句假话我不得好死。

**Comment by kuaiyun33** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/126439012/230522014-0b0bf3ac-7062-4cd4-8a0a-7546cfeb04b9.png">
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/126439012/230522253-55497c33-eb9e-443a-a81c-c8dfdddc6d47.png">

**Comment by git-syl** [comment]
我没有这个情况，不过以防万一，到时候仔细看看项目源码。

我猜，你这个大概率被别人扫到了。

你网站是否设置了复杂的密码？网页title的有没有修改？

**Comment by kuaiyun33** [comment]
> 我没有这个情况，不过以防万一，到时候仔细看看项目源码。
> 
> 我猜，你这个大概率被别人扫到了。
> 
> 你网站是否设置了复杂的密码？网页title的有没有修改？

首先网站地址我没有发过给别人，另外在日志中未发现有其他人的对话，我就自己写了脚本利用API每天定时生成3篇文章，当时我就想着玩意这么贵吗3篇文章每天花我1块钱，直到昨天我换掉了KEY，并没有将KEY填写到这个项目中，消费就正常了。

**Comment by HisKingdom** [comment]
源码都在这里，应该不至于吧

**Comment by dqzboy** [comment]
自己好好看看源码 自己网站有可能被扫了  不是说你没给过别人  就不会被扫

**Comment by fzucs** [comment]
你网站有设权限验证吗，没有的话就算没发给过别人也有可能被扫到然后拿去用，我的设了密码所以目前倒是没这情况

**Comment by Chanzhaoyu** [comment]
我盗你 key ，何必呢？源码全在这，你自己看下不行吗？

P.S. 端口被人扫到了而已，`README` 说的清清楚楚设置访问密钥，修改 `title`

**Comment by nikissXI** [comment]
傻鸟，自己没设置访问秘钥说别人盗你key

**Comment by gmksbk** [comment]
改端口，随便换个5位数的，环境变量AUTH_SECRET_KEY加个密码不就好了。。别武断别误导..

**Comment by Chanzhaoyu** [comment]
> 

没必要，没必要，可能是没有看 `README` ，不过这个项目确实一直被人盯着扫描。

**Comment by AutMaple** [comment]
挂公网，又没有一点安全意识，怪作者？😂

**Comment by jurieo** [comment]
改端口，改title，加密码。。

**Comment by dashug** [comment]
哈哈，笑死了，你要加个密码，我也遇到过，加了个密码就没事了

**Comment by x-hanzh** [comment]
建议在nginx里面加一层IP限制

**Comment by kuaiyun33** [comment]
> 傻鸟，自己没设置访问秘钥说别人盗你key。 这样咒骂自己，笑死 ![image](https://user-images.githubusercontent.com/31379266/230529732-577ff8df-ed48-485b-bfb1-c24aed493f21.png)

我又没说一句假话，我说这句话有什么问题吗？

**Comment by nikissXI** [comment]
> > 傻鸟，自己没设置访问秘钥说别人盗你key。 这样咒骂自己，笑死 ![image](https://user-images.githubusercontent.com/31379266/230529732-577ff8df-ed48-485b-bfb1-c24aed493f21.png)
> 
> 我又没说一句假话，我说这句话有什么问题吗？

《没一句假话》，哈哈哈哈哈哈
![image](https://user-images.githubusercontent.com/31379266/230558760-10633b03-3ca8-4c44-8243-c23c5c8130a1.png)

**Comment by git-syl** [comment]
> > 我没有这个情况，不过以防万一，到时候仔细看看项目源码。
> > 我猜，你这个大概率被别人扫到了。
> > 你网站是否设置了复杂的密码？网页title的有没有修改？
> 
> 首先网站地址我没有发过给别人，另外在日志中未发现有其他人的对话，我就自己写了脚本利用API每天定时生成3篇文章，当时我就想着玩意这么贵吗3篇文章每天花我10块钱，直到昨天我换掉了KEY，并没有将KEY填写到这个项目中，消费就正常了。

但凡你挂公网，就有会有扫人你。这是互联网常识。你这大概率被扫了，你如果日志没关的话可以看调用日志。
