### ISSUE TITLE
这两天多个域名被污染，有相同情况吗？

### ISSUE THREAD

**Issue by moeik** [Chanzhaoyu/chatgpt-web#1276]
最近有好几个域名被污染了，因为部署这个项目，不知是否有相同情况?
都设置了访问鉴权的。。。。

![image](https://user-images.githubusercontent.com/49871008/230522410-8f7a55c9-d86a-40d7-9965-c3a7525644cc.png)

**Comment by Chanzhaoyu** [comment]
只要和 chatgpt 有关都有可能会被 DNS 污染

**Comment by luckywangxi** [comment]
我也挂了域名

**Comment by Bisstocuz** [comment]
是不是 `.cn` 域名，这个部署到国外服务器有概率被直接劫持。

**Comment by moeik** [comment]
不是cn域名 .pro .online都是 
估计是扫到什么特征了


 

-------- 原始邮件 --------
发件人：Notealot ***@***.***>
时间：2023年4月7日 12:28
收件人：Chanzhaoyu/chatgpt-web ***@***.***>
抄送：Aroins ***@***.***>,Author ***@***.***>
主题：Re: [Chanzhaoyu/chatgpt-web] 这两天多个域名被污染，有相同情况吗？ (Issue #1276)

**Comment by ycvk** [comment]
同样，.art 被污染了，换成.online后，就我自己用，一天后又被污染

**Comment by Yharr7** [comment]
一样，网站设置了访问密码，且只分享给了个别朋友使用，于4月6日被墙（**DNS污染+SNI阻断**）

**Comment by kajisan** [comment]
在CF上屏蔽了weixin的UA..目前还活着.仅供参考..

**Comment by tjsky** [comment]
通过nginx反代时替换了页面title，favicon这两个项目，域名含有chatgpt字段，目前还活着，供参考

**Comment by moeik** [comment]
title我已经修改 就是favicon没改


 

-------- 原始邮件 --------
发件人：去年夏天 ***@***.***>
时间：2023年4月9日 11:42
收件人：Chanzhaoyu/chatgpt-web ***@***.***>
抄送：Aroins ***@***.***>,Author ***@***.***>
主题：Re: [Chanzhaoyu/chatgpt-web] 这两天多个域名被污染，有相同情况吗？ (Issue #1276)

**Comment by Bisstocuz** [comment]
你们是在国内注册商注册的吗？我在 namecheap 上的域名一点事没有。
