### ISSUE TITLE
OPENAI_API_MODEL   支持 gpt-4么

### ISSUE THREAD

**Issue by xietianyue** [Chanzhaoyu/chatgpt-web#1277]
如题   支持gpt-4么

**Comment by xietianyue** [comment]
![image](https://user-images.githubusercontent.com/53558082/230527072-a74c2525-1411-478a-be67-4d1ddecf1b8d.png)

**Comment by xietianyue** [comment]
![image](https://user-images.githubusercontent.com/53558082/230527168-b63a5021-64ef-4ffd-b50b-fdcde39c29b4.png)
![image](https://user-images.githubusercontent.com/53558082/230527230-6e237e9e-dd2c-49d8-92e9-e2652255e807.png)
我看文档是支持的  但是报错了，说找不到该模型
![image](https://user-images.githubusercontent.com/53558082/230527301-8e6f0ecd-76f1-4942-a35b-81c112f44c83.png)

**Comment by nikissXI** [comment]
支持的呀 OPENAI_API_MODEL: gpt-4

**Comment by xietianyue** [comment]
@nikissXI   用的是apikey 啊    你看看我的service   没填错啊    就是报错 not exist

**Comment by nikissXI** [comment]
> @nikissXI 用的是apikey 啊 你看看我的service 没填错啊 就是报错 not exist

你这个apikey是gpt4的？

**Comment by xietianyue** [comment]
@nikissXI   
![image](https://user-images.githubusercontent.com/53558082/230530003-a2f32482-7c74-4495-81dd-739d191bce0d.png)
我在这个地址申请的key   请问一下 gpt-4 的key 是指定页面申请的么

**Comment by nikissXI** [comment]
> @nikissXI ![image](https://user-images.githubusercontent.com/53558082/230530003-a2f32482-7c74-4495-81dd-739d191bce0d.png) 我在这个地址申请的key 请问一下 gpt-4 的key 是指定页面申请的么

这是gpt3.5的，gpt4的一堆人排着队都拿不到呢，可以开个plus，然后用accessToken登录就可以用gpt4了，一个月也就20刀（狗头）

**Comment by xietianyue** [comment]
@nikissXI   明白了，谢谢   升级plus通道 好像现在也关闭了，，我也想升级
