### ISSUE TITLE
能否添加oAuth2.0认证的支持

### ISSUE THREAD

**Issue by dashi6174** [Chanzhaoyu/chatgpt-web#1279]

**Comment by liut** [comment]
是个好建议，我在morrigan后端已经实现了，本项目待实现，mark一下，如果没其他人接手，我打算利用周末时间实现看看

**Comment by Cyberbolt** [comment]
你可以开发一下。ChatGPT Web 这个项目有的地方和我想象中不同，如果有空我打算自己写一个带用户管理的 GPT 系统

**Comment by LinLin00000000** [comment]
可以直接使用开源框架 [Logto](https://github.com/logto-io/logto)，我自己就接入了

**Comment by liut** [comment]
> 可以直接使用开源框架 [Logto](https://github.com/logto-io/logto)，我自己就接入了

看它的说明是Auth0的替代，那就表示它是SP的角色；而这里讨论的OAuth2是指对包括Auth0在内的SP的**连接**支持（例如github/google/fb甚至微信等等）；你接入的意思难道不是作为Client么？或者我没理解你的意思？

**Comment by LinLin00000000** [comment]
> 



> > 可以直接使用开源框架 [Logto](https://github.com/logto-io/logto)，我自己就接入了
> 
> 看它的说明是Auth0的替代，那就表示它是SP的角色；而这里讨论的OAuth2是指对包括Auth0在内的SP的**连接**支持（例如github/google/fb甚至微信等等）；你接入的意思难道不是作为Client么？或者我没理解你的意思？

![image](https://user-images.githubusercontent.com/51076594/230701294-448cae4c-fb7c-41b8-a2a0-8036c8ed008b.png)
你说的是这个？

**Comment by liut** [comment]
> > > 可以直接使用开源框架 [Logto](https://github.com/logto-io/logto)，我自己就接入了
> > 
> > 
> > 看它的说明是Auth0的替代，那就表示它是SP的角色；而这里讨论的OAuth2是指对包括Auth0在内的SP的**连接**支持（例如github/google/fb甚至微信等等）；你接入的意思难道不是作为Client么？或者我没理解你的意思？
> 
> ![image](https://user-images.githubusercontent.com/51076594/230701294-448cae4c-fb7c-41b8-a2a0-8036c8ed008b.png) 你说的是这个？

![WX20230408-132934@2x](https://user-images.githubusercontent.com/114243/230705124-798b875c-c265-42fe-90a3-b16c3dbd36cf.png)

这是它的连接器功能，但它本身是作为一个Auth服务存在的（只不过它允许连接其他更多的SP）；就比如此项目作为一个相对独立的app可以用Logto来认证登录，但相应的连接代码和逻辑需要单独实现，包括但不限于以下流程：
1. 实现检测登录状态，并自动跳转到相应的认证处理路由
2. 使用适当配置的OAuth2配置项，跳转到相应的SP认证网站
3. 接收SP回调请求，根据传入的票据拿到有效用户信息，完成认证

**Comment by LinLin00000000** [comment]
> > > > 可以直接使用开源框架 [Logto](https://github.com/logto-io/logto)，我自己就接入了
> > > 
> > > 
> > > 看它的说明是Auth0的替代，那就表示它是SP的角色；而这里讨论的OAuth2是指对包括Auth0在内的SP的**连接**支持（例如github/google/fb甚至微信等等）；你接入的意思难道不是作为Client么？或者我没理解你的意思？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51076594/230701294-448cae4c-fb7c-41b8-a2a0-8036c8ed008b.png) 你说的是这个？
> 
> ![WX20230408-132934@2x](https://user-images.githubusercontent.com/114243/230705124-798b875c-c265-42fe-90a3-b16c3dbd36cf.png)
> 
> 这是它的连接器功能，但它本身是作为一个Auth服务存在的（只不过它允许连接其他更多的SP）；就比如此项目作为一个相对独立的app可以用Logto来认证登录，但相应的连接代码和逻辑需要单独实现，包括但不限于以下流程：
> 
> 1. 实现检测登录状态，并自动跳转到相应的认证处理路由
> 2. 使用适当配置的OAuth2配置项，跳转到相应的SP认证网站
> 3. 接收SP回调请求，根据传入的票据拿到有效用户信息，完成认证

是啊，功能齐全，满足账户系统的要求吧

**Comment by liut** [comment]
功能是挺全的，但是，不是所有团队环境都用它啊，如果环境本身已经有了一个标准或非标准的OAuth2 SP了呢，那加这个Logto就会变得很尴尬吧。

**Comment by LinLin00000000** [comment]
> 功能是挺全的，但是，不是所有团队环境都用它啊，如果环境本身已经有了一个标准或非标准的OAuth2 SP了呢，那加这个Logto就会变得很尴尬吧。

确实，这个是一个比较重的解决方案，适合从零开始且没有从做过账户系统的开发者

**Comment by liut** [comment]
#1483
