### ISSUE TITLE
是否有考虑创建微信群来互相沟通

### ISSUE THREAD

**Issue by dashi6174** [Chanzhaoyu/chatgpt-web#1281]

**Comment by dqzboy** [comment]
我看创建TG比较安全些

**Comment by FishGiter** [comment]
群啥的没啥用。加了两三个，全都是问有没有梯子的，问技术的很少，还不如直接在github交流

**Comment by cvpv** [comment]
是的，可以创建tg,有点门槛

**Comment by MataSong** [comment]
能创一个吗？ 我等着问问题呢 技术问题。

**Comment by gouguoyin** [comment]
有800多人的QQ群 145225165

**Comment by kkxs888** [comment]
人不多，就几十个人
![7f37b0f72dc4b41f91afd9870a41c94](https://user-images.githubusercontent.com/110708228/230724279-1f5bf93e-4b09-4011-956d-ffc9619957ac.jpg)

**Comment by gouguoyin** [comment]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/13517412/230752785-0bfb1d14-bff3-4f07-8968-04aa815ee54c.png">
145225165
