### ISSUE TITLE
这几天会出现语句说不完全的问题

### ISSUE THREAD

**Issue by MoreChanger** [Chanzhaoyu/chatgpt-web#1283]
好像就这几天，经常会出现这种，不知道是openai官方的问题还是什么需要单独设置什么，网络应该是没啥问题，使用的api方式
![image](https://s1.ax1x.com/2023/04/07/ppT1tHO.png)

**Comment by AutMaple** [comment]
#1039 给出了答案，只需要将 TIMEOUT_MS 变量的值设置为 0 即可: TIMEOUT_MS = 0.

**Comment by AutMaple** [comment]
#1039  给出了答案，只需设置一下变量的值就行：
```text
TIMEOUT_MS = 0
```

**Comment by MoreChanger** [comment]
> 

感谢

**Comment by nikissXI** [comment]
> #1039 给出了答案，只需设置一下变量的值就行：
> 
> ```
> TIMEOUT_MS = 0
> ```

大佬，没用呀，设置0，90000，120000都没用，3.5和4都会断，用的accessToken

**Comment by nikissXI** [comment]
> > 
> 
> 感谢

你的解决了吗，我的还是会回答一半就断开

**Comment by MoreChanger** [comment]
> > > 
> > 
> > 
> > 感谢
> 
> 你的解决了吗，我的还是会回答一半就断开

我用的api，貌似没有再出现断句了，token的话多半是网络问题吧

**Comment by AutMaple** [comment]
> > #1039 给出了答案，只需设置一下变量的值就行：
> > ```
> > TIMEOUT_MS = 0
> > ```
> 
> 大佬，没用呀，设置0，90000，120000都没用，3.5和4都会断，用的accessToken

我这边用的是 api-key, 没有用 accessToken. 不知道是不是 accessToken 的问题

**Comment by nikissXI** [comment]
> > > #1039 给出了答案，只需设置一下变量的值就行：
> > > ```
> > > TIMEOUT_MS = 0
> > > ```
> > 
> > 
> > 大佬，没用呀，设置0，90000，120000都没用，3.5和4都会断，用的accessToken
> 
> 我这边用的是 api-key, 没有用 accessToken. 不知道是不是 accessToken 的问题

qwq

**Comment by nikissXI** [comment]
> > > > 
> > > 
> > > 
> > > 感谢
> > 
> > 
> > 你的解决了吗，我的还是会回答一半就断开
> 
> 我用的api，貌似没有再出现断句了，token的话多半是网络问题吧

之前都没问题的，就这几天这样

**Comment by MoreChanger** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 感谢
> > > 
> > > 
> > > 你的解决了吗，我的还是会回答一半就断开
> > 
> > 
> > 我用的api，貌似没有再出现断句了，token的话多半是网络问题吧
> 
> 之前都没问题的，就这几天这样

你用“继续”能续上之前的话吗

**Comment by AutMaple** [comment]
@nikissXI 你搜一下 issue 里面有没有关于 accessToken 的解决方案，或者检查一下你的梯子是否稳定

**Comment by tang5011235** [comment]
我api-key 的形式还是会断开  timeout 设置的0  只能说比未设置采用默认之前的配置要好些

**Comment by MoreChanger** [comment]
可能是官方问题吧，这俩天明显感觉速度变慢了很多，3.5也是。

**Comment by nikissXI** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 感谢
> > > > 
> > > > 
> > > > 你的解决了吗，我的还是会回答一半就断开
> > > 
> > > 
> > > 我用的api，貌似没有再出现断句了，token的话多半是网络问题吧
> > 
> > 
> > 之前都没问题的，就这几天这样
> 
> 你用“继续”能续上之前的话吗

是断了，我去官网是可以看到完整回答的，但在这个项目里不行

**Comment by nikissXI** [comment]
> @nikissXI 你搜一下 issue 里面有没有关于 accessToken 的解决方案，或者检查一下你的梯子是否稳定

都是说改timeout，但我怎么改都不好使

**Comment by nikissXI** [comment]
![image](https://user-images.githubusercontent.com/31379266/230575826-58ab50f8-8e81-4503-a80c-03187c5760e6.png)
![image](https://user-images.githubusercontent.com/31379266/230575861-5924b76e-0f62-4f1d-bc3a-695d7d8b174c.png)

**Comment by AutMaple** [comment]
@nikissXI 你有看你的日志吗？我出现问题，看日志发现是 timeout 的问题，你看看你的日志报的是什么错，有可能和我们的不一样😁

**Comment by nikissXI** [comment]
> @nikissXI 你有看你的日志吗？我出现问题，看日志发现是 timeout 的问题，你看看你的日志报的是什么错，有可能和我们的不一样😁

能教教怎么看日志吗，我是用docker搭建的，不知道怎么看

**Comment by AutMaple** [comment]
@nikissXI 输入下面的命令：

```bash
docker logs <container_name>
# Or in the folder where the docker-compose.yaml file is located
docker compose logs
```

**Comment by nikissXI** [comment]
> @nikissXI 输入下面的命令：
> 
> ```shell
> docker logs <container_name>
> # Or in the folder where the docker-compose.yaml file is located
> docker compose logs
> ```

![image](https://user-images.githubusercontent.com/31379266/230578374-bd4644e8-df94-4bf1-af97-c5b20c9c4c9f.png)

**Comment by AutMaple** [comment]
@nikissXI 你这里是报的是 JSON 解析出错，你看看 issue 上有没有对应的解决方案，或者看看正常的回复是否会出现这个报错。我这边正常回复是没有任何报错的。

**Comment by nikissXI** [comment]
> @nikissXI 你这里是报的是 JSON 解析出错，你看看 issue 上有没有对应的解决方案，或者看看正常的回复是否会出现这个报错。我这边正常回复是没有任何报错的。

噢，谢谢大佬

**Comment by nikissXI** [comment]
回退上一个版本解决了chenzhaoyu94/chatgpt-web:v2.10.8

**Comment by hncboy** [comment]
> 回退上一个版本解决了chenzhaoyu94/chatgpt-web:v2.10.8

直接拉 main 分支的代码，commit 有针对这个 bug 的修复。
