### ISSUE TITLE
上报错误ChatGPT error 400，怎么解决，在线等！

### ISSUE THREAD

**Issue by vwzvwz** [Chanzhaoyu/chatgpt-web#1287]
不管问什么问题，都是回答下面
---------------------------------------
                  ChatGPT error 400: <html>
                  <head><title>400 Bad Request</title></head>
                  <body>
                  <center><h1>400 Bad Request</h1></center>
                  <hr><center>cloudflare</center>
                  </body>
                  </html>
----------------------------

网络已确认没有问题

**Comment by vwzvwz** [comment]
ChatGPT error 400: <html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

**Comment by vwzvwz** [comment]
问题太简单了，都不愿意回复一下。。。。。。。。。。。。。。。

**Comment by Cheng-x-c** [comment]
> 问题太简单了，都不愿意回复一下。。。。。。。。。。。。。。。

什么问题呢老哥，我使用nginx转发到代理报错ChatGPT error 400
