### ISSUE TITLE
浏览器兼容性问题

### ISSUE THREAD

**Issue by cvpv** [Chanzhaoyu/chatgpt-web#1288]
目前项目是基于vite的，只兼容现代浏览器。作者考虑增加兼容性插件开关，对于类似chrome64等老旧浏览器，做个扩展性设置吗？（使用中，经常出现三个点不动的情况）比如增加browserslistrc 配置文件

**Comment by Chanzhaoyu** [comment]
你可以自己加个 [兼容插件](https://cn.vitejs.dev/plugins/#:~:text=%40vitejs/plugin%2Dlegacy)

**Comment by Chanzhaoyu** [comment]
你可以自己加个 [兼容插件](https://cn.vitejs.dev/plugins/#:~:text=%40vitejs/plugin%2Dlegacy)
