### ISSUE TITLE
前端修改路由模式为createWebHistory，build之后页面404

### ISSUE THREAD

**Issue by doyuli** [Chanzhaoyu/chatgpt-web#1290]
项目使用的`createWebHashHistory`路由模式，地址栏中间会多个`#`，想去掉这个，直接切换路由模式会导致页面404，是漏掉了什么配置吗

另外，作者大大有考虑加一个 在设置界面自定义配置key的功能吗

**Comment by x-hanzh** [comment]
nginx location 应该要加上try_files $uri $uri/ /index.html; 试试

**Comment by Chanzhaoyu** [comment]
参考这个 [路由模式](https://router.vuejs.org/zh/guide/essentials/history-mode.html)
