### ISSUE TITLE
/chat-process 报错

### ISSUE THREAD

**Issue by zzmbulldog** [Chanzhaoyu/chatgpt-web#1293]
ChatGPT error 404: {\"ErrorCode\":\"DomainNameNotFound\",\"ErrorMessage\":\"domain name 'api.openai.com' does not exist\"}
请问这个报错是为啥啊

**Comment by Chanzhaoyu** [comment]
有没有自己设置 `OPENAI_API_BASE_URL` 这个参数，默认是不填

**Comment by zzmbulldog** [comment]
> 有没有自己设置 `OPENAI_API_BASE_URL` 这个参数，默认是不填

无设置。本地环境启动，配置了OPENAI_API_KEY和HTTPS_PROXY
