### ISSUE TITLE
chatpgpt-web不支持显示同一问题重新回答历史纪录吗？

### ISSUE THREAD

**Issue by xqm2023** [Chanzhaoyu/chatgpt-web#1298]
chatpgpt-web不支持显示同一问题重新回答历史纪录吗？比如像chatgpt官网那重新回答会显示回答次数及历史回答内容。

**Comment by JS-an** [comment]
![image](https://user-images.githubusercontent.com/25688878/230700993-70489e6d-18c1-48da-bf40-7e20dcf10f0d.png)
你觉得这种还OK吗
