### ISSUE TITLE
没有上下文信息了最新版本v2.10.9

### ISSUE THREAD

**Issue by sunnoy** [Chanzhaoyu/chatgpt-web#1299]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/19342276/230577892-f9c9c50c-8670-4604-9588-11cd3c6ff825.png">

**Comment by dashug** [comment]
我也遇到这个问题，从2.10.8开始的吧，超时时间设置三分钟了

**Comment by sunnoy** [comment]
这个超时3分钟如何理解呢 一个对话的总的三分钟，还是从回答继续

**Comment by sunnoy** [comment]
TIMEOUT_MS = 0 可以了

**Comment by guipie** [comment]
> TIMEOUT_MS = 0 可以了

设置了，还是不行额
![image](https://user-images.githubusercontent.com/55727172/230708434-832b8bf5-fce1-4ccf-89e5-440569446dea.png)

**Comment by rocket2023** [comment]
api方式没上下文，access_token正常带上下文。你们怎么解决的
