### ISSUE TITLE
vite.config.ts此文件大佬是不是漏修改一处？

### ISSUE THREAD

**Issue by fj9876** [Chanzhaoyu/chatgpt-web#13]
里面的端口是1002，运行报错，改为3002就能运行

**Comment by Chanzhaoyu** [comment]
`vite.config.ts` 里面的端口是网页的，你的报错截图有吗

**Comment by fj9876** [comment]
error when starting dev server:
Error: listen EACCES: permission denied 0.0.0.0:1002
    at Server.setupListenHandle [as _listen2] (node:net:1723:21)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Chanzhaoyu** [comment]
我测试是正常的哦，你看下是不是 `node` 版本问题

**Comment by wanmyj** [comment]
As a reminder, I also met this issue. From this [link](https://stackoverflow.com/questions/60372618/nodejs-listen-eacces-permission-denied-0-0-0-080) I read this: `Non-privileged user (not root) can't open a listening socket on ports below 1024.`
