### ISSUE TITLE
看到版本升级了,已经部署到vps上的怎么升级

### ISSUE THREAD

**Issue by Nicolas-XF** [Chanzhaoyu/chatgpt-web#1302]
看到版本升级了,已经部署到vps上的怎么升级,小白,用的是debain

**Comment by joezjy** [comment]
如果是docker，那就docker-compose pull

**Comment by GitHubChrisChen8035** [comment]
> 如果是docker，那就docker-compose pull

旧的容器和镜像好像也要先删掉，然后拉取新镜像，再run
