### ISSUE TITLE
接口返回很慢是怎么回事，好像都要300000ms以上

### ISSUE THREAD

**Issue by QiuZiXian** [Chanzhaoyu/chatgpt-web#1303]
![image](https://user-images.githubusercontent.com/28780269/230585053-99142841-59dd-45ba-8950-64881e234c66.png)

**Comment by civetming** [comment]
我也是

**Comment by luckywangxi** [comment]
加一，今天返回巨慢

**Comment by ottocsb** [comment]
我是刚刚拉取了最新更新，才变的慢

**Comment by ottocsb** [comment]
拉取之前回复还都蛮正常的

**Comment by leter** [comment]
我也是，最新版的很卡

**Comment by KLED-dj** [comment]
我用的2.10.9的时候还是正常的秒回复，拉到最新版回复都在20s以上

**Comment by ottocsb** [comment]
#1260 可以看下吗 @quzard

**Comment by lie5860** [comment]
+1

**Comment by quzard** [comment]
> #1260 可以看下吗 @quzard

应该是openai的问题，那个pr我已经自用了好几天，之前不会影响回答速度。估计openai服务器进行限速了

**Comment by LiweiDong** [comment]
+1  慢虽慢，开发者工具看网络里接口已经返回完了(1min) 但是UI上还是空的。

**Comment by Faithlv-1** [comment]
今天下午2点还能用，5点就不行了

**Comment by quzard** [comment]
测试了一下，没有加支付方式的api速度比加了支付方式的api速度慢了很多。应该是对免费用户限速了。

**Comment by quzard** [comment]
azure的api速度也很快。只有openai的免费api速度变慢了

**Comment by LiweiDong** [comment]
> +1 慢虽慢，开发者工具看网络里接口已经返回完了(1min) 但是UI上还是空的。

好像是默认是1分钟 超时了

**Comment by 8955107** [comment]
我倒是没有1分钟超时，但是明显感觉到慢很多，真的是免费apikey被限速了吗

**Comment by quzard** [comment]
> 我倒是没有1分钟超时，但是明显感觉到慢很多，真的是免费apikey被限速了吗

真的，对比了免费的openai apikey，付费openai apikey，azure的api。付费openai和azure的速度基本一致，很快。但免费的openai apikey很慢，有明显的差距

**Comment by luckywangxi** [comment]
> > 我倒是没有1分钟超时，但是明显感觉到慢很多，真的是免费apikey被限速了吗
> 
> 真的，对比了免费的openai apikey，付费openai apikey，azure的api。付费openai和azure的速度基本一致，很快。但免费的openai apikey很慢，有明显的差距

付费只是绑卡吗 还是开通plus的

**Comment by quzard** [comment]
> > > 我倒是没有1分钟超时，但是明显感觉到慢很多，真的是免费apikey被限速了吗
> > 
> > 
> > 真的，对比了免费的openai apikey，付费openai apikey，azure的api。付费openai和azure的速度基本一致，很快。但免费的openai apikey很慢，有明显的差距
> 
> 付费只是绑卡吗 还是开通plus的

绑卡

**Comment by luckywangxi** [comment]
好像恢复了，我的速度正常了

**Comment by 1378056564** [comment]
> 好像恢复了，我的速度正常了

![1.png](https://img.juyuantop.cn/8j0XRX.png)

没有吧，我用了model 3.5-turbo 和turbo-0301 都这么慢

**Comment by mydaoyuan** [comment]
付费就快

**Comment by 1378056564** [comment]
> 付费就快

我发现时快时慢的0.0头大

**Comment by GavinZJZhang** [comment]
> 测试了一下，没有加支付方式的api速度比加了支付方式的api速度慢了很多。应该是对免费用户限速了。

感觉你这个是正解

**Comment by QiuZiXian** [comment]
好像是官方限速？https://community.openai.com/t/your-service-is-useless-for-developers-just-tell-us-the-truth/145376

**Comment by guipie** [comment]
+1 ，不知道是否代码问题，还是 api限速了。。上午还挺快，下午升级后就变慢了。

**Comment by 2019clover** [comment]
跟最近升级应该没关系，感觉应该是对api限制速度了。我一直没有升级过，时不时报超时。之前没有，最近两天经常这样

**Comment by yoyosbg** [comment]
> > 我倒是没有1分钟超时，但是明显感觉到慢很多，真的是免费apikey被限速了吗
> 
> 真的，对比了免费的openai apikey，付费openai apikey，azure的api。付费openai和azure的速度基本一致，很快。但免费的openai apikey很慢，有明显的差距

azure api怎么用？

**Comment by 2019clover** [comment]
最近一直都很慢 然后我就去用官网访问了,官网提问还免费.api只有免费的5美金
