### ISSUE TITLE
  出现这个错怎么办

### ISSUE THREAD

**Issue by 962241455** [Chanzhaoyu/chatgpt-web#1304]
SyntaxError: Unexpected number in JSON at position 4
chatgpt-web  |     at JSON.parse (<anonymous>)
chatgpt-web  |     at onMessage (file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:622:47)
chatgpt-web  |     at file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:62:7
chatgpt-web  |     at parseEventStreamLine (file:///app/node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/dist/index.js:73:9)
chatgpt-web  |     at Object.feed (file:///app/node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/dist/index.js:61:7)
chatgpt-web  |     at feed (file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:84:12)
chatgpt-web  |     at PassThrough.<anonymous> (file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:94:9)
chatgpt-web  |     at PassThrough.emit (node:events:513:28)
chatgpt-web  |     at emitReadable_ (node:internal/streams/readable:578:12)
chatgpt-web  |     at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by banmengbx** [comment]
我也遇到了这个问题，放在vps上会出现，在本地运行不会出现该问题

**Comment by nikissXI** [comment]
我也是这个问题，回退上一个版本了

**Comment by 962241455** [comment]
好的， 谢谢
