### ISSUE TITLE
一句话没说完就断开了

### ISSUE THREAD

**Issue by Arturia169** [Chanzhaoyu/chatgpt-web#1307]
![image](https://user-images.githubusercontent.com/69199123/230617242-06e14cd9-6a57-4bce-8267-0f9fe475001c.png)
![image](https://user-images.githubusercontent.com/69199123/230617210-fab208f2-8787-47c4-9b89-b265c4586ec3.png)
已经按照issues中的方法更改TIMEOUT_MS = 0 还是没用 
使用apikey登录的

**Comment by firstsaofan** [comment]
+1,这两天的出现的问题，代码已经获取了最新。部署环境是国外服务器 docker，应该不会有网络问题。日志也是TimeoutError,尝试修改了 --env TIMEOUT_MS=0，问题依旧存在。回复会被截断，让他继续回答，不能继续回复上述问题。

**Comment by Arturia169** [comment]
> +1,这两天的出现的问题，代码已经获取了最新。部署环境是国外服务器 docker，应该不会有网络问题。日志也是TimeoutError,尝试修改了 --env TIMEOUT_MS=0，问题依旧存在。回复会被截断，让他继续回答，不能继续回复上述问题。

是的我的服务器也是境外环境

**Comment by GavinZJZhang** [comment]
> +1,这两天的出现的问题，代码已经获取了最新。部署环境是国外服务器 docker，应该不会有网络问题。日志也是TimeoutError,尝试修改了 --env TIMEOUT_MS=0，问题依旧存在。回复会被截断，让他继续回答，不能继续回复上述问题。

回答到一半后台报错，报错后没有保存这一半的回答，所以再“继续”也是连不上的

**Comment by Chanzhaoyu** [comment]
老版本会不会有这个问题？

**Comment by firstsaofan** [comment]
2.10.8也会有这个问题。
@Chanzhaoyu

**Comment by Aallizzwell** [comment]
同样的问题

**Comment by dashug** [comment]
这个问题好像就是从2.10.8开始的 @Chanzhaoyu

**Comment by zohar175** [comment]
是的，我前两天发现了这个问题，然后把版本改回了2.10.7
后好了，但是这两天不知道是我服务器的问题还是怎么样，回答得很慢，而且有时候经常错误，我的服务器的美国的

**Comment by Arturia169** [comment]
> 是的，我前两天发现了这个问题，然后把版本改回了2.10.7 后好了，但是这两天不知道是我服务器的问题还是怎么样，回答得很慢，而且有时候经常错误，我的服务器的美国的

请问如何退回老版本？

**Comment by zohar175** [comment]
> > 是的，我前两天发现了这个问题，然后把版本改回了2.10.7 后好了，但是这两天不知道是我服务器的问题还是怎么样，回答得很慢，而且有时候经常错误，我的服务器的美国的
> 
> 请问如何退回老版本？

我是用docker的，“docker pull chenzhaoyu94/chatgpt-web:v2.10.7”

**Comment by medego** [comment]
我也是境外服务器一样的问题
