### ISSUE TITLE
最近的回答都很短

### ISSUE THREAD

**Issue by raokun** [Chanzhaoyu/chatgpt-web#1308]
看issue的TIMEOUT_MS=0配置的方法无效

**Comment by nikissXI** [comment]
我也是，是代码有问题，退到上一个版本

**Comment by xiaosaaaa** [comment]
我的是2.10.8也是这样

**Comment by LINZONG666** [comment]
docker run --name chatgpt-web2023040810 -d -p 【你的ip】:3002:3002 --env OPENAI_API_KEY=【你的key】 --env AUTH_SECRET_KEY=【访问密码】--env TIMEOUT_MS=0 chenzhaoyu94/chatgpt-web:v2.10.8

ip:端口登录，暂时解决

**Comment by GavinZJZhang** [comment]
> 我也是，是代码有问题，退到上一个版本

对，应该是后面的版本，把每次ChatCompletion的MaxTokens设置小了，导致每次回答变短

**Comment by Chanzhaoyu** [comment]
拉取下最新 `latest` 试试？没有改动这些代码啊，可能是因为升级 `chatgpt` 包的原因

**Comment by guipie** [comment]
> 拉取下最新 `latest` 试试？没有改动这些代码啊，可能是因为升级 `chatgpt` 包的原因

应该是升级包的问题，拉最新版部署是慢多了；
最新版升级包了吗？？我拉最新的还需要 install 一下吗？
