### ISSUE TITLE
添加AUTH_SECRET_KEY后，手机端访问进不去

### ISSUE THREAD

**Issue by hbsgithub** [Chanzhaoyu/chatgpt-web#1310]
电脑端正常访问，可以输入验证码，但在手机端访问页面时，只出现三个球的加载页面，无法进入验证界面，也无法进入对话页面

**Comment by Chanzhaoyu** [comment]
用微信的浏览器扫一扫看是不是版本问题

**Comment by guipie** [comment]
> 



> 用微信的浏览器扫一扫看是不是版本问题

电脑正常，手机端怎么聊天不是即时显示回复了，需要等待全部结果出来统一显示呢。需要改哪里配置吗？

**Comment by hbsgithub** [comment]
> 
感谢回复，部署在railway上面之后手机端可以正常访问了，怀疑是之前部署在vps的docker上的nginx配置有点问题
