### ISSUE TITLE
稍微长文本就被截断，看不到后面的。

### ISSUE THREAD

**Issue by randerswan** [Chanzhaoyu/chatgpt-web#1312]
2023/4/8 上午11:15:31

怎么组装四轴飞行器？

2023/4/8 上午11:16:01

组装四轴飞行器需要一些基础的电子和机械知识，如果您之前没有相关经验，建议在学习和研究之后再进行组装。

以下是一个一般的四轴飞行器组装步骤：

1.准备所需材料和工具：四轴飞行器套件、遥控器、电池、螺旋桨、螺丝刀、电线等。

2.根据说明书组装机架：将四轴飞行器套件中提供的各个零部件按照说明书逐步组装起来。
3.

**Comment by Chanzhaoyu** [comment]
`API` 方式吗？是否是 `Docker` 获取到 `2.10.9` 标签。

**Comment by randerswan** [comment]
> 

是api。那我试试看，多谢。

**Comment by randerswan** [comment]
试了还是一样

**Comment by CaoYunzhou** [comment]
你的网络问题，弄个好点的`proxy`，配置`TIMEOUT_MS`为0,不存在这种问题

**Comment by randerswan** [comment]
> 你的网络问题，弄个好点的`proxy`，配置`TIMEOUT_MS`为0,不存在这种问题

是这个问题，已解决，非常感谢。

**Comment by ybeetle8** [comment]
我也确认, 是网络问题
