### ISSUE TITLE
反应变慢，输入对话之后明显回复变慢，有时还会卡住

### ISSUE THREAD

**Issue by Gao-yu-1214** [Chanzhaoyu/chatgpt-web#1315]

**Comment by Gao-yu-1214** [comment]
有无大佬知道原因是什么，换了模型还是不行

**Comment by guipie** [comment]
是的我也感觉了，应该chatgpt原因。。另外手机端怎么不即时回复了，得全部结果出来才返回呢。

**Comment by Gao-yu-1214** [comment]
> 是的我也感觉到了，应该chatgpt原因。。另外手机端怎么不及时回复了，得全部结果出来才返回呢。

我翻了一下评论，有人说是白嫖的原因，openai对免费用户进行了限速，过几天绑卡试一下

**Comment by xiao-ke-1** [comment]
免费用户是这样的，我昨天换了一个120刀的号嘎嘎快

**Comment by guipie** [comment]
> > 是的我也感觉到了，应该chatgpt原因。。另外手机端怎么不及时回复了，得全部结果出来才返回呢。
> 
> 我翻了一下评论，有人说是白嫖的原因，openai对免费用户进行了限速，过几天绑卡试一下

我已经绑卡了，只是没升级plus。。

**Comment by guipie** [comment]
> 免费用户是这样的，我昨天换了一个120刀的号嘎嘎快

![1680935372650](https://user-images.githubusercontent.com/55727172/230707013-d6bdd32e-d90d-4481-be67-08308c277ce1.png)
我这算120的号吗？？

**Comment by xiao-ke-1** [comment]
是

**Comment by Gao-yu-1214** [comment]
> > 免费用户是这样的，我昨天换了一个120刀的号嘎嘎快
> 
> ![1680935372650](https://user-images.githubusercontent.com/55727172/230707013-d6bdd32e-d90d-4481-be67-08308c277ce1.png) 我这算120的号吗？？

这咋整的，120 刀

**Comment by xiao-ke-1** [comment]
1531049555@qq.com需要联系（带慈善家

**Comment by Gao-yu-1214** [comment]
> [1531049555@qq.com](mailto:1531049555@qq.com)需要联系（带慈善家

OK，多谢

**Comment by Grey0520** [comment]
> 免费用户是这样的，我昨天换了一个120刀的号嘎嘎快

120刀？年费吗

**Comment by Grey0520** [comment]
> qq:1531049555需要联系（带慈善家

哥们俺是学生，扣1可以免费送吗？
grey0520@foxmail.com

求求啦
