### ISSUE TITLE
最新版本反应较慢，而且不携带上下文了，有遇到此问题的大佬吗

### ISSUE THREAD

**Issue by guipie** [Chanzhaoyu/chatgpt-web#1318]
![1680937678179](https://user-images.githubusercontent.com/55727172/230709243-ffb94cc2-9d54-4bac-98c8-d75b593a108d.png)

**Comment by Larsy5** [comment]
我也遇到这问题

**Comment by necopp** [comment]
**好像是因为openai对免费账户的api接口做了限制，应该不是项目的问题，我用了120刀的账号的api就特别快，结局办法有两个。**
**1，补充付款信息
 2. 购买plus订阅**

**Comment by lixingxing001** [comment]
免费用户被限流了，要是想要快，用120美刀的 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/43061802/230713309-b710b11c-a211-442c-830a-9c5e744497c5.png">

**Comment by dreamtraveler-LiuQi** [comment]
120$一个月？

**Comment by lixingxing001** [comment]
> 120$一个月？

绑卡后支付5美刀

**Comment by guipie** [comment]
> **好像是因为openai对免费账户的api接口做了限制，应该不是项目的问题，我用了120刀的账号的api就特别快，结局办法有两个。** **1，补充付款信息 2. 购买plus订阅**

我已经绑卡了，还是慢。。没开plus

**Comment by oliver-yu** [comment]
> > **好像是因为openai对免费账户的api接口做了限制，应该不是项目的问题，我用了120刀的账号的api就特别快，结局办法有两个。** **1，补充付款信息 2. 购买plus订阅**
> 
> 我已经绑卡了，还是慢。。没开plus

折腾了6个google账号，目前只有一个注册超过6年的google账号能登录https://platform.openai.com/account/api-keys获取到API-KEYS，其余5个账号都不行，这种情况能绑卡吗？

**Comment by rocket2023** [comment]
2.10.8开始，到同步2.10.9为止。 api方式依然不带上下文，access_token正常携带上下文

**Comment by guipie** [comment]
已解决处理。

**Comment by Suzichen** [comment]
> 已解决处理。

请问上下文丢失问题怎么解决，我用API和TOKEN都不行
