### ISSUE TITLE
为什么我的请求特别慢啊，难道是nginx的代理问题吗？而且有时候会报错

### ISSUE THREAD

**Issue by dreamtraveler-LiuQi** [Chanzhaoyu/chatgpt-web#1320]
ChatGPT error 429: {
"error": {
"message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at [help.openai.com](http://help.openai.com/) if the error persists. (Please include the request ID 0a407c060a302f0f4ace6ee3be95da59 in your message.)",
"type": "server_error",
"param": null,
"code": null
}
}

**Comment by jianingguo** [comment]
今天开始好像免费key都很慢

**Comment by James-handsome** [comment]
我也是 很慢

**Comment by 2019clover** [comment]
这两天时不时超时

**Comment by Teemwu** [comment]
貌似官方限速了，换 120 美元的号就没影响
