### ISSUE TITLE
问下各位大佬，你们这两天有遇到免费key请求慢的情况吗？

### ISSUE THREAD

**Issue by jianingguo** [Chanzhaoyu/chatgpt-web#1324]
openAI 免费key请求慢的问题有遇到的吗？

**Comment by iszhouhuabo** [comment]
免费的貌似被限制速度了。

**Comment by Arturia169** [comment]
遇到了 很慢

**Comment by James-handsome** [comment]
遇到了 很慢 很慢 很慢

**Comment by 2019clover** [comment]
经常报超时

**Comment by yuntao1997** [comment]
+1，非常慢

**Comment by fzucs** [comment]
慢的我又回网页版了

**Comment by zhaojie199512** [comment]
遇到了，绑了卡后就快了

**Comment by Lincest** [comment]
和key没有关系, 同样的key在另一个项目[chatgpt_academic](https://github.com/binary-husky/chatgpt_academic)上就很快

**Comment by zohar175** [comment]
> 和key没有关系, 同样的key在另一个项目[chatgpt_academic](https://github.com/binary-husky/chatgpt_academic)上就很快

对，我今天也尝试了确实同样的key在别的项目是正常的

**Comment by Willlee11** [comment]
是项目在作妖么TNT

**Comment by jianingguo** [comment]
但是同样是这个项目，我用我朋友的收费key就很快呀

**Comment by jianingguo** [comment]
> 和key没有关系, 同样的key在另一个项目[chatgpt_academic](https://github.com/binary-husky/chatgpt_academic)上就很快

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/7371210/230727912-5e6e556a-e476-407a-a7a1-8949fb80678c.png">
这个项目我刚试了，免费key也很慢啊

**Comment by Willlee11** [comment]
尝试回退老版本也是慢的，还是跟官方限制有关吧？

**Comment by iszhouhuabo** [comment]
虚拟卡吗？我用外币卡不行。> 遇到了，绑了卡后就快了

**Comment by zohar175** [comment]
> 虚拟卡吗？我用外币卡不行。
> 
> > 遇到了，绑了卡后就快了

兄弟你用的是depay吗？

**Comment by chenxinstepone** [comment]
今天早上免费key好像恢复正常速度了

**Comment by iszhouhuabo** [comment]
> 今天早上免费key好像恢复正常速度了
> 
> 

是的，恢复了。不知道能挺多久。

**Comment by iszhouhuabo** [comment]
> > 虚拟卡吗？我用外币卡不行。
> 
> > 
> 
> > > 遇到了，绑了卡后就快了
> 
> 
> 
> 兄弟你用的是depay吗？
> 
> 
我吗？我不是，我也想知道绑卡成功的那个兄弟用的是啥。

**Comment by fzucs** [comment]
早上恢复了一下，然后又变慢了

**Comment by chenxinstepone** [comment]
> 早上恢复了一下，然后又变慢了

是的，无语了

**Comment by xueguizheng** [comment]
> 遇到了，绑了卡后就快了

兄弟绑了卡是不是还是先消耗免费的5刀，这5刀消耗不完还是慢吗？消耗完5刀在消耗120到的话是不是就快了？？

**Comment by James-handsome** [comment]
别信他的绑卡就快了，拿什么绑，中国的卡绑不了好吧

**Comment by xueguizheng** [comment]
> 别信他的绑卡就快了，拿什么绑，中国的卡绑不了好吧

绑visa卡大哥，肯定不绑中国卡，绑了卡属于付费的了，我有visa卡

**Comment by James-handsome** [comment]
> > 别信他的绑卡就快了，拿什么绑，中国的卡绑不了好吧
> 
> 绑visa卡大哥，肯定不绑中国卡，绑了卡属于付费的了，我有visa卡

你不绑定中国的你还有国外的卡吗？

**Comment by xueguizheng** [comment]
> > > 别信他的绑卡就快了，拿什么绑，中国的卡绑不了好吧
> > 
> > 
> > 绑visa卡大哥，肯定不绑中国卡，绑了卡属于付费的了，我有visa卡
> 
> 你不绑定中国的你还有国外的卡吗？

算了不给你犟了，你先了解了解吧，你还有好多没听过的东西。

**Comment by James-handsome** [comment]
> > > > 别信他的绑卡就快了，拿什么绑，中国的卡绑不了好吧
> > > 
> > > 
> > > 绑visa卡大哥，肯定不绑中国卡，绑了卡属于付费的了，我有visa卡
> > 
> > 你不绑定中国的你还有国外的卡吗？
> 
> 算了不给你犟了，你先了解了解吧，你还有好多没听过的东西。

那你绑吧，depay开卡是要月费的，我有什么不知道，搞得好像你是懂王

**Comment by xueguizheng** [comment]
> > > > > 别信他的绑卡就快了，拿什么绑，中国的卡绑不了好吧
> > > > 
> > > > 
> > > > 绑visa卡大哥，肯定不绑中国卡，绑了卡属于付费的了，我有visa卡
> > > 
> > > 
> > > 你不绑定中国的你还有国外的卡吗？
> > 
> > 
> > 算了不给你犟了，你先了解了解吧，你还有好多没听过的东西。
> 
> 那你绑吧，depay开卡是要月费的，我有什么不知道，搞得好像你是懂王

那也没办法，事实证明确实绑卡的速度快。无可置疑的。

**Comment by James-handsome** [comment]
> > > > > > 别信他的绑卡就快了，拿什么绑，中国的卡绑不了好吧
> > > > > 
> > > > > 
> > > > > 绑visa卡大哥，肯定不绑中国卡，绑了卡属于付费的了，我有visa卡
> > > > 
> > > > 
> > > > 你不绑定中国的你还有国外的卡吗？
> > > 
> > > 
> > > 算了不给你犟了，你先了解了解吧，你还有好多没听过的东西。
> > 
> > 那你绑吧，depay开卡是要月费的，我有什么不知道，搞得好像你是懂王
> 
> 那也没办法，事实证明确实绑卡的速度快。无可置疑的。

那你成为了付费用户，肯定要快点

**Comment by Subdue0** [comment]
> 遇到了，绑了卡后就快了

我想问下，绑卡扣得5刀会还的吗？还是每次绑卡扣5刀？

**Comment by iszhouhuabo** [comment]
> xdm亲测绑卡之后提升速度！我费了好大的力气终于绑上一个虚拟信用卡，速度一下子提升了好多

绑的啥虚拟卡呀？

**Comment by yuntao1997** [comment]
我也绑卡了，用了两天感觉一点都不卡，消息发过去就回过来了。  绑的depay

**Comment by leyouBaloy** [comment]
> > xdm亲测绑卡之后提升速度！我费了好大的力气终于绑上一个虚拟信用卡，速度一下子提升了好多
> 
> 只要绑定卡，原来的5美刀的key也会变快吗

是的，绑卡不是免费的，会扣5美刀，如果没用的话，一段时间后还给你

**Comment by jianingguo** [comment]
虚拟信用卡是怎么搞的？求指教发自我的手机-------- 原始邮件 --------发件人： leyouBaloy ***@***.***>日期： 2023年4月12日周三 22:00收件人： Chanzhaoyu/chatgpt-web ***@***.***>抄送： jianingguo ***@***.***>, Author ***@***.***>主    题： Re: [Chanzhaoyu/chatgpt-web] 问下各位大佬，你们这两天有遇到免费key请求慢的情况吗？ (Issue #1324)


xdm亲测绑卡之后提升速度！我费了好大的力气终于绑上一个虚拟信用卡，速度一下子提升了好多

只要绑定卡，原来的5美刀的key也会变快吗

是的，绑卡不是免费的，会扣5美刀，如果没用的话，一段时间后还给你

**Comment by yuntao1997** [comment]
@jianingguo 网上有一堆，google搜 depay 注册。

**Comment by leyouBaloy** [comment]
> > xdm亲测绑卡之后提升速度！我费了好大的力气终于绑上一个虚拟信用卡，速度一下子提升了好多
> 
> 绑的啥虚拟卡呀？

depay，能绑卡，但不保证靠谱

**Comment by jianingguo** [comment]
好嘞，谢谢大佬发自我的手机-------- 原始邮件 --------发件人： yuntao1997 ***@***.***>日期： 2023年4月12日周三 22:22收件人： Chanzhaoyu/chatgpt-web ***@***.***>抄送： jianingguo ***@***.***>, Mention ***@***.***>主    题： Re: [Chanzhaoyu/chatgpt-web] 问下各位大佬，你们这两天有遇到免费key请求慢的情况吗？ (Issue #1324)
@jianingguo 网上有一堆，google搜 depay 注册。
