### ISSUE TITLE
请问max_tokens这个参数可以通过环境变量设置么，或者可以怎么设置呢？

### ISSUE THREAD

**Issue by gx19970920** [Chanzhaoyu/chatgpt-web#1326]
如题，感觉有时候回答不完整，想增加一下max_tokens的大小，但是没有找到在哪里设置

**Comment by Chanzhaoyu** [comment]
你可以在 `service/chatgpt/index.ts` 中设置

**Comment by gx19970920** [comment]
请问需要如何映射出来呢，或者怎么进去容器呢，我映射/service到本地的/service文件夹但是是空的，想进去容器内，但是/bin/bash命令没法进入容器

**Comment by gx19970920** [comment]
请问我需要怎么映射出来这个文件夹呢，我进去docker（/bin/sh）但是没有发现service/chatgpt/index.ts这个文件

**Comment by lalagu27** [comment]
> 

你肯定找不着,这是源代码里的,前端打包发布后,文件名和文件成天书了。

**Comment by gx19970920** [comment]
> 

可是，作者回复可以修改呀，我只是比较菜，没找到
