### ISSUE TITLE
为什么使用token写长一点的内容会中段

### ISSUE THREAD

**Issue by czx1055** [Chanzhaoyu/chatgpt-web#1334]
经过我的多次测试，在windos下是不会出错的，
但是一旦上传到liux服务器，就会出现这种中断问题，我用的宝塔，直接部署的node环境，没有用容器，听说用容器的也会出现这种问题，
写代码写到一半自动停了，  接口我也测试过了，能正常返回所有文本，现在的问题是不是前端哪里有问题。
![image](https://user-images.githubusercontent.com/128042750/230767253-09399395-daef-419e-bc3b-1dc2ca87d2f9.png)

**Comment by Chanzhaoyu** [comment]
我的项目没有登录功能吧？

**Comment by Chanzhaoyu** [comment]
把超时时间设置长一点

**Comment by mornone** [comment]
他这看着像是gpt返回的代码只显示了一部分就中断了，今天我也同样遇到这个情况，返回2、30个字就中断了，不清楚是不是gpt的api升级了

**Comment by dreama86** [comment]
我用node在本地跑没问题，放在服务器上就会这样中断，换了国外的一个不行，用腾讯云也不行，后来用docker部署就没问题了

**Comment by nikissXI** [comment]
> 他这看着像是gpt返回的代码只显示了一部分就中断了，今天我也同样遇到这个情况，返回2、30个字就中断了，不清楚是不是gpt的api升级了

用2.10.8试试

**Comment by nikissXI** [comment]
> 我用node在本地跑没问题，放在服务器上就会这样中断，换了国外的一个不行，用腾讯云也不行，后来用docker部署就没问题了（我用accessToken会出现这个问题，api方式没出现过）

用2.10.8试试

**Comment by tang2330** [comment]
> 把超时时间设置长一点

刚刚看了下面的评论说用2.10.8试试  ，我试了一下 确实2.10.8版本没有出现过accessToken模式返回中断的问题

这个好像也不是超时的问题，因为chatgpt/build/index.js我打印了一下 是完整返回的，但是前端界面那里会中断

然后我又试了使用2.10.8的service服务，前端使用2.10.9的  发现还是没有问题，使用了2.10.9版本的service服务就会出现长一点的内容就会中断。 ts我看不太懂  无法给予作者太大帮助  c:

**Comment by nikissXI** [comment]
> 

看看日志，中断会有报错的，我踢了issues了，但没人理我，我看不懂js也不会修

**Comment by tang2330** [comment]
> > 
> 
> 看看日志，中断会有报错的，我踢了issues了，但没人理我，我看不懂js也不会修

我看不懂typejs

> > 把超时时间设置长一点
> 
> 刚刚看了下面的评论说用2.10.8试试 ，我试了一下 确实2.10.8版本没有出现过accessToken模式返回中断的问题
> 
> 这个好像也不是超时的问题，因为chatgpt/build/index.js我打印了一下 是完整返回的，但是前端界面那里会中断
> 
> 然后我又试了使用2.10.8的service服务，前端使用2.10.9的 发现还是没有问题，使用了2.10.9版本的service服务就会出现长一点的内容就会中断。 ts我看不太懂 无法给予作者太大帮助 c:

@Chanzhaoyu 作者大大看一下

**Comment by Chanzhaoyu** [comment]
> 

获取最新代码，重新部署下。

**Comment by nikissXI** [comment]
> > 
> 
> 获取最新代码，重新部署下。
> 
> `Docker` 的话用 `latest` 标签
> 
> 本地的话就用 `main` 分支

试了下，目前没问题，之前100%稳定报错

**Comment by tang2330** [comment]
> > > 
> > 
> > 
> > 获取最新代码，重新部署下。
> > `Docker` 的话用 `latest` 标签
> > 本地的话就用 `main` 分支
> 
> 试了下，目前没问题，之前100%稳定报错

好像就是service/package.json的chatgpt版本从5.2.2改为5.1.2
