### ISSUE TITLE
大佬们，可以调用text-davinci-003模型吗

### ISSUE THREAD

**Issue by xhenmo** [Chanzhaoyu/chatgpt-web#1337]
想试一试text-davinci-003模型，部署后访问成功，但发送消息报错
ChatGPT error 404: {
"error": {
"message": "Invalid URL (POST /v1/chat/completions)",
"type": "invalid_request_error",
"param": null,
"code": null
}
}

使用默认模型就没有这个问题

**Comment by fujinqi** [comment]
![72B3E792-3584-4081-AD56-70EBE6650F43](https://user-images.githubusercontent.com/68273411/230771882-350038ab-9348-4822-ae7b-babd08f14d16.png)
默认模型

**Comment by fujinqi** [comment]
![202D3CBF-8983-444B-95FE-DAA45FD0C5D5](https://user-images.githubusercontent.com/68273411/230771908-0ef33764-e359-4933-aa31-0d628f51443d.png)
davinci模型

**Comment by fujinqi** [comment]
我用的是docker部署，命令：
docker run --name chatgpt-web -d -p 127.0.0.1:8765:3002 --env OPENAI_API_KEY=xxxxxx --env OPENAI_API_BASE_URL=https://api.openai.com --env OPENAI_API_MODEL=text-davinci-003 chenzhaoyu94/chatgpt-web

**Comment by Bisstocuz** [comment]
`text-davinci-003` 不是 Chat 模型，接口不是 `POST /v1/chat/completions`

**Comment by fujinqi** [comment]
@Chanzhaoyu 作者您好，这个是bug吗，如果是的话可以修复下吗，谢谢
