### ISSUE TITLE
突然无法使用，报404: ChatGPTError: ChatGPT error 404: 404 page not found

### ISSUE THREAD

**Issue by zhangairen** [Chanzhaoyu/chatgpt-web#1339]
ChatGPTError: ChatGPT error 404: 404 page not found
chatgpt-3.5    |     at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
chatgpt-3.5    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
chatgpt-3.5    |   statusCode: 404,
chatgpt-3.5    |   statusText: 'Not Found',

**Comment by qy8502** [comment]
me too，用洛杉矶、西雅图、孟买节点访问都是错误1020。都被封了。

**Comment by qy8502** [comment]
@zhangairen 配置里换个代理好了
 API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation

**Comment by zhangairen** [comment]
> @zhangairen 配置里换个代理好了 API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation

多谢，可以了
