### ISSUE TITLE
输出格式经常不会换行

### ISSUE THREAD

**Issue by xuiam** [Chanzhaoyu/chatgpt-web#134]
![1677405271018](https://user-images.githubusercontent.com/42964379/221403739-9d1100f1-ef38-48f9-9050-466e07a34370.png)
输出格式有点问题，这张图还算可以的，还有一行都不换的

**Comment by Chanzhaoyu** [comment]
前端版本号，后端 API 还是 Token

![54426D13-1F53-4680-8448-6F272030EB38](https://user-images.githubusercontent.com/24789441/221407217-6519c292-3160-4889-8b84-2b6ce8234350.jpeg)

**Comment by xuiam** [comment]
前端版本2.7.3，使用的api

**Comment by xuiam** [comment]
> 前端版本号，后端 API 还是 Token
> 
> ![54426D13-1F53-4680-8448-6F272030EB38](https://user-images.githubusercontent.com/24789441/221407217-6519c292-3160-4889-8b84-2b6ce8234350.jpeg)
![image](https://user-images.githubusercontent.com/42964379/221408206-a5544d00-0f51-4354-9dba-c8131137875b.png)
使用移动端也是一样

**Comment by Chanzhaoyu** [comment]
好的，看来是 API 版本的问题

**Comment by Chanzhaoyu** [comment]
已简单修复换行，不过 API 的有些代码只返回文本，不会返回 markdown ，所以不会被渲染和代码高亮。后期可能需要针对修改。不过你也可以要求它返回 markdown 格式
