### ISSUE TITLE
[stream]按各位大佬提供的配置后仍无流式效果的看过来！我解决了！

### ISSUE THREAD

**Issue by kingfer30** [Chanzhaoyu/chatgpt-web#1341]
很多大佬提供的基本都是nginx那几个配置，最主要就是：
```
proxy_buffering off;
proxy_pass_header Server;                                 
proxy_http_version 1.1;                                   
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
```
配置之后仍没效果的，按步骤来排查：
1、先在服务器上curl测试，如果返回的是stream流，那么这个反代配置正确：
```
curl -vvv https://你的反代域名地址/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-xxx" \
  -d '{
    "stream": true,
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "为何我请求chatgpt API响应都很慢, 平均都要20秒左右"}]
  }'
```
2、检查你的发起请求端，body是否带了这个参数：stream = true，这个参数不设置是不生效的！！默认是false
![image](https://user-images.githubusercontent.com/34082198/230781760-34c43cd8-be27-4e39-8b5b-5d0b8eafdf22.png)
我就是这个问题导致的！搞了半天一直不行，最后发现是这个参数没传的问题 - -

另外、打字流的缺陷：
1、打字流不会返回请求的token总消耗，如果你自己做一层打包计费的话，需要用官方提供的 [tiktoken](https://github.com/openai/openai-cookbook/blob/4c31db4987f82068b0942dc6b84bf71c1d714418/examples/How_to_count_tokens_with_tiktoken.ipynb) 来进行编码计算

2、现在5刀的官方已经限制了网速了，所以打字流优先级又降了，确实还不如一次性返回了

**Comment by PuddingJoker** [comment]
你这个body在项目源代码里面有吗
