### ISSUE TITLE
给前端增加了api-key和accessToken选项

### ISSUE THREAD

**Issue by limenghaolalala** [Chanzhaoyu/chatgpt-web#1342]
演示地址:https://chat.8uai.cn

文件替换:https://github.com/limenghaolalala/ChatGPT-Web-Revise

感谢大佬源码资源!

**Comment by william5200** [comment]
感谢大佬，accessToken方式如果能在前端自定义API_REVERSE_PROXY就更棒了。

**Comment by missuo** [comment]
好像docker build会报错

**Comment by limenghaolalala** [comment]
> 好像docker build会报错

什么错误
