### ISSUE TITLE
Open AI 免费的18美金被限速了，现在回复好慢

### ISSUE THREAD

**Issue by James-handsome** [Chanzhaoyu/chatgpt-web#1343]

**Comment by AutumnStack** [comment]
我也遇到了，特别特别慢现在

**Comment by lixibi** [comment]
难道正常缴费的api速度很快？

**Comment by whatmeans** [comment]
不单慢，生成的还不全。感觉是api服务器炸了

**Comment by shuichang** [comment]
绑卡速度就快了

**Comment by James-handsome** [comment]
> 绑卡速度就快了

绑卡要扣5美金啊

**Comment by zohar175** [comment]
> 绑卡速度就快了

听说绑卡送120u？

**Comment by AutumnStack** [comment]
现在又快了很多

**Comment by zohar175** [comment]
> 现在又快了很多

我立刻去试了一下，确实快了很多，啥情况啊现在，一下慢一下快的，到底是不是限速免费的账户啊

**Comment by zohar175** [comment]
> 

快是快了点，但是和原来的速度比还是有点慢

**Comment by Fugitive844** [comment]
> 
绑卡扣的5美金会退的，我的已经退了，好像是两三周后退

**Comment by fzucs** [comment]
时快时慢，只能希望是服务器负载的问题，而不是对免费帐户限速了

**Comment by yshmoon** [comment]
> > 
> 
> 绑卡扣的5美金会退的，我的已经退了，好像是两三周后退

绑卡扣的5美金，卡账户里面显示状态是待定，应该是还没扣吧

**Comment by zaiMoe** [comment]
绑卡会加速么

**Comment by James-handsome** [comment]
> > 
> 
> 绑卡扣的5美金会退的，我的已经退了，好像是两三周后退

绑卡的同志，你们的卡哪里来的，是不是depay ?

**Comment by zohar175** [comment]
> > > 
> > 
> > 
> > 绑卡扣的5美金会退的，我的已经退了，好像是两三周后退
> 
> 绑卡的同志，你们的卡哪里来的，是不是depay ?

说到depay，我好恨啊，昨天手贱把免费的标准卡注销了，现在重新申请只能最低要10美刀的那个卡/😭

**Comment by James-handsome** [comment]
> > > > 
> > > 
> > > 
> > > 绑卡扣的5美金会退的，我的已经退了，好像是两三周后退
> > 
> > 
> > 绑卡的同志，你们的卡哪里来的，是不是depay ?
> 
> 说到depay，我好恨啊，昨天手贱把免费的标准卡注销了，现在重新申请只能最低要10美刀的那个卡/sob

![depayCard](https://user-images.githubusercontent.com/54829185/230874798-2d74cf4f-d0e2-45cd-9fe4-2ed0d57be32c.png)
这个卡，就算你开了不用，每个月还要收取月费的

**Comment by zohar175** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 绑卡扣的5美金会退的，我的已经退了，好像是两三周后退
> > > 
> > > 
> > > 绑卡的同志，你们的卡哪里来的，是不是depay ?
> > 
> > 
> > 说到depay，我好恨啊，昨天手贱把免费的标准卡注销了，现在重新申请只能最低要10美刀的那个卡/sob
> 
> ![depayCard](https://user-images.githubusercontent.com/54829185/230874798-2d74cf4f-d0e2-45cd-9fe4-2ed0d57be32c.png) 这个卡，就算你开了不用，每个月还要收取月费的

没事呀，大不了一个月几块钱而已，而且不用也可以注销呀

**Comment by James-handsome** [comment]
绑卡被拒绝，Open AI 有钱不赚？为什么呢？
![675ab5de675512719850cd21d13b990](https://user-images.githubusercontent.com/54829185/230905878-5f99b9f9-2f87-448e-a8e6-9e6d38515777.png)

**Comment by Fugitive844** [comment]
> > > 
> > 
> > 
> > 绑卡扣的5美金会退的，我的已经退了，好像是两三周后退
> 
> 绑卡的同志，你们的卡哪里来的，是不是depay ？

是的

**Comment by nxtreaming** [comment]
> 绑卡被拒绝，Open AI 有钱不赚？为什么呢？ ![675ab5de675512719850cd21d13b990](https://user-images.githubusercontent.com/54829185/230905878-5f99b9f9-2f87-448e-a8e6-9e6d38515777.png)

这是鸡国的最惠国待遇，不要感到奇怪，这和为啥youtube访问不了类似，要习惯。

**Comment by assassinliujie** [comment]
> 绑卡被拒绝，Open AI 有钱不赚？为什么呢？ ![675ab5de675512719850cd21d13b990](https://user-images.githubusercontent.com/54829185/230905878-5f99b9f9-2f87-448e-a8e6-9e6d38515777.png)

毕竟是信用卡，得防盗刷和黑卡，美国人反电诈也搞的挺凶的
