### ISSUE TITLE
python版本的API调用模式的后端，给大家参考一下

### ISSUE THREAD

**Issue by elky98** [Chanzhaoyu/chatgpt-web#1346]
项目地址：https://github.com/elky98/chat-web-service
![gpt2](https://user-images.githubusercontent.com/47499368/230942813-864dce44-0139-4242-a4b1-a7ca98c412b6.png)
![gpt1](https://user-images.githubusercontent.com/47499368/230942820-3bd73761-785e-4925-8fa4-a6e810aea66a.png)

**Comment by zmhu** [comment]
你调研过客户端 如chatbox有传历史消息么？

**Comment by elky98** [comment]
你说的传历史消息是指从前端传到后端，还是从后端发送给openai呢？

**Comment by lindo-zy** [comment]
直接接管前端的请求吗，还是需要额外配置？

**Comment by elky98** [comment]
可以看下官方的API: [OpenAI](https://platform.openai.com/docs/guides/chat)

1. 如果是对话形式的请求需要传入上下文，他才知道你前面说了什么
2. 这个项目从前端传到后端并没有包括上下文，所以需要后端自己保存一份

因为我是用的这个项目的前端，所以要跟作者的接口形式保持一致。如果是自己开发的话，可以灵活保存上下文前端后端都可以，只要用api中那样的格式发给openai就行了。
这个项目传的参数可以看下我项目中的message_bodys.py里面定义的很清楚。

**Comment by elky98** [comment]
> 直接接管前端的请求吗，还是需要额外配置？

基本直接接管，只需要把前端.env中的VITE_APP_API_BASE_URL改成python的监听地址就行。
但是对比我和原后端，有一个timeMS超时、rateLimit速率限制去没有实现，可以自己添加。

**Comment by elky98** [comment]
> 你调研过客户端 如chatbox有传历史消息么？


你说的传历史消息是指从前端传到后端，还是从后端发送给openai呢？
