### ISSUE TITLE
会话长了,还是会断, 原因找到了, 看看怎么改. 

### ISSUE THREAD

**Issue by ybeetle8** [Chanzhaoyu/chatgpt-web#1347]
1. 网络原因, 如果是国外服务器, 肯定会出现这个问题.  
2. 设置问题,用国内服务器把 TIMEOUT_MS=0  会好很多, 但未完全解决.
3. 手机浏览器切换后台会断线, 基本上一切就断

程序中考虑要缓存ai过来的对话, 如果断线重连后直接把缓存的对话发过去. 要考虑移动端不可避免的断线问题.

**Comment by ybeetle8** [comment]
通迅层最好不要直接用 websocket  而用 socket.io 这种封装过的,带心跳的, 事断线重连的.

**Comment by nikissXI** [comment]
代码问题，看日志会有json解析出错，开发者说拉取最新的docker或仓库代码
