### ISSUE TITLE
部署在vercel  报500错误

### ISSUE THREAD

**Issue by hieivip** [Chanzhaoyu/chatgpt-web#1349]
![Uploading image.png…]()

**Comment by hieivip** [comment]
![image](https://user-images.githubusercontent.com/54146330/230830318-aed5bb4c-341b-4dda-be86-572cd147c6dd.png)

**Comment by roboger** [comment]
我也是的 希望能出教程

**Comment by mjjh1717** [comment]
可以参考我 fork 项目的配置 https://github.com/mjjh1717/chatgpt-shuowen, 在根目录创建api/proxy.js文件,然后再此文件重写路径,然后在根目录里创建vercel.json 添加rewrites配置 现在还有问题,就是没实现打字机效果,拿不到流式数据
