### ISSUE TITLE
下面的输入框能否改为能拉伸的文本域，文字较多时，不是很友好

### ISSUE THREAD

**Issue by xuiam** [Chanzhaoyu/chatgpt-web#135]
![image](https://user-images.githubusercontent.com/42964379/221413735-4d8241c8-3cb7-4f44-a2a3-87e0dd582ed6.png)
如图，当需要输入数据的行数较多时，不好观查输入内容

**Comment by Chanzhaoyu** [comment]
目前就是文本域，shift enter 换行，我把提示换一下吧

**Comment by xuiam** [comment]
![image](https://user-images.githubusercontent.com/42964379/221414106-fcf1f4cb-b685-4bb1-871c-f7987e17b6a6.png)
嗯，不过这是显示的最大行数，还是比较少，就是希望能够是能拉伸的那种比较好

**Comment by Chanzhaoyu** [comment]
自动高度我后面再考虑下
