### ISSUE TITLE
请教大佬，我自己建立了一个反代，假设地址是 https://a.b.c

### ISSUE THREAD

**Issue by themis0009** [Chanzhaoyu/chatgpt-web#1353]
那么请问一下，是修改API_REVERSE_PROXY这个值么？
直接浏览器输入https://a.b.c，返回结果是
<html><body>

error |  
-- | --
message | "Invalid URL (GET /)"
type | "invalid_request_error"
param | null
code | null

</body>
</html>

是不是直接设置为https://a.b.c
或者是https://a.b.c/api/conversatio ？
我设置一直出错

前者错误代码是：OpenAI timed out waiting for response
后者错误代码是：OpenAI timed out waiting for response

**Comment by themis0009** [comment]
如果直接选择API_REVERSE_PROXY=https://a.b.c/v1/chat
那么会很快返回request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 108.160.xxx.xx:443

**Comment by Chanzhaoyu** [comment]
反代 `https://api.openai.com` 的话填这个 `OPENAI_API_BASE_URL`

**Comment by themis0009** [comment]
感谢大佬，成功了，谢谢~~~^^

**Comment by zhangyongsen** [comment]
> 感谢大佬，成功了，谢谢~~~^^
你好，我这边配置的时候遇到超时，我想知道是不是我的配置没写对，可以参考下你的env配置吗？

**Comment by themis0009** [comment]
> 

我没有配置，是直接借用别人的代码……用cloudf的解析

**Comment by weilun0510** [comment]
> OPENAI_API_BASE_URL

请问是 `OPENAI_API_BASE_URL=https://a.b.c/v1/chat`，还是`OPENAI_API_BASE_URL=https://a.b.c`
