### ISSUE TITLE
回答很慢 断断续续，经常出现

### ISSUE THREAD

**Issue by aql123** [Chanzhaoyu/chatgpt-web#1355]
![Uploading 5a22d208e82b8bdbf462a4fe5856e1d.png…]()

大佬  请指教一下
 用的是美国的服务器  
 经常出现回答很慢  断断续续的  ，有时候几个字就开始断断续续的了

**Comment by aql123** [comment]
用的是正常注册的账号的key

**Comment by yshmoon** [comment]
我昨天在openai账号里绑了虚拟信用卡，这两天回复速度都很快

**Comment by smartfat** [comment]
要么绑卡，要么用token

**Comment by guijianchou** [comment]
我今天重置了api，换了新的发现速度正常了。chatgpt_academic速度比web快不少，现在两者速度差不多

**Comment by git-syl** [comment]
断流是网络问题。你在用户浏览器到你外海服务器的接口之间，套个CDN支持长连接加速的就行。
然后把项目的后端VITE_GLOB_API_URL换成你CDN加速的地址就好了

或者
https://github.com/Chanzhaoyu/chatgpt-web/issues/1333
的思路，打字机效果从流改成前端动画逐个隐藏，后端一次性返回加过。
