### ISSUE TITLE
.env文件在docker哪个目录，怎么把环境变量.env文件使用-v映射到本地目录

### ISSUE THREAD

**Issue by goodnull** [Chanzhaoyu/chatgpt-web#1357]
使用下面命令也没有找到.env文件
```
docker exec -it chatgpt-web sh
find / -name .env
```

请问在.env文件的路径在哪？
我想使用-v映射.env文件到本地，这样我修改了环境变量，只需要重启容器即可
`docker run -v /home/.env:/app/.env --name chatgpt-web chenzhaoyu94/chatgpt-web`

**Comment by yuntao1997** [comment]
放当前目录就行了呀， 不需要挂载volume

`
docker run  --rm --env-file .env --name chatgpt-web chenzhaoyu94/chatgpt-web
`

**Comment by zhangbinhui** [comment]
> 放当前目录就行了呀， 不需要挂载volume
> 
> `docker run --rm --env-file .env --name chatgpt-web chenzhaoyu94/chatgpt-web`

老哥，我用的access-token，然后把token写入本地文件 ./myenv/chatgpt-web-service.env，执行：
docker run --name chatgpt-web -d \
-p 3002:3002 \
--env-file ./myenv/chatgpt-web-service.env \
chatgpt-web-510

就是不行，报错[OpenAI] 提供错误的API密钥 | Incorrect API key provided

但如果直接:
docker run --name chatgpt-web -d \
-p 3002:3002 \
--env OPENAI_ACCESS_TOKEN=my_accesstoken \
--env API_REVERSE_PROXY=http://172.17.0.1:8080/conversation \
chatgpt-web-510

这样就可以正常使用。
![myenv](https://github.com/Chanzhaoyu/chatgpt-web/assets/7031406/229ea92b-d5b8-462e-ad35-2b934f872c65)

why?
