### ISSUE TITLE
404错误

### ISSUE THREAD

**Issue by LiZheHui0** [Chanzhaoyu/chatgpt-web#1358]
ChatGPT error 404: {
"error": {
"message": "The model gpt-3.5 does not exist",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
这是咋回事

**Comment by huangwb8** [comment]
@LiZheHui0 建议选择这个模型： `gpt-3.5-turbo` 。 确实是没有 `gpt-3.5` 这个名字

**Comment by Chanzhaoyu** [comment]
默认情况下，所有参数不需要填，只需要填 Key 或者 Token 就好

**Comment by LiZheHui0** [comment]
模型在哪里改


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chanzhaoyu/chatgpt-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 晚上6:13
***@***.***&gt;;
抄送:&nbsp;"李哲辉 兰州信息科技学院 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chanzhaoyu/chatgpt-web] 404错误 (Issue #1358)





 
@LiZheHui0 建议选择这个模型： gpt-3.5-turbo 。 确实是没有 gpt-3.5 这个名字

**Comment by liuchang830** [comment]
我也是这种情况 请问怎么解决
