### ISSUE TITLE
报错：request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 199.96.58.157:443

### ISSUE THREAD

**Issue by DGYDavid** [Chanzhaoyu/chatgpt-web#1359]
求大佬帮忙解读一下

**Comment by luobo007** [comment]
我今天也遇到，你是处理了吗

**Comment by DGYDavid** [comment]
不清楚哦，这个我也解决不了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月12日 16:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Chanzhaoyu/chatgpt-web] 报错：request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 199.96.58.157:443 (Issue #1359) |

我今天也遇到，你是处理了吗

**Comment by Coooolrui** [comment]
解决了吗，求问

**Comment by DGYDavid** [comment]
没有解决，加油hhh




| |
南开大学经济学院戴冠英
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年4月16日 21:09 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Chanzhaoyu/chatgpt-web] 报错：request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 199.96.58.157:443 (Issue #1359) |

解决了吗，求问

**Comment by Mamba-24k** [comment]
我也遇到了， 怎么解决？

**Comment by commiot** [comment]
我也遇到了~

**Comment by SherlockerSun** [comment]
有人解决了吗
