### ISSUE TITLE
分销代理版大家可以测试下

### ISSUE THREAD

**Issue by codesdevs** [Chanzhaoyu/chatgpt-web#1368]
https://chat.wikll.com

**Comment by kof8855** [comment]
这个速度为什么这么快？是付费了吗？我免费版的api好慢，而且回答到一半还断流

**Comment by wujt1084** [comment]
accesToken的吧

**Comment by zohar175** [comment]
> 这个速度为什么这么快？是付费了吗？我免费版的api好慢，而且回答到一半还断流

我的是免费的，今早也好快，现在速度还是快的，不知道咋回事

**Comment by Lizh6** [comment]
源码能分享吗

**Comment by lph66152137** [comment]
> https://chat.wikll.com

源码有偿可以么

**Comment by liujie329** [comment]
怎么做到那么快的？

**Comment by kof8855** [comment]
> 怎么做到那么快的？

我也想知道他的这个怎么会响应这么快，我的就很慢

**Comment by codesdevs** [comment]
统一回复大家：用的开发者apikey，所以接口响应速度会很快。

**Comment by Ammar-hj** [comment]
> 

是$20一个月的那个吗？

**Comment by codesdevs** [comment]
> > 
> 
> 是$20一个月的那个吗？

$120的

**Comment by zohar175** [comment]
> > > 
> > 
> > 
> > 是$20一个月的那个吗？
> 
> $120的

120是啥？送的？

**Comment by onlyLTY** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > 是$20一个月的那个吗？
> 
> > 
> 
> > $120的
> 
> 
> 
> 120是啥？送的？

就是api绑卡。有些人用黑卡去绑。

**Comment by thenetguy** [comment]
> 统一回复大家：用的开发者apikey，所以接口响应速度会很快。

我正在使用API密钥，我的帐户可以访问GPT4 $120，但我得到的速度比这慢10倍

**Comment by codesdevs** [comment]
分销不需要自己apikey，走平台的
发件人: b002200 ***@***.***&gt;
发送时间: 2023年4月19日 21:27
收件人: Chanzhaoyu/chatgpt-web ***@***.***&gt;
抄送: liyuxiang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Chanzhaoyu/chatgpt-web] 分销代理版大家可以测试下 (Issue #1368)





 
分站开通后可以自己设置apikey吗？还是说必须在上面购买

**Comment by b002200** [comment]
就是所有的资金流水都走平台，那自己可以设置价格吗

**Comment by codesdevs** [comment]
资金走平台，价格在平台的成本价之上可以自定义。

------------------ 原始邮件 ------------------
发件人: b002200 ***@***.***&gt;
发送时间: 2023年4月19日 21:33
收件人: Chanzhaoyu/chatgpt-web ***@***.***&gt;
抄送: liyuxiang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Chanzhaoyu/chatgpt-web] 分销代理版大家可以测试下 (Issue #1368)





 
就是所有的资金流水都走平台，那自己可以设置价格吗
