### ISSUE TITLE
上次解决img被渲染后，现在所有的问题都不能换行了

### ISSUE THREAD

**Issue by luy98** [Chanzhaoyu/chatgpt-web#137]
![image](https://user-images.githubusercontent.com/102730238/221416706-9341dce0-b108-4403-bdae-eaf35d0a8acc.png)
![image](https://user-images.githubusercontent.com/102730238/221416728-59d4929e-d9a9-4ea9-8e94-e92c11f14358.png)
其实我在输入的时候是带有换行的，但是最终发送出去、在ChatGPT的页面看都没有换行。
这样完全不渲染的话，对一些场景会有影响。

**Comment by luy98** [comment]
图发错了，但是应该可以理解我说的意思。。

**Comment by Chanzhaoyu** [comment]
明白，就是提问输入是有换行，但是消息列表把换行符忽略了对吧
