### ISSUE TITLE
token没法用了吗

### ISSUE THREAD

**Issue by servother** [Chanzhaoyu/chatgpt-web#1374]
![image](https://user-images.githubusercontent.com/36033616/231051970-cdb0dd25-0702-4c6f-87fa-83cc9d284108.png)
之前都是用的好好的,今早提示无效了,是token没法用了吗,有大佬有这个同样的问题吗

**Comment by JasonYFY** [comment]
我也是，求问

**Comment by fishslidenas** [comment]
是不是过期了？Token一个月就过期

**Comment by servother** [comment]
> 是不是过期了？token一个月就过期了

是的,过期了,重新获取token就好了
