### ISSUE TITLE
后台接口返回正常，前端不显示响应内容

### ISSUE THREAD

**Issue by prettyboy** [Chanzhaoyu/chatgpt-web#1379]
![QQ截图20230411162344](https://user-images.githubusercontent.com/9334429/231101080-7da84103-30c1-4cc1-88eb-10e1a2ed9a24.png)

**Comment by ceozero** [comment]
我也遇到了。。刷新后之前的词都不显示了。
![1681212290782](https://user-images.githubusercontent.com/22513657/231147121-b8b54ba7-2b62-4b9a-84ab-ac9ddf635207.png)

**Comment by 575405657** [comment]
是不是配置了域名和反向代理？

**Comment by 575405657** [comment]
> > 是不是配置了域名和反向代理？
> 
> 确实配置了域名和反代。

可以试一下使用IP端口的方式访问。应该是反向代理服务器配置的问题
