### ISSUE TITLE
ChatGPTAPI 和 ChatGPTUnofficialProxyAPI 的对比

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#138]
目前个人 `Railway` 部署的使用 `accessToken` 的体验如下

个人感受：

- `Token` 过期有效期是一个月，我的目前仍然稳定中，所以并不担心更换的情况
- 个人测试不需要梯子就可以访问
- 比 `API Key` 回复效果强大，并且免费

使用习惯：

-  仅仅保持了 `2` 个有效会话
- 每小时不要超过访问上线

结论：

如果只是个人使用，想较于官网的双重认证，自我部署的 `accessToken` 目前能获得比较好的体验

个人主观感受，实际结果因人而异

**Comment by nn200433** [comment]
国内部署 accessToken 版貌似连不上啊？不需要梯子？

**Comment by jiusheng6** [comment]
ChatGPTUnofficialProxyAPI 能够自己部署吗？可以的话，具体是那个项目

**Comment by nn200433** [comment]
> ChatGPTUnofficialProxyAPI 能够自己部属吗？可以的话，具体是那个项目

那个是node版gpt客户端，是个模块，貌似没有提供部署方案

**Comment by Chanzhaoyu** [comment]
> ChatGPTUnofficialProxyAPI 能够自己部署吗？可以的话，具体是那个项目

使用 `accessToken` 就是调用 `ChatGPTUnofficialProxyAPI` 这个接口

**Comment by jiusheng6** [comment]
我知道，公开的代理比如https://chat.duti.tech/api/conversation是反代的https://chat.openai.com/backend-api/conversation，我想有没有项目能自己实现反代，不用公开的，毕竟公开的又不确定性

**Comment by nn200433** [comment]
> > ChatGPTUnofficialProxyAPI 能够自己部署吗？可以的话，具体是那个项目
> 
> 使用 `accessToken` 就是调用 `ChatGPTUnofficialProxyAPI` 这个接口

是这样的，问题是国内服务器貌似连不上啊，我已经配置了这两个其中一个地址了。
所以我才有疑问

| Reverse Proxy URL | Author | Rate Limits | Last Checked |
| --- | --- | --- | --- |
| `https://chat.duti.tech/api/conversation` | [@acheong08](https://github.com/acheong08) | 120 req/min by IP | 2/19/2023 |
| `https://gpt.pawan.krd/backend-api/conversation` | [@PawanOsman](https://github.com/PawanOsman) | ? | 2/19/2023 |

**Comment by Chanzhaoyu** [comment]
> > > ChatGPTUnofficialProxyAPI 能够自己部署吗？可以的话，具体是那个项目
> > 
> > 
> > 使用 `accessToken` 就是调用 `ChatGPTUnofficialProxyAPI` 这个接口
> 
> 是这样的，问题是国内服务器貌似连不上啊，我已经配置了这两个其中一个地址了。 所以我才有疑问
> 
> Reverse Proxy URL	Author	Rate Limits	Last Checked
> `https://chat.duti.tech/api/conversation`	[@acheong08](https://github.com/acheong08)	120 req/min by IP	2/19/2023
> `https://gpt.pawan.krd/backend-api/conversation`	[@PawanOsman](https://github.com/PawanOsman)	?	2/19/2023

我用的电信，我的可以使用

**Comment by Chanzhaoyu** [comment]
> 我知道，公开的代理比如[https://chat.duti.tech/api/conversation是反代的https://chat.openai.com/backend-api/conversation，我想有没有项目能自己实现反代，不用公开的，毕竟公开的又不确定性](https://chat.duti.tech/api/conversation%E6%98%AF%E5%8F%8D%E4%BB%A3%E7%9A%84https://chat.openai.com/backend-api/conversation%EF%BC%8C%E6%88%91%E6%83%B3%E6%9C%89%E6%B2%A1%E6%9C%89%E9%A1%B9%E7%9B%AE%E8%83%BD%E8%87%AA%E5%B7%B1%E5%AE%9E%E7%8E%B0%E5%8F%8D%E4%BB%A3%EF%BC%8C%E4%B8%8D%E7%94%A8%E5%85%AC%E5%BC%80%E7%9A%84%EF%BC%8C%E6%AF%95%E7%AB%9F%E5%85%AC%E5%BC%80%E7%9A%84%E5%8F%88%E4%B8%8D%E7%A1%AE%E5%AE%9A%E6%80%A7)

作者没有公开方式，除非去他代码里面找，然后自己部署

**Comment by nn200433** [comment]
> > > > ChatGPTUnofficialProxyAPI 能够自己部署吗？可以的话，具体是那个项目
> > > 
> > > 
> > > 使用 `accessToken` 就是调用 `ChatGPTUnofficialProxyAPI` 这个接口
> > 
> > 
> > 是这样的，问题是国内服务器貌似连不上啊，我已经配置了这两个其中一个地址了。 所以我才有疑问
> > Reverse Proxy URL	Author	Rate Limits	Last Checked
> > `https://chat.duti.tech/api/conversation`	[@acheong08](https://github.com/acheong08)	120 req/min by IP	2/19/2023
> > `https://gpt.pawan.krd/backend-api/conversation`	[@PawanOsman](https://github.com/PawanOsman)	?	2/19/2023
> 
> 我用的电信，我的可以使用

谢谢，我换了台服务器试了下，确实可以。

**Comment by star2k** [comment]
> 目前个人 `Railway` 部署的使用 `accessToken` 的体验如下
> 
> 
> 
> 个人感受：
> 
> 
> 
> - `Token` 过期有效期是一个月，我的目前仍然稳定中，所以并不担心更换的情况
> 
> - 个人测试不需要梯子就可以访问
> 
> - 比 `API Key` 回复效果强大，并且免费
> 
> 
> 
> 使用习惯：
> 
> 
> 
> -  仅仅保持了 `2` 个有效会话
> 
> - 每小时不要超过访问上线
> 
> 
> 
> 结论：
> 
> 
> 
> 如果只是个人使用，想较于官网的双重认证，自我部署的 `accessToken` 目前能获得比较好的体验
> 
> 
> 
> 个人主观感受，实际结果因人而异
> 
> 

请问，我用api key，能支持80人同时体验么？

**Comment by Chanzhaoyu** [comment]
> > 目前个人 `Railway` 部署的使用 `accessToken` 的体验如下
> > 个人感受：
> > 
> > * `Token` 过期有效期是一个月，我的目前仍然稳定中，所以并不担心更换的情况
> > * 个人测试不需要梯子就可以访问
> > * 比 `API Key` 回复效果强大，并且免费
> > 
> > 使用习惯：
> > 
> > * 仅仅保持了 `2` 个有效会话
> > * 每小时不要超过访问上线
> > 
> > 结论：
> > 如果只是个人使用，想较于官网的双重认证，自我部署的 `accessToken` 目前能获得比较好的体验
> > 个人主观感受，实际结果因人而异
> 
> 请问，我用api key，能支持80人同时体验么？

> 只要你有钞能力，你能支持 `180` 个人。（逃

具体并发你可能需要去看看官方文档

**Comment by Chanzhaoyu** [comment]
@star2k `accessToken` 太多人用会出现限制，就是你付费 `Plus` 都没用

**Comment by star2k** [comment]
> @star2k `accessToken` 太多人用会出现限制，就是你付费 `Plus` 都没用

这么说api key不容易崩咯，18美元也有几百条吧，给朋友们玩一下。

**Comment by Chanzhaoyu** [comment]
@star2k `api` 是根据字符算钱，如果多人用的话，建议你去修改下 `max_token` 参数

**Comment by star2k** [comment]
> @star2k `accessToken` 太多人用会出现限制，就是你付费 `Plus` 都没用

![Snipaste_2023-02-27_19-58-06](https://user-images.githubusercontent.com/9582078/221558705-40d266b6-e01c-4082-a003-ff1eb1aa4260.png)

点击，accessToken出不来，请问什么原因？

**Comment by yi-ge** [comment]
@Chanzhaoyu 为何不直接使用gpt-3.5-turbo，这个版本更新一点，gpt-3.5-turbo-0301是个快照呀。
