### ISSUE TITLE
使用warp的sock5代理怎么配置docker-compose啊

### ISSUE THREAD

**Issue by disTance7777** [Chanzhaoyu/chatgpt-web#1386]
已经试过在https_proxy配置和socks_proxy两个地方配置了，但是都不对

**Comment by qy8502** [comment]
我是用WARP这样配置的，但是仍然无法访问。
      SOCKS_PROXY_HOST: 127.0.0.1
      SOCKS_PROXY_PORT: 31303
      API_REVERSE_PROXY: https://chat.openai.com/backend-api/conversation

错误信息里仍然有1020
`
chatgpt-app-1  |   <h1>Access denied</h1>
chatgpt-app-1  |   <p>You do not have access to chat.openai.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
chatgpt-app-1  |   <ul class="cferror_details">
chatgpt-app-1  |     <li>Ray ID: 7b8a16c1482d2b51</li>
chatgpt-app-1  |     <li>Timestamp: 2023-04-16 05:39:37 UTC</li>
chatgpt-app-1  |     <li>Your IP address: 104.28.195.185</li>
chatgpt-app-1  |     <li class="XXX_no_wrap_overflow_hidden">Requested URL: chat.openai.com/backend-api/conversation </li>
chatgpt-app-1  |     <li>Error reference number: 1020</li>
chatgpt-app-1  |     <li>Server ID: FL_619F7</li>
chatgpt-app-1  |     <li>User-Agent: node-fetch</li>
chatgpt-app-1  |   </ul>
`

**Comment by disTance7777** [comment]
> 我是用WARP这样配置的，但是仍然无法访问。 SOCKS_PROXY_HOST: 127.0.0.1 SOCKS_PROXY_PORT: 31303 API_REVERSE_PROXY: https://chat.openai.com/backend-api/conversation
> 
> 错误信息里仍然有1020
> 
> ```
> chatgpt-app-1  |   <h1>Access denied</h1>
> chatgpt-app-1  |   <p>You do not have access to chat.openai.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
> chatgpt-app-1  |   <ul class="cferror_details">
> chatgpt-app-1  |     <li>Ray ID: 7b8a16c1482d2b51</li>
> chatgpt-app-1  |     <li>Timestamp: 2023-04-16 05:39:37 UTC</li>
> chatgpt-app-1  |     <li>Your IP address: 104.28.195.185</li>
> chatgpt-app-1  |     <li class="XXX_no_wrap_overflow_hidden">Requested URL: chat.openai.com/backend-api/conversation </li>
> chatgpt-app-1  |     <li>Error reference number: 1020</li>
> chatgpt-app-1  |     <li>Server ID: FL_619F7</li>
> chatgpt-app-1  |     <li>User-Agent: node-fetch</li>
> chatgpt-app-1  |   </ul>
> ```

我的报错是这个，还没有到你这步来
chatgpt-web | FetchError: request to https://bypass.churchless.tech/api/conversation failed, reason: connect ECONNREFUSED 127.0.0.1:40000
chatgpt-web |     at ClientRequest.<anonymous> (file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:108:11)
chatgpt-web |     at ClientRequest.emit (node:events:525:35)
chatgpt-web |     at onerror (/app/node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/dist/src/index.js:117:21)
chatgpt-web |     at callbackError (/app/node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/dist/src/index.js:136:17)
chatgpt-web |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
chatgpt-web |   type: 'system',
chatgpt-web |   errno: undefined,
chatgpt-web |   code: undefined,
chatgpt-web |   erroredSysCall: undefined
chatgpt-web | }

**Comment by qy8502** [comment]
> > 我是用WARP这样配置的，但是仍然无法访问。 SOCKS_PROXY_HOST: 127.0.0.1 SOCKS_PROXY_PORT: 31303 API_REVERSE_PROXY: https://chat.openai.com/backend-api/conversation
> > 错误信息里仍然有1020
> > ```
> > chatgpt-app-1  |   <h1>Access denied</h1>
> > chatgpt-app-1  |   <p>You do not have access to chat.openai.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
> > chatgpt-app-1  |   <ul class="cferror_details">
> > chatgpt-app-1  |     <li>Ray ID: 7b8a16c1482d2b51</li>
> > chatgpt-app-1  |     <li>Timestamp: 2023-04-16 05:39:37 UTC</li>
> > chatgpt-app-1  |     <li>Your IP address: 104.28.195.185</li>
> > chatgpt-app-1  |     <li class="XXX_no_wrap_overflow_hidden">Requested URL: chat.openai.com/backend-api/conversation </li>
> > chatgpt-app-1  |     <li>Error reference number: 1020</li>
> > chatgpt-app-1  |     <li>Server ID: FL_619F7</li>
> > chatgpt-app-1  |     <li>User-Agent: node-fetch</li>
> > chatgpt-app-1  |   </ul>
> > ```
> 
> 我的报错是这个，还没有到你这步来 chatgpt-web | FetchError: request to https://bypass.churchless.tech/api/conversation failed, reason: connect ECONNREFUSED 127.0.0.1:40000 chatgpt-web | at ClientRequest. (file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:108:11) chatgpt-web | at ClientRequest.emit (node:events:525:35) chatgpt-web | at onerror (/app/node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/dist/src/index.js:117:21) chatgpt-web | at callbackError (/app/node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/dist/src/index.js:136:17) chatgpt-web | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { chatgpt-web | type: 'system', chatgpt-web | errno: undefined, chatgpt-web | code: undefined, chatgpt-web | erroredSysCall: undefined chatgpt-web | }

你这是docker无法通过127.0.0.1访问主机，搜索相关知识
