### ISSUE TITLE
前端界面增加model可选框

### ISSUE THREAD

**Issue by Grypse** [Chanzhaoyu/chatgpt-web#1388]
现在的模型需要在部署时在环境变量中配置好，后续能不能在前端对话框增加一个模型可选框？哪位同学给搞下？我是做后端的，不懂前端咋搞。

**Comment by faidev** [comment]
同求前端页面切换模型的功能，accessToken方式用GPT-4模型有使用频率限制，希望前端可以方便的切换模型

**Comment by faidev** [comment]
![Uploading 43758833-2657-47C0-AC81-23AEC8E6A696.jpeg…]()

**Comment by faidev** [comment]
同求前端页面切换模型的功能，accessToken方式用GPT-4模型有使用频率限制，希望前端可以方便的切换模型
![AA29024D-FB76-4A81-AA54-2D693A6CFC6E](https://user-images.githubusercontent.com/20348767/231360138-ff6896d2-6958-4831-8ad2-6c5379f9cbc6.jpeg)

**Comment by kiritoko1029** [comment]
> 同求前端页面切换模型的功能，accessToken方式用GPT-4模型有使用频率限制，希望前端可以方便的切换模型

我fork实现了这个功能，你可以看我的仓库或者直接使用镜像 `docker pull 195658/chatgpt-web:latest`
<img width="837" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/43572494/063decbf-ccdf-47b6-8ec5-573b0dda75cd">
