### ISSUE TITLE
各位大佬pnpm build打包之后的前端文件报错

### ISSUE THREAD

**Issue by haihaimx** [Chanzhaoyu/chatgpt-web#1389]
各位大佬pnpm build打包之后的前端文件报错 怎么解决啊
![IMG_20230412_121057](https://user-images.githubusercontent.com/82726312/231347489-9bada4e6-d3fb-410d-a2ee-1335d9d1c4a9.jpg)

**Comment by chenshi1324** [comment]
我也遇到了 不知道什么问题  你解决了嘛
