### ISSUE TITLE
down了master分支的代码,变笨了,html没有有效的渲染

### ISSUE THREAD

**Issue by wangrui19970405** [Chanzhaoyu/chatgpt-web#139]
如图所示 只有一部分代码被渲染正确
还有答非所问不知道是不是官方的问题

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/49603204/221458953-5e7f6291-06a2-43a6-9f39-ea936eac16f8.png">

**Comment by Chanzhaoyu** [comment]
emmmm...

因为我一直用的是 `accessToken` ，所以好像忘记测试 `API Key` 下面的渲染问题

**Comment by wangrui19970405** [comment]
这还得用两种渲染吗，我还以为api和token返回的都一样呢

**Comment by Chanzhaoyu** [comment]
> 这还得用两种渲染吗，我还以为api和token返回的都一样呢

`api` 是纯文本， `token` 是富文本，你目前可以在提问的时候加上`用markdown`的形式返回来短暂处理这个问题。

**Comment by wangrui19970405** [comment]
我自己尝试修复一下吧

**Comment by waynedream** [comment]
坐等大佬修复，给大佬沏茶

**Comment by Chanzhaoyu** [comment]
会优先修复，我的问题，忘记测试了

**Comment by Chanzhaoyu** [comment]
暂时没有找到好的判断 `API` 版本返回纯文本所包含代码该渲染成什么格式的问题，可能会延长延长延长延长延长延长，直到我研究出来

**Comment by Chanzhaoyu** [comment]
hello，`2.8.2`已调整，你再试一下，不过因为 `API` 返回的是纯文本，所以可能只有一部分代码会高亮
