### ISSUE TITLE
引入对联网的支持

### ISSUE THREAD

**Issue by Passerby1011** [Chanzhaoyu/chatgpt-web#1393]
在这个网页demo中应该是引入了newbing的搜索答案，所达到的效果意外的非常非常的的棒，比单纯的二者都要棒，应该是该项目的魔改，但作者https://github.com/binjie09   并没有自己的项目，希望能借鉴或者引入试试
https://chat.yqcloud.top/

**Comment by iamflowerdog** [comment]
我试了一下，楼上的根本没有联网。。。。
![image](https://user-images.githubusercontent.com/27678693/231371485-85ff4ade-b994-4f6c-91ee-fb5c045313f4.png)

**Comment by Passerby1011** [comment]
![Screenshot_20230412_150023_com yandex browser alpha](https://user-images.githubusercontent.com/63802758/231377307-5740730f-5457-4545-8ec8-80e4345f9f49.jpg)
![Screenshot_20230412_145902_com yandex browser alpha](https://user-images.githubusercontent.com/63802758/231377318-503140f1-a66c-4d05-8103-91377fdf2f3d.jpg)

**Comment by Passerby1011** [comment]
好家伙，按钮联网，我多试了试新闻，它给的有模有样的，好像都是搜索出来的，结果都是编的

**Comment by assassinliujie** [comment]
我写是写了但是觉得意义不大
