### ISSUE TITLE
GPT-3.5 免费版已经下放了

### ISSUE THREAD

**Issue by James-handsome** [Chanzhaoyu/chatgpt-web#1394]
![05dd2b95bef24a2bff7a6cffe9cf4fa](https://user-images.githubusercontent.com/54829185/231371989-273489fe-4033-4557-b5f3-20afed332a00.png)

**Comment by ceozero** [comment]
> web端一直都是 3.5 呀~ 只有早期Api是3.0

现在的api也只能算3.0.。没有网页端智能.

**Comment by wakefun** [comment]
为啥我的回答还是：我是OpenAI训练的大型语言模型ChatGPT，目前最新版本是GPT-3。
docker参数是：OPENAI_API_MODEL: gpt-3.5-turbo

**Comment by youzeliang** [comment]
> 



> 

对。我也是这样

**Comment by assassinliujie** [comment]
> > web端一直都是 3.5 呀~ 只有早期Api是3.0
> 
> 现在的api也只能算3.0.。没有网页端智能.

3.5-LEGACY和turbo俩版本，trubo应该是量化后的版本，生成速度快一些
