### ISSUE TITLE
Railway 部署的 现在不可用了

### ISSUE THREAD

**Issue by iamflowerdog** [Chanzhaoyu/chatgpt-web#1395]
怀疑是，Railway官方 发现部署这样的太多了，导致Railway官方的ip 被屏蔽多了，直接不让用了
![image](https://user-images.githubusercontent.com/27678693/231372332-53369809-5e94-4000-823f-16ec976490a4.png)

**Comment by lovelywxd** [comment]
+1

**Comment by tourusa** [comment]
railwwy每个月有时长限制
