### ISSUE TITLE
请问，如何直接访问后端服务，不用通过浏览器调用前端？

### ISSUE THREAD

**Issue by simzhangbest** [Chanzhaoyu/chatgpt-web#1398]

**Comment by huangwb8** [comment]
该项目似乎暂时只是一个前端演示。包含Chanzhaoyu在内的多个开发者正在准备一个强大的后端管理系统。 我目前用的是一个基于mongoDB的demo，支持多用户聊天信息管理： https://blognas.hwb0307.com/linux/docker/4201 感兴趣可以看看噢 (ฅ´ω`ฅ)
