### ISSUE TITLE
大佬，有没有遇到npm run build的时候遇到这个error？

### ISSUE THREAD

**Issue by ximeicuc-git** [Chanzhaoyu/chatgpt-web#1403]
![image](https://user-images.githubusercontent.com/70133835/231409130-c1fb8be2-23b4-4710-a701-eb36584447fd.png)

**Comment by Chanzhaoyu** [comment]
这个还没碰到过

**Comment by Ninjaer** [comment]
dmesg看看是不是OOM kill了
