### ISSUE TITLE
没有上下文，使用的是access_token。之前用api也是如此

### ISSUE THREAD

**Issue by DaoyiWeiwo** [Chanzhaoyu/chatgpt-web#1404]
![sad](https://user-images.githubusercontent.com/57880540/231409334-96a5e5f4-5f92-4b3d-9069-b8ab6012665b.png)

**Comment by huoshicang** [comment]
你部署的环境变量可以看看吗，我想用access_token，不知道为啥用不了，添加TIMEOUT_MS=0试试

**Comment by DaoyiWeiwo** [comment]
已解决。删除全部聊天记录重启下就好了
