### ISSUE TITLE
请问默认的头像链接，名称，描述设置在哪里啊？想换一下默认设置，这样在不同设备中打开的都是自己的名字。

### ISSUE THREAD

**Issue by USST-ZQS** [Chanzhaoyu/chatgpt-web#1406]
![image](https://user-images.githubusercontent.com/78264578/231412930-235afa68-fb37-4a70-9947-786e775b9ea6.png)

**Comment by sunmaxwell666** [comment]
@修改无用啊

> 修改文件 src/store/modules/user/helper.ts
> 
> * [chatGPT-WEB一键部署脚本，可自定义描述信息，可参考](https://github.com/dqzboy/ShellProject/tree/main/ChatGPT/ChatGPT-WEB)

修改后没用啊，咋回事儿

**Comment by techxiaofei** [comment]
这个只能通过修改源码重新编译吗，不能支持通过配置？这样就不用每个人都自己编译了。一个Docker搞定了

**Comment by huangwb8** [comment]
@USST-ZQS  @techxiaofei 

会用docker的话，建议关注本项目的衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 。 基于MongoDB后端，支持API或Access Token模式。目前的功能包括：多用户登录/注册、数据库管理、对话云端保存和管理、敏感词管理、自定义提示词、多Key轮询、用户管理、自定义模型等（[v2.13.0](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.13.0)起）。该项目是完全开源和免费的！具体教程见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

另外，Chanzhaoyu大佬在2023-04-26建了一个QQ群734133205，介绍了源项目的plus版本——chatgpt-web-plus，其包含个人部署、商业部署、企业部署和团队部署等内容。项目地址在[Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)，非开源且付费（好像是1000多元/份？）。感兴趣的小伙伴可以关注 [chatgpt-web-plus · Issue #1606 · Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web/issues/1606)。

祝好！
