### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by renjiankun12** [Chanzhaoyu/chatgpt-web#1407]
前后端都部署好了，代理也配置好了，但是聊天的时候一直提示连接超时

![12A8F8C5-0E51-456b-911D-7EC5FA66C302](https://user-images.githubusercontent.com/37288694/231415774-04183ce0-a909-4971-a8bf-6dcd52f836c4.png)
![1681291422038_53E38B58-0F60-4bdf-9FCB-B69BB84374EB](https://user-images.githubusercontent.com/37288694/231415861-9fd2c3be-d87a-4d14-9666-2d7df17cfce1.png)

**Comment by JoshuaYang2001** [comment]
我也出现了这个went

**Comment by JoshuaYang2001** [comment]
同样出现了这个问题

**Comment by renjiankun12** [comment]
> 同样出现了这个问题

我解决了 我把server文件夹放到我买的美国的服务器下面去运行，然后在根目录的.env文件下修改一下代理地址就可以了

**Comment by JoshuaYang2001** [comment]
好的 我去试一下
