### ISSUE TITLE
这个速度为什么这么快？是付费了吗？我免费版的api好慢，而且回答到一半还断流

### ISSUE THREAD

**Issue by codesdevs** [Chanzhaoyu/chatgpt-web#1408]
用的开发者apikey，所以接口响应速度会很快。
https://chat.wikll.com

**Comment by wujt1084** [comment]
怎么申请？

**Comment by ceozero** [comment]
绑卡付5刀，速度起飞。。。实测。

**Comment by codesdevs** [comment]
> 怎么申请？

购买$120的apikey账户

**Comment by xiaosaaaa** [comment]
免费的现在非常慢

**Comment by ceozero** [comment]
> > 怎么申请？
> 
> 购买$120的apikey账户

120刀的账户就一个月使用期吧。

**Comment by codesdevs** [comment]
是的，apikey调用额度是当月清零的
可以通过这个网址获取120$ &nbsp;&nbsp;https://fk.suolj.com/trade/59.html

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ceozero ***@***.***&gt;
发送时间: 2023年4月12日 21:14
收件人: Chanzhaoyu/chatgpt-web ***@***.***&gt;
抄送: liyuxiang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Chanzhaoyu/chatgpt-web] 这个速度为什么这么快？是付费了吗？我免费版的api好慢，而且回答到一半还断流 (Issue #1408)

**Comment by jh410** [comment]
国内服务器实在是用不了啊，哭死

**Comment by RexWzh** [comment]
这个需要注册新号吗，旧号过期了绑卡余额会更新吗

**Comment by wangpre** [comment]
> 国内服务器实在是用不了啊，哭死

百度搜一下  OpenAI API 代理

**Comment by 6uu1** [comment]
牛逼，怎么这么多自问自答推销的。。。。

**Comment by yangyj2000** [comment]
> 牛逼，怎么这么多自问自答推销的。。。。

？我就是一小白，不然你说说看你有什么好的方法能充值，我学一学

**Comment by 6uu1** [comment]
> > 牛逼，怎么这么多自问自答推销的。。。。
> 
> ？我就是一小白，不然你说说看你有什么好的方法能充值，我学一学
🥲我说的是楼主。。。

**Comment by qsc19971022** [comment]
不要买120刀的这种，很坑 不如自己冲10个币 安全

**Comment by RexWzh** [comment]
@Chanzhaoyu 大佬，有人在这里卖号。。。。建议关掉。

顺便提醒下大家，卖的这种号不稳定，可能隔几天就ban了，联系商家只会退一小部分钱。真想弄这类号，自己开虚拟卡去整一个，成本5美刀，比买号实在多了。。。

**Comment by AndySkaura** [comment]
![image](https://user-images.githubusercontent.com/26220564/231962048-fe4dc66b-bd6d-4e20-b92a-18fc26fae115.png)
9.9买了一天无限制的key,结果发现是他们自己平台的,不是openai的key.
提了工单要求给后台反代地址自己部署,今天发现工单订单都没有了.

**Comment by 0lqd0** [comment]
> 不要买120刀的这种，很坑 不如自己冲10个币 安全

120刀咋坑了，求问
