### ISSUE TITLE
docker部署，nginx反向代理后，访问域名css和js不停的返回301，且页面一直处于加载

### ISSUE THREAD

**Issue by yichen666888** [Chanzhaoyu/chatgpt-web#141]
docker部署，nginx反向代理后，访问域名css和js不停的返回301，且页面一直处于加载

**Comment by Chanzhaoyu** [comment]
> 

这个需要你自己去 `issues` 中参考下别人的配置

**Comment by yichen666888** [comment]
> > 
> 
> 这个需要你自己去 `issues` 中参考下别人的配置

找到问题了 不支持https反代

**Comment by Chanzhaoyu** [comment]
所以我得关闭这个问题了

**Comment by Suyknow** [comment]
> > 这个需要你自己去 `issues` 中参考下别人的配置
> 
> 找到问题了 不支持https反代

@yichen666888 支持的，但是对于stream，需要设置udp转发。
给你参考一下我用的。

```
stream {
    upstream chatgpt {
        server localhost:http端口号;
    }
    
    server {
        listen https端口号 ssl;
            ssl_certificate "证书crt地址";
            ssl_certificate_key "证书key地址";
            proxy_pass chatgpt;
    }
    server {
        listen https端口号 udp reuseport;
            proxy_pass chatgpt;
    }
}
```

注意，以上stream的代码块，需要在http代码块以外，具体可以参考nginx的教程。

**Comment by hnuzhoulin** [comment]
> > > 这个需要你自己去 `issues` 中参考下别人的配置
> > 
> > 
> > 找到问题了 不支持https反代
> 
> @yichen666888 支持的，但是对于stream，需要设置udp转发。 给你参考一下我用的。
> 
> ```
> stream {
>     upstream chatgpt {
>         server localhost:http端口号;
>     }
>     
>     server {
>         listen https端口号 ssl;
>             ssl_certificate "证书crt地址";
>             ssl_certificate_key "证书key地址";
>             proxy_pass chatgpt;
>     }
>     server {
>         listen https端口号 udp reuseport;
>             proxy_pass chatgpt;
>     }
> }
> ```
> 
> 注意，以上stream的代码块，需要在http代码块以外，具体可以参考nginx的教程。

我按照这个配置或者直接配置在http里面，效果都是结果一次性全部返回，没有类似打字机的效果出来也。是哪里不对吗？

`upstream chatgpt {
    server XXXXX:3002;
}

server {
    listen 443 ssl;
    #server_name  chat-web.runjian.com;
    ssl_certificate  /ssl/XXXXX.pem;
    ssl_certificate_key  /ssl/XXXX.key;
    proxy_pass chatgpt;
}
server {
    listen 443 udp reuseport;
    #server_name  chat-web.runjian.com;
    proxy_pass chatgpt;
}
`

**Comment by hnuzhoulin** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/issues/147
在这里面实现了
