### ISSUE TITLE
下个版本有没有加vercel部署的想法

### ISSUE THREAD

**Issue by jinghuala** [Chanzhaoyu/chatgpt-web#1412]
1

**Comment by zigou23** [comment]
api可以，token估计不行。你可以去 [Yidadaa/ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web) 看一下

**Comment by Li-GL** [comment]
> api可以，token估计不行。你可以去 [Yidadaa/ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web) 看一下

为什么我api部署的也是500呢，问一下有特别的配置吗

**Comment by Li-GL** [comment]
@zigou23 为什么我api部署的也是500呢，问一下有特别的配置吗

**Comment by zigou23** [comment]
> @zigou23 为什么我api部署的也是500呢，问一下有特别的配置吗

哪个？环境变量正确填写了吗？
