### ISSUE TITLE
有没有大佬提供一个chatweb的网址用用

### ISSUE THREAD

**Issue by yydsluo** [Chanzhaoyu/chatgpt-web#1414]

**Comment by vastxie** [comment]
chatgpt.vast123.com 开了一小时10次提问的限制

**Comment by vastxie** [comment]
[](chatgpt.vast123.com)

**Comment by vastxie** [comment]
[chatweb](chatgpt.vast123.com)

**Comment by 2019clover** [comment]
我是后端 java，经过这几个星期的使用，感觉对api提问技术问题的回答不如去官网提问技术的回答。
我看接入的api访问和去官网访问的 chatgpt的版本都是3.5

**Comment by liu-peiyu** [comment]
https://chat.chat13.com

**Comment by CaoYunzhou** [comment]
> https://chatgpt.vast123.com 开了一小时10次提问的限制

你的为啥这么快？

**Comment by codesdevs** [comment]
http://chat.wikll.com

**Comment by ddkwing** [comment]
https://chat.kosmos.pink 需要公众号获取一个码， 之后免费

**Comment by winteroo** [comment]
http://yl.iisai.cn  稳定快速
