### ISSUE TITLE
更改为非3002的端口，都无法运行，改回3002就可以了。

### ISSUE THREAD

**Issue by randerswan** [Chanzhaoyu/chatgpt-web#1415]
docker run  --name chatgpt-web  -p 55535:55535...
docker run  --name chatgpt-web  -p 3333:3333...
尝试过55535和3333，Docker运行正常，但网页无法访问。

然后用docker ps查看已有实例，发现有3002/tcp的字样：

CONTAINER ID   IMAGE                             COMMAND                   CREATED         STATUS         PORTS                                                 NAMES
46219e5e0ce3   chenzhaoyu94/chatgpt-web:latest   "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   3002/tcp, 0.0.0.0:3333->3333/tcp, :::3333->3333/tcp   chatgpt-web

**Comment by AndySkaura** [comment]
你要是没改源码的话,应该是docker run --name chatgpt-web -p 3333:3002...

**Comment by SeduceQAQ** [comment]
代码里写死了3002端口，看看Dockerfile

**Comment by misszhangzhihui** [comment]
有没有一种可能你端口不应该这样改？我记得docker应该是改-p 65535:3002，还是3002:65535，只改一个端口才对
