### ISSUE TITLE
求大佬分享一份nginx octet-stream配置代码

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#142]
试过了几个代码，都不能正确输出流数据，哪位大佬能分享一下吗？谢谢

**Comment by cy-i** [comment]
关注一下，我也试了很多方法，都不行！

**Comment by GH6324** [comment]
一样，不输出数据。。

**Comment by Siri-Li** [comment]
`
    # 设置反向代理参数以支持流式输出
    proxy_buffering off;
    chunked_transfer_encoding on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
`

**Comment by ludashi2020** [comment]
> proxy_buffering off

location /api/chat-process { 
  types { 
    application/octet-stream octet-stream;
  }

if ($request_method = 'OPTIONS') { 
    add_header Access-Control-Allow-Origin *; 
    add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
    add_header Access-Control-Allow-Headers *;
    return 204;
}

add_header Access-Control-Allow-Origin *; 
add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
add_header Access-Control-Allow-Headers *;  
}

需要加这个吗？

**Comment by ludashi2020** [comment]
感谢分享

**Comment by leeggco** [comment]
同样试了很多方式都不行。

**Comment by zhaohao19941221** [comment]
同样试了很多方式都不行。

**Comment by zhaohao19941221** [comment]
> 
试了一下还是不行

**Comment by xnng** [comment]
终于解决了，还是得靠 chatgpt，人类一败涂地
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/38936252/226843942-a410be81-389a-4ace-b9d5-20257e392422.png">
