### ISSUE TITLE
在Docker中启动项目后，访问地址、自定义的名称和描述以及提示词保存不了

### ISSUE THREAD

**Issue by wumiann** [Chanzhaoyu/chatgpt-web#1420]
在群晖的Docker中启动项目后，访问地址、自定义的名称和描述以及提示词设置好保存以后，只在当前电脑和浏览器中生效，切换设备和更换浏览器就恢复默认值了，这个怎么解决呢

**Comment by Chanzhaoyu** [comment]
聊天记录可导出，因为是保存在本地，跨终端需要自己开发。

**Comment by huangwb8** [comment]
@wumiann  

可以试试本项目的衍生项目的[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)，功能稍微多样化了一些。

用户信息和聊天室可以通过MongoDB管理。具体安装教程（基于Docker）可见我的博客： https://blognas.hwb0307.com/linux/docker/4201 

这个衍生项目的更多的讨论可见issue: [feat: 添加注册登录&同步聊天数据 by Kerwin1202 · Pull Request #589 · Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web/pull/589)。 

另一个衍生项目[gouguoyin/chatgpt-web](https://github.com/gouguoyin/chatgpt-web) 也在开发当中，可适当关注。
