### ISSUE TITLE
部署之后，首次访问页面加载巨慢，有一个文件1.5MB ,哪位大佬有时间优化一下啊   万分感谢。部署在AWS上面的，第一次访问页面。

### ISSUE THREAD

**Issue by ALEXKINGS** [Chanzhaoyu/chatgpt-web#1421]
![无标题](https://user-images.githubusercontent.com/37866571/231712990-9e147448-de4d-4fc0-b93c-d72b7f4e003d.png)
![无标12题](https://user-images.githubusercontent.com/37866571/231713462-7db49de9-69bc-446d-a95c-c1f0b55a39b5.png)

**Comment by chenyinkai** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/pull/1082 可以参考这个，加个gzip

**Comment by lcg890831** [comment]
我也是啊，超级超级慢

**Comment by shishugen** [comment]
我也有这个问题，加载很慢，请问解决问题了吗？

**Comment by shishugen** [comment]
> #1082 可以参考这个，加个gzip

页面不存在了
