### ISSUE TITLE
我用docker部署的，为什么没有上下文，是opeanai的问题吗？

### ISSUE THREAD

**Issue by samkuang1120** [Chanzhaoyu/chatgpt-web#1422]
聊天没有上下文信息，每次让它继续上一个问题，它都不会回答，没有记忆。

**Comment by huangwb8** [comment]
@samkuang1120  可以试试该项目的[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)，用户信息和聊天室可以通过MongoDB管理。具体安装教程（基于Docker）可见我的博客： https://blognas.hwb0307.com/linux/docker/4201

**Comment by samkuang1120** [comment]
@huangwb8 试了下部署，正常运行，不错的项目。谢谢

**Comment by samkuang1120** [comment]
@huangwb8 你知道如何审核新注册的用户吗？

**Comment by huangwb8** [comment]
> @huangwb8 你知道如何审核新注册的用户吗？

我以前试过开放注册但不需要验证，是可行的；但同时开放注册和审核还没试过。

我的文章里写了： 

点亮`新用户`表明你开放注册；点亮`新用户审核`表明该用户需要你审核才可以使用。如果你开放注册，一般建议这两者都要点亮。**如果你不想开放注册，将`新用户`点暗即可**。即时生效，不用重启docker stack。

![image](https://user-images.githubusercontent.com/35643122/231953071-0fb2b2da-d13b-4337-9be3-949a600f885d.png)

不过，我主要是在数据库后台直接添加非注册用户。

**Comment by samkuang1120** [comment]
@huangwb8 试了下，开放注册，和新用户注册都会有邮件，在管理员的邮件会收到一个审核新用户的邮件，点击审核通过就可以了。谢谢。

**Comment by huangwb8** [comment]
@samkuang1120  这应该是目前最好的chat-web衍生项目了 不过改良项目的作者没开issue 可能也是想着自己玩玩而已 (ฅ´ω`ฅ) 咱们也就先凑合着用吧！

**Comment by samkuang1120** [comment]
seems to be a network issue.

**Comment by Kerwin1202** [comment]
> @samkuang1120 这应该是目前最好的chat-web衍生项目了 不过改良项目的作者没开issue 可能也是想着自己玩玩而已 (ฅ´ω`ฅ) 咱们也就先凑合着用吧！

原来是我没开 issue，我说有的人一直在 几百层楼叠加。。 只不过我前端不太好，费时间，所以没有太改，其实有时候想改不少想玩的
