### ISSUE TITLE
前端pnpm build报错

### ISSUE THREAD

**Issue by eureka176** [Chanzhaoyu/chatgpt-web#1423]
~/src/chatgpt/chatgpt-web$ pnpm build

> chatgpt-web@2.10.9 build /home/eureka/src/chatgpt/chatgpt-web
> run-p type-check build-only

> chatgpt-web@2.10.9 build-only /home/eureka/src/chatgpt/chatgpt-web
> vite build

> chatgpt-web@2.10.9 type-check /home/eureka/src/chatgpt/chatgpt-web
> vue-tsc --noEmit

vite v4.2.0 building for production...
transforming (486) node_modules/.pnpm/naive-ui@2.34.3_vue@3.2.47/node_modules/naive-ui/es/spin/src/Spin.jsKilled
 ELIFECYCLE  Command failed with exit code 137.
transforming (495) node_modules/.pnpm/naive-ui@2.34.3_vue@3.2.47/node_modules/naive-ui/es/table/src/Tbody.js ELIFECYCLE  Command failed.
ERROR: "type-check" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
操作系统：
5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

**Comment by lcg890831** [comment]
我也碰到一样的问题，问了chatgpt说是内存不足，加了swap解决的，
创建一个交换文件并启用交换空间的示例如下：

# 创建一个4G大小的交换文件
sudo fallocate -l 4G /swapfile

# 设置交换文件权限
sudo chmod 600 /swapfile

# 设置交换空间
sudo mkswap /swapfile

# 启用交换空间
sudo swapon /swapfile
要使交换空间在系统重启后依然生效，需要将其添加到/etc/fstab文件：


echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
