### ISSUE TITLE
使用 OPENAI_ACCESS_TOKEN 的方式 应该会过期吧  能自动更新吗?

### ISSUE THREAD

**Issue by AnNaiJin1** [Chanzhaoyu/chatgpt-web#1425]
我用api_key的方式部署成功了  但是 用OPENAI_ACCESS_TOKEN 部署请求错误 

我看redame里面 只需要更改 把api_key  替换为 OPENAI_ACCESS_TOKEN 这个 环境变量就行了

还有其它需要改的地方吗?
有部署成功的大佬给指点一下 谢谢

**Comment by ikiwihome** [comment]
readme中的两个代理都用不了了，https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全
