### ISSUE TITLE
使用access token之前可以现在报错[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

### ISSUE THREAD

**Issue by wxzdyq** [Chanzhaoyu/chatgpt-web#1426]
账号可以登录没有被封，查看access token也没有更新，难道代理出问题了吗用的https://bypass.churchless.tech/api/conversation

**Comment by ake02** [comment]
1020了，被封了

**Comment by comeonsunny** [comment]
same issue

**Comment by wxzdyq** [comment]
> 



> 1020了，被封了

老哥，意思是这个代理不能用了吗

**Comment by ake02** [comment]
不能了 自己搭建一个吧哈哈

**Comment by Carzy-feng** [comment]
> 账号可以登录没有被封，查看access token也没有更新，难道代理出问题了吗用的https://bypass.churchless.tech/api/conversation

老哥你弄好了吗

**Comment by wxzdyq** [comment]
> > 账号可以登录没有被封，查看access token也没有更新，难道代理出问题了吗用的https://bypass.churchless.tech/api/conversation
> 
> 老哥你弄好了吗

还没呢，我刚刚才发现这个问题

**Comment by iknow2333** [comment]
寄了，悲

**Comment by comeonsunny** [comment]
怎么查看它用的代理的代码呢？

**Comment by wxzdyq** [comment]
> 不能了 自己搭建一个吧哈哈

搭建流程老哥有指导的连接参考不

**Comment by juPhae** [comment]
我要开始以为是我号无了

**Comment by lery666** [comment]
我以为我号无了，出去之后发现可以登陆，原来是代理无了

**Comment by Carzy-feng** [comment]
现在能用了

**Comment by iknow2333** [comment]
现在好了又

**Comment by ikiwihome** [comment]
readme中的两个代理都用不了了，https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全
