### ISSUE TITLE
Did you mean to use v1/completions?

### ISSUE THREAD

**Issue by ysuzy** [Chanzhaoyu/chatgpt-web#1428]
ChatGPT error 404: {
"error": {
"message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
"type": "invalid_request_error",
"param": "model",
"code": null
}
}

搭建完成后输入内容后，就反馈上面的错误提示，api回调是正常的，这是什么情况呢？

**Comment by huangwb8** [comment]
@ysuzy  `OPENAI_API_MODEL`参数设置为`gpt-3.5-turbo`试试
