### ISSUE TITLE
能不能让自动添加continue，或者自动输入指令 请继续 ?

### ISSUE THREAD

**Issue by zhuangzard** [Chanzhaoyu/chatgpt-web#1431]
相比大家和我有一样的烦恼，输入到一半，字数限制，你的写continue，或者继续，让他继续写。
老大，都是人工智能了，还得需要一个保姆来打继续两个字吗？
能不能在我们的版本里，自动添加补充 continue和继续的 功能？我认为这会让这个比原版更加丝滑。

**Comment by csu-czh** [comment]
开启长回复就行。前端有个配置，监测到长度限制就会continue

**Comment by zhuangzard** [comment]
谢谢回复，有没有具体的文档或者设置方法？> 开启长回复就行。前端有个配置，监测到长度限制就会continue

**Comment by csu-czh** [comment]
项目根目录下 .env 添加VITE_GLOB_OPEN_LONG_REPLY=true

**Comment by zhuangzard** [comment]
谢谢回复，开启了，但是还是的需要输入continue，是我设置的问题？生成code一半，依然的输入继续。

**Comment by csu-czh** [comment]
全局搜索VITE_GLOB_OPEN_LONG_REPLY，看看哪里调用了 ，你改成硬编码。好像是有bug。同时在控制台看网络请求，看看结束原因为length还是fail。

**Comment by zhuangzard** [comment]
我是用synology的docker直接部署从docker hub上下载的image， 从这个[说明里最后一行](https://github.com/Chanzhaoyu/chatgpt-web/blob/639152f9872f92b71e13ebdaa6fe03eceddc2e11/README.md#%E5%89%8D%E7%AB%AF%E7%BD%91%E9%A1%B5)： 说：接口每次返回的内容是有长度限制的，可以修改根目录下.env文件中的VITE_GLOB_OPEN_LONG_REPLY字段，将其设置为true，重新编译前端即可开启长回复功能，即可返回全部的内容。需要注意的是，使用此功能可能带来较多的API使用费用。 我是不是简单的添加环境变量还不行，他让我重新编译前端，有没有可能是由于我需要重新生成一个image？

**Comment by csu-czh** [comment]
是的，build就行
