### ISSUE TITLE
请问在哪里修改chatgpt-web的index.html文件，我想修改掉<title>ChatGPT Web</title> 我尝试进入容器，但进不去。感谢

### ISSUE THREAD

**Issue by kwingart** [Chanzhaoyu/chatgpt-web#1433]
我想修改掉<title>ChatGPT Web</title> 
docker exec -it 5d7c2d142564  bash
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": execunown

**Comment by ioc2008** [comment]
docker exec -it 5d7c2d142564 /bin/sh

**Comment by weareware** [comment]
你不会问gpt？
docker exec -it 你的容器名 ash
cd public 
vi index.html

**Comment by kwingart** [comment]
就是进不去容器才问下你们这些高手

***@***.*** ~]# docker ps
CONTAINER ID   IMAGE                             COMMAND
 CREATED        STATUS        PORTS
   NAMES
07ef02a48069   6053537/portainer-ce              "/portainer"
24 hours ago   Up 24 hours   8000/tcp, 9443/tcp, 0.0.0.0:9000->9000/tcp
  portainer
2cbb63351529   chenzhaoyu94/chatgpt-web:latest   "docker-entrypoint.s…"
25 hours ago   Up 24 hours   0.0.0.0:7678->3002/tcp
  chatgpt-web
***@***.*** ~]#
***@***.*** ~]#
***@***.*** ~]#
***@***.*** ~]# docker exec -it chatgpt-web /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:380: starting
container process caused: exec: "/bin/bash": stat /bin/bash: no such file
or directory: unknown
***@***.*** ~]#



weareware ***@***.***> 于2023年4月14日周五 22:08写道：

**Comment by kwingart** [comment]
明白了，用ash，谢谢

**Comment by imldy** [comment]
可以用外层的Nginx filter模块修改，这样就不涉及docker容器内，也不会被docker镜像更新所影响。
