### ISSUE TITLE
gpt回复长文本时断流

### ISSUE THREAD

**Issue by mklin1999** [Chanzhaoyu/chatgpt-web#1435]
为什么GPT回复到一半就断流了，这是api接口本身的问题吗？还是自己服务的问题？

**Comment by leeyxq** [comment]
me too, rollback

**Comment by fhkong** [comment]
Me too. Please, how to fix it?

**Comment by suchdisease** [comment]
download latest code and build,delete release version.

**Comment by wmwgijol28** [comment]
v2.10.9版本chatgpt 5.2.2有问题,使用main分支 已回退 5.1.2
