### ISSUE TITLE
每次问答都会出现这个404问题

### ISSUE THREAD

**Issue by liuchang830** [Chanzhaoyu/chatgpt-web#1440]
ChatGPT error 404: {
"error": {
"message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
"type": "invalid_request_error",
"param": "model",
"code": null
}
}

**Comment by zhangzq** [comment]
模型填错了，填到一些非对话的模型了。

**Comment by liuchang830** [comment]
但是我是按照教程来填的 教程地址https://allencj.com/archives/2023/27/1536/ 请问该如何修改呢
