### ISSUE TITLE
不知能否和你取得联系

### ISSUE THREAD

**Issue by jamyriver** [Chanzhaoyu/chatgpt-web#1441]
我是一个创业者，对AI应用方面有一些想法和思路，希望能加个联系方式，一起实现理想和抱负。

**Comment by zhangzq** [comment]
楼上就缺一个程序员了 :)

**Comment by xueguizheng** [comment]
> 我是一个创业者，对AI应用方面有一些想法和思路，希望能加个联系方式，一起实现理想和

> 我是一个创业者，对AI应用方面有一些想法和思路，希望能加个联系方式，一起实现理想和抱负。

加我qq1243761088  已对项目进行商业化二开合作加我
