### ISSUE TITLE
苹果手机无法打开页面

### ISSUE THREAD

**Issue by danbo-c** [Chanzhaoyu/chatgpt-web#1447]
程序部署了之后，pc端和安卓手机可以正常使用，但是苹果手机无法打开页面，使用抓包工具看了，接口和js，css文件都加载了

**Comment by Chanzhaoyu** [comment]
我自己用正常，需要具体问题。

**Comment by kkkkxl** [comment]
+1 我也是iPhone手机打不开页面   PC没问题
