### ISSUE TITLE
除了railway，能在阿里云或者其他品牌云服务器一键部署吗

### ISSUE THREAD

**Issue by Jehuty-ML** [Chanzhaoyu/chatgpt-web#1448]
railway在国内经常登录很慢，有其他地方可以使用吗

**Comment by Chanzhaoyu** [comment]
能，只要能用 docker ，不过有风险

**Comment by shuaiplus** [comment]
> 能，只要能用 docker ，不过有风险
可以加一个一键vercel部署吗？求求了

**Comment by shuaiplus** [comment]
可以加一个一键vercel部署吗？求求了

**Comment by MoYiC** [comment]
国内容易被墙，香港服务器方便一点

**Comment by oliver-yu** [comment]
各位老小子，国内VPS 分分秒秒给你墙掉，能找个国外VPS能挂上去能用，你已经中了大奖了！

**Comment by git-syl** [comment]
服务器不在ChatGpt支持的国家列表里面就会被封。
建议优先选择海外服务器。

**Comment by Jehuty-ML** [comment]
> 服务器不在ChatGpt支持的国家列表里面就会被封。 建议优先选择海外服务器。

我用国内服务器再调用境外云函数或者反向代理服务器可以吗

**Comment by MoYiC** [comment]
> > 服务器不在ChatGpt支持的国家列表里面就会被封。 建议优先选择海外服务器。
> 
> 我用国内服务器再调用境外云函数或者反向代理服务器可以吗

可以前端在国内后端在国外

**Comment by qsc19971022** [comment]
> 

可以 但是云函数代理返回结果不支持stream，新的问题就出现了

**Comment by qsc19971022** [comment]
> > > 
> > 
> > 
> > 可以 但是云函数代理返回结果不支持stream，新的问题就出现了
> 
> 你用的谁家的云函数？亚马逊和cloudflare都支持的。 建议一个API，一个IP地址。
> 
> 云函数ip不固定容易被封

腾讯云就可以 可以选地区的

**Comment by assassinliujie** [comment]
docker-compose还不够一键吗（

**Comment by ebrece** [comment]
> 

这个要如何实现呢？

**Comment by Harrison170** [comment]
> docker-compose还不够一键吗（

老哥，我没用过docker，本项目怎么使用docker部署到服务器上，服务器环境ubuntu，且已安装好docker，本都运行成功，但是服务器运行失效，不知道为什么，服务器启动docker后，如何访问本项目，我尝试使用ip：3002访问不到。

**Comment by Harrison170** [comment]
> > docker-compose还不够一键吗（
> 
> 老哥，我没用过docker，本项目怎么使用docker部署到服务器上，服务器环境ubuntu，且已安装好docker，本都运行成功，但是服务器运行失效，不知道为什么，服务器启动docker后，如何访问本项目，我尝试使用ip：3002访问不到。

问题已解决，服务器的安全组策略没开。。。
