### ISSUE TITLE
前端希望增加语音阅读功能

### ISSUE THREAD

**Issue by feiyu201** [Chanzhaoyu/chatgpt-web#1451]
因为今天朋友正好询问我,这个如果用来练习口语不错,比如我输入中文 他回复英文 小朋友也可以跟着读 希望一句结束后有个小喇叭点下就自动阅读 在点就停止

**Comment by Mpynl** [comment]
可以使用微软的Speech API实现，我做的是在Message\index.vue下增加了一个函数，然后在模板里加了一个button用于实现调用这个函数的功能，下面是效果：
![image](https://user-images.githubusercontent.com/42730048/232181215-6df2e489-86ec-436a-8e94-3a4fb3796493.png)

**Comment by feiyu201** [comment]
@Mpynl  有参考代码嘛?
