### ISSUE TITLE
可以添加ShareGPT的导出方式吗？

### ISSUE THREAD

**Issue by shuaiplus** [Chanzhaoyu/chatgpt-web#1456]
感觉比导出图片好用一百倍。哪位大佬研究一下
![image](https://user-images.githubusercontent.com/100134295/232184384-bc38457c-c19c-46f1-a39c-7cf95ca1d262.png)

**Comment by xiaosaaaa** [comment]
你导json格式的

**Comment by shuaiplus** [comment]
> 你导json格式的

这哪里可以选json，不是只有图片吗
![image](https://user-images.githubusercontent.com/100134295/232216215-5e099767-a8bb-455d-9210-c6df556c498d.png)

**Comment by xiaosaaaa** [comment]
设置-聊天记录-导出

**Comment by shuaiplus** [comment]
> 设置-聊天记录-导出

那我把导出来的json放在哪里阅读？

**Comment by swuecho** [comment]
@shuaiplus 计划在我的fork上搞了, schema 搞好了, 有人愿意做前端可以配合,  前端我搞起来慢.

准备现在 chat 上 加 comment 功能. (自己)

然后在share chat

再然后在share chat html 上加 comment (自己或者别人)

如果sharegpt 给api 就好了, 不用自己搞一套了.

**Comment by shuaiplus** [comment]
> 

大佬牛逼，还真做出来了。我是只会拿来用的小白，希望有人能配合你做前端，坐等大佬完成。

**Comment by swuecho** [comment]
@shuaiplus  搞定.  https://github.com/swuecho/chat/pull/131 貌似port 过来也不难, 谁有空可以搞一下.
