### ISSUE TITLE
还是api好用，用TOKEN真的太垃圾了

### ISSUE THREAD

**Issue by zdbpython** [Chanzhaoyu/chatgpt-web#1458]
api答案秒出，token半天出不来，还经常出错

**Comment by feikoooo** [comment]
不会部署能帮操作一下吧付费！

**Comment by shuaiplus** [comment]
> 
我可以帮你

**Comment by MoYiC** [comment]
> 不会部署能帮操作一下吧付费！

咸鱼贵宇网络工作室

**Comment by feikoooo** [comment]
流水
***@***.***

337536686&nbsp; 方便添加一下QQ
你这个部署一下多少钱，要提供什么东西呀。

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chanzhaoyu/chatgpt-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月15日(星期六) 晚上11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chanzhaoyu/chatgpt-web] 还是api好用，用TOKEN真的太垃圾了 (Issue #1458)





  
不会部署能帮操作一下吧付费！
  
咸鱼贵宇网络工作室

**Comment by Devloper1024** [comment]
找我部署绝对最低价，电报：openDuckGPT

**Comment by bigSmartisan** [comment]
> 流水
> ***@***.***
> 
> 337536686&nbsp; 方便添加一下QQ
> 你这个部署一下多少钱，要提供什么东西呀。
> 
> &nbsp;
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "Chanzhaoyu/chatgpt-web"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2023年4月15日(星期六) 晚上11:16
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [Chanzhaoyu/chatgpt-web] 还是api好用，用TOKEN真的太垃圾了 (Issue #1458)
> 
> 
> 
> 
> 
>   
> 不会部署能帮操作一下吧付费！
>   
> 咸鱼贵宇网络工作室
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

找我部署一条龙服务
