### ISSUE TITLE
pnpm dev 测试环境网页可以访问，build 完了后访问网页被拒绝

### ISSUE THREAD

**Issue by sxybikelover** [Chanzhaoyu/chatgpt-web#1459]
也有没有大佬解释下

**Comment by MoYiC** [comment]
打开调试的网络看看报错，可能是目录层级问题

**Comment by sxybikelover** [comment]
type 为document的 (failed)net::ERR_CONNECTION_REFUSED
服务器端口开放了，也build，也后台运行了
很奇怪


> 打开调试的网络看看报错，可能是目录层级问题
