### ISSUE TITLE
用的api,返回的CSS代码直接渲染出来了

### ISSUE THREAD

**Issue by wander555** [Chanzhaoyu/chatgpt-web#146]
![QQ截图20230227144011](https://user-images.githubusercontent.com/6134211/221492481-0cefffac-1a49-4797-b5dc-aec97529243f.png)

**Comment by Chanzhaoyu** [comment]
感谢反馈，更新 `markdown` 渲染导致的问题

**Comment by wangrui19970405** [comment]
噗～～～ 哈哈哈哈哈哈哈啊哈哈 作者太可爱了 哈哈哈 每一个bug都那么可爱

**Comment by Chanzhaoyu** [comment]
emmm...已修复这个问题
