### ISSUE TITLE
咨询使用TOKEN 和API 的区别

### ISSUE THREAD

**Issue by lipeilin375** [Chanzhaoyu/chatgpt-web#1461]
我想请问一下开发者，使用API和使用TOKEN 的区别是什么，以及他们的扣费规则有什么不同？相比于TOKEN ，API 生成速度和精准度是否会更胜一筹？感谢解答！

**Comment by huangwb8** [comment]
@lipeilin375  Token模拟人登陆的过程，因此需要一些反代绕过Cloudflare验证。由于目前gpt3.5对注册用户是免费的，所以token暂时是免费的。一些比较好的反代使用token稳定性也挺好。

API则是一种“官方”的第三方调用方式。API一般是最稳的；但它是要收费的。

表现上，有人说token比较智能；API有一定程度阉割。但这些都不是官方意见，我也不知道是不是。我自己也觉得token版的chatGPT要智能一些。

更多情况你可以看我的博文： https://blognas.hwb0307.com/linux/docker/4201 。

希望有所帮助 (ฅ´ω`ฅ)

**Comment by lipeilin375** [comment]
> @lipeilin375 Token模拟人登陆的过程，因此需要一些反代绕过Cloudflare验证。由于目前gpt3.5对注册用户是免费的，所以token暂时是免费的。一些比较好的反代使用token稳定性也挺好。
> 
> API则是一种“官方”的第三方调用方式。API一般是最稳的；但它是要收费的。
> 
> 表现上，有人说token比较智能；API有一定程度阉割。但这些都不是官方意见，我也不知道是不是。我自己也觉得token版的chatGPT要智能一些。
> 
> 更多情况你可以看我的博文： https://blognas.hwb0307.com/linux/docker/4201 。
> 
> 希望有所帮助 (ฅ´ω`ฅ)

首先，感谢您的回答
目前个人正在使用TOKEN，所以有些不明白，但听完您的回答，我大致了解相关问题
其次，有关智能与否的问题个人也无法完全衡量，CHATGPT作为一个人工智能模型，在此仍旧认为提高工作效率为最先，个人而言，智能与否，影响并非特别大
最后，感谢您的尽心回答
