### ISSUE TITLE
聊天记录会被覆盖，而不是合并

### ISSUE THREAD

**Issue by RexWzh** [Chanzhaoyu/chatgpt-web#1463]
聊天记录的导出和导入只是读取和覆盖浏览器的缓存文件，这里导入能不能改成合并，或者提供这个选项。

实现上，可以把 json 文件完全相同的对话去掉再合并，或者按 chatid合并。楼主有考虑增加这个功能吗？

**Comment by Simon-leomon** [comment]
同问，可以合并不同设备的数据是个好想法。
