### ISSUE TITLE
请求添加特性：设置获取人物头像的超时时间

### ISSUE THREAD

**Issue by ImAmelie** [Chanzhaoyu/chatgpt-web#1464]
我直连我的服务器，头像是 [gravatar](gravatar.com) 的，所以获取不到，但是服务器连接失败返回 `fallbak-src` 时等待的时间 **太** 长了。

因为我不会前端，所以查了几个小时也没有头绪，NAVATAR 这个 vue 标签如何能添加超时时间呢？（[naive-ui](https://www.naiveui.com/zh-CN/os-theme) 没有关于 NAVATAR 的介绍，但是我确实在源代码里看到了）

如果能添加这个设置超时时间的特性，体验应该会更好。

如果特性申请不通过，请务必告诉我设置头像超时时间的方法，thx

PS. 为什么用这个 [gravatar](gravatar.com) ？因为我觉得它是最棒的头像设置网站。

**Comment by cvpv** [comment]
单独写一个axios实例，单独设置超时时间即可。
