### ISSUE TITLE
大家现在使用accessToKen还能用吗？

### ISSUE THREAD

**Issue by Hesdgwr579457** [Chanzhaoyu/chatgpt-web#1466]
undefined
[[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later]

**Comment by James-handsome** [comment]
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

**Comment by zynkchen** [comment]
果然不行了。。。

**Comment by zynkchen** [comment]
换个反代

**Comment by phoniwell** [comment]
Switch to another reverse proxy works for me

**Comment by beyonday-niuja** [comment]
> Switch to another reverse proxy works for me

which one please

**Comment by phoniwell** [comment]
https://github.com/Chanzhaoyu/chatgpt-web#docker-%E5%8F%82%E6%95%B0%E7%A4%BA%E4%BE%8B

Do clear browser's cookies after you switch to the new reverse proxy.

**Comment by ieiian** [comment]
一觉醒来发现accessToKen用不了了，还能抢救一下吗？

**Comment by Hesdgwr579457** [comment]
现在好像又出来一大串了  undefined
[ChatGPT error 522: <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>

<title>bypass.churchless.tech | 522: Connection timed out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />

</head>
<body>
<div id="cf-wrapper">

<div id="cf-error-details" class="p-0">
    <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
        <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
          
          <span class="inline-block">Connection timed out</span>
          <span class="code-label">Error code 522</span>
        </h1>
        <div>
           Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
        </div>
        <div class="mt-3">2023-04-16 04:22:26 UTC</div>
    </header>
    
    <div class="my-8 bg-gradient-gray">
        <div class="w-240 lg:w-full mx-auto">
            <div class="clearfix md:px-8">
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
<div class="relative mb-10 md:m-0">

<span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
<span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
</div>
<span class="md:block w-full truncate">You</span>
<h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

Browser
</h3>
<span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
<div class="relative mb-10 md:m-0">
<a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">
<span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
<span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
</a>
</div>
<span class="md:block w-full truncate">Toronto</span>
<h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
<a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">
Cloudflare
</a>
</h3>
<span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
<div class="relative mb-10 md:m-0">

<span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
<span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
</div>
<span class="md:block w-full truncate">bypass.churchless.tech</span>
<h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

Host
</h3>
<span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

            </div>
          
        </div>
    </div>

    <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
        <div class="clearfix">
            <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
            </div>
          
            <div class="w-1/2 md:w-full float-left leading-relaxed">
                <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                      <h3 class="text-15 font-semibold mb-2">If you're a visitor of this website:</h3>
  <p class="mb-6">Please try again in a few minutes.</p>

  <h3 class="text-15 font-semibold mb-2">If you're the owner of this website:</h3>
  <p><span>Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources.</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522">Additional troubleshooting information here.</a></p>
            </div>
        </div>
          
    </div>

    <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
<p class="text-13">
<span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">7b89a4eae9dda24c</strong></span>
<span class="cf-footer-separator sm:hidden">•</span>
<span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
Your IP:
<button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
<span class="hidden" id="cf-footer-ip">172.245.154.202</span>
<span class="cf-footer-separator sm:hidden">•</span>
</span>
<span class="cf-footer-item sm:block sm:mb-1"><span>Performance & security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech" id="brand_link" target="_blank">Cloudflare</a></span>

</p>
<script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>

</div>
</div>
</body>
</html>

]

**Comment by Hesdgwr579457** [comment]
> https://github.com/Chanzhaoyu/chatgpt-web#docker-%E5%8F%82%E6%95%B0%E7%A4%BA%E4%BE%8B
> 
> Do clear browser's cookies after you switch to the new reverse proxy.
The [apenai] server is still displayed denying access

**Comment by wwlmm** [comment]
是不行了 两个都不行了

**Comment by itsevin** [comment]
[OpenAI] 错误的网关 |  Bad Gateway

**Comment by itsevin** [comment]
应该是默认反代炸了而已，换一个就好了，换成这个 https://api.pawan.krd/backend-api/conversation

**Comment by kwingart** [comment]
> 应该是默认反代炸了而已，换一个就好了，换成这个 https://api.pawan.krd/backend-api/conversation

大佬，在哪里换，指点下，谢谢

**Comment by itsevin** [comment]
> > 应该是默认反代炸了而已，换一个就好了，换成这个 https://api.pawan.krd/backend-api/conversation
> 
> 大佬，在哪里换，指点下，谢谢

修改这个配置项
API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation

**Comment by kwingart** [comment]
> > > 应该是默认反代炸了而已，换一个就好了，换成这个 https://api.pawan.krd/backend-api/conversation
> > 
> > 
> > 大佬，在哪里换，指点下，谢谢
> 
> 修改这个配置项 API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation

好的，看来这个也炸了 ChatGPT error 400: {"detail":"Too many requests in 1 hour. Try again later."}

**Comment by itsevin** [comment]
> > > > 应该是默认反代炸了而已，换一个就好了，换成这个 https://api.pawan.krd/backend-api/conversation
> > > 
> > > 
> > > 大佬，在哪里换，指点下，谢谢
> > 
> > 
> > 修改这个配置项 API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation
> 
> 好的，看来这个也炸了 ChatGPT error 400: {"detail":"Too many requests in 1 hour. Try again later."}

确实(((((((

**Comment by itsevin** [comment]
> 用国外的服务器，部署在国外，是不是就不用反代理了

不行吧

**Comment by tianwen-j** [comment]
> > > > > 应该是默认反代炸了而已，换一个就好了，换成这个 https://api.pawan.krd/backend-api/conversation
> > > > 
> > > > 
> > > > 大佬，在哪里换，指点下，谢谢
> > > 
> > > 
> > > 修改这个配置项 API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation
> > 
> > 
> > 好的，看来这个也炸了 ChatGPT error 400: {"detail":"Too many requests in 1 hour. Try again later."}
> 
> 确实(((((((

只能默默等待了，确实两个反代都用不了啦

**Comment by linweiyuan** [comment]
开源自建代理，今天还能用，可以临时用一下：https://github.com/Chanzhaoyu/chatgpt-web/issues/1465#issuecomment-1510339121

**Comment by linweiyuan** [comment]
@1205129045x 不可以，涉及到账号安全，这个需要自己搭建一个 API，然后指向自己的地址

**Comment by eightHundreds** [comment]
> 开源自建代理，今天还能用，可以临时用一下：[#1465 (comment)](https://github.com/Chanzhaoyu/chatgpt-web/issues/1465#issuecomment-1510339121)

railway不支持docker compose (⊙︿⊙)

**Comment by linweiyuan** [comment]
@eightHundreds 转一下就可以了，试下依次输入下面命令，注意替换 `accessToken`

```bash
docker network create chatgpt
docker run --name chatgpt-proxy-server --restart unless-stopped --network chatgpt -d linweiyuan/chatgpt-proxy-server
docker run --name go-chatgpt-api --restart unless-stopped --network chatgpt -e GIN_MODE=release -e CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515 -d linweiyuan/go-chatgpt-api
docker run --name app --restart unless-stopped --network chatgpt -p 3002:3002 -e OPENAI_ACCESS_TOKEN=accessToken -e API_REVERSE_PROXY=http:/go-chatgpt-api:8080/conversation -d chenzhaoyu94/chatgpt-web
```

**Comment by a97242689** [comment]
![image](https://user-images.githubusercontent.com/17347941/232320677-10ee8895-edb5-4c06-82b7-1d59d969be98.png)
 at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 502,
  statusText: 'Bad Gateway',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 502,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Bad Gateway',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: [Array],
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

是哦，用不了accessToken

> 现在好象又出来一大串了 undefined [ChatGPT error 522:
> 
> <标题>bypass.churchless.tech | 522: 连接超时</title>
> #
> ```
>       <span class="inline-block">Connection timed out</span>
>       <span class="code-label">Error code 522</span>
>     </h1>
>     <div>
>        Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
>     </div>
>     <div class="mt-3">2023-04-16 04:22:26 UTC</div>
> </header>
> 
> <div class="my-8 bg-gradient-gray">
>     <div class="w-240 lg:w-full mx-auto">
>         <div class="clearfix md:px-8">
> ```
> 
> 你
> ###
> 浏览器
> 
> Working
> [ ](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech)
> Toronto
> ### [ Cloudflare ](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech)
> Working
> bypass.churchless.tech
> ###
> Host
> 
> Error
> ```
>         </div>
>       
>     </div>
> </div>
> 
> <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
>     <div class="clearfix">
>         <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
>             <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
>             <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
>         </div>
>       
>         <div class="w-1/2 md:w-full float-left leading-relaxed">
>             <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
>                   <h3 class="text-15 font-semibold mb-2">If you're a visitor of this website:</h3>
> ```
> 
> Please try again in a few minutes.
> 
> ### If you're the owner of this website:
> Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522)
> 
> ```
> </div>
> 
> <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
> ```
> 
> Cloudflare Ray ID: **7b89a4eae9dda24c** • Your IP: Click to reveal 172.245.154.202 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=bypass.churchless.tech)
> 
> <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&" b&&(b.classList.remove("hidden"),c.addEventListener("点击",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip" ).classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
> ]

**Comment by a97242689** [comment]
![image](https://user-images.githubusercontent.com/17347941/232320677-10ee8895-edb5-4c06-82b7-1d59d969be98.png)
 at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 502,
  statusText: 'Bad Gateway',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 502,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Bad Gateway',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: [Array],
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

是哦，用不了accessToken

**Comment by eightHundreds** [comment]
有没有考虑过用把Poe接口包装成open ai的接口

**Comment by ikiwihome** [comment]
readme中的两个代理都用不了了，https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全

**Comment by yefeiyu** [comment]
有好的vps吗？我的搬瓦工openai禁止。
