### ISSUE TITLE
打字机特效-配置化

### ISSUE THREAD

**Issue by waynedream** [Chanzhaoyu/chatgpt-web#147]
看到新版本加了打字机的效果，可以通过配置化的方式决定是否开启吗，或者加个按钮，跳过这个动画

**Comment by Chanzhaoyu** [comment]
可能放在前端会合理点？

**Comment by ludashi2020** [comment]
nginx反代不会有打字机效果，求正确的反代配置

**Comment by Siri-Li** [comment]
# 设置反向代理参数以支持流式输出
proxy_buffering off;
chunked_transfer_encoding on;
tcp_nopush on;
tcp_nodelay on;
keepalive_timeout 65;

**Comment by hnuzhoulin** [comment]
类似打字机的效果出来了吗？
完整nginx配置能分享一下吗？目前试过在strean和http端都没有打字机的效果

**Comment by hnuzhoulin** [comment]
可以了，完整配置如下：

```
server {
    listen       443 ssl;
   ssl_certificate /ssl/XXXXX.pem;
   ssl_certificate_key /ssl/XXXXX.key;

   server_name  chat-web.XX.com;
   root         /usr/share/nginx/html;
   auth_basic "Please input password";
   auth_basic_user_file /etc/nginx/passwd/webchat;

   location / {
    access_log  /var/log/nginx/chat-web.XXX.com.log  main;
    error_log  /var/log/nginx/chat-web.XXX.com.log;
    #下面的4行没测试是否可以删除
    types {
        application/octet-stream octet-stream;
    }
    default_type octet-stream;
    proxy_buffering off;
chunked_transfer_encoding on;
tcp_nopush on;
tcp_nodelay on;
keepalive_timeout 65;
    proxy_pass_header Server;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_pass http://XXXXXX:3002;
    }
}

```

**Comment by hnuzhoulin** [comment]
但是感觉比较容易超时 timeout of 100000ms exceeded
不知道感觉对不对

**Comment by lion-goose** [comment]
我按这个配置，还需要登录和密码啊

**Comment by lion-goose** [comment]
> 可以了，完整配置如下：
> 
> ```
> server {
>     listen       443 ssl;
>    ssl_certificate /ssl/XXXXX.pem;
>    ssl_certificate_key /ssl/XXXXX.key;
> 
>    server_name  chat-web.XX.com;
>    root         /usr/share/nginx/html;
>    auth_basic "Please input password";
>    auth_basic_user_file /etc/nginx/passwd/webchat;
> 
>    location / {
>     access_log  /var/log/nginx/chat-web.XXX.com.log  main;
>     error_log  /var/log/nginx/chat-web.XXX.com.log;
>     #下面的4行没测试是否可以删除
>     types {
>         application/octet-stream octet-stream;
>     }
>     default_type octet-stream;
>     proxy_buffering off;
> chunked_transfer_encoding on;
> tcp_nopush on;
> tcp_nodelay on;
> keepalive_timeout 65;
>     proxy_pass_header Server;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Host $http_host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Scheme $scheme;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection 'upgrade';
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Forwarded-For $remote_addr;
>     proxy_pass http://XXXXXX:3002;
>     }
> }
> ```

我按这个配置，还需要登录和密码啊

**Comment by hnuzhoulin** [comment]
> > 可以了，完整配置如下：
> > ```
> > server {
> >     listen       443 ssl;
> >    ssl_certificate /ssl/XXXXX.pem;
> >    ssl_certificate_key /ssl/XXXXX.key;
> > 
> >    server_name  chat-web.XX.com;
> >    root         /usr/share/nginx/html;
> >    auth_basic "Please input password";
> >    auth_basic_user_file /etc/nginx/passwd/webchat;
> > 
> >    location / {
> >     access_log  /var/log/nginx/chat-web.XXX.com.log  main;
> >     error_log  /var/log/nginx/chat-web.XXX.com.log;
> >     #下面的4行没测试是否可以删除
> >     types {
> >         application/octet-stream octet-stream;
> >     }
> >     default_type octet-stream;
> >     proxy_buffering off;
> > chunked_transfer_encoding on;
> > tcp_nopush on;
> > tcp_nodelay on;
> > keepalive_timeout 65;
> >     proxy_pass_header Server;
> >     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     proxy_set_header Host $http_host;
> >     proxy_set_header X-Real-IP $remote_addr;
> >     proxy_set_header X-Scheme $scheme;
> >     proxy_set_header Upgrade $http_upgrade;
> >     proxy_set_header Connection 'upgrade';
> >     proxy_set_header X-Forwarded-Proto $scheme;
> >     proxy_set_header X-Forwarded-For $remote_addr;
> >     proxy_pass http://XXXXXX:3002;
> >     }
> > }
> > ```
> 
> 我按这个配置，还需要登录和密码啊

不好意思，密码是我有需要，你把李曼auth开头的两行去掉就行

**Comment by xingxin666** [comment]
> proxy_buffering off;
> chunked_transfer_encoding on;
> tcp_nopush on;
> tcp_nodelay on;

感谢，已实现打字机效果

**Comment by zyn514405** [comment]
我想反代到chat-web.XX.com/chatgpt 上，请问完整的配置文件怎么写，在location /chatgpt 会直接加载不出来

**Comment by tsy19900929** [comment]
最好是作者改一下代码，把资源都改成相对路径
