### ISSUE TITLE
数学公式或者数学题目复制粘贴，格式会出现错误，识别不了

### ISSUE THREAD

**Issue by zhouyuanh** [Chanzhaoyu/chatgpt-web#1470]
数学公式或者数学题目复制粘贴，格式会出现错误，识别不了

**Comment by huangwb8** [comment]
你说的是这种公式？

![image](https://user-images.githubusercontent.com/35643122/232265580-c57949b2-7d9c-4de4-a5a7-69e7b269e47a.png)

我在Typora里复制是正常的。如果要居中的话，需要改`$$公式$$`为：

```
$$
公式
$$
```

**Comment by Chanzhaoyu** [comment]
你可以切换成原文本，右边三个小点。

**Comment by zhouyuanh** [comment]
是从word复制进来，查找答案
