### ISSUE TITLE
求助，我填入OpenAI api key 了，但是接口会报这个错，是什么问题啊？

### ISSUE THREAD

**Issue by wpy-hd** [Chanzhaoyu/chatgpt-web#1471]
![image](https://user-images.githubusercontent.com/61164376/232274559-449461d7-7a47-43ba-9746-afad20b5b999.png)
You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys

**Comment by bigSmartisan** [comment]
你在哪里填的啊，如果是部署是在运行参数里设置的

**Comment by wpy-hd** [comment]
我在service下面的.env文件里面填入的sk开头的OpenAI的api key，然后打开网页之后就无法交谈，它每次都报的是这个错。看了下message里面返回的错就是这个。
文档里写API key和token是二选一的，我就只填了API key,没填token



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月16日(周日) 下午4:15
收件人: ***@***.***&gt;;
抄送: "peiyan ***@***.******@***.***&gt;;
主题: Re: [Chanzhaoyu/chatgpt-web] 求助，我填入OpenAI api key 了，但是接口会报这个错，是什么问题啊？ (Issue #1471)




 
你在哪里填的啊，如果是部署是在运行参数里设置的

**Comment by bigSmartisan** [comment]
> 我在service下面的.env文件里面填入的sk开头的OpenAI的api key，然后打开网页之后就无法交谈，它每次都报的是这个错。看了下message里面返回的错就是这个。
> 文档里写API key和token是二选一的，我就只填了API key,没填token
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2023年4月16日(周日) 下午4:15
> 收件人: ***@***.***&gt;;
> 抄送: "peiyan ***@***.******@***.***&gt;;
> 主题: Re: [Chanzhaoyu/chatgpt-web] 求助，我填入OpenAI api key 了，但是接口会报这个错，是什么问题啊？ (Issue #1471)
> 
> 
> 
> 
>  
> 你在哪里填的啊，如果是部署是在运行参数里设置的
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
你用什么方式部署的，docker还是railway，或者是本地运行

**Comment by wpy-hd** [comment]
本地运行，没有用docker和railway



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月16日(周日) 下午4:46
收件人: ***@***.***&gt;;
抄送: "peiyan ***@***.******@***.***&gt;;
主题: Re: [Chanzhaoyu/chatgpt-web] 求助，我填入OpenAI api key 了，但是接口会报这个错，是什么问题啊？ (Issue #1471)




  
我在service下面的.env文件里面填入的sk开头的OpenAI的api key，然后打开网页之后就无法交谈，它每次都报的是这个错。看了下message里面返回的错就是这个。
 文档里写API key和token是二选一的，我就只填了API key,没填token
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2023年4月16日(周日) 下午4:15
 收件人: @.&gt;;
 抄送: "peiyan @.@.&gt;;
 主题: Re: [Chanzhaoyu/chatgpt-web] 求助，我填入OpenAI api key 了，但是接口会报这个错，是什么问题啊？ (Issue #1471)
 
你在哪里填的啊，如果是部署是在运行参数里设置的
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
 你用什么方式部署的，docker还是railway，或者是本地运行

**Comment by bigSmartisan** [comment]
把目录截个图看看，还有.env，把密钥打个码

**Comment by wpy-hd** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] 求助，我填入OpenAI api key 了，但是接口会报这个错，是什么问题啊？ (Issue #1471)





 
把目录截个图看看，还有.env，把密钥打个码

**Comment by Emmpty** [comment]
我也与遇到了相同的问题 ，接口返回报错
`{
"error": {
"message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
"type": "invalid_request_error",
"param": null,
"code": null
}
}`

**Comment by wpy-hd** [comment]
是的，我也是这个问题。但现在还没有解决。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月19日(周三) 中午11:33
收件人: ***@***.***&gt;;
抄送: "peiyan ***@***.******@***.***&gt;;
主题: Re: [Chanzhaoyu/chatgpt-web] 求助，我填入OpenAI api key 了，但是接口会报这个错，是什么问题啊？ (Issue #1471)




 
我也与遇到了相同的问题 ，接口返回报错
 { "error": { "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.", "type": "invalid_request_error", "param": null, "code": null } }

**Comment by DecayHuman** [comment]
同返回此接口提示
