### ISSUE TITLE
chatgpt-plus训练数据截止时间

### ISSUE THREAD

**Issue by 2019clover** [Chanzhaoyu/chatgpt-web#1472]
为什么我开通的chatgptplus，问它数据截止时间还是跟普通版本的一样，是基于2021年的。我看很多公众号开放的，他们的数据截止时间是最新的。我是少开通了啥吗

**Comment by chenjuefei** [comment]
plus是能用4和流畅的3.5 数据截至是一样的

**Comment by 2019clover** [comment]
我看到其它公众号开放的chatgptplus 训练的数据截止时间是当天

**Comment by Chanzhaoyu** [comment]
> 我看到其它公众号开放的chatgptplus 训练的数据截止时间是当天

并不准确，你只要每次告诉它今天的日期，它就会回答数据截止日期是当天。
