### ISSUE TITLE
请求报错443，是啥问题？

### ISSUE THREAD

**Issue by Coooolrui** [Chanzhaoyu/chatgpt-web#1475]
FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 2a03:2880:f127:83:face:b00c:0:25de:443

**Comment by xbsheng** [comment]
同遇到这个问题，解决了吗？

**Comment by SJQSSS** [comment]
同 解决了吗求踢

**Comment by china78** [comment]
同，解决了吗
