### ISSUE TITLE
希望添加退出登录功能

### ISSUE THREAD

**Issue by ImAmelie** [Chanzhaoyu/chatgpt-web#1476]
希望添加前端退出登录（防止公共电脑其他人使用）的功能

我不是前端开发，不然我就搞了，然后提个pull request。

这个功能~可能~就是删除cookies，删除网页缓存，刷新页面

**Comment by oliver-yu** [comment]
API_REVERSE_PROXY: xxx
 # 访问权限密钥，可选
这里加个密码，你登录时就会提示让你输入密码

**Comment by ImAmelie** [comment]
> API_REVERSE_PROXY: xxx
> 
> # 访问权限密钥，可选
> 这里加个密码，你登录时就会提示让你输入密码

你说的是 `AUTH_SECRET_KEY` 吧？这个我设置了，输入密码后，关闭浏览器再打开浏览器，因为有 cookie 的原因，你还是能直接与 GPT 对话

我希望能有个退出按钮，点击后关闭网页再打开，就会让你重新输入密码

**Comment by appotry** [comment]
替代解决方法

删除Cookie就可以了，可以使用浏览器插件 Cookie Editor

或者F12，应用里面自己删除

或者使用隐私浏览模式，关闭浏览器就清除了

**Comment by shuaiplus** [comment]
看看这位大佬的：https://github.com/csu-czh/ChatGPT

**Comment by Kerwin1202** [comment]
试试这个 https://github.com/Kerwin1202/chatgpt-web.git

**Comment by baldLi** [comment]
把这段代码放在左下角的描述中就好了
<a href="javascript:if(localStorage.getItem('SECRET_TOKEN')){localStorage.removeItem('SECRET_TOKEN');location.reload();}" style="color: #009FCC;">注销</a>

![image](https://user-images.githubusercontent.com/72122310/236976184-80bebef5-21a3-4f08-9ecb-4a5e6d6bfe89.png)

**Comment by baldLi** [comment]
把这段代码放到描述中就好了
`<a href="javascript:if(localStorage.getItem('SECRET_TOKEN')){localStorage.removeItem('SECRET_TOKEN');location.reload();}" style="color: #009FCC;">注销</a>`

![image](https://user-images.githubusercontent.com/72122310/236976435-cb071710-4cb3-491d-a42c-54e752711d26.png)

**Comment by SuYxh** [comment]
可以联系 HUAT_JX
