### ISSUE TITLE
[OpenAI] 错误的网关 |  Bad Gateway

### ISSUE THREAD

**Issue by 233zq** [Chanzhaoyu/chatgpt-web#1477]
今天突然出现这个问题，内网外网都一样的提示。
![image](https://user-images.githubusercontent.com/113227651/232315707-3028b37f-6001-4b34-b540-06ef4b173d79.png)

**Comment by 233zq** [comment]
![image](https://user-images.githubusercontent.com/113227651/232315940-853b9ffe-2397-4a02-82b9-28950ae1fee7.png)

**Comment by gygy** [comment]
一样的错误 @Chanzhaoyu

**Comment by lizijiee** [comment]
ChatGPTError: ChatGPT error 502:

**Comment by MichaelCS00** [comment]
我这也是，用gpt原来的web正常

**Comment by lizijiee** [comment]
![image](https://user-images.githubusercontent.com/42395468/232320782-3241ea20-8446-4067-a8bb-8a0a2e564d82.png)

**Comment by a97242689** [comment]
![image](https://user-images.githubusercontent.com/17347941/232320677-10ee8895-edb5-4c06-82b7-1d59d969be98.png)
 at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 502,
  statusText: 'Bad Gateway',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 502,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Bad Gateway',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: [Array],
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

一样哦，用不了 accessToken

**Comment by qNwNp** [comment]
> 是反向代理的问题，请问我的acesstoken过期了，怎么获取新的

和一开始获取token的方式一样，登录chatgpt后访问https://chat.openai.com/api/auth/session
详见readme

**Comment by qNwNp** [comment]
> > > 是反向代理的问题，请问我的acesstoken过期了，怎么获取新的
> > 
> > 和一开始获取token的方式一样，登录chatgpt后访问https://chat.openai.com/api/auth/session 详见readme
> 
> 访问了之后，那里的expire写的还是今天，还是老的acesstoken

chatgpt能用吗？如果chatgpt能的话token就应该没问题

**Comment by qNwNp** [comment]
> > > > > 是反向代理的问题，请问我的acesstoken过期了，怎么获取新的
> > > > 
> > > > 
> > > > 和一开始获取token的方式一样，登录chatgpt后访问https://chat.openai.com/api/auth/session 详见readme
> > > 
> > > 
> > > 访问了之后，那里的expire写的还是今天，还是老的acesstoken
> > 
> > chatgpt能用吗？如果chatgpt能的话token就应该没问题
> 
> 官网的网页版是可以用的

那这足以说明token没问题了吧

**Comment by binsir1** [comment]
好像gpt的访问规则又升级了

**Comment by yefeiyu** [comment]
是因为使用accessToken的原因吗？需要更新吗？更新了管用吗？

**Comment by Nordul** [comment]
根据其他基于ChatGPT网页版项目的issues，网页版应该是没得玩了

**Comment by wumiann** [comment]
ChatGPTUnofficialProxyAPI 挂了

**Comment by tjsky** [comment]
反代失效了，openai增加了对浏览器的识别，
所以原来的反代接口绕过CF的措施失效了。
V1和V4都失效了。

**Comment by garywu520** [comment]
错误+1

**Comment by iamflowerdog** [comment]
access token 都不行了，ChatGPT更新规则了，安全升级了

**Comment by MapleNow** [comment]
这个问题还有解吗

**Comment by chijiao** [comment]
> 
自建代理如何搭建

**Comment by partitionlcj** [comment]
求教

**Comment by ikiwihome** [comment]
https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全

**Comment by 7noemo** [comment]
> https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全

天天给自己打广告，也不累

**Comment by ac-git-cmd** [comment]
换了key访问后可以了

**Comment by huangwb8** [comment]
> > https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全
> 
> 天天给自己打广告，也不累

大哥， 我才是那个文章的博主Bensz。 很感谢 @ikiwihome 的推荐， 但他并不是我本人 Σ( ° △ °|||)︴

**Comment by quartzeast** [comment]
> 求教

什么是反向代理？

**Comment by quartzeast** [comment]
> > > > https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全
> > > 
> > > 
> > > 天天给自己打广告，也不累
> > 
> > 
> > 大哥， 我才是那个文章的博主 Bensz。 很感谢 @ikiwihome 的推荐， 但他并不是我本人 Σ(° △ °|||)︴
> 
> 自建必须有 vps 吗，我本地的电脑行不行，运行的时候就有那个代理，电脑关闭就没了，这样行不

在 vps 上搭建了还是需要web吗？

**Comment by 233zq** [comment]
> > > https://blognas.hwb0307.com/linux/docker/4201 参考这篇文章，自建代理，成功了。速度比第三方代理快多了而且安全
> > 
> > 天天给自己打广告，也不累
> 
> 大哥， 我才是那个文章的博主Bensz。 很感谢 @ikiwihome 的推荐， 但他并不是我本人 Σ( ° △ °|||)︴ 

![IMG_20230419_095531.jpg](https://user-images.githubusercontent.com/113227651/232946531-856237e1-c09f-4bb7-8ab3-bf21122d525a.jpg)
用的是go-chatgpt-api，接入方式是accesss_token，失败了
