### ISSUE TITLE
限流那一块有bug

### ISSUE THREAD

**Issue by csu-czh** [Chanzhaoyu/chatgpt-web#1478]
```
const limiter = rateLimit({
  keyGenerator: (req, res) => {
    let ipAddress = req.ip;
    if (req.headers['x-forwarded-for']) {
      const forwardedIps = req.headers['x-forwarded-for'].split(',');
      if (forwardedIps.length > 0) {
        ipAddress = forwardedIps[0].trim();
      }
    }
    return ipAddress; // 使用 IP 地址作为键值，以便针对每个 IP 地址限制请求次数
  },
  windowMs: 60 * 60 * 1000, // Maximum number of accesses within an hour
  max: maxCount,
``` 
这才真正达到限流的效果。而本项目中没有keyGenerator。导致实际情况为整个api限制了请求次数，而不是对每个ip地址限制

**Comment by 5265liu** [comment]
> ```
> const limiter = rateLimit({
>   keyGenerator: (req, res) => {
>     let ipAddress = req.ip;
>     if (req.headers['x-forwarded-for']) {
>       const forwardedIps = req.headers['x-forwarded-for'].split(',');
>       if (forwardedIps.length > 0) {
>         ipAddress = forwardedIps[0].trim();
>       }
>     }
>     return ipAddress; // 使用 IP 地址作为键值，以便针对每个 IP 地址限制请求次数
>   },
>   windowMs: 60 * 60 * 1000, // Maximum number of accesses within an hour
>   max: maxCount,
> ```
> 
> 这才真正达到限流的效果。而本项目中没有keyGenerator。导致实际情况为整个api限制了请求次数，而不是对每个ip地址限制
确实，希望尽快修复啊
