### ISSUE TITLE
怎么才能开启SSE

### ISSUE THREAD

**Issue by sl514** [Chanzhaoyu/chatgpt-web#1479]
我看pull request里有，但是没搜到相关代码。而现在的模式其实对前端和网路并不太友好。冗余数据太多。请问怎么才能开启SSE呢？

**Comment by csu-czh** [comment]
我也发现了，流数据通常是：
h
he
hel
hello
hello！
我改了后端，我的项目里改成：
hello！
冗余数据直接从On2 到了On

**Comment by JasonYFY** [comment]
同求

**Comment by luoshiyongstudy** [comment]
> 我看pull request里有，但是没搜到相关代码。而现在的模式其实对前端和网路并不太友好。冗余数据太多。请问怎么才能开启SSE呢？

有解决方法了吗
