### ISSUE TITLE
acessToken过期了，怎么重新获取的

### ISSUE THREAD

**Issue by 1205129045x** [Chanzhaoyu/chatgpt-web#1480]
打开这个网址还是原来旧的`https://chat.openai.com/api/auth/session`

**Comment by Kalpeny** [comment]
> 

我打开这个网站，是两个括号{}

**Comment by Kalpeny** [comment]
> > > 
> > 
> > 
> > 我打开这个网站，是两个括号{}
> 
> 你等先登录你的账号

已经登录了

**Comment by hbelove** [comment]
为什么我不能用api key，  free trial credit是0

**Comment by kwingart** [comment]
我也碰到同样问题了，说accesstoken过期，
 ChatGPTError: ChatGPT error 401: {"errorMessage":"Access token has expired."}
但是我登录https://platform.openai.com进去后，用https://chat.openai.com/api/auth/session获取到的还是原来那个token，怎么更新我自己的token呢？有高手知道么？
用微软的浏览器，同样得操作，得到{}，没有其他。
