### ISSUE TITLE
想结合todolist二次开发 已有原型图 工作忙 进度比较慢 有没有感兴趣的能组队开发

### ISSUE THREAD

**Issue by KILL4M** [Chanzhaoyu/chatgpt-web#1482]
vx: Skylar-21
![image](https://user-images.githubusercontent.com/51038773/232324393-7c0908a9-92b0-4d64-b7cb-bbbc81d1f819.png)

**Comment by cvpv** [comment]
描述一下需求看看

**Comment by KILL4M** [comment]
自然语言描述任务的增删改查 智能预估任务完成时间 预估用户高效的时间段 智能有针对性地推荐用户去完成对工作有帮助的任务 定期提醒用户复盘
专注面板 倒计时
可视化图表展示数据&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 上午10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] 想结合todolist二次开发 已有原型图 工作忙 进度比较慢 有没有感兴趣的能组队开发 (Issue #1482)





 
描述一下需求看看
