### ISSUE TITLE
怎么去掉默认的反向代理呢

### ISSUE THREAD

**Issue by e5sub** [Chanzhaoyu/chatgpt-web#1484]
我的小鸡套了warp,本身就可以访问openai的,不需要这鸡肋的反向代理
怎么删除呢

**Comment by xiaoguaishou92** [comment]
本来也没有默认反向代理啊，那个是为了实现绕过CF的验证的。。

**Comment by e5sub** [comment]
> 本来也没有默认反向代理啊，那个是为了实现绕过CF的验证的。。

使用 accessToken 时，不管你是国内还是国外的机器，都会使用代理。默认代理为 [acheong08](https://github.com/acheong08) 大佬的

文档上不是写了吗

**Comment by emmmua** [comment]
warp是啥求大佬指教，想了解一下，他默认没有代理的，大陆访问不了

**Comment by e5sub** [comment]
> warp是啥求大佬指教，想了解一下，他默认没有代理的，大陆访问不了
accessToken默认就有代理,你用的应该是api的吧

**Comment by xiaoguaishou92** [comment]
> > 本来也没有默认反向代理啊，那个是为了实现绕过CF的验证的。。
> 
> 使用 accessToken 时，不管你是国内还是国外的机器，都会使用代理。默认代理为 [acheong08](https://github.com/acheong08) 大佬的
> 
> 文档上不是写了吗

这个是为了绕过CF验证的呀，你web这个程序没办法绕过CF人机验证
