### ISSUE TITLE
开源自建代理，今天还能用，可以临时用一下：https://github.com/Chanzhaoyu/chatgpt-web/issues/1465#issuecomment-1510339121

### ISSUE THREAD

**Issue by xiaoguaishou92** [Chanzhaoyu/chatgpt-web#1485]
开源自建代理，今天还能用，可以临时用一下：https://github.com/Chanzhaoyu/chatgpt-web/issues/1465#issuecomment-1510339121

_Originally posted by @linweiyuan in https://github.com/Chanzhaoyu/chatgpt-web/issues/1466#issuecomment-1510340761_
            自建需要plus账号吧，这里大部分应该都没有开

**Comment by linweiyuan** [comment]
可能别的自建需要，但是我这个反而不用 `plus` 账号，你去试一下就知道了，自己搭建一个，也不会看到你的 token，源代码也在 GitHub 上

**Comment by hbelove** [comment]
> 可能别的自建需要，但是我这个反而不用 `plus` 账号，你去试一下就知道了，自己搭建一个，也不会看到你的 token，源代码也在 GitHub 上

这个要部署在vps上吗

**Comment by linweiyuan** [comment]
@hbelove 如果你自己电脑用魔法能访问 ChatGPT，那么部署在本地也可以

**Comment by xiaoguaishou92** [comment]
> 可能别的自建需要，但是我这个反而不用 `plus` 账号，你去试一下就知道了，自己搭建一个，也不会看到你的 token，源代码也在 GitHub 上

之前搭建过，不带plus用不了。。

**Comment by linweiyuan** [comment]
@xiaoguaishou92 你确定是用我这个来搭哦？

因为我自己就由于某些原因还没开 plus，然后能用，反而 plus 还没正式添加适配

**Comment by ludashi2020** [comment]
> https://github.com/Chanzhaoyu/chatgpt-web/issues/1465#issuecomment-1510339121

docker封装源码了吧？

**Comment by linweiyuan** [comment]
> > [#1465 (comment)](https://github.com/Chanzhaoyu/chatgpt-web/issues/1465#issuecomment-1510339121)
> 
> docker封装源码了吧？

不明白你意思

**Comment by wwlmm** [comment]
> > > [#1465 (comment)](https://github.com/Chanzhaoyu/chatgpt-web/issues/1465#issuecomment-1510339121)
> > 
> > 
> > docker封装源码了吧？
> 
> 不明白你意思

我如果只使用 java-chatgpt-api 这个在docker中布置 不知是否可行，我测试过，刚启动容器的时候是能够成功反代access token的，然后过一段时间，就会是失效出现504，重启重启后又能使用。如此反复。不知道是什么原因。

**Comment by linweiyuan** [comment]
@wwlmm 这个不能多人共用，如果自己用也这样，可能死锁：https://github.com/linweiyuan/go-chatgpt-api/issues/20#issuecomment-1510640670

**Comment by wwlmm** [comment]
> @wwlmm 这个不能多人共用，如果自己用也这样，可能死锁：[linweiyuan/go-chatgpt-api#20 (comment)](https://github.com/linweiyuan/go-chatgpt-api/issues/20#issuecomment-1510640670)

就我一个人用，完全没有别人在用。过段时间就会死锁，很奇怪，从昨晚到现在 出现 过很多次了。看了一下日志，发现一只会出现 no access的对话。

**Comment by xuhuaq** [comment]
> 可能别的自建需要，但是我这个反而不用 `plus` 账号，你去试一下就知道了，自己搭建一个，也不会看到你的 token，源代码也在 GitHub 上

感谢，亲测可用，plus账号，gpt-4可用

#docker network create chatgpt
#docker run --name chatgpt-proxy-server --restart unless-stopped --network chatgpt -d linweiyuan/chatgpt-proxy-server
#docker run --name go-chatgpt-api --restart unless-stopped --network chatgpt -e GIN_MODE=release -e CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515 -d linweiyuan/go-chatgpt-api
#docker run --name app --restart unless-stopped --network chatgpt -p 3002:3002 -e OPENAI_ACCESS_TOKEN=accessToken -e API_REVERSE_PROXY=http://go-chatgpt-api:8080/conversation -d chenzhaoyu94/chatgpt-web #默认是3.5，加参数 -e OPENAI_API_MODEL=gpt-4 成功启用

**Comment by hbelove** [comment]
> docker-compose三个容器顺序依赖没搞好，只有很小概率能成功。我给改了下，成功率大幅增加了。用docker-compose up -d，不要用restart，restart不受依赖顺序控制。重启用这个： docker-compose stop && docker-compose up -d && docker-compose logs -f | grep -v warp 看到welcome chatgpt就成功了，看日志不要着急，一般一分钟左右就好了。
> 
> ```dockerfile
> version: '2.2'
> 
> services:
>   go-chatgpt-api:
>     container_name: go-chatgpt-api
>     image: linweiyuan/go-chatgpt-api
>     networks:
>       - chatgpt
>     ports:
>       - 8080:8080 # 宿主机8080端口可按需改为其它端口
>     environment:
>       - GIN_MODE=release
>       - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
>       - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
>     depends_on:
>       chatgpt-proxy-server:
>         condition: service_healthy
>       chatgpt-proxy-server-warp:
>         condition: service_healthy
>     restart: always
>  
>   chatgpt-proxy-server:
>     container_name: chatgpt-proxy-server
>     image: linweiyuan/chatgpt-proxy-server
>     networks:
>       - chatgpt
>     depends_on:
>       chatgpt-proxy-server-warp:
>         condition: service_healthy
>     healthcheck:    
>         test: ["CMD-SHELL", "sleep 30"]
>         interval: 35s
>         timeout: 35s
>         retries: 3
>     restart: always
>  
>   chatgpt-proxy-server-warp:
>     container_name: chatgpt-proxy-server-warp
>     image: linweiyuan/chatgpt-proxy-server-warp
>     networks:
>       - chatgpt
>     healthcheck:
>         test: ["CMD-SHELL", "sleep 30"]
>         interval: 35s
>         timeout: 35s
>         retries: 3
>     restart: always
> 
> networks:
>     chatgpt:
>         driver: bridge
> ```

部署在本地可以吗，使用魔法

**Comment by zengge99** [comment]
> > docker-compose三个容器顺序依赖没搞好，只有很小概率能成功。我给改了下，成功率大幅增加了。用docker-compose up -d，不要用restart，restart不受依赖顺序控制。重启用这个： docker-compose stop && docker-compose up -d && docker-compose logs -f | grep -v warp 看到welcome chatgpt就成功了，看日志不要着急，一般一分钟左右就好了。
> > ```dockerfile
> > version: '2.2'
> > 
> > services:
> >   go-chatgpt-api:
> >     container_name: go-chatgpt-api
> >     image: linweiyuan/go-chatgpt-api
> >     networks:
> >       - chatgpt
> >     ports:
> >       - 8080:8080 # 宿主机8080端口可按需改为其它端口
> >     environment:
> >       - GIN_MODE=release
> >       - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
> >       - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
> >     depends_on:
> >       chatgpt-proxy-server:
> >         condition: service_healthy
> >       chatgpt-proxy-server-warp:
> >         condition: service_healthy
> >     restart: always
> >  
> >   chatgpt-proxy-server:
> >     container_name: chatgpt-proxy-server
> >     image: linweiyuan/chatgpt-proxy-server
> >     networks:
> >       - chatgpt
> >     depends_on:
> >       chatgpt-proxy-server-warp:
> >         condition: service_healthy
> >     healthcheck:    
> >         test: ["CMD-SHELL", "sleep 30"]
> >         interval: 35s
> >         timeout: 35s
> >         retries: 3
> >     restart: always
> >  
> >   chatgpt-proxy-server-warp:
> >     container_name: chatgpt-proxy-server-warp
> >     image: linweiyuan/chatgpt-proxy-server-warp
> >     networks:
> >       - chatgpt
> >     healthcheck:
> >         test: ["CMD-SHELL", "sleep 30"]
> >         interval: 35s
> >         timeout: 35s
> >         retries: 3
> >     restart: always
> > 
> > networks:
> >     chatgpt:
> >         driver: bridge
> > ```
> 
> 部署在本地可以吗，使用魔法

应该不行吧，我是甲骨文上用warp连的。本地的话，配置肯定要修改。
