### ISSUE TITLE
求助，一直在三个点加载页面

### ISSUE THREAD

**Issue by FEone-c** [Chanzhaoyu/chatgpt-web#1487]
前端和后端都运行起来了的，用的本地运行，截图如下
![image](https://user-images.githubusercontent.com/46013040/232364733-c9ae4fd1-5f3f-432f-93f8-b0037ec86f0e.png)

**Comment by huangwb8** [comment]
@FEone-c 

会用docker可以试试我的方案： https://blognas.hwb0307.com/linux/docker/4201

**Comment by FEone-c** [comment]
> @FEone-c
> 
> 会用docker可以试试我的方案：https://blognas.hwb0307.com/linux/docker/4201

非常感谢，后面会考虑用docker搭建，但是现在我还是挺想知道我这问题是出在哪 : )

**Comment by charlieye-dev** [comment]
我也遇到了

**Comment by imyangjiong** [comment]
同样遇到了

**Comment by ttwang0** [comment]
浏览器版本问题，更新一下，或者换个浏览器
