### ISSUE TITLE
ChatGPT error 404: { "error": { "message": "The model: gpt-4-0314 does not exist", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }

### ISSUE THREAD

**Issue by xinmans** [Chanzhaoyu/chatgpt-web#1488]
environment:
      OPENAI_API_KEY: sk-xxx
      OPENAI_API_MODEL: gpt-4-0314

Why?

**Comment by csu-czh** [comment]
The model: gpt-4-0314 does not exist！
没开通gpt4

**Comment by zhangairen** [comment]
我也遇到同样的问题，开了plus但是今天突然用不了

**Comment by xqm2023** [comment]
开plus会员和api接口的gpt-4没有任何关系，api接口的gpt-4要单独申请才行，要等很久。

**Comment by xinmans** [comment]
> 开plus会员和api接口的gpt-4没有任何关系，api接口的gpt-4要单独申请才行，要等很久。

gpt-4 api如何申请？
