### ISSUE TITLE
怎么清空缓存

### ISSUE THREAD

**Issue by LayneChai** [Chanzhaoyu/chatgpt-web#1489]
当用户使用授权码进入网站之后，怎么清空缓冲，让用户重新输入授权码进入网页

**Comment by huangwb8** [comment]
@LayneChai  

一种更加合理的方法是允许用户注册和修改密码，并在需要的时候退出帐户。具体可见： https://blognas.hwb0307.com/linux/docker/4201

**Comment by LayneChai** [comment]
> @LayneChai
> 
> 一种更加合理的方法是允许用户注册和修改密码，并在需要的时候退出帐户。具体可见： https://blognas.hwb0307.com/linux/docker/4201

使用登录的方式不能让用户每次使用持续从指定的网站获取密码，和需求暂时不匹配

**Comment by Chanzhaoyu** [comment]
只要你后端修改了密码，前端下次进行请求如果不正确的话会自动清理掉本地的 token，这时候就会让重新验证。
