### ISSUE TITLE
使用域名和HTTPS，在PC端使用正常，移动端报错

### ISSUE THREAD

**Issue by leeggco** [Chanzhaoyu/chatgpt-web#149]
Network error 是什么情况？？
![image](https://user-images.githubusercontent.com/1283227/221515230-e5688403-6052-4348-a5ba-1c9c074f2072.png)

**Comment by Chanzhaoyu** [comment]
我...无从下手...也不知道该怎么回答你...

**Comment by leeggco** [comment]
解决了，原来是API地址问题。
