### ISSUE TITLE
有大佬遇上model: gpt-4 Not Found 问题吗

### ISSUE THREAD

**Issue by zhangairen** [Chanzhaoyu/chatgpt-web#1493]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/34363408/232405469-a3c52ee0-7713-42c7-b4ec-838f7775753d.png">

**Comment by rocket2023** [comment]
换access_token应该可以

**Comment by zhangairen** [comment]
> 你是否有 gpt-4 api 的权限

开了Plus，有权限的，前阵子是没问题的，昨天不行了
