### ISSUE TITLE
刚弄了一个方案，自建永久免费openai代理，不依赖别人的代理了，完美

### ISSUE THREAD

**Issue by 1019822077** [Chanzhaoyu/chatgpt-web#1495]
我之前用这个nodejs项目，用了大神的代理，结果昨天不能用了，然后各种找方案，最终完美解决，自己搭了一个自建永久免费openai代理，不依赖别人的代理了，完美

因为不能公开说，也是怕知道人多了，会受影响。想知道的，可以加我V信： xxzhkyly2021   (星星之火可以燎原的首字母哦，备注chatgpt)

**方案如下：**
1、首先我们得实现http代理请求，这样国内就可以请求这个代理服务器完成请求到openai,自建代理不花钱，但你得有一个域名
2、然后布署web和手机端app，添加上自己的代理和open key，就可以实现自建的chatgpt，网站web上访问可以添加密码，这样防止别人知道了你的入口进行访问。手机端只有苹果版的app，暂没有android，不过你有web了，什么时候都可以用了。

给个总结的费用吧，20元

**Comment by 1019822077** [comment]
不是为了挣钱，只是感觉这个方式挺好，想分享一下，就用20元拦住一批人

**Comment by fanghtml** [comment]
我把服务器布到国外，既不怕被封，也不需要域名，省事多了，还代理啥呀，不知道你想总结啥

**Comment by fanghtml** [comment]
我把服务部署到国外服务器，既不怕被封，也不需要域名，省事多了，还代理啥呀，不知道你想总结啥

**Comment by hncboy** [comment]
cloudflare 可以建免费的 openai 接口代理

**Comment by 1019822077** [comment]
是的，只是把步骤记录了一下

**Comment by zengwk2005** [comment]
你这应该不能用accessTOKEN方案吧

**Comment by rocket2023** [comment]
太多人共用ip，会gg的，我搞个美国云主机，自建一个代理socks总共花了35元，代理了十多个账号，刚刚好

**Comment by Chanzhaoyu** [comment]
api 的代理网上大把

**Comment by rockagen** [comment]
辣眼睛，现在什么牛马都能混进来了，群魔乱舞，门槛真低。

**Comment by SealinRepo** [comment]
好家伙 噶韭菜都这么容易了么
