### ISSUE TITLE
Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable

### ISSUE THREAD

**Issue by Jacksonmeking** [Chanzhaoyu/chatgpt-web#1497]
![image](https://user-images.githubusercontent.com/96971753/232513385-5ef874f8-35d2-49a4-a2fd-bcc684c54b0e.png)
看到之前有人问过这个问题，兄弟给回答的是自己生成.env 我这边试过了，但start之后提示这个，还得麻烦帮忙解答一下。

**Comment by iOSQiao** [comment]
是要在service文件夹下创建.env，不是用根目录那个。
