### ISSUE TITLE
v2.8.0测试使用accessToken，不能流输出数据

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#150]
所有结果都是一次性输出，如果数据大的情况下会等很久。没有反代，直接本地运行。测试版本v2.8.0 模式：accessToken。使用openai api key可以一打字一边输出，但是格式化有问题,部分不能分行。用户体验不如accessToken

**Comment by Chanzhaoyu** [comment]
emmm...最好有图片，是否用了 `nginx`

**Comment by ludashi2020** [comment]
是已经找到问题，API代理和cdn的问题。
