### ISSUE TITLE
提供免费代理

### ISSUE THREAD

**Issue by gcslaoli** [Chanzhaoyu/chatgpt-web#1500]
花了两天升级好了 chat接口代理 账号我提供 你只管用
https://xyhelper.cn

**Comment by xuhuaq** [comment]
cn域名，安装软件，卖会员账号 ……广告打到issue了，说清楚一点比较好

**Comment by gcslaoli** [comment]
> cn域名，安装软件，卖会员账号 ……广告打到issue了，说清楚一点比较好

我免费池收一分钱了吗 客户端和网页版我是不是全开源了 非得把代理源码也开源才成吗 爱用不用

**Comment by ludashi2020** [comment]
代理源码呢

**Comment by gcslaoli** [comment]
> 代理源码呢

代理源码不开源，puid方案人尽皆知，然后就GG了。。

**Comment by gcslaoli** [comment]
> issue什么时候变成打广告的地方了？

只是默认代理失效了，希望这个项目能够继续开发token模式，如果没有人用token模式了，担心作者会不再兼容

**Comment by gcslaoli** [comment]
> 是把项目的反向代理替换成你给的网址就行了吗

https://freechat.xyhelper.cn/backend-api/conversation

反代是这个地址，关注下网站 地址可能会有变动 但会在网站通知

**Comment by gcslaoli** [comment]
> > > 是把项目的反向代理替换成你给的网址就行了吗
> > 
> > 
> > https://freechat.xyhelper.cn/backend-api/conversation
> > 反代是这个地址，关注下网站 地址可能会有变动 但会在网站通知
> 
> ![image](https://user-images.githubusercontent.com/50540240/232710079-556d0aee-c89f-455c-af68-8beed0a62fd7.png)
> 
> 为啥还是回答不出信息
有报错么 加群说吧 这里不适合用来聊天

**Comment by xuxiang19961203** [comment]
> 



> > > > 是把项目的反向代理替换成你给的网址就行了吗
> > > 
> > > 
> > > https://freechat.xyhelper.cn/backend-api/conversation
> > > 反代是这个地址，关注下网站 地址可能会有变动 但会在网站通知
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/50540240/232710079-556d0aee-c89f-455c-af68-8beed0a62fd7.png)
> > 为啥还是回答不出信息
> > 有报错么 加群说吧 这里不适合用来聊天

你好,请问怎么加群, 我进官网看, 也没有加的啊?  那个代理好像不能用呢

**Comment by winteroo** [comment]
广告位吗这是，那来试试这个  http://yl.iisai.cn
