### ISSUE TITLE
Add RTL support in the website setting

### ISSUE THREAD

**Issue by ahmadi3d** [Chanzhaoyu/chatgpt-web#1501]
The website does not support right-to-left (RTL) languages. For instance, if you ask chat GPT a question that contains RTL text, it will not display correctly. To resolve this issue, I suggest adding a direction: rtl to the _p_ tag on the page. It would be convenient if there was an option in the settings to apply this automatically. Thank you.

**Comment by poorbash** [comment]
Agree.
