### ISSUE TITLE
请问是否支持 https://gpt.pawan.krd/api/completions？

### ISSUE THREAD

**Issue by Jesn** [Chanzhaoyu/chatgpt-web#1503]
`https://api.pawan.krd/backend-api/conversation` 这个接口失效了，
请问是否支持`https://gpt.pawan.krd/api/completions`

https://gist.github.com/PawanOsman/72dddd0a12e5829da664a43fc9b9cf9a

![image](https://user-images.githubusercontent.com/5728274/232648099-944d7405-e8cf-4e7b-a929-f20ed758eb7a.png)

**Comment by xuhuaq** [comment]
需要自建web api server，请参考回答最多的那个issue

**Comment by xuxiang19961203** [comment]
> 



> 需要自建web api server，请参考回答最多的那个issue

这个需要境外服务器吗? 内地服务器是否可行??
