### ISSUE TITLE
test

### ISSUE THREAD

**Issue by liyanan666** [Chanzhaoyu/chatgpt-web#1505]
test

**Comment by shuaiplus** [comment]
Issues不是你发广告的地方！！！什么垃圾玩意别往这里发！！！
![image](https://user-images.githubusercontent.com/100134295/232666879-cad3728a-3f25-4f94-ad23-b9f7b908a33f.png)
![image](https://user-images.githubusercontent.com/100134295/232666911-9db79c0c-538e-4fb2-91dc-d263886fdec9.png)

**Comment by xuxiang19961203** [comment]
我还去试了一下, 结果发现只能用几次. 真的垃圾

> Issues不是你发广告的地方！！！什么垃圾玩意别往这里发！！！ ![image](https://user-images.githubusercontent.com/100134295/232666879-cad3728a-3f25-4f94-ad23-b9f7b908a33f.png) ![image](https://user-images.githubusercontent.com/100134295/232666911-9db79c0c-538e-4fb2-91dc-d263886fdec9.png)

**Comment by xxxily** [comment]
> Issues不是你发广告的地方！！！什么垃圾玩意别往这里发！！！ ![image](https://user-images.githubusercontent.com/100134295/232666879-cad3728a-3f25-4f94-ad23-b9f7b908a33f.png) ![image](https://user-images.githubusercontent.com/100134295/232666911-9db79c0c-538e-4fb2-91dc-d263886fdec9.png)

看不惯这打广告的，我也要打一个：
免费好用的ChatGPT网站列表（前提你得有梯子）

https://hello-ai.anzz.top/home/FreeChatGPTSiteList.html

**Comment by xuxiang19961203** [comment]
> 



> > Issues不是你发广告的地方！！！什么垃圾玩意别往这里发！！！ ![image](https://user-images.githubusercontent.com/100134295/232666879-cad3728a-3f25-4f94-ad23-b9f7b908a33f.png) ![image](https://user-images.githubusercontent.com/100134295/232666911-9db79c0c-538e-4fb2-91dc-d263886fdec9.png)
> 
> 看不惯这打广告的，我也要打一个： 免费好用的ChatGPT网站列表（前提你得有梯子）
> 
> https://hello-ai.anzz.top/home/FreeChatGPTSiteList.html

老哥, 我进去看了下, 这里面好多都打不开啊, 能打开的, 也有好多都是收费的 T.T

**Comment by xxxily** [comment]
> 

自备梯子啊，好用的都被举报，被墙了，国内能正常访问的基本都是垃圾

**Comment by xiaosaaaa** [comment]
@Chanzhaoyu

**Comment by necopp** [comment]
服了，这里是讨论技术bug交流的地方，zh就是有你这种人才搞得互联网乌烟瘴气

**Comment by chainblock-leji** [comment]
跑这里打广告来了哦，不怕被攻击吗

**Comment by liyanan666** [comment]
怕 请大佬手下留情 关闭issues即可




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月19日(星期三) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] 不想折腾注册和部署的可以看看国内chatgpt平替网站https://www.weijiwangluo.com/talk (Issue #1505)





 
跑这里打广告来了哦，不怕被攻击吗

**Comment by assassinliujie** [comment]
来这发广告你也是个人才

**Comment by assassinliujie** [comment]
有一说一，3.5usd的aws lightsail就够用了，再便宜的rn有封号风险-------- 原始邮件 --------发件人： jiangxiaohuai520 ***@***.***>日期： 2023年4月20日周四 下午3:00收件人： Chanzhaoyu/chatgpt-web ***@***.***>抄送： assassinliujie ***@***.***>, Comment ***@***.***>主    题： Re: [Chanzhaoyu/chatgpt-web] 不想折腾注册和部署的可以看看国内chatgpt平替网站https://www.weijiwangluo.com/talk (Issue #1505)
我用70块的vps搭不香？非要你这玩意，你是觉得能上github都是小白对吧
