### ISSUE TITLE
怎么设置自启啊,每次关闭终端网页进不去了

### ISSUE THREAD

**Issue by hiroot199** [Chanzhaoyu/chatgpt-web#1506]
我都是手动启动./start.sh

对了问下不支持GPT4吗

**Comment by huangwb8** [comment]
@hiroot199  建议使用docker搭建，省力省心 (ฅ´ω`ฅ)

**Comment by hiroot199** [comment]
> @hiroot199 建议使用docker搭建，省力省心 (ฅ´ω`ฅ)

但是在DOCKER怎么改文件呀

**Comment by huangwb8** [comment]
@hiroot199  我的博客有搭建过该项目的衍生项目，基本原理和思路是一样的。 你可以看一下，希望有所帮助： https://blognas.hwb0307.com/linux/docker/4201

**Comment by xiaosaaaa** [comment]
新建一个例如test.sh，给执行权限，然后内容写
nohup /你的路径/start.sh &

**Comment by hiroot199** [comment]
> 新建一个例如test.sh，给执行权限，然后内容写 nohup /你的路径/start.sh &

可以了,谢谢
