### ISSUE TITLE
建议添加显示每次对话消耗token数和消费金额

### ISSUE THREAD

**Issue by shuaiplus** [Chanzhaoyu/chatgpt-web#1508]
![image](https://user-images.githubusercontent.com/100134295/232697006-5db6aa86-90a4-46d8-a34b-42c6b2ac231f.png)

**Comment by shuaiplus** [comment]
还有统计
![image](https://user-images.githubusercontent.com/100134295/232697357-c9375013-b22b-46eb-a82b-489dfb155458.png)
隔壁那个项目这一点做的确实不错，值得学习

**Comment by nmydt** [comment]
为什么添加呢，个人感觉没啥用，看到又怎么样呢

**Comment by JZLeung** [comment]
隔壁哪个项目，看看。

> 还有统计 ![image](https://user-images.githubusercontent.com/100134295/232697357-c9375013-b22b-46eb-a82b-489dfb155458.png) 隔壁那个项目这一点做的确实不错，值得学习

**Comment by assassinliujie** [comment]
理论上这个功能OPENAI 的后台里就有了

**Comment by shuaiplus** [comment]
但这个是实时的，他在回答的过程中会一步一步计算token数和费用

**Comment by xiaoguaishou92** [comment]
个人使用不需要这个功能，除非是卖出去。。
