### ISSUE TITLE
为什么这个ai可以知道今天日期

### ISSUE THREAD

**Issue by xinggonglie** [Chanzhaoyu/chatgpt-web#151]
你好，我用过两三个模型，小程序也用了三四个，为什么这个ai知道今天的日期，是专门优化这个问题还是说用了别的数据？

**Comment by Chanzhaoyu** [comment]
其实没优化过，因为我有时候问时间、天气它也不回答我。

但我需要回复，让你知道我已经看到了这个 `issues`...

**Comment by xinggonglie** [comment]
我这两天，专门测试了下，你的这个ai，昨天，今天都回答出日期了，然后问今天发生了什么新闻，它就开始胡说了，其他的ai，根本不知道今天的日期

**Comment by JarvanDing** [comment]
日期大部分时间是对的。。。但是星期几都是靠猜，每次问都不一样。

**Comment by erhaa233** [comment]
![QQ截图20230228193941](https://user-images.githubusercontent.com/46651798/221843288-7db8c5de-ab7d-4630-8f40-4c8c4bf457ee.jpg)
chatgpt包里的index.js 290行，每次api请求中的prefix参数里都会携带当前时间，如果要校准星期几，也可以在里面写入，但是会消耗token

**Comment by xinggonglie** [comment]
我以为是连到哪个比较特别模型了，可以知道实时时间



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月28日(周二) 晚上7:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Chanzhaoyu/chatgpt-web] 为什么这个ai可以知道今天日期 (Issue #151)




 

 chatgpt包里的index.js 290行，每次api请求中的prefix参数里都会携带当前时间，如果要校准星期几，也可以在里面写入，但是会消耗token
