### ISSUE TITLE
是否会支持多个accessToken呢？

### ISSUE THREAD

**Issue by yayaQAQ** [Chanzhaoyu/chatgpt-web#1510]
我们有一批plus的账号，然后想要共享给其他人用，但是目前只能写入一个accessToken，这样很快就会达到限制，所以想要一个新的会话就使用一个新的accessToken。

**Comment by yayaQAQ** [comment]
> 

你这个本地可以部署吗？这个内部分享给其他用。

**Comment by yayaQAQ** [comment]
> > 我们有一批plus的账号，然后想要共享给其他人用，但是目前只能写入一个accessToken，这样很快就会达到限制，所以想要一个新的会话就使用一个新的accessToken。
> 
> 你说的是这种模式吧？https://chat-shared.zhile.io/shared.html

你这个本地可以部署吗？我要弄一个类似的给内部的人用。

**Comment by pengzhile** [comment]
> > > 我们有一批plus的账号，然后想要共享给其他人用，但是目前只能写入一个accessToken，这样很快就会达到限制，所以想要一个新的会话就使用一个新的accessToken。
> > 
> > 
> > 你说的是这种模式吧？https://chat-shared.zhile.io/shared.html
> 
> 你这个本地可以部署吗？我要弄一个类似的给内部的人用。

我这就是个部署样本啊。

**Comment by xiaoguaishou92** [comment]
你这样。部署到多台机器上，然后在nginx按照ip做负载均衡策略就行了

**Comment by yayaQAQ** [comment]
> > > > 我们有一批plus的账号，然后想要共享给其他人用，但是目前只能写入一个accessToken，这样很快就会达到限制，所以想要一个新的会话就使用一个新的accessToken。
> > > 
> > > 
> > > 你说的是这种模式吧？https://chat-shared.zhile.io/shared.html
> > 
> > 
> > 你这个本地可以部署吗？我要弄一个类似的给内部的人用。
> 
> 我这就是个部署样本啊。



> 你这样。部署到多台机器上，然后在nginx按照ip做负载均衡策略就行了

我试试看
