### ISSUE TITLE
在微信端打开之后，速度非常慢，第一次打开要1分钟

### ISSUE THREAD

**Issue by AlexWeiCD** [Chanzhaoyu/chatgpt-web#1511]
如何解决这个问题

**Comment by necopp** [comment]
之后就不需要了

**Comment by xiaosaaaa** [comment]
你要是直连海外服务器，慢是应该的。

**Comment by jkhcc11** [comment]
加Cdn吧，有个js很大1-2MB，裸奔的话，服务器很慢

**Comment by blindperson** [comment]
@jkhcc11 请问CDN怎么加，naiveUI跟highlight.js这俩比较大，我想用CDN，但是不会用，可以请教一下吗

**Comment by jkhcc11** [comment]
> @jkhcc11 请问CDN怎么加，naiveUI跟highlight.js这俩比较大，我想用CDN，但是不会用，可以请教一下吗

使用打包的方式我也不会，我对vue这块不熟悉，我是搞后端的。我用的笨方法，直接修改打包后的js文件。o(╥﹏╥)o
如果你找到好用的方法，麻烦告诉我下，3Q
