### ISSUE TITLE
docker启动，走自己的代理url，需要改代码的那几个地方，多谢老板帮组

### ISSUE THREAD

**Issue by happysirTZC** [Chanzhaoyu/chatgpt-web#1512]

**Comment by huangwb8** [comment]
没听懂你的问题。。。

**Comment by happysirTZC** [comment]
> 没听懂你的问题。。。
我是部署在阿里云服务器上，另外部署了一个代理url（proxy.happy.com）指向api.openai.com，那么我需要把代码里面deploy.yaml和index.ts两个文件里的字符串”api.openai.com“ 替换成 ”proxy.happy.com“ 吗？我这样改了后，试了本地mac电脑用docker启服务是ok的，但是阿里云服务器上服务起来了，回答问题调openai.com不行，网络是通的，curl测试代理也是好用的。这种是啥问题呢

**Comment by huangwb8** [comment]
@happysirTZC  我是用docker部署的。 不太清楚你所用部署方式的细节。 不好意思喽 (ฅ´ω`ฅ)

**Comment by happysirTZC** [comment]
> @happysirTZC 我是用docker部署的。 不太清楚你所用部署方式的细节。 不好意思喽 (ฅ´ω`ฅ)

多谢，你用代理吗？对docker启动时添加代理的那些参数不太明白，我现在部署好了代理，

**Comment by huangwb8** [comment]
> > @happysirTZC 我是用docker部署的。 不太清楚你所用部署方式的细节。 不好意思喽 (ฅ´ω`ฅ)
> 
> 多谢，你用代理吗？对docker启动时添加代理的那些参数不太明白，我现在部署好了代理，

我写过一个衍生项目的教程，感兴趣可以看看： https://blognas.hwb0307.com/linux/docker/4201

**Comment by assassinliujie** [comment]
我觉得改hosts就行了
