### ISSUE TITLE
对chatglm模型api支持

### ISSUE THREAD

**Issue by abigkeep** [Chanzhaoyu/chatgpt-web#1513]
希望增加对开源项目chatglm[https://github.com/THUDM/ChatGLM-6B](url)的api的支持

**Comment by onetwo12cn** [comment]
希望增加对开源项目chatglm[https://github.com/THUDM/ChatGLM-6B](https://github.com/Chanzhaoyu/chatgpt-web/issues/url)的api的支持

**Comment by cnlinjie** [comment]
希望增加对开源项目chatglm[https://github.com/THUDM/ChatGLM-6B](https://github.com/Chanzhaoyu/chatgpt-web/issues/url)的api的支持
