### ISSUE TITLE
acheong08的Reverse Proxy URL貌似有问题

### ISSUE THREAD

**Issue by 4860575** [Chanzhaoyu/chatgpt-web#1519]
使用浏览器打开“https://bypass.churchless.tech/api/conversation”
提示Origin is unreachable Error code 523
https://api.pawan.krd/backend-api/conversation则正常

**Comment by huangwb8** [comment]
@4860575  第一个公共代理挂了。  现在为了稳定性、速度和安全性，大家比较倾向于自建代理。

**Comment by Stonewalling** [comment]
> @4860575 第一个公共代理挂了。 现在为了稳定性、速度和安全性，大家比较倾向于自建代理。
怎么自建啊

**Comment by huangwb8** [comment]
> > @4860575 第一个公共代理挂了。 现在为了稳定性、速度和安全性，大家比较倾向于自建代理。
> > 怎么自建啊

请看我的博客文章： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by justincnn** [comment]
> > > @4860575 第一个公共代理挂了。 现在为了稳定性、速度和安全性，大家比较倾向于自建代理。
> > > 怎么自建啊
> 
> 请看我的博客文章： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

有推荐vps么？我的vps ip全部阵亡，自建代理也没用

**Comment by huangwb8** [comment]
@justincnn 

我现在用的是RackNerd VPS。 具体情况见： https://blognas.hwb0307.com/ad

**Comment by gcslaoli** [comment]
> 使用浏览器打开“[https://bypass.churchless.tech/api/conversation”](https://bypass.churchless.tech/api/conversation%E2%80%9D) 提示Origin is unreachable Error code 523 [https://api.pawan.krd/backend-api/conversation则正常](https://api.pawan.krd/backend-api/conversation%E5%88%99%E6%AD%A3%E5%B8%B8)

试试我的 https://freechat.xyhelper.cn/backend-api/conversation
