### ISSUE TITLE
请问通过API Key方式使用，每小时能处理多少次请求？

### ISSUE THREAD

**Issue by namrisgan** [Chanzhaoyu/chatgpt-web#1520]
我是部署在独立IP地址的VPS上的，使用自己账号的API Key方式，才问了没多少问题就显示“Too many request from this IP in 1 hour”，是正常的么？

**Comment by xiaosaaaa** [comment]
没见过这提示，你搭建再公网上设置密码了吗？是不是被别人扫描到了，被太多人使用了。

**Comment by swuecho** [comment]
赶紧下线

你正常使用是不会超的

**Comment by namrisgan** [comment]
> 没见过这提示，你搭建再公网上设置密码了吗？是不是被别人扫描到了，被太多人使用了。

谢谢。我设置密码了的。从服务器的日志上看并没有被别人使用；从openai的网站上查我的daily usage也是正常的。应该是我服务器的设置导致的，我再找找原因

**Comment by lalagu27** [comment]
套warp了吗？

**Comment by namrisgan** [comment]
> 套warp了吗？

没有啊，我只是用服务器上已经有的apache设置了一个反向代理。我又试了试，问它6~7个问题就会说该ip1小时内的请求过多

**Comment by namrisgan** [comment]
刚才又进行了测试，我取消了服务器上的本地反向代理，直接打开服务器的3002端口进行使用，还是只问了6个问题就提示该ip每小时的请求次数过多。挠头……

**Comment by xiaosaaaa** [comment]
api泄露了吧，生成个新的试试

**Comment by namrisgan** [comment]
> api泄露了吧，生成个新的试试，原来那个记得删了

我刚更换了新的api key，并且删除了旧key。依然是问6个问题就会提示请求过多；但我只要重新启动docker，就又可以继续使用了……说明问题并没有出在我的api key上。大家使用docker部署本项目的都没有遇到这种情况吗？

**Comment by csu-czh** [comment]
关掉限流就行啊，在后端看看这部分代码吧

**Comment by chainblock-leji** [comment]
我用docker部署的，服务器放在美国和日本，然后通过香港服务器反向代理的，目前没有遇到这个问题。

**Comment by namrisgan** [comment]
> 关掉限流就行啊，在后端看看这部分代码吧

哎呀，我又仔细理了一遍配置文件，原来是MAX_REQUEST_PER_HOUR这个参数控制的……它紧跟着设置访问密码，我以为是控制每小时内可以尝试输入密码的次数。所以闹乌龙了，谢谢各位回复
