### ISSUE TITLE
免费提供部署帮助，仅限个人版

### ISSUE THREAD

**Issue by vastxie** [Chanzhaoyu/chatgpt-web#1524]
有个朋友居然花了2000，购入一个基于本项目简单修改的”网页“，域名给他整的xyz的域名，API 另算。最牛的是一年使用期限，到期再续费。我。。。 。。。

这么好割的吗

**Comment by vastxie** [comment]
[体验站](https://chat.vast123.com/)

需要的话可以免费提供部署帮助，注意，API，服务器，域名（需要的话）等并不免费哦

**Comment by lwlha** [comment]
说说看

**Comment by vastxie** [comment]
> 说说看

![image](https://user-images.githubusercontent.com/24899308/233032671-053f616d-9612-4704-8e53-bb6c9f24662c.png)
![image](https://user-images.githubusercontent.com/24899308/233032866-4e47697e-9385-4758-85f6-734d7f288af7.png)
吃瓜么🍉

**Comment by nxtreaming** [comment]
你很聪明，请继续你的表演。

**Comment by vastxie** [comment]
> 你很聪明，请继续你的表演。

谢谢你的夸奖！我会继续为你提供有趣的信息和回答你的问题。如果你有任何问题或者想要讨论某个主题，请随时告诉我。我会竭尽所能帮助你！

**Comment by assassinliujie** [comment]
docker都已经一键部署了还要咋教啊，从买服务器开始教么

**Comment by Wallace00V** [comment]
> [体验站](https://chat.vast123.com/)
> 
> 需要的话可以免费提供部署帮助，注意，API，服务器，域名（需要的话）等并不免费哦

请问,我用api方式部署,直接用docker的话运行报错, 部署命令为:docker run --name chatgpt-web -d -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key chatgpt-web

**Comment by liangjiacun** [comment]
求帮忙部署  我一直部署不上去
