### ISSUE TITLE
一键部署在Railway，第二天账号被封禁了，大家有遇到过吗

### ISSUE THREAD

**Issue by tsuixl** [Chanzhaoyu/chatgpt-web#1526]
End of the line

You have been flagged for violations concerning the Railway [ToS]and your account has been banned with the reason: Mirrors/Userbots.

If you believe this is an error, [feel free to fill out your form and we'll get you sorted.]
Regards, 
Your friends at Railway

**Comment by goachenjie** [comment]
Do you know what the reason is? Have you solved it

**Comment by yz0812** [comment]
Have you solved it? I have the same problem.

**Comment by dw-liedji** [comment]
hello! Please, how did you solve this issue? I have the same problem and don't have multiple accounts. This problem has shut down all my applications are not working. It is a very bad experience for me.
