### ISSUE TITLE
用的API方式，我本地一直提示超时

### ISSUE THREAD

**Issue by 123Jason-cn** [Chanzhaoyu/chatgpt-web#1527]
VPN是打开的。这个项目必须要放到线上去么？

**Comment by 123Jason-cn** [comment]
我看我的VPN，直接速率都是0。是不是接口没走我的VPN啊？要怎么设置才可以呢？大哥，求告知

**Comment by huangwb8** [comment]
@123Jason-cn 

请问，你绑了openai的payment methods了吗？

**Comment by assassinliujie** [comment]
> 我看我的VPN，直接速率都是0。是不是接口没走我的VPN啊？要怎么设置才可以呢？大哥，求告知

![image](https://user-images.githubusercontent.com/68693675/233059948-f5c2c7d8-3d0e-444a-a7af-fe92991f8596.png)
代理地址看你用什么vpn客户端，如果clash的话就写http://127.0.0.1:7890

**Comment by 123Jason-cn** [comment]
> @123Jason-cn
> 
> 请问，你绑了openai的payment methods了吗？

不太懂。这个key是别人给我的。我就负责接入

**Comment by 123Jason-cn** [comment]
> > 我看我的VPN，直接速率都是0。是不是接口没走我的VPN啊？要怎么设置才可以呢？大哥，求告知
> 
> ![image](https://user-images.githubusercontent.com/68693675/233059948-f5c2c7d8-3d0e-444a-a7af-fe92991f8596.png) 代理地址看你用什么vpn客户端，如果clash的话就写http://127.0.0.1:7890

可以了。谢谢大哥

**Comment by 2562771185** [comment]
我填了HTTPS_PROXY=http://127.0.0.1:7890还是超时啊，还需要改什么地方吗我用的是clash
