### ISSUE TITLE
我用的docker compose部署的，配置文件也有填写apikey,未经授权，是什么鬼，怎么填写都不行

### ISSUE THREAD

**Issue by robinhsu121** [Chanzhaoyu/chatgpt-web#1528]
![image](https://user-images.githubusercontent.com/18637416/233038985-0231fd04-a09a-478e-a5d3-ad7aee34e850.png)

**Comment by trader-tsang** [comment]
你是不是应该仔细看看文档

**Comment by assassinliujie** [comment]
![image](https://user-images.githubusercontent.com/68693675/233052888-fc1dcd55-104d-472b-a66a-d7226aef326d.png)
ji建议先看文档，你给你自己网站设了访问权限那当然就要输入访问密钥

**Comment by CYTand** [comment]
你如果没修改yaml其他配置的话，说明你的密钥字段保留了”AUTH_SECRET_KEY: xxx”这个默认值，那么在这个框里输入“xxx”就可以通过检验了。你也可以改掉这个值或者注释掉这个字段，再重启容器。
