### ISSUE TITLE
使用 nginx 需要自行配置 octet-stream 相关内容

### ISSUE THREAD

**Issue by zzb16888** [Chanzhaoyu/chatgpt-web#153]
各位大佬这里的octet-stream 相关内容 如何配置？我使用的宝塔

**Comment by simzhangbest** [comment]
+1

**Comment by ludashi2020** [comment]
+1

**Comment by shnulaa** [comment]
location /
        {
                 resolver 8.8.8.8;
                proxy_ssl_server_name on;
                keepalive_timeout 5s;
                chunked_transfer_encoding on;
                proxy_buffering off;
                proxy_cache off;
                proxy_cache_bypass $http_pragma;
                proxy_cache_revalidate on;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host:$server_port;
                proxy_pass http://localhost:3002; #通过域名访问frp服务
        }

 proxy_buffering off;  -> 这个要设置为off
