### ISSUE TITLE
自建代理，突然提示failed, reason: connect ECONNREFUSED

### ISSUE THREAD

**Issue by gygy** [Chanzhaoyu/chatgpt-web#1533]

**Comment by huangwb8** [comment]
@gygy  我使用的是该项目：[linweiyuan / go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) ，可以成功自建反向代理 。 如果有x86的国外VPS可以试试。

**Comment by gygy** [comment]
> @gygy  我使用的是该项目：[linweiyuan / go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) ，可以成功自建反向代理 。 如果有x86的国外VPS可以试试。

我也是用这个。不过，经常有问题。

**Comment by xiaoguaishou92** [comment]
> 

弄个定时重启就好了，我理解是有什么卡柱了

**Comment by huangwb8** [comment]
> > > 
> > 
> > 
> > 弄个定时重启就好了，我理解是有什么卡柱了
> 
> 定时重启时怎么搞的

你用的是什么安装的呢？ Docker？

**Comment by huangwb8** [comment]
@1205129045x 

用linux还不简单。 使用Cron即可。 可见： [Linux基础 实用Linux命令一览表 - Bensz](https://blognas.hwb0307.com/linux/linux-basic/445) 的“crontab执行定期任务”小节。 你不是能用chatGPT，搜索一下，看能不能把握住。 加油！

**Comment by gygy** [comment]
docker 指向旁路由，直接翻墙，已经稳定一天多了。不再出现该问题了

**Comment by winteroo** [comment]
试试我的 http://yl.iisai.cn 稳定快速
