### ISSUE TITLE
请问一下如果我有4.0的API怎么接入呢

### ISSUE THREAD

**Issue by Move0124** [Chanzhaoyu/chatgpt-web#1534]
我尝试在linux系统里面的虚拟机找到网页，我现在拥有了GPT4.0的API接口，我需要修改什么文件来让我的chatGPT内核是4.0的呢，谢谢大佬！

**Comment by Move0124** [comment]
是不是在输入命令的时候可以选择模型呢？请问选择模型的命令是什么呢？？

**Comment by gmksbk** [comment]
环境变量OPENAI_API_MODEL: gpt-4

**Comment by Move0124** [comment]
docker run --name chatgpt-web --rm -it -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key --env OPENAI_API_MODEL=gpt-4 chatgpt-web
请问是不是这样就可以修改模型了呢

**Comment by huangwb8** [comment]
@Move0124  大佬， 我写过一个 [自建教程](https://blognas.hwb0307.com/linux/docker/4201) ， 但我还没试过是否可用gpt-4 API。 可否合作一下？ 测试完成后可以销毁api，应该没有安全问题。 感兴趣的话可联系我：  https://t.me/benszhub

**Comment by gmksbk** [comment]
> docker run --name chatgpt-web --rm -it -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key --env OPENAI_API_MODEL=gpt-4 chatgpt-web 请问是不是这样就可以修改模型了呢

可以，根据你的实际情况决定是临时修改还是永久修改，非土豪的话可以export临时使用4.0api，另外建议3002端口映射一下，百分百被扫描。。

**Comment by csu-czh** [comment]
你们知道怎么快速拿到4.0接口吗？我申请一个月了，还没消息

**Comment by Move0124** [comment]
> 

。。如果。。我有

**Comment by Move0124** [comment]
其实我也没有接口，只是想知道怎么操作使用4.0的模型

**Comment by bigdimple** [comment]
我设置了OPENAI_API_MODEL=gpt-4，但是问的时候还是说他是gpt3.5
