### ISSUE TITLE
这个没用用户控制呀

### ISSUE THREAD

**Issue by wengxiaoning** [Chanzhaoyu/chatgpt-web#1542]
如果有用户控制，那就登录后再进行操作是不是方便些呢。

**Comment by wengxiaoning** [comment]
是的，如果，加一个登录，注册就好了。注册登录一个自己的账号。

**Comment by huangwb8** [comment]
该项目有一个衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) ，具有类似的功能。 具体见我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201) 。 

实际上， ChanZhaoyu 已经在 #589 表示后端靠用户自己搞定，所以他可能不会投入太多精力开发这种依赖后端的功能。

**Comment by lonny1987** [comment]
> 
你的项目做的很好，但是你的教程真的是没太多详细 的过程 ，数据库那一块，基本没提供啥教程，怎么创建数据库存，哪个类似，要不要付费，我看了你博客10次，看不懂

**Comment by swuecho** [comment]
https://github.com/swuecho/chat 我这个也有用户控制

**Comment by turbobin** [comment]
实现了注册登录+VIP权限模式，使用github pages部署前端，不用购买域名 [https://github.com/turbobin/chatbot](https://github.com/turbobin/chatbot)
