### ISSUE TITLE
你的项目做的很好，但是你的教程真的是没太多详细 的过程 ，数据库那一块，基本没提供啥教程，怎么创建数据库存，哪个类似，要不要付费，我看了你博客10次，看不懂@wengxiaoning

### ISSUE THREAD

**Issue by lonny1987** [Chanzhaoyu/chatgpt-web#1543]
@wengxiaoning 

该项目有一个衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) ，具有类似的功能。 具体见我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201) 。 

实际上， ChanZhaoyu 已经在 #589 表示后端靠用户自己搞定，所以他可能不会投入太多精力开发这种依赖后端的功能。

_Originally posted by @huangwb8 in https://github.com/Chanzhaoyu/chatgpt-web/issues/1542#issuecomment-1516309182_

**Comment by huangwb8** [comment]
@lonny1987  

教程需要一些docker的基础才能看懂。 你最好找个VPS或者Linux虚拟机实战一下， 遇到问题再讨论。 只看不操作太抽象了，看不懂很正常 Σ( ° △ °|||)︴
