### ISSUE TITLE
Feature request: generate conversation title with `conversation/gen_title`

### ISSUE THREAD

**Issue by KevinWang15** [Chanzhaoyu/chatgpt-web#1544]
Currently the conversation title is the first sentence of the conversation. 

However, in the original ChatGPT front-end, a request will be sent to ` https://chat.openai.com/backend-api/conversation/gen_title/<conversation-id>`, and they will use AI to generate a more concise conversation title. 

Is it possible to support this feature here too?

## Sample request

```shell
curl 'https://chat.openai.com/backend-api/conversation/gen_title/b4ee5ede-...' \
  -H 'authority: chat.openai.com' \
  -H 'accept: */*' \
  -H 'accept-language: en' \
  -H 'authorization: Bearer ...' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'cookie: ...' \
  -H 'origin: https://chat.openai.com' \
  -H 'pragma: no-cache' \
  -H 'referer: https://chat.openai.com/?model=text-davinci-002-render-sha' \
  -H 'sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
  --data-raw '{"message_id":"4e7006bd-..."}' \
  --compressed
```

## Sample response

```json
{"title":"AI Ready to Assist"}
```

**Comment by huangwb8** [comment]
@KevinWang15

As I know, this is a nature feature when you use `Access Token` instead of `API`. 

Here is an alternative choice.  [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web), an [Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)-derived project powered by MongoDB, supports both `API` and `Access Token` well. 

If you use `Access Token`, you have to pay attention to reverse proxy bypassing Cloudflare validation. I have a detailed [Chinese tutorial](https://blognas.hwb0307.com/linux/docker/4201) about [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web). You can have a look if interested.

**Comment by KevinWang15** [comment]
Thanks for the information @huangwb8 

I am using `Access Token`, not `API`.

I think conversation title generation is not automatic, conversations created by `chatgpt-web` all have the title `New chat` in https://chat.openai.com/, and I didn't see `conversation/gen_title` called anywhere in the code.

So I think this is still an issue.

**Comment by huajianjiang** [comment]
@KevinWang15 Hi, I found that ChatGPT website indeed sending request https://chat.openai.com/backend-api/conversation/gen_title/{conv_id} to backend, and **I also want to know what the official's prompt for conv titile generation.**
I designed a prompt but not ideable, not as good as official's. Below is my prompt for generating conversation title:

> Please generate a short and concise chat topic based on the following chat content and language, words length should be around 3 to 10, don't try to reply chat content, if there is no specific topic, return the topic of "Casual chat". the generated topic text language must be the same as the chat's lauguage. for example："hello"，the topic should be "greeting" and "haha" is "Casual chat".

**Comment by KevinWang15** [comment]
I believe it's better to treat `conversation/gen_title` as a blackbox and not try to figure out how it is implemented under the hood. We just need to call the same API as the official frontend.
