### ISSUE TITLE
railway部署的，用国内外的域名进行解析，无法访问

### ISSUE THREAD

**Issue by 1378056564** [Chanzhaoyu/chatgpt-web#1545]
不知道是不是railway进行了国内ip屏蔽的策略。无法通过国内的访问，但是用它自己生成的域名+梯子却可以访问。包括用国外的域名+cname他自己生成的域名+梯子也可以访问
有一样用railway部署的小伙伴吗。有什么好的解决方法吗？

**Comment by HB4daemmon** [comment]
+1, 今天确实发现国内没法获取后端接口，前端的css和js能拿到，不知道是什么策略。尝试了下国内的cdn，貌似也不行，需要试试cf之类的cdn了。

**Comment by Czzzzzzzz** [comment]
+1，有什么好的办法吗？

**Comment by kangkang721** [comment]
+1，有什么好的办法吗？

**Comment by shuaiplus** [comment]
我认为暂时没有解决方法

**Comment by 1378056564** [comment]
> 我认为暂时没有解决方法

不，我已经解决了=。=用我的vps部署了一哈

**Comment by HB4daemmon** [comment]
使用cloudflare可以继续用railway挂着使用，不过需要在cloudflare上面买个域名

**Comment by cd547** [comment]
感觉是railway封大陆的ip，每次发请求会拦截。@HB4daemmon cloudflare如何挂？

**Comment by HB4daemmon** [comment]
@cd547 cf上面买域名开加速开ssl（严格）模式，然后railway里面增加custom domain,然后把railway里面的地址配在cf域名的dns下就行了

**Comment by cd547** [comment]
@HB4daemmon 非要在cf上买？

**Comment by HB4daemmon** [comment]
@cd547 不是必须的，我主要其他域名在国内备案了的，在别的issue上面看到备案的有查水表的风险就在cf新买了个

**Comment by cd547** [comment]
@HB4daemmon 多谢，好了，你也真行! 这都知道。我上午也是这么做的，就是不行，原来必须开ssl（严格）模式

**Comment by cd547** [comment]
这样感觉好像并不是railway封杀我们的ip，更像是我们墙了railway的，和Vercel类似都要用自定义域名访问。当然我是把后端的服务放railway，前端放腾讯云的

**Comment by 1378056564** [comment]
> 这样感觉好像并不是railway封杀我们的ip，更像是我们墙了railway的，和Vercel类似都要用自定义域名访问。当然我是把后端的服务放railway，前端放腾讯云的

如果是我们墙的话，应该railway的官网都访问不了吧0.0

**Comment by shuaiplus** [comment]
dns服务器改成cf就可以了

**Comment by xiao-ke-1** [comment]
我域名被墙，然后换个域名也没用

**Comment by HB4daemmon** [comment]
@xiao-ke-1 你可以用https://tcp.ping.pe 测下域名是不是真的被墙了，如果没被墙，用cf应该还是可以的

**Comment by shuaiplus** [comment]
> 

试试301重定向

**Comment by liu-peiyu** [comment]
> @cd547 cf上面买域名开加速开ssl（严格）模式，然后railway里面增加custom domain,然后把railway里面的地址配在cf域名的dns下就行了

我这边就是按这个方式做的，也不行

**Comment by stevenQinwen** [comment]
找人帮我解决注册和登陆+支付的问题，愿意付费，感兴趣+vx: wx5713a

**Comment by lidanyang8** [comment]
> 不知道是不是railway进行了国内ip屏蔽的策略。无法通过国内的访问，但是用它自己生成的域名+梯子却可以访问。包括用国外的域名+cname他自己生成的域名+梯子也可以访问 有一样用railway部署的小伙伴吗。有什么好的解决方法吗？

https://render.com/ 用docker方式部署，不需要挂梯即可访问

**Comment by zccguagua** [comment]
> @cd547 cf上面买域名开加速开ssl（严格）模式，然后railway里面增加custom domain,然后把railway里面的地址配在cf域名的dns下就行了

真的可以，现在可以访问了，railway域名那里有个连接也这样说了https://docs.railway.app/deploy/exposing-your-app#lets-encrypt-ssl-certificates

**Comment by wangrui1573** [comment]
> @cd547 cf上面买域名开加速开ssl（严格）模式，然后railway里面增加custom domain,然后把railway里面的地址配在cf域名的dns下就行了

真的可以，现在可以访问了

**Comment by CNenfan** [comment]
就离谱，六月初我railway挂的
