### ISSUE TITLE
本地搭建了代理，验证代理是没有问题的，但是指定参数--env API_REVERSE_PROXY=http://172.18.0.3:3128启动报错

### ISSUE THREAD

**Issue by zhangtw1** [Chanzhaoyu/chatgpt-web#1548]
![image](https://user-images.githubusercontent.com/28799814/233537167-539d076d-8b12-4ea8-90b6-5ea9be5b853d.png)
![image](https://user-images.githubusercontent.com/28799814/233537299-538ec178-5d29-4bec-8c8f-d0e5f97baa76.png)

**Comment by dahaoGPT** [comment]
大佬，怎么验证本地代理没问题？
