### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by MingDengEason** [Chanzhaoyu/chatgpt-web#1549]
我出现图片无法显示的情况
![image](https://user-images.githubusercontent.com/92716961/233557090-17931bb9-be1a-4383-a73e-b1ba89b7e7dc.png)

**Comment by Chanzhaoyu** [comment]
这不是加载了吗

**Comment by lixingxing001** [comment]
哈哈

**Comment by shuaiplus** [comment]
图片成功加载了，但图片加载失败了，哈哈哈

**Comment by huangwb8** [comment]
大佬的意思应该是它的确提供了一个图片的链接和展示，但这个链接已经失效了，锅不在chatGPT上。 所以，它确实是成功了 (ฅ´ω`ฅ)
