### ISSUE TITLE
找人帮我解决注册和登陆+支付的问题，愿意付费，感兴趣+vx: wx5713a

### ISSUE THREAD

**Issue by stevenQinwen** [Chanzhaoyu/chatgpt-web#1551]

**Comment by gouguoyin** [comment]
![image](https://user-images.githubusercontent.com/13517412/233638272-acfa9e9c-304e-4bf0-af75-dbd582cf62a9.png)

**Comment by clayboby** [comment]
https://www.vivi-chat.com/#/chat

**Comment by luckywangxi** [comment]
> https://www.vivi-chat.com/#/chat,

你这官网侵权了把，BAI的官网被你抄的一干二净？

**Comment by as449871748** [comment]
> https://github.com/gouguoyin/chatgpt-web

他这个数据库链接老是失败，登录不了后台

**Comment by 3w3w** [comment]
> https://github.com/gouguoyin/chatgpt-web

这个有水印，授权版要1500元子

**Comment by zaiMoe** [comment]
> > https://www.vivi-chat.com/#/chat,
> 
> 你这官网侵权了把，BAI的官网被你抄的一干二净？

看了下收费，真离谱

**Comment by booktel** [comment]
> > > https://www.vivi-chat.com/#/chat,
> > 
> > 
> > 你这官网侵权了把，BAI的官网被你抄的一干二净？
> 
> 看了下收费，真离谱



> > https://github.com/gouguoyin/chatgpt-web
> 
> 这个有水印，授权版要1500元子



> > https://github.com/gouguoyin/chatgpt-web
> 
> 这个有水印，授权版要1500元子

可以去版权

**Comment by turbobin** [comment]
实现了注册登录+VIP权限模式，使用github pages部署前端，不用购买域名 [https://github.com/turbobin/chatbot](https://github.com/turbobin/chatbot)

**Comment by amdxypf** [comment]
这个项目支持注册登录 https://github.com/amdxypf/chatgpt-web
后端是PHP，体验地址：[https://123.aiman.chat](https://123.aiman.chat)

![image](https://user-images.githubusercontent.com/8206847/236656414-b42bb403-0e1f-4cd8-aee0-25369b51a1f1.png)
