### ISSUE TITLE
答案生成完毕后，请不要跳转

### ISSUE THREAD

**Issue by yefeiyu** [Chanzhaoyu/chatgpt-web#1553]
本来跟着生成的答案阅读到一半了，结果一跳转，又从头来了。很不方便。

**Comment by huangwb8** [comment]
@yefeiyu 

这主要是你没有给该项目提供一个后端，所以对话数据并没有在云端保存。

衍生项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 从[v2.12.3](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.12.3)起，API模式支持每个特定房间有一个基础Prompt。此外，Access Token模式一向是支持连续对话的。

感兴趣的话，可以看看我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。 

加油 (ฅ´ω`ฅ)

**Comment by clayboby** [comment]
我看到这个项目：https://www.vivi-chat.com/#/chat 是基于这个网页搭建的，但是又多了很多功能，是也有fork之后的开源版本吗

**Comment by wanghuohuoyan** [comment]
> @yefeiyu
> 
> 这主要是你没有给该项目提供一个后端，所以对话数据并没有在云端保存。
> 
> 衍生项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 从[v2.12.3](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.12.3)起，API模式支持每个特定房间有一个基础Prompt。此外，Access Token模式一向是支持连续对话的。
> 
> 感兴趣的话，可以看看我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。
> 
> 加油 (ฅ´ω`ฅ)
请教下，我按照你的弄，服务器直接炸了，能使用一会，CPU 内存爆了，关了容器和删了都一样，只能重装系统

**Comment by huangwb8** [comment]
@wanghuohuoyan  

不知道你的服务器的配置如何呢？ 发出来看看。

我暂时还没有遇到过装docker要搞到重装系统的情况。

**Comment by wanghuohuoyan** [comment]
> @wanghuohuoyan
> 
> 不知道你的服务器的配置如何呢？ 发出来看看。
> 
> 我暂时还没有遇到过装docker要搞到重装系统的情况。

cenos7 内存500M 2核

**Comment by huangwb8** [comment]
@wanghuohuoyan 

那可能真的是你的机器内存太小了 Σ( ° △ °|||)︴ 

我的配置是这样的：

```
3x vCPU Core
45 GB SSD Cached RAID-10 Storage
3 GB RAM
6500GB Monthly Premium Bandwidth
1Gbps Public Network Port
Full Root Admin Access
1 Dedicated IPv4 Address
KVM / SolusVM Control Panel - Reboot, Reinstall, Manage rDNS, & much more
LOCATION: Los Angeles
JUST $24.28/YEAR or $47.06/2 YEARS
```
这确实是我的疏忽。因为我没有这么小的vps。

我觉得，你那个配置，可以勉强试一下chatgpt-web。 如果你同时还装了反向代理，估计不太行。

**Comment by wanghuohuoyan** [comment]
我只chatgpt-web + 代理可以使用，但是半小时后，后台给我装四五个乌班图的容器，不知为啥

> @wanghuohuoyan
> 
> 那可能真的是你的机器内存太小了 Σ( ° △ °|||)︴
> 
> 我的配置是这样的：
> 
> ```
> 3x vCPU Core
> 45 GB SSD Cached RAID-10 Storage
> 3 GB RAM
> 6500GB Monthly Premium Bandwidth
> 1Gbps Public Network Port
> Full Root Admin Access
> 1 Dedicated IPv4 Address
> KVM / SolusVM Control Panel - Reboot, Reinstall, Manage rDNS, & much more
> LOCATION: Los Angeles
> JUST $24.28/YEAR or $47.06/2 YEARS
> ```
> 
> 这确实是我的疏忽。因为我没有这么小的vps。
> 
> 我觉得，你那个配置，可以勉强试一下chatgpt-web。 如果你同时还装了反向代理，估计不太行。

我只chatgpt-web + 代理可以使用，但是半小时后，后台给我装四五个乌班图的容器，不知为啥

**Comment by huangwb8** [comment]
@wanghuohuoyan 

我从来没遇到过喔！ 

我提供的docker-compose脚本，是不包含其它镜像的。 也没有恶意的代码。

如果它自动给你装Ubuntu容器，可能你要小心自己的电脑是不是被入侵了。

**Comment by wanghuohuoyan** [comment]
> @wanghuohuoyan
> 
> 我从来没遇到过喔！
> 
> 我提供的docker-compose脚本，是不包含其它镜像的。 也没有恶意的代码。
> 
> 如果它自动给你装Ubuntu容器，可能你要小心自己的电脑是不是被入侵了。

好的，谢谢

**Comment by huangwb8** [comment]
@wanghuohuoyan 

使用ssh的时候，不要使用弱密码。 你可以用 [bitwarden](https://blognas.hwb0307.com/linux/docker/236) 之类的工具托管密码。

建议使用密钥对而不是密码登陆VPS： [Linux基础 基于密钥对的SSH远程登陆](https://blognas.hwb0307.com/linux/linux-basic/3020)

你也可以看看和VPS安全有关的一些技巧： [Linux基础 个人VPS安全](https://blognas.hwb0307.com/linux/linux-basic/412)

**Comment by wanghuohuoyan** [comment]
> @wanghuohuoyan
> 
> 使用ssh的时候，不要使用弱密码。 你可以用 [bitwarden](https://blognas.hwb0307.com/linux/docker/236) 之类的工具托管密码。
> 
> 建议使用密钥对而不是密码登陆VPS： [Linux基础 基于密钥对的SSH远程登陆](https://blognas.hwb0307.com/linux/linux-basic/3020)
> 
> 你也可以看看和VPS安全有关的一些技巧： [Linux基础 个人VPS安全](https://blognas.hwb0307.com/linux/linux-basic/412)

 :+1:

**Comment by yefeiyu** [comment]
> 

感兴趣的话，可以看看我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。
在你的教程里没有找到怎么消除这个逐字回答完毕后、跳转到该回复最上端的问题。

**Comment by huangwb8** [comment]
> > 
> 
> 感兴趣的话，可以看看我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。 在你的教程里没有找到怎么消除这个逐字回答完毕后、跳转到该回复最上端的问题。

我并没有直接使用Chanzhaoyu/chatgpt-web，而是使用[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)项目——它并没有这个问题。 这不知道算不算回答了这个问题 Σ( ° △ °|||)︴

**Comment by yefeiyu** [comment]
> Kerwin1202/chatgpt-web

感谢。问题解决了。
能否将stop responding这个标签与chatgpt的图标结合起来，在responding的时候chatgpt的logo就旋转、如果想停止，就点击这logo。生成完答案后，停止旋转。如果答案是可生成的，就是绿色；如果无法回答的答案，就是黄色；有第三词的就是红色。
当然，我不是为了好看，我主要是想解决：答案生成完毕后，stop responding这标签消失，导致的网页向下跳动一行。
