### ISSUE TITLE
使用docker自建后ssl握手错误

### ISSUE THREAD

**Issue by ev11ccaatt** [Chanzhaoyu/chatgpt-web#1554]
这是错误详情
`request to https://api.openai.com/v1/chat/completions failed, reason: write EPROTO 387BF4B3077F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 40`

**Comment by huangwb8** [comment]
会用docker的话可以试试衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) ，基于MongoDB后端。可以对比一下试试看，目前是挺稳定的。 具体见我的教程：  [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by horse-world** [comment]
![image](https://user-images.githubusercontent.com/62488969/235632513-c4f8e853-8bbf-46af-98c2-f25f34cfa701.png)
how to fix it

**Comment by horse-world** [comment]
换一个节点就行了
