### ISSUE TITLE
我想实现sw缓存

### ISSUE THREAD

**Issue by feiyu201** [Chanzhaoyu/chatgpt-web#1556]
哪位可以告诉我需要修改那些东西,我想打包就自动生成sw的缓存省去每次加载过久

**Comment by huangwb8** [comment]
> 哪位可以告诉我需要修改那些东西,我想打包就自动生成sw的缓存省去每次加载过久

有个数据库后端就行了吧？我平时用也没感觉加载很久呀

**Comment by feiyu201** [comment]
@huangwb8 sw 直接缓存js 可以更快速 基本上刷新感觉无感一样

**Comment by swuecho** [comment]
> @huangwb8 sw 直接缓存js 可以更快速 基本上刷新感觉无感一样

服务器配置好了 js css 静态资源本来就是缓存的。
