### ISSUE TITLE
如何部署在vercel

### ISSUE THREAD

**Issue by lanhaitaojin** [Chanzhaoyu/chatgpt-web#1557]
使用vite在vercel部署后报错，有在vercel上面部署的解决方案么
![image](https://user-images.githubusercontent.com/130837051/233763987-214e4793-3cb0-4b2c-9d70-02768c0976bd.png)

**Comment by shuaiplus** [comment]
作者说过要前后端分离，但我没弄会，放弃了

**Comment by 3w3w** [comment]
我也是显示这个...不会解决

**Comment by 393695510** [comment]
求教程

**Comment by 870384300** [comment]
> 求教程

把项目里面的node服务单独部署，静态请求发送到你单独部署的服务

**Comment by wujt1084** [comment]
https://chatgpt-web-service-seven.vercel.app/  我后端单独部署了也不行

**Comment by jh410** [comment]
用另一个开源吧，这个我也没弄成功

**Comment by dgqyushen** [comment]
同没弄成功
