### ISSUE TITLE
如何统计每次对话消耗的token数呢

### ISSUE THREAD

**Issue by git136390** [Chanzhaoyu/chatgpt-web#1558]
我在这个开源项目基础上添加了用户登录/注册部分，发现不知道用户每次对话消耗了多少token，或者说用了多少额度，这个怎么实现呢

**Comment by huangwb8** [comment]
@git136390 

可以参考衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 的某次[pull request](https://github.com/Kerwin1202/chatgpt-web/pull/19)。  目前这个功能已经是默认的了。 

更多教程可参考： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by shuaiplus** [comment]
> @git136390
> 
> 可以参考衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 的某次[pull request](https://github.com/Kerwin1202/chatgpt-web/pull/19)。 目前这个功能已经是默认的了。
> 
> 更多教程可参考： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

怎么哪哪都有你，哈哈哈

**Comment by huangwb8** [comment]
> > @git136390
> > 可以参考衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 的某次[pull request](https://github.com/Kerwin1202/chatgpt-web/pull/19)。 目前这个功能已经是默认的了。
> > 更多教程可参考： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> 
> 怎么哪哪都有你，哈哈哈

哪都有我的主要原因，是因为大家总是重复地问类似的问题；而这些问题，在我的文章中都有现在的答案。 直接引用个链接比较省口水。

**Comment by shuaiplus** [comment]
还有一个原因就是你把作者不想弄，但咱们想添加的功能差不多都弄好了，牛

**Comment by git136390** [comment]
> @git136390
> 
> 可以参考衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 的某次[pull request](https://github.com/Kerwin1202/chatgpt-web/pull/19)。 目前这个功能已经是默认的了。
>
> 更多教程可参考： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

这个pull quest完全没提到实现过程啊，我的后台不是express实现的，**该怎么改呢**
就算我用express，这个fork改了哪些代码我也不知道，**照搬不了**
有没有详细讲解token如何实现的文章，付费也行，急用o(╥﹏╥)o

**Comment by codewithAI** [comment]
> > @git136390
> > 可以参考衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 的某次[pull request](https://github.com/Kerwin1202/chatgpt-web/pull/19)。 目前这个功能已经是默认的了。
> > 更多教程可参考： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> 
> 这个pull quest完全没提到实现过程啊，我的后台不是express实现的，**该怎么改呢** 就算我用express，这个fork改了哪些代码我也不知道，**照搬不了** 有没有详细讲解token如何实现的文章，付费也行，急用o(╥﹏╥)o

我实现了这个功能后，抽空详细整理了相关的原理和代码实现，[系列文章见链接](https://mbd.pub/o/bread/ZJiUk5Zw)：
https://mbd.pub/o/bread/ZJiUk5Zw
最近很多人在根据不同场景(小红书文案)做二次开发，这个功能实现过程有问题可加我微信**langu86**，包教包会

**Comment by git136390** [comment]
> > > @git136390
> > > 可以参考衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 的某次[pull request](https://github.com/Kerwin1202/chatgpt-web/pull/19)。 目前这个功能已经是默认的了。
> > > 更多教程可参考： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> > 
> > 
> > 这个pull quest完全没提到实现过程啊，我的后台不是express实现的，**该怎么改呢** 就算我用express，这个fork改了哪些代码我也不知道，**照搬不了** 有没有详细讲解token如何实现的文章，付费也行，急用o(╥﹏╥)o
> 
> 我实现了这个功能后，抽空详细整理了相关的原理和代码实现，[系列文章见链接](https://mbd.pub/o/bread/ZJiUk5Zw)： https://mbd.pub/o/bread/ZJiUk5Zw 最近很多人在根据不同场景(小红书文案)做二次开发，这个功能实现过程有问题可加我微信**langu86**，包教包会

弄好了，谢谢，原来看懂源码、理解实现原理后要改的并不多
老哥教程写得很详细，赞ヾ(●゜ⅴ゜)ﾉ

**Comment by rocket2023** [comment]
参考群项目：204311814
