### ISSUE TITLE
有没有使用宝塔部署的教程，本地搞了下速度很棒呀

### ISSUE THREAD

**Issue by liupeng176** [Chanzhaoyu/chatgpt-web#1559]
你好

**Comment by dqzboy** [comment]
一键部署脚本：[ChatGPT-WEB一键部署](https://github.com/dqzboy/ShellProject/tree/main/ChatGPT/ChatGPT-WEB)

**Comment by Nordul** [comment]
已经给了docker compose的文件，宝塔在docker compose配置文件位置直接docker-compose up -d更方便吧

**Comment by liupeng176** [comment]
多谢各位,这个是我想要的  附链接:https://github.com/gouguoyin/chatgpt-web
