### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by SAmcmm** [Chanzhaoyu/chatgpt-web#1560]
throw new Error('Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable')  请问这个是什么原因我都填写了啊

**Comment by xuliyaheizi** [comment]
你是不是在.env.example文件里面写的？需要重新建一个.env文件，然后里面写

**Comment by SAmcmm** [comment]
新建了server运行pnpm start也是错误...

**Comment by SAmcmm** [comment]
我是windows服务器
