### ISSUE TITLE
手动部署前端无法访问后端解决办法

### ISSUE THREAD

**Issue by Lang5200** [Chanzhaoyu/chatgpt-web#1561]
使用pnpm dev运行没有问题，但是编译之后，配置文件中的VITE_APP_API_BASE_URL视乎就没有作用了，api是指向前端的/api/xxx
需要做一个反向代理，将/api目录下的访问代理到127.0.0.1:3002
我这边用的apache
<IfModule mod_proxy.c>
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPass /api http://127.0.0.1:3002/
    ProxyPassReverse /api http://127.0.0.1:3002/
</IfModule>

**Comment by huangwb8** [comment]
会用/能用docker的话可以看看这个教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

教程展示了[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)的衍生项目之一[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)的安装方法，后者使用mongoDB作为后端。

目前， Kerwin1202/chatgpt-web已经支持房间特定提示词、GUI界面用户密码重置、百度敏感词审计、提问/回复token消耗数显示、Temprature和Top_p超参数等功能。 由于有数据库支持，还有很多基于数据库的特性，比如云端聊天记录保持。Kerwin1202/chatgpt-web对于API和Access Token的支持都挺好。 我自己是两个都有使用。 

教程还展示了自建反向代理以绕过Cloudflare验证的方法。

感兴趣的话自己看看喽！

**Comment by hieivip** [comment]
> @Lang5200
> 
> 会用/能用docker的话可以看看这个教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> 
> 教程展示了[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)的衍生项目之一[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)的安装方法，后者使用mongoDB作为后端。
> 
> 目前， Kerwin1202/chatgpt-web已经支持房间特定提示词、GUI界面用户密码重置、百度敏感词审计、提问/回复token消耗数显示、Temprature和Top_p超参数等功能。 由于有数据库支持，还有很多基于数据库的特性，比如云端聊天记录保持。Kerwin1202/chatgpt-web对于API和Access Token的支持都挺好。 我自己是两个都有使用。
> 
> 教程还展示了自建反向代理以绕过Cloudflare验证的方法。
> 
> 感兴趣的话自己看看喽！

你把服务弄到https://vercel.com/ 这个上面

**Comment by omgcx1222** [comment]
> > @Lang5200
> > 会用/能用docker的话可以看看这个教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> > 教程展示了[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)的衍生项目之一[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)的安装方法，后者使用mongoDB作为后端。
> > 目前， Kerwin1202/chatgpt-web已经支持房间特定提示词、GUI界面用户密码重置、百度敏感词审计、提问/回复token消耗数显示、Temprature和Top_p超参数等功能。 由于有数据库支持，还有很多基于数据库的特性，比如云端聊天记录保持。Kerwin1202/chatgpt-web对于API和Access Token的支持都挺好。 我自己是两个都有使用。
> > 教程还展示了自建反向代理以绕过Cloudflare验证的方法。
> > 感兴趣的话自己看看喽！
> 
> 你把服务弄到https://vercel.com/ 这个上面

服务放到这上面好像会报跨域
