### ISSUE TITLE
百度云服务器代理请求failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by lemonwan** [Chanzhaoyu/chatgpt-web#1562]
我的环境是用docker搭建的，百度云的服务器。我在服务器上装了clash订阅机场，开始一个星期是好用的，但是后来就不能用了，麻烦能有什么办法解决下吗？
![微信截图_20230423094806](https://user-images.githubusercontent.com/23022365/233814999-182398c6-bf28-49ab-abe3-bc90beacb59e.png)

**Comment by 0hMyGod** [comment]
我的今天也变成这样了 ，直接访问chatgpt官网可用，自己docker部署的报这个错

**Comment by 1368590868** [comment]
> 

老哥，有clash安装订阅的具体步骤嘛，用的飞鸟云。

**Comment by lemonwan** [comment]
@1368590868 我之前刚写的https://lemonwan.github.io/2023/04/22/Clash%E9%83%A8%E7%BD%B2Linux%E6%9C%8D%E5%8A%A1%E5%99%A8/
