### ISSUE TITLE
Nginx 反向代理了，逐字效果也不行，逐字效果的代码在哪里~~~~~

### ISSUE THREAD

**Issue by Goody-5566** [Chanzhaoyu/chatgpt-web#1572]
看的迷迷糊糊的，大佬，请轻轻的告诉我逐字显示怎么搞的，在线等，急！！！

**Comment by Goody-5566** [comment]
这个效果，前端的代码是怎么实现的

**Comment by huangwb8** [comment]
不知道你是使用api还是access token？有没有可能是网络延迟导致逐字效果不明显呢？

**Comment by Goody-5566** [comment]
token，反向代理也搞了，大佬的源码看不懂，这个想项目的逐字效果是前端实现的吗？

**Comment by huangwb8** [comment]
> token，反向代理也搞了，大佬的源码看不懂，这个想项目的逐字效果是前端实现的吗？

我觉得是你的反向代理延迟比较高。 我之前部署的时候 Chanzhaoyu/chatgpt-web 是有逐字效果的（虽然现在我用的是另外一个项目）

**Comment by Goody-5566** [comment]
他这个源码没实现逐字打印这个效果吗？

**Comment by huangwb8** [comment]
> 他这个源码没实现逐字打印这个效果吗？

应该是有的吧。 或者你可以试试 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 。 我也写过教程， 它是有逐字效果的： 

![](https://user-images.githubusercontent.com/35643122/233847095-0d02853a-86e5-41ad-97d0-85ac2c73214c.gif)


具体教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by Goody-5566** [comment]
> > 他这个源码没实现逐字打印这个效果吗？
> 
> 应该是有的吧。 或者你可以试试 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 。 我也写过教程， 它是有逐字效果的：
> 
> ![](https://user-images.githubusercontent.com/35643122/233847095-0d02853a-86e5-41ad-97d0-85ac2c73214c.gif) [ ![](https://user-images.githubusercontent.com/35643122/233847095-0d02853a-86e5-41ad-97d0-85ac2c73214c.gif) ](https://user-images.githubusercontent.com/35643122/233847095-0d02853a-86e5-41ad-97d0-85ac2c73214c.gif) [ ](https://user-images.githubusercontent.com/35643122/233847095-0d02853a-86e5-41ad-97d0-85ac2c73214c.gif)
> 
> 具体教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

这个项目就差逐字效果就结束了，不想再换了

**Comment by xiaosaaaa** [comment]
没有打字机的效果，可能是因为你nginx的配置问题，查之前的issue应该有的

**Comment by huangwb8** [comment]
@Goody-5566  @xiaosaaaa 

之前issue里面的意见是禁用nginx的缓存。 你可以试试。

**Comment by xuxiang19961203** [comment]
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
	proxy_buffering off;             //在你的nginx中配置一行这个, 就可以解决了
    location / {}
.......
}

**Comment by yjn140** [comment]
我也遇到这个问题
![屏幕录制2023-04-26 11 43 26](https://user-images.githubusercontent.com/30982195/235096427-4314cb97-6199-4cf4-bb29-511dcd2dbade.gif)

**Comment by SeduceQAQ** [comment]
麻烦先看一下README
