### ISSUE TITLE
ChatGPTError: ChatGPT error 401: {"errorMessage":"Access token has expired."}

### ISSUE THREAD

**Issue by lwsqzwb** [Chanzhaoyu/chatgpt-web#1574]
ChatGPTError: ChatGPT error 401: {"errorMessage":"Access token has expired."}

我切换到gpt4的token，报错了，说token过期，但实际没有过期

**Comment by GitHubChrisChen8035** [comment]
网页正常登录，开发者模式查看AccessToken，那个才是正确的Token...

**Comment by kwingart** [comment]
> 网页正常登录，开发者模式查看AccessToken，那个才是正确的Token...

具体怎么看，我也碰到同样问题了，说accesstoken过期，
ChatGPTError: ChatGPT error 401: {"errorMessage":"Access token has expired."}
但是我登录https://platform.openai.com进去后，用https://chat.openai.com/api/auth/session获取到的还是原来那个token，怎么更新我自己的token呢？有高手知道么？
用微软的浏览器，同样得操作，得到{}，没有其他。
