### ISSUE TITLE
请优化stop responding按钮并附方案

### ISSUE THREAD

**Issue by yefeiyu** [Chanzhaoyu/chatgpt-web#1575]
能否将stop responding这个标签与左侧chatgpt的图标结合起来，在responding的时候chatgpt的logo就旋转、如果想停止，就点击这logo。生成完答案后，停止旋转。如果答案是可生成的，就是绿色；如果无法回答的答案，就是红色；有敏感词的就是黄色。
当然，我不是为了好看，我主要是想解决：（视觉bug）答案生成完毕后，stop responding标签消失，导致的网页向下跳动一行。
目前左侧chatgpt logo的“身份”是“答主”，位于回答汽泡的左上角，因此会随答案往上走。使用上面方案后，需要将该logo置于回答汽泡的左下角，不随答案向上走，才能具有美观性和实用性，即可方便点击停止回答。

**Comment by MH-14** [comment]
颜色区分从技术上是没法简单实现的, 要实现首先得让gpt先分析他的回答是不是这种情况 过于理想化了
停止响应跟别的东西集成在一起对易用性有比较大的影响 甚至需要专门对用户做出提示 不是一个好的方案

**Comment by yefeiyu** [comment]
那就先实现较简单的一点可行与否：
stop responding按钮在回答完成后，消失，但是依然保持图像占位，解决回答完成按钮消失时屏幕文字整体向下“跳”了一下的感觉。

**Comment by MH-14** [comment]
考虑移动端的话 不是一个特别好的方案 会一直有一个高度不小的占位
