### ISSUE TITLE
OPENAI_API_KEY is an array instead of a value

### ISSUE THREAD

**Issue by bcat95** [Chanzhaoyu/chatgpt-web#1576]
OPENAI_API_KEY is an array instead of a value
Currently, the highest OPENAI_API_KEY is credit, if you use it a lot, you will run out of credits or access to openAI in 60s. To overcome this situation, what do you think if OPENAI_API_KEY is an array of KEYs instead of 1 key?
If different KEY has effect on parentMessageId

**Comment by liut** [comment]
Is it really like this? I have linked my credit card and have never encountered this issue. Or try purchasing Plus.
