### ISSUE TITLE
提示"Your account is not active, please check your billing details on our website."

### ISSUE THREAD

**Issue by stormofwormhole** [Chanzhaoyu/chatgpt-web#1577]
"Your account is not active, please check your billing details on our website."

**Comment by huangwb8** [comment]
@stormofwormhole 

你没有免费额度，要绑卡才行。 我当时使用API的时候也是这样。

**Comment by china-zhoujie** [comment]
我也是这个提示，但是我看了免费额度是到7月1号~而且5美金还没有用完，奇怪啊
