### ISSUE TITLE
支持azure openai api吗

### ISSUE THREAD

**Issue by shexiaobin** [Chanzhaoyu/chatgpt-web#1578]

**Comment by zaiMoe** [comment]
请教下如何申请 azure openai api，没有公司真难申请

**Comment by shexiaobin** [comment]
要有公司哈

**Comment by RexWzh** [comment]
国内账号能申请吗，第一步会跳到这个表格：https://aka.ms/oai/access

<img width="387" alt="image" src="https://user-images.githubusercontent.com/62223937/233928974-57f128e7-824a-4179-9bb0-1c1b34f866b8.png">

第11项红字，感觉国内申请不了，我就没弄了。。。

P.S. 有个 Julia 的封装库，看代码可能是支持 Azure 的，这个：https://github.com/JuliaML/OpenAI.jl/blob/main/src/OpenAI.jl#L26

我自己维护了个工具 [openai_api_call](https://github.com/RexWzh/openai_api_call)，也想支持类似功能。。

**Comment by LZQCN** [comment]
> 国内账号能申请吗，第一步会跳到这个表格：https://aka.ms/oai/access
> 
> <img alt="image" width="387" src="https://user-images.githubusercontent.com/62223937/233928974-57f128e7-824a-4179-9bb0-1c1b34f866b8.png">
> 
> 第11项红字，感觉国内申请不了，我就没弄了。。。
> 
> P.S. 有个 Julia 的封装库，看代码可能是支持 Azure 的，这个：https://github.com/JuliaML/OpenAI.jl/blob/main/src/OpenAI.jl#L26
> 
> 我自己维护了个工具 [openai_api_call](https://github.com/RexWzh/openai_api_call)，也想支持类似功能。。

国内可以申请，意思是让你填写完整的国家名称，China 就填 People's Republic of China

**Comment by LZQCN** [comment]
> 请教下如何申请 azure openai api，没有公司真难申请

你可以“代表”你的公司去申请，懂我意思吧？

**Comment by swuecho** [comment]
我的扩展版本是支持的 https://github.com/swuecho/chat/discussions/318
