### ISSUE TITLE
ChatGPTUnofficialProxyAPI(网页 accessToken) 方式不行了吗？一直没反应

### ISSUE THREAD

**Issue by qingyanbaby** [Chanzhaoyu/chatgpt-web#1579]
一直未返回。过了很久就返回504。已经试过那两个推荐的代理地址，都一样

**Comment by huangwb8** [comment]
已经有类似的已解决issue： #1491 

一般反向代理都使用自建的。 公共的不太稳。 

当然也可能存在其它影响网络环境的情况，但你并没有透露相关信息。

**Comment by qingyanbaby** [comment]
https://blognas.hwb0307.com/linux/docker/4201
自搭建反向代理可以了
