### ISSUE TITLE
导出图片的代码块显示不全

### ISSUE THREAD

**Issue by RexWzh** [Chanzhaoyu/chatgpt-web#1581]
这个问题出现挺久了，搜了 Issue 发现还没人提过：

导出图片的代码块最后一行显示不全：
![chat-shot (19)](https://user-images.githubusercontent.com/62223937/233925138-7ad9a3c5-83af-4eed-b8c0-2e9846fa5d0f.png)

测试了 Mac 端和 IPad 端的 Chrome，Safari，都有这个问题。

**Comment by AKGO47** [comment]
@Chanzhaoyu  #381 3月份就有这个问题了
