### ISSUE TITLE
stream方式显示无效

### ISSUE THREAD

**Issue by lix-fs** [Chanzhaoyu/chatgpt-web#1582]
打印了后台是有多个stream流输出，但前端的监控事件就只有最后一个汇总输出。本地起的服务不存在nginx代理；有什么原因会导致我这个不同于别人的响应

**Comment by lix-fs** [comment]
await chatReplyProcess({
      message: prompt,
      lastContext: options,
      process: (chat: ChatMessage) => {
        console.log(chat)
        res.write(firstChunk ? JSON.stringify(chat) : `\n${JSON.stringify(chat)}`)
        firstChunk = false
      },
      systemMessage,
      temperature,
      top_p,
    })
后台打印处

**Comment by lix-fs** [comment]
const fetchChatAPIOnce = async () => {
      await fetchChatAPIProcess<Chat.ConversationResponse>({
        prompt: message,
        options,
        signal: controller.signal,
        onDownloadProgress: ({ event }) => {
          console.log('a', event);
          const xhr = event.target
          const { responseText } = xhr
          // Always process the final line
          const lastIndex = responseText.lastIndexOf('\n', responseText.length - 2)
          let chunk = responseText
          if (lastIndex !== -1)
            chunk = responseText.substring(lastIndex)
          try {
            const data = JSON.parse(chunk)
            console.log('b', data);
前端打印处

**Comment by liut** [comment]
这个问题我还没有遇到过，我本地的环境是正常的。另外，你可以试试co #1289 这个分支，它改为使用`text/event-stream`，看看在你的环境里前端输出是否正常。
