### ISSUE TITLE
如果不要服务端 是不是要把.evn内容放到根目录

### ISSUE THREAD

**Issue by hieivip** [Chanzhaoyu/chatgpt-web#1583]
# Glob API URL
VITE_GLOB_API_URL=/api

VITE_APP_API_BASE_URL=http://127.0.0.1:3002/
这两个参数是不是可以删除

**Comment by haihaimx** [comment]
这两个参数不能删除

**Comment by hieivip** [comment]
> 这两个参数不能删除
官方是这样写的


为了简便 后端开发人员 的了解负担，所以并没有采用前端 workspace 模式，而是分文件夹存放。如果只需要前端页面做二次开发，删除 service 文件夹即可。

如果把service 删除。里面.evn 文件的配置信息就没有；

所以如果我保留VITE_GLOB_API_URL=/api

VITE_APP_API_BASE_URL=http://127.0.0.1:3002/  这两个变量 我还是没有后端的支撑还是会报500错误

**Comment by Chanzhaoyu** [comment]
因为鉴权有用到，你需要删除对应的代码。

**Comment by jacky1997** [comment]
有计划增加auth2鉴权功能吗?

**Comment by vual** [comment]
> 阶段或调试时用到，编译部署后就可以不再用了。

改了VITE_GLOB_API_URL指向我自己的后端，docker打包部署，无效果，怎么解决？

**Comment by vual** [comment]
> 因为鉴权有用到，你需要删除对应的代码。

改了VITE_GLOB_API_URL指向我自己的后端，docker打包部署，无效果，怎么解决？
