### ISSUE TITLE
是否支持 websoket 模式的消息传输

### ISSUE THREAD

**Issue by wll8** [Chanzhaoyu/chatgpt-web#1585]
由于某些服务/代理真的不支持 sse/octet-stream， 就没有了打字效果。

- nginx 层无权限配置
- frp/nps 穿透不支持此推流

是否可以开发一个选项，在 server/env 中可配置，客户端链接后判断是 ws 模式即使用 ws 连接来接收服务器消息.

**Comment by Chanzhaoyu** [comment]
这个项目的 `sse/octet-stream` 本身是项目初期产生的错误，我思考下

**Comment by wll8** [comment]
明天我拉下 #1289 试试，看看我这边的代理是否支持。

**Comment by liut** [comment]
理论上说，ws协议走的是http 1.1，代理支持也是没有问题的。但ws的协议相对底层一些，需要自己做封装，略麻烦。
