### ISSUE TITLE
OPENAI_ACCESS_TOKEN 是不能用了吗？

### ISSUE THREAD

**Issue by qianchen9527** [Chanzhaoyu/chatgpt-web#1586]

**Comment by Chanzhaoyu** [comment]
切换下代理地址

**Comment by huangwb8** [comment]
@qianchen9527 

已经在此issue中解决了 #1491

**Comment by ltinerary** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/pull/1567

这个PR修改了默认的代理，作者已经合并到主分支了。

另外，这个代理地址可以自己配置
