### ISSUE TITLE
执行docker build -t chatgpt-web .命令报错

### ISSUE THREAD

**Issue by ZhiXuanPSY** [Chanzhaoyu/chatgpt-web#1587]
Build的时候报错ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3297996721/Dockerfile: no such file or directory
求大佬解答，我看了/tmp文件夹下面啥都没有，到底是啥原因啊。搞了三四天了头发都掉光了
![c7c882bd08fcb04346bbb6544576d2e](https://user-images.githubusercontent.com/131680566/234012147-470db1a1-0bae-4738-b838-fe47dc08dea9.png)

**Comment by huangwb8** [comment]
@ZhiXuanPSY 

如果你是用docker，不妨试试衍生项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)。 他基于[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)，但在后端有一些优化。 

详细教程在这： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

有问题可以在issue里继续提问；或者在博客评论区留言也行 (ฅ´ω`ฅ)

**Comment by zeraturing** [comment]
...你都没进入编译目录，你能成功才奇怪了....

**Comment by ZhiXuanPSY** [comment]
> ...你都没进入编译目录，你能成功才奇怪了....

啊？怎么进入编译目录啊，是进入chatgpt web文件夹吗大佬，还是需要其他口令？求捞一手
