### ISSUE TITLE
如何取消反向代理（API_REVERSE_PROXY ）

### ISSUE THREAD

**Issue by ray24777** [Chanzhaoyu/chatgpt-web#1588]
当容器部署在原生网络环境或个人拥有访问openai网页的代理时，如何取消代理？

**Comment by huangwb8** [comment]
@ray24777  

打不过就加入。 使用access token的很多小伙伴都可以自建代理。

或者你直接使用api，它是不需要反向代理的。

**Comment by ray24777** [comment]
> 

请问有相关的repo可以参考一下吗
