### ISSUE TITLE
有计划增加auth2鉴权功能吗?

### ISSUE THREAD

**Issue by jacky1997** [Chanzhaoyu/chatgpt-web#1589]
目前的模式似乎完全不用登录验证

**Comment by liut** [comment]
你是指`OAuth2`吗？目前正在测试中，见 #1483 .

**Comment by jacky1997** [comment]
有预计的上线时间么?oauth2验证功能

**Comment by jacky1997** [comment]
> 有预计的上线时间么?oauth2验证功能



> 你是指`OAuth2`吗？目前正在测试中，见 #1483 .

有预计的上线时间么?oauth2验证功能

**Comment by liut** [comment]
> > 有预计的上线时间么?oauth2验证功能
> 
> > 你是指`OAuth2`吗？目前正在测试中，见 #1483 .
> 
> 有预计的上线时间么?oauth2验证功能

最近两天比较忙呢，要不你帮忙接手？

**Comment by jacky1997** [comment]
> 

我帮忙测试可以,开发还不行.
