### ISSUE TITLE
如何给此项目添加一个搜索联网功能

### ISSUE THREAD

**Issue by luckywangxi** [Chanzhaoyu/chatgpt-web#1590]

**Comment by liut** [comment]
没有具体的内容吗？解释一下像什么样的搜索联网功能，具体场景需求是什么？让别人猜？那可有难度。

或者我猜猜看：

按关键字触发搜索？？这个功能官方有插件的。

**Comment by liut** [comment]
https://d58hixvcd6.feishu.cn/docx/HfMEds7Z1ov37wxqM19czTBinWg 这里有提到具体的做法，应该是用插件实现的
