### ISSUE TITLE
流式输出时界面不会自动卷到底部

### ISSUE THREAD

**Issue by Simonmxy** [Chanzhaoyu/chatgpt-web#1591]
输出文字超过2行时，会被Stop Generating的按钮遮住，然后会在后面继续产生内容，滚动条不能一直追逐内容使它们完整展示出来。Generating结束之后，需要手动上滑一下才能将内容全部展示。
Chrome的PC版和Android版均有此问题。

**Comment by jakeslee** [comment]
我也有这个问题，尤期是使用 Azure 的时候，通常一大段同时返回，但不会显示最新行，只能手动下拉。
