### ISSUE TITLE
部署问题汇总

### ISSUE THREAD

**Issue by hieivip** [Chanzhaoyu/chatgpt-web#1592]
本地正常运行，部署服务器不成功。
1.采用的是宝塔node项目 把service文件夹单独部署到node服务器上 如图 
![image](https://user-images.githubusercontent.com/54146330/234164253-b9b07766-c255-4f75-803c-b119f610366c.png)
2.配置域名和端口（主要实现访问IP+端口 可以通） 
![image](https://user-images.githubusercontent.com/54146330/234164389-9ad775c1-3bbe-4713-9c30-1118fa34fd7a.png)
3.查看项目记录 确认servie可以获取到前端信息（这里我是用本地前台修改.env  VITE_APP_API_BASE_URL 换成我上面服务器的ip+端口）
![image](https://user-images.githubusercontent.com/54146330/234164503-28aa0661-6cdb-404b-9aeb-c2f797c9fb44.png)
![image](https://user-images.githubusercontent.com/54146330/234164664-e63b1b91-178c-4a35-96ce-8d9415b29125.png)
这个步骤就把service服务单独部署到了node上。
重点，重点，重点，重点！！！！！！！！！！！  前台部署之后还是报500错误，本地前台正常运行，放到服务器上500错误
是不是需要做一个反向代理 我这样设置的 各位大佬帮忙看看对不对呢？

![image](https://user-images.githubusercontent.com/54146330/234166532-a01c014f-8096-4de3-9f2c-d5cda585b444.png)
![image](https://user-images.githubusercontent.com/54146330/234166601-472e416d-7234-46a3-a58b-ffe111046fc2.png)

我是直接把本地前端代码 pnpm build  打包好 直接压缩到 宝塔根目录，并且给这个站点配置了一个前端访问的域名；
![image](https://user-images.githubusercontent.com/54146330/234167101-a3786ed7-6b41-4a70-8bfe-70b79a5b64fb.png)
下面是审查F12 前端 报404 错误  这个错误是不是代表 前端没有和后端交互上？？？
![image](https://user-images.githubusercontent.com/54146330/234167467-3659ef73-58a7-44e5-a4e4-2f4b7d41eced.png)

各位大佬有没有能帮忙看看的，一直困惑。一直搞。一直搞。一直困惑。搞不明白。砸电脑~~ 只能厚着脸皮~~~~求助，求助呗~~

**Comment by jasontips** [comment]
我建议你不要这样搞啊，在后台直接用命令跑起来，BT面板上做个反代到http://localhost:3002.
不需要在BT上修改参数乱七八糟的

**Comment by liangjiacun** [comment]
大佬 搞定了吗  我部署也一直有问题

**Comment by liangjiacun** [comment]
大佬 搞定了吗  我部署也一直有问题

**Comment by xiehg** [comment]
实验了一下，是注意要改**VITE_GLOB_API_URL**的配置，而不是下面那个，改为VITE_GLOB_API_URL=http://公网IP:3002/api，还没尝试用局域网得不得
