### ISSUE TITLE
OPENAI_ACCESS_TOKEN不可用了吗？

### ISSUE THREAD

**Issue by williamzheng2013** [Chanzhaoyu/chatgpt-web#1594]
ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined

**Comment by gcslaoli** [comment]
> ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined

可以试试我的代理 https://freechat.xyhelper.cn/backend-api/conversation    token随便写不用写真实的

**Comment by huangwb8** [comment]
@williamzheng2013 

清除原有消息或者删除这个对话。 新建一个对话再试试。
