### ISSUE TITLE
感谢作者，放一个演示地址：http://easyai.ink，不需要 key ，免费用

### ISSUE THREAD

**Issue by yisier** [Chanzhaoyu/chatgpt-web#1596]
http://easyai.ink

**Comment by huangwb8** [comment]
@yisier  

加个https是不是会好一点呢

**Comment by yisier** [comment]
> 无法使用

最近这两天，Openai api 速度特别慢，不知道怎么回事

**Comment by huangkezhao** [comment]
免费使用地址：http://huangkz.chat 不注册，不登陆，不关注，打开网址就能用，永久免费

**Comment by leochen12-rgb** [comment]
能不能把key也免费分享一下，/滑稽

**Comment by hjkl950217** [comment]
@leochen12-rgb 这个白嫖过分了
