### ISSUE TITLE
如何修改GPT的错误提示语：ChatGPT error 429: { "error": { "message": "That model is currently overloaded with other requests. ...

### ISSUE THREAD

**Issue by ZhiXuanPSY** [Chanzhaoyu/chatgpt-web#1598]
RT，像这种GPT返回的提示语怎么修改？例如改成“服务器繁忙请稍后重试”之类的？
![image](https://user-images.githubusercontent.com/131680566/234240691-7e2284fc-6f98-4bbd-a78e-8c20c125d8de.png)

**Comment by fanghejun** [comment]
请问你解决了吗？我也出现了同样的问题

**Comment by alex58914195** [comment]
> 请问你解决了吗？我也出现了同样的问题

同样的问题 你解决了吗
