### ISSUE TITLE
有没有人发现api现在越来越慢了，是已经绑了卡的

### ISSUE THREAD

**Issue by Roselearn** [Chanzhaoyu/chatgpt-web#1601]
昨天开始突然变得非常非常慢，有没有兄弟有一样的情况啊！

**Comment by lhbdhr** [comment]
确定一下你自己的网站是否除了你还有别人在用。
我之前懒得设密码，经常回复卡死，
设了密码之后，没人和我同时使用之后，速度起飞。

**Comment by xiaosaaaa** [comment]
并不慢

**Comment by Chanzhaoyu** [comment]
昨晚直连是慢，后来恢复了

**Comment by hjkl950217** [comment]
歪个楼，绑卡后大概消费如何阿？  有些对话久了，一次就要几K的token，我有点打怵

**Comment by gygy** [comment]
不绑卡，自建代理，秒回
