### ISSUE TITLE
ChatGPTAPI和ChatGPTUnofficialProxyAPI都用不了了

### ISSUE THREAD

**Issue by hbsszh** [Chanzhaoyu/chatgpt-web#1602]
我是用docker方式
用ChatGPTAPI，提问后回复的是“request to https://api.openai.com/v1/chat/completions failed, reason: getaddrinfo EAI_AGAIN api.openai.com”
用ChatGPTUnofficialProxyAPI，提问后回复的是“request to https://bypass.churchless.tech/api/conversation failed, reason: getaddrinfo EAI_AGAIN bypass.churchless.tech”

我登录官网使用正常。

大家是这样吗？

**Comment by arthur19q3** [comment]
我也是,现在变成OpenAI timed out waiting for response了

**Comment by DearChuck** [comment]
这是咋回事呢？我也是这个问题

**Comment by arthur19q3** [comment]
是不是梯子的问题呢。怎么每人回复一下。
