### ISSUE TITLE
今天使用出问题了，一直提示：速率限制，请重试。 Rate limit reached, please try again.

### ISSUE THREAD

**Issue by 2wong** [Chanzhaoyu/chatgpt-web#1603]

**Comment by HPUxiaoxiaqi** [comment]
对，我也是

**Comment by Alenwang-96** [comment]
同遇此况

**Comment by mb-fff** [comment]
me too

**Comment by jkhcc11** [comment]
为啥我这边没事？ 你们用的Access Token么？

**Comment by mb-fff** [comment]
没有用 Access Token ，不过现在可以用了，十点左右那会不行。

**Comment by jkhcc11** [comment]
> 没有用 Access Token ，不过现在可以用了，十点左右那会不行。

我的好像一直没问题，用的120刀的 api key

**Comment by jkhcc11** [comment]
> > 没有用 Access Token ，不过现在可以用了，十点左右那会不行。
> 
> 我的好像一直没问题，用的120刀的 api key

然后加 自建反代。

**Comment by AlpacaBi** [comment]
你这个是限流了，没绑信用卡的免费用户rate limit是1分钟30次。绑了信用卡则会扩展刀1分钟3000次

**Comment by GavinZhou0125** [comment]
应该是chat的原因吧，现在chat1分钟有条数限制（token模式下）

**Comment by yaoyi098** [comment]
api改规则了 原来是30 RPM 现在改3RPM了 不绑卡基本用不了了。
