### ISSUE TITLE
超长回复分段的时候有内容丢失-token模式

### ISSUE THREAD

**Issue by xiaoguaishou92** [Chanzhaoyu/chatgpt-web#1604]
![image](https://user-images.githubusercontent.com/20310407/234444183-975334ea-9616-428b-99b2-91564a7cd8fe.png)
![image](https://user-images.githubusercontent.com/20310407/234444281-8559eb8f-4f81-4da2-902d-d35a0a81e093.png)

第一张图是通过镜像返回的，第二张图是官网同一个会话的

**Comment by ludashi2020** [comment]
是的。感觉上下文会乱。

**Comment by xiaoguaishou92** [comment]
> 是的。感觉上下文会乱。

![image](https://user-images.githubusercontent.com/20310407/234444885-cc6c4843-232d-4b70-b64b-4b86e7ae0c4c.png)
上下文乱可能是你点到了这个，点一下或者清除下缓存，我之前也踩过这个坑

**Comment by HPUxiaoxiaqi** [comment]
为什么我的显示速率限制，请重试。 Rate limit reached, please try again.，而你们的还能正常用呀

**Comment by xiaoguaishou92** [comment]
> 为什么我的显示速率限制，请重试。 Rate limit reached, please try again.，而你们的还能正常用呀

你去官网试试能不能正常用，如果能用考虑下代理的问题，我是自建的代理。平时用的也不多
