### ISSUE TITLE
好久没更新了

### ISSUE THREAD

**Issue by lqs1920** [Chanzhaoyu/chatgpt-web#1605]
啥时候可以release新版本呀？期待~

**Comment by shuaiplus** [comment]
作者在憋大招呢，不要急

**Comment by shuaiplus** [comment]
你看，我就说嘛，作者更新了

**Comment by clayboby** [comment]
去做商业版去了
www.vivi-chat.com

**Comment by clayboby** [comment]
https://chat.zhenbs.com/
微信登录后，每天都免费用，注册就送GPT4试用。也可游客体验
每邀请一个人增加一次GPT4的使用次数，外加送GPT3五次和余额赠送
公众号还有各种福利，实现3.5和4的使用
