### ISSUE TITLE
chatgpt-web-plus

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#1606]
简介：

包含完整管理的 `chatgpt-web` 应用

- 个人部署
- 商业部署
- 企业部署
- 团队部署

预览：

> 服务速率有限，请有限访问，谢谢

[介绍地址](https://github.com/Chanzhaoyu/chatgpt-web-plus)

[体验地址](http://chatgpt-web-plus.it007996.top/login?inviteCode=BNPW7BQHD)

联系

Q群1：734133205（满）
Q群2：708017015

**Comment by rockagen** [comment]
高低搞个TG，现在谁用qq

**Comment by shuaiplus** [comment]
意思是要收费吗？

**Comment by Chanzhaoyu** [comment]
> 

那个版本是收费

**Comment by Chanzhaoyu** [comment]
> 高低搞个TG，现在谁用qq

很多能访问 `GitHub` 的其实访问不了 `TG`

**Comment by axtlive** [comment]
打广告这么猖獗了吗？直接用issue打广告

**Comment by tech1502** [comment]
来试试我的http://chatgpt.030987.xyz/

**Comment by tech1502** [comment]
来试试我的http://chatgpt.030987.xyz/，套餐，支付，限流，token和api模式等功能全部都有

**Comment by winteroo** [comment]
试试这个 http://yl.iisai.cn  稳定快速

**Comment by 5265liu** [comment]
区别是啥

**Comment by 5265liu** [comment]
会不会后续不维护了

**Comment by dakaca007** [comment]
今天发现软件严重封Key。亲身部署2次key。上线马上封key。基本上无用了。服务器新加坡。使用别的软件用的非常好。

**Comment by shuaiplus** [comment]
我用的vercel  没问题

**Comment by 1130600015** [comment]
> 今天发现软件严重封Key。亲身部署2次key。上线马上封key。基本上无用了。服务器新加坡。使用别的软件用的非常好。

无稽之谈

**Comment by feikoooo** [comment]
有演示吗？怎么收费的呀！


流水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chanzhaoyu/chatgpt-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月3日(星期三) 晚上11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chanzhaoyu/chatgpt-web] chatgpt-web-plus (Issue #1606)





 
来试试我的http://chatgpt.030987.xyz/，套餐，支付，限流，token和api模式等功能全部都有

**Comment by wangjueszu** [comment]
群二加不上

**Comment by younghang** [comment]
好人一生平安

**Comment by skyee1** [comment]
怎么感觉最近使用railway部署之后还是需要梯子才能访问，有谁遇到过这个问题吗？

**Comment by swuecho** [comment]
> 怎么感觉最近使用railway部署之后还是需要梯子才能访问，有谁遇到过这个问题吗？

我在fly io 遇到过，换了个自定义域名了事

**Comment by skyee1** [comment]
但是railway没法自定义域名哇，怎么解决呀，有人知道代理自己怎么建立嘛

**Comment by luneice** [comment]
请谨慎甄别，有一些人冒充作者出售盗版源码！！！
