### ISSUE TITLE
注意在服务器上运行docker时端口映射

### ISSUE THREAD

**Issue by randbitxx** [Chanzhaoyu/chatgpt-web#1609]
官方的docker hub镜像 [chenzhaoyu94/chatgpt-web](https://hub.docker.com/r/chenzhaoyu94/chatgpt-web/)疑似在2023-04-22日开始全天偷偷使用api key。刚开始以为api key被泄漏了，毕竟在很多应用里面配置了。于是马上删除了老的api key，只在chatgpt-web的docker镜像上使用了新的api key。docker 容器一启动，在没有访问的情况下（nginx没有访问日志）。open ai的后台使用量统计中就开始有请求了，容器停止请求就没有了。大概偷跑了$3。不知道其他人有没有这种情况。

说明：我的chatgpt-web使用docker运行，通过nginx代理到docker，并且需要basic认证才能访问，并配置了访问日志。服务器防火墙只允许443和22端口入包。初步排除服务器被入侵可能。

**Comment by huangcj-git** [comment]
我没出现这种情况，代码都是开源的应该也不会出现这个问题。
openai 官方的用量统计是用的UTC时间，不是本地时。有没有可能是你统计的时候看错了时间

**Comment by randbitxx** [comment]
> 我没出现这种情况，代码都是开源的应该也不会出现这个问题。 openai 官方的用量统计是用的UTC时间，不是本地时。有没有可能是你统计的时候看错了时间

我知道是utc时间，和中国差8小时，他其实也在后面标注了本机时间。使用量按每5分钟统计一次。
以下是4月25号的使用量同时，时间是utc：

Language modelusage 791 requests

|time|requests|
|---|---|
|00:00|32 requests|
|01:00|65 requests|
|02:00|68 requests|
|03:00| 69 requests|
|04:00| 58 requests|
|05:00| 29 requests|
|06:00| 12 requests|
|07:00| 30 requests|
|08:00| 17 requests|
|09:00| 2 requests|
|10:00| 24 requests|
|13:00| 18 requests|
|14:00| 35 requests|
|15:00| 31 requests|
|16:00| 19 requests|
|17:00| 37 requests|
|18:00| 40 requests|
|19:00| 52 requests|
|20:00| 34 requests|
|21:00| 54 requests|
|22:00| 21 requests|
|23:00| 44 requests|

**Comment by randbitxx** [comment]
确实是我搞错了，给大家造成困扰了🙇‍♀️🙇‍♀️

情况是这样的：  
  我是使用 `docker run  -p 3002:3002'来将端口以host方式映射到本机，但是docker的实现方式是在 iptables nat PREROUTING 加了一条`-A DOCKER ! -i docker0 -p tcp -m tcp --dport 3002 -j DNAT --to-destination 172.17.0.2:3002`  ，结果在DNAT了所有3002的数据包到docker，跳过了iptables INPUT的规则（悲剧啊）。

由于平时很少在服务器上使用docker照成了这个问题。希望大家引以为戒，在映射端口时最好注意使用 `-p 127.0.0.1:3002:3002`。

再次道歉🙇‍♀️
