### ISSUE TITLE
请教一下，有没有人能明确说一下这几个微调参数在哪里可以改啊？主要是max_tokens参数

### ISSUE THREAD

**Issue by jasontips** [Chanzhaoyu/chatgpt-web#1610]
![image](https://user-images.githubusercontent.com/130386594/234481870-286ca346-f142-4495-86e8-f1846f19207c.png)
在这里加 的参数没用：
![image](https://user-images.githubusercontent.com/130386594/234482266-7d6e1525-948e-4a97-bc26-a896842f3d3a.png)
 是我加的有问题么？
    const options: ChatGPTAPIOptions = {
      apiKey: process.env.OPENAI_API_KEY,
      completionParams: { model, max_tokens: 4096 },
      debug: !disableDebug,
    }

或者：
if (model.toLowerCase().includes('gpt-3.5-turbo')) {
        options.maxModelTokens = 4096
        options.maxResponseTokens = 2048
    }
麻烦哪 位大神能指点一下，不甚感激！

**Comment by csu-czh** [comment]
![7531682493637_ pic](https://user-images.githubusercontent.com/30564011/234499854-a35a22d1-450b-499c-b157-45f4e178bf28.jpg)
maxModelTokens 是整个模型的最大token，包括上下文和回复的内容，max_tokens是回复的最大token
