### ISSUE TITLE
[建议]是否能增加多key和api设置

### ISSUE THREAD

**Issue by maxage** [Chanzhaoyu/chatgpt-web#1612]
以下是您编辑后的文章：

# 能否增加以下功能？

## 1. 自定义key

在网页设置中增加自定义key，例如当原始key失效时，在此处输入新的key，而不必每次更改容器。

（例如，在高级选项中添加）

## 2. 增加自定义API地址

是否可以在网页设置中增加自定义API地址的选项？例如当容器部署在家中或其他环境中时，当您无法访问该位置时，您可以在此处填写自己的API地址。

（例如，在高级选项中添加）

## 3. 保存聊天记录至服务器

我想在多个设备上使用ChatGPT并同步访问聊天记录。在更换电脑后发现之前的聊天记录都丢失了，是否可以增加一个将聊天内容保存至服务端的选项？授权码正确匹配不同身份。

需要注意的是，聊天记录保存在服务器可能会涉及到隐私和安全问题，因此在实施之前应该谨慎考虑，并征询相关法律意见。

感谢您的阅读！

**Comment by maxage** [comment]
呃~chatgpt帮我写的。后面还帮我增加了

>>需要注意的是，聊天记录保存在服务器可能会涉及到隐私和安全问题，因此在实施之前应该谨慎考虑，并征询相关法律意见。

>>感谢您的阅读！

**Comment by huangwb8** [comment]
@maxage 

你的诉求，开源免费项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) ——[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)的一个分支——基本可以解决。对于第一、第二个要求，本来就可以直接在前端的设置里更改。  至于第三个要求， Kerwin1202/chatgpt-web本来就是基于MongoDB的，你的聊天数据都是保存在数据库里，自然就是在哪里登陆都可以保持了。

关于[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)的部署我也写过教程，具体见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

值得一提的是，Chanzhaoyu大佬在2023-04-26建了一个QQ群734133205，介绍了Chanzhaoyu/chatgpt-web项目的plus版本——chatgpt-web-plus，其包含个人部署、商业部署、企业部署和团队部署等内容。项目地址在[Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)，非开源且付费。感兴趣可以关注 [chatgpt-web-plus · Issue #1606 · Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web/issues/1606)。

**Comment by clayboby** [comment]
大佬去做商业版去了
http://www.vivi-chat.com/

**Comment by UseGPT** [comment]
https://github.com/UseGPT/ChatGPT-SaaS

**Comment by maxage** [comment]
> @maxage
> 
> 你的诉求，开源免费项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) ——[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)的一个分支——基本可以解决。对于第一、第二个要求，本来就可以直接在前端的设置里更改。 至于第三个要求， Kerwin1202/chatgpt-web本来就是基于MongoDB的，你的聊天数据都是保存在数据库里，自然就是在哪里登陆都可以保持了。
> 
> 关于[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)的部署我也写过教程，具体见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> 
> 值得一提的是，Chanzhaoyu大佬在2023-04-26建了一个QQ群734133205，介绍了Chanzhaoyu/chatgpt-web项目的plus版本——chatgpt-web-plus，其包含个人部署、商业部署、企业部署和团队部署等内容。项目地址在[Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)，非开源且付费。感兴趣可以关注 [chatgpt-web-plus · Issue #1606 · Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web/issues/1606)。

牛~谢谢解惑！

**Comment by maxage** [comment]
> 大佬去做商业版去了 http://www.vivi-chat.com/

大佬还是大佬~哈哈！

**Comment by huangkezhao** [comment]
永久免费：不注册 不登陆 不关注 不广告 http://www.aiassist.chat
