### ISSUE TITLE
求大佬指点：request to http://127.0.0.1:8081/conversation failed, reason: connect ECONNREFUSED 127.0.0.1:8081

### ISSUE THREAD

**Issue by Jehuge** [Chanzhaoyu/chatgpt-web#1617]
用的美国服务器，自建反代配置完成后交互出现：request to http://127.0.0.1:8081/conversation failed, reason: connect ECONNREFUSED 127.0.0.1:8081
![image](https://user-images.githubusercontent.com/89401498/234787813-a0cebb78-98e3-4a61-840f-214ff48405bd.png)

**Comment by Usongkam** [comment]
首先看看你的go-chatgpt-api的端口是不是映射到了宿主机的8081，其次看看你的宿主机的8081端口允许哪些ip访问。

另外，go-chatgpt-api这个docker 并不推荐直接映射到宿主机的端口上。不如把两个docker部署在同一个网段通过名字互相访问。

**Comment by dqzboy** [comment]
http://127.0.0.1:8081/conversation   换成你的VPS内网IP；如果chatgpt-web也是docker启动的，那么直接http://go-chatgpt-api:8081/conversation
