### ISSUE TITLE
更新到 2.10.9后，回答到一半经常就断了。

### ISSUE THREAD

**Issue by popokcn** [Chanzhaoyu/chatgpt-web#1618]
看了下docker中的日志，显示
![image](https://user-images.githubusercontent.com/17810922/234794008-923972b2-aee9-4af9-8930-32002d6deb22.png)

应该不是我的网络问题，因为更新2.10.9之前是从来没有问题的。
而且我另一个chatgpt next web的套壳就没这个问题。

api用的是3.5,收费充值余额的

**Comment by huangcj-git** [comment]
参照docker部署的参数，有个超时时间 TIMEOUT_MS， 试试把这个设置大一点

**Comment by huangcj-git** [comment]
> 看了下docker中的日志，显示 ![image](https://user-images.githubusercontent.com/17810922/234794008-923972b2-aee9-4af9-8930-32002d6deb22.png)
> 
> 应该不是我的网络问题，因为更新2.10.9之前是从来没有问题的。 而且我另一个chatgpt next web的套壳就没这个问题。
> 
> api用的是3.5,收费充值余额的


参照docker部署的参数，有个超时时间 TIMEOUT_MS， 试试把这个设置大一点
