### ISSUE TITLE
提问Sql语句会报错

### ISSUE THREAD

**Issue by keaiye** [Chanzhaoyu/chatgpt-web#162]
Request failed with status code 403
![image](https://user-images.githubusercontent.com/43440669/221810229-6ecdc61a-ee47-41d3-891a-cd455b628aad.png)

**Comment by pzve** [comment]
> Request failed with status code 403 ![image](https://user-images.githubusercontent.com/43440669/221810229-6ecdc61a-ee47-41d3-891a-cd455b628aad.png)

不是报错，是你没权限

**Comment by GH6324** [comment]
是你的服务器被Ban了而已

**Comment by keaiye** [comment]
> 是你的服务器ip被Ban了而已

问其他的东西是可以回答的，发sql语句就会403

**Comment by Chanzhaoyu** [comment]
到了晚上不会太稳定

**Comment by keaiye** [comment]
找到问题了，使用frp穿透的公网地址访问，然后提问sql语句就会403，其他内容就没问题。使用内网地址访问没问题
