### ISSUE TITLE
Caddy2反代后请求路径不对

### ISSUE THREAD

**Issue by jialinjun** [Chanzhaoyu/chatgpt-web#1620]
主要是为了实现: 访问 https://example.com/chatgpt -> http://localhost:3002

目前Caddy配置如下 (这里8080是因为配置了xray代理, 代理会回落到caddy的8080) :
```
:8080 {
    root * /usr/share/caddy
    file_server
    handle_path /chatgpt {
      reverse_proxy localhost:3002
    }
}
```
现在的问题是, 访问https://example.com/chatgpt, 页面一致处于加载状态: 
![image](https://user-images.githubusercontent.com/19832380/234804912-f73a7f52-5c89-4d75-84c9-3571f1f7e8d3.png)

F12看了下:
发现https://example.com/chatgpt是可以访问的:
![image](https://user-images.githubusercontent.com/19832380/234805246-73b156e3-13c5-4a14-8af2-a2fafbe02898.png)

但是,后面的js和css, 访问路径不对 
![image](https://user-images.githubusercontent.com/19832380/234805939-ad7e9402-b8e3-4ae8-9932-c636d41f87c5.png)

不知应如何修改? 需要修改应用代码么. 谢谢!

**Comment by lemonwan** [comment]
你这等于是在项目地址前加了一个前缀，但是拿资源的时候又去了你的file_server指定的root目录去找了。最好的办法就是，加个二级域名，可以完美解决问题，我也是用caddy部署的。
