### ISSUE TITLE
 reason: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by lancyJD** [Chanzhaoyu/chatgpt-web#1625]
FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established
最新代码。这是什么问题啊

**Comment by guinanlin** [comment]
+1 晚上我这边也报了。

**Comment by jiehuo666** [comment]
解决了吗？什么原因阿

**Comment by 2020-1998** [comment]
request to https://api.openai.com/v1/chat/completions failed  请问你这边解决这个问题了嘛

**Comment by zhangchengwen629** [comment]
是不是节点被ban了
