### ISSUE TITLE
欢迎各位大佬提供更新accesstoken的办法

### ISSUE THREAD

**Issue by kwingart** [Chanzhaoyu/chatgpt-web#1628]
老的报过期，新的不知道去哪里更新。
GitHub上能找到的办法都试了，无痕流量，换机场，网页源码，官方给我反馈的都是老的。但是老的又报错。 ChatGPTError: ChatGPT error 401: {"errorMessage":"Access token has expired."}

**Comment by huangwb8** [comment]
@kwingart 

OpenAI的Access Token可以通过访问 https://chat.openai.com/api/auth/session （返回的json文件中有一个accessToken字段）或者F12自己在application里找。

更多细节可关注我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by HHhne** [comment]
[https://github.com/acheong08/OpenAIAuth](url) 目前已能工作，需要注意VPS不能是被限制地区的。

**Comment by kwingart** [comment]
> @kwingart
> 
> 你在浏览器里成功登陆后， OpenAI的Access Token可以通过访问 https://chat.openai.com/api/auth/session （返回的json文件中有一个accessToken字段）或者F12自己在application里找。
> 
> 更多细节可关注我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

这个网站返回的，一直是同样得一个token。而这个token，我用在chatgpt-web里面就报过期的错误。
我的问题是，怎么更新（或者说强制更新）自己的accesstoken。。。。。。

**Comment by kwingart** [comment]
> https://github.com/acheong08/OpenAIAuth 目前已能工作，需要注意VPS不能是被限制地区的。
我的是国内vps，能通过clash出海。。。
看了，只有源码不会用。是go语言么？
我只有linux vps，能说具体点怎么用么？而且，会不会获得的token跟https://chat.openai.com/api/auth/session 这里拿到的一样，如果一样，对我来说没用。这个token在chatgpt-web里面报错了。说是过期了ChatGPT error 401: {"errorMessage":"Access token has expired."}

**Comment by xiaosaaaa** [comment]
不是你的token过期了，是本项目原来的代理服务器过期了吧。国内的服务器需要通过代理访问openai，之前默认的代理服务器过期了，你换个代理服务器或者你重新部署最新版。

**Comment by tankxiaodi** [comment]
> https://github.com/acheong08/OpenAIAuth 目前已能工作，需要注意VPS不能是被限制地区的。

我试了这个. 提升需要JavaScript验证浏览器, 看来被"识破"了.
