### ISSUE TITLE
假设我想把每个用户的conversation保存到数据库中...

### ISSUE THREAD

**Issue by helperAI** [Chanzhaoyu/chatgpt-web#163]
1、不知道是不是有这个开发计划？
2、如果没有，我希望自己来实现，有没有大牛提供一些思路和建议。
再次感谢分享这么好的东东方便我们学习和使用。

**Comment by Chanzhaoyu** [comment]
这个涉及到数据库的内容，不好放在项目里面，只能用自己的后端语言自行开发。

目前开发的目标可能是做整套的前端用户页面（登录之内的），方便大家做对外项目

**Comment by helperAI** [comment]
谢谢，用户登录会做吗？
另外如果我们自己实现，我们是在每一次提问和收到回复的时候去upsert数据库还是和pinia的状态同步比较好？我有点不太熟悉。感谢

**Comment by Chanzhaoyu** [comment]
> 谢谢，用户登录会做吗？
> 另外如果我们自己实现，我们是在每一次提问和收到回复的时候去upsert数据库还是和pinia的状态同步比较好？我有点不太熟悉。感谢

用 pinia 的原因是为了和本地同步，如果你改成数据库获取会话记录，其实可以把很多前端代码删除，比如新增、删除这种完全可以用接口代替。

**Comment by helperAI** [comment]
是的，但是目前的前端处理数据也有好处，感觉响应很快，数据库是不是只有在本地缓存丢失才从服务器获得这些聊天历史记录。
否则数据库如果每一个字都要去更新，这个应该是没有必要的。肯定要保留这个功能。等到完全显示完整后，再触发执行一次数据库的upsert操作是不是更加合理？
