### ISSUE TITLE
可否加入Azure Openai的选择？

### ISSUE THREAD

**Issue by sissimonster** [Chanzhaoyu/chatgpt-web#1631]

**Comment by Axe-l** [comment]
坐等

**Comment by renwofei423** [comment]
+1

**Comment by VectorZhao** [comment]
+1

**Comment by irmowan** [comment]
Use this one as a proxy:  https://github.com/stulzq/azure-openai-proxy

**Comment by seanshb** [comment]
坐等

**Comment by kongpf8848** [comment]
写了一个Azure代理程序，同时也修复了Azure OpenAI不支持打字效果的问题，[https://github.com/kongpf8848/azure-openai-proxy](https://github.com/kongpf8848/azure-openai-proxy)
