### ISSUE TITLE
[ 求助 ]  在根目录pnpm dev后出现了Error: connect ECONNREFUSED 127.0.0.1:3002

### ISSUE THREAD

**Issue by arthur19q3** [Chanzhaoyu/chatgpt-web#1632]
> chatgpt-web@2.11.0 dev /opt/chatgpt-web
> vite

  VITE v4.2.0  ready in 342 ms

  ➜  Local:   http://localhost:1002/
  ➜  Network: http://192.168.1.3:1002/
  ➜  press h to show help
5:02:03 PM [vite] http proxy error at /session:
Error: connect ECONNREFUSED 127.0.0.1:3002
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1532:16)
5:02:03 PM [vite] http proxy error at /session:
Error: connect ECONNREFUSED 127.0.0.1:3002
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1532:16) (x2)

下面是我的**env**设置

```

# OpenAI API Base URL - https://api.openai.com
OPENAI_API_BASE_URL= https://api.openai.com

# OpenAI API Model - https://platform.openai.com/docs/models
OPENAI_API_MODEL=gpt-3.5-turbo

# set `true` to disable OpenAI API debug log
OPENAI_API_DISABLE_DEBUG= true

# Reverse Proxy - Available on accessToken
# Default: https://ai.fakeopen.com/api/conversation
# More: https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
API_REVERSE_PROXY= https://ai.fakeopen.com/api/conversation

# timeout
TIMEOUT_MS=20000

# HTTPS PROXY
HTTPS_PROXY= https://127.0.0.1:7890

```

**Comment by arthur19q3** [comment]
原来前端后端是分开的, 搞定了.

**Comment by weilun0510** [comment]
> https://127.0.0.1:7890

怎么搞定的
