### ISSUE TITLE
用Debian系统搭建的docker-compose，请问日志在哪里查询

### ISSUE THREAD

**Issue by shenxianbu4** [Chanzhaoyu/chatgpt-web#1635]
用的Debian系统搭建的docker-compose，请问日志在哪里查询

**Comment by huangwb8** [comment]
@shenxianbu4 

可以在docker-compose.yml文件中使用这个命令：

```bash
docker-compose logs -f
```

你也可以安装[Portainer](https://blognas.hwb0307.com/linux/docker/487)在一个GUI里面查看某个容器的运行日志。

感兴趣可以看看我之前对Docker compose的科普《 [Docker系列 了解Docker Compose的配置文件](https://blognas.hwb0307.com/linux/docker/3880)》以及 chatgpt-web 的安装教程《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》。
