### ISSUE TITLE
这个代理，你们能用么？https://ai.fakeopen.com/api/conversation

### ISSUE THREAD

**Issue by kwingart** [Chanzhaoyu/chatgpt-web#1636]
我这老报错， 这是chatgpt-web 启动后，我与chatgpt互动后的报错：ChatGPTError: ChatGPT error 404: {"detail":{"message":"Conversation not found","code":"conversation_not_found"}}

这是我用浏览器直接访问https://ai.fakeopen.com/api/conversation的截图
![image](https://user-images.githubusercontent.com/20697608/235485702-3fce4193-0b52-4ac4-9512-81261fdb0f0b.png)

我的配置
![image](https://user-images.githubusercontent.com/20697608/235486336-60009ee1-2f33-4b87-92be-ba72527bd8a4.png)
最下面的proxy打开关闭都是报一样错。
我一直不明白这个proxy是用来干嘛的，有懂的解释下么？
谢谢各位大神。

**Comment by kwingart** [comment]
BTW: http://172.17.0.1:7890是本机上的魔法。

**Comment by huangwb8** [comment]
@kwingart 

![image](https://user-images.githubusercontent.com/35643122/235548000-c799220b-6656-4794-93c7-6ae05883b249.png)

具体见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by gmksbk** [comment]
代理地址换成外网vps的ip，或者本机做网关，代理留空

**Comment by kwingart** [comment]
其实我是想这么搞，我有魔法，也能访问到openai.com ,不想用warp，不知是否可行？  但是会在第三步报错

1，在本机上安装魔法，目前已经测试OK. 于是有了http://172.17.0.1:7890

2，起go-chatgpt-api:配置如下，也见到Welcome to ChatGPT，说明OK
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    # legacy是依赖chatgpt-proxy-server的，我个人测试比较稳定
    image: linweiyuan/go-chatgpt-api:legacy
    ports:
      - **8082**:8080 # 宿主机8080端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=http://172.17.0.1:7890
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped

3，起chatgpt-web,配置如下，但是，在web页面与gpt互动时，总是有报错，不知如何解决
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 0.0.0.0:7679:3002
    environment:
      OPENAI_ACCESS_TOKEN: 完整的accesstoken
      API_REVERSE_PROXY: http://172.17.0.1:**8082**/conversation
      AUTH_SECRET_KEY: 我的password
      MAX_REQUEST_PER_HOUR: 0
      TIMEOUT_MS: 60000

报错如下：
 **FetchError: request to http://172.17.0.1:8082/conversation failed, reason: read ECONNRESET**
app_1  |     at ClientRequest.<anonymous> (file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:108:11)
app_1  |     at ClientRequest.emit (node:events:525:35)
app_1  |     at Socket.socketErrorListener (node:_http_client:502:9)
app_1  |     at Socket.emit (node:events:525:35)
app_1  |     at emitErrorNT (node:internal/streams/destroy:151:8)
app_1  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
app_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
app_1  |   type: 'system',
app_1  |   errno: 'ECONNRESET',
app_1  |   code: 'ECONNRESET',
app_1  |   erroredSysCall: 'read'
app_1  | }


谢谢大神，帮忙看看。
 @gmksbk

**Comment by kwingart** [comment]
![image](https://user-images.githubusercontent.com/20697608/235589506-c28d4049-5a80-44e9-acac-4b4551e018ba.png)

**Comment by gmksbk** [comment]
这是反代出问题了，建议改为默认：http://go-chatgpt-api，不要用本机IP

**Comment by huangwb8** [comment]
@kwingart 

如果还不行，有几个方面可以考虑下：

+ 端口号是否都已经在防火墙放行？

+ 你的clash是用docker安装的？ 是否确定`http://172.17.0.1:7890/`可用？注意，我是说地址可用，它与clash可用是两码事

+ 你确定你的反向代理和clash是处于同一个网段？

方便的话可以加群 https://t.me/benszhub ，有时间间我可以帮你远程瞄一下。 自备todesk等远程软件即可。

**Comment by kwingart** [comment]
感谢 @huangwb8 ,搞掂了。

**Comment by juggli** [comment]
@kwingart 你好，请问下，咋搞定的，我这也遇到了。
