### ISSUE TITLE
https成功了,怎么样把http自动定向到https

### ISSUE THREAD

**Issue by gygy** [Chanzhaoyu/chatgpt-web#1638]
没使用docker , 部署方式:
 服务器下面 直接运行 sh start.sh

通过NPM 进行设置https成功了,  但同一个端口http访问 不会重定向到 https.

**Comment by 1130600015** [comment]
> 没使用docker , 部署方式: 服务器下面 直接运行 sh start.sh
> 
> 通过NPM 进行设置https成功了, 但同一个端口http访问 不会重定向到 https.

我没用npm，直接用的nginx，就是80端口的时候转发下，不会就问chatgpt啊 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/67859663/236490085-5bc1f1ee-a8f9-404c-9895-3967aed600ed.png">

**Comment by x28622930** [comment]
> > 没使用docker , 部署方式: 服务器下面 直接运行 sh start.sh
> > 通过NPM 进行设置https成功了, 但同一个端口http访问 不会重定向到 https.
> 
> 我没用npm，直接用的nginx，就是80端口的时候转发下，不会就问chatgpt啊 <img alt="image" width="387" src="https://user-images.githubusercontent.com/67859663/236490085-5bc1f1ee-a8f9-404c-9895-3967aed600ed.png">

直接linux的下302就行了。然后配置本地转发就OK了
