### ISSUE TITLE
泄露问题

### ISSUE THREAD

**Issue by hyyxiaoluo** [Chanzhaoyu/chatgpt-web#1639]
![image](https://user-images.githubusercontent.com/102205671/235591329-19cbc07c-2b54-4013-8719-c553c45f2fc2.png)

自己在railway上面使用的apikey部署的项目，也没告诉任何人key的自己的网址，喵的一段时间没看再上去发现自己的key的余额没了，统计里面看图在几天内直接呈指数蹭蹭涨，一天上百请求，每条10000左右的token，我想问有没有遇到和我类似的，这他妈的是哪个地方出问题了，感觉好不安全啊，害怕

**Comment by huangwb8** [comment]
@hyyxiaoluo 

如果你不是来搞事情的话。。。

可能被人扫描了；没有设置密码或者只是用弱密码；有其它泄露key的危险操作而不自知；等等。 

最后，别人就用`http://ip:端口号`访问了你的chatGPT喽。

**Comment by hyyxiaoluo** [comment]
之前是不想麻烦，没设置密码，喵的，怕了，反正是现在额度没了，用OPENAI_ACCESS_TOKEN慢慢用

**Comment by huangwb8** [comment]
> 之前是不想麻烦，没设置密码，喵的，怕了，反正是现在额度没了，用OPENAI_ACCESS_TOKEN慢慢用

连这点安全意识都没有就敢搭建公共服务，吃亏也只能忍了 Σ( ° △ °|||)︴ 

下次注意吧
