### ISSUE TITLE
Access Token 消息不完成

### ISSUE THREAD

**Issue by huoshicang** [Chanzhaoyu/chatgpt-web#1641]
![image](https://user-images.githubusercontent.com/74391377/235895995-def66f2b-c9dd-4f8c-914a-0142827ca606.png)
反代：https://ai.fakeopen.com/api/conversation
TIMEOUT_MS：0
消息显示不完整，但是https://chat.openai.com/显示完整

**Comment by xiaosaaaa** [comment]
代理的问题吧，自建一个

**Comment by jh410** [comment]
我建议用大厂的云函数自建

**Comment by marujun** [comment]
> 我建议用大厂的云函数自建

请教一下自建反代的话有哪些比较好的开源项目？
