### ISSUE TITLE
api key过期之后，使用OPENAI_ACCESS_TOKEN还能继续访问吗

### ISSUE THREAD

**Issue by JankinHou** [Chanzhaoyu/chatgpt-web#1643]
api key 免费的18美元额度已经过期。
官网上还能用，web api也可以使用吗？
配置OPENAI_ACCESS_TOKEN就好了么

**Comment by huangwb8** [comment]
@JankinHou  

可以试试Access Token，它是免费的，虽然与API相比有一些缺陷。

具体的讨论和方法可以见我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

有不懂可以加群提问：  https://t.me/benszhub

**Comment by hjkl950217** [comment]
@huangwb8 感谢老哥

**Comment by surperzcj** [comment]
@huangwb8 老哥，chat4 的 Access Token 支持吗？需要改哪些参数？

**Comment by huangwb8** [comment]
> @huangwb8 老哥，chat4 的 Access Token 支持吗？需要改哪些参数？

你可以试试啊，直接在网页设置里选一下模型。 原项目我没怎么用过，不好说。

**Comment by hjkl950217** [comment]
@Xyy-tj 这个也是一个不错的思路

**Comment by JankinHou** [comment]
> 我个人觉得去买一些白号比较方便，我自己用的少，一个月四个5刀额度的白号就可以了，不过就是需要时不时换一下apikey

白号哪里能买呢？

**Comment by Xyy-tj** [comment]
> > 我个人觉得去买一些白号比较方便，我自己用的少，一个月四个5刀额度的白号就可以了，不过就是需要时不时换一下apikey
> 
> 白号哪里能买呢？

plus的群里就有，很便宜的。或者你可以加我zyfan_97

**Comment by One1209** [comment]
> > > 我个人觉得去买一些白号比较方便，我自己用的少，一个月四个5刀额度的白号就可以了，不过就是需要时不时换一下apikey
> > 
> > 
> > 白号哪里能买呢？
> 
> plus的群里就有，很便宜的。或者你可以加我zyfan_97

搜不到你的微信呀

**Comment by Xyy-tj** [comment]
> 

微信给错了hhh不好意思，zy_fan97
