### ISSUE TITLE
域名无法解析，你们遇到这个问题了吗

### ISSUE THREAD

**Issue by liujie329** [Chanzhaoyu/chatgpt-web#1649]
域名是在aliyun上购买的，域名指向 aws 的一个部署服务器，之前没问题，可以正常访问，现在遇到无法解析问题，见图：
![1](https://user-images.githubusercontent.com/11437703/236133511-008b948d-e0d4-415e-b0aa-ff33a0dfe7d2.jpg)

大家遇到这个问题了吗？怎么解决的？

**Comment by kenser** [comment]
看提示你域名已经被查封了。ChatGPT是主管部门明令禁止的！！！

**Comment by qinghuas** [comment]
可以参照以下 nginx 反向代理配置，这样就可以做到访问 your.domain.com/entry 才能进入，直接访问 your.domain.com 会 403 错误，避免被扫到

修改关键词 entry 就可以自定义进入的路径

```
location /entry {
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Host $host;
            proxy_pass         http://localhost:3002/;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }

        location /assets/ {
            rewrite ^/assets/(.*)$ /assets/$1 break;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Host $host;
            proxy_pass         http://localhost:3002/;                proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }

        location /api/ {
            rewrite ^/api/(.*)$ /api/$1 break;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Host $host;
            proxy_pass         http://localhost:3002/;                proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }
```

**Comment by HOMHOG** [comment]
> 可以参照以下 nginx 反向代理配置，这样就可以做到访问 your.domain.com/entry 才能进入，直接访问 your.domain.com 会 403 错误，避免被扫到
> 
> 修改关键词 entry 就可以自定义进入的路径
> 
> ```
> location /entry {
>             proxy_set_header   X-Real-IP $remote_addr;
>             proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header   Host $host;
>             proxy_pass         http://localhost:3002/;
>             proxy_http_version 1.1;
>             proxy_set_header   Upgrade $http_upgrade;
>             proxy_set_header   Connection "upgrade";
>         }
> 
>         location /assets/ {
>             rewrite ^/assets/(.*)$ /assets/$1 break;
>             proxy_set_header   X-Real-IP $remote_addr;
>             proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header   Host $host;
>             proxy_pass         http://localhost:3002/;                proxy_http_version 1.1;
>             proxy_set_header   Upgrade $http_upgrade;
>             proxy_set_header   Connection "upgrade";
>         }
> 
>         location /api/ {
>             rewrite ^/api/(.*)$ /api/$1 break;
>             proxy_set_header   X-Real-IP $remote_addr;
>             proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header   Host $host;
>             proxy_pass         http://localhost:3002/;                proxy_http_version 1.1;
>             proxy_set_header   Upgrade $http_upgrade;
>             proxy_set_header   Connection "upgrade";
>         }
> ```

你好，我现在docker里面还部署了其他服务，想用nginx同时反向代理gpt-web和另外一个服务，如果如上设置location会和另外一个服务有冲突，因为另外一个服务会有同名的路径，这个问题有解吗

**Comment by turbobin** [comment]
分享一个**不需要购买域名，不需要搞域名备案**的方式，使用github pages就可以直接部署：[https://github.com/turbobin/chatbot](https://github.com/turbobin/chatbot)

**Comment by tech1502** [comment]
遇到过，有偿解决
