### ISSUE TITLE
想问下server端在服务器上是如何打包部署的？

### ISSUE THREAD

**Issue by jianingguo** [Chanzhaoyu/chatgpt-web#165]
想问下server端在服务器上是如何打包部署的？

**Comment by Chanzhaoyu** [comment]
复制 `serive` 文件夹，安装依赖，`pnpm start` 或者运行 `pnpm build` 再 `pnpm prod`

**Comment by jianingguo** [comment]
> 复制 `serive` 文件夹，安装依赖，`pnpm start` 或者运行 `pnpm build` 再 `pnpm prod`

OK，👍，谢谢
