### ISSUE TITLE
为什么配置为gpt-4模型后它还是说自己是gpt3呢 一个月前是plus会员  gpt-4发邮件说已经申请通过了

### ISSUE THREAD

**Issue by M0Cube** [Chanzhaoyu/chatgpt-web#1658]

**Comment by x28622930** [comment]
那你后端模型参数没修改

**Comment by weareware** [comment]
> 那你后端模型参数没修改

我同样遇到了但是依旧不行，日志如下：

**Comment by weareware** [comment]
sendMessage (48 tokens) {
  max_tokens: 2048,
  model: 'gpt-4',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
    },
    {
      role: 'user',
      content: '你是gpt 3.5吗，只回答yes or no',
      name: undefined
    }
  ],
  stream: true
}

**Comment by zf670471** [comment]
> 
请问一下，你这个参数是在哪个文件中设置的呢

**Comment by 1130600015** [comment]
> 

你是docker部署就是去docker配置文件改啊，如果是分开部署的话，后端就去.env里更改

**Comment by xseruer** [comment]
模型并不知道自己的版本，所以无法通过直接询问版本号。当然，如果你在意的话角色设定的方式直接告诉它就是gpt-4版本，比如：
![image](https://user-images.githubusercontent.com/4255288/236590380-f4deb52c-5de0-4dd3-b7e7-0b36fdd19d3e.png)

**Comment by 15935856121** [comment]
> 请问docker配置文件的哪个字段可以更改回复限制，目前是已经通过了4的api申请

**Comment by x28622930** [comment]
> > 请问docker配置文件的哪个字段可以更改回复限制，目前是已经通过了4的api申请

我没用docker的 所以不是很清楚

**Comment by arkcool** [comment]
> 模型并不知道自己的版本，所以无法通过直接询问版本号。当然，如果你在意的话角色设定的方式直接告诉它就是gpt-4版本，比如： ![image](https://user-images.githubusercontent.com/4255288/236590380-f4deb52c-5de0-4dd3-b7e7-0b36fdd19d3e.png)

多谢提醒，我发现确实是gpt4，但是它会回答gpt3，要按照你的更改，实在感谢（我今天测试了下，我问它“为什么我亲生父母结婚的时候没有邀请我”，gpt3.5回答不上，但是它能回答上，看来确实是gpt4），再次感谢

**Comment by 15935856121** [comment]
> > > 请问docker配置文件的哪个字段可以更改回复限制，目前是已经通过了4的api申请
> 
> 我没用docker的 所以不是很清楚

那你用的哪种方式呀，可以修改返回长度嘛？

**Comment by CYLOL2019** [comment]
> > 请问docker配置文件的哪个字段可以更改回复限制，目前是已经通过了4的api申请
我跟你遇到了一样的问题，docker使用GPT4，长一点的问题就不能考虑上下文。

**Comment by CYLOL2019** [comment]
> > > > 请问docker配置文件的哪个字段可以更改回复限制，目前是已经通过了4的api申请
> > 
> > 
> > 我没用docker的 所以不是很清楚
> 
> 那你用的哪种方式呀，可以修改返回长度嘛？

我跟你遇到了一样的问题，docker使用GPT4，长一点的问题就不能考虑上下文。
