### ISSUE TITLE
[share]分享一下我基于这个框架搭建的免费使用服务

### ISSUE THREAD

**Issue by AllenLuosong** [Chanzhaoyu/chatgpt-web#1660]
###  体验密钥: Chaofen0423
> 注: 因使用的是免费的key,存在各种限制(如并发请求数不超过3,最大token数不超过1000),如出现服务异常请稍后再尝试,我看到异常后会第一时间处理
欢迎各位体验

**Comment by huangkezhao** [comment]
体验地址: http://aiassist.chat 不注册 不登陆 不广告 不关注 永久免费

**Comment by 1130600015** [comment]
> Chaofen0423

你这用的api key？ api key的方式共享出来网站，大佬.用用token吧，不用花钱的。

**Comment by huangkezhao** [comment]
> > Chaofen0423
> 
> 你这用的api key？ api key的方式共享出来网站，大佬.用用token吧，不用花钱的。

token体验不是很好

**Comment by codesdevs** [comment]
体验地址: http://s.wikll.com 不注册 不登陆 不广告 不关注 免费
