### ISSUE TITLE
期望功能：允许用户下拉选择模型版本，类似官方版本那样

### ISSUE THREAD

**Issue by xseruer** [Chanzhaoyu/chatgpt-web#1663]
比如配置参数OPENAI_API_MODEL允许支持逗号分隔输入2个或多个模型：OPENAI_API_MODEL=gpt-3.5-turbo,gpt-4
然后用户在前台上可以选择模型，因为gpt-4的成本比3.5高很多。

**Comment by zhaojie199512** [comment]
加一，这个功能挺实用的

**Comment by Berumotto1** [comment]
cy
