### ISSUE TITLE
今天发现这个软件严重封Key只要是用这个软件。封key。我试了两个Key...挂了

### ISSUE THREAD

**Issue by dakaca007** [Chanzhaoyu/chatgpt-web#1665]
服务器是新加坡。。。不要问任何简单问题。直接切入主题。这个软件造成封key。赶紧查问题。

**Comment by sunyyo** [comment]
美国服务器一直存活

**Comment by zcyxy1** [comment]
这和软件有啥关系？封key是你ip不干净吧，咋感觉GitHub上都是小白，我以为我是小白，也就1个月前现学现卖的开发一下。咋这才多久碰到好几个比我还白的啊。还是我理解错了

**Comment by adinxiang** [comment]
俄罗斯服务器，两个月了好好地呢

**Comment by qsc19971022** [comment]
这项目只是你key的载体，被封只能说你ip有问题，怪人项目，离谱

**Comment by tech1502** [comment]
来试试https://chatgpt.030987.xyz/

**Comment by zcyxy1** [comment]
> 



> 来试试 https://chatgpt.030987.xyz/

想问一下你这个版本是哪里来的 呀

**Comment by huangkezhao** [comment]
来试试 http://aiassist.chat 永久免费

**Comment by juzigithu** [comment]
感觉还是小白。api是需要代理，国内的服务器基本无用。香港台湾可能还能用用吧   代理现在还弄不懂 烦死了

**Comment by danran12** [comment]
同样服务器是新加坡我就用的好好的，估计是你人品差

**Comment by assassinliujie** [comment]
跟项目有毛线关系，要么你IP不干净要么你请求太多滥用了
