### ISSUE TITLE
你们服务器都是买的境外服务器嘛？

### ISSUE THREAD

**Issue by gjing1st** [Chanzhaoyu/chatgpt-web#1669]
通过什么方式实现服务器访问api.openai.com嘛

**Comment by AllenLuosong** [comment]
aws有美国服务可以试试

**Comment by huangwb8** [comment]
@gjing1st 

我用的是[RackNerd服务器](https://blognas.hwb0307.com/ad)，API和Access Token模式都可以正常运行。

具体安装教程见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by 15935856121** [comment]
> @gjing1st
> 
> 我用的是[RackNerd服务器](https://blognas.hwb0307.com/ad)，API和Access Token模式都可以正常运行。
> 
> 具体安装教程见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

你的这个能修改返回长度限制嘛？

**Comment by huangwb8** [comment]
> > @gjing1st
> > 我用的是[RackNerd服务器](https://blognas.hwb0307.com/ad)，API和Access Token模式都可以正常运行。
> > 具体安装教程见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> 
> 你的这个能修改返回长度限制嘛？

暂时没有发现此类参数。 平时使用似乎没有感觉到长度限制的影响很大。

**Comment by oysmile** [comment]
我是用家里群晖NAS搭建的，走代理，一切正常。

**Comment by hao-guocheng** [comment]
> @gjing1st
> 
> 我用的是[RackNerd服务器](https://blognas.hwb0307.com/ad)，API和Access Token模式都可以正常运行。
> 
> 整体安装教程见：[Docker系列基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

你这个文章里面的telegram，国内手机没办法注册吧。

**Comment by huangwb8** [comment]
> > @gjing1st
> > 我用的是[RackNerd服务器](https://blognas.hwb0307.com/ad)，API和Access Token模式都可以正常运行。
> > 整体安装教程见：[Docker系列基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> 
> 你这个文章里面的telegram，国内手机没办法注册吧。

国内手机没办法注册与telegram没有关系。  我之前是用国内手机的，可以注册。当然，我是很久以前注册的，可能现在有变化，这个就不太了解了。

**Comment by hao-guocheng** [comment]
> 



> > > @gjing1st
> > > 我用的是[RackNerd服务器](https://blognas.hwb0307.com/ad)，API和Access Token模式都可以正常运行。
> > > 整体安装教程见：[Docker系列基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> > 
> > 
> > 你这个文章里面的telegram，国内手机没办法注册吧。
> 
> 国内手机没办法注册与telegram没有关系。 我之前是用国内手机的，可以注册。当然，我是很久以前注册的，可能现在有变化，这个就不太了解了。

应该是了，现在点击发送验证码会提示连接不上。

**Comment by turbobin** [comment]
@gjing1st 腾讯云服务器+clash代理，很稳，域名也不需要买，直接用github托管，可以看看这个 https://github.com/turbobin/chatbot
