### ISSUE TITLE
timeout of 100000ms exceeded

### ISSUE THREAD

**Issue by xieqifei** [Chanzhaoyu/chatgpt-web#167]
在chatgpt高峰期等待chatgpt做出回应的时间通常比较长，他的逐字生成答案的时间也比较长。我多次遇到这种情况，在chatgpt正在回复且内容在变化时，timeout出现了，并且将我之前收到的答案全部删除。是否有办法增加timeout的时长或者关闭它，至少保留已生成的答案。使用的是accesstoken。

**Comment by Chanzhaoyu** [comment]
下个版本修正，保留已有回答

**Comment by xiabill** [comment]
坐等更新了，也是遇到这个情况

**Comment by Quantatirsk** [comment]
同样遇到这个问题

**Comment by xieqifei** [comment]
目前我的解决办法是，在项目环境变量里添加一个变量_TIMEOUT\_MS=600000_
或者在server目录下的_.env_文件里修改此变量。
这样timeout不会出现在前端对话框里。但是当对话内容更新大概一分多钟时，对话会中断。这是由于前段请求超时。
解决办法是修改_/src/api/index.ts_文件里34到39行内容为
```

 return post<T>({
    url: '/chat-process',
    data: { prompt: params.prompt, options: params.options },
    signal: params.signal,
    onDownloadProgress: params.onDownloadProgress,
    timeout:600000,
  })

```
这里修改前端请求超时为10分钟。

**Comment by ludashi2020** [comment]
最好是超时后不收回已经回答的内容，然后输入“继续”，让它接着回答就更好了
