### ISSUE TITLE
本地docker部署，走代理，出现错误:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by zxhdaniel** [Chanzhaoyu/chatgpt-web#1671]
启动命令
docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=xx -e HTTPS_PROXY=http://`ipconfig getifaddr en0`:1085 chenzhaoyu94/chatgpt-web

报错：
request to https://api.openai.com/v1/chat/completions failed, reason: write EPROTO 38BB2C2BF47F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 40

只有我一个人遇到这种错误吗？

**Comment by oysmile** [comment]
检查代理SSL证书是否正常，监测中间证书是否补全。看报错似乎并未设置成代理？

**Comment by zxhdaniel** [comment]
> 检查代理SSL证书是否正常，监测中间证书是否补全。看报错似乎并未设置成代理？

设置成代理了，如果没设置代理是会超时的

**Comment by oysmile** [comment]
我自建代理也出现过api ssl问题，后面检查发现反代理的ssl中间证书未补全。

**Comment by zxhdaniel** [comment]
> 我自建代理也出现过api ssl问题，后面检查发现反代理的ssl中间证书未补全。

我这个是正向代理，就是mac上装的Clash

**Comment by Solituderr** [comment]
用socks
