### ISSUE TITLE
我部署在国内服务器，请问有什么风险吗？

### ISSUE THREAD

**Issue by wleelw** [Chanzhaoyu/chatgpt-web#1673]
目前正常进行访问，能够进行提问

**Comment by xiananliu** [comment]
账号会被封

**Comment by 9527-bit** [comment]
> 目前正常进行访问，能够进行提问

![image](https://user-images.githubusercontent.com/63514538/236970015-01fe328c-d560-43ee-b398-1b0dceab789e.png)

**Comment by wleelw** [comment]
> > 目前正常进行访问，能够进行提问
> 
> ![image](https://user-images.githubusercontent.com/63514538/236970015-01fe328c-d560-43ee-b398-1b0dceab789e.png)

这个情况没有遇到，我已经把项目删除了

**Comment by etmorefish** [comment]
部署在国内，你不挂代理肯定不能访问得了接口的，挂了代理，服务器提供商会封你得服务器，本人的腾讯云服务器被封了，麻烦

**Comment by wleelw** [comment]
> 部署在国内，你不挂代理肯定不能访问得了接口的，挂了代理，服务器提供商会封你得服务器，本人的腾讯云服务器被封了，麻烦

不会，可以用cf的worker

**Comment by MQPearth** [comment]
> 部署在国内，你不挂代理肯定不能访问得了接口的，挂了代理，服务器提供商会封你得服务器，本人的腾讯云服务器被封了，麻烦

我靠, 还有这说法.

**Comment by wleelw** [comment]
> > 部署在国内，你不挂代理肯定不能访问得了接口的，挂了代理，服务器提供商会封你得服务器，本人的腾讯云服务器被封了，麻烦
> 
> 我靠, 还有这说法.

我也不建议，别搞，我已经把备案撤销了，以后也不会再整了
