### ISSUE TITLE
Add talk to GPT features

### ISSUE THREAD

**Issue by kotobuki09** [Chanzhaoyu/chatgpt-web#1676]
I really like the talk-to GPT features from this repo [https://github.com/C-Nedelcu/talk-to-chatgpt](url), however, it currently only supports OpenAI officially. 

I would love to have an enhanced feature with a similar function like this on the current version chatgpt-web would be awesome!

**Comment by luckywangxi** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/pull/1182
this PR may help you

**Comment by kotobuki09** [comment]
> #1182 this PR may help you

I already tried this one. For some reason I can only implemented locally. Moreover, it's only have text to speech function not speech to text to make it more like conversation.
