### ISSUE TITLE
docker镜像出现[OpenAI] 提供错误的API密钥 | Incorrect API key provided

### ISSUE THREAD

**Issue by wp861010** [Chanzhaoyu/chatgpt-web#1677]
从6号晚上开始一直提示[OpenAI] 提供错误的API密钥 | Incorrect API key provided
换了Access token也不行

**Comment by hyrhyrh** [comment]
大哥 请问你是用什么方式部署的

**Comment by wp861010** [comment]
> 

群晖docker啊

**Comment by Azangxue** [comment]
我也出现了同样的问题

**Comment by a97242689** [comment]
[OpenAI] 提供错误的API密钥 | Incorrect API key provided

**Comment by 9527-bit** [comment]
应该是账号被锁了
