### ISSUE TITLE
小白求助大佬，服务器上 docker build -t 一直不成功，啥反应也没有，试了很多次

### ISSUE THREAD

**Issue by hyrhyrh** [Chanzhaoyu/chatgpt-web#1678]
执行命令后，一直停留在该界面。试了多次还是一样，是我服务器问题吗，用的aws ec2服务器
=> [frontend 8/8] RUN pnpm run build                                                                                                                           4546.5s
 => => # > chatgpt-web@2.11.0 type-check /app                                                                                                                          
 => => # > vue-tsc --noEmit                                                                                                                                            
 => => # > chatgpt-web@2.11.0 build-only /app                                                                                                                          
 => => # > vite build                                                                                                                                                  
 => => # vite v4.2.0 building for production...                                                                                                                        
 => => # transforming...

**Comment by hyrhyrh** [comment]
请问下载下来的项目，需要修改Dockerfile文件参数吗

**Comment by huangwb8** [comment]
@hyrhyrh  

既然会用docker，可以直接拉取镜像，不用自己build。

可以参考我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

有问题可以加群和大家讨论： https://t.me/benszhub

**Comment by hyrhyrh** [comment]
好的谢谢

**Comment by hyrhyrh** [comment]
> @hyrhyrh
> 
> 既然会用docker，可以直接拉取镜像，不用自己build。
> 
> 可以参考我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
> 
> 有问题可以加群和大家讨论： https://t.me/benszhub

好的，谢谢
