### ISSUE TITLE
我就想问问nginx怎么配置流响应，我的都是等待一次性全部返回

### ISSUE THREAD

**Issue by ping138338438** [Chanzhaoyu/chatgpt-web#168]
我就想问问nginx怎么配置流响应，我的都是等待一次性全部返回。
我的宝塔搭建的，web服务器nginx。

**Comment by Chanzhaoyu** [comment]
你在 issue 里面搜一下

**Comment by hnuzhoulin** [comment]
参照 https://github.com/Chanzhaoyu/chatgpt-web/issues/147 试一试

**Comment by leeggco** [comment]
同求，宝塔下没法流响应
