### ISSUE TITLE
有朋友将消息记录改成云同步的吗

### ISSUE THREAD

**Issue by string-new** [Chanzhaoyu/chatgpt-web#1681]
账号我已经改成支持多个账号的了，但是我看了消息记录好像比较复杂，在本地存储空间里面的字段比较多，有点不知道从哪里下手了

**Comment by string-new** [comment]
> @string-new
> 
> 有一个衍生项目是支持数据库保存用户信息的，具体见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。我自己也是用这个。

哦对了你的blog背景套图能交出来吗(doge)

**Comment by huangwb8** [comment]
> > @string-new
> > 有一个衍生项目是支持数据库保存用户信息的，具体见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。我自己也是用这个。
> 
> 哦对了你的blog背景套图能交出来吗(doge)

如果你有网站想要用我的随机图API，可以在博客留言板留下你的网站，我加入到白名单就可以使用。 至于直接下载下来传给你则不太合适。 有其它问题可以加我的[tg群](https://t.me/benszhub)交流 (ฅ´ω`ฅ)

**Comment by string-new** [comment]
> > > @string-new
> > > 有一个衍生项目是支持数据库保存用户信息的，具体见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。我自己也是用这个。
> > 
> > 
> > 哦对了你的blog背景套图能交出来吗(doge)
> 
> 如果你有网站想要用我的随机图API，可以在博客留言板留下你的网站，我加入到白名单就可以使用。 至于直接下载下来传给你则不太合适。 有其它问题可以加我的[tg群](https://t.me/benszhub)交流 (ฅ´ω`ฅ)

好的哈哈，后续用的到话再来问大佬

**Comment by wooveep** [comment]
[wooveep/chatserver-web](https://github.com/wooveep/chatserver-web)   这个使用的Golang做后端的写的，新增了本地知识库回答。
