### ISSUE TITLE
打字机效果没了

### ISSUE THREAD

**Issue by Zhao-sai-sai** [Chanzhaoyu/chatgpt-web#1684]
打字机效果没了，必须回答完毕才一下子出来完

**Comment by huangcj-git** [comment]
用了nginx吗，要把nginx的缓存关闭，readme中提到的

**Comment by rovertang** [comment]
location / {
        proxy_pass http://127.0.0.1:1002;  # 替换为你要代理的目标服务器地址和端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ssl_verify off;
        proxy_ssl_session_reuse off;
        proxy_buffering off;  # 禁用缓冲
    }
同#1685的case
