### ISSUE TITLE
nginx加了proxy_buffering off;之后重新打包，还是没有打印机效果

### ISSUE THREAD

**Issue by mrgAndysm** [Chanzhaoyu/chatgpt-web#1685]
nginx加了proxy_buffering off;之后重新打包，还是没有打印机效果，需等待全部结果才显示。

**Comment by rovertang** [comment]
参考：
    location / {
        proxy_pass http://127.0.0.1:1002;  # 替换为你要代理的目标服务器地址和端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ssl_verify off;
        proxy_ssl_session_reuse off;
        proxy_buffering off;  # 禁用缓冲
    }
测试结果：OK。注意有三个off

**Comment by jiangxiaohuai520** [comment]
nginx默认禁止ws协议，把ws协议开了就行了
