### ISSUE TITLE
建议增加一个模型训练，将covid-19最新的变种的库纳入训练

### ISSUE THREAD

**Issue by Mydtlwn** [Chanzhaoyu/chatgpt-web#1688]
信息参照库:
https://github.com/cov-lineages/pango-designation
参考文件1:
https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json
参考文件2:
https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt

**Comment by Mydtlwn** [comment]
目前国内对于covid-19变种信息的参照比较滞后，我希望能够将上述文件纳入到模型训练，以便大家能够通过这个及时了解信息，做出预判和心理准备。

**Comment by dqzboy** [comment]
目前已经没人关心这了

**Comment by Mydtlwn** [comment]
@dqzboy 至少做了之后，被别人引用之后，有些人可能会使用到。
