### ISSUE TITLE
各位查看一下容器的日志，端口是不是被扫了

### ISSUE THREAD

**Issue by ac1595** [Chanzhaoyu/chatgpt-web#1690]
搭着好玩的，被疯狂输出^^

**Comment by ac1595** [comment]
昨天发现直连不能用了，用代理还可以打开，直连就显示重置。以为端口被封，试一下国内外telnet 端口又是正常的，看了容器日志，妈耶，不知哪位IT大神在疯狂提问。。。

**Comment by huangwb8** [comment]
@ac1595 

该项目可以用docker进行搭建。 如果你使用容器（比如[Nginx Proxy Manager](https://blognas.hwb0307.com/linux/docker/604)）托管443端口，你可以将chatgpt-web搭建在 Nginx Proxy Manager 的内网中，不需要向宿主机映射端口。

如此一来，访问chatgpt-web的方法就只有`https://网址`，而无法通过`http://ip:端口`进行访问，因而可以从根本上避免端口扫描的隐患。

我在文章 [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201) 中也描述过类似的方案，感兴趣可以看看。

**Comment by ac1595** [comment]
> 



> @ac1595
> 
> 该项目可以用docker进行搭建。 如果你使用容器（比如[Nginx Proxy Manager](https://blognas.hwb0307.com/linux/docker/604)）托管443端口，你可以将chatgpt-web搭建在 Nginx Proxy Manager 的内网中，不需要向宿主机映射端口。
> 
> 如此一来，访问chatgpt-web的方法就只有`https://网址`，而无法通过`http://ip:端口`进行访问，因而可以从根本上避免端口扫描的隐患。
> 
> 我在文章 [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201) 中也描述过类似的方案，感兴趣可以看看。

谢谢哦，443给梯子用了。
