### ISSUE TITLE
https://ai.fakeopen.com/  反向代理的思路

### ISSUE THREAD

**Issue by qingfengtaizi** [Chanzhaoyu/chatgpt-web#1691]
问下 各位，项目实现反向代理 的思路是什么？有点模糊

**Comment by timiil** [comment]
same question

**Comment by bincooo** [comment]
一种是开plus，plus请求中携带的puid可以绕过很多限制。不知道现在还行不
另一种是开浏览器，将别人的请求通过浏览器中用注入的js发送请求。这个不稳定

**Comment by imldy** [comment]
Pandora项目，好像是绕过Cloudflare？
