### ISSUE TITLE
如何通过token的方式使用GPT4？

### ISSUE THREAD

**Issue by antiblahblah** [Chanzhaoyu/chatgpt-web#1695]
如题，plus账户，默认https://chat.openai.com/api/auth/session提取到的session总是3.5的，如何能拿到4的呢？

**Comment by Berumotto1** [comment]
同问

**Comment by Berumotto1** [comment]
> 如题，plus账户，默认[https://chat.openai.com/api/auth/session提取到的session总是3.5的，如何能拿到4的呢？](https://chat.openai.com/api/auth/session%E6%8F%90%E5%8F%96%E5%88%B0%E7%9A%84session%E6%80%BB%E6%98%AF3.5%E7%9A%84%EF%BC%8C%E5%A6%82%E4%BD%95%E8%83%BD%E6%8B%BF%E5%88%B04%E7%9A%84%E5%91%A2%EF%BC%9F)

将OPENAI_API_MODEL修改为gpt-4

**Comment by antiblahblah** [comment]
你这种是api方式，不是token方式吧。

> > 如题，plus账户，默认[https://chat.openai.com/api/auth/session提取到的session总是3.5的，如何能拿到4的呢？](https://chat.openai.com/api/auth/session%E6%8F%90%E5%8F%96%E5%88%B0%E7%9A%84session%E6%80%BB%E6%98%AF3.5%E7%9A%84%EF%BC%8C%E5%A6%82%E4%BD%95%E8%83%BD%E6%8B%BF%E5%88%B04%E7%9A%84%E5%91%A2%EF%BC%9F)
> 
> 将OPENAI_API_MODEL修改为gpt-4

**Comment by Berumotto1** [comment]
就是token的。session根本不区分3.5和4

**Comment by albort11** [comment]
@Berumotto1 大大，我是plus，还想使用联网功能，应该怎么改呢

**Comment by Berumotto1** [comment]
联网功能现在不是还没上线吗

**Comment by albort11** [comment]
> 联网功能现在不是还没上线吗

@Berumotto1 开plus之后可以联网啊，我是新手，刚弄好的plus，还有插件功能也有了

**Comment by LaoW7** [comment]
我也想问，就是access token的方式添加选择模型的功能，我在其他仓库看到有实现的。

**Comment by albort11** [comment]
感觉联网和插件不是模型，不是选择模型就可以解决的，accesstoken方式还是得模拟出，勾选那个联网选项的动作

**Comment by LaoW7** [comment]
> 感觉联网和插件不是模型，不是选择模型就可以解决的，accesstoken方式还是得模拟出，勾选那个联网选项的动作

https://github.com/acheong08/ChatGPT这个仓库实现了accesstoken选择模型甚至添加插件
