### ISSUE TITLE
request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 31.13.85.53:443

### ISSUE THREAD

**Issue by ouylzq** [Chanzhaoyu/chatgpt-web#1698]
在大陆被墙了吗，但是我看到有人的还可以用，有办法解决吗

**Comment by huangwb8** [comment]
1. 自建，具体教程见：  [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
2. 加代理
2. 换海外VPS

**Comment by fushengss** [comment]
怎么让项目请求走自建的v2ray代理

**Comment by calljia** [comment]
解决了吗？怎么解决的
