### ISSUE TITLE
centos7 服务运行一段时间自己退出

### ISSUE THREAD

**Issue by NUAAwanghe** [Chanzhaoyu/chatgpt-web#1701]
系统: centos7
最新版本

通过后台运行 pnpm dev 和pnpm start
运行几天后后台服务莫名其妙挂掉了

有人遇到过吗

**Comment by zhousgv5** [comment]
遇到过2次，不知道什么原因

**Comment by NUAAwanghe** [comment]
> 使用systemd管理
> 
> ```shell
> vim /etc/systemd/system/chatgpt-web.service
> 
> [Unit]
> Description=ChatGPT Web Service
> After=network.target
> 
> [Service]
> Type=simple
> User=root
> WorkingDirectory=/usr/share/nginx/html/service
> ExecStart=pnpm run start
> Restart=always
> ExecReload=/bin/kill -s HUP $MAINPID
> ExecStop=/bin/kill -s QUIT $MAINPID
> Restart=always
> TimeoutStopSec=5s
> 
> [Install]
> WantedBy=multi-user.target
> ```

老哥，我对web不是很熟，这个pnpm run start是在service目录下执行，那个前端页面怎么设置

**Comment by changhan1203** [comment]
> > 使用systemd管理
> > ```shell
> > vim /etc/systemd/system/chatgpt-web.service
> > 
> > [Unit]
> > Description=ChatGPT Web Service
> > After=network.target
> > 
> > [Service]
> > Type=simple
> > User=root
> > WorkingDirectory=/usr/share/nginx/html/service
> > ExecStart=pnpm run start
> > Restart=always
> > ExecReload=/bin/kill -s HUP $MAINPID
> > ExecStop=/bin/kill -s QUIT $MAINPID
> > Restart=always
> > TimeoutStopSec=5s
> > 
> > [Install]
> > WantedBy=multi-user.target
> > ```
> 
> 老哥，我对web不是很熟，这个pnpm run start是在service目录下执行，那个前端页面怎么设置

前端是静态文件，你放在服务器某个位置配置好请求转发就不用管了。service目录是后端服务，需要持续运行，用上面那个systemd可以在linux后台运行，或者使用Tmux也可以，Tmux可以在后台管理多个linux控制台窗口。

**Comment by changhan1203** [comment]
> > 使用systemd管理
> > ```shell
> > vim /etc/systemd/system/chatgpt-web.service
> > 
> > [Unit]
> > Description=ChatGPT Web Service
> > After=network.target
> > 
> > [Service]
> > Type=simple
> > User=root
> > WorkingDirectory=/usr/share/nginx/html/service
> > ExecStart=pnpm run start
> > Restart=always
> > ExecReload=/bin/kill -s HUP $MAINPID
> > ExecStop=/bin/kill -s QUIT $MAINPID
> > Restart=always
> > TimeoutStopSec=5s
> > 
> > [Install]
> > WantedBy=multi-user.target
> > ```
> 
> 老哥，我对web不是很熟，这个pnpm run start是在service目录下执行，那个前端页面怎么设置

前端是静态文件，你放在服务器某个位置配置好请求转发就不用管了。service目录是后端服务，需要持续运行，用上面那个systemd可以在linux后台运行，或者使用Tmux也可以，Tmux可以在后台管理多个linux控制台窗口。
