### ISSUE TITLE
感觉有人盗刷，更新了最新的image也还有

### ISSUE THREAD

**Issue by muxuan1978** [Chanzhaoyu/chatgpt-web#1706]
sendMessage (28 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.5,
  top_p: undefined,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are a helpful assistant that translates text.'
    },
    {
      role: 'user',
      content: '英译中：<p><strong>Result:</strong></p>',
      name: undefined
    }
  ],
  stream: true
}

**Comment by Nanford** [comment]
我也遇到响应的问题，我换了key还是会有

**Comment by muxuan1978** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/38503222/e39353ba-e129-4a2e-9b3e-c74f0848474a)

一直没停，刷了不少token

**Comment by liushanv** [comment]
看项目首页能设置密码呀

**Comment by ccdanpian** [comment]
我的也是在五一前后被盗用了5$多，已经换用其他的了

**Comment by guoxiangdaxia** [comment]
确实有暴漏key的风险，我也换了好几次，赶紧把项目停了吧。换一个可以登录验证的项目

**Comment by Special-Week** [comment]
请问搭建https站点也会有这个风险吗

**Comment by shouyong** [comment]
> 

一样的，项目本身对这部分不甚关注。

**Comment by swuecho** [comment]
https://github.com/swuecho/chat

可以部署我这个，需要登陆， 后端加入流控。 非信任用户流控弄0

目前没人反应盗用风险。
