### ISSUE TITLE
启动之后报错响应数据：request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by 03jia** [Chanzhaoyu/chatgpt-web#1709]

**Comment by wainyang** [comment]
request to https://ai.fakeopen.com/api/conversation failed, reason: Client network socket disconnected before secure TLS connection was established

加了代理也是报错

**Comment by wainyang** [comment]
> request to https://ai.fakeopen.com/api/conversation failed, reason: Client network socket disconnected before secure TLS connection was established
> 
> 加了代理也是报错

解决了,是科学上网的问题

**Comment by vintonHuang** [comment]
开启了代理就可以了嘛

**Comment by 2020-1998** [comment]
request to https://api.openai.com/v1/chat/completions failed    能拦截不让页面显示嘛

**Comment by learnmodest** [comment]
配了vscode的代理，不开全局也能跑了
