### ISSUE TITLE
ChatGPT error 403

### ISSUE THREAD

**Issue by no-today** [Chanzhaoyu/chatgpt-web#171]
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/34943822/222032501-233e7fb0-f181-4eda-bb2b-4b3664d6d5e8.png">

1. token 是有效的，没有发生变化。
2. 是服务器IP被Ban了吗？可是我浏览器开全局代理是可以访问的。
3. OpenAI识别出了浏览器请求和服务器请求的不一致，对服务器请求进行拦截？

**Comment by Chanzhaoyu** [comment]
开后端调试看一下，不过 403 就是超限了，一个小时之后才解除

**Comment by ludashi2020** [comment]
也有可能是你的api代理服务器把你ip屏蔽了

**Comment by ludashi2020** [comment]
公开的那个api代理服务器有频率限制

**Comment by ludashi2020** [comment]
公开的那个api代理服务器有频率限制

**Comment by no-today** [comment]
啥也没干下午试了一下又可以了，应该就是限流了。

**Comment by no-today** [comment]
题外话，我开了 Plus，照样限流，供其他人参考。

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/34943822/222056599-bc76a61b-cb47-442e-a509-f29f81934731.png">

**Comment by hncboy** [comment]
我也遇到了官网能访问，这里请求却是 403

**Comment by no-today** [comment]
> 我也遇到了官网能访问，这里请求却是 403

等着吧，我现在好了
