### ISSUE TITLE
请问有没有人把这个服务部署在Railway上，我的github账号不能用，不知道怎么操作

### ISSUE THREAD

**Issue by zhaoyuan020** [Chanzhaoyu/chatgpt-web#1710]
有没有人部署成功的，部署的地址能不能分享一下，国内无魔法可以访问吗？想体验。。。

**Comment by zhoayuan020gmail** [comment]
同求！！！

**Comment by zhaoyuan020** [comment]
> 同求！！！

握手。。。

**Comment by dqzboy** [comment]
国内服务器实现科学上网即可；这里是[一键部署脚本](https://github.com/dqzboy/ChatGPT)

**Comment by Azad-sl** [comment]
有，可以国内访问，github账号必须注册半年以上，不然就得绑卡

**Comment by zhoayuan020gmail** [comment]
> 有，可以国内访问，github账号必须注册半年以上，不然就得绑卡

兄弟，是不是可以输入我自己的api key就可以了，求地址啊，多谢了！

**Comment by zhaoyuan020** [comment]
> > 有，可以国内访问，github账号必须注册半年以上，不然就得绑卡
> 
> 兄弟，是不是可以输入我自己的api key就可以了，求地址啊，多谢了！

兄弟，地址发一下啊。
