### ISSUE TITLE
小白问一下大家，如何更改外部访问端口号

### ISSUE THREAD

**Issue by li7355608** [Chanzhaoyu/chatgpt-web#1712]
项目的外网默认访问方式是http://ip:1002
如何把1002端口更改为其他端口？

**Comment by li7355608** [comment]
部署方式是直接部署到服务器，没有进行打包

**Comment by mesfreeman** [comment]
如果你是 `pnpm dev` 方式启动的话，可以改 [vite.config.ts](https://github.com/Chanzhaoyu/chatgpt-web/blob/1cb5393b91d188d4906dbf9fa72bb1143de75df7/vite.config.ts#L36) 代码中的端口号来实现，但部署到服务器还是推荐还是打包方式。

**Comment by li7355608** [comment]
> 

OK，感谢帮助
