### ISSUE TITLE
有没有部署在软路由上，软路由开全局运行这个项目是否可行？

### ISSUE THREAD

**Issue by dksir47** [Chanzhaoyu/chatgpt-web#1714]
。。。

**Comment by huangwb8** [comment]
@dksir47 

如果你的软路由相关环境可以访问openai的官网，可以试试我的方案： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》中的“Access Token自建ChatGPT——在本地Linux系统自建反向代理”小节。 

API其实也是类似的，添加对应的Proxy就行。

**Comment by dksir47** [comment]
> @dksir47
> 
> 如果你的软件路径由相关环境可以访问openai的官网，可以试试我的方案：《[Docker系列基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》中的“Access Token自建ChatGPT——在本地Linux系统自建反向代理”小节。
> 
> API其实也是类似的，添加对应的Proxy就行。
我瞅瞅

**Comment by dksir47** [comment]
我瞅瞅

**Comment by jasontips** [comment]
完全没问题，用上api反代就行了
