### ISSUE TITLE
请问要改后端接口，需要该哪几个参数？

### ISSUE THREAD

**Issue by dimingchan** [Chanzhaoyu/chatgpt-web#1715]
Q: 如果只使用前端页面，在哪里改请求接口？
A: 根目录下 .env 文件中的 VITE_GLOB_API_URL 字段。

原来的.env文件内容如下：
# Glob API URL
VITE_GLOB_API_URL=/api
VITE_APP_API_BASE_URL=http://127.0.0.1:1003/

譬如我的api端口是 8787，那么是改成
VITE_GLOB_API_URL=/api
VITE_APP_API_BASE_URL=http://127.0.0.1:8787/
吗？

后端会访问 http://127.0.0.1:8787/api/session 吧？

为什么我改了之后，会提示url不正确？

**Comment by woodchen-ink** [comment]
vs code，搜索3002，批量改成你所需要的端口

**Comment by woodchen-ink** [comment]
VITE_GLOB_API_URL=http://127.0.0.1:8787/api

**Comment by woodchen-ink** [comment]
另一个无视

**Comment by woodchen-ink** [comment]
kook：https://kook.top/2HoPpe
欢迎一起交流，现在都没人😭
