### ISSUE TITLE
现在最新2.11.0版本还是会报模型的错误，要求给model参数

### ISSUE THREAD

**Issue by TravelingLee** [Chanzhaoyu/chatgpt-web#1718]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/81201812/728591d0-754c-46fd-9cc9-c5d298d80dd8)
我看了好多次commit，改了好多次都没改对

**Comment by Chanzhaoyu** [comment]
把 .env.example 复制一份改为 .env 文件
