### ISSUE TITLE
关于EventStream

### ISSUE THREAD

**Issue by lengyibai** [Chanzhaoyu/chatgpt-web#1721]
我也按照项目里使用了axios的onDownloadProgress方法来实现流式输出，在输出结束后使用controller.abort();来结束，页面上也正常显示了，但是奇怪的是，为什么在浏览器开发者工具-网络-EventStream为空，除了这个问题，其他一切正常，我看你们项目的EventStream直接就把输出内容显示出来了的。我想知道前端是否漏了哪个步骤，或者是后端的问题？
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/74140255/74d37254-bea4-4e3a-84fb-f0b0d2267b1d)
参考：https://qccq.cc
流式请求结束后，浏览器EventStream栏目为空

**Comment by diudiudiuu** [comment]
不知道,但是网站很是炫酷
