### ISSUE TITLE
请问是否可以增加多账号系统？分配不同账号不同模型权限？

### ISSUE THREAD

**Issue by darkice1** [Chanzhaoyu/chatgpt-web#1723]

**Comment by Berumotto1** [comment]
同问

**Comment by Kerwin1202** [comment]
https://github.com/Kerwin1202/chatgpt-web  这个项目有 ¯\_(ツ)_/¯

**Comment by woodchen-ink** [comment]
plus版本也有，chat.czl.net，不过收费的

**Comment by woodchen-ink** [comment]
kook：https://kook.top/2HoPpe
欢迎一起交流，现在都没人😭

**Comment by huangwb8** [comment]
@darkice1 

多谢 @Kerwin1202 大佬主持的开发工作，应该是最好的免费开源的ChatGPT类项目了！

从v2.13.0版本开始， [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 已经支持很多功能了，包括：**多用户登录/注册**、**数据库管理**、**对话云端保存和管理**、**敏感词管理**、**自定义提示词**、**多Key轮询**、**用户管理**、**自定义模型**等 。 

我之前也出了相关的教程，实时更新，安装和使用时有什么问题可以多多交流： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
