### ISSUE TITLE
宣传一波开发者的plus版本

### ISSUE THREAD

**Issue by woodchen-ink** [Chanzhaoyu/chatgpt-web#1725]
https://chat.czl.net
基于开发者的收费plus版本搭建，6月底前3.5免费，4限时免费，欢迎体验
开发者的plus版本还支持midjourney制图，我还没上。

**Comment by wwlmm** [comment]
你这还备案了。。。厉害 佩服

**Comment by woodchen-ink** [comment]
> 多少钱一套？

1500

**Comment by woodchen-ink** [comment]
kook：https://kook.top/2HoPpe
欢迎一起交流，现在都没人😭

**Comment by joy199703** [comment]
怎么联系搭建
