### ISSUE TITLE
可以只使用前端，不用后端吗

### ISSUE THREAD

**Issue by xiyuvi** [Chanzhaoyu/chatgpt-web#1727]
请问一下，我想只使用前端部分，直接调用api来请求，不用后端，应该怎么修改，感谢

**Comment by vintonHuang** [comment]
可以啊，注意看没有看起服务的接口报错，你就懂得改了

**Comment by swuecho** [comment]
可以参考我这个 golang的后端 https://github.com/swuecho/chat

前端基本一致
