### ISSUE TITLE
关于头像链接的问题

### ISSUE THREAD

**Issue by wuuuyifan** [Chanzhaoyu/chatgpt-web#1730]
我的Chrome浏览器 在此之前使用过我本地部署的chatgpt-web
我修改了setting内的头像链接，在我的Chrome浏览器内还是原头像。使用一个从未打开过本地部署的chatgpt-web的浏览器打开时，头像发生了变化。
我认为是Chrome存储了某些cookie？或者其他信息导致的，但是当我清除Chrome的数据 重新打开本地部署的chatgpt-web还是原头像。
有大佬知道是什么原因吗

**Comment by huangwb8** [comment]
@wuuuyifan  原始项目的后端要靠自己搞的。你可以使用 @Chanzhaoyu  的Plus版本： [Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)

或者像我一样，使用 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.13.0)，它使用MongoDB作为后端，可以认为是云端保存用户信息。 

这两种方式都可以解决你的需求。

**Comment by imldy** [comment]
> 我修改了setting内的头像链接

你修改的应该是服务器上的代码，功能为给本地没有头像链接的浏览器赋予默认头像链接。

> 在我的Chrome浏览器内还是原头像。

你本地有之前代码赋予的默认头像链接，所以新代码并不会执行，

> 我认为是Chrome存储了某些cookie？或者其他信息导致的

可以去F12删除application中的localstorage，找到头像链接并修改。

> 但是当我清除Chrome的数据 重新打开本地部署的chatgpt-web还是原头像。
有大佬知道是什么原因吗

未知

**Comment by assassinliujie** [comment]
自己修改下后端吧
