### ISSUE TITLE
大佬能不能加两个功能。

### ISSUE THREAD

**Issue by jt8823** [Chanzhaoyu/chatgpt-web#1732]
先谢谢大佬，我的ip已经被chat.openai.com封了，只能调用api使用，这个镜像非常好用
求能加入两个功能更好了
1:弄个能将某条聊天记录收藏
2:能把聊天记录的缓存保存在映射目录里面，而不是本地，这样其它设备也能共享聊天记录了

我的设备是群晖，使用的docker部署。

**Comment by huangwb8** [comment]
@jt8823 

你有两个选择：

+ 按教程《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》进行操作。

+ 使用大佬的另一个项目，地址为[Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)，非开源且付费（好像是1000多元/份？）

**Comment by wooveep** [comment]
@jt8823  看看我这个项目 https://github.com/wooveep/chatserver-web
