### ISSUE TITLE
关于该项目的网络安全风险

### ISSUE THREAD

**Issue by angrysoap** [Chanzhaoyu/chatgpt-web#1736]
freebuff的相关文章有详细介绍
https://www.freebuf.com/articles/network/366740.html

**Comment by Special-Week** [comment]
请问搭建的是https站点改了title开启了防火墙能规避这些问题吗。

我就昨天搭了个http站点就是给我们群里用，一天就用掉了2.7刀怪吓人的。吓得我急忙重置了apikey。

现在我在用nginx搭建https站点转发到127.0.0.1:1002，防火墙只放行22 80 443这样

**Comment by shouyong** [comment]
> 请问搭建的是https站点改了title开启了防火墙能规避这些问题吗。
> 
> 我就昨天搭了个http站点就是给我们群里用，一天就用掉了2.7刀怪吓人的。吓得我急忙重置了apikey。
> 
> 现在我在用nginx搭建https站点转发到127.0.0.1:1002，防火墙只放行22 80 443这样

项目本身的问题，要自行修改。  也不是很麻烦

**Comment by Nanford** [comment]
可以通过nginx反代理设置登陆校验，然后部署的时候只允许127.0.0.1:port访问，通过公网IP不能访问。具体可以自己找ChatGPT问一下怎么操作

**Comment by swuecho** [comment]
试试我的扩展版， 默认把 OPENAI_RATELIMIT=0 只对验证过的用户加流控就可以了。

https://github.com/swuecho/chat
