### ISSUE TITLE
分享一个chatgpt web api代理

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#174]
`https://chatgptapi.googlevideo.dev/api/conversation`
使用assentoken模式的把那个api 代理服务器填这个就好了。不好意思弄错了，有速率限制。40 req/min by IP。

**Comment by bluefrankey** [comment]
用api key的可以用吗？

**Comment by Chanzhaoyu** [comment]
我 ip 用的效果不好

**Comment by Chanzhaoyu** [comment]
> 用api key的可以用吗？

key 不需要

**Comment by ludashi2020** [comment]
> 用api key的可以用吗？

api key不需要用代理

**Comment by bluefrankey** [comment]
可为什么我用api key一直提示fetch failed

**Comment by ludashi2020** [comment]
或许是本地网络到api.openai.com这段超时了

**Comment by Chanzhaoyu** [comment]
> 可为什么我用api key一直提示fetch failed

用 `key` 的话一直都很稳定吧

**Comment by qiaohaoforever** [comment]
可以做多代理负载均衡吗？

**Comment by hnuzhoulin** [comment]
请问构建这个代理有什么要求吗？还是只要能访问openai的都可以，简单的socket5代理就行？

**Comment by ludashi2020** [comment]
> 请问构建这个代理有什么要求吗？还是只要能访问openai的都可以，简单的socket5代理就行？
不行的。反代的源码和配置被原作者删除了，目前弄不了。

**Comment by lhlxx2010** [comment]
> `https://chatgptapi.googlevideo.dev/api/conversation` 使用assentoken模式的把那个api 代理服务器填这个就好了。不好意思弄错了，有速率限制。40/Minute。

可以请教下具体怎么使用吗？
