### ISSUE TITLE
通过Docker部署的程序，查询日志时有办法看到具体的请求日期吗？

### ISSUE THREAD

**Issue by tanglu86** [Chanzhaoyu/chatgpt-web#1741]
我通过docker logs查看日志时能看到问答内容，但是看不到问答时间，现在需要排查问题不太方便

**Comment by huangwb8** [comment]
@tanglu86 

使用[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)是可以的，因为它有一个数据库后端。 具体见我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。

或者关注作者的Plus项目也行： [Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)
