### ISSUE TITLE
docker部署后怎么进入容器修改配置

### ISSUE THREAD

**Issue by Timqaq** [Chanzhaoyu/chatgpt-web#1742]
部署好后我想设置个访问密码，但是找不到配置文件

**Comment by huangwb8** [comment]
@Timqaq 

访问密码在docker-compose.yml里可以通过`AUTH_SECRET_KEY`确定。

你也可以关注一下本项目的一个分支 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) ，它有一个数据库后端，目前支持多用户登录/注册、数据库管理、对话云端保存和管理、敏感词管理、自定义提示词、多Key轮询、用户管理、自定义模型等。开源免费的！

具体教程可见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by 2020-1998** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/65844345/347aad7b-41b4-4ae9-94e5-ace29e7e8c95)
这个你们有遇到过嘛

**Comment by 2020-1998** [comment]
2023/5/31 12:00:03

request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 69.171.234.48:443

**Comment by Timqaq** [comment]
> @Timqaq
> 
> 访问密码在docker-compose.yml里可以通过`AUTH_SECRET_KEY`确定。
> 
> 你也可以关注一下本项目的一个分支 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) ，它有一个数据库后端，目前支持多用户登录/注册、数据库管理、对话云端保存和管理、敏感词管理、自定义提示词、多Key轮询、用户管理、自定义模型等。开源免费的！
> 
> 具体教程可见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

好的，谢谢

**Comment by Timqaq** [comment]
> ![image](https://user-images.githubusercontent.com/65844345/242158701-347aad7b-41b4-4ae9-94e5-ace29e7e8c95.png) 这个你们有遇到过嘛

没遇到过
