### ISSUE TITLE
使用docker部署时，如何暴露后端项目的端口

### ISSUE THREAD

**Issue by zhangupkai** [Chanzhaoyu/chatgpt-web#1751]
本地测试时，可以使用的不同的端口分别访问前端和后端。使用docker部署到服务器后，可以额外暴露后端端口吗，将后端服务提供给其他项目。

**Comment by Kerwin1202** [comment]
docker 部署 默认就一个端口 nginx 会转发倒后端  部署之后f12 看下请求，就有后端地址了

**Comment by intfish123** [comment]
-p ${你的主机端口}:${容器中的端口}
如把容器的8080端口映射到主机9000上, `docker run -p 9000:8080`
