### ISSUE TITLE
小白问题，在线等

### ISSUE THREAD

**Issue by flying0018** [Chanzhaoyu/chatgpt-web#1753]
使用docker部署应用，除了端口和API key以外的参数全部取默认，拉取镜像，打开网站后，报错：

对https://api.openai.com/v1/chat/completions的请求失败，原因：提供了无效的 SOCKS 代理详细信息。

请问该如何处理？

**Comment by 2020-1998** [comment]
在.env中配置scoks代理地址和代理端口
