### ISSUE TITLE
如何保护我的镜像网站，或者说设置验证登录还价

### ISSUE THREAD

**Issue by SkySpaceF** [Chanzhaoyu/chatgpt-web#1757]
比如进入网站后，必须输入密码才可以使用，以过滤简单的他人滥用

**Comment by LiberatorHg** [comment]
Nginx的Auth认证可以实现你说的简单过滤，或者不让其他人注册呗 关闭注册

**Comment by huangwb8** [comment]
@SkySpaceF 

基于MongoDB可实现多用户登录/注册、数据库管理、对话云端保存和管理、敏感词管理、自定义提示词、多Key轮询、用户管理、自定义模型等实用功能。 

教程详见： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》

**Comment by gougui** [comment]
最简单就是环境变量配置密码，AUTH_SECRET_KEY 访问权限密钥

**Comment by vintonHuang** [comment]
> @SkySpaceF
> 
> 基于MongoDB可实现多用户登录/注册、数据库管理、对话云端保存和管理、敏感词管理、自定义提示词、多Key轮询、用户管理、自定义模型等实用功能。
> 
> 教程详见： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》

多key轮询是什么意思

**Comment by huangwb8** [comment]
@vintonHuang 

就是你可以放多个Key，然后根据一些规则访问它们。这样可以支持比较大量的请求。

我知道有这个功能；但我的日常使用比较轻量，所以只用过1个key。

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/35643122/35873454-74df-4c03-9a79-f743b102e34c)
