### ISSUE TITLE
用代理访问一直报429错误

### ISSUE THREAD

**Issue by zzq0610** [Chanzhaoyu/chatgpt-web#1759]
报错如下，用阿里fc函数配的美国硅谷的也是一样的报错，你们没有遇到吗，怎么解决？
ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": null
}
}

**Comment by llc2214926** [comment]
同问，账号余额还有的

**Comment by boboanyko** [comment]
同问，官网可以使用，走api就一直429

**Comment by boboanyko** [comment]
同问，官网可以使用，走api就一直429 @zzq0610

**Comment by llc2214926** [comment]
好像是用openai密钥的方式请求就会这样，是官方服务器的问题。估计是资源不够用了都移给付费计划了吧

**Comment by zzq0610** [comment]
> 好像是用openai密钥的方式请求就会这样，是官方服务器的问题。估计是资源不够用了都移给付费计划了吧

就是说现在得开通pro才能继续调用么

**Comment by lpple** [comment]
同问。到底是哪里问题

**Comment by lpple** [comment]
我免费的API 一次没有用过，就是429

**Comment by ryankklam** [comment]
之前用是可以，后面一直不行，quota都正常，使用频率也不频繁，除了用openai密钥还有没有其他方式 ？
