### ISSUE TITLE
页面放到服务器以后，回答的问题不再是流式输出返回

### ISSUE THREAD

**Issue by li18833135474** [Chanzhaoyu/chatgpt-web#1762]
项目在本地跑，问的问题返回的结果是流式的一个个字写出来的，但是放到服务器上以后就需要一直等，等到结果全部返回才行，这是怎么回事，能不能解答一下，老哥

**Comment by vintonHuang** [comment]
同问，这是为什么呢？但是我看了请求返回体，类型是流对象啊

**Comment by li18833135474** [comment]
> 

你是在服务器上用的nginx吗，如果是的话看下你的nginx版本，是不是1.5以上，如果是的话在 server里加上这个	# 不缓存，支持流式输出
    proxy_cache off;  # 关闭缓存
    proxy_buffering off;  # 关闭代理缓冲
    chunked_transfer_encoding on;  # 开启分块传输编码
    tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
    tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
    keepalive_timeout 300;  # 设定keep-alive超时时间为65秒

这个是关闭缓存用流式输出的，加上重启一下就行了

**Comment by vintonHuang** [comment]
这个要加在哪里啊，有没有ngixn的文件配置贴出来看一下
