### ISSUE TITLE
Vercel 500 错误

### ISSUE THREAD

**Issue by Lopins** [Chanzhaoyu/chatgpt-web#1763]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/44494732/c1616e6c-42cd-41f6-8832-c1e2487f5d4a)

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/44494732/5932230c-8217-4fca-8549-1c7ff231595c)

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/44494732/90b1cd28-b32f-4910-8725-78c33715192f)

**Comment by yefeiyu** [comment]
same error
hope explains

**Comment by zhaobudaomingzi** [comment]
希望项目能早日支持vercel
