### ISSUE TITLE
ChatGPT error 429判断

### ISSUE THREAD

**Issue by Moment455** [Chanzhaoyu/chatgpt-web#1764]
调用频繁会返回：

ChatGPT error 429: {
"error": {
"message": "Rate limit reached for default-gpt-3.5-turbo in organization xxxxxxxxxxxx on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
"type": "requests",
"param": null,
"code": null
}
}

请问在哪里可以判断这个429错误码，并返回：API 请求配额超出限制，请稍后再试或联系管理员

**Comment by bbyamap** [comment]
同样问题

**Comment by swuecho** [comment]
node 后端处理， 应该在 chat api process 需要懂一点js
