### ISSUE TITLE
来自小白的成功，终于弄好了，打包成dits后也能访问了。不再是500错误了

### ISSUE THREAD

**Issue by kdcms** [Chanzhaoyu/chatgpt-web#1767]
终于不再是500的错误了。

所有配置完成，先打包成dist

然后新建一个网站，目录指向dist

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/128931267/f01d8f17-f26c-4e83-bb7b-be919813ead5)

/
```
location /api {
	proxy_set_header   X-Real-IP $remote_addr; #转发用户IP
        proxy_pass http://127.0.0.1:3002;
       proxy_ssl_verify off;
       proxy_ssl_session_reuse off;
       proxy_buffering off; # 禁用缓冲
    }
``` 

增加一个配置参数

这样新建后，打开网站是500错误，咋办呢，发现了一下，这个是因为没有启动service的问题，API这个是调用的service这个里面的，发现还需要启动。尝试手动启动，在service运行pnpm start，发现网页访问正常.

这样然后写一个自动启动命令

在根目录新建一个open.sh

```c#
#!/bin/bash
cd /www/wwwroot/chatgpt-web/service
pnpm start
``` 

然后使用以下命令将脚本添加到pm2进程管理器并启动它

pm2 start /www/wwwroot/chatgpt-web/open.sh --name chatgpt

最后，使用以下命令将pm2添加到系统启动项中
pm2 startup systemd
参考如下
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/128931267/8105b8b3-98b6-47b3-8bba-f7590de20837)

最后，我尝试重启服务器，还是照样可以打开。

小白的方法，有不对之处，请指教。。。

**Comment by kdcms** [comment]
```c#
#!/bin/bash
cd /www/wwwroot/chatgpt-web/service
nohup pnpm start > service.log 2>&1 &
``` 

更新一下文件

**Comment by Lopins** [comment]
插眼

**Comment by lixiaolong25** [comment]
代理怎么解决的
