### ISSUE TITLE
后端用的chatgpt那个库，每次更新服务器后记忆功能都会丢失，该怎么解决？

### ISSUE THREAD

**Issue by 1596944197** [Chanzhaoyu/chatgpt-web#1769]

**Comment by swuecho** [comment]
这个项目后端没有存储， 可以试试我的 https://github.com/swuecho/chat

**Comment by 1596944197** [comment]
> 这个项目后端没有存储， 可以试试我的 https://github.com/swuecho/chat

转go的话我用不上，我用node开发了一些功能

**Comment by cy948** [comment]
项目用的 `chatgpt` 这个包使用KeyV库做持久化，[demo](https://github.com/transitive-bullshit/chatgpt-api/blob/main/demos/demo-persistence.ts)。

项目中引入：

```ts
import Keyv from 'keyv'

// 可选 keyv 支持的Adapter
import KeyvRedis from '@keyv/redis'

const redisUrl = process.env.REDIS_URL || 'redis://localhost:6379'
const store = new KeyvRedis(redisUrl)
const messageStore = new Keyv({ store, namespace: 'chatgpt-web' })

// 此处对应下文链接内容
api = new ChatGPTAPI({ ...options, messageStore })
```

https://github.com/Chanzhaoyu/chatgpt-web/blob/bc390ef09deb391c8d3f5a16aa9c45cc44082818/service/src/chatgpt/index.ts#L67

**Comment by 1596944197** [comment]
好的，有空我接入试一下
