### ISSUE TITLE
npm run build ERROR: "type-check" exited 

### ISSUE THREAD

**Issue by jianingguo** [Chanzhaoyu/chatgpt-web#177]
npm run build ERROR: "type-check" exited  请问怎么解决呀？

**Comment by Chanzhaoyu** [comment]
代码类型检查没通过，不过你可以强制 `pnpm build-only`

**Comment by jianingguo** [comment]
> 代码类型检查没通过，不过你可以强制 `pnpm build-only`

我把这个去掉了并且使用的npm run build，会有什么问题么？
![image](https://user-images.githubusercontent.com/7371210/222144134-dc969166-230f-4a93-ba12-78d8dd030ebd.png)

**Comment by Chanzhaoyu** [comment]
也没问题，那个只是检测用

**Comment by jianingguo** [comment]
好嘞，感谢大佬

**Comment by jianingguo** [comment]
追加个问题哈，想问下server端能打包成一个可执行程序吗？
