### ISSUE TITLE
如将左下角的名字更改

### ISSUE THREAD

**Issue by carrycan** [Chanzhaoyu/chatgpt-web#1772]
类似别人打开后，会看到牛i皮66的名称

**Comment by huangwb8** [comment]
@carrycan 

你只需要衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)——不仅可以改左下解用户名，还支持API或Access Token模式。

目前的功能包括：多用户登录/注册、数据库管理、对话云端保存和管理、敏感词管理、自定义提示词、多Key轮询、用户管理、自定义模型等（[v2.13.0](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.13.0)起）。

教程详见《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》

**Comment by 6bf3803cb456** [comment]
/src/store/modules/user/helper.ts
改好docker build重新构建镜像就可以了
