### ISSUE TITLE
ChatGPT error 429

### ISSUE THREAD

**Issue by rover75** [Chanzhaoyu/chatgpt-web#1774]
大佬，我搭建好之后聊天，机器人返回这个错误：
ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": null
}
}

**Comment by rover75** [comment]
请问是怎么回事？谢谢。

**Comment by betterlch** [comment]
> 请问是怎么回事？谢谢。

api调用有额度限制，6.2之前有免费额度，现在都过期了，得绑卡付费了，参见[https://platform.openai.com/overview](url)

**Comment by rover75** [comment]
> > 请问是怎么回事？谢谢。
> 
> api调用有额度限制，6.2之前有免费额度，现在都过期了，得绑卡付费了，参见https://platform.openai.com/overview

好的，谢谢大佬。
