### ISSUE TITLE
OPENAI_API_MODEL=gpt-3.5-turbo   已经改成 这个了，为什么会话还是说是gpt-3的呢

### ISSUE THREAD

**Issue by kdcms** [Chanzhaoyu/chatgpt-web#1779]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/128931267/106ffeb6-952e-434e-9c49-abe340880369)
这是啥意思呢

**Comment by assassinliujie** [comment]
因为他不知道自己是3.5，你拿4问也是一样的，都会看返回值了怎么还信这个

**Comment by kdcms** [comment]
> 因为他不知道自己是3.5，你拿4问也是一样的，都会看回去值了怎么还信这个

哈哈哈，信一下嘛

**Comment by chen3728060** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/59358061/801a4b6a-5d92-4153-9923-71beb94c4e09)
gpt说的话你也信？它整天胡说八道的
