### ISSUE TITLE
有没有哪个变量可以修改gpt的输出上下文长度？是max_token吗？

### ISSUE THREAD

**Issue by a616824431** [Chanzhaoyu/chatgpt-web#1781]
如题

**Comment by Sanyela** [comment]
不知道怎么修改max_token

**Comment by ChuckZengxf** [comment]
<img width="1361" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/86394244/f2bf5fe1-3c51-4b48-b6d8-7ea17afe4de8">
