### ISSUE TITLE
官方更新了16k

### ISSUE THREAD

**Issue by cssjidi** [Chanzhaoyu/chatgpt-web#1782]
![Screenshot_2023-06-14-08-52-14-175_com tencent androidqqmail](https://github.com/Chanzhaoyu/chatgpt-web/assets/8515692/4740fa0a-11cf-414f-b82b-96967c305b8c)
官方更新了

**Comment by zhanggaolei001** [comment]
求更新

**Comment by WPF0414** [comment]
chatgpt-next-web更新了 可以去试试

**Comment by jianqiao0313** [comment]
直接在docker-compose文件里配置 **OPENAI_API_MODEL: gpt-3.5-turbo-16k** 就行。

=======================================================
sendMessage (32 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo-16k',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
    },
    { role: 'user', content: '你好', name: undefined }
  ],
  stream: true
}

**Comment by cssjidi** [comment]
done

**Comment by hostemail** [comment]
API模式下才可用吧？
