### ISSUE TITLE
没有回答完整就停止了

### ISSUE THREAD

**Issue by wang0808an** [Chanzhaoyu/chatgpt-web#1786]
没有回答完整就停止了，可否添加一个继续的功能，使ChatGPT回答变得完整呢？

**Comment by shuichang** [comment]
那你输出继续它不就继续答了吗？

**Comment by wang0808an** [comment]
输入继续就变成一个新的答案了😂

shuichang ***@***.***> 于 2023年6月14日周三 21:08写道：

**Comment by shuichang** [comment]
可以把超时设置长一点或直接设置为0看看

**Comment by zhanggaolei001** [comment]
官方的可以一键继续,不知道怎么实现的
