### ISSUE TITLE
一点小小的使用体验建议

### ISSUE THREAD

**Issue by i-iooi-i** [Chanzhaoyu/chatgpt-web#179]
![image](https://user-images.githubusercontent.com/1827701/222147525-99ba4040-80f6-4f4d-b5b6-b522257bf0ab.png)
太感动了，这是用过的几个Docker里面最棒的chatgpt了。
另外，终于在dockerhub平台可以搜索到chenzhaoyu94/chatgpt-web了，之前搜不到。😂

![Snipaste_2023-03-01_21-02-53](https://user-images.githubusercontent.com/1827701/222148677-d5d70b27-f409-4358-8778-a9874de1143b.png)

还是想提个建议：

1. 是否可以考虑，把 “停止响应” 的弹窗关掉，或者多少秒未响应，再出现这个弹窗。现在的情况是只要输入一个问题，这个弹窗就会立即跳出一次，几乎非常频繁，使用久了就会影响体验了。
2. 是否可以考虑增加让用户自定有头像的功能？
3. 是否可以考虑增加账号登录功能呢？这样方便反代到外网，在公司或者其他场所使用。

总之，已经很棒了，再次感谢大佬。🚀😊🌹

**Comment by tangjiahua** [comment]
3的功能我个人感觉还是开发者自己开发接入好，这个仓库做UI表现上的东西会好一点，因为后端部分的需求都太定制化了，语言上大家也不一定会统一，保持后端部分简洁感觉才是优势。仅个人观点 ;-)

**Comment by i-iooi-i** [comment]
> 3的功能我个人感觉还是开发者自己开发接入好，这个仓库做UI表现上的东西会好一点，因为后端部分的需求都太定制化了，语言上大家也不一定会统一，保持后端部分简洁感觉才是优势。仅个人观点 ;-)

嗯嗯，刚才玩了一下，体验超级棒，一个激动就上来提一下建议。

我在想若是第三点不方便的话，可否做一个定制功能，比如，允许用户给机器人自定义一个名字，只有在使用它的时候，通过名字唤醒机器人，然后进入问答模式。若是连续超过某个定制的时间，那么机器人就会下线。

这样的话，是否就可以降低外网使用的风险。毕竟只有知道正确名字的人，才可以把机器人召唤出来。😂

**Comment by Chanzhaoyu** [comment]
> > 3的功能我个人感觉还是开发者自己开发接入好，这个仓库做UI表现上的东西会好一点，因为后端部分的需求都太定制化了，语言上大家也不一定会统一，保持后端部分简洁感觉才是优势。仅个人观点 ;-)
> 
> 嗯嗯，刚才玩了一下，体验超级棒，一个激动就上来提一下建议。
> 
> 我在想若是第三点不方便的话，可否做一个定制功能，比如，允许用户给机器人自定义一个名字，只有在使用它的时候，通过名字唤醒机器人，然后进入问答模式。若是连续超过某个定制的时间，那么机器人就会下线。
> 
> 这样的话，是否就可以降低外网使用的风险。毕竟只有知道正确名字的人，才可以把机器人召唤出来。😂

可以后端环境增加个密码，前端判断是否有密码，如果有就跳转验证再使用，其实不复杂

**Comment by gouguoyin** [comment]
我也是建议账号登录开发者自己开发接入的好，要不然前端太杂，自己更换服务端的成本就会变高。
