### ISSUE TITLE
请问长文本被截断的问题如何解决

### ISSUE THREAD

**Issue by tanglu86** [Chanzhaoyu/chatgpt-web#1790]
我通过docker启动
docker run --name chatgpt-web_2.11.0 -d -p 8080:3002 --env OPENAI_API_KEY=sk-123456 --env OPENAI_API_MODEL=gpt-3.5-turbo-0613 --env TIMEOUT_MS=0 chenzhaoyu94/chatgpt-web:latest
但是每次文本内容达到800左右就会被截断，请问如何修改MAX_TOKENS

**Comment by c534450673** [comment]
+1

**Comment by VergilWang15** [comment]
max_token 在 service\src\chatgpt\index.ts 中可以通过
```       
        options.maxModelTokens = 4096
        options.maxResponseTokens = 2048
```
修改

**Comment by ba0gu0** [comment]
回复  继续 即可

如果包含代码，则回复  ```继续

**Comment by Caiyou1001** [comment]
> max_token 在 service\src\chatgpt\index.ts 中可以通过
> 
> ```
>         options.maxModelTokens = 4096
>         options.maxResponseTokens = 2048
> ```
> 
> 修改

怎么bash方式进不去
