### ISSUE TITLE
这个项目有复刻后保持更新的兄弟吗？

### ISSUE THREAD

**Issue by oasis168** [Chanzhaoyu/chatgpt-web#1793]
用来用去还是这个项目最好用，可惜作者不怎么更新了，请问这个项目有复刻后保持更新的兄弟吗？或者知道项目地址的推荐一个，谢谢

如果有更好的项目，也可推荐下，谢谢

**Comment by huangwb8** [comment]
@oasis168 

推荐衍生项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)。 具体教程见： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》。 它也是一个开源免费项目，更新还挺频繁的。

Chanzhaoyu应该不是不更新；更多的精力应该是在闭源收费项目[Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)里。

**Comment by oasis168** [comment]
谢谢推荐解答，期待作者更新

**Comment by a97242689** [comment]
> @oasis168
> 
> 推荐生成项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)。具体教程见：《[Docker系列基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》。它也是一个开源免费项目，更新还顶视频繁的。
> 
> 单照玉应该不是不更新；更多的实力应该在闭源收费项目[单照单/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)里。

这个收费版是要多少米？
