### ISSUE TITLE
请问如果是自建代理,如何隐藏配置的url

### ISSUE THREAD

**Issue by xuxiang19961203** [Chanzhaoyu/chatgpt-web#1795]

**Comment by xuxiang19961203** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/77263257/b99e8964-312d-4c3e-8935-aa11aa41efe1)

**Comment by ryomahan** [comment]
不理解你的意思，你是是想怎么隐藏，在响应里隐藏吗？那你就改成一个后端配置项就行了，在后端写死不要让前端去修改。

**Comment by zjuwyz** [comment]
可以在本地再包一层 nginx ，把代理包装到一个本地端口。这样从 chatgpt-web 那里只能看到一个 127.0.0.1:XXXX，没啥价值。
具体怎么弄问chatgpt。

stream {
    server {
        listen local-port;
        proxy_pass proxy.url:port
    }
}

**Comment by xuxiang19961203** [comment]
> 



> 可以在本地再包一层 nginx ，把代理映射到一个本地端口。这样从 chatgpt-web 那里只能看到一个 127.0.0.1:XXXX，没啥价值。
> 
> stream { server { listen local-port; proxy_pass proxy.url:port } }

说得有道理, 反向代理简单明了,我去试试.
