### ISSUE TITLE
最近使用遇到问题

### ISSUE THREAD

**Issue by aiexonline** [Chanzhaoyu/chatgpt-web#1802]
request to https://ai.fakeopen.com/api/conversation failed, reason: connect ECONNREFUSED 223.75.236.241:443 聊天错误

**Comment by aiexonline** [comment]
之前一直可以，换了ACCESSTOKEN也不行

**Comment by aiexonline** [comment]
有大佬帮我解答一下吗？

**Comment by Yzwcp** [comment]
我也是

**Comment by edgleaf** [comment]
同样的问题
