### ISSUE TITLE
长回答流式超时，设定 timeoutMs 无效

### ISSUE THREAD

**Issue by qzxin365** [Chanzhaoyu/chatgpt-web#1805]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/66016718/833422f2-9382-4853-8368-52f2b48987d8)
如图所示，当 content-download 达到 1 min 后，必现 Network error。
已设定超时时间为 10min，但是无效：SendMessageOptions: { timeoutMs: 600000 }

**Comment by PuddingJoker** [comment]
> ![image](https://user-images.githubusercontent.com/66016718/248524969-833422f2-9382-4853-8368-52f2b48987d8.png) 如图所示，当 content-download 达到 1 min 后，必现 Network error。 已设定超时时间为 10min，但是无效：SendMessageOptions: { timeoutMs: 600000 }

老哥解决了吗

**Comment by qzxin365** [comment]
并没有
