### ISSUE TITLE
ChatGPT error 524

### ISSUE THREAD

**Issue by iamflowerdog** [Chanzhaoyu/chatgpt-web#1811]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/27678693/fe17606c-482f-4359-b8bb-0bafc9f94ccc)
看起来像是反向代理不行了？
用ChatGPT账号登陆 chat.openai.com 可以查看聊天已经发送，内容也能收到，但是咱们部署收不到回答

**Comment by iamflowerdog** [comment]
问了一下讯飞，得到的答案是：
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/27678693/3a3b4384-1815-4fa6-9913-65a7b73b23a7)

**Comment by xuxiang19961203** [comment]
我也遇到了这个问题

**Comment by serena886** [comment]
我也是 有知道怎么解决的吗

**Comment by yunxuanlee** [comment]
> 我也是 有知道怎么解决的吗

把代理的地址改了就好了
API_REVERSE_PROXY=https://api.pawan.krd/backend-api/conversation

**Comment by iamflowerdog** [comment]
> > 我也是 有知道怎么解决的吗
> 
> 把代理的地址改了就好了 API_REVERSE_PROXY=https://api.pawan.krd/backend-api/conversation

感谢，已经可以了

**Comment by nsnake** [comment]
> > > 我也是 有知道怎么解决的吗
> > 
> > 
> > 把代理的地址改了就好了 API_REVERSE_PROXY=https://api.pawan.krd/backend-api/conversation
> 
> 感谢，已经可以了

我也改了，但现在变成400错误了

**Comment by wejudging** [comment]
还是不行啊啊啊


> > > > 我也是 有知道怎么解决的吗
> > > 
> > > 
> > > 把代理的地址改了就好了 API_REVERSE_PROXY=https://api.pawan.krd/backend-api/conversation
> > 
> > 
> > 感谢，已经可以了
> 
> 我也改了，但现在变成400错误了
> 
> 最新更新:把之前的对话删了或者新开一个对话就好了

**Comment by wejudging** [comment]
ChatGPT error 400: {"detail":"Our systems have detected unusual activity from your system. Please try again later."}

**Comment by wejudging** [comment]
ChatGPT error 400: {"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}
