### ISSUE TITLE
chatgpt4

### ISSUE THREAD

**Issue by xiaozhen228** [Chanzhaoyu/chatgpt-web#1813]
拥有chatgpt4如何使用access token的方式?，指定模型似乎是给api用的，不指定默认用的是gpt3.5

**Comment by mingyuetian** [comment]
需要自建代理，然后将 API_REVERSE_PROXY 选择到自己的代理上，在OPENAI_API_MODEL中就可以选择模型了
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/39106989/6d00a54b-2dc1-47aa-a54e-e68c6ac547f7)
