### ISSUE TITLE
请问一下vue前端是如何接收流式字符串数据的

### ISSUE THREAD

**Issue by codemonkey-1024** [Chanzhaoyu/chatgpt-web#1814]
请问一下vue前端是如何接收流式字符串数据的

**Comment by ytking** [comment]
request progress

**Comment by zerlous** [comment]
核心就是使用`eventsource-parser`createParser去轮询回调处理streams.
`
export async function* streamAsyncIterable<T>(stream: ReadableStream<T>) {
  const reader = stream.getReader()
  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) {
        return
      }
      yield value
    }
  } finally {
    reader.releaseLock()
  }
}
`
