### ISSUE TITLE
docker-compose使用access token方式 部署后，回答问题不齐全(文字多的时候)，请问是什么原因？

### ISSUE THREAD

**Issue by walkchen9** [Chanzhaoyu/chatgpt-web#1817]
![不全](https://github.com/Chanzhaoyu/chatgpt-web/assets/125525044/64eae700-a359-4974-bc06-b3431312c340)

这是我的yaml文件 
![yaml](https://github.com/Chanzhaoyu/chatgpt-web/assets/125525044/d473e589-2cc1-48ae-b0f3-d59e13d843ca)

**Comment by clwang798** [comment]
有字数限制，2048个字符utf-8编码相当于682个汉字。

**Comment by walkchen9** [comment]
但是用其他项目做的GPT web好像没有这个情况
