### ISSUE TITLE
BAI chat 提供错误的API密钥 | Incorrect API key provided

### ISSUE THREAD

**Issue by fkggggg** [Chanzhaoyu/chatgpt-web#1819]
7.4遇到这个问题

**Comment by youyaa** [comment]
我也是，解决了吗？

**Comment by fkggggg** [comment]
> 我也是，解决了吗？

当天下午就能用了，以及我刚才试了一下是可用的

**Comment by youyaa** [comment]
> > 我也是，解决了吗？
> 
> 当天下午就能用了，以及我刚才试了一下是可用的

我也解决了，是token过期了，但是通过session获取的token还是原来的，开了个无痕模式重新获取就好了
