### ISSUE TITLE
https://chatbot.theb.ai/这个网站的怎么做的呢，好像不是简单调用gpt3的api

### ISSUE THREAD

**Issue by zndqs** [Chanzhaoyu/chatgpt-web#1820]
模型知道自己不是原生gpt3：‘我是BAI Chat，由开发者Little B使用OpenAI的GPT-3.5构建的聊天机器人。有什么我可以帮助你的吗？’
是做了ft吗,还是api的进阶用法

**Comment by KKISO574** [comment]
默认给他的一个提示词，你在别的调用的类似项目也可以这样设置啊

**Comment by huangkezhao** [comment]
开源永久免费 不注册 不登陆 不限次数  http://aiassist.plus
