### ISSUE TITLE
onDownloadProgress接收到的responseText偶尔缺失一部分

### ISSUE THREAD

**Issue by Du1129** [Chanzhaoyu/chatgpt-web#1821]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/51909949/c2305a68-0fba-4ea5-9cd9-c93d5f13263b)

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/51909949/bb4692de-b484-4b72-ad34-0debaa6e4499)
xhr 接收到responseText的最新回复会缺失不部分，倒是JSON.parse()解析错误，但是后续的回复又是正常的，这是为什么？

**Comment by linsonglinsonga** [comment]
是因为接口返回内容太快了吗？循环展示的时候慢，导致的展示不全吗，我也遇到了这个问题

**Comment by Du1129** [comment]
> 是因为接口返回内容太快了吗？循环展示的时候慢，导致的展示不全吗，我也遇到了这个问题
不是展示的不完全，而是onDownloadProgress偶尔接收的到的数据就是不完整的了，最后一段就有可能不是一个完整的json字符串，解析不了

**Comment by zerlous** [comment]
[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api)中的`fetchSSE`方法，在处理stream流数据的过程中，`TextDecoder().decode(chunk)`的返回是非json字符串，parse的时候异常导致的。

**Comment by Du1129** [comment]
> TextDecoder()

这个是不是没法解决了？

**Comment by Du1129** [comment]
> [chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api)中的`fetchSSE`方法，在处理stream流数据的过程中，`TextDecoder().decode(chunk)`的返回是非json字符串，parse的时候异常导致的。

这个是不是没法解决了？

**Comment by Voyager-sun** [comment]
问题解决了吗？

**Comment by linsonglinsonga** [comment]
解决了
















在 2024-04-07 10:06:30，"voyagesun" ***@***.***> 写道：

问题解决了吗？
