### ISSUE TITLE
[Feature Request] API Update

### ISSUE THREAD

**Issue by Quorafind** [Chanzhaoyu/chatgpt-web#183]
今早 OpenAI 更新了它的 API ，您考虑将本方案中的 API 适配升级成 ChatGPT 的 API 吗？为了方便您的操作，这里是对应的 API 文档以及介绍：

- https://platform.openai.com/docs/api-reference/completions
- https://platform.openai.com/docs/guides/chat

**Comment by Chanzhaoyu** [comment]
感谢，现在关闭此 `issue`
