### ISSUE TITLE
填了accesstoken 启动后端的时候还是提示没填accesstoken

### ISSUE THREAD

**Issue by xiaozeyo** [Chanzhaoyu/chatgpt-web#1831]
单引双引不加引号`号都试过了……，安装前端的时候还报了个错，求大佬帮看看……
![图片](https://github.com/Chanzhaoyu/chatgpt-web/assets/84388487/cef20b4d-c72f-4bb2-a86a-3df4b3130bbd)
![图片](https://github.com/Chanzhaoyu/chatgpt-web/assets/84388487/5efa723a-6fbd-4821-a8cd-6741e46f55eb)
![图片](https://github.com/Chanzhaoyu/chatgpt-web/assets/84388487/b7f639ad-cc8a-4b8a-a16e-68d1ae67203e)

**Comment by xiaozeyo** [comment]
> 

非常感谢！话说大佬知道那个前端的问题出在哪嘛

**Comment by Du1129** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/51909949/e58cb5f8-07a0-4553-9fb7-7ad46900340e)
"pnpm bootstrap" 本意是执行pnpm install 和pnpm run common:prepare
pnpm run common:prepare的执行husky install 的操作，如果不需要提交代码到原作者仓库，就运行pnpm install 安装就可以了
关于husky相关知识可以自行上网了解一下

**Comment by xiaozeyo** [comment]
> 

原来如此感谢大佬指点
