### ISSUE TITLE
实际的后端地址

### ISSUE THREAD

**Issue by caoyangyang1215** [Chanzhaoyu/chatgpt-web#1832]
1、修改根目录下 .env 文件中的 VITE_GLOB_API_URL 为你的实际后端接口地址

默认的值是 /api

我需要修改成什么？？

现在前端代码在 nginx 下，访问时控制提示

http://ip/api/session 404

请指教

**Comment by caoyangyang1215** [comment]
已解决

**Comment by MrBocchi** [comment]
> 已解决

碰到相同问题了，求问怎么解决的

**Comment by ZZLinvec** [comment]
同问

**Comment by OswaldSnow** [comment]
@ZZLinvec @MrBocchi 

{
tls [xxxxxx@gmail.com](mailto:xxxxxx@gmail.com)

encode zstd gzip

handle_path /api* {
reverse_proxy localhost:8123
}

route {
handle {
root * /var/www/html/dist
file_server
}
}
}

这是我 caddy 中的配置，后端的 js 运行在 8123 端口，前端资源在 dist 下面，配置文件中的路径 /api 不需要改，你可以参考一下
nginx 的话也是类似的
