### ISSUE TITLE
https 与 nginx

### ISSUE THREAD

**Issue by caoyangyang1215** [Chanzhaoyu/chatgpt-web#1833]
前端：在服务器 A 上，使用 nginx 且配置了 ssl 证书

后台：也在服务器 A 上，使用 pnpm start 运行在 3002 上

此时 .nev 中 VITE_GLOB_API_URL 的地址 http://ip:3002/ 无法访问

请问我应该怎么做

**Comment by caoyangyang1215** [comment]
Q——Q
    ~~

**Comment by caoyangyang1215** [comment]
emmmm

**Comment by caoyangyang1215** [comment]
已解决

**Comment by zyyint** [comment]
> 已解决

请问是如何解决的？

**Comment by OswaldSnow** [comment]
@heiyyint 

{
  tls xxxxxx@gmail.com 

  encode zstd gzip

  handle_path /api* {
      reverse_proxy localhost:8123
    }

  route {
    handle {
      root * /var/www/html/dist
      file_server
    }
  }
}

这是我 caddy 中的配置，后端的 js 运行在 8123 端口，前端资源在 dist 下面，配置文件中的路径  /api 不需要改，你可以参考一下
nginx 的话也是类似的
