### ISSUE TITLE
access_token 模式是不是不支持了

### ISSUE THREAD

**Issue by jackbon8** [Chanzhaoyu/chatgpt-web#184]
貌似官方添加了人机验证  使用不了了

**Comment by jackbon8** [comment]
![图片](https://user-images.githubusercontent.com/43921493/222308514-d0842168-f73b-4c20-aaf5-fcbaf7526953.png)

**Comment by ludashi2020** [comment]
你没有使用api代理吧？

**Comment by ludashi2020** [comment]
`https://chatgptapi.googlevideo.dev/api/conversation`  api代理使用这个

**Comment by gygy** [comment]
session今天开始提示403

**Comment by ludashi2020** [comment]
> session今天开始提示403
我使用一切正常,没有出现403。我是用的token

**Comment by piglingcn** [comment]
> https://chatgptapi.googlevideo.dev/api/conversation

怎么修改代理
