### ISSUE TITLE
404报错

### ISSUE THREAD

**Issue by zhaizhaohui** [Chanzhaoyu/chatgpt-web#1848]
网站访问500，日志显示报错 api/session 404

**Comment by huangwb8** [comment]
@zhaizhaohui 

你透露的日志和过程信息太少，不好排障。

另外，你可以试试衍生项目[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)。它基于MongoDB后端，支持API或Access Token模式。目前的功能包括：多用户登录/注册、数据库管理、对话云端保存和管理、敏感词管理、自定义提示词、多Key轮询、用户管理、自定义模型等（[v2.13.0](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.13.0)起）。最重要的是，该项目是完全开源和免费的！具体教程： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》

Chanzhaoyu大佬在2023-04-26建了一个QQ群734133205，介绍了源项目的plus版本——chatgpt-web-plus，其包含个人部署、商业部署、企业部署和团队部署等内容。项目地址在[Chanzhaoyu/chatgpt-web-plus](https://github.com/Chanzhaoyu/chatgpt-web-plus)，非开源且付费（之前好像是1000多元/份，最近没怎么了解）。感兴趣也可以关注 [chatgpt-web-plus · Issue #1606 · Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web/issues/1606)。

**Comment by lqs1920** [comment]
h5gpt.cn

出售域名
