### ISSUE TITLE
用Docker-Compose方式启动，但页面打不开

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [Chanzhaoyu/chatgpt-web#1851]
日志显示正常：

> chatgpt-web-service@1.0.0 prod /app
> node ./build/index.mjs

Server is running on port 3002

同时本机端口监听正常：

tcp        0      0 0.0.0.0:3002            0.0.0.0:*               LISTEN      217429/docker-proxy 
tcp6       0      0 :::3002                 :::*                    LISTEN      217434/docker-proxy 

用VPS的ip:3002无法访问，一周之前突然不行，之前可以，没动过配置
看看是很简单的问题，但找不到头绪，求教~~

附docker-compose.yaml配置

version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web
    restart: unless-stopped
    ports:
        - 3002:3002
    environment:
        OPENAI_ACCESS_TOKEN: "MY TOKEN"
        TIMEOUT_MS: 100000
        API_REVERSE_PROXY:

**Comment by huangwb8** [comment]
@GitHubChrisChen8035 

会用docker-compose，建议了解一下衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 。 具体教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201) 。 祝好！

**Comment by GitHubChrisChen8035** [comment]
已解决，记录一下

偶然间看到VPS登录显示如下信息：
  IPv4 address for br-3f82a82155c9: 172.18.0.1
  IPv4 address for br-91db6df128b2: 172.19.0.1
  IPv4 address for br-b4eb30442442: 172.20.0.1
  IPv4 address for docker0:         172.17.0.1
  IPv4 address for eth0:            10.2.15.2

  通过命令docker network ls查询docker内部网络接口：
  NETWORK ID   NAME                      DRIVER    SCOPE
460a34229bca   bridge                    bridge    local
3f82a82155c9   chatgpt_default           bridge    local
b4eb30442442   combine_chatgpt_default   bridge    local
91db6df128b2   go-chatgpt-api_default    bridge    local
334266c7b9e0   host                      host      local
264c43cdecf5   none                      null      local
  3f82a82155c9、b4eb30442442都是chatgpt_web的容器网络接口（combine_chatgpt_default是之前创建的容器，已经stop和rm），不知为何容器网络接口没有删掉，导致3002端口占用冲突，删除该容器网络并重新启动容器，解决。
