### ISSUE TITLE
余额查询

### ISSUE THREAD

**Issue by lxlfifa** [Chanzhaoyu/chatgpt-web#1855]
大家的余额查询功能还能用么？今天换了个apikey，查询使用量一直为-

**Comment by VegetableChichen** [comment]
我也一样显示“ - ”，而且我没换apikey

**Comment by lxlfifa** [comment]
> 我也一样显示“ - ”，而且我没换apikey

你的解决了么

**Comment by VegetableChichen** [comment]
> > 我也一样显示“ - ”，而且我没换apikey
> 
> 你的解决了么

没有

**Comment by bazijun** [comment]
是因为报错了，好像这个接口只能在浏览器请求了
> 'Your request to GET /v1/dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.'
