### ISSUE TITLE
求大佬解答一下，一直报Request failed with status code 504

### ISSUE THREAD

**Issue by xunfeng2zkj** [Chanzhaoyu/chatgpt-web#1856]
# 1. 有clash代理
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/22878414/cb56405e-f134-4c16-b71b-01aaf3456646)
# 2. 使用docker部署
docker run --name chatgpt-web --rm -it -p 127.0.0.1:3002:3002 --env TIMEOUT_MS=0  --env HTTP_PROXY=http://127.0.0.1:7890 --env OPENAI_API_KEY=sk-* chatgpt-web
# 3. 使用nginx代理127.0.0.1：3002

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/22878414/06706563-dc22-4b42-857f-f65e3f8a4044)
# 4. 然后一直报错
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/22878414/2f222aba-5a27-42d4-9249-46dc1918c04e)
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/22878414/fe8390d8-ea42-4514-8ecf-985696991e56)

**Comment by yuanbaiqi** [comment]
问题解决吗，老哥
