### ISSUE TITLE
ChatGPTUnofficialProxyAPI(网页 accessToken) 方式是否可调用chatgpt4模型？

### ISSUE THREAD

**Issue by walkchen9** [Chanzhaoyu/chatgpt-web#1857]
ChatGPTUnofficialProxyAPI(网页 accessToken) 方式是否可调用chatgpt4模型？

**Comment by walkchen9** [comment]
如果账号开通了plus会员的话access token能否调用gpt聊天，

**Comment by walkchen9** [comment]
如果账号开通了plus会员的话access token能否调用gpt4模型聊天，

**Comment by gougui** [comment]
不能
