### ISSUE TITLE
求大佬解答，提问时一直报错，ChatGPT error 429: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by caoshihao** [Chanzhaoyu/chatgpt-web#1858]
ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}

我看了一下，我的余额余额还有$15呢！不知道原因。感谢！

**Comment by foxtwobao** [comment]
Billing-UsageLimits里面的限制调一调

**Comment by caoshihao** [comment]
> Billing-UsageLimits里面的限制调一调

按照你提示的操作了一下，页面说需要升级套餐？估计没辙了，国内信用卡不允许充值。请问有其他办法吗？

**Comment by foxtwobao** [comment]
你的免费计划到期了，虽然看上去还有余额，但是有效期过了，看看是不是这个原因。充值方法自行百度

**Comment by caoshihao** [comment]
好的，我找找办法。谢谢！
