### ISSUE TITLE
反向代理挂了，有没推荐？或有没项目可以自己部署？

### ISSUE THREAD

**Issue by walkchen9** [Chanzhaoyu/chatgpt-web#1859]
https://api.pawan.krd/backend-api/conversation

比较大的2个反向代理好像挂了，有没有推荐？

**Comment by huangwb8** [comment]
如果你会docker，可以很方便地布署一个反向代理。

具体见《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》中的“（新版本）Access Token自建ChatGPT——在VPS里自建反向代理”部分。我当时使用的项目是 [linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)。

**Comment by dfvips** [comment]
通过这个自建可以解决ChatGPTUnofficialProxyAPI挂了的问题。
https://github.com/linweiyuan/go-chatgpt-api/
