### ISSUE TITLE
官方的ChatGPTUnofficialProxyAPI挂了，自建反向代理解决方案！

### ISSUE THREAD

**Issue by dfvips** [Chanzhaoyu/chatgpt-web#1865]
通过这个自建可以解决ChatGPTUnofficialProxyAPI挂了的问题。
https://github.com/linweiyuan/go-chatgpt-api/
<img width="1439" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/21048630/e17ab5b5-d89b-429f-8cb7-ba8b215236e0">
docker run -d --restart=always -p 39001:8080 -e PUID=0 -e PGID=0 -e UMASK=022 --name="go-chatgpt-api" linweiyuan/go-chatgpt-api
其中39001可以改为任意需要映射的外部端口，8080不可修改，是go-chatgpt-api服务的默认端口。

**Comment by walkchen9** [comment]
[chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web) 的docker run命令是啥

**Comment by dfvips** [comment]
> chatgpt-web
chatgpt-web建议用docker-compose比较方便一点，可以改配置内容。
