### ISSUE TITLE
获取不到本月使用量

### ISSUE THREAD

**Issue by caoyangyang1215** [Chanzhaoyu/chatgpt-web#1866]
当我点开 配置，本月使用量的数据显示是 - 
登录我的 openai 账号是能看到本月使用量的
这是 console 看到的响应值

{
    "apiModel": "ChatGPTAPI",
    "reverseProxy": "",
    "timeoutMs": 100000,
    "socksProxy": "-",
    "httpsProxy": "-",
    "usage": "-"
}

请教一下各位可能是什么原因

**Comment by caoyangyang1215** [comment]
Error: 获取使用量失败
    at fetchUsage (file:///root/service/build/index.mjs:137:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatConfig (file:///root/service/build/index.mjs:156:17)
    at async file:///root/service/build/index.mjs:265:22

**Comment by MicroGalaxy** [comment]
官方接口关了，这个用不了

**Comment by Special-Week** [comment]
f12打开原本用来请求获取使用量的Authorization中apikey，变成了一个sess开头的一个字符串，它能够正常获取使用量，并且我还发现这东西还能充当apikey使用，但是他貌似会失效，我账号注销后他就没用了

**Comment by caoyangyang1215** [comment]
@Special-Week 那个应该是登录之后生成的 token 令牌，重新登录之后就会变得
