### ISSUE TITLE
你好，请问下后端部署的问题。

### ISSUE THREAD

**Issue by CherishMvp** [Chanzhaoyu/chatgpt-web#1874]

**Comment by CherishMvp** [comment]
我已经部署好Pandora后端代理服务，本地也可以跑起来，那要怎么接入我们这个项目呢？

**Comment by Pigeon-fancier** [comment]
后端的接口应该都在https://github.com/Chanzhaoyu/chatgpt-web/blob/main/service/src/index.ts 里面

**Comment by CherishMvp** [comment]
看了下应该是被墙了，用fakeopen的临时的反向代理是可以用的
