### ISSUE TITLE
用这个程序结合stulzq/azure-openai-proxy，的docker应用。azure的API接口会被盗用。具体哪个有问题我不清楚

### ISSUE THREAD

**Issue by dyingway** [Chanzhaoyu/chatgpt-web#1879]
给自费的提个醒。已经两次了，我第一次本来以为我自己用的超了（因为就多了几美元没在意），重置了密钥。

然后这次直接给我干到了30多美元（非GPT4)

<img width="1679" alt="屏幕截图 2023-08-03 111930" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/14267351/8b3f1456-38d9-4d85-8237-ade13f1c06de">

**Comment by dyingway** [comment]
> 我靠真的假的啊，我也用了这个stulzq/azure-openai-proxy

May this is a "the proof of the pudding"problem.

**Comment by stulzq** [comment]
stulzq/azure-openai-proxy 不担这个锅，代码经得起审查，https://www.freebuf.com/articles/network/366740.html

**Comment by AndyX-Net** [comment]
建议楼主用Nginx给web前端套个密码，保证只有自己用就行。

**Comment by dyingway** [comment]
> 

是azure api的密钥被盗用，不是我的网页被盗用。
