### ISSUE TITLE
内容被屏蔽了？

### ISSUE THREAD

**Issue by hotinewang** [Chanzhaoyu/chatgpt-web#1882]
我部署在自己的服务器上，服务器的其他内容都能正常访问，唯独这个chatgpt-web，会提示访问被拒绝。开vpn就能访问，不开vpn就访问不了。咋回事？

**Comment by imldy** [comment]
域名被反诈阻断了？

**Comment by hotinewang** [comment]
ping我的vps其他端口，都能ping通，但是ping这个3002端口，境外都可以ping通，但是国内都ping不通

**Comment by hotinewang** [comment]
> 域名被反诈阻断了？

不久我的ip就被墙了，好桑心。。。。。
