### ISSUE TITLE
开源java版本，基于springboot，数据存储于数据库，支持注册登录、生成图片

### ISSUE THREAD

**Issue by moyangzhan** [Chanzhaoyu/chatgpt-web#1887]
前端界面基于chatgpt-web

地址：https://github.com/moyangzhan/aideepin

![1691585544443](https://github.com/Chanzhaoyu/chatgpt-web/assets/83471894/e0800880-8110-4e91-a0b5-cbbb74467223)

![1691583184761](https://github.com/Chanzhaoyu/chatgpt-web/assets/83471894/46aa4161-f83c-4290-8f01-23e613458692)

![1691583124744](https://github.com/Chanzhaoyu/chatgpt-web/assets/83471894/76b64d3a-0492-4c91-92c5-c7429b2b055c)

**Comment by alex-oos** [comment]
继续加大宣传

**Comment by zhuxindong** [comment]
支持绑定
