### ISSUE TITLE
为什么一直会有echo hello world这个会话在刷呢？

### ISSUE THREAD

**Issue by Zhanghao0150** [Chanzhaoyu/chatgpt-web#1888]
如题，通过accesstoken搭建的免费的聊天，在官方那边的对话一直有echo hello world 这个内容在刷新建聊天

**Comment by alex-oos** [comment]
我没有发现呀？

**Comment by alex-oos** [comment]
目前我的没有，你是不是修改什么代码了呢？你加个日志，定位一下吧

**Comment by alex-oos** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/46887064/32ab1f4e-7139-4ca3-a7f7-480c6c86e023)
我的首页都与你的页面不一致，这是why？

**Comment by alex-oos** [comment]
重新，拉取一下镜像，更新一下，你再试试吧

**Comment by Zhanghao0150** [comment]
嗯 我试试.

**Comment by Zhanghao0150** [comment]
还是会，算了 不管了 定期上官方的网站删掉这些对话吧.

**Comment by HaiLinWang** [comment]
我也被刷了。

**Comment by alex-oos** [comment]
估计是被攻击了吧，你更换端口试试

**Comment by alex-oos** [comment]
> ![image](https://user-images.githubusercontent.com/37323577/259669262-cd4e5b34-0043-43af-b6fa-919e92744bcc.png) ![image](https://user-images.githubusercontent.com/37323577/259669291-06bed479-bc66-43b0-abf8-5454dcbb6996.png)
这个问题的原因是，你的token 被人使用了，并且部署了chatgpt-web 项目，那个项目的端口被默认扫描了，老是发送1，目前我的chatgpt也是如此，我目前停止了chatgpt-web项目就好了
