### ISSUE TITLE
在sever端部署出现一些问题

### ISSUE THREAD

**Issue by hxhaozi** [Chanzhaoyu/chatgpt-web#189]
1.使用nohup pnpm start  & 和 nohup pnpm dev& 分别部署后端和前端后  退出ssh连接器服务会从listen变为time out 断开连接
2.此时再部署后端和前端,登录前端页面后发现前后端没有关联(就是后端配置的token和代理都没有),查询了下服务都是运行的

作者大大和其他大佬能帮我解答下么

**Comment by Zo3i** [comment]
可以使用docker-compose 方式搭建，我fork 的版本有部署教程。

**Comment by hxhaozi** [comment]
> 可以使用docker-compose 方式搭建，我fork 的版本有部署教程。

我现在页换方式搭建了  ,但就是好奇之前为什么出错

**Comment by Zo3i** [comment]
一般推荐docker 部署，问题少一点。有的时候各种各样的问题，没法复现不好排查

**Comment by Chanzhaoyu** [comment]
此 `issue` 关闭了哈，我有强迫症
