### ISSUE TITLE
怎么实现流输出

### ISSUE THREAD

**Issue by qq921124136** [Chanzhaoyu/chatgpt-web#1891]
我感觉输入一个答案，等很久才出来，我想看见流输出那种模式

**Comment by Zexin** [comment]
需要配置nginx

**Comment by qq921124136** [comment]
怎么实现了？

**Comment by qq921124136** [comment]
加上 proxy_buffering off;
 proxy_http_version 1.1;
 chunked_transfer_encoding on;这3个好像就可以了
