### ISSUE TITLE
chatgpt-web更新chatGPT模型为3.5版的方法

### ISSUE THREAD

**Issue by gouguoyin** [Chanzhaoyu/chatgpt-web#190]
1、打开 `service/package.json` 文件，将 `chatgpt` 的依赖更新为 `^5.0.1`，如下图
<img width="959" alt="image" src="https://user-images.githubusercontent.com/13517412/222331830-9c6ae3a6-5fe2-44ce-acf9-cb5b6e85895b.png">
2、运行 `pnpm install` 
3、打开 `service/src/chatgpt.ts` ，将 `debug` 设为 `true` 开启调试模式
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/13517412/222333765-38944cb8-acf7-4162-90b9-827e2b144b02.png">
4、运行 `pnpm start` ，就可以在当前命令行里可以看到当前使用的模型为 `gpt-3.5-turbo-0301`，不过如果你问 `chatGPT` 当前用的版本它有时会回复是 `3.5`，有时回复是 `3.0`，有时说保密，实际上已经是 `3.5` 版本了
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/13517412/222332424-0df50f28-e907-4ef1-a679-23af30fe20ed.png">
<img width="985" alt="image" src="https://user-images.githubusercontent.com/13517412/222333480-b4b1da1a-c36d-483b-beb7-e7d66b696cc9.png">

为了方便大家沟通交流，同步消息，建了QQ群，群号 145225165
![image](https://user-images.githubusercontent.com/13517412/222332574-77a113db-2848-4e05-87a9-db86589d7074.png)

**Comment by GeorgeGalway** [comment]
上下文理解能力怎么样

**Comment by ZhangXY-Magic** [comment]
这个要买plus才能体验3.5么？

**Comment by GeorgeGalway** [comment]
> 这个要买plus才能体验3.5么？

不需要

**Comment by ZhangXY-Magic** [comment]
> > 这个要买plus才能体验3.5么？
> 
> 不需要

![image](https://user-images.githubusercontent.com/25630228/222362716-d2cca334-23f8-4f2c-8bd8-b3a9c179de15.png)

![image](https://user-images.githubusercontent.com/25630228/222362486-427fa0f5-75f9-47e3-ae61-411f1f2092af.png)
那我升级chatgpt版本5.0.1 重新install 怎么模型不变。。

**Comment by GeorgeGalway** [comment]
> 

你这是反向代理吧，采用ChatGPTAPI(GPT-3) Api方式可以使用3.5

**Comment by pengmaochang** [comment]
docker compose可以这样
```
docker-compose down
docker-compose pull
docker-compose up -d
```
