### ISSUE TITLE
部署在国外服务器上，前端返回的数据，最后一行是不完整的，无法解析，没有一个字一个字显示的效果。

### ISSUE THREAD

**Issue by dichen2013** [Chanzhaoyu/chatgpt-web#1902]
![f](https://github.com/Chanzhaoyu/chatgpt-web/assets/19348017/0e35d31e-8cc2-4f74-99df-47f674353524)

**Comment by xiaosaaaa** [comment]
和你说的没关系，nginx用了吗？用了的话关闭nginx缓存

**Comment by dichen2013** [comment]
> 和你说的没关系，nginx用了吗？用了的话关闭nginx缓存
已经解决，前端返回的数据chunk是不完整的。已经提交了pull。不全的时候不取最后一行，取倒数第二行
