### ISSUE TITLE
请问这个项目会导致GFW触发机制而墙域名吗？

### ISSUE THREAD

**Issue by crazyd2sty** [Chanzhaoyu/chatgpt-web#1908]
我自己有两个域名,第一个是新买的,用了两三个月之后域名被墙了,然后拿了一个之前的老域名使用,再次被墙了,这一次不到短短的一个星期。
两个域名都是在阿里云注册,服务器在美国,使用cloudflare。
在未弄清楚原因之前不建议大家用主域名进行搭建

**Comment by MicroGalaxy** [comment]
有可能会，自己做好防范

**Comment by crazyd2sty** [comment]
> 有可能会，自己做好防范

用不用cf都是一样的,两个域名 我自己测试了一下 封的很快,而且只封域名不封IP

**Comment by MicroGalaxy** [comment]
把页面中ChatGPT的关键字去掉，然后用项目的放爬虫配置Nginx试试

**Comment by crazyd2sty** [comment]
> 把页面中ChatGPT的关键字去掉，然后用项目的放爬虫配置Nginx试试

我重新弄个镜像尝试一下,谢谢(*´I`*)

**Comment by daniel-8642** [comment]
我这里没遇到，稳定用了半年了。域名在国内备案，有ICP号就不会墙。

**Comment by Chanzhaoyu** [comment]
是不是在微信或者 QQ 这种地方分享了

**Comment by crazyd2sty** [comment]
> 是不是在微信或者 QQ 这种地方分享了

没有哦,只有自己和朋友用,我也觉得很奇怪
