### ISSUE TITLE
ChatGPT error 404

### ISSUE THREAD

**Issue by JackieHeCc** [Chanzhaoyu/chatgpt-web#1909]
在vps上面用docker compose搭建打开页面之后聊天提示：
ChatGPT error 404: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

不知道是哪里设置不对。

**Comment by daniel-8642** [comment]
前端部署对了，但是后端接口访问不到。
