### ISSUE TITLE
更了2.9怎么还是笨笨的机器人

### ISSUE THREAD

**Issue by binad2022** [Chanzhaoyu/chatgpt-web#191]
怎么搞到gpt-3.5-turbo呢？

**Comment by baby9** [comment]
花钱订阅plus，想要稳定优质的服务就加钱

**Comment by ludashi2020** [comment]
> 怎么搞到gpt-3.5-turbo呢？

使用token模式就好了

**Comment by CKylinMC** [comment]
> 花钱订阅plus，想要稳定优质的服务就加钱

我记得新注册用户不是有免费18刀的额度吗

**Comment by baby9** [comment]
> > 花钱订阅plus，想要稳定优质的服务就加钱
> 
> 我记得新注册用户不是有免费18刀的额度吗

对，只能调用几年前训练出来的模型，和现在官网的不一样

**Comment by CKylinMC** [comment]
> > > 花钱订阅plus，想要稳定优质的服务就加钱
> > 
> > 
> > 我记得新注册用户不是有免费18刀的额度吗
> 
> 对，只能调用几年前训练出来的模型，和现在官网的不一样

懂了，我刚刚去看了一下，确实都是0301的模型
