### ISSUE TITLE
当纯前端使用时，使用docker打包，实现 /api 转发到自己开发的后端服务 

### ISSUE THREAD

**Issue by vual** [Chanzhaoyu/chatgpt-web#1914]
只需要修改 Dockerfile，且把 nginx.conf 放到根目录，修改里面的proxy后端地址的指向，指到自己的后端地址。
VITE_GLOB_API_URL 和 VITE_APP_API_BASE_URL 无需修改。
原理就是，从node环境运行，换到nginx环境运行
格式不太对，自行调整下。

# Dockerfile  内容:

  FROM node:lts-alpine AS frontend
  
  RUN npm install pnpm -g
  
  WORKDIR /app
  
  COPY ./package.json /app
  
  COPY ./pnpm-lock.yaml /app
  
  RUN pnpm install
  
  COPY . /app
  
  RUN pnpm run build-only
  
  
  FROM nginx
  
  RUN rm /etc/nginx/conf.d/default.conf
  
  ADD ./nginx.conf /etc/nginx/conf.d/default.conf
  
  COPY --from=frontend /app/dist /data
  
  RUN /bin/bash -c 'echo init ok'

# nginx.conf 内容：

server {
    listen 80;
    server_name localhost;

    gzip on;
    gzip_static on; # 需要http_gzip_static_module 模块
    gzip_min_length 1k;
    gzip_comp_level 4;
    gzip_proxied any;
    gzip_types text/plain text/xml text/css;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    # 前端打包好的dist目录文件
    root /data/;

    location ^~/api/ {
        proxy_pass http://后端ip:端口/; #注意/后缀
        proxy_connect_timeout 60s;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }
}

**Comment by xahy123** [comment]
谢谢，解决了部署报错
