### ISSUE TITLE
使用 access token这种方式有什么注意事项吗？

### ISSUE THREAD

**Issue by xahy123** [Chanzhaoyu/chatgpt-web#1917]

**Comment by zhuxindong** [comment]
需要配置API_REVERSE_PROXY环境变量，目前推荐的社区代理有两个，详见 https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy 。我自己也搭建了一个，用的是ipv6的代理池，每次都是随机ip，https://openchat.geekgpt.site/backend-api/conversation
