### ISSUE TITLE
acheong08开发者的web api代理好像封禁了所有ip访问了，大家可以使用这个

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#192]
![QQ截图20230302140535.png](https://pic.shenbian.tv/2023/03/02/b75a259494495.png)

不知道是不是在更新维护

`https://chatgptapi.googlevideo.dev/api/conversation` 这个可用

**Comment by OwenTest** [comment]
这个也是超时。。。。

**Comment by ludashi2020** [comment]
> https://chatgptapi.googlevideo.dev/api/conversation
![QQ截图20230302142722.png](https://pic.shenbian.tv/2023/03/02/720a8834d4890.png)
正常啊

**Comment by Chanzhaoyu** [comment]
> 

确实是超时，我之前用过你的。但是一直没成功

**Comment by ludashi2020** [comment]
> > 
> 
> 确实是超时，我之前用过你的。但是一直没成功

应该是你的网络到cf ip超时了

**Comment by kissyouhunter** [comment]
> > https://chatgptapi.googlevideo.dev/api/conversation
> > ![QQ截图20230302142722.png](https://camo.githubusercontent.com/8389ec7299d1910c5695ec8d109502f665de80ca36ae5814a7486d31840304c0/68747470733a2f2f7069632e7368656e6269616e2e74762f323032332f30332f30322f373230613838333464343839302e706e67)
> > 正常啊

可以用，这两天一直在用。
像自己搭建一个。
但是大佬的repo里没看见怎么写搭建的过程

**Comment by ludashi2020** [comment]
https://chat.duti.tech/api/conversation 这个作者维护结束了，现在正常了
![QQ截图20230302195406.png](https://pic.shenbian.tv/2023/03/02/afd4ee3892896.png)
