### ISSUE TITLE
request to https://api.openai.com/v1/chat/completions failed, reason: Invalid SOCKS proxy details were provided

### ISSUE THREAD

**Issue by Mophee-ds** [Chanzhaoyu/chatgpt-web#1923]
我部署在我的nas，科学上网，能够正常访问外网，且也单独添加了API.openai.com网址到强制代理，但在Chat GPT Web中对话仍提示：
request to https://api.openai.com/v1/chat/completions failed, reason: Invalid SOCKS proxy details were provided

求助各位大神，谢谢

**Comment by RodisSevenW** [comment]
我也是这样，同求解法
