### ISSUE TITLE
access token经常失效，如果失效了我想更换token，应该怎么操作呢？

### ISSUE THREAD

**Issue by longwangjiang** [Chanzhaoyu/chatgpt-web#1926]
access token经常失效，如果失效了我想更换token就直接删除容器然后再建立，这种太麻烦了，有没有哪个文件是存放token的地方，我直接修改一下就可以使用的？谢谢！！！！

**Comment by CyJaySong** [comment]
docker compose 了解一下

**Comment by Emptyverse** [comment]
> access token经常失效，如果失效了我想更换token就直接删除容器然后再建立，这种太麻烦了，有没有哪个文件是存放token的地方，我直接修改一下就可以使用的？谢谢！！！！

直接用sealos部署 直接改配置参数
