### ISSUE TITLE
希望可以支持systemMessage的设置

### ISSUE THREAD

**Issue by 804701332** [Chanzhaoyu/chatgpt-web#193]
场景是：要在特定语境下调试systemMessage设置进去后，3.5的api的回复能力。
希望systemMessage这个字段可以在页面上设置

opts.systemMessage - Optional override for the chat "system message" which acts as instructions to the model (defaults to the ChatGPT system message)

**Comment by Chanzhaoyu** [comment]
这个会酌情设置哈

**Comment by zcong1993** [comment]
+1
