### ISSUE TITLE
nginx配置完成也无法流式是为什么？

### ISSUE THREAD

**Issue by PuddingJoker** [Chanzhaoyu/chatgpt-web#1931]
<img width="695" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/81021391/2a4be66c-1ae3-4eff-b69a-5130a946e329">

大佬们帮我看看！头疼死了

**Comment by bianjieops** [comment]
proxy_cache off;
                proxy_cache_bypass $http_pragma;
                proxy_cache_revalidate on;
                proxy_buffering off;

**Comment by PuddingJoker** [comment]
> ```
>            proxy_cache off;
>             proxy_cache_bypass $http_pragma;
>             proxy_cache_revalidate on;
>             proxy_buffering off;
> ```

还是不行
