### ISSUE TITLE
ChatGPT error 418: {"detail":{"message":"Client challenge required","code":"challenge_required"}}

### ISSUE THREAD

**Issue by 2233kkk** [Chanzhaoyu/chatgpt-web#1933]
报这个错是怎么回事？

**Comment by a97242689** [comment]
同样遇到，求大佬帮忙！！！！

**Comment by honggaowei** [comment]
我也是

**Comment by jindc123** [comment]
我也是，求方法

**Comment by 2233kkk** [comment]
好像是说没用人家官方的网页。。

**Comment by zjiuxin** [comment]
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later


我遇到了这个。。。

**Comment by zhangweijie97** [comment]
> [OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later
> 
> 我遇到了这个。。。

一模一样

**Comment by jindc123** [comment]
报错信息已经变了

**Comment by xiaonian233** [comment]
> [OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later
> 
> 我遇到了这个。。。

+1

**Comment by Chanzhaoyu** [comment]
今天 OpenAI 官方接口出问题了，现在应该修复了

**Comment by a180560** [comment]
> 今天 OpenAI 官方接口出问题了，现在应该修复了

大佬，现在gpt一直是思考中，是不是api反向代理流量过大？麻烦帮确认下呢

**Comment by 2233kkk** [comment]
> 今天 OpenAI 官方接口出问题了，现在应该修复了

好像又不行了，用token

**Comment by 2233kkk** [comment]
好了，openai在灰度测试，换账号

**Comment by GitHubChrisChen8035** [comment]
> 好了，openai在灰度测试，换账号

除了更换账号，还有其他办法么？
