### ISSUE TITLE
vps docker部署，一直报错429

### ISSUE THREAD

**Issue by daerdai** [Chanzhaoyu/chatgpt-web#1934]
ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}

**Comment by daerdai** [comment]
只加了一个环境变量：OPENAI_API_KEY=xxxxx

**Comment by daerdai** [comment]
怎么会有限额问题

**Comment by Emptyverse** [comment]
> ChatGPT error 429: { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }

用的有gpt4的api接口吗
