### ISSUE TITLE
accesstoken（已刷新过）的部署方式，忽然不能用了，反向代理也换过了，在官方网页那能看到我发的消息，但是没有回应的消息。

### ISSUE THREAD

**Issue by xiaosaaaa** [Chanzhaoyu/chatgpt-web#1936]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/115446601/d3923800-2eaa-40c2-99a3-c62770cb04a4)

**Comment by xiaosaaaa** [comment]
有一样的小伙伴吗？

**Comment by hub058** [comment]
我也是

**Comment by xiaosaaaa** [comment]
> 我也是
是和我的截图一样的错误提示吗？

**Comment by zjiuxin** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/96709612/909c339c-d438-4720-80fb-869ccca4cb3f)
一直在思考中

**Comment by xiaosaaaa** [comment]
@Chanzhaoyu 可否指导一下

**Comment by chounvwudi** [comment]
俺也是，感觉post数据变了，问题能提交到gpt，但是答案是空的。通过官方网站访问只有提问没有回答

**Comment by linxp001** [comment]
me too

**Comment by Mr-LJJ** [comment]
+1

**Comment by 2233kkk** [comment]
me too

**Comment by steinvenic** [comment]
+1

**Comment by BAISHUN0911** [comment]
10.23 22:49 accessToken和OPENAI_API_KEY都无法使用。一直显示“思考中”或者[好像出错了，请稍后再试。]

**Comment by catsimple** [comment]
https://github.com/zhile-io/pandora/issues/235#issuecomment-1774544557

**Comment by imfifc** [comment]
我也是

**Comment by imfifc** [comment]
> ![image](https://user-images.githubusercontent.com/115446601/277214936-d3923800-2eaa-40c2-99a3-c62770cb04a4.png)

问题找到了，是账号被封了，不是他的问题，换个账号，重新找下accessToken就ok了

**Comment by xiaosaaaa** [comment]
> > ![image](https://user-images.githubusercontent.com/115446601/277214936-d3923800-2eaa-40c2-99a3-c62770cb04a4.png)
> 
> 问题找到了，是账号被封了，不是他的问题，换个账号，重新找下accessToken就ok了

不是账号被封，账号登录官方是能用的，楼上发的链接说的对，某些账号触发验证了。

**Comment by a97242689** [comment]
+1 换过token也不行

**Comment by GitHubChrisChen8035** [comment]
+1

**Comment by DLOOODL** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/148837526/14220a71-7c6b-459d-a7b2-7a425cd9a55c)
项目是不是出bug了  api和token都测试成功   token代理入口关了，用api方式访问gpt 显示404
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/148837526/6b1db299-4727-40e7-aea6-8aaebe68af29)

**Comment by fenglindubu** [comment]
我也是

**Comment by XTxiaoting14332** [comment]
我感觉这个issue应该去反代api的作者那里提才有用（）

**Comment by xiaosaaaa** [comment]
> 我感觉这个issue应该去反代api的作者那里提才有用（）

现在弄清楚原因了，是应该在那边提。可是那边关了，没法提哈哈，谁认识能联系一下就好了，就让大佬们慢慢解决吧。

**Comment by XTxiaoting14332** [comment]
> > 我感觉这个issue应该去反代api的作者那里提才有用（）
> 
> 现在弄清楚原因了，是应该在那边提。可是那边关了，没法提哈哈，谁认识能联系一下就好了，就让大佬们慢慢解决吧。

我这边已经正常了 我觉得只要你停用一段时间就可以了

**Comment by xiaosaaaa** [comment]
> > > 我感觉这个issue应该去反代api的作者那里提才有用（）
> > 
> > 现在弄清楚原因了，是应该在那边提。可是那边关了，没法提哈哈，谁认识能联系一下就好了，就让大佬们慢慢解决吧。
> 
> 我这边已经正常了 我觉得只要你停用一段时间就可以了

我的已经好几天了，两个号都不行。

**Comment by huangjiarong** [comment]
我也不行好几天了，但是我的账号在官网是可以用的，我感觉是反代的问题，官网加了什么但是反代的大佬没更新。

**Comment by imfifc** [comment]
问题已解决，用fakeopen的反向代理，用新账号的accessToken
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/53161431/669eab3f-9d6c-468b-8f16-4fc691f10068)

**Comment by imfifc** [comment]
新账号要先登录openai,在官方对话几次，再去获取accesToken，才行

**Comment by linxp001** [comment]
应该主要是账号的问题，换个账号一般都能好。

**Comment by fenglindubu** [comment]
> 俺也是，感觉post数据变了，问题能提交到gpt，但是答案是空的。通过官方网站访问只有提问没有回答

我也感觉是这样，应该是 ai.fakeopen.com的问题

**Comment by Chanzhaoyu** [comment]
https://api.pawan.krd/backend-api/conversation 用这个替代下

**Comment by xiaosaaaa** [comment]
老毛病又出来了，每次一到星期六就炸代理，openai官方又在搞事情，pandora的代理也出问题了，我自己部署的也不行。

**Comment by Nordul** [comment]
又寄咯，openai是不是又在搞事

**Comment by eightreal** [comment]
我的也是这个状况， 有点奇怪
