### ISSUE TITLE
提示好像出错了，请稍后再试。

### ISSUE THREAD

**Issue by wp861010** [Chanzhaoyu/chatgpt-web#1937]
如题，提问回复：好像出错了，请稍后再试。什么原因？

**Comment by needhourger** [comment]
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later 

类似问题，日志显示
`ChatGPTError: ChatGPT error 403: {"cf_details":"Request is not allowed. Please try again later.", "type":"dc"}
    at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  statusText: 'Forbidden',
  [cause]: Response {
    size: 0,
    [Symbol(Body internals)]: {
      body: [BrotliDecompress],
      stream: [BrotliDecompress],
      boundary: null,
      disturbed: true,
      error: null
    },
    [Symbol(Response internals)]: {
      type: 'default',
      url: 'https://ai.fakeopen.com/api/conversation',
      status: 403,
      statusText: 'Forbidden',
      headers: [Object],
      counter: 0,
      highWaterMark: 16384
    }
  }
}`

**Comment by MicroGalaxy** [comment]
你是开通了Plus 然后用gpt-4模型吗

**Comment by needhourger** [comment]
> 你是开通了Plus 然后用gpt-4模型吗

plus已开通，openai官网使用没有问题，用本项目部署的3.5也没有问题，4.0报错

**Comment by MicroGalaxy** [comment]
> > 你是开通了Plus 然后用gpt-4模型吗
> 
> plus已开通，openai官网使用没有问题，用本项目部署基于openai官方api的3.5也没有问题，4.0报错

+1 估计是代理限制了
