### ISSUE TITLE
本地测试环境能运行，但云服务器不行

### ISSUE THREAD

**Issue by zhenianchuyu** [Chanzhaoyu/chatgpt-web#194]
![image](https://user-images.githubusercontent.com/53022996/222347029-940a7931-446f-4a5d-8f63-cbc06383ad23.png)
这是本地测试的，想着直接弄到服务器上，然后在服务器上安装了前置要求和依赖，测试时发现不成功
![image](https://user-images.githubusercontent.com/53022996/222347288-20f5164d-27ce-4835-801a-1f29654ebcea.png)

**Comment by Chanzhaoyu** [comment]
要不，我们不要用 `IE`...

**Comment by zhenianchuyu** [comment]
这样吗，好的我现在换个浏览器

**Comment by GeorgeGalway** [comment]
服务器上import pkg from '@/../package.json'失败，会报404错误，但是我很机智的给他注释了 @Chanzhaoyu

**Comment by zhenianchuyu** [comment]
> 服务器上import pkg from '@/../package.json'失败，会报404错误，但是我很机智的给他注释了 @Chanzhaoyu

请问是哪个文件呀？我现在好像就是报404错误

**Comment by Chanzhaoyu** [comment]
> > 服务器上import pkg from '@/../package.json'失败，会报404错误，但是我很机智的给他注释了 @Chanzhaoyu
> 
> 请问是哪个文件呀？我现在好像就是报404错误

可能你服务器不支持 json 文件，这个在设置里面用于显示当前版本，你把这些删了都可以，和功能不冲突。

**Comment by wlrwx** [comment]
> 要不，我们不要用 ...`IE`

感觉和ie没关系，从2.6以后就会这样，一直转点点，之前删了Config还正常，现在删了直接报错了。

**Comment by Chanzhaoyu** [comment]
> 

进入 `Setting/About.vue` 文件，删除以下代码

```vue
import pkg from '@/../package.json'

<h2 class="text-xl font-bold">
    Version - {{ pkg.version }}
</h2>
```

**Comment by wlrwx** [comment]
> 服务器上import pkg from '@/../package.json'失败，会报404错误，但是我很机智的给他注释了 @Chanzhaoyu

对了，好像就是json报错，哈哈

**Comment by wlrwx** [comment]
> > 
> 
> 进入 `Setting/About.vue` 文件，删除以下代码
> 
> ```
> import pkg from '@/../package.json'
> 
> <h2 class="text-xl font-bold">
>     Version - {{ pkg.version }}
> </h2>
> ```

谢谢🙏

**Comment by Chanzhaoyu** [comment]
> > > 
> > 
> > 
> > 进入 `Setting/About.vue` 文件，删除以下代码
> > ```
> > import pkg from '@/../package.json'
> > 
> > <h2 class="text-xl font-bold">
> >     Version - {{ pkg.version }}
> > </h2>
> > ```
> 
> 谢谢🙏

不客气

**Comment by zhenianchuyu** [comment]
> > 
> 
> 进入 `Setting/About.vue` 文件，删除以下代码
> 
> ```
> import pkg from '@/../package.json'
> 
> <h2 class="text-xl font-bold">
>     Version - {{ pkg.version }}
> </h2>
> ```

大佬，我是直接clone下来的代码，项目文件夹搜不到这个About.vue

**Comment by GeorgeGalway** [comment]
> 

看你的截图已经是老版本了，你更新代码试一下

**Comment by zhenianchuyu** [comment]
> > > > 
> > > 
> > > 
> > > 进入 `Setting/About.vue` 文件，删除以下代码
> > > ```
> > > import pkg from '@/../package.json'
> > > 
> > > <h2 class="text-xl font-bold">
> > >     Version - {{ pkg.version }}
> > > </h2>
> > > ```
> > 
> > 
> > 大佬，我是直接clone下来的代码，项目文件夹搜不到这个About.vue
> 
> 看你的截图已经是老版本了，你更新代码试一下

好家伙，两个小时之前更新了

**Comment by wanhaij** [comment]
![image](https://user-images.githubusercontent.com/82032645/222412055-10baeebb-f77b-4315-8f7c-ae330c441b3b.png)
使用测试模式可以打开，但是build之后就一直报404，注释掉了上面提到的About.vue文件中的那几行代码也没有用

**Comment by Chanzhaoyu** [comment]
> ![image](https://user-images.githubusercontent.com/82032645/222412055-10baeebb-f77b-4315-8f7c-ae330c441b3b.png) 使用测试模式可以打开，但是build之后就一直报404，注释掉了上面提到的About.vue文件中的那几行代码也没有用

正式环境去根目录的 `.env` 文件修改为真实地址

**Comment by Smeleo** [comment]
github好像没办法发布成功，已经修改成真实地址了，还是没办法用，大大有什么解决办法吗

**Comment by wanhaij** [comment]
之前就是按照说明修改成了真实地址，还是出现这种现象

> > ![image](https://user-images.githubusercontent.com/82032645/222412055-10baeebb-f77b-4315-8f7c-ae330c441b3b.png) 使用测试模式可以打开，但是build之后就一直报404，注释掉了上面提到的About.vue文件中的那几行代码也没有用
> 
> 正式环境去根目录的 `.env` 文件修改为真实地址

**Comment by kuxingdu** [comment]
> > 
> 
> 进入 `Setting/About.vue` 文件，删除以下代码
> 
> ```vue
> import pkg from '@/../package.json'
> 
> <h2 class="text-xl font-bold">
>     Version - {{ pkg.version }}
> </h2>
> ```

删除了好像也不行
😂
