### ISSUE TITLE
纯小白求助，built失败

### ISSUE THREAD

**Issue by yizhilangou** [Chanzhaoyu/chatgpt-web#1942]
sudo docker build -t chatgpt-web .
[+] Building 0.2s (2/2) FINISHED                                                                                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.1s
 => => transferring dockerfile: 2B                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                                                                        0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount745984645/Dockerfile: no such file or directory

**Comment by chehongchao** [comment]
Dockerfile的目录不对，可以用-f参数指定Dockerfile的绝对目录。例如：sudo docker build -t chatgpt-web -f Dockerfile绝对目录 .
