### ISSUE TITLE
好像访问不了，反向代理崩掉了

### ISSUE THREAD

**Issue by ghost** [Chanzhaoyu/chatgpt-web#1945]

**Comment by imfifc** [comment]
我也是

<p>你所访问的页面出错了！</p>
<p>可前往本站<a href="https://status.fakeopen.com/" target="_blank">服务状态页面</a>查看更多服务状态。</p>
<p><div class="cf-error-details cf-error-524">

**Comment by li258w** [comment]
有解了吗？

**Comment by GitHubChrisChen8035** [comment]
access token模式，使用默认反代，发现翻墙情况下，可以访问，但用国内网络，就打不开。
