### ISSUE TITLE
你们的代码有后门，偷取用户的access token卖给商家用

### ISSUE THREAD

**Issue by pospospos2007** [Chanzhaoyu/chatgpt-web#1946]
我查阅了一下chatgpt的聊天历史记录，发现了很多我没有发送的聊天。见图：
<img width="1088" alt="Screenshot 2023-10-28 030013" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/11675650/ce56fff5-23e0-4436-b09e-f4e4494de627">

**Comment by xiaosaaaa** [comment]
你的access token还在其他地方用过，或者你自己布置的网站没有设置密码，后门不存在的，用了大半年了从没这情况。

**Comment by wwlmm** [comment]
用了大半年 大半年了都和安全 没有所谓的后门

**Comment by Yang2635** [comment]
你自己设置密码了吗？你设置的密码是弱密码吗？

**Comment by pospospos2007** [comment]
好的，谢谢，我把密码改成复杂的，然后过短时间更新

**Comment by weareware** [comment]
睿智
