### ISSUE TITLE
请教如果不使用反向代理，如何设置？

### ISSUE THREAD

**Issue by antiblahblah** [Chanzhaoyu/chatgpt-web#1947]
如题，服务器可以直接访问openai，是否就可以不使用反向代理了？我看readme中写的是"可选"。
如果可以不使用，该如何设置，是直接注释API_REVERSE_PROXY行么？谢谢！

**Comment by li258w** [comment]
注释掉一样不行，我一直没有加这个参数，也不行了
ChatGPT error 524: <!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
<title>出错了</title>

</head>
<body>
<p>你所访问的页面出错了！</p>
<p>可前往本站<a href="https://status.fakeopen.com/" target="_blank">服务状态页面</a>查看更多服务状态。</p>
<p><div class="cf-error-details cf-error-524">
<h1>A timeout occurred</h1>
<p>The origin web server timed out responding to this request.</p>
...

**Comment by xiaosaaaa** [comment]
accesstoken的部署方式必须要用反代，apikey的部署是可以不用的，你不填就好了。

**Comment by 327078466** [comment]
微信小程序版的有啦 搜GF聊天
