### ISSUE TITLE
我是用的是access token,我有海外服务器怎么去除API_REVERSE_PROXY而不报错

### ISSUE THREAD

**Issue by shuaiBi903** [Chanzhaoyu/chatgpt-web#1951]
发现去除去除API_REVERSE_PROXY后报错,一直没找到报错的原因,按道理我海外的服务器是不需要代理的

**Comment by Yang2635** [comment]
access token走的是chat.openai.com接口，API走的是api.openai.com接口。chat.openai.com接口有CF认证，绕过CF是关键

**Comment by shuaiBi903** [comment]
好的,感谢回复

Yang2635 ***@***.***> 于2023年11月2日周四 13:51写道：
