### ISSUE TITLE
可以增加在前端更新OPENAI_ACCESS_TOKEN的功能吗

### ISSUE THREAD

**Issue by MDeath** [Chanzhaoyu/chatgpt-web#1957]
我用TrueNAS SCALE的容器部署，但是环境变量长度限制为1024，长了104个字符。
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/42289879/42090ebe-c93d-49c9-bff2-781b22570871)

**Comment by LandLinhangzhou** [comment]
我自己改了个出来，这个应该不是很难
<img width="1080" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/34364866/9b7768b5-8edd-482f-be6d-db834fd94d28">

**Comment by LandLinhangzhou** [comment]
@MDeath 
这个应该不是很难，前端加个输入框，后端再加一个替换变量的接口
<img width="965" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/34364866/59913310-0d03-44f4-ae35-db1010a0163c">

**Comment by MDeath** [comment]
😢没学过求教

**Comment by LandLinhangzhou** [comment]
@MDeath 
不会前端的话，可能是没法下手
