### ISSUE TITLE
Request is not allowed，ChatGPT error 403

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [Chanzhaoyu/chatgpt-web#1960]
ChatGPTError: ChatGPT error 403: {"cf_details":"Request is not allowed. Please try again later.", "type":"dc"}
    at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)

是不是默认的API_REVERSE_PROXY挂了？因为我自己手动登GPT官网，出来新的验证机制：左边是手势，右边是动物，要求调整动物的方向与手指向一致。

**Comment by ZevAlain** [comment]
我的是下面这个，可能是不是反代挂了？谁有能用的反代啊？
[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error

**Comment by wwlmm** [comment]
openai自己都挂了，等等吧

**Comment by ZevAlain** [comment]
> openai自己都挂了，等等吧

手机还能用。

**Comment by GitHubChrisChen8035** [comment]
昨天官网被DDOS攻击了，今天已恢复，关闭issue
