### ISSUE TITLE
为什么项目现在不能大陆线路访问，以前是可以的

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [Chanzhaoyu/chatgpt-web#1961]
项目是部署在洛杉矶VPS上，已经用了大半年了，但是上个月开始只能在翻墙条件下才可以打开，不明所以，是不是和API代理有关呢？

**Comment by 4ppp44** [comment]
IP被墙了呗

**Comment by GitHubChrisChen8035** [comment]
> IP被墙了呗

请教一下，怎么确认ip是否被墙？

**Comment by 4ppp44** [comment]
> > IP被墙了呗
> 
> 
> 
> 请教一下，怎么确认ip是否被墙？
> 
> 

https://mping.chinaz.com

**Comment by GitHubChrisChen8035** [comment]
> > > IP被墙了呗
> > 
> > 
> > 请教一下，怎么确认ip是否被墙？
> 
> https://mping.chinaz.com

ping都没问题，但是测速大部分都显示超时，是不是就是被墙了？

**Comment by 4ppp44** [comment]
> > > > IP被墙了呗
> 
> > > 
> 
> > > 
> 
> > > 请教一下，怎么确认ip是否被墙？
> 
> > 
> 
> > https://mping.chinaz.com
> 
> 
> 
> ping都没问题，但是测速大部分都显示超时，是不是就是被墙了？

是啊

**Comment by GitHubChrisChen8035** [comment]
> > > > > IP被墙了呗
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 请教一下，怎么确认ip是否被墙？
> > 
> > 
> > > 
> > 
> > 
> > > https://mping.chinaz.com
> > 
> > 
> > ping都没问题，但是测速大部分都显示超时，是不是就是被墙了？
> 
> 是啊

了解，谢谢！
