### ISSUE TITLE
求助，为什么报"You exceeded your current quota, please check your plan and billing details."的错误

### ISSUE THREAD

**Issue by bigtime1006** [Chanzhaoyu/chatgpt-web#1965]
我用chatgpt的客户端是能正常使用的，为什么用chatgpt-web就报这个错误提示了？
是哪里配置错误了吗？
ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}

**Comment by sunweixn** [comment]
api没费用了

**Comment by joelzzhang** [comment]
我也是遇到这个问题，大佬们怎么解决的，充值的话能行么，要是充值的话需要怎么弄

**Comment by bigtime1006** [comment]
> api没费用了

确实是.用一些非常规做法充值了以后好用了.
但是,第二天就被删帐号了.晕了
有谁能共用api吗?我用的不多,就是自己用来工作的时候用,费用可以商量,请联系我.

**Comment by wosicainiao** [comment]
买个key不就得了,一块钱用一个多月
