### ISSUE TITLE
有没有办法支持gpt-4-gizmo？

### ISSUE THREAD

**Issue by wumiann** [Chanzhaoyu/chatgpt-web#1967]
目前免费账户可以使用gpt-4-gizmo这个模型，进行GPT4的聊天和画图，但是配置以后会报错，只有官方网页版才可以用，有没有办法让这个程序支持这个模式啊

**Comment by headingy** [comment]
漏洞已经堵上了，免费用不了了。
付费支持gpt4也行啊，有没有办法？
