### ISSUE TITLE
数学公式渲染改进

### ISSUE THREAD

**Issue by touchtop** [Chanzhaoyu/chatgpt-web#1969]
首先感谢作者和其他贡献者的工作。
部署项目在小组内自用， 使用过程中公式方面的讨论较多，发现项目目前没有将laTex的 \[ ,\( 之类的包裹符转换为kaTex的 #, ##，就阅读了kaTex文档，发现在代码中 markdown-it 渲染部分用正则表达式进行替换即可，效果还不错。如下图：

![1700178852942](https://github.com/Chanzhaoyu/chatgpt-web/assets/32572336/6b75dd84-f1e8-4655-b886-54aa8eb59a0b)

**Comment by Yang2635** [comment]
你好，有改进教程吗
