### ISSUE TITLE
复制对话的一些优化建议

### ISSUE THREAD

**Issue by pengmaochang** [Chanzhaoyu/chatgpt-web#197]
当前返回的内容是多行时，一键复制聊天内容会忽略换行符。
1. 希望复制时能支持内容换行。
2. 希望增加复制为md的选项，方便使用
3. 希望代码块能像原生网页一样，有右上角复制按钮

**Comment by Chanzhaoyu** [comment]
`2.9.0` 支持复制格式换行，下个小版本添加代码块复制和当前代码语言显示

**Comment by Chanzhaoyu** [comment]
已更新
