### ISSUE TITLE
OPENAI_ACCESS_TOKEN 方式部署，页面提示报错

### ISSUE THREAD

**Issue by keeStep** [Chanzhaoyu/chatgpt-web#1971]
部署方式：
docker run --name chatgpt-web -d -p 80:3002 --env OPENAI_ACCESS_TOKEN=*********** chenzhaoyu94/chatgpt-web

报错内容：
request to https://bypass.churchless.tech/api/conversation failed, reason: getaddrinfo ENOTFOUND bypass.churchless.tech

**Comment by keeStep** [comment]
已解决。
docker早期镜像（4月的latest）的默认代理   https://bypass.churchless.tech/api/conversation 无法连接，更新设置代理：

>docker run --name chatgpt-web -d -p 80:3002 --env OPENAI_ACCESS_TOKEN=*********** --env API_REVERSE_PROXY=https://ai.fakeopen.com/api/conversation  chenzhaoyu94/chatgpt-web

**Comment by cryboy007** [comment]
> 已解决。 docker早期镜像（4月的latest）的默认代理 https://bypass.churchless.tech/api/conversation 无法连接，更新设置代理：
> 
> > docker run --name chatgpt-web -d -p 80:3002 --env OPENAI_ACCESS_TOKEN=*********** --env API_REVERSE_PROXY=https://ai.fakeopen.com/api/conversation  chenzhaoyu94/chatgpt-web

现在应该不行了
