### ISSUE TITLE
更多的 LaTeX

### ISSUE THREAD

**Issue by chokiproai** [Chanzhaoyu/chatgpt-web#1972]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/128912789/2f29a049-14d3-4ac5-92f5-69bbf7e699e4)

**Comment by Yang2635** [comment]
解决了吗，公式渲染问题，最近我也遇到了

**Comment by chokiproai** [comment]
> Referen

有时有效，需要解决这个问题
