### ISSUE TITLE
ChatGPT error 429: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}

### ISSUE THREAD

**Issue by zzzzzwww** [Chanzhaoyu/chatgpt-web#1975]
ChatGPT error 429: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}

**Comment by Danborad** [comment]
我也是一样，就是不想用这个pandora才用这个web，为什么会提示这个

**Comment by jamesyoung233** [comment]
我也是这样，怎么解决？

**Comment by JerryFoundation** [comment]
之前有个帖子不见了

**Comment by ZevAlain** [comment]
[#1973](https://github.com/Chanzhaoyu/chatgpt-web/issues/1973) 旧贴

**Comment by GJXS1980** [comment]
想要用docker自建代理教程可以参考[ChatGPT 不让你说话？如何绕过 IP 拦截？](http://www.aigrantli.com/archives/%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86),亲自测试没有问题。

**Comment by xavier-xu99** [comment]
> 确实是反向代理问题，想要用docker自建代理教程可以参考[突破网络封锁：在国内使用ChatGPT的方法](http://www.aigrantli.com/archives/%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86),亲自测试用自己的反向代理没有问题。

所以, 只能用国外的服务器是吗? 国内的云服务器是否可行?
