### ISSUE TITLE
如何使用azure openai key?

### ISSUE THREAD

**Issue by taozhiyuai** [Chanzhaoyu/chatgpt-web#1978]
如何使用azure openai key?

**Comment by taozhiyuai** [comment]
另外，如果用oneapi， 启动的时候提供oneapi key， .env已经配置oneapi base, 但是会提示key错误。

**Comment by zhangchengwen629** [comment]
自己把环境配一下用自己网址

**Comment by lanceli93** [comment]
@taozhiyuai https://www.cnblogs.com/stulzq/p/17271937.html
