### ISSUE TITLE
我看有中韩英，没有日语的，需要弄吗？

### ISSUE THREAD

**Issue by bigtime1006** [Chanzhaoyu/chatgpt-web#1979]

**Comment by eburnette** [comment]
You will need to fork the project, add a Japanese localization yourself and submit a PR to add it back to the main source. If you search for "ko-KR", just add a case for "ja-JP" in each of those places, and also add https://github.com/Chanzhaoyu/chatgpt-web/tree/main/src/locales/ja-JP.ts . You can use ChatGPT or Github Copilot to create the translation (start with en-US or zh-CN) and then verify it by hand.

**Comment by xlcodes** [comment]
有没有可能是作者不想整

**Comment by ghost** [comment]
> 有没有可能是作者不想整

我觉得是的
