### ISSUE TITLE
链接自动的问题

### ISSUE THREAD

**Issue by hfpp2012copy** [Chanzhaoyu/chatgpt-web#198]
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/39046778/222368949-9139fea8-b75f-4fe2-bdfb-b7ff68941d6e.png">

这个链接有点问题

<img width="682" alt="image" src="https://user-images.githubusercontent.com/39046778/222369058-e86b646f-c45c-4018-8c22-aead5c0b6b94.png">

**Comment by Chanzhaoyu** [comment]
感谢反馈，但是优先级排后
