### ISSUE TITLE
请问ChatGPT error 429: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}

### ISSUE THREAD

**Issue by hanhunhan** [Chanzhaoyu/chatgpt-web#1980]
提示这个错误应该怎么解决

**Comment by RedCarl** [comment]
+1

**Comment by ibingdian** [comment]
+1

**Comment by thlearncom** [comment]
那个服务停了，需要你自己部署一个pandoranext的服务，然后在本项目的变量中指明你部署的pandoranext服务地址，具体见那边的文档

**Comment by chouniu666** [comment]
> 那个服务停了，需要你自己部署一个pandoranext的服务，然后在本项目的变量中指明你部署的pandoranext服务地址，具体见那边的文档

大佬，说具体点，如果本地搭建好了，如何在这边更改服务地址？

**Comment by 1154761334** [comment]
非常感谢您的回答

> > > 那个服务停了，需要你自己部署一个pandoranext的服务，然后在本项目的变量中指明你部署的pandoranext服务地址，具体见那边的文档
> > 
> > 
> > 大佬，说具体点，如果本地搭建好了，如何在这边更改服务地址？
> 
> 这个项目有个参数，是API_REVERSE_PROXY，默认是[https://ai.fakeopen.com/api/conversation，部署的时候给它设置你实际的pandoranext地址，类似这样的https://xxxxxxx/backend-api/conversation。](https://ai.fakeopen.com/api/conversation%EF%BC%8C%E9%83%A8%E7%BD%B2%E7%9A%84%E6%97%B6%E5%80%99%E7%BB%99%E5%AE%83%E8%AE%BE%E7%BD%AE%E4%BD%A0%E5%AE%9E%E9%99%85%E7%9A%84pandoranext%E5%9C%B0%E5%9D%80%EF%BC%8C%E7%B1%BB%E4%BC%BC%E8%BF%99%E6%A0%B7%E7%9A%84https://xxxxxxx/backend-api/conversation%E3%80%82) 注意PandoraNext项目的部署要选择proxy模式，具体的你去那边看文档就行。

非常感谢您的回答

**Comment by jindc123** [comment]
+1

**Comment by musaart** [comment]
我也遇到这个问题

**Comment by zlianzhuang** [comment]
> 作者关闭了fakeopen代理，PandoraNext可以部署代理，https://www.aimini.top/article/971c8dbe-1be8-4b02-bbdc-8125feae50d9

那就只能自己搭建代理了么？ 那好麻烦啊。

**Comment by 804782069** [comment]
> > 作者关闭了fakeopen代理，PandoraNext可以部署代理，https://www.aimini.top/article/971c8dbe-1be8-4b02-bbdc-8125feae50d9
> 
> 那就只能自己搭建代理了么？ 那好麻烦啊。

哈哈，部署还简单的，或者使用别人部署好的代理地址。PandoraNext有两种模式可以选择，可以部署web直接访问、或者部署作为代理其它web使用。
