### ISSUE TITLE
Integration request

### ISSUE THREAD

**Issue by Torhamilton** [Chanzhaoyu/chatgpt-web#1981]
Hi,
OpenAI has a context paradox problem, we are solving it. Let's work together.
https://twitter.com/GPT_Brancher/status/1728976732118520158
Demo site:
https://www.gptbrancher.com/

DM us on twitter.
Sorry only way to reach you.

**Comment by assassinliujie** [comment]
looks like some saving points like the galgame

**Comment by Torhamilton** [comment]
Yes. Just a demo for now. How do I bring you onboard? wanna DM me on twitter?
