### ISSUE TITLE
ChatGPT error 429 错误

### ISSUE THREAD

**Issue by musaart** [Chanzhaoyu/chatgpt-web#1984]
ChatGPT error 429有没有别的方法，如果再部署一个PandoraNext那不是脱裤子放屁多此一举么，那玩意本身就带web界面啊

**Comment by xuxiang19961203** [comment]
> 作者关闭了fakeopen代理，PandoraNext可以部署代理，https://www.aimini.top/article/971c8dbe-1be8-4b02-bbdc-8125feae50d9

你好, 请问这个服务器是需要可以访问chatgpt的服务器吗?? 还是国内的云服务器就行呢?

**Comment by wwlmm** [comment]
> ChatGPT error 429有没有别的方法，如果再部署一个PandoraNext那不是脱裤子放屁多此一举么，那玩意本身就带web界面啊

PandoraNext还自带Proxy模式。你就可以通过Proxy调用接口了。
