### ISSUE TITLE
这个速度真快，代码框也能复制。仿官版

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#199]
https://freechatgpt.lol/
![QQ截图20230302161116.png](https://pic.shenbian.tv/2023/03/02/fa50d42c9cc37.png)

**Comment by Chanzhaoyu** [comment]
如果卖源码，我可能比他做的更好 😄

**Comment by pengmaochang** [comment]
他这个是否完全免费呢，如果是，其API数量撑得住吗；
而且，咱们项目改改，直接从他这走，是不是也可以哈哈哈哈哈

**Comment by ludashi2020** [comment]
> 他这个是否完全免费呢，如果是，其API数量撑得住吗； 而且，咱们项目改改，直接从他这走，是不是也可以哈哈哈哈哈

他这个是套娃版的。做自己的最好。

**Comment by ccquan** [comment]
试了下，确实快，但智能程度跟web的那个还是区别

**Comment by hnuzhoulin** [comment]
api的速度是很快 ，但是回答的内容不太行

**Comment by binwang672012** [comment]
这速度，比网页版爽太多了

**Comment by movingcity** [comment]
他这个快是因为用的model是text-davinci-002-render

**Comment by hnuzhoulin** [comment]
已经挂了

**Comment by CKylinMC** [comment]
> 已经挂了

好像又起了，页面最下面还标了`Developed using gpt-3.5-turbo API.`

**Comment by jasonZenith** [comment]
这个好像又挂了

**Comment by CKylinMC** [comment]
> 这个好像又挂了

访问的时候网址自动跳到 https://freegpt.one/ 并且过了一次cloudflare，但是我这里看最终是能打开的...
<details>
<summary>scrshot</summary>


![image](https://user-images.githubusercontent.com/11648014/222655669-2cd3195d-c902-4d7f-8891-83d5f7e9b6e8.png)


</details>

怀疑访问不稳定或者是cf过滤所以有的地方打不开？

**Comment by eysam** [comment]
想问个问题，就是我们https://github.com/Chanzhaoyu/chatgpt-web这个如何才能够像他的那样一个字一个字地输出结果呢，而非现在这样整篇内容输出😊

**Comment by CKylinMC** [comment]
> 想问个问题，就是我们[https://github.com/Chanzhaoyu/chatgpt-web这个如何才能够像他的那样一个字一个字地输出结果呢，而非现在这样整篇内容输出😊](https://github.com/Chanzhaoyu/chatgpt-web%E8%BF%99%E4%B8%AA%E5%A6%82%E4%BD%95%E6%89%8D%E8%83%BD%E5%A4%9F%E5%83%8F%E4%BB%96%E7%9A%84%E9%82%A3%E6%A0%B7%E4%B8%80%E4%B8%AA%E5%AD%97%E4%B8%80%E4%B8%AA%E5%AD%97%E5%9C%B0%E8%BE%93%E5%87%BA%E7%BB%93%E6%9E%9C%E5%91%A2%EF%BC%8C%E8%80%8C%E9%9D%9E%E7%8E%B0%E5%9C%A8%E8%BF%99%E6%A0%B7%E6%95%B4%E7%AF%87%E5%86%85%E5%AE%B9%E8%BE%93%E5%87%BA%F0%9F%98%8A)

直接使用API模式而不是accesstoken，或者不使用accesstoken模式下的api proxy，好像就可以一个字一个字的输出。

**Comment by eysam** [comment]
> > 想问个问题，就是我们[https://github.com/Chanzhaoyu/chatgpt-web这个如何才能够像他的那样一个字一个字地输出结果呢，而非现在这样整篇内容输出😊](https://github.com/Chanzhaoyu/chatgpt-web%E8%BF%99%E4%B8%AA%E5%A6%82%E4%BD%95%E6%89%8D%E8%83%BD%E5%A4%9F%E5%83%8F%E4%BB%96%E7%9A%84%E9%82%A3%E6%A0%B7%E4%B8%80%E4%B8%AA%E5%AD%97%E4%B8%80%E4%B8%AA%E5%AD%97%E5%9C%B0%E8%BE%93%E5%87%BA%E7%BB%93%E6%9E%9C%E5%91%A2%EF%BC%8C%E8%80%8C%E9%9D%9E%E7%8E%B0%E5%9C%A8%E8%BF%99%E6%A0%B7%E6%95%B4%E7%AF%87%E5%86%85%E5%AE%B9%E8%BE%93%E5%87%BA%F0%9F%98%8A)
> 
> 直接使用API模式而不是accesstoken，或者不使用accesstoken模式下的api proxy，好像就可以一个字一个字的输出。

本地启动。。。就能一个字一个字输出，如果是docker启动就不行😅
