### ISSUE TITLE
部署了一下测试提示报错

### ISSUE THREAD

**Issue by maojianyou** [Chanzhaoyu/chatgpt-web#1995]
报错内容
ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}

**Comment by deary777** [comment]
You exceeded your current quota.
超过限额，可能是超过了日请求上限，api也有额度限制，可以进入官网api模块下的usage确认配额

**Comment by deary777** [comment]
You exceeded your current quota.
超过限额，可能是超过了日请求上限，api也有额度限制，可以进入官网api模块下的usage确认配额
