### ISSUE TITLE
Pandora也装了API_REVERSE_PROXY也配置了，还是报错

### ISSUE THREAD

**Issue by sandnul025** [Chanzhaoyu/chatgpt-web#1999]
![1702894040351](https://github.com/Chanzhaoyu/chatgpt-web/assets/23227136/a5584cc9-b48a-46aa-a35d-091cd7c99407)
![1702894118930](https://github.com/Chanzhaoyu/chatgpt-web/assets/23227136/1f415020-11e4-483c-8328-2f53ccfcf225)
![1702894169440](https://github.com/Chanzhaoyu/chatgpt-web/assets/23227136/f0e27679-4b8c-421d-81a5-c843fd878e09)
OPENAI_ACCESS_TOKEN是最新的
所以为什么报错

**Comment by ttwo22** [comment]
一样的原因

**Comment by Yang2635** [comment]
使用Proxy的接口模式
