### ISSUE TITLE
这个跟原版的回答差很多，应该不是原版接口

### ISSUE THREAD

**Issue by chendimao** [Chanzhaoyu/chatgpt-web#2]

**Comment by Chanzhaoyu** [comment]
这个问题是因为网页版用的是单独的语言模型 GPT 3.5，目前还没有在 OpenAI Api 中公开。

现在能调用的是公开的 GPT-3 。如果需要像网页版的效果一样，需要去预约等候列表开通 Plus 版本。

**Comment by Chanzhaoyu** [comment]
其实归结到底就是，充钱就会变强，哈哈哈

**Comment by chendimao** [comment]
谢谢，了解了。

**Comment by Chanzhaoyu** [comment]
添加了上下文联想，现在功能应该会好很多。

**Comment by 7757** [comment]
> 

我刚刚充值了chatgpt-puls 是不是不需要跟换任何东西就能使用了？

**Comment by Chanzhaoyu** [comment]
> > 
> 
> 我刚刚充值了chatgpt-puls 是不是不需要跟换任何东西就能使用了？

可是官方应该还没有推出模型参数，plus 目前好像只能网页用
