### ISSUE TITLE
反代出问题

### ISSUE THREAD

**Issue by T0ybox** [Chanzhaoyu/chatgpt-web#2002]
request to http://vps-ip:7999/backend-api/conversation failed, reason: getaddrinfo ENOTFOUND  vps-ip

**Comment by T0ybox** [comment]
request to http://vps-ip:port/backend-api/conversation failed, reason: Proxy connection timed out 这两问题是啥呀

**Comment by T0ybox** [comment]
request to http://vps:port/backend-api/conversation failed, reason: socket hang up
这又是啥问题

**Comment by null0034** [comment]
你这反代地址没有啊

**Comment by T0ybox** [comment]
已经解决了  反代地址我只是没写



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月26日 01:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Chanzhaoyu/chatgpt-web] 反代出问题 (Issue #2002) |

你这反代地址没有啊
