### ISSUE TITLE
困惑，ChatGPT error 429

### ISSUE THREAD

**Issue by yefeiyu** [Chanzhaoyu/chatgpt-web#2003]
我直接docker一键运行的，api也填写正确了，怎么就提示下面的错误呢？
我是买的官方的plus，使用官网的网址登陆正常使用中啊。。。

ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}

**Comment by skycxp** [comment]
insufficient_quota 配额不足，你没有额度了。你用的是apiKey，这个是需要额度的，你改成accessToken。
