### ISSUE TITLE
疑问：回答的结果和官方回答有差异

### ISSUE THREAD

**Issue by kilvn** [Chanzhaoyu/chatgpt-web#201]
问题：

```text
mysql 表中存储的字段形式如:
第一行 meal 字段: HB,BB
第二行 meal 字段: BB
第三行 meal 字段: AI
第四行 meal 字段: HB

laravel 怎么查询包含 HB 或 BB 的行
```

朋友发的官方回答：

<img width="847" alt="image" src="https://user-images.githubusercontent.com/16423601/222377860-32b4f7fd-ac38-4691-a0c0-98d4a0064501.png">

我用自己部署的回答：

![image](https://user-images.githubusercontent.com/16423601/222377946-6dae7bba-5d1f-4329-80f2-f8dc0d9b9f1d.png)

![image](https://user-images.githubusercontent.com/16423601/222377964-470b2003-1c8d-47a6-88aa-5cb730a988ef.png)

部署的时候 release 是  v.2.9.0，通过 Railway模版部署的，只填了OPENAI_API_KEY。

可以看到官方的回答考虑到了英文逗号 , 连接的情况，这个时候不能用 whereIn，用like不够精准，用 find_in_set 可以解决这个问题，但是我问了好几遍，他的回答都是错误的，不知道目前用的API和官方的有什么差别？

**Comment by Chanzhaoyu** [comment]
`API` 形式都 `3.5` 和官网的 `3.5` 不能相提并论
