### ISSUE TITLE
兼容官方新出gpt3.5

### ISSUE THREAD

**Issue by 6uu1** [Chanzhaoyu/chatgpt-web#202]
听说速度很快，请作者大大更新一下

**Comment by ottocsb** [comment]
已经是了，拉取重新部署下

**Comment by Joke-csgo** [comment]
> 已经是了，拉取重新部署下

请问作者大大，docker部署的有需要更改啥的么

**Comment by ottocsb** [comment]
我不是作者，不需要更改什么配置

**Comment by pengmaochang** [comment]
`docker-compose down
docker-compose pull
docker-compose up -d
`

**Comment by pengmaochang** [comment]
```
docker-compose down
docker-compose pull
docker-compose up -d
```
这样就能拉到最新的gpt3.5镜像了

**Comment by Limour-dev** [comment]
> 已经是了，拉取重新部署下

# Note: you need to be using OpenAI Python v0.27.0 for the code below to work
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

1、请问可以像这个的{"role": "system", "content": "You are a helpful assistant."}一样，自定义role为system的content吗？
2、请问可以修改temperature、top_p、max_tokens、presence_penalty、frequency_penalty、logit_bias、user这些额外的参数吗？

**Comment by Chanzhaoyu** [comment]
> > 已经是了，拉取重新部署下
> 
> # Note: you need to be using OpenAI Python v0.27.0 for the code below to work
> import openai
> 
> openai.ChatCompletion.create( model="gpt-3.5-turbo", messages=[ {"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "Who won the world series in 2020?"}, {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."}, {"role": "user", "content": "Where was it played?"} ] )
> 
> 1、请问可以像这个的{"role": "system", "content": "You are a helpful assistant."}一样，自定义role为system的content吗？ 2、请问可以修改temperature、top_p、max_tokens、presence_penalty、frequency_penalty、logit_bias、user这些额外的参数吗？

可以在服务端自行添加参数
