### ISSUE TITLE
还是超时啊-怎么办呢

### ISSUE THREAD

**Issue by ykshao** [Chanzhaoyu/chatgpt-web#2020]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/13257015/f63a7c86-a971-4062-bd36-54f926232767)

**Comment by ykshao** [comment]
用的 最新的代码啊, 需要什么特殊配置吗?? 我使用的是 docker 的项目镜像

**Comment by unclehu87** [comment]
自建反代 https://github.com/dqzboy/ChatGPT-Proxy
