### ISSUE TITLE
对于GPT-4 Vision Preview模型的支持

### ISSUE THREAD

**Issue by Type-32** [Chanzhaoyu/chatgpt-web#2034]
使用GPT-4 Vision Preview模型时能有个上传图片的功能

**Comment by yxlspider** [comment]
> 使用GPT-4 Vision Preview模型时能有个上传图片的功能

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/38686017/19f7a830-5867-4358-8b23-a97586daf2fb)
gpt4怎么使用的,能教我下吗   我的配置如上图  没生效   我的apikey是支持gpt4的
