### ISSUE TITLE
可以提供新的反向代理吗？

### ISSUE THREAD

**Issue by imfifc** [Chanzhaoyu/chatgpt-web#2037]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/53161431/af2d154c-4245-4628-b1a1-bf89b31d72b6)
fakeopen 的反向代理不行了

**Comment by xionggd** [comment]
同求方案

**Comment by justincnn** [comment]
同求方案，自己搭建，

**Comment by liguobao** [comment]
没必要非要用这种反代吧，直接用一些转发代理不就好了？

**Comment by lnxknl** [comment]
ninja方案可以用吗？前面部署可以用，现在没有回复。

**Comment by NaughtyQi** [comment]
> 没必要非要用这种反代吧，直接用一些转发代理不就好了？

举一两个例子🫥

**Comment by liguobao** [comment]
> > 没必要非要用这种反代吧，直接用一些转发代理不就好了？
> 
> 举一两个例子🫥

https://github.com/chatanywhere/GPT_API_free

这种转发代理，按Token计费的。
