### ISSUE TITLE
功能增强——加了一些画图联网识图等功能

### ISSUE THREAD

**Issue by liyf1** [Chanzhaoyu/chatgpt-web#2040]
仓库在这里：https://github.com/liyf1/CHATGPT-WEB，wiki晚点改下
加了以下的功能：
1、支持使用mj画图
2、支持插件功能
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/49024327/e2e83b55-df80-4a73-b880-fe2acc7f7a88)
<img width="1172" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/49024327/80ba3ff1-f348-4228-ae41-31f0d9b1da02">
<img width="1224" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/49024327/e84ac7d3-5d7e-4bec-81b8-f5732cb74c21">
3、支持对上传的图片进行解析
4、添加权限功能，这个功能是在别人的分支基础上修改的chatgpt-web-dev/chatgpt-web

**Comment by liyf1** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/49024327/359ba473-7300-477d-a793-c04ff372cb21)

**Comment by liyf1** [comment]
<img width="779" alt="image" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/49024327/0456696b-de4a-4d2b-b810-743eb00a758d">

**Comment by liyf1** [comment]
你用这个镜像启动下 a419820659/chatgpt-web-plus

**Comment by JerryFoundation** [comment]
启动不了
