### ISSUE TITLE
使用Ninja也不行了

### ISSUE THREAD

**Issue by Superqinqing** [Chanzhaoyu/chatgpt-web#2041]
上周六还行的，我一直使用ninja进行代理转发，使用的是AccessToken，这两天突然不行了，真不知道为啥，是OpenAI官方做了限制了，吗，我发现问的问题在官方的问题列表里是有显示的，并且也有返回，现在不知道啥问题了不行了

**Comment by zhangweijie97** [comment]
协议改了，目前只能等大佬适配

**Comment by Superqinqing** [comment]
> 协议改了，目前只能等大佬适配
目前还有哪个项目是可以使用AccessToken的项目的吗

**Comment by justincnn** [comment]
应该是ninja不行了，不是这里不行了

**Comment by JerryFoundation** [comment]
根据把go-chatgpt-api fork出来跑起来发现， https://chat.openai.com/backend-api/conversation  已经变成了 wss 不是http了， 所以需要改源码支持，  我尝试弄一下
<img width="880" alt="截屏2024-02-23 19 38 48" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/10803410/f784a8ca-82dd-466b-80ad-878ad50fa36e">

**Comment by Superqinqing** [comment]
> 根据把go-chatgpt-api fork出来跑起来发现， https://chat.openai.com/backend-api/conversation 已经变成了 wss 不是http了， 所以需要改源码支持， 我尝试弄一下 <img alt="截屏2024-02-23 19 38 48" width="880" src="https://private-user-images.githubusercontent.com/10803410/307309114-f784a8ca-82dd-466b-80ad-878ad50fa36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTE2MDcsIm5iZiI6MTcwODY5MTMwNywicGF0aCI6Ii8xMDgwMzQxMC8zMDczMDkxMTQtZjc4NGE4Y2EtODJkZC00NjZiLTgwYWQtODc4YWQ1MGZhMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEyMjgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZDc2MWVmZWY5NGQyMTI3MzI4NzFlMzVkMzJmNTg5NTk2ZjAyMjg0NzE4MTIyZDEzYWYxMjM4NDJkM2M2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MLEBkSrMtTmGM5_V-sN4sg2t_OzZ0P38EHcB5JkYoSY">
现在有啥能替换Ninja的代理吗

**Comment by Superqinqing** [comment]
Ninja 那个项目好像闭源了

**Comment by JerryFoundation** [comment]
已经解决了， 用这个镜像反代

docker run -d --name go-chatgpt-api \
  -p 8080:8080 \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e TZ=Asia/Shanghai \
  -e PROXY= \
  -e ARKOSE_TOKEN_URL= \
  -e BX= \
  -e BX_URL= \
  -e OPENAI_EMAIL= \
  -e OPENAI_PASSWORD= \
  -e CONTINUE_SIGNAL= \
  --restart unless-stopped \
  maxduke/go-chatgpt-api

**Comment by JerryFoundation** [comment]
> 已经解决了， 用这个镜像反代
> 
> docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api

代理地址设置为：
http://{{ip}}:8080/chatgpt/backend-api/conversation

**Comment by justincnn** [comment]
> 已经解决了， 用这个镜像反代
> 
> docker run -d --name go-chatgpt-api \
>   -p 8080:8080 \
>   -v /var/run/docker.sock:/var/run/docker.sock:ro \
>   -e TZ=Asia/Shanghai \
>   -e PROXY= \
>   -e ARKOSE_TOKEN_URL= \
>   -e BX= \
>   -e BX_URL= \
>   -e OPENAI_EMAIL= \
>   -e OPENAI_PASSWORD= \
>   -e CONTINUE_SIGNAL= \
>   --restart unless-stopped \
>   maxduke/go-chatgpt-api

这个项目的地址在哪里？我记得go chatgpt api差不多名字的，原作者好像停止更新好长时间了

**Comment by Superqinqing** [comment]
> > 已经解决了， 用这个镜像反代
> > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> 
> 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation

大佬，牛逼，可以了

**Comment by 2018ybq** [comment]
> 已经解决了， 用这个镜像反代
> 
> docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/40756807/548f3704-b1da-4170-9f4e-cf6c234253f9)
访问报这个是什么原因

**Comment by CrossStone** [comment]
> 已经解决了， 用这个镜像反代
> 
> docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api

真的好用了，大佬怎么改的

**Comment by 2018ybq** [comment]
> > 已经解决了， 用这个镜像反代
> > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> 
> 真的好用了，大佬怎么改的

version: "3"
services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080         # 容器端口映射到宿主机8080端口；宿主机监听端口可按需改为其它端口
    #network_mode: host   # 可选，将容器加入主机网络模式，即与主机共享网络命名空间；上面的端口映射将失效
    environment:
      - PORT=
      - TZ=Asia/Shanghai
      - PROXY=                   # PROXY=：可配置科学上网代理地址，例如：http://clash_vpsIP:7890；注释掉或者留空则不启用
      - ARKOSE_TOKEN_URL=
      - OPENAI_EMAIL=
      - OPENAI_PASSWORD=
      - CONTINUE_SIGNAL=         # CONTINUE_SIGNAL=1，开启/imitate接口自动继续会话功能，留空关闭，默认关闭
      - ENABLE_HISTORY=
      - IMITATE_ACCESS_TOKEN=
    volumes:
      - ./chat.openai.com.har:/app/chat.openai.com.har
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

# IP被Ban，提示Access denied之类的报错，可尝试使用warp，把注释取消
  #chatgpt-proxy-server-warp:
  #  container_name: chatgpt-proxy-server-warp
  #  image: linweiyuan/chatgpt-proxy-server-warp
  #  environment:
  #    - LOG_LEVEL=OFF
  #  restart: unless-stopped

我用的这个，但是报403
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/40756807/d149fa3b-ac67-44bd-a041-1652ef30926d)

**Comment by dearfaint** [comment]
> > > 已经解决了， 用这个镜像反代
> > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > 
> > 
> > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> 
> 大佬，牛逼，可以了

求大概教程，我docker布置提示Error: please put HAR files in harPool directory! 谢谢

**Comment by justincnn** [comment]
> > > > 已经解决了， 用这个镜像反代
> > > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > > 
> > > 
> > > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> > 
> > 大佬，牛逼，可以了
> 
> 求大概教程，我docker布置后日志提示Error: please put HAR files in harPool directory! 谢谢

https://newchato.eu.org/2024/02/24/Irregular-updates-Reverse-engineered-ChatGPT-proxy/


你可以看下这个，以easydict为例的配置

**Comment by ssssshql** [comment]
> > > > 已经解决了， 用这个镜像反代
> > > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > > 
> > > 
> > > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> > 
> > 
> > 大佬，牛逼，可以了
> 
> 求大概教程，我docker布置后日志提示Error: please put HAR files in harPool directory! 谢谢

你好，你这个解决了吗我也这样子

**Comment by mianqiangsheng** [comment]
> please put HAR files in harPool directory!

能否给一个详细点的回答？小白不是很懂呀

**Comment by mianqiangsheng** [comment]
> > > > > 已经解决了， 用这个镜像反代
> > > > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > > > 
> > > > 
> > > > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> > > 
> > > 
> > > 大佬，牛逼，可以了
> > 
> > 
> > 求大概教程，我docker布置后日志提示Error: please put HAR files in harPool directory! 谢谢
> 
> https://newchato.eu.org/2024/02/24/Irregular-updates-Reverse-engineered-ChatGPT-proxy/
> 
> 你可以看下这个，以easydict为例的配置

能否给一个详细点的回答？小白不是很懂呀。谢谢指教！

**Comment by mianqiangsheng** [comment]
> > > > > 已经解决了， 用这个镜像反代
> > > > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > > > 
> > > > 
> > > > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> > > 
> > > 
> > > 大佬，牛逼，可以了
> > 
> > 
> > 求大概教程，我docker布置后日志提示Error: please put HAR files in harPool directory! 谢谢
> 
> 你好，你这个解决了吗我也这样子

参考作者维护的源码。主要就是作者把har文件映射目录改了下，变成了“/app/harPool”

**Comment by PhiBrain-ZhaoLiang** [comment]
现在ninja docker镜像都没有了，怎么解决？

docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api 已经尝试，看起来无法使用

**Comment by potoo0** [comment]
我的 ninja 为啥一直都没有问题，是我的版本太旧了吗？我最近没有更新过，现在版本是 *0.9.36*

**Comment by PhiBrain-ZhaoLiang** [comment]
> 我的 ninja 为啥一直都没有问题，是我的版本太旧了吗？我最近没有更新过，现在版本是 _0.9.36_

是的，作者已经不更新了，甚至变成只读存档了

**Comment by haers** [comment]
我的突然也不行了。Error: please put HAR files in harPool directory!

**Comment by potoo0** [comment]
> 我的突然也不行了。Error: please put HAR files in harPool directory!

你的什么版本呀？

**Comment by haers** [comment]
> > 我的突然也不行了。Error: please put HAR files in harPool directory!
> 
> @haers 你的什么版本呀？

maxduke/go-chatgpt-api，服务器国外

**Comment by potoo0** [comment]
> maxduke/go-chatgpt-api，服务器国外

@haers 我的是 gngpp/ninja (0.9.36) 还是正常的:
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/34411681/3dc21536-b9f0-4e75-95d1-02f40502e056)

**Comment by Caiyou1001** [comment]
> > > > > > 已经解决了， 用这个镜像反代
> > > > > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > > > > 
> > > > > 
> > > > > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> > > > 
> > > > 
> > > > 大佬，牛逼，可以了
> > > 
> > > 
> > > 求大概教程，我docker布置后日志提示Error: please put HAR files in harPool directory! 谢谢
> > 
> > 
> > 你好，你这个解决了吗我也这样子
> 
> 参考作者维护的源码。主要就是作者把har文件映射目录改了下，变成了“/app/harPool”

![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/31730136/69a9f446-b174-4336-b223-ed8eeecf6a88)
感觉成功了，可一直在思考是什么问题呢。。是否遇到同样问题

**Comment by PhiBrain-ZhaoLiang** [comment]
> > maxduke/go-chatgpt-api，服务器国外
> 
> @haers 我的是 gngpp/ninja (0.9.36) 还是正常的: ![image](https://private-user-images.githubusercontent.com/34411681/313942776-3dc21536-b9f0-4e75-95d1-02f40502e056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTkzODIsIm5iZiI6MTcxMDg1OTA4MiwicGF0aCI6Ii8zNDQxMTY4MS8zMTM5NDI3NzYtM2RjMjE1MzYtYjlmMC00ZTc1LTk1ZDEtMDJmNDA1MDJlMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE0MzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MmUwYmYzMjA0NThkMDA4ZWVhMThmYzY3ZDMzZjA1NDExNjExZWVmODE5MzA5Y2RiMjAyMzU1NGFhZDM0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46ev-Xg8UUi7B8xFyMfGznZxAN1FV1p0lKanF5Tqh5U)

你的看起来不像是用的docker，你用的本地安装方案？

**Comment by potoo0** [comment]
> 你的看起来不像是用的docker，你用的本地安装方案？

@PhiBrain-ZhaoLiang 
是的，ninja 很干净的，启动的话一行命令就行了，所以我没用 docker

**Comment by unclehu87** [comment]
> > 你的看起来不像是用的docker，你用的本地安装方案？
> 
> @PhiBrain-ZhaoLiang 是的，ninja 很干净的，启动的话一行命令就行了，所以我没用 docker

ninjaa项目关闭了，二进制包在哪下载的？

**Comment by artisth** [comment]
> > > > > > > 已经解决了， 用这个镜像反代
> > > > > > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > > > > > 
> > > > > > 
> > > > > > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> > > > > 
> > > > > 
> > > > > 大佬，牛逼，可以了
> > > > 
> > > > 
> > > > 求大概教程，我docker布置后日志提示Error: please put HAR files in harPool directory! 谢谢
> > > 
> > > 
> > > 你好，你这个解决了吗我也这样子
> > 
> > 
> > 参考作者维护的源码。主要就是作者把har文件映射目录改了下，变成了“/app/harPool”
> 
> ![image](https://private-user-images.githubusercontent.com/31730136/314103176-69a9f446-b174-4336-b223-ed8eeecf6a88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTk3ODYsIm5iZiI6MTcxMDkxOTQ4NiwicGF0aCI6Ii8zMTczMDEzNi8zMTQxMDMxNzYtNjlhOWY0NDYtYjE3NC00MzM2LWIyMjMtZWQ4ZWVlY2Y2YTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWUzZGVlM2FlMGNjZjNkN2I5NDhlM2IxODg0NTIwZGNlMjA5NjdmODEwZGEyNTdhMmJhNWU0NjZlNjc0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lyWeZkKMfa9yqVbGtBGYEFedBS2vyCRKja9VvlIXHw) 感觉成功了，可一直在思考是什么问题呢。。是否遇到同样问题

你好，请问这个问题解决了吗？我也出现了相同的问题。

**Comment by unclehu87** [comment]
maxduke/go-chatgpt-api 这个现在不行了，
go-chatgpt-api  | WARN[155317] you have no permission to use this model 
go-chatgpt-api  | [GIN] 2024/03/22 - 10:37:32 | 403 |    564.3328ms | 127.0.0.1 | POST     "/chatgpt/backend-api/conversation"
Ninja还有用吗？有哪个版本能用

**Comment by CrossStone** [comment]
> maxduke/go-chatgpt-api 这个现在不行了， go-chatgpt-api | WARN[155317] you have no permission to use this model go-chatgpt-api | [GIN] 2024/03/22 - 10:37:32 | 403 | 564.3328ms | 127.0.0.1 | POST "/chatgpt/backend-api/conversation" Ninja还有用吗？有哪个版本能用

更新最新的docker镜像就好了

**Comment by ZYMirror** [comment]
> > > > > > > > 已经解决了， 用这个镜像反代
> > > > > > > > docker run -d --name go-chatgpt-api -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api
> > > > > > > 
> > > > > > > 
> > > > > > > 代理地址设置为： http://{{ip}}:8080/chatgpt/backend-api/conversation
> > > > > > 
> > > > > > 
> > > > > > 大佬，牛逼，可以了
> > > > > 
> > > > > 
> > > > > 求大概教程，我docker布置后日志提示Error: please put HAR files in harPool directory! 谢谢
> > > > 
> > > > 
> > > > 你好，你这个解决了吗我也这样子
> > > 
> > > 
> > > 参考作者维护的源码。主要就是作者把har文件映射目录改了下，变成了“/app/harPool”
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/31730136/314103176-69a9f446-b174-4336-b223-ed8eeecf6a88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTk3ODYsIm5iZiI6MTcxMDkxOTQ4NiwicGF0aCI6Ii8zMTczMDEzNi8zMTQxMDMxNzYtNjlhOWY0NDYtYjE3NC00MzM2LWIyMjMtZWQ4ZWVlY2Y2YTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWUzZGVlM2FlMGNjZjNkN2I5NDhlM2IxODg0NTIwZGNlMjA5NjdmODEwZGEyNTdhMmJhNWU0NjZlNjc0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lyWeZkKMfa9yqVbGtBGYEFedBS2vyCRKja9VvlIXHw) 感觉成功了，可一直在思考是什么问题呢。。是否遇到同样问题
> 
> 你好，请问这个问题解决了吗？我也出现了相同的问题。

我也是这个问题，本来用的好好的，突然出现这个问题

**Comment by unclehu87** [comment]
> > maxduke/go-chatgpt-api 这个现在不行了， go-chatgpt-api | WARN[155317] you have no permission to use this model go-chatgpt-api | [GIN] 2024/03/22 - 10:37:32 | 403 | 564.3328ms | 127.0.0.1 | POST "/chatgpt/backend-api/conversation" Ninja还有用吗？有哪个版本能用
> 
> 更新最新的docker镜像就好了

  多谢，更新后确实可行了

**Comment by haers** [comment]
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later




魔改版又出问题了

**Comment by yizhilangou** [comment]
还有可用的反代吗，分享一下orz

**Comment by unclehu87** [comment]
最近用的maxduke/go-chatgpt-api  貌似又开始报please provide a valid access token or api key in 'Authorization' header  了
返回不了回答，是OPENAI又改接口了吗?
