### ISSUE TITLE
是否支持逐字显示呢。

### ISSUE THREAD

**Issue by davisharry** [Chanzhaoyu/chatgpt-web#2043]
是否支持逐字显示呢。

**Comment by INCORRENTs** [comment]
老哥实现了吗

**Comment by ChrisKimZHT** [comment]
即使有中文文档也不看？

> Q: 前端没有打字机效果？
> A: 一种可能原因是经过 Nginx 反向代理，开启了 buffer，则 Nginx 会尝试从后端缓冲一定大小的数据再发送给浏览器。请尝试在反代参数后添加 proxy_buffering off;，然后重载 Nginx。其他 web server 配置同理。
