### ISSUE TITLE
为什么暴露的是3002端口？

### ISSUE THREAD

**Issue by IMYR666** [Chanzhaoyu/chatgpt-web#2044]
dockerfile中为什么暴露的是3002端口？我理解的3002是后端接口使用的端口，前端页面使用的是1002端口，不应该暴露出1002端口供调用吗

**Comment by ChrisKimZHT** [comment]
这什么理解？你去把 docker 容器启起来试下再说。

**Comment by IMYR666** [comment]
@ChrisKimZHT  不好意思，我对服务应用算是小白，docker启起来了，但直接访问3002端口不行，是还需要对nginx作什么配置吗？

**Comment by ChrisKimZHT** [comment]
> @ChrisKimZHT 不好意思，我对服务应用算是小白，docker启起来了，但直接访问3002端口不行，是还需要对nginx作什么配置吗？

应该就是能直接访问到，你发下你容器参数的看看。

**Comment by IMYR666** [comment]
@ChrisKimZHT docker正常了，但我还是不理解为什么访问3002端口就能打开原本开发环境1002端口才能打开的页面，能帮忙解释一下吗，或者给点参考资料也行，谢谢

**Comment by ChrisKimZHT** [comment]
前端页面的静态文件实际上是由 express 来提供的：

https://github.com/Chanzhaoyu/chatgpt-web/blob/15903fae3895c500b0de3ccdfaf87668c987dbf4/service/src/index.ts#L12

express 运行在 3002 端口，因此需要访问 3002 端口。
