### ISSUE TITLE
部署完成以后无法使用

### ISSUE THREAD

**Issue by S3257467509** [Chanzhaoyu/chatgpt-web#2046]
报错信息
request to https://ai.fakeopen.com/api/conversation failed, reason: getaddrinfo EAI_AGAIN [ai.fakeopen.com](http://ai.fakeopen.com/)

我是用docker部署的

**Comment by Hnitrogen** [comment]
应该是用代理访问gpt，但是大佬停止代理服务了（1.30关闭）， https://ai.fakeopen.com/api/conversation  中有详细内容
