### ISSUE TITLE
docker安装2.8.3版本能正常运行，但是2.9.0就不行了部署好以后是502错误，怎么办啊？

### ISSUE THREAD

**Issue by wwlmm** [Chanzhaoyu/chatgpt-web#205]
docker安装2.8.3版本能正常运行，但是2.9.0就不行了部署好以后是502错误，怎么办啊？

**Comment by Asura88** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/25000885/222416161-52006d8e-10b4-4ee1-8bdf-edfd7d758e6c.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/25000885/222416190-83a8ae06-e867-4882-819a-6be8f48e0c3f.png">
