### ISSUE TITLE
为什么api一直连接失败，

### ISSUE THREAD

**Issue by mobile17682318557** [Chanzhaoyu/chatgpt-web#2050]
我用的api-key，然后我网络应该没问题，访问网页版一直正常的，但是用这个项目一直失败
<img width="1158" alt="1709775399625" src="https://github.com/Chanzhaoyu/chatgpt-web/assets/28769282/7dc8220c-27af-4853-b34e-d30df68be344">

**Comment by mobile17682318557** [comment]
直接post访问接口也没问题

**Comment by qzzhujixue** [comment]
我也是，怎么处理的呀？跟我开着vpn有关吗？

**Comment by yizhilangou** [comment]
你们使用api有用吗，我这一直Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.

**Comment by jiayusu** [comment]
why 
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by jiayusu** [comment]
同求
