### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by Asura88** [Chanzhaoyu/chatgpt-web#206]
fetch failed

<img width="334" alt="image" src="https://user-images.githubusercontent.com/25000885/222416689-b1543545-7edd-4146-a28c-74dcdf78f95e.png">

**Comment by Arvintian** [comment]
+1

**Comment by Chanzhaoyu** [comment]
用 `Token` 晚上是这样的

**Comment by wwlmm** [comment]
我也是要刷新好几次才会出现答案

**Comment by TyCoding** [comment]
我也遇到了，刚才还行

**Comment by wanhaij** [comment]
我不是用的Token，用的是API_KEY，也会这样

**Comment by zailushang2008** [comment]
mee too,api key,docker

**Comment by wanhaij** [comment]
不过现在chatgpt的官网都打不开了，感觉是openai自己不行了

**Comment by TyCoding** [comment]
不是啊，官网和镜像站都能用，是这个chatgpt-api库调用不通了吗？还是所有API请求都调不通了？

**Comment by gygy** [comment]
今天早上也是这样。

**Comment by Chanzhaoyu** [comment]
`API` 方式今晚开始大部份地区都不能正常访问，看明天是否还是被墙。

**Comment by helperAI** [comment]
确实只有海外服务器的可以使用

**Comment by wysuperfly** [comment]
如何配置代理服务器呢？ 试过env，设置里面也能看到socks proxy，但对于api似乎不生效

**Comment by Chanzhaoyu** [comment]
> 

别折腾了，用 `Token` 吧

**Comment by siknet** [comment]
如何配置代理服务器呢？ 试过env，设置里面也能看到socks proxy，但对于api似乎不生效

-----
同疑问，我甚至不指定参数名是proxy还是socks，好像都不对

**Comment by chenying99** [comment]
如果设置socks5代理，大佬？

**Comment by helperAI** [comment]
> > 
> 
> 别折腾了，用 `Token` 吧

token是自己直接用梯子获得session的token还是可以通过代理，然后泄露邮箱，密码给代理服务器？

**Comment by Jason6111** [comment]
> > 别折腾了，用 `Token` 吧
> 
> token是自己直接用梯子获得session的token还是可以通过代理，然后泄露邮箱，密码给代理服务器？

自建一个代理socks proxy

**Comment by i-iooi-i** [comment]
删掉了api，使用Token，是可以正常使用的。

**Comment by ludashi2020** [comment]
用token很香，没有任何问题。

**Comment by Gavinluo** [comment]
用api key如何使用代理的方式呢? 自己只有订阅地址

**Comment by HuTa0kj** [comment]
同样遇到了这个问题

**Comment by Quorafind** [comment]
> #214

好

**Comment by TyCoding** [comment]
> 用token很香，没有任何问题。

请问怎么用accesstoken呢？我把token配置上了，是不是还需要填proxy地址？这个地址填什么？

**Comment by chrischjh** [comment]
能否支持正向代理

**Comment by 404name** [comment]
我token+api都是这样

**Comment by ludashi2020** [comment]
> > 用token很香，没有任何问题。
> 
> 请问怎么用accesstoken呢？我把token配置上了，是不是还需要填proxy地址？这个地址填什么？

proxy地址 https://chatgptapi.googlevideo.dev/api/conversation/

**Comment by eadst** [comment]
刚刚把API换成token，管用。https://chat.openai.com/api/auth/session

**Comment by 404name** [comment]
> 我token+api都是这样

楼上解决了

**Comment by 404name** [comment]
> 我token+api都是这样

楼上方法解决了

**Comment by Asura88** [comment]
我token+api都是这样

楼上方法解决了

**Comment by guoguo163** [comment]
> #214

可用

**Comment by w7sgyf** [comment]
用token还是频繁出现fetch failed，要刷新好多次才会出现答案

**Comment by william5200** [comment]
`ufw disable` 把 ufw 关闭可以临时解决这个问题，还没有找到问题根源
