### ISSUE TITLE
IP是被Ban了吗，使用Warp 也不行

### ISSUE THREAD

**Issue by Superqinqing** [Chanzhaoyu/chatgpt-web#2064]
![111](https://github.com/Chanzhaoyu/chatgpt-web/assets/47345142/3206c735-d896-4330-861f-bc57ec6de90e)
但检查又貌似是可以的

![2](https://github.com/Chanzhaoyu/chatgpt-web/assets/47345142/65be37f2-81d9-44a0-b06e-f4f0a4f27be3)

**Comment by lewisshao** [comment]
@Superqinqing 大佬这问题怎么解决的
