### ISSUE TITLE
私人API被盗？

### ISSUE THREAD

**Issue by chuhaoran20** [Chanzhaoyu/chatgpt-web#2066]
我添加了自己的API，很少用，但发现近段时间一直在消费，请问是被盗用了么？如何能避免被盗用？

**Comment by yizhilangou** [comment]
重新生成一个key,删除之前那个

**Comment by bibubi** [comment]
> 我添加了自己的API，很少用，但发现近段时间一直在消费，请问是被盗用了么？如何能避免被盗用？

原来不止我一个。。
