### ISSUE TITLE
获取accesstoken返回的是大括号

### ISSUE THREAD

**Issue by weiq** [Chanzhaoyu/chatgpt-web#208]
访问 https://chat.openai.com/api/auth/session 返回的是 {}
![image](https://user-images.githubusercontent.com/1697158/222450500-1fe1526a-942b-4b94-929d-cbde0b0ba610.png)

**Comment by i-iooi-i** [comment]
> 访问 https://chat.openai.com/api/auth/session 返回的是 {} ![image](https://user-images.githubusercontent.com/1697158/222450500-1fe1526a-942b-4b94-929d-cbde0b0ba610.png)

你需要先登录自己的账号再获取

**Comment by Jason6111** [comment]
先正常登录上 才能正确获取 不要用无痕模式

**Comment by weiq** [comment]
嗷嗷，谢谢，我用的无痕模式
