### ISSUE TITLE
是否计划支持4o的附件上传功能？

### ISSUE THREAD

**Issue by LeiyuanBlog** [Chanzhaoyu/chatgpt-web#2087]
是否计划支持4o的附件上传功能？

**Comment by tluo-github** [comment]
非常需要！

**Comment by LeiyuanBlog** [comment]
> 非常需要！

我觉得是非常有必要的一个功能，毕竟咱有api，但是没有ui可以用

**Comment by tluo-github** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sutao29** [comment]
非常需要

**Comment by LeiyuanBlog** [comment]
# **项目leader是否有看到？**

**Comment by Csmkl000** [comment]
需要需要，求

**Comment by fudai** [comment]
+1

**Comment by tluo-github** [comment]
我临时给 gpt-4o 添加了上传图片，和让 gpt-4o 识别图片
代码在：https://github.com/tluo-github/chatgpt-web

**Comment by yvonneit** [comment]
> 我临时给 gpt-4o 添加了上传图片，和让 gpt-4o 识别图片 代码在：https://github.com/tluo-github/chatgpt-web

使用了一下，为什么照片无法上传呢？
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/29810005/29a40390-f633-41ed-b7d0-19fab2342e74)

**Comment by LeiyuanBlog** [comment]
开发者是否有看到？

**Comment by LeiyuanBlog** [comment]
期待回复

**Comment by wdqzdd** [comment]
+1

**Comment by xiaoshieefocus** [comment]
+1
