### ISSUE TITLE
你好，我是一名新手，我想问一下怎么对项目进行修改然后使用项目，谢谢😊

### ISSUE THREAD

**Issue by NO1FFF** [Chanzhaoyu/chatgpt-web#2096]

**Comment by zlq54321** [comment]
你好我也是新手，我的流程是这样的：先速成html css js ts vue 然后配合ai工具阅读代码，然后尝试修改。有些库或者工具查阅官网就够了，主要是 naiveUI tailwind iconify等。 部署项目是编译出来的东西放到nginx容器中。整个大约耗时三个周，希望能帮到你

**Comment by NO1FFF** [comment]
> 你好我也是新手，我的流程是这样的：先速成html css js ts vue 然后配合ai工具阅读代码，然后尝试修改。有些库或者工具查阅官网就够了，主要是 naiveUI tailwind iconify等。部署项目是编译出来的东西放到nginx容器中。仅针对前端，后端是自行开发的RAG，整个大约耗时三个周，希望能帮到你。

谢谢你,这些对我来说很有帮助😄
