### ISSUE TITLE
这个上下文功能是否是将历史消息都发给ChatGPT?

### ISSUE THREAD

**Issue by shelken** [Chanzhaoyu/chatgpt-web#210]
查了下接口使用记录，发现一次就发了2000多个prompt。这个上下文功能是否是将历史都发送过去？是否可以考虑在会话中选择是否开启上下文？现在的按照tokens计数。感觉这样消耗挺快的。

**Comment by zhy3213** [comment]
左上角new chat

**Comment by acongee** [comment]
要能根据上下文回答的话就必须把当前对话过去的内容一起发过去，不需要根据上下文回答的话新开一个 chat 就好
