### ISSUE TITLE
大佬请教一下，不太懂ChatGPTAPI怎么调用的

### ISSUE THREAD

**Issue by qaz31857619** [Chanzhaoyu/chatgpt-web#2101]
文档中，ChatGPTAPI非官方渠道俩种方法，不会使用，怎么办啊，第一步就卡死了

**Comment by Borease** [comment]
ChatGPTUnofficialProxyAPI no longer supported, use ChatGPTAPI instead.
See: https://github.com/transitive-bullshit/agentic/issues/453
