### ISSUE TITLE
身份认证功能请求

### ISSUE THREAD

**Issue by ReaderC** [Chanzhaoyu/chatgpt-web#211]
开发者你好，不知道有没有考虑加上身份认证功能🤔，不需要太复杂，特别是现在3.5的API出来了，如果没有认证的话，配额很容易被误入的人用光

这是我用Shodan搜索 http.title:"chatgpt web"得到的结果，每一个都不需要认证可以直接用 
![IMG_20230302_234847.jpg](https://user-images.githubusercontent.com/42609462/222478616-cdff60c1-1d50-4682-a252-40684d63846b.jpg)

**Comment by helperAI** [comment]
+1，后台接口可以我们自己实现。前端需要统一网格。

**Comment by ReaderC** [comment]
这是我用Shodan搜索 http.title:"chatgpt web"得到的结果，每一个都不需要认证可以直接用 
![Screenshot_2023-03-02-23-44-12-698_com.android.chrome.jpg](https://user-images.githubusercontent.com/42609462/222477313-e296f2e8-fc45-4fe3-8992-099ddb056f82.jpg)

**Comment by caotao94** [comment]
加个nginx登录认证就行两行配置

**Comment by ReaderC** [comment]
> 加个nginx登录认证就行两行配置

可是，不是每个人都会配置的，大部分人都是开箱既用，如果不是开发者加上认证功能的话，我想shodan搜出来的结果，还是随点随用吧

**Comment by inceptiongt** [comment]
为啥搜http.title:"chatgpt web"可以搜出来啊，啥原理呢

**Comment by ZiYang-oyxy** [comment]
确实，很有必要

**Comment by DomainSmart** [comment]
+10086

**Comment by ReaderC** [comment]
> 为啥搜http.title:"chatgpt web"可以搜出来啊，啥原理呢

搜索引擎

**Comment by hnuzhoulin** [comment]
感谢，又发现了一个有意思的东西

**Comment by ReaderC** [comment]
> 感谢，又发现了一个有意思的东西

不要干坏事哦

**Comment by Chanzhaoyu** [comment]
会加一个简单的密码权限判断，每个请求加上中间件，不正确跳转`403`页面输入密码。
复杂的登录验证 `Token` 之内的应该不会实现。

**Comment by ReaderC** [comment]
> 会加一个简单的密码权限判断，每个请求加上中间件，不正确跳转`403`页面输入密码。
> 复杂的登录验证 `Token` 之内的应该不会实现。

简单的就够用了，主要还是防君子不防小人，只要能够保证不会被乱入的人消耗配额就已经够了

**Comment by OwenTest** [comment]
ldap  哈哈哈

**Comment by bjznl** [comment]
> 加个nginx登录认证就行两行配置

我今天就想着用nginx加密码反代docker容器，结果一直不成功总是一个加载页面。其他容器都能正常反代。

**Comment by caotao94** [comment]
> > 加个nginx登录认证就行两行配置
> 
> 我今天就想着用nginx加密码反代docker容器，结果一直不成功总是一个加载页面。其他容器都能正常反代。

<img width="498" alt="image" src="https://user-images.githubusercontent.com/31203266/222683256-cbb61e0c-8ac0-4435-9992-456e2702a956.png">
Nginx这个模块安装了吗

**Comment by Chanzhaoyu** [comment]
去获取 dev 分支代码，已经加了

**Comment by bjznl** [comment]
> > > 加个nginx登录认证就行两行配置
> > 
> > 
> > 我今天就想着用nginx加密码反代docker容器，结果一直不成功总是一个加载页面。其他容器都能正常反代。
> 
> <img alt="image" width="498" src="https://user-images.githubusercontent.com/31203266/222683256-cbb61e0c-8ac0-4435-9992-456e2702a956.png">
> 
> Nginx这个模块安装了吗

![image](https://user-images.githubusercontent.com/32454911/222683932-7a8ab78c-01bc-45c5-a0ee-a6fefe2a3c90.png)
这个吗

**Comment by ReaderC** [comment]
> 去获取 dev 分支代码，已经加了

高效率
