### ISSUE TITLE
openai o1 model 

### ISSUE THREAD

**Issue by BertramRay** [Chanzhaoyu/chatgpt-web#2115]
1. 不支持system message
2. 不支持流式传输
3. max_tokens 参数名改为 max_completion_tokens
4. 不支持"temperature"， "top_p"， "frequency_penalty"， "presence_penalty"

想问一下开发者们，后续考虑合入o1相关的代码吗

**Comment by PeterDaveHello** [comment]
Some of them are just beta limitations ;)

https://platform.openai.com/docs/guides/reasoning/beta-limitations

> Other: `temperature`, `top_p` and `n` are fixed at `1`, while `presence_penalty` and `frequency_penalty` are fixed at `0`.

**Comment by PeterDaveHello** [comment]
@Chanzhaoyu would you like to accept a pull request for it?
