### ISSUE TITLE
为APi添加代理

### ISSUE THREAD

**Issue by jiusheng6** [Chanzhaoyu/chatgpt-web#217]
昨天下午开始，api的域名被墙，希望能支持代理

**Comment by gdzjy** [comment]
建议支持SOCKS5代理。

**Comment by ws1993** [comment]
目前可以自己加一下，我这边已经可以用了：
1.安装https-proxy-agent
`npm install https-proxy-agent`
2.在service/arc.chatgpt.ts下修改
引入https-proxy-agent
`import { HttpsProxyAgent } from 'https-proxy-agent'`
然后找到new ChatGPTAPI那一行，按如下修改：
`    // api = new ChatGPTAPI({ ...options })
    api = new ChatGPTAPI({
      ...options,
      fetch: (url, options = {}) => {
        const defaultOptions = {
          agent: new HttpsProxyAgent({your proxy}),
        }

        const mergedOptions = {
          ...defaultOptions,
          ...options,
        }

        return fetch(url, mergedOptions)
      },`

**Comment by jianqiao0313** [comment]
+1  现在api都是fetch failed

**Comment by ws1993** [comment]
> 目前可以自己加一下，我这边已经可以用了： 1.安装https-proxy-agent `npm install https-proxy-agent` 2.在service/arc.chatgpt.ts下修改 引入https-proxy-agent `import { HttpsProxyAgent } from 'https-proxy-agent'` 然后找到new ChatGPTAPI那一行，按如下修改： ` api = new ChatGPTAPI({ ...options, fetch: (url, options = {}) => { const defaultOptions = { agent: new HttpsProxyAgent({your proxy}), } const mergedOptions = { ...defaultOptions, ...options, } return fetch(url, mergedOptions) },`
结果
![Snipaste-20230303_103106](https://user-images.githubusercontent.com/6252124/222616611-5edc7b9e-7cf3-4298-921b-575be2f56459.png)

**Comment by ws1993** [comment]
> 目前可以自己加一下，我这边已经可以用了： 1.安装https-proxy-agent `npm install https-proxy-agent` 2.在service/arc.chatgpt.ts下修改 引入https-proxy-agent `import { HttpsProxyAgent } from 'https-proxy-agent'` 然后找到new ChatGPTAPI那一行，按如下修改： ` api = new ChatGPTAPI({ ...options, fetch: (url, options = {}) => { const defaultOptions = { agent: new HttpsProxyAgent({your proxy}), } const mergedOptions = { ...defaultOptions, ...options, } return fetch(url, mergedOptions) },`

参考：
[fetch failed (OpenAI API banned in certain countries like China) · Issue #419 · transitive-bullshit/chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api/issues/419)

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/222616891-d64b3482-f3a7-4336-a9cf-fed30dfc18bd.png)
我把下面的代码复制上来，通过在`.env`定义`SOCKS_PROXY_HOST`和`SOCKS_PROXY_PORT`来解决问题。这个代码原本就在，只是不知道为什么readme没有提到。

**Comment by acongee** [comment]
#214

**Comment by ws1993** [comment]
> #214 在 `/service/.env` 文件里配置 `SOCKS_PROXY_HOST` 和 `SOCKS_PROXY_PORT` 就好了
不对的，如果是用的api模式，及时配置了这2个，也不会走代理的
![image](https://user-images.githubusercontent.com/6252124/222624585-abb1483e-3a37-4980-a294-38c3e8f8afaf.png)

**Comment by CKylinMC** [comment]
> > #214 在 `/service/.env` 文件里配置 `SOCKS_PROXY_HOST` 和 `SOCKS_PROXY_PORT` 就好了
> 
> 不对的，如果是用的api模式，即使配置了这2个，也不会走代理的 ![image](https://user-images.githubusercontent.com/6252124/222624585-abb1483e-3a37-4980-a294-38c3e8f8afaf.png)

就像我提到的，你需要复制你框住的那段代码到上面才可以

**Comment by acongee** [comment]
> > #214 在 `/service/.env` 文件里配置 `SOCKS_PROXY_HOST` 和 `SOCKS_PROXY_PORT` 就好了
> 
> 不对的，如果是用的api模式，即使配置了这2个，也不会走代理的 ![image](https://user-images.githubusercontent.com/6252124/222624585-abb1483e-3a37-4980-a294-38c3e8f8afaf.png)

几十分钟前 merge 了对 API 方式提供代理代码

**Comment by CKylinMC** [comment]
> 几十分钟前 merge 了对 API 方式提供代理代码

是的，我也看见了，其实就是把那段代码拿到上面来了，所以就可以使用了。

**Comment by yoke0104x** [comment]
@CKylinMC 这样设置也不太行啊

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44898730/222626403-bf4187f3-d90b-4d01-ad79-0cffd8b7af3f.png">

<img width="804" alt="image" src="https://user-images.githubusercontent.com/44898730/222626442-0de41276-fa86-4a1b-92fa-8f378db748ec.png">

**Comment by CKylinMC** [comment]
> @CKylinMC 这样设置也不太行啊

3002？这里不是写后端服务端口，而是你的proxy的端口。因为这是OpenAI的锁区，你需要一个代理，这里填写的是SOCKS代理服务的地址和端口。

**Comment by nhannguyensy** [comment]
> 目前可以自己加一下，我这边已经可以用了： 1.安装https-proxy-agent `npm install https-proxy-agent` 2.在service/arc.chatgpt.ts下修改 引入https-proxy-agent `import { HttpsProxyAgent } from 'https-proxy-agent'` 然后找到new ChatGPTAPI那一行，按如下修改：
> 
> ```
> api = new ChatGPTAPI({
>       ...options,
>       fetch: (url, options = {}) => {
>         const defaultOptions = {
>           agent: new HttpsProxyAgent({your proxy}),
>         }
>         const mergedOptions = {
>           ...defaultOptions,
>           ...options,
>         }
>         return fetch(url, mergedOptions)
>       },
> ```

Thanks @ws1993 , I just want to correct your code : 

api = new ChatGPTAPI({
  ...options, // Spread operator to include any additional options provided to ChatGPTAPI constructor
  fetch: (url, options = {}) => {
    const defaultOptions = {
      agent: new HttpsProxyAgent({host: 'IP', port: 3128}), // Update to pass proxy server information correctly
    }
    const mergedOptions = {
      ...defaultOptions,
      ...options, // Spread operator to override defaultOptions with any options provided to the fetch function
    }
    return fetch(url, mergedOptions) // Return fetch function with merged options
  }
})

**Comment by gefeiyanga** [comment]
有人时常遇到接口503报错吗

**Comment by alphanlp** [comment]
有共享的代理吗？没有海外服务器啊
