### ISSUE TITLE
CanI use squid proxy to call outside ( api.openai.com) ?

### ISSUE THREAD

**Issue by nhannguyensy** [Chanzhaoyu/chatgpt-web#218]
Our server can not go to internet directly ,It must go through via proxy server ( squid ) before then it can go outside , how to use squid proxy to call outside ? Thanks !

**Comment by Chanzhaoyu** [comment]
```
# /service/.env

# Socks Proxy Port
SOCKS_PROXY_HOST=

# Socks Proxy Port
SOCKS_PROXY_PORT=
```

**Comment by nhannguyensy** [comment]
I use squid for proxy server , I update your code  in file service/src/chatgpt/index.js at  line api = new ChatGPTAPI like : 

api = new ChatGPTAPI({
  ...options, // Spread operator to include any additional options provided to ChatGPTAPI constructor
  fetch: (url, options = {}) => {
    const defaultOptions = {
      agent: new HttpsProxyAgent({host: 'IP', port: 3128}), // Update to pass proxy server information correctly
    }
    const mergedOptions = {
      ...defaultOptions,
      ...options, // Spread operator to override defaultOptions with any options provided to the fetch function
    }
    return fetch(url, mergedOptions) // Return fetch function with merged options
  }
})

It can work !
