### ISSUE TITLE
一直显示超时是为什么啊？

### ISSUE THREAD

**Issue by yoke0104x** [Chanzhaoyu/chatgpt-web#220]
![image](https://user-images.githubusercontent.com/44898730/222620842-d27c47a5-938f-4f65-b73c-f5e4b5648ad6.png)

**Comment by yoke0104x** [comment]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/44898730/222621023-64567895-6798-46d2-979b-bb8e4a2dfed6.png">

**Comment by wangzhen-CHN** [comment]
国内IP被墙了

**Comment by wwlmm** [comment]
貌似API的域名被封了，所以你把API删了，直接用token的话 还是能用一下的

**Comment by CKylinMC** [comment]
#214 #206 #217
