### ISSUE TITLE
Incorrect word break

### ISSUE THREAD

**Issue by dohsimpson** [Chanzhaoyu/chatgpt-web#225]
Screenshot attached for English conversation:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/5865309/222641716-ab792fcc-c1b3-454d-816a-a267ec3dfcac.png">

As seen aboe, the word is being broken: e.g. `grandmother` -> `g` NEW LINE `randmother`. This makes the message hard to read.

Excepted Behaviour: the word should not be broken up.

**Comment by dohsimpson** [comment]
Working on a PR, will submit a merge soon

**Comment by Chanzhaoyu** [comment]
I'm already working on this in the development branch

**Comment by Chanzhaoyu** [comment]
Fixed
