### ISSUE TITLE
request to https://api.openai.com/v1/chat/completions failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by MrBoShen** [Chanzhaoyu/chatgpt-web#228]
![image](https://user-images.githubusercontent.com/38562441/222646022-3b3d78bb-bb0f-421f-9153-eb1ff8743be6.png)
用的OPENAI_API_KEY就提示这个错误。

**Comment by Chanzhaoyu** [comment]
被墙了

**Comment by MrBoShen** [comment]
有什么替代方法吗

**Comment by YutHelloWorld** [comment]
换主机。。

**Comment by TyCoding** [comment]
我也是这个，话说现在还有解决方案吗？感觉彻底用不了了，apiKey和token都没法用，我的是阿里云服务器

**Comment by jianqiao0313** [comment]
#217 可以看看这个
我也是阿里云的服务器，装了个shellclash，然后通过socks代理，就可以用了

**Comment by Wants1203** [comment]
有好的解决办法吗

**Comment by jerryzhang721** [comment]
我有v2ray，怎么设置代理啊？

**Comment by jackc4bug** [comment]
> 我有v2ray，怎么设置代理啊？

我也用的v2ray 大佬现在解决了吗

**Comment by GPTCraft** [comment]
我也是这个报错，但是没有被墙啊，官方页面还是用的好好的，而且是全局代理，usage也够

**Comment by GPTCraft** [comment]
> 我也是这个报错，但是没有被墙啊，官方页面还是用的好好的，而且是全局代理，usage也够

找到原因了，macbook m1终端默认没有走代理，开了全局也没用，export ALL_PROXY=socks5://127.0.0.1:7890解决，端口换成本地代理的端口
