### ISSUE TITLE
有没有脚本可以一键关闭，杀进程再启动发现端口会被占用

### ISSUE THREAD

**Issue by cary-sas** [Chanzhaoyu/chatgpt-web#229]
我现在只看见一个启动的shell脚本，但是需要一个一键关闭所有服务的脚本。 不然手动杀进程 后再启动 发现1002 端口会被占用，然后就自动切换到 1003端口了， 这样导致原来的历史聊天记录都没有了

**Comment by cjw-666** [comment]
一个粗暴的办法：重启服务器
