### ISSUE TITLE
建议配置按钮弹出模态框增加底部重置和提交按钮

### ISSUE THREAD

**Issue by gouguoyin** [Chanzhaoyu/chatgpt-web#232]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/13517412/222660814-7646c5e5-66be-4513-ba73-46957bce45b3.png">
建议重置用户信息右侧的`重置`按钮放在最底部，并增加`提交`按钮，方便改造成用户登录成功后个人信息修改页面。

**Comment by Chanzhaoyu** [comment]
这个自行调整哈，不难，不做展开了

**Comment by Chanzhaoyu** [comment]
这个自行调整哈，不难，不做展开了
