### ISSUE TITLE
你好我想问下如果修改api，是否只有在docker-compose中修改后然后重启？

### ISSUE THREAD

**Issue by qdd14284421** [Chanzhaoyu/chatgpt-web#240]
有没有后台可以直接修改的？
有的话，后台地址是多少。

已搭建完成，这一套对话系统非常nice

**Comment by Chanzhaoyu** [comment]
不会做后台功能，这些功能比较简单，不做扩展。

**Comment by aboutblank123** [comment]
我更新完之后，对话一直fetch failed！是那个环节有问题，回退到上个版本又是正常的
