### ISSUE TITLE
用key的可以把api域名替换成这个就好了

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#241]
官网接口https://api.openai.com被污染了，把这个域名替换成https://api.googlevideo.dev就可以了。替换后国内机器也能用

**Comment by qdd14284421** [comment]
在那个文件里替换

**Comment by linxkon** [comment]
请问大佬在哪个地方替换呢？

**Comment by Chanzhaoyu** [comment]
`service/src/chatgpt/index.ts`

如图所示

<img width="542" alt="image" src="https://user-images.githubusercontent.com/24789441/222699870-12287cc2-21d0-4549-a5c0-567f8162f7b8.png">

**Comment by zzb16888** [comment]
官方的api是被污染还是被强？

**Comment by juzi3333** [comment]
https://openapi.ssiic.com  我也弄了个

**Comment by goodwisdom** [comment]
> `service/src/chatgpt/index.ts`
> 
> ```
> const options: ChatGPTAPIOptions = {
>       apiKey: process.env.OPENAI_API_KEY,
>       apiBaseUrl: 'https://api.googlevideo.dev',
>       debug: false,
>     }
> 
> ```
> 
> 但是不知道安全问题

可以把这个替换做成环境配置吗？或者网页上增加修改地方？

**Comment by yuwangi** [comment]
有没有自己实现 https://api.googlevideo.dev 的方法  ，我有国外的服务器 和域名， 怎么做反向代理转发呢？

**Comment by juzi3333** [comment]
反代就行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 中午11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] 用key的可以把api域名替换成这个就好了 (Issue #241)





 
有没有自己实现 https://api.googlevideo.dev 的方法  ，我有国外的服务器 和域名， 怎么做反向代理转发呢？

**Comment by yuwangi** [comment]
@juzi3333  是的  我试着做了反向代理  结果走不通？  有实现的例子吗？

**Comment by juzi3333** [comment]
提示什么



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] 用key的可以把api域名替换成这个就好了 (Issue #241)





 
@juzi3333  是的  我试着做了反向代理  结果走不通？  有实现的例子吗？

**Comment by yuwangi** [comment]
![image](https://user-images.githubusercontent.com/13346477/223010592-d8d0e76a-09f5-4a2e-abbf-6f999b04ebdf.png)

**Comment by yuwangi** [comment]
不好意思 我的失误 多加了一层链接  导致404了  已经跑通了  感谢 @juzi3333

**Comment by juzi3333** [comment]
提供一个我自己弄的  https://openapi.ssiic.com

**Comment by hnuzhoulin** [comment]
我是直接把容器运行在外面的服务器上，省掉一层

**Comment by ldybyz** [comment]
谢谢兄弟

**Comment by chenlihao111** [comment]
好像又不行了？
