### ISSUE TITLE
虽然ChatGPTAPI说自己已经支持了gpt-3.5-turbo和 gpt-3.5-turbo-0301 ，但是我怎么感觉支持的不够好的样子？

### ISSUE THREAD

**Issue by likeyiyy** [Chanzhaoyu/chatgpt-web#242]
首先，证明我版本已经升上去了：
![image](https://user-images.githubusercontent.com/5380901/222697835-bb36af93-c362-4430-80cd-bf59d35654e5.png)

![image](https://user-images.githubusercontent.com/5380901/222697523-8fd52a01-35cc-4b2c-a6bc-03a54a0e581a.png)

然后，这是问话效果：

![image](https://user-images.githubusercontent.com/5380901/222697916-10cabd23-60d2-4bc2-acdc-beedac22d366.png)

而我同样用相同的API KEY，用另外一个demo启动的。

![image](https://user-images.githubusercontent.com/5380901/222698331-70e7b722-381c-4062-91df-8e85c5f9f758.png)

然后我用chatgpt网页提问的：

![image](https://user-images.githubusercontent.com/5380901/222698450-7370f209-a1d9-4085-b15c-b6a5a9420df7.png)

而且，那个不能回答还不是说随即的不能回答， 基本上我每次问都回答不了。

有人遇到过类似的情况吗？

**Comment by JeamUmika** [comment]
这是我的，版本是 '2.9.1'
![Screenshot_20230303-191217_Chrome.png](https://user-images.githubusercontent.com/93057377/222706200-c7d1ef84-a2cf-4eae-b2e6-ba136253999b.png)

**Comment by pzcn** [comment]
确实不太一样，一个认为自己是chatgpt，一个认为自己是gpt-3
![image](https://user-images.githubusercontent.com/29601158/222715239-e0935551-f7b7-4abe-b273-d66f5cbff71f.png)
![image](https://user-images.githubusercontent.com/29601158/222715274-96746cba-5236-419f-8059-20de8ff01e5a.png)

**Comment by 404gods** [comment]
我对比试了也是这个效果，不知道因为什么

**Comment by pzcn** [comment]
看了下，这个项目用的是chatgpt的npm包，另外一个是使用的openai的官方接口 https://platform.openai.com/docs/api-reference/answers 
目前看来二者还是存在一定区别的，虽然都是gpt3.5。npm包认为自己是chatgpt，而openai官方接口认为自己是gpt3，至少就图灵斑图这个问题，openai接口是强于npm的
个人认为 https://github.com/Chanzhaoyu/chatgpt-web/issues/243 也是想表达这个意思

**Comment by pzcn** [comment]
我手动指定调用gpt-3.5-turbo，现在可以回答图灵斑图问题了

**Comment by 404gods** [comment]
> 我手动指定调用gpt-3.5-turbo，现在可以回答图灵斑图问题了

docker如何做到手动指定？

**Comment by pzcn** [comment]
> > 我手动指定调用gpt-3.5-turbo，现在可以回答图灵斑图问题了
> 
> docker如何做到手动指定？

不太懂docker，我是手动部署的

**Comment by fierceX** [comment]
@pzcn 手动部署需要修改哪里

**Comment by pzcn** [comment]
> @pzcn 手动部署需要修改哪里
https://github.com/Chanzhaoyu/chatgpt-web/blob/f95af40ab89d0370702e32b9eccdcc229bfe5782/service/src/chatgpt/index.ts#L27

参考 https://platform.openai.com/docs/api-reference/completions/create#completions/create-model

**Comment by pzcn** [comment]
> @pzcn 是需要将node包改成官网的node包吗，看起来比较复杂的样子

不是，可以参考下我改的 https://github.com/pzcn/chatgpt-web2/commit/aea1ba54df64989277b3aa3646c2af18d927aa50

**Comment by i-iooi-i** [comment]
![image](https://user-images.githubusercontent.com/1827701/222752273-7cae501b-df3b-43c1-bc60-aff04f707573.png)

Docker 部署的，好像也还好。

**Comment by qq7780891** [comment]
> 这是我的，版本是`2.9.1` ![Screenshot_20230303-191217_Chrome.png](https://user-images.githubusercontent.com/93057377/222706200-c7d1ef84-a2cf-4eae-b2e6-ba136253999b.png)

这个demo是你自己写的吗?

**Comment by hyln9** [comment]
The upstream issue has been fixed in transitive-bullshit/chatgpt-api#425.
