### ISSUE TITLE
目前这个项目是否支持ChatGPT的官方API？

### ISSUE THREAD

**Issue by sphinger** [Chanzhaoyu/chatgpt-web#243]
ChatGPTAPI说自己已经支持了gpt-3.5-turbo，这个项目什么时候能够引入？期待

**Comment by Chanzhaoyu** [comment]
默认已经是了，也可以自行调整模型和参数

**Comment by pzcn** [comment]
> 默认已经是了，也可以自行调整模型和参数

试了下openai的api始终认为自己是gpt-3，但是chatgpt的npm包就认为自己是chatgpt，感觉chatgpt的npm不是官方的吧...

**Comment by pzcn** [comment]
![image](https://user-images.githubusercontent.com/29601158/222746011-e6a36e7a-3069-4f0c-8378-f0a84e140f97.png)
![image](https://user-images.githubusercontent.com/29601158/222746079-2bac0033-5acf-472b-8be4-f712d8a08561.png)

**Comment by sphinger** [comment]
> 默认已经是了，也可以自行调整模型和参数

看到了，谢谢
