### ISSUE TITLE
shell脚本代码里注释“#” 符号，被解析成markdown语法

### ISSUE THREAD

**Issue by JeazW** [Chanzhaoyu/chatgpt-web#245]
![image](https://user-images.githubusercontent.com/75829171/222710532-d7880bf4-9c28-4110-b100-d7897a1f7c37.png)

**Comment by pengmaochang** [comment]
哈哈哈哈哈哈。我知道这个是个bug，但是莫名戳中我的笑点

**Comment by aboutblank123** [comment]
根目录和server目录下都从新安装下依赖

**Comment by ludashi2020** [comment]
使用token没这个问题

**Comment by Chanzhaoyu** [comment]
已修复，重新部署下
