### ISSUE TITLE
数据存储位置

### ISSUE THREAD

**Issue by Zhanghyi** [Chanzhaoyu/chatgpt-web#248]
可以问下数据存放在哪里呢，如果要迁移项目的话需要迁移哪些数据，数据是否明文存储，开发人员要如何查看。本人后端背景，希望有前端小伙伴帮忙解答

**Comment by Chanzhaoyu** [comment]
目前存在浏览器 localStorage 中，是明文，并没有迁徙功能

**Comment by ChasLui** [comment]
> 目前存在浏览器 localStorage 中，是明文，并没有迁徙功能

期望可以本地存储

**Comment by Chanzhaoyu** [comment]
> > 目前存在浏览器 localStorage 中，是明文，并没有迁徙功能
> 
> 期望可以本地存储, 哪怕是有个导入导出功能也好.

导入导出下版本更新
