### ISSUE TITLE
部署pm2无法运行

### ISSUE THREAD

**Issue by YutHelloWorld** [Chanzhaoyu/chatgpt-web#25]
pm2 挂起后就error。请教下如何部署

**Comment by l0o0** [comment]
我尝试部署后，网页端输入信息，会提示超时。不过在Service端打印出来的信息看，是正常的

**Comment by Chanzhaoyu** [comment]
> 我尝试部署后，网页端输入信息，会提示超时。不过在Service端打印出来的信息看，是正常的
> ![图片](https://user-images.githubusercontent.com/2743744/218899361-dc99e498-fe77-43b0-8894-ee0473e75b9b.png)
> 切换为Chrome或Edge就可以了，我在Firefox里使用会报如上的错误

这是网络请求不稳定，10秒超时太早了，我统一延长点。

**Comment by YutHelloWorld** [comment]
node 16环境不能部署是因为node16不支持esm。整体改为兼容16版本即可。pr已merge

**Comment by yuwangi** [comment]
@YutHelloWorld  我也遇到了这个问题 node 版本 16.18.1 使用pm2 启动报错  请问如何解决的？
