### ISSUE TITLE
Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by xin800** [Chanzhaoyu/chatgpt-web#250]
求教 Invalid URL (POST /v1/chat/completions) 怎么处理呢？

![image](https://user-images.githubusercontent.com/9602020/222722498-6cd855ef-a2d3-45d5-8f32-eb2c7a0b803e.png)

**Comment by opticalix** [comment]
配置OPENAI_API_BASE_URL

**Comment by 957955071** [comment]
配置什么呢？上面写的那个注释吗，配置了也没有用呢，很头痛

**Comment by ChandlerVer5** [comment]
检查路径，你的请求路径不对应该

**Comment by uknfire** [comment]
https://github.com/openai/openai-python/issues/271#issuecomment-1455910924
我也遇到这个问题，似乎和账号有关

**Comment by Halowangqx** [comment]
我已经更换帐号了，但还是不能用
