### ISSUE TITLE
当点击输入框位置后的显示可能有一个bug？

### ISSUE THREAD

**Issue by helperAI** [Chanzhaoyu/chatgpt-web#256]
当我们手指在上半部分的消息显示部位点击一下，然后看到输入框的边框已经变成非绿色了（此时说明焦点不是输入框了），此时如果我们点击输入框，弹出键盘后，会把输入框遮挡住，截图是iphone 13的页面截图。
![6021677853303_ pic](https://user-images.githubusercontent.com/75373309/222745637-8d471c40-aca6-4f20-8780-a50b91046282.jpg)

**Comment by Chanzhaoyu** [comment]
已修复
