### ISSUE TITLE
希望优化一下布局

### ISSUE THREAD

**Issue by pzcn** [Chanzhaoyu/chatgpt-web#257]
目前在高分屏上会左右占满整个屏幕，如果关键内容居中紧凑一点会更舒服。

**Comment by wwlmm** [comment]
赞成，像官方那样的宽度正好，768px

**Comment by pzcn** [comment]
![画板 1](https://user-images.githubusercontent.com/29601158/222754248-a90d4a0a-0902-4688-9d1e-1bef35d0bd67.png)
像这样，如果宽度可以窄一点会舒服的多，希望开发者可以考虑一下

**Comment by Chanzhaoyu** [comment]
已修复
