### ISSUE TITLE
启用Socks代理以后，回答的输出不再是Stream流了吗？

### ISSUE THREAD

**Issue by caneman** [Chanzhaoyu/chatgpt-web#259]
之前的版本，答案是一个个蹦出来的，用户体验上从输入到输出不用等很久。

加了Socks代理以后，现在是问完问题会等待一会儿，等所有的答案接受完毕后，前端再一下子全部输出，用户体验上其实不是很好，有种很卡很慢的感觉。

个人感觉，问答总时长不变的情况下，逐字输出让人感觉整个体验会更流畅一些。

是我网络/环境原因还是说这块确实有改动？

PS: 2.9.1和dev分支都存在这个现象

**Comment by BruceHan98** [comment]
我用了socks代理，通过http访问可以实现流输出，通过https访问就不行，不知道是哪里的问题

**Comment by shansing** [comment]
不知道你们是否用了 Nginx 作反向代理。我的情况是有 Nginx 作反代，几乎没有打字机效果。参考 #153 ，我在反代块加上了下面两行配置：
```
keepalive_timeout 10s;
proxy_buffering off;
```
之后就有顺畅的打字效果了。供参考。

**Comment by BruceHan98** [comment]
> 不知道你们是否用了 Nginx 作反向代理。我的情况是有 Nginx 作反代，几乎没有打字机效果。参考 #153 ，我在反代块加上了下面两行配置：
> 
> ```
> keepalive_timeout 10s;
> proxy_buffering off;
> ```
> 
> 之后就有顺畅的打字效果了。供参考。

是的，在nginx添加这两行就可以了，感谢！👍

**Comment by caneman** [comment]
> 不知道你们是否用了 Nginx 作反向代理。我的情况是有 Nginx 作反代，几乎没有打字机效果。参考 #153 ，我在反代块加上了下面两行配置：
> 
> ```
> keepalive_timeout 10s;
> proxy_buffering off;
> ```
> 
> 之后就有顺畅的打字效果了。供参考。

确实如此👍

**Comment by opticalix** [comment]
> 

请问是在docker-compose/nginx/nginx.conf加吗？

**Comment by BruceHan98** [comment]
> > 
> 
> 请问是在docker-compose/nginx/nginx.conf加吗？ 我是使用docker-compose部署的
> 
> > > 不知道你们是否用了 Nginx 作反向代理。我的情况是有 Nginx 作反代，几乎没有打字机效果。参考 #153 ，我在反代块加上了下面两行配置：
> > > ```
> > > keepalive_timeout 10s;
> > > proxy_buffering off;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 之后就有顺畅的打字效果了。供参考。
> > 
> > 
> > 是的，在nginx添加这两行就可以了，感谢！👍

我没有用docker-compose部署，我是在服务器的/etc/nginx/nginx.conf中添加的，你可以都试一下
