### ISSUE TITLE
html代码无法复制，整体可以复制

### ISSUE THREAD

**Issue by dennyliao** [Chanzhaoyu/chatgpt-web#260]
__
![1](https://user-images.githubusercontent.com/6821814/222855535-76f2a6d6-d60b-4f24-ae3a-403b547a92b3.png)
这个地方，点击复制无效

![2](https://user-images.githubusercontent.com/6821814/222855577-44d94f22-a0ab-4785-a76b-5b3141f50de9.png)
这个地方，点击复制正常

**Comment by Chanzhaoyu** [comment]
已修复
