### ISSUE TITLE
右上角复制代码为和还是没有出现，已经全删除重新部署了

### ISSUE THREAD

**Issue by JeazW** [Chanzhaoyu/chatgpt-web#264]
![image](https://user-images.githubusercontent.com/75829171/222875600-9ef9b984-90ac-4778-8de6-f9974e270698.png)

**Comment by Chanzhaoyu** [comment]
只有被正确识别并渲染为代码块的才会出现，你这个是文本渲染

**Comment by ChandlerVer5** [comment]
其实我觉得这个没有被返回markdown识别的代码语言，但是应该也可以复制才方便。

**Comment by Chanzhaoyu** [comment]
现在已经支持了
