### ISSUE TITLE
在iOS中，输入框当输入多行文本时，输入框下面会被遮挡。

### ISSUE THREAD

**Issue by wwlmm** [Chanzhaoyu/chatgpt-web#266]
在iOS中，输入框当输入多行文本时，输入框下面会被遮挡。
![IMG_9953](https://user-images.githubusercontent.com/23204809/222876129-d81cfb18-bd73-4823-80e0-04fbcfa356f8.jpg)

**Comment by Chanzhaoyu** [comment]
已修复
