### ISSUE TITLE
希望添加pwa支持

### ISSUE THREAD

**Issue by pzcn** [Chanzhaoyu/chatgpt-web#267]
https://www.npmjs.com/package/vite-plugin-pwa/

**Comment by Chanzhaoyu** [comment]
添加很简单，但是具体有什么打的益处吗。离线缓存？

**Comment by pzcn** [comment]
> 添加很简单，但是具体有什么大的益处吗。离线缓存？

可以在pc或者移动端的chromium平台上安装为应用，更像一款app，例如tgweb
![image](https://user-images.githubusercontent.com/29601158/222877969-c6c2d59e-1ecf-46f3-b134-f6577da67037.png)
![image](https://user-images.githubusercontent.com/29601158/222878048-75a43152-e54d-4930-80fb-4fee0d17c666.png)

**Comment by Chanzhaoyu** [comment]
感谢建议

**Comment by shangdev** [comment]
@Chanzhaoyu 手机版底部输入框在Iphone10+上贴底了，加个安全距离吧：
```
pb: 'constant(safe-area-inset-bottom)',
pb: 'env(safe-area-inset-bottom)',
```

**Comment by Chanzhaoyu** [comment]
> @Chanzhaoyu 手机版底部输入框在Iphone10+上贴底了，加个安全距离吧：
> 
> ```
> pb: 'constant(safe-area-inset-bottom)',
> pb: 'env(safe-area-inset-bottom)',
> ```

感谢反馈，已修复，我手机上暂无问题，你可以试一下

**Comment by shangdev** [comment]
@Chanzhaoyu好像还是不行，dev更新到最新版了

![image](https://user-images.githubusercontent.com/15621520/222898326-c04e5e1a-b3a5-41aa-8c0c-b8a101ccc4ce.png)

**Comment by fierceX** [comment]
根据chatgpt的建议，直接修改前端的配置文件 vite.config.js ,重新打包就支持pwa了：

```js
import path from 'path'
import { defineConfig, loadEnv } from 'vite'
import vue from '@vitejs/plugin-vue'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig((env) => {
  const viteEnv = loadEnv(env.mode, process.cwd()) as unknown as ImportMetaEnv

  return {
    resolve: {
      alias: {
        '@': path.resolve(process.cwd(), 'src'),
      },
    },
    plugins: [
      vue(),
      VitePWA({
        manifest: {
          name: 'My App',
          short_name: 'App',
          icons: [
            {
              src: '/assets/icon.png',
              sizes: '192x192',
              type: 'image/png',
            },
            {
              src: '/assets/icon-512x512.png',
              sizes: '512x512',
              type: 'image/png',
            },
          ],
        },
      }),
    ],
    server: {
      host: '0.0.0.0',
      port: 1002,
      open: false,
      proxy: {
        '/api': {
          target: viteEnv.VITE_APP_API_BASE_URL,
          changeOrigin: true, // 允许跨域
          rewrite: path => path.replace('/api/', '/'),
        },
      },
    },
    build: {
      reportCompressedSize: false,
      sourcemap: false,
      commonjsOptions: {
        ignoreTryCatch: false,
      },
    },
  }
})
```

**Comment by pzcn** [comment]
> 根据chatgpt的建议，直接修改前端的配置文件 vite.config.js ,重新打包就支持pwa了：
> 
> ```js
> import path from 'path'
> import { defineConfig, loadEnv } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import { VitePWA } from 'vite-plugin-pwa'
> 
> export default defineConfig((env) => {
>   const viteEnv = loadEnv(env.mode, process.cwd()) as unknown as ImportMetaEnv
> 
>   return {
>     resolve: {
>       alias: {
>         '@': path.resolve(process.cwd(), 'src'),
>       },
>     },
>     plugins: [
>       vue(),
>       VitePWA({
>         manifest: {
>           name: 'My App',
>           short_name: 'App',
>           icons: [
>             {
>               src: '/assets/icon.png',
>               sizes: '192x192',
>               type: 'image/png',
>             },
>             {
>               src: '/assets/icon-512x512.png',
>               sizes: '512x512',
>               type: 'image/png',
>             },
>           ],
>         },
>       }),
>     ],
>     server: {
>       host: '0.0.0.0',
>       port: 1002,
>       open: false,
>       proxy: {
>         '/api': {
>           target: viteEnv.VITE_APP_API_BASE_URL,
>           changeOrigin: true, // 允许跨域
>           rewrite: path => path.replace('/api/', '/'),
>         },
>       },
>     },
>     build: {
>       reportCompressedSize: false,
>       sourcemap: false,
>       commonjsOptions: {
>         ignoreTryCatch: false,
>       },
>     },
>   }
> })
> ```

这只是其中一步，我尝试了没效果。应该还需要更多配置

**Comment by pzcn** [comment]
yitian

**Comment by rovertang** [comment]
补充说明一下用途：在edge的侧边栏上添加，就可以不离开网页的情况下用chatgpt啦。类似于侧边栏工具，很赞。
