### ISSUE TITLE
用docker-compose方式，build遇到"html/: file does not exist"

### ISSUE THREAD

**Issue by opticalix** [Chanzhaoyu/chatgpt-web#272]
dist复制到 /docker-compose/html下了，/docker-compose下执行docker-compose build会报这个错，请问有人遇到过吗

> app uses an image, skipping
Building nginx
Sending build context to Docker daemon  3.072kB
Step 1/7 : FROM hub.c.163.com/library/nginx
 ---> 46102226f2fd
Step 2/7 : MAINTAINER jo "tionsin@live.com"
 ---> Running in 7753c662d0c9
Removing intermediate container 7753c662d0c9
 ---> 051202579ba1
Step 3/7 : RUN rm -rf /etc/nginx/conf.d/default.conf
 ---> Running in b02dc51def2b
Removing intermediate container b02dc51def2b
 ---> 97a71637fe2b
Step 4/7 : COPY ./nginx.conf /etc/nginx/conf.d/default.conf
 ---> 9d8a89c752ed
Step 5/7 : COPY ./html/ /usr/share/nginx/html/
COPY failed: file not found in build context or excluded by .dockerignore: stat html/: file does not exist
ERROR: Service 'nginx' failed to build

html文件夹长这样
`ubuntu@VM-8-16-ubuntu:~/repo/chatgpt-web/docker-compose/html$ ls`
`assets  favicon.ico  favicon.svg  index.html`

**Comment by opticalix** [comment]
please @Zo3i

**Comment by Zo3i** [comment]
你文件夹搞错了，是nginx/html

**Comment by opticalix** [comment]
> 你文件夹搞错了，是nginx/html

thanks  眼拙了..
