### ISSUE TITLE
这个虽然是3.5版本，但是因为调用接口差异，所以并不很好用

### ISSUE THREAD

**Issue by hallfay** [Chanzhaoyu/chatgpt-web#273]
这个问题和#242 他们的问题一样，我也通过不同demo发现这个demo几乎是最不聪明的，而#242 也解释了出现这问题的原因，这是#242给出的解释：chatgpt的npm包，另外一个是使用的openai的官方接口 https://platform.openai.com/docs/api-reference/answers
目前看来二者还是存在一定区别的，虽然都是gpt3.5。npm包认为自己是chatgpt，而openai官方接口认为自己是gpt3，至少就图灵斑图这个问题，openai接口是强于npm的
。
不仅是图灵斑图，几乎全方位的各种问题这个demo 出现了不能回答或者不能完成，比如我让他做一个简单的图表，它也告诉我不能完成，但是其他demo都是没有问题的。

**Comment by hyln9** [comment]
The issue was fixed in transitive-bullshit/chatgpt-api#425.
