### ISSUE TITLE
Error: Network Error

### ISSUE THREAD

**Issue by 7noemo** [Chanzhaoyu/chatgpt-web#28]
在服务器上搭建 
后端服务/service pnpm start 后IP:3002 得到的页面是 Cannot GET / 如何解决？
网页端报错Error: Network Error

是后端没开成功导致的网络报错吗？

**Comment by YutHelloWorld** [comment]
如果服务器不是18的话，需要进行代码改造支持16.

**Comment by wangdashuaihenshuai** [comment]
> 在服务器上搭建 后端服务/service pnpm start 后IP:3002 得到的页面是 Cannot GET / 如何解决？ 网页端报错Error: Network Error
> 
> 是后端没开成功导致的网络报错吗？

可以用我打的docker镜像部署, 指定一下 .env 文件就行。

```bash
docker run -d --restart=always -v /etc/chatgpt/.env:/data/node/app/.env -p 3002:3002 --name="chat" wangjinhai68/chatgpt-web:main
```

**Comment by 7noemo** [comment]
> > 在服务器上搭建 后端服务/service pnpm start 后IP:3002 得到的页面是 Cannot GET / 如何解决？ 网页端报错Error: Network Error
> > 是后端没开成功导致的网络报错吗？
> 
> 可以用我打的docker镜像部署, 指定一下 .env 文件就行。
> 
> ```shell
> docker run -d --restart=always -v /etc/chatgpt/.env:/data/node/app/.env -p 3002:3002 --name="chat" wangjinhai68/chatgpt-web:main
> ```

你这里面的参数咋改 不需要改吗？

**Comment by 7noemo** [comment]
> 如果服务器不是18的话，需要进行代码改造支持16.

改了18了的

**Comment by Siri-Li** [comment]
> 在服务器上搭建 后端服务/service pnpm start 后IP:3002 得到的页面是 Cannot GET / 如何解决？ 网页端报错Error: Network Error
> 
> 是后端没开成功导致的网络报错吗？

一样的问题呢，v18.14.0 , 3002端口开放的 网页端： Error: Network Error

**Comment by ventusoon** [comment]
> > 如果服务器不是18的话，需要进行代码改造支持16.
> 
> 改了18了的

大佬怎么解决的？
