### ISSUE TITLE
docker-compose部署的时候，中间做了端口转发，出现bug，js文件down不下来。

### ISSUE THREAD

**Issue by kainstan** [Chanzhaoyu/chatgpt-web#281]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/37264681/222905478-398a352e-78c0-4162-a7e3-81fc61ff8d99.png">

index-2e6834fd.js文件正常1.5MB，但是无法完全加载完，导致主页页面无法加载

**Comment by Chanzhaoyu** [comment]
强制刷新浏览器缓存试试

**Comment by kainstan** [comment]
强制刷新也是这样子的，状态码200，但是文件就是下载不下完全

**Comment by First-Power** [comment]
我也是这样nginx设置二级目录后就这样了，你有办法解决吗？

**Comment by asuna** [comment]
> 我也是这样nginx设置二级目录后就这样了，你有办法解决吗？

二级目录如果是404的话，可以用[ngx_http_sub_module](https://nginx.org/en/docs/http/ngx_http_sub_module.html)解决。
