### ISSUE TITLE
为什么Request failed with status code 500，秘钥没问题。

### ISSUE THREAD

**Issue by liuchengbin6** [Chanzhaoyu/chatgpt-web#282]
为什么Request failed with status code 500，秘钥没问题。[vite] http proxy error at /chat-process:
Error: connect ECONNREFUSED ::1:3002
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

**Comment by ChandlerVer5** [comment]
我之前部署到 cloudbase 云开发上也是，我那是服务器处理`/chat-process`接口太长时间，导致云函数直接超时和断开了。反正基本都是自己服务器配置问题

**Comment by liuchengbin6** [comment]
请问你怎么解决的

**Comment by liuchengbin6** [comment]
请问你怎么解决的

**Comment by liuchengbin6** [comment]
> cloudbase云之前云云上上，我我也服务器处理`/chat-process`接口太太长太长长长长，导致导致，导致导致云函数直接超时和和断开和断开了了了了。。

请问你怎么解决的

**Comment by ChandlerVer5** [comment]
> > cloudbase云之前云云上上，我我也服务器处理`/chat-process`接口太太长太长长长长，导致导致，导致导致云函数直接超时和和断开和断开了了了了。。
> 
> 请问你怎么解决的

没解决，搁置了...😄；因为我的问题，只要答案短，接口回答是可以正常的，只是没有打字机效果。如果答案太长就被断开了，目前在云开发SCF我没找到解决办法。
