### ISSUE TITLE
复制代码块，JS报错 undefined (reading 'writeText')

### ISSUE THREAD

**Issue by TeachMeJavaTonight** [Chanzhaoyu/chatgpt-web#284]
错误如下：
![image](https://user-images.githubusercontent.com/104610452/222911256-700f6ef8-5797-4369-adee-28442688e9b9.png)

![image](https://user-images.githubusercontent.com/104610452/222911336-cfe65490-ada8-42a1-acd7-ad03be839119.png)

**Comment by Chanzhaoyu** [comment]
浏览器兼容性问题，更多里面的复制是否会报错？

**Comment by Chanzhaoyu** [comment]
已修复
