### ISSUE TITLE
【必看】ChatGPT快速注册登录指南！

### ISSUE THREAD

**Issue by Pacdage** [Chanzhaoyu/chatgpt-web#285]
ChatGPT注册登录流程详解，轻松上手：[ChatGPT注册登录指南](https://github.com/xiaoming2028/FreePAC/wiki/ChatGPT%E6%B3%A8%E5%86%8C%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%8C%E6%95%B4%E6%8C%87%E5%8D%97%EF%BC%89)

**Comment by JeamUmika** [comment]
这是你发的第二次了，第一次是昨天发的 https://github.com/Chanzhaoyu/chatgpt-web/issues/255#issue-1608736481

**Comment by Siri-Li** [comment]
这是发广告的
