### ISSUE TITLE
vercel 部署404 错误

### ISSUE THREAD

**Issue by Danielypzhang** [Chanzhaoyu/chatgpt-web#287]
vercel  使用和railway 同样的系统变量，但是提问返回404
![image](https://user-images.githubusercontent.com/26704645/222916357-59306d29-82b0-46cf-93b7-16d411dab439.png)

**Comment by pzcn** [comment]
你在vercel部署默认只部署了前端，需要自行写配置文件让他同时部署service

**Comment by Danielypzhang** [comment]
@pzcn 感谢回复，有参考的配置文件吗？不太懂这个。

**Comment by kollyQAQ** [comment]
@pzcn 同求指导如何配置

**Comment by pzcn** [comment]
> @pzcn 感谢回复，有参考的配置文件吗？不太懂这个。



> @pzcn 同求指导如何配置

单独一个实现前后端的我也不会，理论上可能能行。之前我搞过其他项目的，不过我现在没时间去尝试。

可以尝试前后端分离试试看

**Comment by qimo2020** [comment]
nginx配置文件 域名下面加上 那段&nbsp;


HiPHP
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月5日(星期天) 晚上10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [Chanzhaoyu/chatgpt-web] vercel 部署404 错误 (Issue #287)





  
@pzcn 感谢回复，有参考的配置文件吗？不太懂这个。
   
@pzcn 同求指导如何配置
  
单独一个实现前后端的我也不会，理论上可能能行。之前我搞过其他项目的，不过我现在没时间去尝试。
 
可以尝试前后端分离试试看

**Comment by kollyQAQ** [comment]
@qimo2020 不好意思，没看懂你的意思

HiPHP
***@***.***

是啥意思啊，请教下

**Comment by Danielypzhang** [comment]
暂时不搞了，先用railway
