### ISSUE TITLE
请问在安卓的termux上可以部署吗？我初步尝试了下卡在安装依赖那一步了

### ISSUE THREAD

**Issue by linxkon** [Chanzhaoyu/chatgpt-web#288]
执行pnpm install命令后，弹出EPERM: operation not permitted, symlink '../../cac@6.7.14/node_modules/cac'错误

**Comment by ChandlerVer5** [comment]
这好像是权限问题，这错误信息不完整，你可以尝试移动到 home 文件夹下或者提升下权限？

**Comment by linxkon** [comment]
🙇‍
