### ISSUE TITLE
docker镜像无法下载

### ISSUE THREAD

**Issue by gzelvis** [Chanzhaoyu/chatgpt-web#289]
hub.docker.com 那里其它镜像一下都装完了。就大神的 chatgpt-web 怎么都装不了，用pull 测试下来发现镜像下载速度超级慢，几乎到不可下载的速度。但从hub.docker.com下载其它镜像却是好的哦（就几秒下载完了），能看看怎么回事吗？

**Comment by acongee** [comment]
刚刚新加坡和日本的机器都 pull 了一下挺正常的

**Comment by gzelvis** [comment]
已经有大力了，不然连github都有困难，其它镜像不会的。后来试试用香港的本土机pull一秒就好了。从hub.docker.com难道还有其它的网址需要加速吗？还是hub.docker.com国内有镜像源所以。。。

**Comment by 7noemo** [comment]
不知道你有没有正确的输入docker容器的创建代码，作者大大首页的README.md其实写漏了
-- 后面是 chenzhaoyu94/chatgpt-web

# 前台运行
`docker run --name chatgpt-web --rm -it -p 3002:3002 --env OPENAI_API_KEY=your_api_key chenzhaoyu94/chatgpt-web`

# 后台运行
`docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_API_KEY=your_api_key chenzhaoyu94/chatgpt-web`

**Comment by oioilu** [comment]
> 已经有大力了，不然连github都有困难，其它镜像不会的。后来试试用香港的本土机pull一秒就好了。从hub.docker.com难道还有其它的网址需要加速吗？还是hub.docker.com国内有镜像源所以。。。

官方源报错
`Trying to pull repository docker.io/chenzhaoyu94/chatgpt-web ... 
manifest for docker.io/chenzhaoyu94/chatgpt-web:latest not found`
