### ISSUE TITLE
2.9.2 版本的 Latex 渲染有问题

### ISSUE THREAD

**Issue by acongee** [Chanzhaoyu/chatgpt-web#290]
行内或者单行的公式基本没问题，跨行的话就不行了
![image](https://user-images.githubusercontent.com/71998166/222917250-34337665-3c56-40b2-a8f2-5533f126805b.png)
![image](https://user-images.githubusercontent.com/71998166/222917384-cb68c01f-58e8-4a0a-b998-87bfd6728b6c.png)

**Comment by hyln9** [comment]
<img width="771" alt="Screenshot 2023-03-05 at 12 44 27 AM" src="https://user-images.githubusercontent.com/6761583/222918289-c713a44d-f2e1-4c13-a6c5-766108fb1e3d.png">

**Comment by acongee** [comment]
> <img alt="Screenshot 2023-03-05 at 12 44 27 AM" width="771" src="https://user-images.githubusercontent.com/6761583/222918289-c713a44d-f2e1-4c13-a6c5-766108fb1e3d.png">

确实，需要告诉他放在 $ 里面

**Comment by JeazW** [comment]
为什么我去这样的😂
![Uploading C22F4EAD-1B7F-4174-8718-5F4A667CE624.png…]()

**Comment by JeazW** [comment]
为什么我是这样的😂
![594CEBFD-18FB-4062-8573-1B0604BF154C](https://user-images.githubusercontent.com/75829171/222934569-ef584bd7-91aa-4611-bd36-9e80f2001283.png)

**Comment by acongee** [comment]
> 为什么我是这样的😂 ![594CEBFD-18FB-4062-8573-1B0604BF154C](https://user-images.githubusercontent.com/75829171/222934569-ef584bd7-91aa-4611-bd36-9e80f2001283.png)

告诉他把公式放在 $$$$ 里面就好了😂
