### ISSUE TITLE
iphone 输入框没有焦点的时候，点击输入框，键盘弹出后还是会挡住输入框，感觉没有修复， 已经更新到v2.9.2

### ISSUE THREAD

**Issue by helperAI** [Chanzhaoyu/chatgpt-web#291]
![image](https://user-images.githubusercontent.com/75373309/222917693-0277d562-6ef0-49f9-b857-cf21d605af6c.png)

**Comment by 7noemo** [comment]
再一次输入框就能滑上来了

**Comment by helperAI** [comment]
> 再一次输入框就能滑上来了

我知道呀，但是这个体验也太友好了吧

**Comment by JeazW** [comment]
换自带输入法就ok，如果一定要用搜狗，比如我，就在设置里把输入法上边的小工具都隐藏了，就正常了。

**Comment by helperAI** [comment]
> 换自带输入法就ok，如果一定要用搜狗，比如我，就在设置里把输入法上边的小工具都隐藏了，就正常了。
我现在切换为iphome自带的输入法了。还是会出现我说的问题。你们要先在消息聊天消息详情页面的其它地方点击一下，让输入框失去焦点，然后再点击输入框 ，就会发现此类问题，请看截图：
![image](https://user-images.githubusercontent.com/75373309/222951459-bcdef9f6-1d82-4e66-8c0b-eb95bbd012bc.png)
