### ISSUE TITLE
前端能否加一个账号登陆的限制？

### ISSUE THREAD

**Issue by wowmarcomei** [Chanzhaoyu/chatgpt-web#297]
前端能否加一个账号登陆的限制？
API是自己的token，暴露公网的话余额很快就会被耗尽，基于账号控制的话就可以设置登录账户。

**Comment by acongee** [comment]
#238 dev 版本有这个功能

**Comment by jbang2004** [comment]
> #238 dev 版本有这个功能

具体是在什么地方？

**Comment by acongee** [comment]
> > #238 dev 版本有这个功能
> 
> 具体是在什么地方？

#238

**Comment by Chanzhaoyu** [comment]
`2.10.0` 已添加此功能
