### ISSUE TITLE
建议增加docker封装方便部署

### ISSUE THREAD

**Issue by hostage007** [Chanzhaoyu/chatgpt-web#30]
如题，方便不会配置环境的小白，非常感谢。

**Comment by chenyuxiangyes** [comment]
+1 已经搞了快一小时了，还没运行起来。

**Comment by Chanzhaoyu** [comment]
hello~ 
因为我对 `docker` 不太了解，不过已经有小伙伴在 `PR`，我可以说下流程

服务端

1. 首先是复制 `service` 文件夹到服务器，并且通过 `node` 安装对应依赖
2. 运行 `pnpm build`
3. 运行 `pnpm prod`
4. 运行成功的端口是 `3002`，并将端口开放

前端
1、项目根目录下运行 `pnpm build` 会得到一个 `dist` 文件夹

**Comment by Chanzhaoyu** [comment]
`docker` 镜像已添加

**Comment by chenyuxiangyes** [comment]
感谢！！

**Comment by chenyuxiangyes** [comment]
建议docker-compose里增加一个管理员密码，再搞一个管理后台，进行个性化设置。
跟我同学装13的时候，我希望首页希望写上自己的名字，哈哈，GitHub链接肯定得保留。
辛苦大佬了！！！

**Comment by Chanzhaoyu** [comment]
> 建议docker-compose里增加一个管理员密码，再搞一个管理后台，进行个性化设置。 跟我同学装13的时候，我希望首页希望写上自己的名字，哈哈，GitHub链接肯定得保留。 辛苦大佬了！！！

个性化设置是设置 `chatgpt` 的参数吗，好像是个好主意

**Comment by chenyuxiangyes** [comment]
对，比如设置ADMIN密码是：Qwerty，那么在https://chatgpt-web.example.com/admin输入密码后就可以进行设置。

**Comment by Anrufen** [comment]
环境变量是不是要写成 - open api key:xxx才行？不然一直提示必须mapping；但是写成这样还是提示key无效

**Comment by Chanzhaoyu** [comment]
> 环境变量是不是要写成 - open api key:xxx才行？不然一直提示必须mapping；但是写成这样还是提示key无效

`OPENAI_API_KEY`

**Comment by Chanzhaoyu** [comment]
> 环境变量是不是要写成 - open api key:xxx才行？不然一直提示必须mapping；但是写成这样还是提示key无效

`OPENAI_API_KEY`
