### ISSUE TITLE
发现有可以实时联网搜索的chargpt应用

### ISSUE THREAD

**Issue by goodwisdom** [Chanzhaoyu/chatgpt-web#300]
https://chat.binjie.site:7777
就是本源码做的修改，这个功能不错，有可能增加吗？

**Comment by luy98** [comment]
牛。。。

**Comment by denvey** [comment]
这个是不错，不值得用什么什么API，难道是Bing的吗

**Comment by i-iooi-i** [comment]
> 这个是不错，研究了一下，用的是这个 https://github.com/circlestarzero/EX-chatGPT

看上去好牛的样子，最新剧集它居然也能正确回答出信息。

**Comment by nuoooo** [comment]
牛。。就是联网有点不准

**Comment by binjie09** [comment]
是我的网站。。。我会一直免费提供服务。感谢作者写的前端。后端其实是自己很早之前就写了的。联网功能也很早就有，后面参考https://github.com/circlestarzero/EX-chatGPT做了prompt的优化，有apiKey池。加了很多key（60个）防止 429 请求过多。

**Comment by mkdirmushroom** [comment]
> 是我的网站。。。我会一直免费提供服务。感谢作者写的前端。后端其实是自己很早之前就写了的。联网功能也很早就有，后面参考https://github.com/circlestarzero/EX-chatGPT 做了prompt的优化，有apiKey池。加了很多key（60个）防止 429 请求过多。

请问oepnai不是根据ip+key双重验证限制的嘛？我之前做了测试，我加了key池，仍然429，所以认为它是限制了ip。

**Comment by binjie09** [comment]
> > 是我的网站。。。我会一直免费提供服务。感谢作者写的前端。后端其实是自己很早之前就写了的。联网功能也很早就有，后面参考https://github.com/circlestarzero/EX-chatGPT 做了prompt的优化，有apiKey池。加了很多key（60个）防止 429 请求过多。
> 
> 请问oepnai不是根据ip+key双重验证限制的嘛？我之前做了测试，我加了key池，仍然429，所以认为它是限制了ip。

不清楚，我这一个代理ip，QPM最大1800正常。偶尔会429，后端发起重试就好。

**Comment by goodwisdom** [comment]
> 是我的网站。。。我会一直免费提供服务。感谢作者写的前端。后端其实是自己很早之前就写了的。联网功能也很早就有，后面参考https://github.com/circlestarzero/EX-chatGPT 做了prompt的优化，有apiKey池。加了很多key（60个）防止 429 请求过多。

网站似乎已经好几天打不开了

**Comment by binjie09** [comment]
> > 是我的网站。。。我会一直免费提供服务。感谢作者写的前端。后端其实是自己很早之前就写了的。联网功能也很早就有，后面参考https://github.com/circlestarzero/EX-chatGPT 做了prompt的优化，有apiKey池。加了很多key（60个）防止 429 请求过多。
> 
> 网站似乎已经好几天打不开了

被运营商dns污染了，可以尝试托管cloudflare的 https://chat.yqcloud.top/  国内还有 https://chat1.binjie.site:7777/ https://chat2.binjie.site:7777/ 一直到chat9都有，暂时没被污染，低调使用。勿微信或国内平台转发。

**Comment by goodwisdom** [comment]
> > > 是我的网站。。。我会一直免费提供服务。感谢作者写的前端。后端其实是自己很早之前就写了的。联网功能也很早就有，后面参考https://github.com/circlestarzero/EX-chatGPT 做了prompt的优化，有apiKey池。加了很多key（60个）防止 429 请求过多。
> > 
> > 网站似乎已经好几天打不开了
> 
> 被运营商dns污染了，可以尝试托管cloudflare的 https://chat.yqcloud.top/  国内还有 https://chat1.binjie.site:7777/ https://chat2.binjie.site:7777/ 一直到chat9都有，暂时没被污染，低调使用。勿微信或国内平台转发。

如果搭建后域名只是自己用，未公开，域名还会被污染吗？

**Comment by xiaosaaaa** [comment]
> 是我的网站。。。我会一直免费提供服务。感谢作者写的前端。后端其实是自己很早之前就写了的。联网功能也很早就有，后面参考https://github.com/circlestarzero/EX-chatGPT 做了prompt的优化，有apiKey池。加了很多key（60个）防止 429 请求过多。

你这个能联网的牛哇，我也想搭一个你这样的，能放GitHub上吗？大佬

**Comment by binjie09** [comment]
> 

最晚周末，会放的

**Comment by xiaosaaaa** [comment]
> > 
> 
> 最晚周末，会放的 @xiaosaaaa

谢谢大佬，我到时候一定支持

**Comment by xiaosaaaa** [comment]
> > > 
> > 
> > 
> > 最晚周末，会放的 @xiaosaaaa
> 
> 谢谢大佬，我到时候一定支持

@binjie09 谢谢大佬，到时候一定支持

**Comment by wnb6cf** [comment]
> > 
> 
> 最晚周末，会放的 @xiaosaaaa

放了吗？

**Comment by binjie09** [comment]
> > > 
> > 
> > 
> > 最晚周末，会放的 @xiaosaaaa 
> 
> 放了吗？
@wnb6cf 

两个接口以gist形式放出https://gist.github.com/binjie09/5a8e9a9ff2eb84eda198c8e0af33b86a
核心是这段代码，next写的两个接口，由于代码里有很多敏感的key 还有不大合法的操作（指openai key池），后续整个项目会重写
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/18377378/225068738-0cbb067d-353f-4969-ab31-158c101035d2.png">
