### ISSUE TITLE
希望前端增加一个按键盘上方向键，输入框自动读取上一次输入的内容，因为有时候问题需要根据他的回复修正重新问，感谢

### ISSUE THREAD

**Issue by msterzhang** [Chanzhaoyu/chatgpt-web#301]

**Comment by bluefrankey** [comment]
确实有这个需要

**Comment by oikewll** [comment]
有必要，上一次的提问不够精准，需要修改再问一次
telegram 的是编辑状态下上一条信息

**Comment by yi-ge** [comment]
<https://github.com/Chanzhaoyu/chatgpt-web/pull/497> 请问是否能满足需求？ 使用上键很难判断是要修改还是追问。
