### ISSUE TITLE
使用apikey回答文字过多就会卡住，无法得到完整回答

### ISSUE THREAD

**Issue by wxe999** [Chanzhaoyu/chatgpt-web#302]
![image](https://user-images.githubusercontent.com/57397393/222941147-32b27978-201b-41e5-ad3d-2e0d743f91c6.png)

**Comment by wwlmm** [comment]
直接在chatgpt官网上，字数多了也会停的

**Comment by wxe999** [comment]
> 直接在chatgpt官网上，字数多了也会停的

这比官网字数少了好多（⊙ｏ⊙）

**Comment by CKylinMC** [comment]
> > 直接在chatgpt官网上，字数多了也会停的
> 
> 这比官网字数少了好多（⊙ｏ⊙）

可以试试看回复一个“继续说” / "continue"，虽然这会消耗额外的token。

**Comment by wxe999** [comment]
> > > 直接在chatgpt官网上，字数多了也会停的
> > 
> > 
> > 这比官网字数少了好多（⊙ｏ⊙）
> 
> 可以试试看回复一个“继续说” / "continue"，虽然这会消耗额外的token。

还没回答完毕是没法发送消息的，只能终止ai回答。
