### ISSUE TITLE
国内环境调用超时

### ISSUE THREAD

**Issue by selectbook** [Chanzhaoyu/chatgpt-web#304]
怎么解决国内网络环境下调用超时的问题呢，

**Comment by Chanzhaoyu** [comment]
使用代理转发

**Comment by selectbook** [comment]
代码里面是配置这两个吗
# Socks Proxy Host
SOCKS_PROXY_HOST=

# Socks Proxy Port
SOCKS_PROXY_PORT=

**Comment by selectbook** [comment]
代码里面是配置这两个吗
`# Socks Proxy Host
SOCKS_PROXY_HOST=

# Socks Proxy Port
SOCKS_PROXY_PORT=`

**Comment by selectbook** [comment]
代码里面是配置这两个吗
`SOCKS_PROXY_HOST=
SOCKS_PROXY_PORT=`

**Comment by Chanzhaoyu** [comment]
> 代码里面是配置这两个吗
> `SOCKS_PROXY_HOST= SOCKS_PROXY_PORT=`

是，可以自己配置，也可以把 API_BASE_URL 换成社区转发的
