### ISSUE TITLE
调用API也需要梯子么？

### ISSUE THREAD

**Issue by lust0yixiong** [Chanzhaoyu/chatgpt-web#306]
<img width="192" alt="image" src="https://user-images.githubusercontent.com/4714775/222942560-632d1b8b-07af-45d5-b076-4876d63bc0b6.png">
是因为梯子的原因么？

**Comment by hfpp2012copy** [comment]
需要的

**Comment by Chanzhaoyu** [comment]
早几天被墙了

**Comment by shenwrt** [comment]
我是在软路由里搭，直接就翻了
