### ISSUE TITLE
发图片调教不好用了

### ISSUE THREAD

**Issue by 404gods** [Chanzhaoyu/chatgpt-web#309]
![网页捕获_5-3-2023_14148_gpt 711000 xyz](https://user-images.githubusercontent.com/50573302/222944337-3440afb8-84d8-47ba-ac88-d77d4130e4e0.jpeg)

**Comment by ChandlerVer5** [comment]
我测试，是可以的。等pr合并之后，应该就可以了

**Comment by Chanzhaoyu** [comment]
多试几次，3.5之后是没有以前3.0对这种命令的响应了。
