### ISSUE TITLE
点击无用

### ISSUE THREAD

**Issue by 7757** [Chanzhaoyu/chatgpt-web#31]
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/48285391/218947867-8d0d63d9-73e7-4724-82bd-b9f65f9e278e.png">

**Comment by Chanzhaoyu** [comment]
需要更多的信息～

**Comment by 7757** [comment]
> 已修复，因合并`开发测试分支`导致
老哥可以稍微写点注释嘛 我一个后端 有点看不太懂

**Comment by Chanzhaoyu** [comment]
> > 已修复，因合并`开发测试分支`导致
> > 老哥可以稍微写点注释嘛 我一个后端 有点看不太懂

可以的哦，尽量
