### ISSUE TITLE
能否支持设置gpt-3.5-turbo，而不是默认使用gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by danovw** [Chanzhaoyu/chatgpt-web#311]
[ID of the model to use. Currently, only gpt-3.5-turbo and gpt-3.5-turbo-0301 are supported.](https://platform.openai.com/docs/api-reference/chat/create#chat/create-model)

`gpt-3.5-turbo-0301`模型能力后续不会有更新：
https://platform.openai.com/docs/models/gpt-3-5

**Comment by LuckyZY** [comment]
我也希望有选择，买了付费版本的还是希望能调最新的API接口，给朋友们玩起来也更有趣一些

**Comment by wnb6cf** [comment]
service/src/chatgpt/index.ts中改
 

 if (process.env.OPENAI_API_KEY) {
    const options: ChatGPTAPIOptions = {
      model: "gpt-3.5-turbo",
      temperature: 0.8,
      apiKey: process.env.OPENAI_API_KEY,
      presence_penalty: 0.6,
      debug: false,
    }

**Comment by LuckyZY** [comment]
Docker的话也是进入到容器里面改这个嘛？

**Comment by tiro8183** [comment]
> Docker的话也是进入到容器里面改这个嘛？

建议.env文件中添加MODEL参数重新构建

**Comment by Chanzhaoyu** [comment]
service 中可以自行去调整

**Comment by tiro8183** [comment]
使用统计页面始终显示是gpt-3.5-turbo-0301, 不清楚什么原因

**Comment by danovw** [comment]
> 使用统计页面始终显示是gpt-3.5-turbo-0301, 不清楚什么原因

是的，我修改service里的参数也没生效

**Comment by acongee** [comment]
看本地的日志显示模型是 gpt-3.5-turbo，但是 OpenAI 官网上的使用统计是 gpt-3.5-turbo-0301，不知道是什么问题
