### ISSUE TITLE
有什么办法可以永久更改头像和名字

### ISSUE THREAD

**Issue by xiaosaaaa** [Chanzhaoyu/chatgpt-web#313]
更改完名字头像后，换台设备也不能记住新头像和名字

**Comment by ChandlerVer5** [comment]
只能自己配置到服务端，这种小数据，在服务端写进json文件读取就行了

**Comment by Chanzhaoyu** [comment]
前端文件里面修改了再打包

**Comment by helperAI** [comment]
> 前端文件里面修改了再打包，然后把相关可以调整的代码删除就好。

此处问你下面这个问题可能不太合适，不过我真的想请教你在哪个js函数，通过stream方式如何识别出目前这个chunk的消息是最后的部分。记得chatgpt包是有一个if (data === '[DONE]') 来代表结束的吧，我们的代码如何识别stream结束了呢。本人急需要（因为我想在消息返回完整后同步到后台数据库，谢谢）

**Comment by ChandlerVer5** [comment]
> > 前端文件里面修改了再打包，然后把相关可以调整的代码删除就好。
> 
> 此处问你下面这个问题可能不太合适，不过我真的想请教你在哪个js函数，通过stream方式如何识别出目前这个chunk的消息是最后的部分。记得chatgpt包是有一个if (data === '[DONE]') 来代表结束的吧，我们的代码如何识别stream结束了呢。本人急需要（因为我想在消息返回完整后同步到后台数据库，谢谢）

我看了下，目前是获取不到的，但是官网自己的api应该是可以的。 chatgpt包只返回了需要的信息，将其他信息给去除了，包括整个会话的结束（meta:{ finish_details: {type: 'stop'} ,...}）

**Comment by helperAI** [comment]
> > > 前端文件里面修改了再打包，然后把相关可以调整的代码删除就好。
> > 
> > 
> > 此处问你下面这个问题可能不太合适，不过我真的想请教你在哪个js函数，通过stream方式如何识别出目前这个chunk的消息是最后的部分。记得chatgpt包是有一个if (data === '[DONE]') 来代表结束的吧，我们的代码如何识别stream结束了呢。本人急需要（因为我想在消息返回完整后同步到后台数据库，谢谢）
> 
> 我看了下，目前是获取不到的，但是官网自己的api应该是可以的。 chatgpt包只返回了需要的信息，将其他信息给去除了，包括回答的结束（meta:{ finish_details: {type: 'stop'} ,...}）

谢谢。你觉得如果要把聊天记录长期保存到后台数据库，应该用下面哪种机制？
方法1）修改chatgpt包里面处理stream的消息返回逻辑，标识出steam已经完成，从而前端也知道何时已经获取到完整消息，这个可行吗？
方法2）通过vue的watch机制，监测变量currentChat的内容有变化，并且1秒内不再变化，则同步该chat的所有消息到后端mysql中。
方法3）希望听听各位同仁的建议？
再次感谢，借宝地一用探讨一下

**Comment by ChandlerVer5** [comment]
第一个完全可行

**Comment by shenwrt** [comment]
搜索一下那个英文，直接在文件里修改，然后再重新安装一下，还有改默认主题颜色，头像

**Comment by xiaosaaaa** [comment]
感谢各位

**Comment by Chanzhaoyu** [comment]
> > > > 前端文件里面修改了再打包，然后把相关可以调整的代码删除就好。
> > > 
> > > 
> > > 此处问你下面这个问题可能不太合适，不过我真的想请教你在哪个js函数，通过stream方式如何识别出目前这个chunk的消息是最后的部分。记得chatgpt包是有一个if (data === '[DONE]') 来代表结束的吧，我们的代码如何识别stream结束了呢。本人急需要（因为我想在消息返回完整后同步到后台数据库，谢谢）
> > 
> > 
> > 我看了下，目前是获取不到的，但是官网自己的api应该是可以的。 chatgpt包只返回了需要的信息，将其他信息给去除了，包括回答的结束（meta:{ finish_details: {type: 'stop'} ,...}）
> 
> 谢谢。你觉得如果要把聊天记录长期保存到后台数据库，应该用下面哪种机制？ 方法1）修改chatgpt包里面处理stream的消息返回逻辑，标识出steam已经完成，从而前端也知道何时已经获取到完整消息，这个可行吗？ 方法2）通过vue的watch机制，监测变量currentChat的内容有变化，并且1秒内不再变化，则同步该chat的所有消息到后端mysql中。 方法3）希望听听各位同仁的建议？ 再次感谢，借宝地一用探讨一下

前端的话 `const {data} = await fetchChatAPIProcess<Chat.ConversationResponse>({` 在这行代码后获得的数据就是完整的了
