### ISSUE TITLE
使用OPENAI_ACCESS_TOKEN报错403

### ISSUE THREAD

**Issue by sunnoy** [Chanzhaoyu/chatgpt-web#314]
![WX20230305-182739@2x](https://user-images.githubusercontent.com/19342276/222954994-34fa2d48-02bc-4220-95be-4d9c4d116141.png)

**Comment by coder-mtj** [comment]
同问，但是好像是不再支持public key了

**Comment by acongee** [comment]
这个，人家主动 block 好像也没啥办法😂，如果能知道是因为什么被 block 还好说

**Comment by piglingcn** [comment]
那这个怎么办。。。

**Comment by 18845898547** [comment]
同问  用api_key提示我充值  用accesstoken报403 access denied

**Comment by Chanzhaoyu** [comment]
> 同问 用api_key提示我充值 用accesstoken报403 access denied

用代理
