### ISSUE TITLE
异步问题

### ISSUE THREAD

**Issue by Kerwin1202** [Chanzhaoyu/chatgpt-web#317]
https://github.com/Chanzhaoyu/chatgpt-web/blob/de34d97529cd2821227e06b7abc2580eee769951/src/views/chat/index.vue#L29

https://github.com/Chanzhaoyu/chatgpt-web/blob/de34d97529cd2821227e06b7abc2580eee769951/src/views/chat/layout/sider/List.vue#L13

我想改代码，目前数据都在本地 localstorge 想 http 去获取 所以 就异步 http 请求了，但是会造成这个代码无法加载，对vue不熟

**Comment by helperAI** [comment]
我也想把聊天信息保存到后端mysql中，我都不知道在哪里调用api来保存数据，尤其是stream模式获取到的结果是一个字一个字返回到前端的，总不能一个字一个字保存到后台数据库吧。但是又不知道何时返回结果已经全部完成了。这个问题困惑我好几天了。
非常希望大家一起交流探讨一下。

**Comment by Kerwin1202** [comment]
@helperAI  存数据我改好了，我现在要把页面也改下 他总共有2个接口 chat 以及 chat-process 区别在于 process 会输出中间部分，chat只会返回最后一个完整的

参考我下面这个

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/16319833/222964226-ce38997d-80ce-4a6b-bda7-54c0625992b2.png">

**Comment by helperAI** [comment]
> @helperAI 存数据我改好了，我现在要把页面也改下 他总共有2个接口 chat 以及 chat-process 区别在于 process 会输出中间部分，chat只会返回最后一个完整的
> 
> 参考我下面这个
> 
> <img alt="image" width="1044" src="https://user-images.githubusercontent.com/16319833/222964226-ce38997d-80ce-4a6b-bda7-54c0625992b2.png">

你好赞，加个微信聊，我的微信：shopifier，大家一起多交流探讨哈。

**Comment by qimo2020** [comment]
都挺会整的，一起研究下

**Comment by Kerwin1202** [comment]
看了官方文档，自己解决了 改为  `onMounted` 中处理
