### ISSUE TITLE
为何不是流式输出的？

### ISSUE THREAD

**Issue by qimo2020** [Chanzhaoyu/chatgpt-web#318]
你好：
  ip:端口号 ，访问是流式输出的。nginx代理域名解析后，测试发现是非流式输出？

**Comment by pzcn** [comment]
https://github.com/Chanzhaoyu/chatgpt-web#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by acongee** [comment]
#147 参考这个，发 issue 前建议先看下已有的
