### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by gaozhun** [Chanzhaoyu/chatgpt-web#319]
使用APIkey有报错，请问是什么原因呢？
request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established

**Comment by qimo2020** [comment]
国内被墙了，不要用国内服务器。你配置完nginx文件后，重新构建&nbsp;


HiPHP
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月5日(星期天) 晚上10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Chanzhaoyu/chatgpt-web] Client network socket disconnected before secure TLS connection was established (Issue #319)





 
使用APIkey有报错，请问是什么原因呢？
 request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established

**Comment by Chanzhaoyu** [comment]
被墙了，参考其他 `issues`

**Comment by xingshijun** [comment]
我也遇到了，但不是被墙，发其他的还是正常的
【我希望你能担任英语翻译、拼写校对和修辞改进的角色。我会用任何语言和你交流，你会识别语言，将其翻译并用更为优美和精炼的英语回答我。请将我简单的词汇和句子替换成更为优美和高雅的表达方式，确保意思不变，但使其更具文学性。请仅回答更正和改进的部分，不要写解释。我的第一句话是“how are you ?”，请翻译它。】这句话整体发就会报错，断个句分开发就可以回复，但最后【我的第一句话是“how are you ?”，请翻译它】发了就报错
