### ISSUE TITLE
我想只使用前端，然后我是不是只用修改根目录下的.env字段？再然后我启动前端发送消息回复的是Network Error，这是什么问题？

### ISSUE THREAD

**Issue by anranq** [Chanzhaoyu/chatgpt-web#320]
![image](https://user-images.githubusercontent.com/126095767/222966501-b80ab8e9-53f8-4db9-a096-3552812d17b2.png)

**Comment by Kerwin1202** [comment]
自然是因为只使用前端了。后端负责对接chatgpt api 你不使用就会这样

**Comment by anranq** [comment]
> 当然是因为只使用前面了。后面负责对接chatgpt api 你不使用就会这样

我写了一个后端，我现在想把前端的数据拿过来看一下，但是没有对接到我的接口，不太懂是什么问题？

**Comment by anranq** [comment]
![image](https://user-images.githubusercontent.com/126095767/222968359-7ee530dc-e7c8-451d-b488-b19c12ef7e35.png)
![image](https://user-images.githubusercontent.com/126095767/222968373-4da48b87-efdf-42ce-9a52-178b920eda49.png)
这样子？

**Comment by fierceX** [comment]
我不太了解node.js，但是我用nginx反代前端，加了个/api的路径，代理到后端的路径上就行了。具体nginx示例如下：

```
location /api {
	proxy_pass http://127.0.0.1:3002/;
        proxy_buffering off;
}
```

**Comment by Kerwin1202** [comment]
@anranq 你不能乱写  /example 要 符合已有的接口 如果按照你的设置（.env） 那么你的后端要  
支持以下接口

http://localhost:8082/example/config
http://localhost:8082/example/chat-process
http://localhost:8082/example/verify （dev）分支才有

**Comment by anranq** [comment]
> @anranq 你不能乱写 /example 要 符合已有的接口 如果按照你的设置（.env） 那么你的后端要 支持以下接口
> 
> http://localhost:8082/example/config http://localhost:8082/example/chat-process http://localhost:8082/example/verify （dev）分支才有

再开启了这三个接口也还是不行，依旧是Network Error

**Comment by Kerwin1202** [comment]
@anranq 看下 f12 里面的错误 估计是跨域没解决

**Comment by anranq** [comment]
> @anranq 看下 f12 里面的错误 估计是跨域没解决

确实是跨域问题

**Comment by anranq** [comment]
![image](https://user-images.githubusercontent.com/126095767/222970748-d044da9d-65ad-4c99-b9e8-1ae391b326fb.png)
这个没有用户ID的吗？如何判断来自哪个用户？  @Kerwin1202

**Comment by Kerwin1202** [comment]
@anranq 他这个没登录的。自然没有id

**Comment by anranq** [comment]
@Kerwin1202 有没有做有登录的参考？或者有什么办法能增加一个判断

**Comment by helperAI** [comment]
我们也在准备做登录接口的整合。大家一起多探讨啊。看看如何实现是最小发动前端，同时后端逻辑也比较清晰的。大家有好的思路可以一起多交流。我要感谢 @Kerwin1202 的指点。

**Comment by Kerwin1202** [comment]
@anranq 参考 dev 分支的验证

**Comment by Liu-Shihao** [comment]
> chat-process

我用python单独写了一个接口，也是跨域了，要怎么解决呢？

**Comment by CKylinMC** [comment]
> > chat-process
> 
> 我用python单独写了一个接口，也是跨域了，要怎么解决呢？

像flask这样的有一个包flask-cors，其他的框架应该也有类似的，可以搜索一下框架名称+cors。没有的话也可以自己重写一下相关Header就可以了。

**Comment by anranq** [comment]
> 

需要自己在后端开启跨域
