### ISSUE TITLE
经常出现错误代码429，请问是何原因？

### ISSUE THREAD

**Issue by goodwisdom** [Chanzhaoyu/chatgpt-web#321]
问了几个问题后，随机就会出现这个429错误，我以为是key泄露，换了key，还是会出现，一分钟肯定没有超过20个请求
ChatGPT error 429: { "error": { "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-xccgfgggghherfghettg on requests per min. Limit: 20 / min. Current: 30 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.", "type": "requests", "param": null, "code": null } }

**Comment by acongee** [comment]
加访问限制吧，搜 chaygpt web 可以直接搜出来会被人滥用

**Comment by goodwisdom** [comment]
> 加访问限制吧，搜 ChatGPT Web 可以直接搜出来会被其他人滥用

我记得是在什么地方可以改标题让搜不出来，你知道吗？

**Comment by acongee** [comment]
> > 加访问限制吧，搜 ChatGPT Web 可以直接搜出来会被其他人滥用
> 
> 我记得是在什么地方可以改标题让搜不出来，你知道吗？

#238 在里面有讲
