### ISSUE TITLE
能否实现在前端直接修改OPENAI_API_KEY

### ISSUE THREAD

**Issue by lizhengxiang87** [Chanzhaoyu/chatgpt-web#322]
APIKey用完后必须进到文件目录修改.env文件后，重启服务器，操作起来比较麻烦，能否直接在设置那直接加一个更改的功能？

**Comment by rhymed-liu** [comment]
我已经改为数据库获取了并加了轮询

**Comment by Chanzhaoyu** [comment]
> 我已经改为数据库获取了并加了轮询

轮询有封号风险

**Comment by rhymed-liu** [comment]
> > 我已经改为数据库获取了并加了轮询
> 
> 轮询有封号风险

确实有,不知道根据上下文关联key是否有风险,相当于一个key只在一个上下文中使用
