### ISSUE TITLE
计量对话总 Token 预防 error 400 错误

### ISSUE THREAD

**Issue by sudoskys** [Chanzhaoyu/chatgpt-web#324]
计量 Token
https://www.npmjs.com/package/gpt-3-encoder

关联 Issue
https://github.com/Chanzhaoyu/chatgpt-web/issues/298

**Comment by wejudging** [comment]
什么时候优化一下啊。期待作者大大更新

**Comment by Nicolas-Gong** [comment]
service/src/chatgpt/index.ts

文件第27行添加
`maxModelTokens: 3500,` 
试试，记得升级到最新版
