### ISSUE TITLE
在完全没使用的情况下一天2000多的requests

### ISSUE THREAD

**Issue by jh3274** [Chanzhaoyu/chatgpt-web#330]
平均每5分钟10000token的请求 ，请问是什么原因
![Screenshot_20230305-214946](https://user-images.githubusercontent.com/27186426/222992870-f5a7d74f-f7e2-4407-b478-57c68e72463c.png)
![Screenshot_20230305-214725](https://user-images.githubusercontent.com/27186426/222992884-45a47286-5eea-426c-8f26-05de0230a2c5.png)

**Comment by jh3274** [comment]
新建了一个号  新DD的机器 一个晚上
![Screenshot_20230306-074834](https://user-images.githubusercontent.com/27186426/222993180-eaa0a176-1ea1-4005-b0da-545c57d667b8.png)
![Screenshot_20230306-074821](https://user-images.githubusercontent.com/27186426/222993181-35c1f0b6-3341-4710-bf64-73ee7d31c26c.png)

**Comment by goodwisdom** [comment]
估计和#321的问题本质是一样的

**Comment by jh3274** [comment]
所以这个问题无解？ 我换了台机器 换了个账号 也是一样的被刷api 而且只刷14小时

**Comment by acongee** [comment]
> 所以这个问题无解？ 我换了台机器 换了个账号 也是一样的被刷api 而且只刷14小时

nginx 加个 basic_authn 或者 dev 版本 #238 也有这个功能

**Comment by Chanzhaoyu** [comment]
`2.10.0` 添加了访问权限限制
