### ISSUE TITLE
是不是应该考虑整合图片生成模型：DALLE了？

### ISSUE THREAD

**Issue by helperAI** [Chanzhaoyu/chatgpt-web#331]
目前的图片生成好像不work，用起来也很不友好。是不是应该允许切换模型，然后首先把DALLE的图片生成模型整合到页面来。
你们说呢？

**Comment by AlpacaBi** [comment]
我自己在这个项目加入过DALLE，其实很简单，本身这个项目里的openai nodejs sdk就有图片生成的api，而且共享一套apikey，但是最后我放弃了，主要是两个原因：

1.DALLE生成的图片不怎么样，翻车率极高，效果真的不好
2.DALLE要钱，而且还不是扣你18刀免费余额的钱，DALLE费用是直接算在你信用卡里的，一个请求大概0.02美元，生成10个图片1块多rmb

**Comment by AlpacaBi** [comment]
> 原来如此，但是很多的chatGPT的应用我都看到有图片生成功能，难道他们不要钱的吗？感觉都是随便用的。

我见过一些生成图片的，现在有一些ai平台可以通过网址生成图片，比如这个

https://image.pollinations.ai/prompt/whitecat

你想生成什么图片，你只需要改最后面的whitecat就行了，基本是这个原理。

这个不要钱，但是效果怎么样我没试过

**Comment by CornerSkyless** [comment]
> 我自己在这个项目加入过DALLE，其实很简单，本身这个项目里的openai nodejs sdk就有图片生成的api，而且共享一套apikey，但是最后我放弃了，主要是两个原因：
> 
> 1.DALLE生成的图片不怎么样，翻车率极高，效果真的不好 2.DALLE要钱，而且还不是扣你18刀免费余额的钱，DALLE费用是直接算在你信用卡里的，一个请求大概0.02美元，生成10个图片1块多rmb

图片生成好像是扣额度的，但确实很贵 #410
