### ISSUE TITLE
做了个登录注册页面，供大家参考(更新进度)

### ISSUE THREAD

**Issue by gouguoyin** [Chanzhaoyu/chatgpt-web#332]
未登录状态下，出现登录注册按钮，点击左下角 `头像` 或者 `登录/注册` 按钮弹出登录注册界面，如下图
![01](https://user-images.githubusercontent.com/13517412/223004410-c82f1a33-59d4-4306-ae84-cf0e8f9f1e47.png)
![02](https://user-images.githubusercontent.com/13517412/223004456-e0587b3f-f6bb-42ef-94bc-6231301c5603.png)
![03](https://user-images.githubusercontent.com/13517412/223004584-64665536-aae9-4498-a8a6-7f95cebf94e2.png)
![04](https://user-images.githubusercontent.com/13517412/223004621-23ff48c3-2165-4dce-90f4-761b0408f3cc.png)
![05](https://user-images.githubusercontent.com/13517412/223004658-9de0cbee-75f5-4131-a7a3-922700fb675e.png)
![06](https://user-images.githubusercontent.com/13517412/223004725-73ade972-9004-4eda-883e-6e91f1f9bdee.png)
未登录状态下，出现 `个人中心` 按钮和 `设置` 按钮，点击左下角 `头像` 可以更换头像，点击 `设置` 按钮弹出用户自定义设置界面，如下图
![11](https://user-images.githubusercontent.com/13517412/223005680-21b4c14f-fb9a-48bb-b3f6-ca87b9b5c877.png)
![12](https://user-images.githubusercontent.com/13517412/223005719-0b5959fa-8e33-4c06-8664-62b5ac336e75.png)
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/13517412/223007860-db3b0a90-26e3-44ee-8c18-02ab0cd66567.png">

为了方便大家沟通交流，同步消息，建了QQ群，群号 145225165
![image](https://user-images.githubusercontent.com/13517412/223005824-5fc2075d-371a-4f68-8d09-d91598844e50.png)

**Comment by ludashi2020** [comment]
求分享

**Comment by ludashi2020** [comment]
求分享

**Comment by juzi3333** [comment]
这厉害啊666

**Comment by bluefrankey** [comment]
急需登录后才能合用的页面！

**Comment by helperAI** [comment]
点赞

**Comment by Chanzhaoyu** [comment]
厉害，修改能力杠杠的👍

**Comment by helperAI** [comment]
搞成分支，然后大家可以自定义后台的接口标准。那就更棒了。

**Comment by pattonbina** [comment]
6，求分享

**Comment by gouguoyin** [comment]
> 厉害，修改能力杠杠的👍

就是升级比较麻烦，需要改源码

**Comment by helperAI** [comment]
> > 厉害，修改能力杠杠的👍
> 
> 就是升级比较麻烦，需要改源码

所以，建议搞一个分支，这个功能应该是很大一部分用户的诉求。可以不过完善。后端接口可以大家自己实现。或者直接使用版主的

**Comment by gouguoyin** [comment]
**最近进度**
登录注册页面加了个倒计时，防止邮件被滥发
![519982C76D9143E9EDBD8973E4F4F9D7](https://user-images.githubusercontent.com/13517412/223031756-3f0fa207-7230-45bd-a825-4ad20baaf998.jpg)
![519982C76D9143E9EDBD8973E4F4F9D7](https://user-images.githubusercontent.com/13517412/223031769-30349f6b-a903-445c-bf80-3cad9c4ef289.jpg)

**Comment by xiaosaaaa** [comment]
在哪有这个版本

**Comment by helperAI** [comment]
最好支持微信直接登录。

**Comment by gouguoyin** [comment]
> 最好支持微信直接登录。
微信已经禁止chatGPT了，会被封的

**Comment by helperAI** [comment]
> > 最好支持微信直接登录。
> > 微信已经禁止chatGPT了，会被封的

确实，只能是邮箱了。准备fork一个分支或者独立项目吗？

**Comment by gouguoyin** [comment]
> > > 最好支持微信直接登录。
> > > 微信已经禁止chatGPT了，会被封的
> 
> 确实，只能是邮箱了。准备fork一个分支或者独立项目吗？

最好方式是短信验证，只是发送短信需要花钱，所以只能用免费的邮箱验证码了

**Comment by Cp0204** [comment]
支持！

**Comment by wenkangzhou** [comment]
关注

**Comment by gouguoyin** [comment]
最新进度，因为改动较大，新来了一个分支 https://github.com/gouguoyin/chatgpt-web
