### ISSUE TITLE
今天访问时出现403

### ISSUE THREAD

**Issue by piglingcn** [Chanzhaoyu/chatgpt-web#333]
<p>You do not have access to chat.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.

**Comment by 18845898547** [comment]
我也是这个问题 你是用的accesstoken吗

**Comment by whatmeans** [comment]
Request failed with status code 504

还有一个504的错误。

**Comment by wwlmm** [comment]
多刷新几次 就出来了 不晓得是什么原因

**Comment by Simon-Yi** [comment]
我也是，用Token似乎不行
