### ISSUE TITLE
因为现实工作繁忙，基本功能正常的情况下，更新会相较之前放缓，请点击查看详情...

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#334]
因为现实工作繁忙，目前基本功能正常的情况下，更新会相较之前放缓，每个 `Issues` 和 `PR` 我都有看，也很感谢大家建议和贡献

这里有个由 @gouguoyin 建立的社区 QQ 群 `145225165`，如果实在有问题，也方便大家去交流，本来我是不用 `QQ `的，不过我也在里面潜水，感谢

还有解释下为什么会用 `chatgpt` 这个 `npm` 包和使用 `octet-stream` 来做数据流的原因：

如果关注的早的小伙伴应该知道，之前的 `GPT-3` 和现在的 `GPT-3.5` 是有很大差别，返回的内容也基本是以纯文本的形式，为了配合 `accessToken` 使用并且渲染消息，并且在 `API` 被墙了之后实现 `Scoks` ，这是一个折中的方法。

现在的我认为自 `API` 更新之后，它其实已经没有任何开发上的优势，项目也没有优化的更好，大家直接调用接口二次开发可能会更好的扩展和自定义，并且目前并不能直接抛弃 `accessToken` 这个模式。

这个项目 `20` 多天来，收获了很多的关注和部分打赏，也感谢各位的建议和 `PR`。

Thank everyone~

**Comment by Chanzhaoyu** [comment]
P.S：强烈建议放在公共平台上的自用的小伙伴使用 `dev` 分支的密码权限功能，并把 `index.html` 文件中的 `title`名称修改以防止别人搜索到使用了你的 `key`，还有`不要不要不要不要不要`使用公共平台上的那些填写 `key` 就可以使用的网页，你并不知道他是否会记录并把你的 `key` 放在他的轮询池里面当免费工具！（虽然你可以自己在后台把 `key` 移除）

**Comment by 404gods** [comment]
期待大佬更新，因为用的docker，等待新镜像

**Comment by helperAI** [comment]
感谢热爱分享的 @Chanzhaoyu  ，界面体验一直认为是最好的，没有之一。
另外希望 @gouguoyin 能够带头把登录认证功能扩展为新的分支大家继续迭代下去。

**Comment by GH6324** [comment]
再次感谢大佬的无私奉献（收下我的膝盖

**Comment by i-iooi-i** [comment]
谢谢人帅心善的大佬，作为个人自用来说，它已经很棒了！

**Comment by xiaosaaaa** [comment]
感谢

**Comment by jianqiao0313** [comment]
感谢大佬~

**Comment by Cp0204** [comment]
感谢大佬~ 这个UI是各项目里完成度最高的

**Comment by CodeIntegrity** [comment]
感谢大佬，爆赞

**Comment by goodwisdom** [comment]
感谢大佬无私奉献

**Comment by zzb16888** [comment]
感谢大佬无私奉献

**Comment by wanmyj** [comment]
感谢奉献

**Comment by WinterChenS** [comment]
谢谢大佬无私贡献

**Comment by lqs2019** [comment]
大佬真的太牛逼了，通过这个开源项目跳槽到GPT内部去 哈哈

**Comment by RyanXinOne** [comment]
感谢大佬，最喜欢的ui，已经自己部署给小伙伴用了

**Comment by 2482103133** [comment]
本地部署还是有很多好处的

**Comment by 101536363** [comment]
感谢无私的奉献

**Comment by paolutan** [comment]
感谢大佬

**Comment by Simon-Yi** [comment]
感谢大神无私奉献！

**Comment by Xmaspro** [comment]
感谢，已经部署，这个方案相比其他是比较完美的。

**Comment by wqzvic88** [comment]
不是程序员，只是电子产品的爱好者，发现楼主的docker太开心了，对于我们这种技术小白来说docker最方便最好用，很方便就直接在自己家里的nas上搭建起来，把自己的api key一填就能用，而且还能填AUTH_SECRET_KEY，这样也放心开放到公网。

**Comment by houchaowei** [comment]
期待大佬更新镜像

**Comment by Chanzhaoyu** [comment]
> 期待大佬更新镜像

发布版本自动更新的

**Comment by houchaowei** [comment]
刚看到是最新的了   顺便请教个问题，回答的拉流走的这个content-type:application/octet-stream吗

**Comment by daiaji** [comment]
官方的webUI有时候会吃掉一些对话，挺烦的。

**Comment by stulzq** [comment]
感谢奉献

**Comment by hezhefly** [comment]
感谢

**Comment by daiaji** [comment]
能把导入词加到系统角色里吗？
每次对话都重复的系统角色的导入词，还是有助于治疗chatgpt的健忘。

**Comment by xiaokai0203** [comment]
上下文关联是还没做嘛

**Comment by renwofei423** [comment]
> 发现楼主的docker太开心了，对于我们这种技术小白来说docker最方便最好用，很方便就直接在自己家里的nas上搭建起来，把自己的api key一填就能用，而且还能填AUTH_SECRET_KEY，这样也放心开放到公网。

> 上下文关联是还没做嘛

现在默认就是上下文关联的吧。
