### ISSUE TITLE
[suggest] 一个同步会话的方案：导出导入会话记录功能

### ISSUE THREAD

**Issue by yhm-amber** [Chanzhaoyu/chatgpt-web#340]
支持导出一整个会话成一个包含所有信息的 Json （或者别的）格式，并且支持从它导入新会话。

如果是 Json 的话，还可以批量导出导入多个会话，用 Json 的数组来把它们放到一个文件里。

好处：

- 避免帐号管理的实现。（从而避免了服务器存储聊天记录数据还有账号数据存储等等一系列特性的引入。）
- 导出的 Json 作为文本可以放到 Git 存储库里分享，且在这个基础上可以实现自由选择同步中间件的同步方案。
- 也可以增加加密分享的选项，每个对话框内容用用户指定或自动生成的密码加密后写入 Json 相应位置。

坏处：

- 分享起来有点繁琐，而且比起类似于「只分享一个 cookie 和一个链接就能完成同步」的这种方案要多用一些流量，且消耗量会与会话的长度成正比。

所以，上述方案可以作为可以参考的同步方案之一（如果有加同步功能的计划的话）。

灵感：来自于对「如果把整个会话导出成 MD 都需要保存哪些方面的信息呢」的思考。

**Comment by Chanzhaoyu** [comment]
`2.10.1` 添加了导出数据和导出为图片功能

**Comment by yhm-amber** [comment]
> `2.10.1` 添加了导出数据和导出为图片功能

一些补充……

-----

我刚刚想到，可以有这样几种导出/导入的形式：

- 导出到某个网盘文件，新的覆盖旧的。导出/导入动作，需要用户输入网盘地址、用户验证信息、目标文件路径。
- 导出到 GitHub 之类的 Git 托管，导出就是更改文件内容为最新的。导出/导入动作，需要用户提供仓库地址、验证信息（如果需要）、目标文件路径。
- 导出到本地或从本地导入。

这样一来，聊天数据应该就只需要用户本地有缓存就可以了，相当于用户可以自行选择用什么数据存储服务，并且同步的方便性也有了，**而且还可以跨实例同步**！（就是比如，我用 docker 自己部署了一个公网不可访问的在电脑上用、手机上又在用别人部署的实例，而我只需要配置好数据同步，就可以在不同的部署实例上使用同一个会话记录或者同一些会话记录们了。）

-----

另外是导出数据格式的补充：

导出数据的格式可以参考 Matrix 的标准。它就是 Json 的并且也是支持 markdown 的。那么会话就是一个结构体，里面有一个属性是数组，数组内容就是一段段话的 Json 内容……

如此的好处是方便日后和 Matrix 梦幻联动（如果可能的话比如群里的机器人之类的）……但如果没这个打算也就没必要啦。
