### ISSUE TITLE
API 地址被墙了，可以在程序里面加一个 代理服务器 的选项吗

### ISSUE THREAD

**Issue by cary-sas** [Chanzhaoyu/chatgpt-web#341]
API 地址被墙了，https://github.com/transitive-bullshit/chatgpt-api/issues/419

由于服务端在国内， 能否在 .env 里面加上一个 proxy 的参数啊。 另外，可否支持自定义的 API 域名 （cloudflare 里面设置的 worker）啊

**Comment by ottocsb** [comment]
OPENAI_API_BASE_URL 不是有这个环境变量吗

**Comment by BruceHan98** [comment]
SOCKS_PROXY_HOST 填写服务器ip试试，SOCKS_PROXY_PORT 为socks代理端口

**Comment by luuziiyoo** [comment]
> fetch fail，

我同一个内网，上游路由器已经翻了过去， 电脑访问api啥问题没有，群晖里的chatgpt-web就不行 死活得再内网里弄个代理 相当于脱了裤子放屁的节奏

**Comment by luuziiyoo** [comment]
> 

代理服务器得能访问api那样才能访问，127.0.0.1不就是本机吗？要是本机能翻过去那还本机代理本机有啥意义

**Comment by gygy** [comment]
> > fetch fail，
> 
> 我同一个内网，上游路由器已经翻了过去， 电脑访问api啥问题没有，群晖里的chatgpt-web就不行 死活得再内网里弄个代理 相当于脱了裤子放屁的节奏
应是路由器fq设置问题。我一直这样用。没发现什么问题，一直正常。

**Comment by luuziiyoo** [comment]
> 



> > > fetch fail，
> > 
> > 
> > 我同一个内网，上游路由器已经翻了过去， 电脑访问api啥问题没有，群晖里的chatgpt-web就不行 死活得再内网里弄个代理 相当于脱了裤子放屁的节奏
> > 应是路由器fq设置问题。我一直这样用。没发现什么问题，一直正常。

重新拉取了2.9.3可以用了 不用再挂代理了 但是今早都403了 哈哈

**Comment by kof8855** [comment]
同样是今天403，重新拉了2.9.3版本又正常了

**Comment by x-dr** [comment]
最新的支持的
<img width="579" alt="20230308000018" src="https://user-images.githubusercontent.com/79109673/223477569-79ff0b6a-2ec1-45a2-bf35-9a321970796c.png">

可以用cf_worker反代apenai api 替换掉https://api.openai.com/

[自建教程](https://github.com/x-dr/chatgptProxyAPI/blob/main/README.md)

**Comment by GrayXu** [comment]
> 我尝试了 SOCKS_PROXY_HOST=127.0.0.1 SOCKS_PROXY_PORT=10808 ， 但是 没有用，依然 fetch fail， 至于OPENAI_API_BASE_URL ， 我再来试试，

你这issue的直接问题是docker如何访问宿主机网络，两者不是直接共享的。设置为host之类的都可以解决这个问题。
