### ISSUE TITLE
搞了个代理，但是网页端报错

### ISSUE THREAD

**Issue by devyujie** [Chanzhaoyu/chatgpt-web#342]
如题，使用的这个[项目](https://github.com/Ice-Hazymoon/openai-scf-proxy/issues/1)

![image](https://user-images.githubusercontent.com/48620527/223075453-fea55c12-3ba9-4d9f-8b54-a6add261b30d.png)

**Comment by qimo2020** [comment]
看来网页端获取的方式还不完善？
