### ISSUE TITLE
markdown 会闪烁

### ISSUE THREAD

**Issue by quzard** [Chanzhaoyu/chatgpt-web#344]
![](https://s21.aconvert.com/convert/p3r68-cdx67/9emkl-g4kwa.gif)

**Comment by quzard** [comment]
https://s21.aconvert.com/convert/p3r68-cdx67/9emkl-g4kwa.gif

**Comment by quzard** [comment]
官方的web不会这样

**Comment by JeamUmika** [comment]
链接挂了

**Comment by quzard** [comment]
> 链接挂了

链接没挂，Imgur的图床需要挂代理才能打开

**Comment by Chanzhaoyu** [comment]
稍等，发布之后就不会了

**Comment by qimo2020** [comment]
api回复时，markdown解析 确实会不协调，这里肯定要优化的

**Comment by qimo2020** [comment]
> 稍等，发布之后就不会了

很积极哦

**Comment by Chanzhaoyu** [comment]
再试一下，兄弟们

**Comment by quzard** [comment]
> 再试一下，兄弟们

还是差不多样子

**Comment by Chanzhaoyu** [comment]
你问的什么问题，我试试

**Comment by quzard** [comment]
> > 你问的什么问题，我试试
> 
> 你看下前端版本号是最新的 `2.9.3` 吗，问的什么问题，我看下

给以下代码添加详细中文注释，输出格式要统一，要代码高亮


version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 3000:3002
    environment:
      # 二选一
      OPENAI_API_KEY: xxxxxx
      # 二选一
      OPENAI_ACCESS_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.123123123.YDWOzmmAVoxZg8hhipzRcyzXVLqvyOu3ZtGkl8czd8idISOskElkaZ7qhd6UxiENfqzRb1VyueaOg7LHgqSG1JZvAEAgu6HvaoCiv0_6pSNESvt-pCpdx96LppJVj8NiXVzLfC-bx3CFpvl5TIVgp-L-f_yjkxoWsEwUS1t179PiO4s6VpXfXvXBkMG-jlJdFokyHXaBZHV4HkJqEbZqZO13LE2m_IJjkaro-dztN4jjMFH5ezTEv-RhjkRcNi18RRO83XJZ4Pf6yyIViQRS4EixzcrDKD_1XgBJCex569JLb6cm_wH7og8v9HJkNfbnltZwHG5VGueKJF0vZ2IX-w
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: xxxx
      # 反向代理，可选
      API_REVERSE_PROXY: xxx
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 30000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: http://10.0.4.4
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: 7890
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-chatgpt-web
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_CLEANUP=true     # 更新后移除旧的镜像
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

**Comment by Chanzhaoyu** [comment]
> > > 你问的什么问题，我试试
> > 
> > 
> > 你看下前端版本号是最新的 `2.9.3` 吗，问的什么问题，我看下
> 
> 给以下代码添加详细中文注释，输出格式要统一，要代码高亮
> 
> version: '3'
> 
> services: app: image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可 ports: - 3000:3002 environment: # 二选一 OPENAI_API_KEY: xxxxxx # 二选一 OPENAI_ACCESS_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.123123123.YDWOzmmAVoxZg8hhipzRcyzXVLqvyOu3ZtGkl8czd8idISOskElkaZ7qhd6UxiENfqzRb1VyueaOg7LHgqSG1JZvAEAgu6HvaoCiv0_6pSNESvt-pCpdx96LppJVj8NiXVzLfC-bx3CFpvl5TIVgp-L-f_yjkxoWsEwUS1t179PiO4s6VpXfXvXBkMG-jlJdFokyHXaBZHV4HkJqEbZqZO13LE2m_IJjkaro-dztN4jjMFH5ezTEv-RhjkRcNi18RRO83XJZ4Pf6yyIViQRS4EixzcrDKD_1XgBJCex569JLb6cm_wH7og8v9HJkNfbnltZwHG5VGueKJF0vZ2IX-w # API接口地址，可选，设置 OPENAI_API_KEY 时可用 OPENAI_API_BASE_URL: xxxx # 反向代理，可选 API_REVERSE_PROXY: xxx # 超时，单位毫秒，可选 TIMEOUT_MS: 30000 # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效 SOCKS_PROXY_HOST: http://10.0.4.4 # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效 SOCKS_PROXY_PORT: 7890 watchtower: image: containrrr/watchtower container_name: watchtower-chatgpt-web environment: - TZ=Asia/Shanghai - WATCHTOWER_CLEANUP=true # 更新后移除旧的镜像 volumes: - /var/run/docker.sock:/var/run/docker.sock restart: always

实测不会，是不是用的 `docker`，刚刚镜像还在发布

**Comment by quzard** [comment]
> > > > 你问的什么问题，我试试
> > > 
> > > 
> > > 你看下前端版本号是最新的 `2.9.3` 吗，问的什么问题，我看下
> > 
> > 
> > 给以下代码添加详细中文注释，输出格式要统一，要代码高亮
> > version: '3'
> > services: app: image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可 ports: - 3000:3002 environment: # 二选一 OPENAI_API_KEY: xxxxxx # 二选一 OPENAI_ACCESS_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.123123123.YDWOzmmAVoxZg8hhipzRcyzXVLqvyOu3ZtGkl8czd8idISOskElkaZ7qhd6UxiENfqzRb1VyueaOg7LHgqSG1JZvAEAgu6HvaoCiv0_6pSNESvt-pCpdx96LppJVj8NiXVzLfC-bx3CFpvl5TIVgp-L-f_yjkxoWsEwUS1t179PiO4s6VpXfXvXBkMG-jlJdFokyHXaBZHV4HkJqEbZqZO13LE2m_IJjkaro-dztN4jjMFH5ezTEv-RhjkRcNi18RRO83XJZ4Pf6yyIViQRS4EixzcrDKD_1XgBJCex569JLb6cm_wH7og8v9HJkNfbnltZwHG5VGueKJF0vZ2IX-w # API接口地址，可选，设置 OPENAI_API_KEY 时可用 OPENAI_API_BASE_URL: xxxx # 反向代理，可选 API_REVERSE_PROXY: xxx # 超时，单位毫秒，可选 TIMEOUT_MS: 30000 # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效 SOCKS_PROXY_HOST: http://10.0.4.4 # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效 SOCKS_PROXY_PORT: 7890 watchtower: image: containrrr/watchtower container_name: watchtower-chatgpt-web environment: - TZ=Asia/Shanghai - WATCHTOWER_CLEANUP=true # 更新后移除旧的镜像 volumes: - /var/run/docker.sock:/var/run/docker.sock restart: always
> 
> 实测不会，是不是用的 `docker`，刚刚镜像还在发布

本地试了下不会了，可能我的GitHub action编译的docker有问题，我再试试，谢谢
