### ISSUE TITLE
chatgpt在回答的时候，页面不可向上滑动

### ISSUE THREAD

**Issue by leesq01** [Chanzhaoyu/chatgpt-web#349]
windows 11 chrome 均是最新版
版本 2.9.3
手动部署
chatgpt在回答的时候，页面不可向上滑动

**Comment by acongee** [comment]
同样有这个问题，打字机模式不断输出的时候就这样

**Comment by Chanzhaoyu** [comment]
那我把它改成不要进行自动底部吧

**Comment by Chanzhaoyu** [comment]
`2.10.0` 已改

**Comment by zzzqu** [comment]
可是我觉得改了之后不好用啊，不会自动跟随翻页了，只在生成完自动翻页，不丝滑了

**Comment by Chanzhaoyu** [comment]
> 

em....🤯

**Comment by Chanzhaoyu** [comment]
> 可是我觉得改了之后不好用啊，不会自动跟随翻页了，只在生成完自动翻页，不丝滑了

em....🤯

**Comment by zzzqu** [comment]
大部分人都是盯着ai一个字一个字出来的，不跟随确实不好用我觉得。
要不就给个选项嘛= =

**Comment by Chanzhaoyu** [comment]
> 大部分人都是盯着ai一个字一个字出来的，不跟随确实不好用我觉得。 要不就给个选项嘛= =

主分支改回来了，我的问题
