### ISSUE TITLE
使用 ChatGPTUnofficialProxyAPI 方式搭建的响应速度太鸡儿慢了

### ISSUE THREAD

**Issue by gimgoo** [Chanzhaoyu/chatgpt-web#352]
如题，本人使用日本的服务器部署，本地环境也是路由器科学上网，但是那响应速度真的不敢恭维。官网即使慢都没有这么慢。

如果可以的话，希望大佬优化一下 ChatGPTUnofficialProxyAPI 这块的响应，不然速度跟官网比起来差很远，跟API Key比起来差更远。

**Comment by tourusa** [comment]
使用railway部署的，国内访问没有问题，响应很快

**Comment by luuziiyoo** [comment]
我昨天访问也是满的一批

**Comment by Chanzhaoyu** [comment]
你们换一下社区的代理服务器试试，我自己部署的本地也出问题，不过用 railway 的正常。

**Comment by diudiudiuu** [comment]
为什么我的很快

**Comment by Apple-ljj** [comment]
如何部署ChatGPTUnofficialProxyAPI ，有教程吗？
