### ISSUE TITLE
(网页 accessToken)模式403

### ISSUE THREAD

**Issue by qlql765** [Chanzhaoyu/chatgpt-web#353]
今天早上(网页 accessToken)模式403
![QQ截图20230307084730](https://user-images.githubusercontent.com/108382776/223290159-483d0bde-b02d-4326-91e4-b4f0b9d79692.png)

**Comment by luuziiyoo** [comment]
都这样了

**Comment by zhanghengtian** [comment]
米兔

**Comment by terrywangt** [comment]
我也这样了

**Comment by dgutyanghs** [comment]
Same issue.

**Comment by tristone13th** [comment]
我的也这样了，不知道 key 模式还正常不

**Comment by jiajiangtao122** [comment]
早上起来也是403了 挂反代也是403  现在换成key没事了

**Comment by ilongli** [comment]
same，用apikey正常

**Comment by qlql765** [comment]
是不是非官方代理服务器的问题，所以才这样

**Comment by KeepeeLee** [comment]
我也是403

**Comment by luuziiyoo** [comment]
![屏幕截图 2023-03-07 105748](https://user-images.githubusercontent.com/10737650/223308863-fb4de14e-7b7d-4d3c-81bd-06c0a1fdb0eb.png)
拒绝访问了

**Comment by hnuzhoulin** [comment]
https://github.com/acheong08/ChatGPT/issues/1064#issuecomment-1457410323
看起来是上游修复了？

**Comment by cjw-666** [comment]
一样的问题，看看有没有解决方案

**Comment by terrywangt** [comment]
我刚刚添加代理参数就好了， API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation
这里有说明：https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
比如docker启动
docker run --name chatgpt-web -d -p 3002:3002  --env API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation --env OPENAI_ACCESS_TOKEN=xxx chatgpt-web

**Comment by cjw-666** [comment]
> 我刚刚添加代理参数就好了， API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation 这里有说明：https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy 比如docker启动 docker run --name chatgpt-web -d -p 3002:3002 --env API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation --env OPENAI_ACCESS_TOKEN=xxx chatgpt-web

你是用的国内服务器吗？

**Comment by terrywangt** [comment]
> > 我刚刚添加代理参数就好了， API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation 这里有说明：https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy 比如docker启动 docker run --name chatgpt-web -d -p 3002:3002 --env API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation --env OPENAI_ACCESS_TOKEN=xxx chatgpt-web
> 
> 你是用的国内服务器吗？

不是，是国外的服务器。

**Comment by luuziiyoo** [comment]
> 



> > > 我刚刚添加代理参数就好了， API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation 这里有说明：https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy 比如docker启动 docker run --name chatgpt-web -d -p 3002:3002 --env API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation --env OPENAI_ACCESS_TOKEN=xxx chatgpt-web
> > 
> > 
> > 你是用的国内服务器吗？
> 
> 不是，是国外的服务器。

路由器爬梯子的话直接把这个gpt.pawan.krd扔到域名黑名单就可以了

**Comment by qlql765** [comment]
到目前是已经恢复了

**Comment by cjw-666** [comment]
应该是自动恢复了

**Comment by gygy** [comment]
> > 
> 
> 
> 
> > > > 我刚刚添加代理参数就好了， API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation 这里有说明：https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy 比如docker启动 docker run --name chatgpt-web -d -p 3002:3002 --env API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation --env OPENAI_ACCESS_TOKEN=xxx chatgpt-web
> > > 
> > > 
> > > 你是用的国内服务器吗？
> > 
> > 不是，是国外的服务器。
> 
> 路由器爬梯子的话直接把这个gpt.pawan.krd扔到域名黑名单就可以了

这个是什么原理呢？
