### ISSUE TITLE
出现了以下错误“This model's maximum context length is 4096 tokens”，如何处理？

### ISSUE THREAD

**Issue by slieer** [Chanzhaoyu/chatgpt-web#354]
ChatGPT error 400: {

  "error": {
    "message": "This model's maximum context length is 4096 tokens. However, you requested 4130 tokens (3130 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

**Comment by acongee** [comment]
字太多了分段吧，或者新开个chat但是会不记得上文

**Comment by shiqianwei0508** [comment]
我也碰到了一样的问题，只有重启服务才能解决。刷新页面没用，并且只要报错，后面就会一直报错。

**Comment by ndcc5** [comment]
新开一个对话。
