### ISSUE TITLE
网页版gg了，希望同学们修复下，谢谢

### ISSUE THREAD

**Issue by qimo2020** [Chanzhaoyu/chatgpt-web#356]

**Comment by VectorZhao** [comment]
早上大概9点不到，网页版就出问题了

```
ChatGPT error 403: 

<!DOCTYPE html>

<html lang="en-US">
   <head>
      <title>Access denied</title>
      <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
      <meta name="robots" content="noindex, nofollow" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <link rel="stylesheet" href="/cdn-cgi/styles/errors.css" media="screen" />
      <script>
(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1020,helpful:a,version:5}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
</script>
```

**Comment by lion-goose** [comment]
我也是的，一样的问题

**Comment by 7noemo** [comment]
+1

**Comment by hnuzhoulin** [comment]
https://github.com/acheong08/ChatGPT/issues/1064#issuecomment-1457410323

是不是意味着上游修复问题了？

**Comment by xyqkent** [comment]
API_REVERSE_PROXY，调整这个env，说明文档里面写了的，更换ChatGPTUnofficialProxyAPI的地址即可使用

**Comment by Rannnm** [comment]
@xyqkent 这个地址更换成什么呢

**Comment by 7noemo** [comment]
> 

docker版如何修改

**Comment by luuziiyoo** [comment]
我刚刚添加代理参数就好了， API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation
看最后一行
![屏幕截图 2023-03-07 133945](https://user-images.githubusercontent.com/10737650/223330511-79c1fd93-dc28-4e95-a27a-e9dea683d819.png)

**Comment by 7noemo** [comment]
> 

SSH链接的呢？

**Comment by luuziiyoo** [comment]
没有别的需要修改的地方了啊

**Comment by 7noemo** [comment]
> 没有别的需要修改的地方了啊

比如之前建docker容器的代码是这样的：
`docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_ACCESS_TOKEN=your_api_key chenzhaoyu94/chatgpt-web`
那现在加一行`API_REVERSE_PROXY=`的话 在SSH终端代码中应该添加在何处？ (vps上使用无docker管理ui)

**Comment by Rannnm** [comment]
> 

但是用token的还是不行

**Comment by luuziiyoo** [comment]
> 
可以啊 token 和api我都试过了  你看上面的图apikey我注释掉了 一样可以用的

**Comment by 7noemo** [comment]
使用下列代码创建容器可添加 `API_REVERSE_PROXY=` 属性
 `docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_ACCESS_TOKEN=your_api_key --env https://gpt.pawan.krd/backend-api/conversation chenzhaoyu94/chatgpt-web`
另外这里的`https://gpt.pawan.krd` 是不可替换的？

**Comment by luuziiyoo** [comment]
> 使用下列代码创建容器可添加 `API_REVERSE_PROXY=` 属性 `docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_ACCESS_TOKEN=your_api_key --env API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation chenzhaoyu94/chatgpt-web` 另外这里的`https://gpt.pawan.krd` 是不可替换的？

对啊 这不是你的代理服务器地址不需要修改 你要改的是你的token和apikey
