### ISSUE TITLE
[Feature Request] 支持搜索历史记录

### ISSUE THREAD

**Issue by Quorafind** [Chanzhaoyu/chatgpt-web#357]
# 原因

需要在很多的聊天记录中搜索结果

**Comment by Chanzhaoyu** [comment]
可是现在 API 有上下文限制，确定要吗

**Comment by Quorafind** [comment]
抱歉让您这边误会了我的意思，我的意思是在前端提供一个搜索窗口来搜索当前我们已经聊天的内容，从而能够定位到对应的聊天窗

**Comment by Quorafind** [comment]
> 抱歉让您这边误会了我的意思，我的意思是在前端提供一个搜索窗口来搜索当前我们已经聊天的内容，从而能够定位到对应的聊天窗

或者应该说是缓存中搜索，然后定位到对应的 id，进而跳转，而不是用 API 来重新获取一次
