### ISSUE TITLE
返回的链接有个小bug

### ISSUE THREAD

**Issue by melivn** [Chanzhaoyu/chatgpt-web#358]
![image](https://user-images.githubusercontent.com/52886192/223318302-20d5d40f-e4a9-44e6-b510-4c0e62882cd5.png)
链接后面跟的符号会挂到链接去。导致跳转404

**Comment by melivn** [comment]
另外，我觉得链接用“_blank”开新窗口打开会更合适。

**Comment by Chanzhaoyu** [comment]
已修改为新窗口打开，渲染的问题还要处理下规则
