### ISSUE TITLE
关于服务器聊天记录缓存

### ISSUE THREAD

**Issue by gefeiyanga** [Chanzhaoyu/chatgpt-web#36]
#### 上下文
我看这个项目的服务端也是用的https://github.com/transitive-bullshit/chatgpt-api 这个库，他的代码里聊天记录会缓存最大数量10000条的记录，所谓的“上下文”是把上一句话拼到新的请求里，大概是这个逻辑。
极端情况下，假设10000条数据存满了，现在第10001条push进来了，那第负一条数据就shift了，接下来这条数据想上下文关联就关联不起来了。

#### 针对这个问题想到的办法是：
- 服务器直接不缓存了，前端维护某个时间段的聊天记录，前端自己拼好了上文，连着新消息发过去，conversationId和parentMessageId都不传了。但这样页面刷新就历史记录消失了...
- 还有就是所有数据入库，那都好说...

**想听听大家的意见**

**Comment by Chanzhaoyu** [comment]
hello～
你现在用的版本好是多少呢？最新的 `2.3.1` 已经改成了前端发送上下文 `ID`，并且会记录下每个会话到本地，这样刷新页面聊天记录也会存在。

**Comment by gefeiyanga** [comment]
> hello～ 你现在用的版本号是多少呢？最新的 `2.3.0` 已经改成了前端发送上下文 `ID`，并且会记录下每个会话到本地，这样刷新页面聊天记录也会存在。

我没有跑起来你的项目，只是想探讨一下10000数据这个问题，想听听你的看法

**Comment by Chanzhaoyu** [comment]
暂时还没考虑上限的问题，但是前端不传` id` 而是拼接上下文，如果数据条数超过 `10` 条的话，好像不太合理。

**Comment by gefeiyanga** [comment]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/30728843/219262528-8e365405-251e-4af2-9d03-ece2f352e239.png">
确实不合适
