### ISSUE TITLE
用docker出现错误403的筒子们看过来

### ISSUE THREAD

**Issue by luuziiyoo** [Chanzhaoyu/chatgpt-web#360]
先停止docker运行 添加最后一行的的 API_REVERSE_PROXY         https://gpt.pawan.krd/backend-api/conversation
就可以运行了，速度感觉别以前还快了，我的docker用的是桥接模式，host模式下还是不行
docker运行就填写如下的变量就能运行了  
至于你用token还是apikey不用的注释掉就行了以免到时候不能用临时启用

![屏幕截图 2023-03-07 133945](https://user-images.githubusercontent.com/10737650/223332246-09dfd5ac-5ad6-46de-90b6-21d8b4010ff2.png)

**Comment by KIOldd** [comment]
成功 谢谢楼主

**Comment by WinterChenS** [comment]
我也是安装在群辉里面的，哈哈哈哈

**Comment by luuziiyoo** [comment]
> 我也是安装在群晖里的，哈哈

群辉我觉得挺好用的，我部署了好多东西
