### ISSUE TITLE
manifest for docker.io/chenzhaoyu94/chatgpt-web:latest not found

### ISSUE THREAD

**Issue by mqk98** [Chanzhaoyu/chatgpt-web#371]
when I pull the image，it can't work.

**Comment by zbysir** [comment]
docker pull  chenzhaoyu94/chatgpt-web:main

> when I pull the image，it can't work.

**Comment by zbysir** [comment]
It worked for me, perhaps you can check the 'registry-mirrors' configuration in /etc/docker/daemon.json and clear it.

```
root@i:~# docker pull  chenzhaoyu94/chatgpt-web:main
main: Pulling from chenzhaoyu94/chatgpt-web
63b65145d645: Already exists
061765f30124: Already exists
478140d59116: Already exists
00ca3aba45c3: Already exists
6ecb41867060: Pull complete
7d707d136d31: Pull complete
4f4fb700ef54: Pull complete
bd78fff9ff97: Pull complete
Digest: sha256:5198cc80113ec916a76160ca62861d491043899a6129495b64db9b9d51b0fc44
Status: Downloaded newer image for chenzhaoyu94/chatgpt-web:main
docker.io/chenzhaoyu94/chatgpt-web:main
```

> > docker pull chenzhaoyu94/chatgpt-web:main
> > >
> 
> manifest for docker.io/chenzhaoyu94/chatgpt-web:main not found

**Comment by hnuzhoulin** [comment]
your network is not allowed to access docker hub,using a proxy

**Comment by mqk98** [comment]
> your network is not allowed to access docker hub,using a proxy

I confirm that I'm using a proxy, but it still can't work.

**Comment by mqk98** [comment]
I installed docker but not docker-compose, is this the cause of the error？

**Comment by Tianchen627** [comment]
> docker pull  chenzhaoyu94/chatgpt-web:main

same thing happened on me.Have u solved the problem?
