### ISSUE TITLE
【小白求助】代理服务器超时问题

### ISSUE THREAD

**Issue by jerryzhang721** [Chanzhaoyu/chatgpt-web#373]
我在Google cloud的vps上部署了tinyproxy，在外网环境测试可以正常工作。但使用本应用的SOCKS_PROXY_HOST 和 SOCKS_PROXY_PORT配置后仍然无法使用，提示Proxy connection timed out，求大佬指点。

**Comment by gaoobin** [comment]
那是别人免费贡献出来给大家用的，大家都在免费用，流量太大估计人家停止代理了。
别人贡献的那两个都不好用了，建议你自己买一个海外api proxy服务或者vps吧

**Comment by jerryzhang721** [comment]
> 那是别人免费贡献出来给大家用的，大家都在免费用，流量太大估计人家停止代理了。
> 别人贡献的那两个都不好用了，建议你自己买一个海外api proxy服务或者vps吧

哥，我是用我买的 Google cloud 的 vps，自己部署的 tinyproxy，但还是提示代理服务器超时
