### ISSUE TITLE
如何在Debian系统下一键安装？

### ISSUE THREAD

**Issue by Simon-Yi** [Chanzhaoyu/chatgpt-web#376]
我是一个小白，请问大神，有没有一键安装的命令？

**Comment by Simon-Yi** [comment]
> 那就只有用 docker-compose 方式了

请问下具体操作命令应该如何操作？可以指点下吗？

**Comment by zhuxindong** [comment]
1.先安装docker
```shell
curl -fsSL https://get.docker.com/ -o get-docker.sh
sudo sh get-docker.sh
```

2.docker 一键运行
```shell
# -p 80:3002的意思是你debian系统对外提供服务的端口是80，你可以替换成任何你想要的
docker run --name chatgpt-web -idt --restart always -p 80:3002 --env OPENAI_API_KEY=替换成你的api_key chenzhaoyu94/chatgpt-web
```

**Comment by Simon-Yi** [comment]
> 1.先安装docker
> 
> ```shell
> curl -fsSL https://get.docker.com/ -o get-docker.sh
> sudo sh get-docker.sh
> ```
> 
> 2.docker 一键运行
> 
> ```shell
> # -p 80:3002的意思是你debian系统对外提供服务的端口是80，你可以替换成任何你想要的
> docker run --name chatgpt-web -idt --restart always -p 80:3002 --env OPENAI_API_KEY=替换成你的api_key chenzhaoyu94/chatgpt-web
> ```

好的，非常感谢大佬
