### ISSUE TITLE
重写后端，后端返回的前端的数据参数是怎样的？

### ISSUE THREAD

**Issue by anranq** [Chanzhaoyu/chatgpt-web#377]
![image](https://user-images.githubusercontent.com/126095767/223436456-ecbb0cbf-c22e-4f9b-99f8-97005be26430.png)
上图是原后端F12看到的数据
![image](https://user-images.githubusercontent.com/126095767/223436695-14aacefd-1f78-45d9-b53f-e6d4faf70ee5.png)
这是我写的后端返回数据参数，json和String类型都不行
![Uploading image.png…]()
这是报错的图，为什么F12看到的不是我图二返回的数据？

**Comment by anranq** [comment]
图片顺序出错，有人重写了后端的吗或者知道什么情况的？求指教一下

**Comment by helperAI** [comment]
你是准备改为直接调用openai.com的官方API而不是chatgpt-api这个包，对吗？
确实应该重写了。因为那个包：1）有冗余参数。2）未来更新麻烦。3）好像也不太好动态设置temperature等参数。4）重写后也方便未来整合DALLE模型。

**Comment by anranq** [comment]
> 你准备修改为直接调用openai.com的官方API而不是chatgpt-api这个包，对吗？ 确实应该重写了。因为那个包：1）有余参数。2）未来雁。也不太好设置温度等参数。4）重写后也方便未来整合DALLE模型。

是的，但是我还没弄好，你搭建了吗

**Comment by helperAI** [comment]
> > 你准备修改为直接调用openai.com的官方API而不是chatgpt-api这个包，对吗？ 确实应该重写了。因为那个包：1）有余参数。2）未来雁。也不太好设置温度等参数。4）重写后也方便未来整合DALLE模型。
> 
> 是的，但是我还没弄好，你搭建了吗

其实应该大家一起来改进。这是最通用的功能。我搞不来。我是后端开发为主。
