### ISSUE TITLE
上下文聊天太贵了，如果能加上一个开关就好了

### ISSUE THREAD

**Issue by somego** [Chanzhaoyu/chatgpt-web#378]
大部分时候可能需要上下文，这样能获得更好的回答。
但是有时候也不需要上下文，这样不需要上下文的如果想省钱，只能每发送一条就new一个新聊天窗口，要不然就会把之前生成的回答也发送了，相当费钱。如果在聊天窗口上有个选项，是否开启上下文，这样不需要上下文聊天时候就关闭这个选项，可以省不少钱😄

或者还有复杂一些的，能自己选择把之前的哪些回答作为上下文发送

**Comment by Byz-liu** [comment]
对，以为很便宜，其实一个请求就占了2K-3K个token。

**Comment by qimo2020** [comment]
这个支持！

**Comment by assassinliujie** [comment]
之前生成的回答还会每次重新发送计费么，这玩意计费啥原理来着

**Comment by assassinliujie** [comment]
我现在每五分钟就有几万个token，不知道问题出在哪

**Comment by fierceX** [comment]
@assassinliujie 是不是有可能被盗刷了

**Comment by assassinliujie** [comment]
> @assassinliujie 是不是有可能被盗刷了

这还真不知道，docker部署的不知道该怎么查看请求日志

**Comment by Byz-liu** [comment]
应该不是被刷了，几万个token也就几十次请求，应该就是用的人多了一点，更新一下加个访问密码，应该会好一点。

**Comment by Arvintian** [comment]
重写了一下服务端api，做了一个chat会话保持时间机制，和预留tokens数截断上下文的机制，参考[https://github.com/Arvintian/chatgpt-web](https://github.com/Arvintian/chatgpt-web)
