### ISSUE TITLE
建议测试一下text-davinci-002效果如何

### ISSUE THREAD

**Issue by wrhsd1** [Chanzhaoyu/chatgpt-web#38]
试了下text-davinci-002-render-sha，用的https://github.com/acheong08/ChatGPT
revChatGPT.V1版本，貌似比api的版本回复更好一点
感谢大佬付出

**Comment by Chanzhaoyu** [comment]
这个是抓取的 `web` 接口吧

**Comment by Siri-Li** [comment]
这个是抓取的web token,不过这个一直可用，还是可以考虑

**Comment by wrhsd1** [comment]
> 这个是抓取的 `web` 接口吧

对，这是用代理抓取的网页版的token

**Comment by lhlxx2010** [comment]
这个模型确实聪明很多，求开发一下

**Comment by 7757** [comment]
> -

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/48285391/219608150-d6339ef7-0c07-42b0-97f5-7faef4d10b7a.png">

**Comment by Chanzhaoyu** [comment]
已添加网页的方式，不过 accessToken 一般只有 8 小时，不太稳定
