### ISSUE TITLE
Docker 运行不了提示 docker: Error response from daemon: p

### ISSUE THREAD

**Issue by skykiah** [Chanzhaoyu/chatgpt-web#380]
docker: Error response from daemon: pull access denied for chatgpt-web, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by Chanzhaoyu** [comment]
去 dockerhub 里面拉标签过最新的

**Comment by foolzhang** [comment]
docker pull chenzhaoyu94/chatgpt-web:v2.10.0
Error response from daemon: manifest for chenzhaoyu94/chatgpt-web:v2.10.0 not found

**Comment by Chanzhaoyu** [comment]
> docker pull chenzhaoyu94/chatgpt-web:v2.10.0 Error response from daemon: manifest for chenzhaoyu94/chatgpt-web:v2.10.0 not found

直接拉 [latest](https://hub.docker.com/layers/chenzhaoyu94/chatgpt-web/latest/images/sha256-f713072559f013fde6f2c1291b7ed16cf675cc1fcbf2d23c7c7dfa43eaed061b?context=repo) 也是一样的

**Comment by yisizhu520** [comment]
> > docker pull chenzhaoyu94/chatgpt-web:v2.10.0 Error response from daemon: manifest for chenzhaoyu94/chatgpt-web:v2.10.0 not found
> 
> 直接拉 [latest](https://hub.docker.com/layers/chenzhaoyu94/chatgpt-web/latest/images/sha256-f713072559f013fde6f2c1291b7ed16cf675cc1fcbf2d23c7c7dfa43eaed061b?context=repo) 也是一样的

请问这个问题怎么解决的呢？我也遇到这个问题了，docker pull 拉哪个tag的都是这个报错......
