### ISSUE TITLE
截图样式需要优化

### ISSUE THREAD

**Issue by devyujie** [Chanzhaoyu/chatgpt-web#381]
保存的截图需要再优化一下
![image](https://user-images.githubusercontent.com/48620527/223471114-67611873-b604-4389-9ec4-f541886320a3.png)

**Comment by devyujie** [comment]
补充
![image](https://user-images.githubusercontent.com/48620527/223473331-0bb239b3-3965-42ac-b1c4-50fe4bb36e7d.png)

**Comment by devyujie** [comment]
猜测是因为保存图片时，浏览器底部的弹出导致此问题
![image](https://user-images.githubusercontent.com/48620527/223473785-28153465-0005-4cfb-bf6d-259b413fbd49.png)

**Comment by ottocsb** [comment]
和底部弹下载无关系，个人浏览器无下面弹下载也是会略低，且没有使用默认头像时，下载的图片头像是为灰色

**Comment by CornerSkyless** [comment]
> 和底部弹下载无关系，个人浏览器无下面弹下载也是会略低，且没有使用默认头像时，下载的图片头像是为灰色

头像的问题已经提交了 PR #392
