### ISSUE TITLE
修复railway的同步更新

### ISSUE THREAD

**Issue by beiyaohhhc** [Chanzhaoyu/chatgpt-web#382]
希望能修复railway的同步更新
每次部署厚更新总是合并不了（或许我不太会用railway）

**Comment by Chanzhaoyu** [comment]
railway 不是自动更新的吗

**Comment by hnuzhoulin** [comment]
他的意思是railway默认会将本库fork到个人空间下，大佬你这边更新之后不会自动同步到个人库。
建议简单熟悉一下git的操作，在本地手动或者自己写一个小脚本定期，也可以考虑github action(我没去试验，应该是可以的)

**Comment by Chanzhaoyu** [comment]
> 他的意思是railway默认会将本库fork到个人空间下，大佬你这边更新之后不会自动同步到个人库。 建议简单熟悉一下git的操作，在本地手动或者自己写一个小脚本定期，也可以考虑github action(我没去试验，应该是可以的)

fork 之后好像在自己仓库手动点一下 sync 就好了吧，railway 会自动监听 main 分支改动重新部署

**Comment by beiyaohhhc** [comment]
好的 已解决 谢谢
