### ISSUE TITLE
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

### ISSUE THREAD

**Issue by samulo7** [Chanzhaoyu/chatgpt-web#385]
![image](https://user-images.githubusercontent.com/64634578/223596017-687c17cc-f6b1-4d87-9912-ec31904549c3.png)
突然报错，昨天还好用。确定家里的服务器可以翻墙节点可以上chatgpt

**Comment by yuntao1997** [comment]
等一会就好了，openai服务不稳定。  我昨天也碰到了

**Comment by Chanzhaoyu** [comment]
看后端控制台具体信息

**Comment by wansenlyt** [comment]
更新到2.10.0出现这个问题，之前版本没有遇到过，来反馈一下。

**Comment by Chanzhaoyu** [comment]
> 更新到2.10.0出现这个问题，之前版本没有遇到过，来反馈一下。

这个报错其实就是以前的 `403`，可以在后端看到详细报错信息。

**Comment by samulo7** [comment]
> > 更新到2.10.0出现这个问题，之前版本没有遇到过，来反馈一下。
> 
> 这个报错其实就是以前的 `403`，可以在后端看到详细报错信息。

我是用docker-compose搭建的，请问怎么看后端报错信息

**Comment by VectorZhao** [comment]
> 看后端控制台具体信息


     ```
 <script>
      (function(){function d(c){var b=document.getElementById("copy-label"),a=document.getElementById("cf-details-wrapper-expandable");c.target.checked?a.classList.add("expanded"):(a.classList.remove("expanded"),b.innerText="Click to copy")}if(document.addEventListener){var e=function(){var c=document.getElementById("copy-label");var b=document.getElementById("error-details").textContent;if(navigator.clipboard)navigator.clipboard.writeText(b);else{var a=document.createElement("textarea");a.value=b;a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}c.innerText="Copied text to clipboard"};document.addEventListener("DOMContentLoaded",function(){var c=document.getElementById("error-details-checkbox"),b=document.getElementById("click-to-copy-btn");document.getElementById("copy-label").classList.remove("hidden");c.addEventListener("change",d);b.addEventListener("click",e)})}})();
      </script>
      <script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
   </head>

>
   <div class="cf-main-wrapper" role="main">
      <div class="cf-header cf-section">
         <div class="cf-error-title">
            <h1>Access denied</h1>
            <span class="cf-code-label">Error code <span>1020</span></span>
         </div>
         <div class="cf-error-description">
            <p>You do not have access to chat.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
         </div>

      </div>

>

   <div class="cf-details-wrapper">
      <div class="cf-section" role="region">
         <div class="cf-expandable" id="cf-details-wrapper-expandable">
            <label for="error-details-checkbox" title="Error details" class="cf-expandable-btn">
               <p class="cf-dropdown-title">Error details</p>
               <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAf2CAMKS61bwAAABTSURBVCjPzcq7DcAgFENR5zMATfo06TNCViAS+6+CeFi6gglw4eLqaPVtaQpXnkApaQT/k0dw70EAUhCA1AnABGACMAGYAEwAkCOAydv+I5xaZhXWbQrD80TkkQAAAABJRU5ErkJggg=="
               class="cf-caret-icon" id="caret-icon" alt="Caret icon" />
            </label>

            <input id="error-details-checkbox" class="hidden" type="checkbox">

            <div class="cf-expandable-error-info hidden">
               <p class="cf-error-copy-description">Provide the site owner this information.</p>
               <button class="cf-click-to-copy-btn" id="click-to-copy-btn" title="Click to copy" type="button">
<div class="cf-error-wrapper" id="error-details"><p class="cf-error-details-endpoint">I got an error when visiting chat.duti.tech/api/conversation.</p>

<p>Error code: 1020</p>
<p>Ray ID: 7a477ed828af2ed7</p>
<p>Country: SG</p>
<p>Data center: sin02</p>
<p>IP: 129.150.52.237</p>
<p>Timestamp: 2023-03-08 02:02:20 UTC</p>
</div>
                  <p class="cf-copy-label hidden" id="copy-label">Click to copy</p>
               </button>
            </div>
         </div>

      </div>

      <div class="clearfix cf-footer cf-section" role="contentinfo">
      <div class="cf-column">
           <div class="feedback-hidden py-8 text-center" id="error-feedback">
    <div id="error-feedback-survey" class="footer-line-wrapper">
        Was this page helpful?
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
    </div>
    <div class="feedback-success feedback-hidden" id="error-feedback-success">
        Thank you for your feedback!
    </div>
</div>


      </div>
         <div class="cf-column cf-footer-line-wrapper text-center">
            <p>

               Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=1020_error" target="_blank">Cloudflare <img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link"></a>
            </p>
         </div>

      </div>

>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a477ed828af2ed7","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>

    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.0.8/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  statusText: 'Forbidden',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

**Comment by VectorZhao** [comment]
> 看后端控制台具体信息


      <script>
      (function(){function d(c){var b=document.getElementById("copy-label"),a=document.getElementById("cf-details-wrapper-expandable");c.target.checked?a.classList.add("expanded"):(a.classList.remove("expanded"),b.innerText="Click to copy")}if(document.addEventListener){var e=function(){var c=document.getElementById("copy-label");var b=document.getElementById("error-details").textContent;if(navigator.clipboard)navigator.clipboard.writeText(b);else{var a=document.createElement("textarea");a.value=b;a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}c.innerText="Copied text to clipboard"};document.addEventListener("DOMContentLoaded",function(){var c=document.getElementById("error-details-checkbox"),b=document.getElementById("click-to-copy-btn");document.getElementById("copy-label").classList.remove("hidden");c.addEventListener("change",d);b.addEventListener("click",e)})}})();
      </script>
      <script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
   </head>

>
   <div class="cf-main-wrapper" role="main">
      <div class="cf-header cf-section">
         <div class="cf-error-title">
            <h1>Access denied</h1>
            <span class="cf-code-label">Error code <span>1020</span></span>
         </div>
         <div class="cf-error-description">
            <p>You do not have access to chat.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
         </div>

      </div>

>

   <div class="cf-details-wrapper">
      <div class="cf-section" role="region">
         <div class="cf-expandable" id="cf-details-wrapper-expandable">
            <label for="error-details-checkbox" title="Error details" class="cf-expandable-btn">
               <p class="cf-dropdown-title">Error details</p>
               <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAf2CAMKS61bwAAABTSURBVCjPzcq7DcAgFENR5zMATfo06TNCViAS+6+CeFi6gglw4eLqaPVtaQpXnkApaQT/k0dw70EAUhCA1AnABGACMAGYAEwAkCOAydv+I5xaZhXWbQrD80TkkQAAAABJRU5ErkJggg=="
               class="cf-caret-icon" id="caret-icon" alt="Caret icon" />
            </label>

            <input id="error-details-checkbox" class="hidden" type="checkbox">

            <div class="cf-expandable-error-info hidden">
               <p class="cf-error-copy-description">Provide the site owner this information.</p>
               <button class="cf-click-to-copy-btn" id="click-to-copy-btn" title="Click to copy" type="button">
<div class="cf-error-wrapper" id="error-details"><p class="cf-error-details-endpoint">I got an error when visiting chat.duti.tech/api/conversation.</p>

<p>Error code: 1020</p>
<p>Ray ID: 7a477ed828af2ed7</p>
<p>Country: SG</p>
<p>Data center: sin02</p>
<p>IP: 129.150.52.237</p>
<p>Timestamp: 2023-03-08 02:02:20 UTC</p>
</div>
                  <p class="cf-copy-label hidden" id="copy-label">Click to copy</p>
               </button>
            </div>
         </div>

      </div>

      <div class="clearfix cf-footer cf-section" role="contentinfo">
      <div class="cf-column">
           <div class="feedback-hidden py-8 text-center" id="error-feedback">
    <div id="error-feedback-survey" class="footer-line-wrapper">
        Was this page helpful?
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
    </div>
    <div class="feedback-success feedback-hidden" id="error-feedback-success">
        Thank you for your feedback!
    </div>
</div>


      </div>
         <div class="cf-column cf-footer-line-wrapper text-center">
            <p>

               Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=1020_error" target="_blank">Cloudflare <img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link"></a>
            </p>
         </div>

      </div>

>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a477ed828af2ed7","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>

    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.0.8/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  statusText: 'Forbidden',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by VectorZhao** [comment]
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a477773385f4bf2","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>

    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.0.8/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  statusText: 'Forbidden',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by lockeisadog** [comment]
<p>You do not have access to chat.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>

**Comment by assassinliujie** [comment]
八成国内屏蔽了

**Comment by hxhaozi** [comment]
同错误 mark一下

**Comment by ba0gu0** [comment]
### 解决办法，修改默认的api反向代理地址
* chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
* 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.

```
# 反向代理，可选
API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
```

**Comment by jiajiangtao122** [comment]
更新2.10同样也是拒绝访问

**Comment by samulo7** [comment]
> ### 解决办法，修改默认的api反向代理地址
> * chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.
> * 切换可用的代理，参考[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了??? 第二个可用。
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> 
> ```
> # 反向代理，可选
> API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> ```

谢谢你的回答，看来是默认的反代挂掉了，按照你发的备用反代地址可以正常运行了^_^

**Comment by jiajiangtao122** [comment]
> ### 解决办法，修改默认的api反向代理地址
> * chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.
> * 切换可用的代理，参考[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了??? 第二个可用。
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> 
> ```
> # 反向代理，可选
> API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> ```

怎么默认不走代理 我服务器在国外不用反代

**Comment by greatewar** [comment]
> ### 解决办法，修改默认的api反向代理地址
> * chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.
> * 切换可用的代理，参考[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了??? 第二个可用。
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> 
> ```
> # 反向代理，可选
> API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> ```

用楼主的办法解决了

**Comment by i-iooi-i** [comment]
> ### 解决办法，修改默认的api反向代理地址
> * chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.
> * 切换可用的代理，参考[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了??? 第二个可用。
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> 
> ```
> # 反向代理，可选
> API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> ```

感谢，完美复活。

**Comment by gygy** [comment]
> > ### 解决办法，修改默认的api反向代理地址
> > 
> > * chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> > * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.
> > * 切换可用的代理，参考[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了??? 第二个可用。
> > 
> > <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> > ```
> > # 反向代理，可选
> > API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> > ```
> 
> 怎么默认不走代理 我服务器在国外不用反代

同问

**Comment by saaaaadk** [comment]
> > ### 解决办法，修改默认的api反向代理地址
> > 
> > * chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> > * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.
> > * 切换可用的代理，参考[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了??? 第二个可用。
> > 
> > <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> > ```
> > # 反向代理，可选
> > API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> > ```
> 
> 感谢，完美复活。

我也遇到了一样的问题，打开原来的 proxyurl现在直接就是404，去尝试了一换一个反向代理的网址，结果出现网关超时。我能保证自己的代理是能够访问chatgpt的

**Comment by tristone13th** [comment]
> > ### 解决办法，修改默认的 api 反向代理地址
> > 
> > * chatgpt-api 库默认使用 `https://chat.duti.tech/api/conversation`反响代理，就算你的.env 没有配置，它也会默认走这个代理。（实际上 openai 只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> > * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是 403.
> > * 切换可用的代理，参考 [chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了？？？第二个可用。
> > 
> > <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> > ```
> > # 反向代理，可选
> > API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> > ```
> 
> 怎么默认不走代理 我服务器在国外不用反代

同问，部署在 railway 上，需要反代吗？

**Comment by tristone13th** [comment]
> 国外越来越多的服务商被禁中，railway 之前不需要反代能用，现在不行了，部分 vps 厂商 也不行了。。。。

不走 token，走 API 也不行嘛

**Comment by Chanzhaoyu** [comment]
> > > ### 解决办法，修改默认的 api 反向代理地址
> > > 
> > > * chatgpt-api 库默认使用 `https://chat.duti.tech/api/conversation`反响代理，就算你的.env 没有配置，它也会默认走这个代理。（实际上 openai 只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> > > * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是 403.
> > > * 切换可用的代理，参考 [chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了？？？第二个可用。
> > > 
> > > <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> > > ```
> > > # 反向代理，可选
> > > API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> > > ```
> > 
> > 
> > 怎么默认不走代理 我服务器在国外不用反代
> 
> 同问，部署在 railway 上，需要反代吗？

能保证的是之前不管是 token 还是 key 都不用，现在不清楚

**Comment by hnuzhoulin** [comment]
> > 国外越来越多的服务商被禁中，railway 之前不需要反代能用，现在不行了，部分 vps 厂商 也不行了。。。。
> 
> 不走 token，走 API 也不行嘛

API用国外的服务器还是可以的。

**Comment by assassinliujie** [comment]
> 国外越来越多的服务商被禁中，railway之前不需要反代能用，现在不行了，部分vps厂商 也不行了。。。。

AWS 、azure和oracle目前还能用，我挂我oracle免费JP机上的

**Comment by 1791209985** [comment]
> > ### 解决办法，修改默认的api反向代理地址
> > 
> > * chatgpt-api库默认使用`https://chat.duti.tech/api/conversation`反响代理，就算你的.env没有配置，它也会默认走这个代理。（实际上openai只有在登录时需要走代理，其他大部分时候都是可以正常访问的。）
> > * 默认的反向代理，目前好像挂了？？？切了日本、香港、国内的代理，访问都是403.
> > * 切换可用的代理，参考[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi)，官方提供了两个反向代理，第一个挂了??? 第二个可用。
> > 
> > <img alt="image" width="730" src="https://user-images.githubusercontent.com/19379443/223616710-fe51304d-bad1-4802-a90e-8dfafbb15b6c.png">
> > ```
> > # 反向代理，可选
> > API_REVERSE_PROXY: "https://gpt.pawan.krd/backend-api/conversation"
> > ```
> 
> 怎么默认不走代理 我服务器在国外不用反代

在国外的服务器可以不用反代嘛

**Comment by 1791209985** [comment]
本人服务器在国外，但是还是出现了
![image](https://user-images.githubusercontent.com/100143315/224043865-36eee117-ac84-433d-bc1e-42812e9b6003.png)
是用docker镜像安装的

**Comment by ventusoon** [comment]
> 本人服务器在国外，但是还是出现了 ![image](https://user-images.githubusercontent.com/100143315/224043865-36eee117-ac84-433d-bc1e-42812e9b6003.png) 是用docker镜像安装的

同样的问题，请问解决了吗

**Comment by saaaaadk** [comment]
本人是使用自己的api key是可以用的。浅说一下自己搭建代理的思路，本人有一台国内的阿里云，同时也有一个国外的小鸡。采用v2ray的方式在国外搭建好能用的代理，然后再用一个docker项目v2ray/official直接在阿里云的服务器部署v2ray，记住ip和地址，最后启动本项目的时候将apikey设置好，然后代理 SOCKS_PROXY_HOST: ***（填写自己的ip，别填127.0.0.1，像我就是直接用阿里云的ip）、SOCKS_PROXY_PORT:***(docker映射 出来的地址）即可
然后出现的问题是 token仍然是无法使用的，现在的token修复我好像传参出现问题，与原来的接口不一致·
### linux用docker设置代理

将v2的端口设置好，并在` /etc/v2ray/config.json`这个文件中配置好导出的客户端模块，最后一键运行这个代码

```dockerfile
docker run -d --name v2ray -v /etc/v2ray:/etc/v2ray -p 10890:10890 v2ray/official  v2ray -config=/etc/v2ray/config.json
```
### docker 查看自己是否启动代理

- 如果是http代理

  - ```shell
    curl --proxy http://127.0.0.1:10890 www.google.com
    ```
