### ISSUE TITLE
我想加入https和fs模块，一直报错，不知道是什么情况，请帮忙看下

### ISSUE THREAD

**Issue by Nicolas-Gong** [Chanzhaoyu/chatgpt-web#387]
![image](https://user-images.githubusercontent.com/23067153/223598468-82ab4933-5c1b-492d-b711-fd051caa6ad0.png)
如图所示
系统 deepin20
node v18.15.0/v18.12.1 2个版本都试过
https v1.0.0
fs 0.0.1-security
pnpm v7.29.0
npm v9.5.0

不知道为什么会导入失败，搜索了很久没找到有用的答案，chatgpt的回答等于没回答。。。所以来这儿问问

**Comment by yiios** [comment]
我也折腾过，加不了。直接反代吧

**Comment by assassinliujie** [comment]
nginx自己反代一下好了

**Comment by Chanzhaoyu** [comment]
大哥，你加在前端页面是浏览器环境肯定会报错啊。

**Comment by Nicolas-Gong** [comment]
> 大哥，你加在前端页面是浏览器环境肯定会报错啊。

老哥，我是想做mTLS,应该是前后端都需要证书加密吧？前端请求接口时直接解密？发送的时候不加密？服务器上我是用的nginx反代的node的3001端口，然后加上了证书，全都是用的cloudflare的一套，我不是前端，所以不是太明白。

**Comment by vulgatecnn** [comment]
建议https等在nginx上做，nodejs核心是解决业务问题，不要把web server要干的事情让nodejs来做

**Comment by Nicolas-Gong** [comment]
> 建议https等在nginx上做，nodejs核心是解决业务问题，不要把web server要干的事情让nodejs来做

https已经用上了，这个很简单，现在想对接口双向非对称加密，cloudflare里有提供mTLS，但是不知道咋用。
