### ISSUE TITLE
关于ESLint的报错

### ISSUE THREAD

**Issue by TyCoding** [Chanzhaoyu/chatgpt-web#39]
这两天提交的代码中，IDEA总是会莫名奇妙报错EsLint 
TypeError: Cannot read properties of undefined (reading 'type')

导致ESLint失效，请问知道是什么原因吗，是否是配置有问题

**Comment by Chanzhaoyu** [comment]
Eslint 的问题 https://github.com/eslint/eslint/issues/16896

**Comment by Chanzhaoyu** [comment]
不过你可以复制的我的 `pnpm-lock.yaml`，目前还可以使用
