### ISSUE TITLE
使用accesstoken除了每个小时有提问数量限制之外，其他方面吊打api

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#390]
尤其是专业问题的回答，非常明显。api在accesstoken面前就是小学生。不服来辩。

**Comment by qyqx233** [comment]
自己搭的比官网稳定，官网用一会就要重连。真是 绝了。

**Comment by cquliaoli** [comment]
是的，感觉 accessToken 和 api 是两个层次的产品，api 回答的结果根本没法看

**Comment by mormiddle** [comment]
使用accessToken 和使用官网差别大吗？在考虑续费plus，api和accessToken哪个适合我 ，纯个人使用，真的很节省开发时间

**Comment by skifffire** [comment]
> 是的，感觉 accessToken 和 api 是两个层次的产品，api 回答的结果根本没法看
ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined

**Comment by skifffire** [comment]
ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined 这个是什么错误

**Comment by cquliaoli** [comment]
> ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined 这个是什么错误

新建一个会话试试

**Comment by ludashi2020** [comment]
> ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined 这个是什么错误
api代理服务器的问题，填这个
API_REVERSE_PROXY=https://chatgptapi.googlevideo.dev/api/conversation

**Comment by ludashi2020** [comment]
> 使用accessToken 和使用官网差别大吗？在考虑续费plus，api和accessToken哪个适合我 ，纯个人使用，真的很节省开发时间

个人用的不频繁的话，accessToken够了。需求大，上plus。高峰期访问有明显加成。

**Comment by caogle** [comment]
这个API_REVERSE_PROXY怎么搭的，能不能自己搞一个

**Comment by skifffire** [comment]
> > ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined 这个是什么错误
> > api代理服务器的问题，填这个
> > API_REVERSE_PROXY=https://chatgptapi.googlevideo.dev/api/conversation

谢谢，可以了

**Comment by tiro8183** [comment]
但是它慢呐

**Comment by cooolr** [comment]
慢的问题有很多方式可以解决

**Comment by mormiddle** [comment]
> 慢的问题有很多方式可以解决

求指点，我想试试，chatgpt最近用的很频繁

**Comment by cooolr** [comment]
> > 慢的问题有很多方式可以解决
> 
> 求指点，我想试试，chatgpt最近用的很频繁

秘密在我的项目代码里面 https://github.com/cooolr/chatgpt-proxy-web

**Comment by Simon-Yi** [comment]
感觉accesstoken对于个人来说很足够用了
