### ISSUE TITLE
能增加一个登录后才能使用功能吗？

### ISSUE THREAD

**Issue by XMFEr** [Chanzhaoyu/chatgpt-web#391]
能否增加登录后才能使用功能，国能环境比较复杂，小人难防，v2ex上就有人一夜之间收到300刀账单的，钱事小，被举报还有喝茶的机会。如果能加上此功能，万分感谢！

**Comment by wwlmm** [comment]
210版本，已经添加了啊 你更新一下

**Comment by liopoos** [comment]
可以在`/service`的`.env`中配置`AUTH_SECRET_KEY`用来提供访问权限密钥

**Comment by XMFEr** [comment]
哦，我更新一下，非常感谢你们的提醒，浪费你们时间了
