### ISSUE TITLE
建议 在聊天框或者左侧栏添加prompt预设选择

### ISSUE THREAD

**Issue by luckywangxi** [Chanzhaoyu/chatgpt-web#396]
类似于这个网站
https://chat.theb.ai/
![Screenshot_20230308_144715_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/112324550/223639487-27e489c9-40c9-4791-b5d6-2a5d6d6421e6.jpg)

**Comment by acongee** [comment]
下次大版本更新应该有了，有个 PR
