### ISSUE TITLE
能不能添加多个key然后检测key的余额，余额没了自动切换

### ISSUE THREAD

**Issue by Byz-liu** [Chanzhaoyu/chatgpt-web#397]
不知道能不能实现这个功能，我是自己和几个朋友一起用的，但是费用远远超出了预算，18刀两天就没了🤣，一开始打算绑卡现在也不敢绑了，只能买18刀账号一直换key，要是可以自动切换就好了。如果可以实现的话非常感谢！！！

**Comment by luuziiyoo** [comment]
用token不好吗

**Comment by qidian99** [comment]
18刀账号，什么价格

**Comment by Byz-liu** [comment]
> 用token不好吗

又不是自己用，还有朋友呢，根本不够用，而且token没有API稳定，没有API丝滑，我主要就是拿来翻译和润色文章，感觉API和token没啥区别。

**Comment by Byz-liu** [comment]
> 18刀账号，什么价格

我50块钱买了10个感觉价格还可以。

**Comment by gaoobin** [comment]
个人使用还是accesstoken香

**Comment by yeqiu006** [comment]
我1.5一个，有需要的可以联系我

**Comment by qimo2020** [comment]
1块钱1个key，找我买

**Comment by yudaqiangge** [comment]
> 



> 1块钱1个key，找我买

怎么出？

**Comment by assassinliujie** [comment]
> 1块钱1个key，找我买

怎么出

**Comment by assassinliujie** [comment]
> 我1.5一个，有需要的可以联系我

有多少

**Comment by niufox** [comment]
> 1块钱1个key，找我买

可以的呀

**Comment by yeqiu006** [comment]
现在outlook邮箱都封了，我是微软账号注册的
