### ISSUE TITLE
不支持上下文，实现对话

### ISSUE THREAD

**Issue by tiamohf** [Chanzhaoyu/chatgpt-web#4]
如果过个用户同时使用，每个用户都能实现对话，这个可以实现吗

**Comment by Chanzhaoyu** [comment]
接口是支持的，之后会支持联想和时间线

**Comment by tiamohf** [comment]
很棒，我准备再加一个语音识别跟文字转语音的功能，实现对话

**Comment by tiamohf** [comment]
另外使用API比官方demo对话的功能要弱很多，有办法提升吗

**Comment by tiamohf** [comment]
const api = new ChatGPTAPI({ apiKey: process.env.OPENAI_API_KEY })

// send a message and wait for the response
let res = await api.sendMessage('What is OpenAI?')
console.log(res.text)

// send a follow-up
res = await api.sendMessage('Can you expand on that?', {
  conversationId: res.conversationId,
  parentMessageId: res.id
})
console.log(res.text)

// send another follow-up
res = await api.sendMessage('What were we talking about?', {
  conversationId: res.conversationId,
  parentMessageId: res.id
})
console.log(res.text)

**Comment by Chanzhaoyu** [comment]
> 另外使用API比官方demo对话的功能要弱很多，有办法提升吗

因为网页的模型是 GPT-3.5，官方并没有放出来。现在 API 最新为 GPT-3，以后使用估计要另外付费。

**Comment by tiamohf** [comment]
其实你现在的代码比较简洁，挺好的，其它的功能可以可以我们自己完善

**Comment by Chanzhaoyu** [comment]
> 其实你现在的代码比较简洁，挺好的，其它的功能可以可以我们自己完善

我在想要不要先完善界面，把时间线，用户登录，还有你说的语音按钮这些先做出来。

**Comment by Chanzhaoyu** [comment]
现在能用的模型其实很蠢

**Comment by tiamohf** [comment]
> 现在能用的模型其实很蠢
对比了国内的一些，虽然很蠢，但是已经很强大了

**Comment by tiamohf** [comment]
> > 其实你现在的代码比较简洁，挺好的，其它的功能可以可以我们自己完善
> 
> 我在想要不要先完善界面，把时间线，用户登录，还有你说的语音按钮这些先做出来。

加上用户登录，就可以方便多用户对话，还能把历史对话给记录下来(用户使用的时候其实很喜欢分享)
{"role":"assistant","id":"cmpl-6iZTyQ61NcEAqG9RxZhDyCcjs75G3","parentMessageId":"dfb540d5-2ed5-4946-87c7-b937ac5d472b","conversationId":"cd0128fe-c425-40fd-bc71-ce93113cba71","text":"Hi!"}

**Comment by tiamohf** [comment]
加了 

> const api = new ChatGPTAPI({ apiKey: process.env.OPENAI_API_KEY })
> 
> // send a message and wait for the response let res = await api.sendMessage('What is OpenAI?') console.log(res.text)
> 
> // send a follow-up res = await api.sendMessage('Can you expand on that?', { conversationId: res.conversationId, parentMessageId: res.id }) console.log(res.text)
> 
> // send another follow-up res = await api.sendMessage('What were we talking about?', { conversationId: res.conversationId, parentMessageId: res.id }) console.log(res.text)

我按这样用了，上下文没有效果

**Comment by tiamohf** [comment]
这是不是问题
https://github.com/transitive-bullshit/chatgpt-api/issues/323

**Comment by Chanzhaoyu** [comment]
工作日的时候我把上下文联想加上

**Comment by Chanzhaoyu** [comment]
已经添加上下文功能，右上角的删除按钮退出联想

**Comment by tiamohf** [comment]
你是在服务端缓存的conversationId跟parentMessageId，如果有多人使用，内容会串掉

**Comment by Chanzhaoyu** [comment]
目前是单点访问，如果是多人要做关联

**Comment by tiamohf** [comment]
真厉害，我写了半天的代码全删了，换成你的代码了，我是做java的，前端代码写不利索

**Comment by Chanzhaoyu** [comment]
下一步我会做时间线(历史记录)，到时候我会写多个会话的上下文，也感谢你的建议

**Comment by Chanzhaoyu** [comment]
之后的 Route Map
- 上下文联想优化
- 会话时间线(历史记录)
- 个人登录相关页面
- 语音输入
- 多语言
- 主题

**Comment by gefeiyanga** [comment]
> 已经添加上下文功能，右上角的删除按钮退出联想

看了你的代码，确实简介，也提供了好的思路，其实就是直接拿最新一条的消息的两个id，作为下一条消息的消息的上文联系，以此循环类推。但是，如何不带参数，自动理解所有的上下文呢（前面好几句话），还是说官网产品才可以。

**Comment by Chanzhaoyu** [comment]
> > 已经添加上下文功能，右上角的删除按钮退出联想
> 
> 看了你的代码，确实简洁，也提供了好的思路，其实就是直接拿最新一条的消息的两个id，作为下一条消息的消息的上文联系，以此循环类推。但是，如何不带参数，自动理解所有的上下文呢（前面好几句话），还是说官网产品才可以。

目前我了解到的必须传参数，如果存在错误见谅。下个版本我会改成前端传ID来获取内容，以便同时进行多个会话，而不是缓存到服务端。

**Comment by tiamohf** [comment]
> 之后的 Route Map
> 
> * 上下文联想优化
> * 会话时间线(历史记录)
> * 个人登录相关页面
> * 模型参数设置
> * 语音输入
> * 多语言
> * 主题

建议后端部分加上log4js记录log，我目前用了这个记录了用户的对话历史

**Comment by gefeiyanga** [comment]
> > > 已经添加上下文功能，右上角的删除按钮退出联想
> > 
> > 
> > 看了你的代码，确实简洁，也提供了好的思路，其实就是直接拿最新一条的消息的两个id，作为下一条消息的消息的上文联系，以此循环类推。但是，如何不带参数，自动理解所有的上下文呢（前面好几句话），还是说官网产品才可以。
> 
> 目前我了解到的必须传参数，如果存在错误见谅。下个版本我会改成前端传ID来获取内容，以便同时进行多个会话，而不是缓存到服务端。

是的

**Comment by jjm2473** [comment]
不是支持上下文吗？
![localhost_1002_](https://user-images.githubusercontent.com/3896703/218291672-5db8475e-cd37-4173-affe-dd9a382cfbc2.png)

**Comment by Chanzhaoyu** [comment]
> 不是支持上下文吗？ ![localhost_1002_](https://user-images.githubusercontent.com/3896703/218291672-5db8475e-cd37-4173-affe-dd9a382cfbc2.png)

现在版本可以了，他提出来之后我更新了代码。

**Comment by icefox57** [comment]
现在实现上下文是靠拼接之前的对话作为参数吗? 如果是, 那不是很容易超token限制?

**Comment by icefox57** [comment]
现在实现上下文是靠拼接之前的对话作为参数吗?
