### ISSUE TITLE
如何设置默认中文语言

### ISSUE THREAD

**Issue by LiuQuanYou** [Chanzhaoyu/chatgpt-web#40]
如题

**Comment by sparrow211** [comment]
设置？？ 你是想知道AI回复中文？ 直接发送 “后续回复要用中文”

**Comment by Chanzhaoyu** [comment]
有一种取巧的参数，在`chatgpt.ts` 中加上这个

 `let options: SendMessageOptions = { timeoutMs: 30 * 1000, promptPrefix: '用中文回复我' }`

**Comment by LiuQuanYou** [comment]
好的，谢谢啦
