### ISSUE TITLE
前端手动打包到服务器，进去了然后发生问题请求，秒回空内容，前端并没有发生请求到后端出来，是怎么回事？

### ISSUE THREAD

**Issue by anranq** [Chanzhaoyu/chatgpt-web#400]
![Screenshot_2023-03-08-15-44-24-526_com android browser](https://user-images.githubusercontent.com/126095767/223652608-b6b6c65d-102f-4d04-b29e-a58faed218e5.jpg)
一直这样回复我，本地前端可以用，后端也是没问题的，前端node打包到服务器就不行了，求告知是什么问题？

**Comment by anranq** [comment]
@puppywang @shansing @PeterDaveHello @jjm2473 求助🆘

**Comment by anranq** [comment]
有人知道这个是怎么回事吗？

**Comment by Simon-Yi** [comment]
是不是没搭建好呢？

**Comment by Simon-Yi** [comment]
https://blog.zmyos.com/docker-chatgpt.html

**Comment by Simon-Yi** [comment]
我今天下午找到这个保姆级别的教程，一下子就搭建出来了，而且没问题

**Comment by anranq** [comment]
> 

![image](https://user-images.githubusercontent.com/126095767/223742132-2fb5ad0e-ea6c-40ac-a3fc-480a4a954d06.png)
没有啊，搭建出来前端是500错误

**Comment by anranq** [comment]
> 建议你先看下终端日志情况

我怀疑没连到后端，我在前端配置的端口为8083，然后我开了一个反代理监听8083转到后端的端口3002，都是在服务器上，请问这样对吗

**Comment by jjm2473** [comment]
.env改好了api地址吗？ 

https://github.com/Chanzhaoyu/chatgpt-web/blob/main/.env
