### ISSUE TITLE
网页如果不关的话，会一直重复的发送request么

### ISSUE THREAD

**Issue by Ohlagrange** [Chanzhaoyu/chatgpt-web#401]
![Snipaste_2023-03-08_16-03-25](https://user-images.githubusercontent.com/23275388/223656453-614cab0b-9a28-4af4-bf27-9a9c78fcb5d2.png)
![Snipaste_2023-03-08_16-05-07](https://user-images.githubusercontent.com/23275388/223656481-6085f985-fed5-42e4-9e9f-400995f631e2.png)
![微信图片_20230308160540](https://user-images.githubusercontent.com/23275388/223656509-b228dc9a-fed4-4424-81dc-56175f15ba87.png)

只有我一个人在用，然后前几天自己电脑上chat网页一直没关。今天收到了禁用邮件，服务端在国外。

**Comment by acongee** [comment]
改网页标题加访问控制吧，`ChatGPT Web` 可以直接搜出来好多不幸的话就被盯上了

**Comment by Chanzhaoyu** [comment]
放公网被人搜出来了？
