### ISSUE TITLE
使用 nginx 配置 octet-stream （打字特效）无法实现

### ISSUE THREAD

**Issue by JuneDan** [Chanzhaoyu/chatgpt-web#402]
在issues很多人提出的解决方法是
default_type octet-stream;
	proxy_buffering off;
	chunked_transfer_encoding on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header REMOTE-HOST $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
这个配置是可以的，但是要重启nginx，重启这个不只是nginx-t + nginx -s reload这么简单，要进去进程里面把nginx的进程杀死再重启，就可以生效了

**Comment by vulgatecnn** [comment]
proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "Upgrade";

我的解决办法增加这个配置

systemctl restart nginx  解决了，核心原因是nginx默认没有开websockets

**Comment by rhymed-liu** [comment]
我是这样设置的还是没用

location /api
    {
        rewrite  ^/api/?(.*)$ /$1 break;
        default_type octet-stream;
        proxy_buffering off;
        chunked_transfer_encoding on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 120;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "";
        proxy_http_version 1.1; 
        proxy_pass http://127.0.0.1:3002/; 
    }

**Comment by rhymed-liu** [comment]
已经找到问题了
  location /api
    {
        rewrite  ^/api/?(.*)$ /$1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "";
        proxy_http_version 1.1; 
        proxy_pass http://127.0.0.1:3002/; 
    }
本地的这个配置是没有问题的 可以实现打字机效果

主要的就是如果你用的是代理的api,那么代理的api也要配置,如下是配置参考
location /openai/ {
    default_type octet-stream;
    proxy_buffering off;
    chunked_transfer_encoding on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 120;
    proxy_pass https://api.openai.com/;
    proxy_set_header Host api.openai.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
}

**Comment by ludejun-666** [comment]
我是用Docker compose架构出来的，以上答案不知道怎么配置

**Comment by renqi1996** [comment]
> ```
>        proxy_http_version 1.1;
>        proxy_set_header Upgrade $http_upgrade;
>        proxy_set_header Connection "Upgrade";
> ```
> 
> 我的解决办法增加这个配置
> 
> systemctl restart nginx 解决了，核心原因是nginx默认没有开websockets

worked for me

**Comment by geegku** [comment]
proxy_buffering off;

**Comment by xyhcode** [comment]
> proxy_buffering off; 这一句是关键

用了这句也是一大块一大块的展示怎么办

**Comment by xyhcode** [comment]
> 如果是你的前端,并且打包部署了,那么相当于静态页面,则需要将api的请求通过ng转发到后端的api接口,如下配置即可
> location /api
> {
> rewrite ^/api/?(.*)$ /$1 break;
> proxy_set_header Host $host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header REMOTE-HOST $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header Connection "";
> proxy_http_version 1.1;
> proxy_pass http://127.0.0.1:3002/;
> }

我这个还需要配置 location /的模块吗？
