### ISSUE TITLE
解决在MAC下访问不了openapi的问题，给后人留点经验

### ISSUE THREAD

**Issue by laozhuang727** [Chanzhaoyu/chatgpt-web#408]
1.刚开始一直请求时报错fetch failed

在.env文件中
改了一下openapi的代理
OPENAI_API_BASE_URL= 'https://openapi.ssiic.com'

改完后在windows下可以了

2. 在mac下有证书问题，一直报错“unable to get local issuer certificate”
在.env文件中
NODE_TLS_REJECT_UNAUTHORIZED='0'

重启，搞定，希望给后人有一些帮助

**Comment by AtlanticYu** [comment]
确实有效, 谢谢了
