### ISSUE TITLE
docker images ：pnpm not found cmd

### ISSUE THREAD

**Issue by 7757** [Chanzhaoyu/chatgpt-web#41]
![image](https://user-images.githubusercontent.com/48285391/219306040-79a82049-c4d5-44d9-8a99-5b6a508859e0.png)

**Comment by 7757** [comment]
可以使用 npm bootstrap 吗

**Comment by Chanzhaoyu** [comment]
`docker` 我不是很了解诶，现在是合并的 `PR`

**Comment by 7757** [comment]
依赖npm 不顶用 就很鸡肋 
![image](https://user-images.githubusercontent.com/48285391/219307132-37f76022-82e3-424d-9850-0f90dc426f6b.png)

**Comment by Chanzhaoyu** [comment]
已经添加 `docker` 部署
