### ISSUE TITLE
添加了AUTH Key但是无效

### ISSUE THREAD

**Issue by kylejiang85** [Chanzhaoyu/chatgpt-web#411]
使用的docker部署：
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web:latest
    ports:
      - 9999:3002
    environment:
		OPENAI_ACCESS_TOKEN: XXXX
                API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation
		AUTH_SECRET_KEY: mypassword

之后访问locahost:9999仍然是不需要认证直接打开，清空浏览器cache后结果一样。

**Comment by Jason6111** [comment]
> 我也是在 railway 试了不行，在系统 env 加的参数没用，问下是不是只能改 server 里面的.env 才能生效，这样的话对 docker 用户不友好我用docker railway 试过可以

**Comment by caogle** [comment]
> 使用的docker部署： version: '3'
> 
> services: app: image: chenzhaoyu94/chatgpt-web:latest ports: - 9999:3002 environment: OPENAI_ACCESS_TOKEN: XXXX API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation AUTH_SECRET_KEY: mypassword
> 
> 之后访问locahost:9999仍然是不需要认证直接打开，清空浏览器cache后结果一样。

清cache还是可以访问的，但是用无痕模式就要密码了
