### ISSUE TITLE
accessToken如何获取

### ISSUE THREAD

**Issue by gaozhao7** [Chanzhaoyu/chatgpt-web#412]
https://chat.openai.com/api/auth/session 返回{}怎么办？

**Comment by Chanzhaoyu** [comment]
登录

**Comment by i-iooi-i** [comment]
登录：https://chat.openai.com/chat 获取
登录：https://platform.openai.com/ 获取不到的

**Comment by gaozhao7** [comment]
可以了，感谢各位！

**Comment by gaozhao7** [comment]
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later
@Chanzhaoyu 大佬 提问的时候一直报这个错误是什么原因

**Comment by i-iooi-i** [comment]
> [OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later @Chanzhaoyu 大佬 提问的时候一直报这个错误是什么原因

https://github.com/Chanzhaoyu/chatgpt-web/issues/385

**Comment by gaozhao7** [comment]
可以用了，感谢大家解答

**Comment by hansonhantong** [comment]
> 可以了，感谢各位！

怎么操作的 分享下呗
