### ISSUE TITLE
【Bug】深色模式导出图片不对，浅色模式没问题（同时导出没有头像，已经有人pull了）

### ISSUE THREAD

**Issue by Faithlv-1** [Chanzhaoyu/chatgpt-web#416]
版本v2.10.0

### 1.深色模式导出
![chat-shot](https://user-images.githubusercontent.com/80620739/223768809-b36d74a8-6ec8-4a5b-916d-d50a1ddb7314.png)

### 2.浅色模式导出
![chat-shot (1)](https://user-images.githubusercontent.com/80620739/223768997-13f96c3b-69e7-454a-bf7c-c778aab27825.png)

### 3.实际截图
![Snipaste_2023-03-09_00-00-59](https://user-images.githubusercontent.com/80620739/223769066-368505ec-0bc9-4748-9d96-49fb50f12e63.png)

**Comment by Chanzhaoyu** [comment]
已修复
