### ISSUE TITLE
支持登录注册 & 多设备同步

### ISSUE THREAD

**Issue by Kerwin1202** [Chanzhaoyu/chatgpt-web#418]
>  https://github.com/Chanzhaoyu/chatgpt-web/pull/417

## 开启登录
> 当 AUTH_SECRET_KEY 不为空则开启登录，否则为空也可以多设备同步聊天。不同设备刷新页面会同步

> 其他设置看 注释好了

<img width="865" alt="image" src="https://user-images.githubusercontent.com/16319833/223781819-f3eabf77-3532-4f13-af7a-ec403f9379e2.png">

<img width="855" alt="image" src="https://user-images.githubusercontent.com/16319833/223785840-fe6dd74b-d438-4d1f-975a-6614c1bb4cac.png">

<img width="1764" alt="image" src="https://user-images.githubusercontent.com/16319833/223781734-d86cf733-1e4c-4df0-b663-3610e2f7408b.png">

**Comment by Luchioxy** [comment]
大佬你好！这个要怎么搞呀，我部署好了直接是对话页面，没有登录和注册，谢谢大佬

**Comment by helperAI** [comment]
感谢作者的无私奉献

**Comment by Simon-Yi** [comment]
这个是怎么实现的？
可以发下代码吗？

**Comment by Kerwin1202** [comment]
> 大佬你好！这个要怎么搞呀，我部署好了直接是对话页面，没有登录和注册，谢谢大佬

得看你是docker还是怎么配置的，如果你用的是 `docker-compose.yml` 需要自己编译 dockerfile 修改 image 否则还是用的在线旧版的


如果是 docker 在根目录
# 第一步
```
 docker build -t chatgpt-web .
```
# 第二步
```
pnpm build
```

# 第三步 
> 把 dist 下的所有文件移动到 docker-compose/nginx/html 目录下

# 第四步 
> 修改 `docker-compose.yml` 里的 `image` 指向 `chatgpt-web`
> 设置 `AUTH_SECRET_KEY` 不为空 就需要登录了  
> 如果开启注册 `REGISTER_ENABLED` 设置  true

# 第五步
```
docker-compose up -d
```

**Comment by Siri-Li** [comment]
没有手动配置的吗

**Comment by Kerwin1202** [comment]
> 没有手动配置的吗

手动指的是 非 docker 吗，就需要自己安装数据库  并修改 `server/env` 里的 按照注释写的配置
其他的和现在没区别

**Comment by Simon-Yi** [comment]
好复杂，小白一脸懵逼

**Comment by Luchioxy** [comment]
> > 大佬你好！这个要怎么搞呀，我部署好了直接是对话页面，没有登录和注册，谢谢大佬
> 
> 得看你是docker还是怎么配置的，如果你用的是 `docker-compose.yml` 需要自己编译 dockerfile 修改 image 否则还是用的在线旧版的
> 
> # 第一步
> > 根目录
> 
> ```
>  docker build -t chatgpt-web .
> ```
> 
> # 第二步
> > 根目录
> 
> ```
> pnpm build
> ```
> 
> # 第三步
> > 把 dist 下的所有文件移动到 docker-compose/nginx/html 目录下
> 
> # 第四步
> > 修改 `docker-compose.yml` 里的 `image` 指向 `chatgpt-web`
> > 设置 `AUTH_SECRET_KEY` 不为空 就需要登录了
> > 如果开启注册 `REGISTER_ENABLED` 设置  true
> 
> # 第五步
> > docker-compose 目录下
> 
> ```
> docker-compose up -d
> ```

非常感谢！

**Comment by Kerwin1202** [comment]
> > > 没有手动配置的吗
> > 
> > 
> > 手动指的是 非 docker 吗，就需要自己安装数据库  并修改 `server/env` 里的 按照注释写的配置
> > 其他的和现在没区别
> 
> 可以细说手动吗 大佬

得看你是什么模式部署。。

**Comment by oldfishoh** [comment]
> > > > 没有手动配置的吗
> > > 
> > > 
> > > 手动指的是 非 docker 吗，就需要自己安装数据库  并修改 `server/env` 里的 按照注释写的配置
> > > 其他的和现在没区别
> > 
> > 可以细说手动吗 大佬
> 
> 得看你是什么模式部署。。

pnpm build打包托管到静态服务器

**Comment by Kerwin1202** [comment]
> > > > > 没有手动配置的吗
> > > > 
> > > > 
> > > > 手动指的是 非 docker 吗，就需要自己安装数据库  并修改 `server/env` 里的 按照注释写的配置
> > > > 其他的和现在没区别
> > > 
> > > 
> > > 可以细说手动吗 大佬
> > 
> > 
> > 得看你是什么模式部署。。
> 
> pnpm build打包托管到静态服务器

打包之后 需要设置环境变量 类似在根目录下使用 .env文件 （默认有一个 .env.example 自己重命名改下里面的配置
