### ISSUE TITLE
ChatGPT独享账户，几块钱省的折腾了

### ISSUE THREAD

**Issue by zerobyw** [Chanzhaoyu/chatgpt-web#419]
ChatGPT独享账户，几块钱省的折腾了
http://ifaka.icu/?code=YT0xJmI9Mw%3D%3D

**Comment by huxubo** [comment]
自己注册不行吗！

**Comment by qimo2020** [comment]
人家chatgpt账号都卖1块钱，你翻了10倍价格了

**Comment by huxubo** [comment]
自己注册的，用英格兰号码接码花了不到4块钱

**Comment by Nihosijie** [comment]
这算是广告吧？这不删？

**Comment by Simon-Yi** [comment]
> 这算是广告吧？这不删？

肯定是广告了，真无聊这种人

**Comment by Byz-liu** [comment]
抢银行去吧，那样来钱快

**Comment by BeUnhappy** [comment]
还细心的带上了邀请码，怎么滴，靠这个养老？

**Comment by font-size** [comment]
老铁，这里的人基本都是懂开发的，在这里打广告不划算

**Comment by assassinliujie** [comment]
> 这价格就不要搞了，现在某宝注册一堆1快的

有一说一，政策更新了之后赠金只有5usd了，要是卖的是18usd的还行吧（）
