### ISSUE TITLE
有没有大佬可以研究出来代理接口,目前国外两个接口地址都挂了

### ISSUE THREAD

**Issue by wangrui19970405** [Chanzhaoyu/chatgpt-web#422]

**Comment by sonken87** [comment]
我之前看到一个googleapi的反代，可以用的，后面找不见了

**Comment by ludashi2020** [comment]
目前全都挂了，暂时先切回api key吧

**Comment by sonken87** [comment]
> 

今天上午还行的

**Comment by qyqx233** [comment]
It looks like **OpenAI has patched the current unofficial ChatGPT API proxy method**. It's possible this is related to a temporary OpenAI server outage, but I think that's unlikely.

Unofficial API proxies are unlikely to work for the time being until we find a different workaround.

If you haven't already switched to using the official API, now might be a good time to try it out.

找到了hack proxy的群，结论如上

**Comment by wuzhijie0101** [comment]
API KEY目前正常，就是反应有点慢。

**Comment by acongee** [comment]
应该是官方想 ban 这些代理了

**Comment by wangrui19970405** [comment]
那就终结了 只能用回 apikey了 apikey的训练模型需要切换 至于怎么切换 还是不清楚

**Comment by DragonRollGH** [comment]
> 那就终结了 只能用回 apikey了 apikey的训练模型需要切换 至于怎么切换 还是不清楚

试试这个：https://github.com/Chanzhaoyu/chatgpt-web/pull/404

**Comment by rocket2023** [comment]
我用的香港节点，使用token模式都正常

**Comment by sunchir** [comment]
> token

为啥我403同香港服务器

**Comment by ludashi2020** [comment]
有没有合租plus订阅的，开plus订阅可解![WeChat截图_20230309190702.png](https://pic.shenbian.tv/2023/03/09/c35f09eae8e4a.png)

**Comment by ttqwer1** [comment]
> 

可合租， 怎么联系

**Comment by gk34577** [comment]
> 有没有合租plus订阅的，开plus订阅可解![WeChat截图_20230309190702.png](https://camo.githubusercontent.com/40a6cc0d8c041cd9ba62cec03e5381732c824ee2ddd5dc3a8916adae536519bd/68747470733a2f2f7069632e7368656e6269616e2e74762f323032332f30332f30392f633335663039656165386534612e706e67)

怎么联系？

**Comment by JamesFlare1212** [comment]
https://github.com/acheong08/ChatGPT/commit/64f5f3db66cd3e6cb773379f900801a4ad8bc8ad

**Comment by rhymed-liu** [comment]
https://proxy.durance.top/openai/
