### ISSUE TITLE
客户端build出来访问500

### ISSUE THREAD

**Issue by jpinglove** [Chanzhaoyu/chatgpt-web#423]
![微信图片_20230309103935](https://user-images.githubusercontent.com/8130561/223901892-7ea3d88b-509a-4c1e-96fa-a78010912205.png)
客户端build 出来后，我放在内网打开就500.  
2个服务器，外网接口服务器，内网客户端。
最初是访问 外网服务器测试， build时，使用过ip,域名，都不好用。
我又把服务器和客户端放在内网的同一台机器上，访问也是这样500。先不说接口能不能调通，打开页面就500. 
是除了按文档但要说的，还要配置其它什么吗？
但是客户端如果用 pnpm dev 就可以，外网内网都可以访问。
实在不懂，请指教。

**Comment by ChandlerVer5** [comment]
404 ，你这个api路径对吗？

**Comment by Simon-Yi** [comment]
有没有一种可能，你端口没打开，默认端口是81

**Comment by jpinglove** [comment]
> 有没有一种可能，你端口没打开，默认端口是81

81? 我全局搜了整个项目，没有找到81的端口设置。
谢谢2位。我再看看。

**Comment by Pastechn** [comment]
看起来似乎是后端地址的问题 我记得后端的端口默认是3002
你可以试试直接访问后端地址 看看有没有问题

**Comment by Simon-Yi** [comment]
> > 有没有一种可能，你端口没打开，默认端口是81
> 
> 81? 我全局搜了整个项目，没有找到81的端口设置。 谢谢2位。我再看看。

楼上的大佬说3002的默认端口，你试试

**Comment by iamjimmycheng** [comment]
我用render部署也是500错误，点击go to home，问问题没反应。
但是用自己服务器docker部署，一切都是正常的。

**Comment by Atomin-Lee** [comment]
不用docker，自己部署在服务器，在nginx中添加下面的参数
``` nginx
 location /api {
        proxy_pass http://localhost:3002;
        proxy_buffering off;
    }
```

**Comment by jpinglove** [comment]
> 不用docker，自己部署在服务器，在nginx中添加下面的参数
> 
> ```nginx
>  location /api {
>         proxy_pass http://localhost:3002;
>         proxy_buffering off;
>     }
> ```

好用 ！！ 牛拜！

**Comment by diyyong** [comment]
> 不用docker，自己部署在服务器，在nginx中添加下面的参数
> 
> ```nginx
>  location /api {
>         proxy_pass http://localhost:3002;
>         proxy_buffering off;
>     }
> ```

感谢，好用！！
