### ISSUE TITLE
ChatGPTUnofficialProxyAPI no longer works – use ChatGPTAPI instead

### ISSUE THREAD

**Issue by yzh990918** [Chanzhaoyu/chatgpt-web#425]
Original link: https://github.com/transitive-bullshit/chatgpt-api/issues/453

**Comment by ludashi2020** [comment]
开plus订阅可解。我花了20刀搞定了。![WeChat截图_20230309190702.png](https://pic.shenbian.tv/2023/03/09/c35f09eae8e4a.png)

**Comment by hncboy** [comment]
> 开plus订阅可解。我花了20刀搞定了。![WeChat截图_20230309190702.png](https://camo.githubusercontent.com/40a6cc0d8c041cd9ba62cec03e5381732c824ee2ddd5dc3a8916adae536519bd/68747470733a2f2f7069632e7368656e6269616e2e74762f323032332f30332f30392f633335663039656165386534612e706e67)

这是直接访问官网的接口吧，如果把代理地址改为这个会报 403

**Comment by hnuzhoulin** [comment]
> 开plus订阅可解。我花了20刀搞定了。![WeChat截图_20230309190702.png](https://camo.githubusercontent.com/40a6cc0d8c041cd9ba62cec03e5381732c824ee2ddd5dc3a8916adae536519bd/68747470733a2f2f7069632e7368656e6269616e2e74762f323032332f30332f30392f633335663039656165386534612e706e67)

plus的接口地址不一样？

**Comment by hncboy** [comment]
> > 开plus订阅可解。我花了20刀搞定了。![WeChat截图_20230309190702.png](https://camo.githubusercontent.com/40a6cc0d8c041cd9ba62cec03e5381732c824ee2ddd5dc3a8916adae536519bd/68747470733a2f2f7069632e7368656e6269616e2e74762f323032332f30332f30392f633335663039656165386534612e706e67)
> 
> plus的接口地址不一样？

我是 plus，plus 接口是一样的，accesstoken 也是同一个
