### ISSUE TITLE
提问过的问题，可否增加编辑功能，编辑后的问题，chargpt生成新问题的答案覆盖原先的问题答案

### ISSUE THREAD

**Issue by goodwisdom** [Chanzhaoyu/chatgpt-web#426]
有时提过的问题，chargpt回复的答案不是太满意，需要修改提问的个别用词，如果问题很长，复制然后粘贴、再修改，比较麻烦

**Comment by tiro8183** [comment]
倒是可以加个复制问题与答案的按钮

**Comment by assassinliujie** [comment]
这个双击全选就行吧，手机的话长按复制应该都是默认全选？

**Comment by zmlix** [comment]
可以看看我做的😀 https://github.com/zmlix/chatgpt-web/tree/main/ChatGPT

**Comment by goodwisdom** [comment]
小白，不懂测试😂
