### ISSUE TITLE
只发了2个请求，就429了，有没有遇到这个问题的

### ISSUE THREAD

**Issue by sdli** [Chanzhaoyu/chatgpt-web#427]
如题，感觉不是限流，是哪里不对，请求2次正常，一会儿就429，看了request记录，只有2个。

**Comment by tttpeng** [comment]
是的 我也同样遇到这样的问题，使用的阿里云的新加坡服务器

**Comment by iamjimmycheng** [comment]
request记录在哪看呢？

**Comment by sdli** [comment]
在个人账号-> usage中查看

> request记录在哪看呢？

**Comment by sdli** [comment]
> 

+1 我腾讯云新加坡

**Comment by sdli** [comment]
> 是的 我也同样遇到这样的问题，使用的阿里云的新加坡服务器


+1 我腾讯云新加坡

**Comment by Simon-Yi** [comment]
> 

+2 同样是腾讯云的新加坡服务器

**Comment by HHhne** [comment]
是被封号了，铁汁们，限流是作者的判断语，实际上的回包就是api被封了

**Comment by fireinrain** [comment]
> 我也是，只发了一个请求，没多久就来邮件提示API被禁用了

我的api也被禁用了 尴尬

**Comment by Rannnm** [comment]
具体是什么原因封的呢 危险发言 还是因为地区限制

**Comment by Chanzhaoyu** [comment]
> 具体是什么原因封的呢 危险发言 还是因为地区限制

VPS 提供商，IP 都会

**Comment by fireinrain** [comment]
我也是用新的账户的api key, 只问了两个问题，就被429了, 这是服务器日志
 chatgpt-web-service@1.0.0 start /app
> esno ./src/index.ts
Server is running on port 3002
ChatGPTError: ChatGPT error 429: {
    "error": {
        "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.",
        "type": "access_terminated",
        "param": null,
        "code": null
    }
}
    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.0.8/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 429,
  statusText: 'Too Many Requests',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 429,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Too Many Requests',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by quzard** [comment]
无法理解openai这波操作，api的使用场景往往是服务器，却封服务器
