### ISSUE TITLE
移动端情况下侧边栏自动隐藏

### ISSUE THREAD

**Issue by TyCoding** [Chanzhaoyu/chatgpt-web#43]
请教一下作者，因为本人是Java后端开发，请问侧边栏如何增加对移动端设备监听，实现在移动端下自动隐藏侧边栏。

其次，还有一个小样式问题，侧边栏关闭情况下，箭头按钮的位置有点隐藏了

![image](https://user-images.githubusercontent.com/36946717/219313398-1cacf859-c2cf-44b6-bb65-0a5402efcd1b.png)

**Comment by Chanzhaoyu** [comment]
下个版本添加

**Comment by TyCoding** [comment]
好的感谢

**Comment by Chanzhaoyu** [comment]
最新代码已添加
