### ISSUE TITLE
求问部署完成之后无法正常使用

### ISSUE THREAD

**Issue by wanghuisenior** [Chanzhaoyu/chatgpt-web#431]
使用docker部署到了openwrt上，网页可以访问，但是对话提示：
[OpenAI] 服务器限流，请稍后再试 | Server was limited, please try again later 
 要么回答 ：fetch failed  ，登录openai后台查看useage啥也没有，这是什么意思呢，  不是免费的吗，还是咋回事

**Comment by Chanzhaoyu** [comment]
API 被墙了，你要想办法代理

**Comment by Simon-Yi** [comment]
> > API 被墙了，你要想办法代理
> 
> 大佬， 我有代理，用哪个国家的节点呢， 挂代理是在本地访问时使用代理，还是配置这个服务的时候挂代理？docker部署的时候没有设置代理的地方

用Nginx Proxy Manager这个反神代理神器

**Comment by wanghuisenior** [comment]
> > > API 被墙了，你要想办法代理
> > 
> > 
> > 大佬， 我有代理，用哪个国家的节点呢， 挂代理是在本地访问时使用代理，还是配置这个服务的时候挂代理？docker部署的时候没有设置代理的地方
> 
> 用Nginx Proxy Manager这个反神代理神器

你好，你说的这个代理是翻墙的意思还是啥? 我现在用的是路由器端口转发，在加上花生壳的ddns，  可以在外网访问这个服务，还需要代理吗

**Comment by nagaame** [comment]
你的服务需要通过代理，你可以使用美国的节点试试，或者找个反向代理，替代`api.openai.com`这个域名

**Comment by wanghuisenior** [comment]
> 你的服务需要通过代理，你可以使用美国的节点试试，或者找个反向代理，替代`api.openai.com`这个域名

![QQ截图20230309172835](https://user-images.githubusercontent.com/9377248/223979201-7c1ee9ee-763a-44a8-8ebe-d6211d3a777b.png)
我装了Nginx Proxy Manager  这里怎么填？  填192.168.31.95:3002  这样？  域名是自己随便写的吗

**Comment by Simon-Yi** [comment]
> > 你的服务需要通过代理，你可以使用美国的节点试试，或者找个反向代理，替代`api.openai.com`这个域名
> 
> ![QQ截图20230309172835](https://user-images.githubusercontent.com/9377248/223979201-7c1ee9ee-763a-44a8-8ebe-d6211d3a777b.png) 我装了Nginx Proxy Manager 这里怎么填？ 填192.168.31.95:3002 这样？ 域名是自己随便写的吗

域名填写你当前能够正常解析的就行了，中间填写你的公网IP，然后填写3002端口就行了，
