### ISSUE TITLE
拉取最新镜像后，服务器拒绝访问

### ISSUE THREAD

**Issue by nonskim** [Chanzhaoyu/chatgpt-web#434]
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

**Comment by Transparenthw** [comment]
被封了，看看你注册时候的邮箱有没有邮件

**Comment by nonskim** [comment]
> 被封了，看看你注册时候的邮箱有没有邮件

没有啊，我自己用的封我干啥

**Comment by Transparenthw** [comment]
挂个代理

**Comment by yanstu** [comment]
插眼

**Comment by fireinrain** [comment]
不知道是项目代码问题还是chatgpt那边触发了什么，反正目前我两个号的api key都被terminate了。相当难受

**Comment by lqs2019** [comment]
我的也被封了 ，有人知道怎么解锁吗？
![image](https://user-images.githubusercontent.com/52406708/224011456-3593ad6a-82b1-4146-b21d-77a98aafb39d.png)
