### ISSUE TITLE
昨天还好好的，今天前端发消息就收到这个提示，是不是封号了？

### ISSUE THREAD

**Issue by 917931227** [Chanzhaoyu/chatgpt-web#436]
ChatGPT error 429: {
"error": {
"message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.",
"type": "access_terminated",
"param": null,
"code": null
}
}

**Comment by fireinrain** [comment]
是的  我两个号都这样死了

**Comment by baby9** [comment]
> 是的 我两个号都这样死了

same

**Comment by baby9** [comment]
> > 是的 我两个号都这样死了
> 
> same

我今天就请求了一次，第二次就429了

**Comment by 917931227** [comment]
我还花20刀开了plus，是什么原因引起的？这没法解封吗？

**Comment by Transparenthw** [comment]
你的配置文件里面OPENAI_API_BASE_URL填的是https://api.openai.com吗？

**Comment by 917931227** [comment]
OPENAI_API_BASE_URL=https://api.openai.com

**Comment by caogle** [comment]
部署在公网吗，是不是被人薅了

**Comment by Transparenthw** [comment]
> 部署在公网吗，是不是被人薅了

被薅了啥意思

**Comment by 917931227** [comment]
账号登陆https://chat.openai.com/chat看不到历史聊天记录了，但是new chat提交问题chatgpt能正常回答

**Comment by L0yy** [comment]
我也是！

**Comment by mason0510** [comment]
被人薅羊毛了 操

**Comment by hncboy** [comment]
> 账号登陆[https://chat.openai.com/chat看不到历史聊天记录了，但是new](https://chat.openai.com/chat%E7%9C%8B%E4%B8%8D%E5%88%B0%E5%8E%86%E5%8F%B2%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AFnew) chat提交问题chatgpt能正常回答

昨天我也遇到了这个问题，看控制台是获取历史聊天记录的接口报错了，然后清除了之前的 apikey，并且退出 chatgpt 重新登录就可以了。
