### ISSUE TITLE
本地电脑起前后端遇到fetch failed问题

### ISSUE THREAD

**Issue by karl-tao-zhang** [Chanzhaoyu/chatgpt-web#437]
![微信截图_20230309175731](https://user-images.githubusercontent.com/42770875/223987067-0ba6eb13-0c62-46a5-8942-3a1aea98b81f.png)

**Comment by karl-tao-zhang** [comment]
只填了个OPENAI_API_KEY

**Comment by karl-tao-zhang** [comment]
vpn开关都不管用

**Comment by fireinrain** [comment]
上面不是写了timeout 链接超时  我看是不是你这个请求没走vpn

**Comment by Faithlv-1** [comment]
service 配置，换个url
OPENAI_API_BASE_URL=

**Comment by Chanzhaoyu** [comment]
> 换了url还是不行呀, vpn开的 日本 美国 全局代理 一样还是这样

这个链接拉闸了，你得自己反代一个

**Comment by karl-tao-zhang** [comment]
本地安装了个Nginx进行反代就好了,感谢回答
