### ISSUE TITLE
chatgpt的API变笨了

### ISSUE THREAD

**Issue by somego** [Chanzhaoyu/chatgpt-web#439]
记得gpt3.5版本刚接入那几天试用得到的答案好像和官网差不多，这几天发现明显有点变笨了，同一个问题官网能给出很丰富的回答，但是API版结果很简洁，偶尔有时候也能比官网要丰富一些。

**我刚才测试问了一个问题，输入后直接给我返回英语翻译。**
![Screen Shot 2023-03-09 at 19 12 47](https://user-images.githubusercontent.com/2386215/224007026-bae0a937-f081-49d7-92c7-c763c9cd084d.png)

**如果在后面加上“意味什么”这四个字，也只能得到简短的答案**
![Screen Shot 2023-03-09 at 19 10 18](https://user-images.githubusercontent.com/2386215/224007107-80d62738-26a6-466d-9fb5-d3eb3a8e3bfc.png)
**还有其他问题，比如**
![Screen Shot 2023-03-09 at 19 10 30](https://user-images.githubusercontent.com/2386215/224007185-63345f2e-d6f7-4321-982b-b6e2c1e00748.png)

**但是在官网和其他类似notionAI这样也是API接入的却能给出字数较多的回答。**
![Screen Shot 2023-03-09 at 19 02 28](https://user-images.githubusercontent.com/2386215/224008074-80e5ae4c-1262-493e-8b90-3c903cea4ca6.png)

![Screen Shot 2023-03-09 at 19 16 28](https://user-images.githubusercontent.com/2386215/224007846-b1b49f2f-1ef7-4110-8caf-47074311d95e.png)

**Comment by anranq** [comment]
模型本来就不一样，官网的先进一些的

**Comment by somego** [comment]
> 模型本来就不一样，官网的先进一些的

感觉前段时间3.5刚出时候，体验跟官网差不多，不知道是不是心理作用
API版写诗倒是和官网差不多，有时候甚至比官网还好一些

**Comment by Chanzhaoyu** [comment]
> > 模型本来就不一样，官网的先进一些的
> 
> 感觉前段时间3.5刚出时候，体验跟官网差不多，不知道是不是心理作用 API版写诗倒是和官网差不多，有时候甚至比官网还好一些

不是心里作用，是新模型出来的那天响应很快

**Comment by linesoft2** [comment]
这个项目所用的ChatGPT API项目在调用接口时会默认让GPT-3.5-turbo以简洁的方式回复，可能是这个原因。

**Comment by herepost** [comment]
可以参考一下你的配置吗，我接入3.5的时候一直有404错误
