### ISSUE TITLE
如何更新新的版本？

### ISSUE THREAD

**Issue by Simon-Yi** [Chanzhaoyu/chatgpt-web#441]
请问如何更新新的版本？
在Debian系统下通过什么命令进行更新？

**Comment by Chanzhaoyu** [comment]
群里面有同学做了一件脚本啊

**Comment by Simon-Yi** [comment]
> 群里面有同学做了一件脚本啊

你好大神，我是一个小白，不知道怎么做才对。
因为我没有找到大神你所说的群的一键脚本，请问你可以指点一下我吗？谢谢了！

**Comment by Chanzhaoyu** [comment]
你的 ID 我一直看到还小白啊 😂，你去看下置顶的 issues 里有个群号，群公告里面有一件脚本，我用手机不方便操作。

**Comment by Simon-Yi** [comment]
> 你的 ID 我一直看到还小白啊 😂，你去看下置顶的 issues 里有个群号，群公告里面有一件脚本，我用手机不方便操作。

好的，谢谢大神指点！

**Comment by wwlmm** [comment]
更新起来麻烦的很，重新部署一下好了
