### ISSUE TITLE
[OpenAl] 服务器限流，请稍后再试1Server was limited, please try again later

### ISSUE THREAD

**Issue by 1791209985** [Chanzhaoyu/chatgpt-web#442]
本人服务器在国外，但是还是出现了下面的现象（不清楚还需不需要反向代理）
![image](https://user-images.githubusercontent.com/100143315/224043865-36eee117-ac84-433d-bc1e-42812e9b6003.png)
是用docker镜像安装的，有无佬指点一下

**Comment by Chanzhaoyu** [comment]
也有可能是被封号了，去控制台看一下

**Comment by 1791209985** [comment]
> 也有可能是被封号了，去控制台看一下

好的佬，这就去检查一下

**Comment by 1791209985** [comment]
> 也有可能是被封号了，去控制台看一下

佬，果真让封了，得换服务器嘛
