### ISSUE TITLE
更新后报错说我没选择model，现在必须手动写吗，我填入了OPENAI_API_MODEL=gpt-3.5-turbo还是一样报错

### ISSUE THREAD

**Issue by JeazW** [Chanzhaoyu/chatgpt-web#443]
![image](https://user-images.githubusercontent.com/75829171/224053354-e0bb3e8d-c035-42a4-886c-9ec16f3fe934.png)

**Comment by Chanzhaoyu** [comment]
抱歉，添加参数导致的判断错误，已修复，`Docker` 正在推送中。

**Comment by Chanzhaoyu** [comment]
已推送

**Comment by JeazW** [comment]
> 已推送

已更新，辛苦大佬

**Comment by Chanzhaoyu** [comment]
> > 已推送
> 
> 已更新，辛苦大佬

现在是否正常？

**Comment by JeazW** [comment]
正常了😂感谢

**Comment by JeazW** [comment]
已解决

**Comment by JeazW** [comment]
已解决

**Comment by JeazW** [comment]
既然有了数据库，还希望能支持保存和恢复回话记录，类似于现在的导入导出功能，只不过现在是保存访问设备在本地。数据库推荐mongo，对json储存比较友好
