### ISSUE TITLE
下午API被封后，重装最新的code换了一个API发送请求又被限流了

### ISSUE THREAD

**Issue by 917931227** [Chanzhaoyu/chatgpt-web#444]
![image](https://user-images.githubusercontent.com/20813956/224064100-01a312cc-559b-4cab-a28a-bb24bf047fae.png)
这是账号的问题吗？还是这个程序接入openai的API后有被封禁的风险？

**Comment by Chanzhaoyu** [comment]
和你 `IP` 有关

**Comment by Byz-liu** [comment]
绑卡就没事了

**Comment by 1791209985** [comment]
> 绑卡就没事了

绑定银行卡吗

**Comment by 917931227** [comment]
> 绑卡就没事了

我的号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发出请求导致的。

**Comment by 1791209985** [comment]
> 和你 `IP` 有关，你换再多号都无效，这个项目的 `API` 就是调用的官方接口无其他处理。

那这个ip是服务器的ip吗

**Comment by 1791209985** [comment]
> 

我已经让封了 55

**Comment by 917931227** [comment]
> > 和你 `IP` 有关，你换再多号都无效，这个项目的 `API` 就是调用的官方接口无其他处理。
> 
> 那这个ip是服务器的ip吗

作者说的IP应该指的是访问前端页面并发出请求的IP，而不是所部署的服务器的公网IP

**Comment by 1791209985** [comment]
> > > 和你 `IP` 有关，你换再多号都无效，这个项目的 `API` 就是调用的官方接口无其他处理。
> > 
> > 
> > 那这个ip是服务器的ip吗
> 
> 作者说的IP应该指的是访问前端页面并发出请求的IP，而不是所部署的服务器的公网IP

嗷嗷这样啊

**Comment by 917931227** [comment]
> > > 绑卡就没事了
> > 
> > 
> > 我的号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发出请求导致的。
> 
> 请问你的是原本就不管，然后绑定银行卡，才好的吗？

我的问题没有解决，准备尝试用新账号和新服务器重新部署

**Comment by 1791209985** [comment]
> > > > 绑卡就没事了
> > > 
> > > 
> > > 我的号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发出请求导致的。
> > 
> > 
> > 请问你的是原本就不管，然后绑定银行卡，才好的吗？
> 
> 我的问题没有解决，准备尝试用新账号和新服务器重新部署

嗷嗷，就是还是显示限制是吧

**Comment by 917931227** [comment]
> > > > > 绑卡就没有事了
> > > > 
> > > > 
> > > > 我的账号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发送请求。
> > > 
> > > 
> > > 请问你的是本来就不管，然后绑定银行卡，才好吗？
> > 
> > 
> > 我的问题没有解决，准备尝​​试使用新账号和新服务器重装新部
> 
> 嘶嘶，就是还是显示限制制是吧

是的，API被权限禁用了，官方网页问答不影响。

**Comment by 1791209985** [comment]
> > > > > > 绑卡就没有事了
> > > > > 
> > > > > 
> > > > > 我的账号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发送请求。
> > > > 
> > > > 
> > > > 请问你的是本来就不管，然后绑定银行卡，才好吗？
> > > 
> > > 
> > > 我的问题没有解决，准备尝​​试使用新账号和新服务器重装新部
> > 
> > 
> > 嘶嘶，就是还是显示限制制是吧
> 
> 是的，API被权限禁用了，官方网页问答不影响。

感谢你的回答（）

**Comment by 917931227** [comment]
> > > > > > > 绑卡就没有事了
> > > > > > 
> > > > > > 
> > > > > > 我的账号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发送请求。
> > > > > 
> > > > > 
> > > > > 请问你的是本来就不管，然后绑定银行卡，才好吗？
> > > > 
> > > > 
> > > > 我的问题没有解决，准备尝​​试使用新账号和新服务器重装新部
> > > 
> > > 
> > > 嘶嘶，就是还是显示限制制是吧
> > 
> > 
> > 是的，API被权限禁用了，官方网页问答不影响。
> 
> 感谢你的回答（）

刚刚使用新账号和新服务器重新部署，能正常使用了！

**Comment by 1791209985** [comment]
> > > > > > > > 绑卡就没有事了
> > > > > > > 
> > > > > > > 
> > > > > > > 我的账号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发送请求。
> > > > > > 
> > > > > > 
> > > > > > 请问你的是本来就不管，然后绑定银行卡，才好吗？
> > > > > 
> > > > > 
> > > > > 我的问题没有解决，准备尝​​试使用新账号和新服务器重装新部
> > > > 
> > > > 
> > > > 嘶嘶，就是还是显示限制制是吧
> > > 
> > > 
> > > 是的，API被权限禁用了，官方网页问答不影响。
> > 
> > 
> > 感谢你的回答（）
> 
> 刚刚使用新账号和新服务器重新部署，能正常使用了！

请等几个小时后，继续测试，我的出现了，刚开始行，几个小时后就寄了

**Comment by 917931227** [comment]
> > > > > > > > > 绑定卡就没有事了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我的账号是plus的已经绑定过银行卡。邮件没有收到openai的封号通知。我的服务器是美国的，ip也是美国的，可能是API被盗用在其他地区的IP发送。
> > > > > > > 
> > > > > > > 
> > > > > > > 请问你的是本来就不管，然后绑定银行卡，才好吗？
> > > > > > 
> > > > > > 
> > > > > > 我的问题没有解决，准备试试 尝试使用新账号和新服务器重装新部
> > > > > 
> > > > > 
> > > > > 嘻嘻，就是还是显示限制制是吧
> > > > 
> > > > 
> > > > 是的，API被权限禁止使用了，官方网页提问没有影响。
> > > 
> > > 
> > > 感谢你的回答（）
> > 
> > 
> > 刚使用新账号和新服务器重新部署，可以正常使用了！
> 
> 请等几个小时后，继续测试，我的出现了，刚开始行，几个小时后就寄存了

已经正常使用1天了，目前没发现问题。
