### ISSUE TITLE
AUTH_SECRET_KEY使用中文，权限认证后500

### ISSUE THREAD

**Issue by KeepeeLee** [Chanzhaoyu/chatgpt-web#446]
权限认证后成功，然后跳转到此界面，点击go to home无反应
![图片](https://user-images.githubusercontent.com/62918613/224070771-51535a31-f151-4aaf-8cb1-098183737e39.png)

**Comment by Chanzhaoyu** [comment]
看控制台，这是后端服务没启动吧

**Comment by Chanzhaoyu** [comment]
还有为啥要用中文……

**Comment by RexWzh** [comment]
同样问题，刚拉取的镜像，没有设置密码，同样提示 500

**Comment by KeepeeLee** [comment]
> 看控制台，这是后端服务没启动吧

没有啊，用的docker，英文密码一切正常。。只是给你指出一个bug

**Comment by RexWzh** [comment]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/62223937/224077121-30e74752-ca98-4cab-9b29-77027d3d010b.png">

<img width="395" alt="image" src="https://user-images.githubusercontent.com/62223937/224077256-d5a3611c-6b09-419b-ae00-d5428175582d.png">

**Comment by Chanzhaoyu** [comment]
我知道原因了，靠！

**Comment by Chanzhaoyu** [comment]
我脑子被水抽了，乱合并

**Comment by Chanzhaoyu** [comment]
稍等，我本地 `docker build` 测试下

**Comment by Chanzhaoyu** [comment]
已修复
