### ISSUE TITLE
移動端的輸入格太小，較難閱讀

### ISSUE THREAD

**Issue by jtung4** [Chanzhaoyu/chatgpt-web#447]
移動端的輸入格現在變得太小了，較難閱讀。能否在正在輸入文字的時候把左邊的項目收起？
![677D552D-4CBB-4054-B148-F3423FE06030](https://user-images.githubusercontent.com/126780548/224085139-b38433b9-7653-434e-9047-61f2f9e74a06.jpeg)

**Comment by DragonRollGH** [comment]
获取可以把左边的按钮移到标题上？

**Comment by Chanzhaoyu** [comment]
> 或许可以把左边的按钮移到标题上？

我暂时改为了获取焦点隐藏，之后再优化吧

**Comment by wansenlyt** [comment]
在Android端当光标焦点在输入框内，弹出输入法后，输入框不能上移，被输入法遮挡住了，希望能优化下。

**Comment by Chanzhaoyu** [comment]
> 或许可以把左边的按钮移到标题上？

感谢你的建议，新版本按照你的建议优化了移动端的展示。

**Comment by Chanzhaoyu** [comment]
> 在Android端当光标焦点在输入框内，弹出输入法后，输入框不能上移，被输入法遮挡住了，希望能优化下。

这个我还需要测试下，感谢反馈
