### ISSUE TITLE
可以用 nginx 转发吗

### ISSUE THREAD

**Issue by 7757** [Chanzhaoyu/chatgpt-web#45]
如果是nginx的话 应该怎么构建环境大佬

**Comment by YutHelloWorld** [comment]
service build后用pm2挂起：pm2 start ./build/index.js
然后前端的nginx反向代理
location ^~ /api/
{
    proxy_pass http://127.0.0.1:3002/;
    // 省略

**Comment by 7757** [comment]
建议前后端赶紧分开放，分为两个project ，现在docker 把两个项目揉在一起发布到一个容器感觉很乱  不利于后面拓展
基于目前项目情况 nginx+docker 可以这样配
目前nginx 配置如下 ：
filename：chat.conf
`server {
    listen 80;
    server_name localhost;

    gzip on;
    gzip_static on;     # 需要http_gzip_static_module 模块
    gzip_min_length 1k;
    gzip_comp_level 4;
    gzip_proxied any;
    gzip_types text/plain text/xml text/css;
    gzip_vary on;
    gzip_http_version   1.0; #兼容多层nginx 反代
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    # 打包好的dist目录文件，放置到这个目录下
    root /data/;

    location ^~ /api/ {
			 proxy_pass http://192.168.8.47:3002/;
       #proxy_set_header Host $http_host;
       proxy_connect_timeout 15s;
       proxy_send_timeout 15s;
       proxy_read_timeout 15s;
       proxy_set_header X-Forwarded-Proto http;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 避免端点安全问题
    if ($request_uri ~ "/actuator"){
        return 403;
    }
}
`

前端dockerfile：
`FROM nginx

COPY ./dist /data

RUN rm /etc/nginx/conf.d/default.conf

ADD ./docker/chat.conf /etc/nginx/conf.d/

RUN /bin/bash -c 'echo init ok'
`

后端dockerfile：

`
FROM node:lts-alpine

COPY ./service /data

WORKDIR /data/service

EXPOSE 3002

RUN npm install pnpm -g && pnpm install

CMD sleep 1; pnpm start

`

运行状况：
![image](https://user-images.githubusercontent.com/48285391/219541355-c8f578db-71f3-4546-a6b8-451f00638ca0.png)

**Comment by Chanzhaoyu** [comment]
> 建议前后端赶紧分开放，分为两个project ，现在docker 把两个项目揉在一起发布到一个容器感觉很乱 不利于后面拓展 基于目前项目情况 nginx+docker 可以这样配 目前nginx 配置如下 ： filename：chat.conf `server { listen 80; server_name localhost;
> 
> ```
> gzip on;
> gzip_static on;     # 需要http_gzip_static_module 模块
> gzip_min_length 1k;
> gzip_comp_level 4;
> gzip_proxied any;
> gzip_types text/plain text/xml text/css;
> gzip_vary on;
> gzip_http_version   1.0; #兼容多层nginx 反代
> gzip_disable "MSIE [1-6]\.(?!.*SV1)";
> 
> # 打包好的dist目录文件，放置到这个目录下
> root /data/;
> 
> location ^~ /api/ {
> 		 proxy_pass http://192.168.8.47:3002/;
>    #proxy_set_header Host $http_host;
>    proxy_connect_timeout 15s;
>    proxy_send_timeout 15s;
>    proxy_read_timeout 15s;
>    proxy_set_header X-Forwarded-Proto http;
>    proxy_set_header X-Real-IP $remote_addr;
>    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> }
> 
> # 避免端点安全问题
> if ($request_uri ~ "/actuator"){
>     return 403;
> }
> ```
> 
> } `
> 
> 前端dockerfile： `FROM nginx
> 
> COPY ./dist /data
> 
> RUN rm /etc/nginx/conf.d/default.conf
> 
> ADD ./docker/chat.conf /etc/nginx/conf.d/
> 
> RUN /bin/bash -c 'echo init ok' `
> 
> 后端dockerfile：
> 
> ` FROM node:lts-alpine
> 
> COPY ./service /data
> 
> WORKDIR /data/service
> 
> EXPOSE 3002
> 
> RUN npm install pnpm -g && pnpm install
> 
> CMD sleep 1; pnpm start
> 
> `
> 
> 运行状况： ![image](https://user-images.githubusercontent.com/48285391/219541355-c8f578db-71f3-4546-a6b8-451f00638ca0.png)

一开始我是想用前端 `workspace` 分两个仓库，但是操作麻烦，怕很多不熟悉 `node.js` 的后端开发用不来。

而且现在很多人 `fork` 之后不好在小版本做大改。

之后还是做成前后端分离和分仓库的，因为我是前端，对后端很多都不懂。

还是发挥特长，主要做前端界面通用性的功能，只要接入自身的 `api` 就好。
