### ISSUE TITLE
建议写一下后端响应的数据参数，方便自开后端

### ISSUE THREAD

**Issue by anranq** [Chanzhaoyu/chatgpt-web#454]
只做后端有很多好处，比如可以限制违规话题，防范于未然，但是现在不清楚响应的数据参数有哪些？如何看？求大佬解释一下。

**Comment by Chanzhaoyu** [comment]
```ts
{
  status: 'Success' | 'Fail' |  'Unauthorized'
  data: any,
  message: string
}
```

**Comment by anranq** [comment]
> ```ts
> {
>   status: 'Success' | 'Fail' |  'Unauthorized'
>   data: any,
>   message: string
> }
> ```

感谢作者的回复

**Comment by anranq** [comment]
> ```ts
> {
>   status: 'Success' | 'Fail' |  'Unauthorized'
>   data: any,
>   message: string
> }
> ```

首先感谢作者的回复，请问message是显示在前端的消息吗？如果是的话那么data的数据在前端的作用是什么，麻烦说下，感谢

**Comment by aiens** [comment]
@anranq 你是准备用go写个自己的服务端吗？

**Comment by anranq** [comment]
> @anranq你准备好去写自己的服务端了吗？

我用的是Java
