### ISSUE TITLE
更换api不生效

### ISSUE THREAD

**Issue by zhzyg** [Chanzhaoyu/chatgpt-web#456]
在配置文件service/.env里面更换了api key，重启了后端和前段，在openai上看了但是还是用的旧apikey（两个不同的帐号），是不是还需要其他操作才能生效？

**Comment by Chanzhaoyu** [comment]
官网有延迟

**Comment by zhzyg** [comment]
> 官网有延迟

已经快一天了，还是走的旧API，服务器重启了还是一样，求原因……
