### ISSUE TITLE
api_key可以支持填多个，轮询吗

### ISSUE THREAD

**Issue by zhuxindong** [Chanzhaoyu/chatgpt-web#457]
比如api_key可以填写多个，逗号分割sk1,sk2,sk3。实际使用的时候去轮询

**Comment by HHhne** [comment]
上下文会话咋办。而且同ip不同账号api 会不会被封号

**Comment by 1VeniVediVeci1** [comment]
> 上下文会话咋办。而且同ip不同账号api 会不会被封号

会，只能说羊毛不能薅的太猛

**Comment by Chanzhaoyu** [comment]
同 `IP` 容易被封号
