### ISSUE TITLE
可以部署在vercel吗

### ISSUE THREAD

**Issue by Angel0726** [Chanzhaoyu/chatgpt-web#46]

**Comment by marlkiller** [comment]
可以部署在 railway , 环境变量配置 OPENAI_API_KEY 跟 port
https://railway.app/dashboard

**Comment by Angel0726** [comment]
> OPENAI_API_KEY

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/32816780/219538867-eb510d89-c3f2-41d7-824a-dc33ce31c2d8.png">
设置了port并没用是基于gpt3的吗？

**Comment by marlkiller** [comment]
大写的 PORT

**Comment by Angel0726** [comment]
> 大写的 PORT

<img width="923" alt="image" src="https://user-images.githubusercontent.com/32816780/219539755-a83ad2e1-0172-4db3-88c6-029ad8d431d1.png">
大小写都有

**Comment by marlkiller** [comment]
> > 大写的 PORT
> 
> <img alt="image" width="923" src="https://user-images.githubusercontent.com/32816780/219539755-a83ad2e1-0172-4db3-88c6-029ad8d431d1.png">
> 
> 大小写都有

拉最新代码, PORT=3002

**Comment by Angel0726** [comment]
> 3002

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/32816780/219540472-8966ecc9-836a-4304-8022-5e8a43c149a2.png">
单独大写PORT，单独消歇port，混合大小写PORT都不行。port设置的443、3002都进行了尝试
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/32816780/219540651-59b45b1c-4450-4a23-9904-709dc5ea28ba.png">
