### ISSUE TITLE
可以提供用户自己输入api key的界面么

### ISSUE THREAD

**Issue by Mircc** [Chanzhaoyu/chatgpt-web#461]
兼顾自身的访问需求，和公开给其他人的访问需求，实现方式您看看怎么合适
比如说：
1.输入正确的访问验证码，表示是本人使用，直接进入页面
2.输入错误的访问验证码，表示是其他人使用，直接引导其输入其自己的api key
或其他简单又不用过多开发的方式

**Comment by Chanzhaoyu** [comment]
封号概率很大
