### ISSUE TITLE
版本更新太频繁，使用群晖docker的兄弟看过来，简单的更新方法

### ISSUE THREAD

**Issue by luuziiyoo** [Chanzhaoyu/chatgpt-web#462]
我使用群晖docker
版本更新频繁，每次我更新都是重新拉取然后填写各种环境变量，然后删除之前版本的docker，太麻烦了。
下面是更新方法

前提是拉取的时候版本选的latest

1.停止运行需要升级的容器，“设置”导出容器内容和设置（防止出错给自己留后路）。

2.下载最新的镜像。

“注册表”搜索chatgpt-web镜像，选择版本“latest”

3.重置容器

回到“容器”，选中你的chatgpt容器，“操作”-“重置”

4.启动容器

大功告成，看看版本是不是更新了

**Comment by xyqkent** [comment]
用portainer可以直接recreate和re-pull最新镜像

**Comment by luuziiyoo** [comment]
群晖里有自己的容器管理工具 不需要portainer

**Comment by sola97** [comment]
可以用watchtower自动更

**Comment by luuziiyoo** [comment]
群晖有自己docker图形界面具体叫啥还真不知道叫啥
<img width="1279" alt="截屏2023-03-10 下午11 16 37" src="https://user-images.githubusercontent.com/10737650/224353911-6872d025-d15e-472e-9963-1894fc3358cd.png">
<img width="1277" alt="截屏2023-03-10 下午11 16 20" src="https://user-images.githubusercontent.com/10737650/224353923-ba0ecbcb-0316-46a2-acfb-f67e6201d2fc.png">

**Comment by i-iooi-i** [comment]
拉取最新的镜像，然后停掉当前运行的镜像，在停掉的镜像上=右键选择重置，就可以应用下载的最新镜像了。

另外，群晖刚发布的 dsm7.2 系统支持镜像自动升级了，可以等推送：https://www.synology.cn/zh-cn/DSM72

**Comment by yijiangchengming** [comment]
> 群晖有自己docker图形界面具体叫啥还真不知道叫啥 <img alt="截屏2023-03-10 下午11 16 37" width="1279" src="https://user-images.githubusercontent.com/10737650/224353911-6872d025-d15e-472e-9963-1894fc3358cd.png"> <img alt="截屏2023-03-10 下午11 16 20" width="1277" src="https://user-images.githubusercontent.com/10737650/224353923-ba0ecbcb-0316-46a2-acfb-f67e6201d2fc.png">

搜了一下，群晖在这方面不是很上心，没有用户界面。
