### ISSUE TITLE
关于文本偶尔出现的乱码和图片外链错误

### ISSUE THREAD

**Issue by Pandoxie** [Chanzhaoyu/chatgpt-web#463]
![Screenshot 2023-03-10 131356](https://user-images.githubusercontent.com/4418547/224229485-92705204-1ef5-459b-88e2-5b2099928d4d.jpg)
![Screenshot 2023-03-10 131028](https://user-images.githubusercontent.com/4418547/224229494-8472d5ef-469e-4122-8d11-9a867949ce68.jpg)
是不是中文的encoding有点问题，并且还有一些奇怪的图片外链错误。
大家有没有碰到

**Comment by goodnull** [comment]
遇到了，而且很频繁的出现，不知道是api本来就返回乱码，还是哪里的问题
![image](https://user-images.githubusercontent.com/11374302/224620606-7baa0f74-6f27-4d8d-b924-c16b1f022bfc.png)

**Comment by Chanzhaoyu** [comment]
我也遇到了，但是我看返回数据就是乱码
