### ISSUE TITLE
【优化】聊天框右侧增加话筒按钮，进行语音识别

### ISSUE THREAD

**Issue by gouguoyin** [Chanzhaoyu/chatgpt-web#468]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13517412/224238778-a1c1ce2a-8570-48a9-88c1-f6f89bcb8ec9.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13517412/224239708-f35357fa-3a43-46f0-a8dd-00482b7eede5.png">
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/13517412/224239546-a4a337ca-e8f5-4df3-a44e-c548a2c559b4.png">
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/13517412/224238958-856a673c-ffe6-4b2f-8950-6e4c049ff4eb.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13517412/224239293-19d2c62a-a9fa-40b1-a821-cb42621e2cad.png">
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/13517412/224239410-ce57bee2-9e32-4b99-80d7-8c4ac8cad155.png">

因为改动较大，因此另外拉了一个分支 https://github.com/gouguoyin/chatgpt-web

为了方便大家沟通交流，同步消息，建了QQ群，群号 145225165
![image](https://user-images.githubusercontent.com/13517412/223005824-5fc2075d-371a-4f68-8d09-d91598844e50.png)

**Comment by Byz-liu** [comment]
666 👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by Chanzhaoyu** [comment]
语音识别好像要 https 才能用吧

**Comment by gouguoyin** [comment]
> 语音识别好像要 https 才能用吧

是的

**Comment by Siri-Li** [comment]
可以了并到main就好了，老板更新速度

**Comment by Siri-Li** [comment]
.env 好像没有相关的配置选项哦

**Comment by rocket2023** [comment]
分支名换一下，fork的时候同名覆盖基础分支名
