### ISSUE TITLE
某大佬免费提供的api代理

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#469]
https://chatgpt.tgbot.co/backend-api/conversation

**Comment by zisanjun** [comment]
反代现在还可以用？

**Comment by ludashi2020** [comment]
> 反代现在还可以用？

这是某大佬重新弄，目前没有开源。测试token可用。

**Comment by zisanjun** [comment]
恢复了！！感谢

**Comment by 7757** [comment]
怎么用

**Comment by hncboy** [comment]
终于恢复了

**Comment by Cp0204** [comment]
可用，thk

**Comment by richadlee** [comment]
我返回了这个:[OpenAI] 提供错误的API密钥 | Incorrect API key provided

**Comment by GH6324** [comment]
> 

应该是Token过期了，重新获取一下token就好了

**Comment by wangrui1573** [comment]
这种代理怎么自建呢?

**Comment by Jason6111** [comment]
> 这种代理怎么自建呢?

https://github.com/ahmetkca/chatgpt-unofficial-api-docker/tree/ChatGPT-API-agent 应该是这个 但具体的看自己本事了

**Comment by ChandlerVer5** [comment]
不知道能撑多久...

**Comment by B1ue1nWh1te** [comment]
感谢大佬分享，速度确实不错。
