### ISSUE TITLE
请教docker两种安装方式下长回复设置问题

### ISSUE THREAD

**Issue by goodwisdom** [Chanzhaoyu/chatgpt-web#470]
1、群晖Docker安装镜像后，直接在环境变量中添加代码命令是否就可以了？

2、Docker compose安装如何设置才可以支持长回复？

  如果网页上有控制按钮就更方便了，可以跟随需求进行实时调整了

**Comment by luuziiyoo** [comment]
群晖docker直接在高级设置的变量中添加即可其他的都不用管，想在外网访问就在群晖的控制面板里找到登陆门户--高级--反代设置下端口号和你的群晖域名这样用群晖的域名加反代端口即可访问，别忘了路由器转发你的反代端口

**Comment by goodwisdom** [comment]
> 群晖docker直接在高级设置的变量中添加即可其他的都不用管，想在外网访问就在群晖的控制面板里找到登陆门户--高级--反代设置下端口号和你的群晖域名这样用群晖的域名加反代端口即可访问，别忘了路由器转发你的反代端口
> 

谢谢，Docker compose安装模式有好的解决办法吗

**Comment by luuziiyoo** [comment]
没用过 我一直用的群晖的

**Comment by cloudGrin** [comment]
长回复功能是根据前端项目里的vite环境变量import.meta.env.VITE_GLOB_OPEN_LONG_REPLY配置的，在编译阶段已经静态替换了，使用docker时用的是运行时，所以必须自己手动打包才行的。

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/27754342/224268934-b7211bc5-bc85-4e48-8f33-b9f5d7f68ef7.png">

**Comment by goodwisdom** [comment]
> 长回复功能是根据前端项目里的vite环境变量import.meta.env.VITE_GLOB_OPEN_LONG_REPLY配置的，在编译阶段已经静态替换了，使用docker时用的是运行时，所以必须自己手动打包才行的。
> 
> <img width="1177" alt="image" src="https://user-images.githubusercontent.com/27754342/224268934-b7211bc5-bc85-4e48-8f33-b9f5d7f68ef7.png">
> 

看来只能等待作者更新才能使用了

**Comment by goodwisdom** [comment]
> 群晖docker直接在高级设置的变量中添加即可其他的都不用管，想在外网访问就在群晖的控制面板里找到登陆门户--高级--反代设置下端口号和你的群晖域名这样用群晖的域名加反代端口即可访问，别忘了路由器转发你的反代端口
> 

似乎群晖直接添加变量也是不可以的

**Comment by luuziiyoo** [comment]
> > 群晖docker直接在高级设置的变量中添加即可其他的都不用管，想在外网访问就在群晖的控制面板里找到登陆门户--高级--反代设置下端口号和你的群晖域名这样用群晖的域名加反代端口即可访问，别忘了路由器转发你的反代端口
> 
> 似乎群晖直接添加变量也是不可以的

我就是这么用的
没问题啊

**Comment by goodwisdom** [comment]
> > > 群晖docker直接在高级设置的变量中添加即可其他的都不用管，想在外网访问就在群晖的控制面板里找到登陆门户--高级--反代设置下端口号和你的群晖域名这样用群晖的域名加反代端口即可访问，别忘了路由器转发你的反代端口
> > 
> > 似乎群晖直接添加变量也是不可以的
> 
> 我就是这么用的
> 没问题啊

参数能发下吗？难道我输入错误了？
