### ISSUE TITLE
怎么微调模型参数，还有能加一个聊天记录的记忆压缩的算法吗，希望在一个会话中可以不断深入话题聊下去

### ISSUE THREAD

**Issue by jiaqp** [Chanzhaoyu/chatgpt-web#471]

**Comment by jiaqp** [comment]
可以在超过token的时候压缩上文记忆，然后为下面的问题做为背景

**Comment by fwwdn** [comment]
上文记忆如何压缩？通过ChatGPT接口让模型提炼总结？

**Comment by jiaqp** [comment]
嗯总结一下

**Comment by jiaqp** [comment]
比如，请简化我这段话，要求在基本不损失原意的基础上越短越好，

xxxxxxxx

**Comment by jiaqp** [comment]
比如，请总结这段话的涵义，然后以你最大能力不丢失重要信息的情况下压缩这句话的长度

xxxxxxxx
