### ISSUE TITLE
docker部署后没有打字效果

### ISSUE THREAD

**Issue by YanzyUpEveryDay** [Chanzhaoyu/chatgpt-web#473]
你好，用docker部署镜像服务后本地访问也没有打字效果了。 目前出现的效果是 回复内容 一节一节的回复出来。
并且也没有用nginx做代理

**Comment by william5200** [comment]
我的情况有点不同，docker部署，用ip:端口直接访问有打字效果，反应很快，用nginx反代后没有打字效果，反应变慢。

**Comment by YanzyUpEveryDay** [comment]
> 前天在服务器上部署的服务，用nginx代理后是有打字效果的。。
今天更新了代码之后就没有了

**Comment by V-arc** [comment]
> 我的情况有点不同，docker部署，用ip:端口直接访问有打字效果，反应很快，用nginx反代后没有打字效果，反应变慢。

<img width="765" alt="" src="https://user-images.githubusercontent.com/53041402/224281562-10a43585-372b-4c9e-890f-476ecba8eaa5.png">

**Comment by YanzyUpEveryDay** [comment]
> docker本地也要用nginx做代理才能有打字效果吗？ 没更新之前本地没有做代理是有效果的

**Comment by william5200** [comment]
> > 我的情况有点不同，docker部署，用ip:端口直接访问有打字效果，反应很快，用nginx反代后没有打字效果，反应变慢。
> 
> <img alt="" width="765" src="https://user-images.githubusercontent.com/53041402/224281562-10a43585-372b-4c9e-890f-476ecba8eaa5.png">

感谢提醒，已解决！

**Comment by 2bstronger** [comment]
我也是使用docker部署，用ip:端口直接访问，但是没有打字效果

**Comment by 2bstronger** [comment]
> 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果

把（OPENAI_API_BASE_URL:）取消，使用以下就好了
SOCKS_PROXY_HOST: 
SOCKS_PROXY_PORT:

**Comment by BENBENBAI** [comment]
> > 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果
> 
> 把（OPENAI_API_BASE_URL:）取消，使用以下就好了 SOCKS_PROXY_HOST: SOCKS_PROXY_PORT:

老哥能细说么,我也是这个问题，是把url填写到host位置，port写443么？

**Comment by 2bstronger** [comment]
> > > 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果
> > 
> > 
> > 把（OPENAI_API_BASE_URL:）取消，使用以下就好了 SOCKS_PROXY_HOST: SOCKS_PROXY_PORT:
> 
> 老哥能细说么,我也是这个问题，是把url填写到host位置，port写443么？

port只写端口，host写地址，具体看你代理服务器是哪个地址提供服务

**Comment by BENBENBAI** [comment]
> > > > 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果
> > > 
> > > 
> > > 把（OPENAI_API_BASE_URL:）取消，使用以下就好了 SOCKS_PROXY_HOST: SOCKS_PROXY_PORT:
> > 
> > 
> > 老哥能细说么,我也是这个问题，是把url填写到host位置，port写443么？
> 
> port只写端口，host写地址，具体看你代理服务器是哪个地址提供服务

我很困扰啊，还不行，方便截一张您的容器环境配置的图么，麻烦了。

**Comment by 2bstronger** [comment]
version: '3'
  
services:
  test:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: 
      #      OPENAI_API_BASE_URL: 'https://openapi.ssiic.com'
      SOCKS_PROXY_HOST: ""
      SOCKS_PROXY_PORT: ""

**Comment by 2bstronger** [comment]
> > > > > 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果
> > > > 
> > > > 
> > > > 把（OPENAI_API_BASE_URL:）取消，使用以下就好了 SOCKS_PROXY_HOST: SOCKS_PROXY_PORT:
> > > 
> > > 
> > > 老哥能细说么,我也是这个问题，是把url填写到host位置，port写443么？
> > 
> > 
> > port只写端口，host写地址，具体看你代理服务器是哪个地址提供服务
> 
> 我很困扰啊，还不行，方便截一张您的容器环境配置的图么，麻烦了。

version: '3'

services:
test:
image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
ports:
- 3002:3002
environment:
# 二选一
OPENAI_API_KEY:
# OPENAI_API_BASE_URL: 'https://openapi.ssiic.com/'
SOCKS_PROXY_HOST: ""
SOCKS_PROXY_PORT: ""

**Comment by 2bstronger** [comment]
> > > > > 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果
> > > > 
> > > > 
> > > > 把（OPENAI_API_BASE_URL:）取消，使用以下就好了 SOCKS_PROXY_HOST: SOCKS_PROXY_PORT:
> > > 
> > > 
> > > 老哥能细说么,我也是这个问题，是把url填写到host位置，port写443么？
> > 
> > 
> > port只写端口，host写地址，具体看你代理服务器是哪个地址提供服务
> 
> 我很困扰啊，还不行，方便截一张您的容器环境配置的图么，麻烦了。

```yaml
version: '3'

services:
test:
image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
ports:
- 3002:3002
environment:
# 二选一
OPENAI_API_KEY:
# OPENAI_API_BASE_URL: 'https://openapi.ssiic.com/'
SOCKS_PROXY_HOST: ""
SOCKS_PROXY_PORT: ""
```

**Comment by BENBENBAI** [comment]
> > > > > > 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果
> > > > > 
> > > > > 
> > > > > 把（OPENAI_API_BASE_URL:）取消，使用以下就好了 SOCKS_PROXY_HOST: SOCKS_PROXY_PORT:
> > > > 
> > > > 
> > > > 老哥能细说么,我也是这个问题，是把url填写到host位置，port写443么？
> > > 
> > > 
> > > port只写端口，host写地址，具体看你代理服务器是哪个地址提供服务
> > 
> > 
> > 我很困扰啊，还不行，方便截一张您的容器环境配置的图么，麻烦了。
> 
> ```yaml
> version: '3'
> services:
>   test:
>     image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
>     ports:
>       - 3002:3002
>     environment:
>       # 二选一
>       OPENAI_API_KEY:
>       # OPENAI_API_BASE_URL: 'https://openapi.ssiic.com/'
>       SOCKS_PROXY_HOST: ""
>       SOCKS_PROXY_PORT: ""
> ```

我不用proxy都是主路由直接全局接管的，那我sock5部分直接省略？

**Comment by 2bstronger** [comment]
> > > > > > > 我也是使用docker部署，用ip:端口直接访问，但是没有打字效果
> > > > > > 
> > > > > > 
> > > > > > 把（OPENAI_API_BASE_URL:）取消，使用以下就好了 SOCKS_PROXY_HOST: SOCKS_PROXY_PORT:
> > > > > 
> > > > > 
> > > > > 老哥能细说么,我也是这个问题，是把url填写到host位置，port写443么？
> > > > 
> > > > 
> > > > port只写端口，host写地址，具体看你代理服务器是哪个地址提供服务
> > > 
> > > 
> > > 我很困扰啊，还不行，方便截一张您的容器环境配置的图么，麻烦了。
> > 
> > 
> > ```yaml
> > version: '3'
> > services:
> >   test:
> >     image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
> >     ports:
> >       - 3002:3002
> >     environment:
> >       # 二选一
> >       OPENAI_API_KEY:
> >       # OPENAI_API_BASE_URL: 'https://openapi.ssiic.com/'
> >       SOCKS_PROXY_HOST: ""
> >       SOCKS_PROXY_PORT: ""
> > ```
> 
> 我不用proxy都是主路由直接全局接管的，那我sock5部分直接省略？

按照你说的应该是的
