### ISSUE TITLE
请问，如何添加ssl证书呢

### ISSUE THREAD

**Issue by Cophe** [Chanzhaoyu/chatgpt-web#479]

**Comment by PeterDaveHello** [comment]
Ask ChatGPT?

**Comment by GH6324** [comment]
不是吧，这种问题也要来这里提issues么，建议你去问chatgpt或者百度。别说作者看了高血压，我们看了都要高血压了。。。

**Comment by Cophe** [comment]
> 不是吧，这种问题也要来这里提issues么，建议你去问chatgpt或者百度。别说作者看了高血压，我们看了都要高血压了。。。

请问把您气死了没？没有的话我在努努力

> Ask ChatGPT? (nginx ssl cert & config)

我现在是通过反向代理的方式实现的，我想的是这个需求是不是都有，可以放在配置选项中

**Comment by Cophe** [comment]
> 不是吧，这种问题也要来这里提issues么，建议你去问chatgpt或者百度。别说作者看了高血压，我们看了都要高血压了。。。

小屁孩阴阳怪气的，戾气这么重
