### ISSUE TITLE
不建议使用别人的反代地址，除非是自己实现搭建的

### ISSUE THREAD

**Issue by fireinrain** [Chanzhaoyu/chatgpt-web#481]
我前天使用反代地址，别人把我的accessToken去做公益了，收集别人的accessToken 然后去做其他的api用
希望大家注意一下。当使用accessToken被人获取之后，他用你的accessToken可以疯狂请求openai的接口
导致你这个accessToken 在正常的官网后会先Too many request in 1Hour。然后你的chat 列表 会多了好多
莫名的对话。

**Comment by fireinrain** [comment]
盗用者直接把我的accessToken给干废了
<img width="651" alt="image" src="https://user-images.githubusercontent.com/14249262/224460621-6b520ef5-19d1-4d8d-9dd4-788b844d13e0.png">

**Comment by Chanzhaoyu** [comment]
好的，你是用的社区的反代地址还是别人在 `issues` 中发出来的地址。

**Comment by Chanzhaoyu** [comment]
目前已经在 `README` 添加和 `issues` 中置顶

**Comment by yijiangchengming** [comment]
如何刷新accessToken

**Comment by fireinrain** [comment]
> 好的，你是用的社区的反代地址还是别人在 `issues` 中发出来的地址。

用的是在github上找的，但是当时我想赶快修改配置所以没有记录下来.
如果不是自己对反向代理的地址有比较透明的掌握，即不保存你的accessToken 都不太建议用
人心隔肚皮的

**Comment by fireinrain** [comment]
> 目前已经在 `README` 添加和 `issues` 中置顶

万分感谢

**Comment by kintong3000** [comment]
能不能把这个反代地址找出来，据我所知目前能实现反代就两个人，我觉得你是用了在他们的反代之上的反代。
