### ISSUE TITLE
Changing the openapi model does not work

### ISSUE THREAD

**Issue by spencerwongfeilong** [Chanzhaoyu/chatgpt-web#485]
Hello i change the openai model to "text-davinci-003" and got the followiwng results in the chat webgui

undefined
[ChatGPT error 404: {
"error": {
"message": "Invalid URL (POST /v1/chat/completions)",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
]

It seems that i need the backend endpoint need to be modified. How can i change that?

**Comment by spencerwongfeilong** [comment]
https://platform.openai.com/docs/models/gpt-3



![Capture](https://user-images.githubusercontent.com/127573355/224461147-17185f16-dae8-4b5f-babe-d0a606eb1172.PNG)

**Comment by Chanzhaoyu** [comment]
Currently only `gpt-3.5-turbo` and `gpt-3.5-turbo-0301` are supported.

**Comment by spencerwongfeilong** [comment]
thanks for the clarifications =D
