### ISSUE TITLE
警告！！！不要使用来路不明的代理！！！

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#488]
警告：

1. 你应该首先使用 `API` 方式。
2. 使用 `accessToken` 方式时反向代理将向第三方暴露您的访问令牌。这样做应该不会产生任何不良影响，但在使用这种方法之前请考虑风险，修改代理地址时也请使用公开的[社区方案](https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy)，不要不要不要使用来源不明的地址！
3. 因为国内 `API` 被墙，如果服务器不在国外，则需要代理才能请求到官方接口，也非常不建议使用别人发出来的代理地址，请自己搭建。
4. 虽然肯定是有乐于分享的大佬。但是，人性也是丑陋的，你永远不知道你乐于相信的人会用你的账号当免费工具！！！
5. 此项目所有源码和上游依赖都开源于 `GitHub` ，可以审查代码。

注：可能会在将来的版本中删除对 `ChatGPTUnofficialProxyAPI` 的支持。

**Comment by wlrwx** [comment]
我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。

**Comment by Chanzhaoyu** [comment]
> 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。

使用 `API` 不需要，服务器能请求到 `https://api.openai.com` 就可以

**Comment by HHhne** [comment]
用clash设置socks不好吗，实在不行自己搭个nginx反代也不费事

**Comment by wlrwx** [comment]
> > 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。
> 
> 使用 `API` 不需要，服务器能请求到 `https://api.openai.com` 就可以

API我也切换了，也一样是fetch failed，我也确定服务器是可以正常访问openai的。看日志你默认就走chat.duti.tech？

**Comment by Chanzhaoyu** [comment]
> > > 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。
> > 
> > 
> > 使用 `API` 不需要，服务器能请求到 `https://api.openai.com` 就可以
> 
> API我也切换了，也一样是fetch failed，我也确定服务器是可以正常访问openai的。看日志你默认就走chat.duti.tech？

`API` 默认是 `https://api.openai.com`
`accessToken` 默认是 `https://chat.openai.com/backend-api/conversation`

**Comment by Chanzhaoyu** [comment]
> 

`https://chat.duti.tech/api/conversation` 和 `https://gpt.pawan.krd/backend-api/conversation` 这个是社区反代，是值得信任的

**Comment by Chanzhaoyu** [comment]
> > > 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。
> > 
> > 
> > 使用 `API` 不需要，服务器能请求到 `https://api.openai.com` 就可以
> 
> API我也切换了，也一样是fetch failed，我也确定服务器是可以正常访问openai的。看日志你默认就走chat.duti.tech？

`https://chat.duti.tech/api/conversation` 是 [@acheong08](https://github.com/acheong08) 的，
`https://gpt.pawan.krd/backend-api/conversation` 是 [@PawanOsman](https://github.com/PawanOsman) 的，
这两个肯定是可以信任的

**Comment by wlrwx** [comment]
换了老版本，2.9,默认https://chat.duti.tech/api/conversation已经挂了，所以必须填写反代https://gpt.pawan.krd/backend-api/conversation不走默认的https://chat.duti.tech/api/conversation，正常了，先用着吧，新版2.10.*，一直都是fetch failed。

**Comment by wlrwx** [comment]
> 



> > > > 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。
> > > 
> > > 
> > > 使用 `API` 不需要，服务器能请求到 `https://api.openai.com` 就可以
> > 
> > 
> > API我也切换了，也一样是fetch failed，我也确定服务器是可以正常访问openai的。看日志你默认就走chat.duti.tech？
> 
> `https://chat.duti.tech/api/conversation` 是 [@acheong08](https://github.com/acheong08) 的， `https://gpt.pawan.krd/backend-api/conversation` 是 [@PawanOsman](https://github.com/PawanOsman) 的， 这两个肯定是可以信任的

已经换回老版本2.9，默认的chat.duti.tech代理已挂，2.10.*一直都是fetch failed，换回老版本，并填入gpt.pawan.krd一切正常了，不填反代默认就走chat.duti.tech，国内应该已挂，我服务器在国外，实际是不需要反代的。先用着了，新版本填了反代也不正常。

**Comment by 917931227** [comment]
> 警告：
> 
> 1. 你应该首先使用 `API` 方式。
> 2. 使用 `accessToken` 方式时反向代理将向第三方暴露您的访问令牌。这样做应该不会产生任何不良影响，但在使用这种方法之前请考虑风险，修改代理地址时也请使用公开的[社区方案](https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy)，不要不要不要使用来源不明的地址！
> 3. 因为国内 `API` 被墙，如果服务器不在国外，则需要代理才能请求到官方接口，也非常不建议使用别人发出来的代理地址，请自己搭建。
> 4. 虽然肯定是有乐于分享的大佬。但是，人性也是丑陋的，你永远不知道你乐于相信的人会用你的账号当免费工具！！！
> 5. 此项目所有源码和上游依赖都开源于 `GitHub` ，可以审查代码。
> 
> 注：可能会在将来的版本中删除对 `ChatGPTUnofficialProxyAPI` 的支持。

能否再加一个前端http://localhost:1003，把http://localhost:1002/的消息记录保存到数据库，写个后端把http://localhost:1003的请求和http://localhost:3002的响应通过数据库来交互。国内IP就可以直接访问http://localhost:1003发送请求和接收响应了，从而达到避开openai因政策限制而封号的风险！

**Comment by haofeiyan** [comment]
> 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。

我也遇到这个问题，不用docker，用pnpm在本地运行就没有fetch failed问题，奇了怪了

**Comment by CaptainYan2** [comment]
> 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。

我也遇到这个问题，不用docker，用pnpm在本地运行就没有fetch failed问题，奇了怪了

**Comment by kintong3000** [comment]
> > > > 我的服务器在国外，按理不需要反代吧？可现在一直都是fetch failed，换了账号也不行，切api也不行，accesstoken也不行，另外没必要删accesstoken，毕竟还有很多国外服务器的，反代风险提示就行吧。
> > > 
> > > 
> > > 使用 `API` 不需要，服务器能请求到 `https://api.openai.com` 就可以
> > 
> > 
> > API我也切换了，也一样是fetch failed，我也确定服务器是可以正常访问openai的。看日志你默认就走chat.duti.tech？
> 
> `https://chat.duti.tech/api/conversation` 是 [@acheong08](https://github.com/acheong08) 的， `https://gpt.pawan.krd/backend-api/conversation` 是 [@PawanOsman](https://github.com/PawanOsman) 的， 这两个肯定是可以信任的

acheong的地址改了

**Comment by kintong3000** [comment]
> 个问题，不用docker，用pn

你好像不知道为什么需要反代
