### ISSUE TITLE
求助，阿里云香港服务器 “chatgpt-web:latest not found”

### ISSUE THREAD

**Issue by Tianchen627** [Chanzhaoyu/chatgpt-web#489]
Pulling app (chenzhaoyu94/chatgpt-web:)...
Trying to pull repository docker.io/chenzhaoyu94/chatgpt-web ...
ERROR: manifest for docker.io/chenzhaoyu94/chatgpt-web:latest not found

问下有大佬知道如何解决这个问题么？同样docker pull也是没有。

**Comment by 917931227** [comment]
阿里云香港服务器会封号

**Comment by RoadMillion** [comment]
我在https://hub.docker.com/ 自己建了一个仓库，从能拉到镜像的机器，推送到自己的仓库里。
现在从其他机器可以拉取到镜像，但是后续更新比较麻烦。
docker1451871636/chatgpt-web:latest

**Comment by liujianchen2013** [comment]
我也遇到了同样的问题，有人解决了吗？
