### ISSUE TITLE
使用token，使用sock代理，只填了地址和端口，没找到填写https://chat.openai.com/backend-api/conversation的地方

### ISSUE THREAD

**Issue by jiaqp** [Chanzhaoyu/chatgpt-web#492]
然后启动项目弹出错误：

undefined
[request to https://chat.duti.tech/api/conversation failed, reason: Client network socket disconnected before secure TLS connection was established]

作者默认了https://chat.duti.tech/api/conversation，在哪个文件修改

**Comment by HaanJam** [comment]
# service/.env
API_REVERSE_PROXY=

**Comment by jiaqp** [comment]
> # service/.env
> API_REVERSE_PROXY=

意思是sock也用反向代理的URL吗
