### ISSUE TITLE
代理怎么搭建呢，哪位大佬给个教程

### ISSUE THREAD

**Issue by 1715819** [Chanzhaoyu/chatgpt-web#494]

**Comment by fjiabinc** [comment]
如题,确实需要这个代理方案

**Comment by ludashi2020** [comment]
需要plus订阅，没法白嫖

**Comment by silversuncn** [comment]
> 需要plus订阅，没法白嫖

能详细解释下么

**Comment by rhymed-liu** [comment]
先有个翻墙的机器,然后搭建宝塔(因为搭建好宝塔后就可以纯页面操作),宝塔安装nginx,安装好nginx后就按下面步骤走
1.
![image](https://user-images.githubusercontent.com/37588640/224590438-15f416da-5978-40f1-b3a6-0a49272e4714.png)
2.
![image](https://user-images.githubusercontent.com/37588640/224590511-c1c26fa5-ae4a-4bbf-8fa4-024c9e6ce8ad.png)
3.编辑配置文件以实现打字机效果
![image](https://user-images.githubusercontent.com/37588640/224590557-98f2b0cf-e315-4851-930f-4d1119da9d9c.png)

**Comment by rhymed-liu** [comment]
这个的话就需要sockt代理了,你可以看看这个https://www.qdcto.com/archives/492

**Comment by pepsigold** [comment]
感谢分享！！！

**Comment by pepsigold** [comment]
> 先有个翻墙的机器,然后搭建宝塔(因为搭建好宝塔后就可以纯页面操作),宝塔安装nginx,安装好nginx后就按下面步骤走 1. ![image](https://user-images.githubusercontent.com/37588640/224590438-15f416da-5978-40f1-b3a6-0a49272e4714.png) 2. ![image](https://user-images.githubusercontent.com/37588640/224590652-d6292264-8d16-44c3-abd0-b3ddceb18fe1.png)
> 
> 3.编辑配置文件以实现打字机效果 ![image](https://user-images.githubusercontent.com/37588640/224590557-98f2b0cf-e315-4851-930f-4d1119da9d9c.png)
感谢大佬分享。
