### ISSUE TITLE
给个UI建议

### ISSUE THREAD

**Issue by zhxuri** [Chanzhaoyu/chatgpt-web#495]
界面右下角的设置打开的设置窗口，没有关闭按钮，需要点窗口外空白处关闭，其实很多人是不知道点窗口空白处关闭的，我给朋友用，我看他们竟然是通过点刷新来关闭窗口，特别是手机打开的情况下，手机打开窗口之外的空白处是很小，屏幕小点的手机就只有一点边边，说以手机更需要有这个关闭按钮。

![Screenshot 2023-03-11 150541](https://user-images.githubusercontent.com/11741854/224470686-d6334a7c-e06d-4da6-a408-75a5af322105.png)
![Screenshot 2023-03-11 145556](https://user-images.githubusercontent.com/11741854/224470689-d3805484-c20d-4c1c-a29e-1917defa2104.png)

**Comment by zhxuri** [comment]
手机我是用iphone打开的，按我屏幕的大小可以触发关闭的空白处就只有一点边边而已

**Comment by Chanzhaoyu** [comment]
已修复

**Comment by zhxuri** [comment]
速度真快
