### ISSUE TITLE
Feature request: 支持部署到vercel serverless function中

### ISSUE THREAD

**Issue by linesoft2** [Chanzhaoyu/chatgpt-web#498]
这样可以让用户方便，更低成本（甚至免费）部署本项目。
如果可以，我愿意提交PR参与贡献。

**Comment by wuzhijie0101** [comment]
同求

**Comment by JiangZongKang** [comment]
同求

**Comment by baby9** [comment]
> 这样可以让用户方便，更低成本（甚至免费）部署本项目。 如果可以，我愿意提交PR参与贡献。

大佬快出个部署教程，前面有好几个issue提出过vercel部署请求了

**Comment by linesoft2** [comment]
> > 这样可以让用户方便，更低成本（甚至免费）部署本项目。 如果可以，我愿意提交PR参与贡献。
> 
> 大佬快出个部署教程，前面有好几个issue提出过vercel部署请求了

需要修改代码

**Comment by baby9** [comment]
> > > 这样可以让用户方便，更低成本（甚至免费）部署本项目。 如果可以，我愿意提交PR参与贡献。
> > 
> > 
> > 大佬快出个部署教程，前面有好几个issue提出过vercel部署请求了
> 
> 需要修改代码

大佬fork一个，我去给你点star

**Comment by linesoft2** [comment]
> > > > 这样可以让用户方便，更低成本（甚至免费）部署本项目。 如果可以，我愿意提交PR参与贡献。
> > > 
> > > 
> > > 大佬快出个部署教程，前面有好几个issue提出过vercel部署请求了
> > 
> > 
> > 需要修改代码
> 
> 大佬fork一个，我去给你点star

还是在原仓库改比较好吧，要不收不到后面更新了
