### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by wangzhaolun** [Chanzhaoyu/chatgpt-web#5]
The build is complete, and the apikey is also added, why is it prompted Network Error

**Comment by Chanzhaoyu** [comment]
你需要开启一个 `node` 服务

**Comment by renny-ren** [comment]
[demo page](https://chatgpt-bot-peach.vercel.app/) 也 Network Error 了

**Comment by Chanzhaoyu** [comment]
> [demo page](https://chatgpt-bot-peach.vercel.app/) 也 Network Error 了

因为我没有开启服务，有 18 美金的上线

**Comment by Imbalancer** [comment]
请问，本地端口1002是有网络的，服务器端口1002没有网络是为什么呢。

**Comment by wangzhaolun** [comment]
按照教程一步步的完成，后台运行了服务和网页，填写了API
3002访问提示Cannot GET /
1002访问正常，提问后Network Error
请问是哪里出错？

**Comment by Chanzhaoyu** [comment]
@Imbalancer  @wangzhaolun 

可能没有写清楚，因为这个后端服务是用 `node` 写的
所以需要复制文件到服务器上的一个文件夹内使用 `pnpm service` 运行。
可能对不了解前端的来说是有点迷惑，我修改下 `README.MD`

**Comment by Imbalancer** [comment]
pnpm service后3002端口打开，但是实际访问还是只能1002本地端口

**Comment by Imbalancer** [comment]
服务器测试 localhost:1002和10.0.4.13:1002是提问正常，但是开放1002端口后，公网ip的1002端是提问错误，这些前提是pnpm service正常运行3002端口的，请问该如何让公网接口也正常访问呢

**Comment by Siri-Li** [comment]
本地win测试正常，服务器centos8 Network Error
