### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by cghk002** [Chanzhaoyu/chatgpt-web#50]
配置过全局API和service里的API了,但是发送消息就报错

**Comment by a8dog** [comment]
404就是后端端api不存在啊，要么你填写错误了，要么你没有跑起来

**Comment by Siri-Li** [comment]
前端build 后有一样的报错， dev就可以，是啥问题呢，后端是好的

**Comment by Siri-Li** [comment]
`    location /api{
        proxy_pass http://127.0.0.1:3002;
    }`

**Comment by cghk002** [comment]
> 

我这里没有127.0.0.1这个地址,我的两个.env文件里都是localhost:3002

**Comment by cghk002** [comment]
我是将release在服务器上解压,然后直接在service文件夹内pnpm start后端,然后根目录pnpm dev的

**Comment by cghk002** [comment]
> ` location /api{ proxy_pass http://127.0.0.1:3002; }`
> 404就是后端端api不存在啊，要么你填写错误了，要么你没有跑起来

我这里没有127.0.0.1这个地址,我的两个.env文件里都是localhost:3002
我是将release在服务器上解压,然后直接在service文件夹内pnpm start后端,然后根目录pnpm dev的

**Comment by Chanzhaoyu** [comment]
> > ` location /api{ proxy_pass http://127.0.0.1:3002; }`
> > 404就是后端端api不存在啊，要么你填写错误了，要么你没有跑起来
> 
> 我这里没有127.0.0.1这个地址,我的两个.env文件里都是localhost:3002 我是将release在服务器上解压,然后直接在service文件夹内pnpm start后端,然后根目录pnpm dev的

去根目录下 `.env` 文件改成你实际的 `IP` 地址

**Comment by cghk002** [comment]
![屏幕截图_20230219_161153](https://user-images.githubusercontent.com/49087345/219936758-06c6a8ad-3087-43f6-988a-6b4e68db9549.png)
使用实际IP也没用...

**Comment by cghk002** [comment]
![image](https://user-images.githubusercontent.com/49087345/219936857-3f01b676-4ab3-4034-a48f-f3321414162a.png)
直接访问后端的3002也有响应

**Comment by cghk002** [comment]
我的问题,我把根目录的.env中的VITE_GLOB_API_URL填上了我的API,恢复默认值就好了,service中的.env的localhost可以不用改
