### ISSUE TITLE
chatGPT当前回答是直至2021年9月吗？

### ISSUE THREAD

**Issue by Xmaspro** [Chanzhaoyu/chatgpt-web#504]
![IMG_F4A04EDFA3C6-1](https://user-images.githubusercontent.com/61029176/224480503-fd32d22d-16ec-4f66-94a2-bce429024d6d.jpeg)
是否有办法回答基于最新数据的答案？

**Comment by Chanzhaoyu** [comment]
chatgpt/index.ts 中自己修改 systemMessage

**Comment by Xmaspro** [comment]
> 

是service/src/chatgpt 下的index.ts吗？
这个文件里没有systemMessage，请问能再看下吗，谢谢。

**Comment by xiaosaaaa** [comment]
没找到systemMessage
