### ISSUE TITLE
为什么没有用全天全时段也在不断的消耗token？

### ISSUE THREAD

**Issue by zhanhuajie** [Chanzhaoyu/chatgpt-web#506]
![image](https://user-images.githubusercontent.com/13690777/224481756-cbf4ecbd-615e-40f4-a0ba-f0e027fe07ae.png)

![image](https://user-images.githubusercontent.com/13690777/224481725-784ba4f8-917a-434b-9532-fe46694b2104.png)

**Comment by Chanzhaoyu** [comment]
用的社区的反代还是别人发的？

**Comment by jiaqp** [comment]
你登陆下你的账号看看有没有新的会话，很有可能是你的token被别人用了，或者你把你的网站发出去别人在用

**Comment by Chanzhaoyu** [comment]
1、用的别人的代理，被人记录私用了
2、发布到公网，没有加权限，被人刷了

**Comment by zhanhuajie** [comment]
![image](https://user-images.githubusercontent.com/13690777/224484942-c4bbf082-de63-4c59-a703-abb0ecfc806f.png)
找到原因了，公网没加权限，被盗刷了。。。
