### ISSUE TITLE
docker版如何实现访问权限控制？

### ISSUE THREAD

**Issue by 7noemo** [Chanzhaoyu/chatgpt-web#509]
如题，docker版每次改了配置的logo说明什么的总是被重置。

**Comment by AONE-Y** [comment]
docker的镜像还没更新，我看最近更新都是七天前，所以没权限控制

**Comment by Chanzhaoyu** [comment]
不对啊，docker 都是自动同步的啊，而且 2.10.0 之后已经合并了权限分支。

**Comment by luuziiyoo** [comment]
我用的docker都更新到2.10.4

**Comment by richadlee** [comment]
小白问下 怎么更新已启动的docker容器,必须删掉重新拉镜像建立吗

**Comment by jbang20042004** [comment]
> 不对啊，docker 都是自动同步的啊，而且 2.10.0 之后已经合并了权限分支。

同问，我已经建好了镜像，弄好了网页，怎么更新里面的配置？

**Comment by bs10081** [comment]
> > 不对啊，docker 都是自动同步的啊，而且 2.10.0 之后已经合并了权限分支。
> 
> 同问，我已经建好了镜像，弄好了网页，怎么更新里面的配置？



> 小白问下 怎么更新已启动的docker容器,必须删掉重新拉镜像建立吗

先 `docker-compose down`，然後重新 Pull image，再 `docker-compose up -d` 即可。

**Comment by richadlee** [comment]
> > > 不对啊，docker 都是自动同步的啊，而且 2.10.0 之后已经合并了权限分支。
> > 
> > 
> > 同问，我已经建好了镜像，弄好了网页，怎么更新里面的配置？
> 
> > 小白问下 怎么更新已启动的docker容器,必须删掉重新拉镜像建立吗
> 
> 先 `docker-compose down`，然後重新 Pull image，再 `docker-compose up -d` 即可。

找到方法了 用 watchtower监测更新

**Comment by tjsky** [comment]
> 小白问下 怎么更新已启动的docker容器,必须删掉重新拉镜像建立吗

如果想自己手动就是先

```shell
docker-compose down
docker-compose pull
docker-compose up -d
```
