### ISSUE TITLE
有没有办法做成爬网页版而不是调用目前智能化比较落后的api

### ISSUE THREAD

**Issue by mobile17682318557** [Chanzhaoyu/chatgpt-web#51]
目前跟网页版智能化差距很大，写的文章非常不行，没有办法用，只有网页版的有使用价值

**Comment by a8dog** [comment]
等等官方放新的api，目前官方的网页版又是cf的验证，又是他自己的验证，体验一点都不好

**Comment by Chanzhaoyu** [comment]
有个 `py` 的项目，你可以自己接。访问网页 `api` 不稳定，要翻墙还有验证

**Comment by mobile17682318557** [comment]
> 等等官方放新的api，目前官方的网页版又是cf的验证，又是他自己的验证，体验一点都不好

网页端的会开放吗，官方有计划吗

**Comment by chenyuxiangyes** [comment]
有的，GPT-3.5。

**Comment by chenyuxiangyes** [comment]
ChatGPT is coming to our API soon, sign up to stay updated.
https://platform.openai.com/overview

**Comment by gygy** [comment]
+1，使用爬网页版模拟登录web是一个比较好的方式

**Comment by Chanzhaoyu** [comment]
已添加网页的方式，不过 `accessToken` 一般只有 8 小时，不太稳定

**Comment by dayunnas** [comment]
> 已添加网页的方式，不过 `accessToken` 一般只有 8 小时，不太稳定

docker同步更新了吗？

**Comment by Chanzhaoyu** [comment]
> 

已更新，但是我自用的话，体验不好

**Comment by Chanzhaoyu** [comment]
> > 已添加网页的方式，不过 `accessToken` 一般只有 8 小时，不太稳定
> 
> docker同步更新了吗？

已同步，自用感觉不稳定

**Comment by dayunnas** [comment]
> > > 已添加网页的方式，不过 `accessToken` 一般只有 8 小时，不太稳定
> > 
> > 
> > docker同步更新了吗？
> 
> 已同步，自用感觉不稳定

那暂时不更新了，等稳定了在更新，GPT3目前够用

**Comment by Chanzhaoyu** [comment]
> > > > 已添加网页的方式，不过 `accessToken` 一般只有 8 小时，不太稳定
> > > 
> > > 
> > > docker同步更新了吗？
> > 
> > 
> > 已同步，自用感觉不稳定
> 
> 那暂时不更新了，等稳定了在更新，GPT3目前够用

可以同步，不影响现在的 API，可选参数
