### ISSUE TITLE
在清空聊天内容时，能否不要清空左边的标签中的内容

### ISSUE THREAD

**Issue by eureka176** [Chanzhaoyu/chatgpt-web#510]
现象：点击聊天页面中的清除会话按钮后，页面左边对应标签的标题也被清掉了。
左边chat标签中的标题是允许修改的，一旦改好了以后应该被保存下来，不应该被“清除会话功能”清除。

**Comment by Chanzhaoyu** [comment]
啊…好难办，有些说要清空，有些又不清空

**Comment by Chanzhaoyu** [comment]
已改
