### ISSUE TITLE
Feature request: Support to search prompts in the Prompt Store among many of them.

### ISSUE THREAD

**Issue by PeterDaveHello** [Chanzhaoyu/chatgpt-web#514]
After imported awesome-chatgpt-prompts-zh from the default online import list, there are so many prompts in the store, with many pages, which may need you to turn the pages many times to find the one you need. A simple search could be very helpful in the scenario.

![image](https://user-images.githubusercontent.com/3691490/224491883-abbc143d-4cf9-4117-8827-c5e6667c6a5f.png)

**Comment by wwlmm** [comment]
You can directly call it by entering the symbol "/" in the input box. However, adding a search function to this page is also necessary.

**Comment by PeterDaveHello** [comment]
I believe it's done in af76b89fd4eb64f0d0056a8e62252fd9248d993e 👍
