### ISSUE TITLE
求助 undefined[fetch failed ]错误解决办法

### ISSUE THREAD

**Issue by kuxingdu** [Chanzhaoyu/chatgpt-web#515]
![mmexport1678550321508.png](https://user-images.githubusercontent.com/125985887/224494610-071694a9-4d3d-4636-8808-420a8cd6968d.png)

配置如下：API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation  
另外使用token如何配置呀

**Comment by kuxingdu** [comment]
@Chanzhaoyu 大大，能不能帮忙看一下

**Comment by wuzhijie0101** [comment]
用token 才用API_REVERSE_PROXY，你用api的话就用OPENAI_API_BASE_URL

**Comment by kuxingdu** [comment]
> 用token 才用API_REVERSE_PROXY，你用api的话就用OPENAI_API_BASE_URL
用api也不行，有啥解决办法嘛

**Comment by Chanzhaoyu** [comment]
> 用token 才用API_REVERSE_PROXY，你用api的话就用OPENAI_API_BASE_URL
> 用api也不行，有啥解决办法嘛

API 是被墙了，你要想办法代理

**Comment by kuxingdu** [comment]
> > 用token 才用API_REVERSE_PROXY，你用api的话就用OPENAI_API_BASE_URL
> > 用api也不行，有啥解决办法嘛
> 
> API 是被墙了，你要想办法代理

社区的两个代理我试了下，好像也不行😳

**Comment by jbang2004** [comment]
> 

大大，我也是这样，已经挂好代理了，而且我在本地直接python里import openai是成功的，但这个项目就是死活不成功，service/.env里已经配好api了，是否还有其他要注意的？

**Comment by terranc** [comment]
直接railway构建的也是提示这个。

**Comment by devinglaw** [comment]
API KEY报错，本来正常的KEY反复报错，开始能使用，刷新网页一次就报错，要重新SUDO修改，代码有BUG

**Comment by devinglaw** [comment]
根本不可能被墙，我用3.7.1老版就没问题，用最新版本就是BUG，应该是系统代码有问题缺陷
