### ISSUE TITLE
[Improvements] recommend.json 里的URL来自两个作者的仓库（自定义在线模板）

### ISSUE THREAD

**Issue by simonwu53** [Chanzhaoyu/chatgpt-web#516]
目前的在线模板来自src/assets/recommend.json文件

```json
{
  "key": "awesome-chatgpt-prompts-zh",
  "desc": "ChatGPT 中文调教指南",
  "downloadUrl": "https://raw.githubusercontent.com/Nothing1024/chatgpt-prompt-collection/main/awesome-chatgpt-prompts-zh.json",
  "url": "https://github.com/PlexPt/awesome-chatgpt-prompts-zh"
}
```

其中`downloadUrl`用的是“Nothing1024”的配置，而`url`给的项目地址是“PlexPt”的仓库。本来没什么，但是在我想参考他们的模板来做自己的在线prompts的时候，发现他们两个仓库用的模板是**不一样**的！

本项目代码用的是“Nothing1024”的配置模板，每个prompt字典里的key是`key`和`value`两个。而“PlexPt”的模板用的key是`act`和`prompt`（如果取他的模板的raw地址导入会报错并导致**prompt商店无法打开**直到清空cookie重置所有记录）。

以下是正确的prompt模板（务必用“key”和“value”）：
```json
[
  {
    "key": "prompt提示词",
    "value": "prompt内容"
  }
]
```

最后，如果导入其他人做的在线模板，也最好看一下他们的模板是不是用“key”和“value”作为prompt字典key的，否则就要重制网页cookie了😅

**Comment by Nothing1024** [comment]
你好，我是prompt部分的PR提交者，我简单解释一下吧。
1. 两个仓库不一样的内容是因为我在进行prompt部分调试时，原项目还没有上传JSON文件（可以参考他们的update日期），只有md文档，所有的文档内容其实是我通过官方的readme手动收集爬取处理的。而且目前该文件主要是为了部署者进行自定义设置演示，感兴趣可以自己进行修改。
2. prompt导入这个问题确实是我的问题，我在提交pr时没有成功提交`key`和`value`的检测处理（逻辑应是 如果检测JSON格式错误或者是没有对应键值会报错， 目前后者没有检测），今天下午我会尝试添加相关部分
3. 具体的导入模板可参考我当时提交的PR
https://github.com/Chanzhaoyu/chatgpt-web/pull/268

**Comment by xiaosaaaa** [comment]
速度够快的

**Comment by HHhne** [comment]
> 你好，我是prompt部分的PR提交者，我简单解释一下吧。
> 
>     1. 两个仓库不一样的内容是因为我在进行prompt部分调试时，原项目还没有上传JSON文件（可以参考他们的update日期），只有md文档，所有的文档内容其实是我通过官方的readme手动收集爬取处理的。而且目前该文件主要是为了部署者进行自定义设置演示，感兴趣可以自己进行修改。
> 
>     2. prompt导入这个问题确实是我的问题，我在提交pr时没有成功提交`key`和`value`的检测处理（逻辑应是 如果检测JSON格式错误或者是没有对应键值会报错， 目前后者没有检测），今天下午我会尝试添加相关部分
> 
>     3. 具体的导入模板可参考我当时提交的PR
>        [feat: 添加Prompt模板和Prompt商店支持 #268](https://github.com/Chanzhaoyu/chatgpt-web/pull/268)

来个json的github反代地址，或用下gitee这样子的吧，移动端不挂梯用不了

**Comment by Chanzhaoyu** [comment]
> 比较好奇模板可以固定一种职业性格一直使用吗？直到手动切换为另外一种性格。
> 还是说有时限性？超过一段时间就会变为默认。

没有做这个，不过你可以手动设定

**Comment by i-iooi-i** [comment]
> > 比较好奇模板可以固定一种职业性格一直使用吗？直到手动切换为另外一种性格。
> > 还是说有时限性？超过一段时间就会变为默认。
> 
> 没有做这个，不过你可以手动设定

感谢大佬，我在超时变量里设定个时间看看。
