### ISSUE TITLE
请教直接在VPS上搭建后端出现“Cannot GET /”错误，前端一直在等待页面问题。

### ISSUE THREAD

**Issue by wansenlyt** [Chanzhaoyu/chatgpt-web#517]
本人门外汉一个，如有描述不准确的地方还请多包涵。
        VPS在国外，系统为Debian11X64，之前使用https://github.com/kirin10000/Xray-script/raw/main/Xray-TLS+Web-setup.sh这个脚本搭建了cloudreve服务及Xray服务，Xray服务使用正常。用Docker compose搭建chatgpt-web通过http://IP:3002/可以正常使用，考虑到这样直接访问不安全，又因为自己水平太差，想着通过宿主机Nginx反代容器内chatgpt-web应用，查了很多资料，也通过chatgpt-web查询，结果一直无法反代成功，所以就想着不通过docker搭建，直接在宿主机上搭建，搭建过程如下：
----------------------------------------------------------------------------------
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.bashrc && nvm --version
source ~/.bashrc && nvm install v18.15.0 && node -v
npm install unfetch && npm i unfetch
npm install pnpm -g
cd /home && git clone https://github.com/Chanzhaoyu/chatgpt-web
cd /home/chatgpt-web*
nano /home/chatgpt-web/service/.env
cd /home/chatgpt-web*/service && pnpm install
cd .. && pnpm bootstrap
source ~/.bashrc && cd /home/chatgpt-web*/service && pnpm start
source ~/.bashrc && cd /home/chatgpt-web* && pnpm dev
----------------------------------------------------------------------------------
搭建完成，在浏览器内打开http://IP:3002/，网页提示错误：Cannot GET /
在浏览器内打开http://IP:1002/，网页一直是三个等待球晃来晃去。

如有高人或搭建成功者指点一、二，不胜感激！

**Comment by baby9** [comment]
估计你只会用一件脚本吧，readme里面有一个部署在railway的示例，你部署到railway就好了

**Comment by nagaame** [comment]
`service`后端文件夹里边需要有`.env`文件, 你把example复制, 然后配置好, 再试试

**Comment by wansenlyt** [comment]
> 估计你只会用一键脚本吧，readme里面有一个部署在railway的示例，你部署到railway就好了

是的，会点基本的Lunix命令

**Comment by wansenlyt** [comment]
> `service`后端文件夹里边需要有`.env`文件, 你把example复制, 然后配置好, 再试试

已参考docker内配置进行了相应配置

**Comment by wansenlyt** [comment]
> `service`后端文件夹里边需要有`.env`文件, 你把example复制, 然后配置好, 再试试

已参考docker内配置进行了相应配置

**Comment by chiao666** [comment]
我也有这个情况诶，请问解决了吗

**Comment by xiwei26** [comment]
我也是这个情况。。。所以后来换成了docker-compose

**Comment by wansenlyt** [comment]
> 我也有这个情况诶，请问解决了吗

没有

**Comment by DDToms** [comment]
解决了吗 同

**Comment by DreamArc77** [comment]
我这边成功了，应该是用[http://IP:1002/]访问，三个球一直加载可以看下浏览器的console输出
