### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by aijumpx** [Chanzhaoyu/chatgpt-web#52]
我在页面大约三秒就会返回Request failed with status code 502.但是docker logs 里面是有应答的。

app_1  | Server is running on port 3002
app_1  | upsertMessage 3e4eda8e-8a4d-4534-b9a7-e8c8916c2de2 {
app_1  |   role: 'user',
app_1  |   id: '3e4eda8e-8a4d-4534-b9a7-e8c8916c2de2',
app_1  |   parentMessageId: undefined,
app_1  |   conversationId: '841f86c7-4cdd-4996-87ca-f337286f88f9',
app_1  |   text: '你知道tiktok吗？'
app_1  | }
app_1  | upsertMessage cmpl-6kppdi7YrxjLR7pIpmkbM5DZDBHdp {
app_1  |   role: 'assistant',
app_1  |   id: 'cmpl-6kppdi7YrxjLR7pIpmkbM5DZDBHdp',
app_1  |   parentMessageId: '3e4eda8e-8a4d-4534-b9a7-e8c8916c2de2',
app_1  |   conversationId: '841f86c7-4cdd-4996-87ca-f337286f88f9',
app_1  |   text: '当然！ TikTok是一个流行的社交媒体应用，它可以让你创建和共享精彩视频。',
app_1  |   detail: {
app_1  |     id: 'cmpl-6kppdi7YrxjLR7pIpmkbM5DZDBHdp',
app_1  |     object: 'text_completion',
app_1  |     created: 1676620349,
app_1  |     model: 'text-davinci-003',
app_1  |     choices: [ [Object] ],
app_1  |     usage: { prompt_tokens: 72, completion_tokens: 70, total_tokens: 142 }
app_1  |   }
app_1  | }

**Comment by Chanzhaoyu** [comment]
已修复过
