### ISSUE TITLE
我的API应该是被盗用了...

### ISSUE THREAD

**Issue by lion-goose** [Chanzhaoyu/chatgpt-web#528]
中午在外面收到邮件，说API被限制了，然后就发现昨天到今天上午一直在跑，直接给我18刀额度跑没了。我自己才用了0点几，气死我了
![1](https://user-images.githubusercontent.com/59443350/224531585-c1da4ee0-6563-4448-a66c-b81c91dc80f9.png)
![2](https://user-images.githubusercontent.com/59443350/224531587-fe11062d-ff88-4bfe-8830-20b0e3e09081.png)
![3](https://user-images.githubusercontent.com/59443350/224531590-da25066d-5c6c-4f44-afd7-f5f5c7378111.png)
然后我看到官网上数不清的new chat,每一个都一样，这是什么鬼啊
![4](https://user-images.githubusercontent.com/59443350/224531858-e41eb128-4f10-448e-9632-cebf0bec3686.png)
然后我改了ChatGPTUnofficialProxyAPI，发现还在跑，没几分钟又增加了好多new chat
然后我又在nginx的配置里加了需要密码打开页面，然后我把docker停掉，等了半小时，发现停了，没有再增加新的了。
但是，我启动docker，没过一会儿，又跑了一堆出来，这可咋整啊...我被盯住了啊

**Comment by Chanzhaoyu** [comment]
1. 放公网一定要加权限，项目自带！
2. Token 的反代只用社区的，别用别人的，目前就社区的两个反代是可靠的！
3. API 别用别人的代理，自己搭建！

**Comment by lion-goose** [comment]
> 1. 放公网一定要加权限，项目自带！
> 2. Token 的反代只用社区的，别用别人的，目前就社区的两个反代是可靠的！
> 3. API 别用别人的代理，自己搭建！

擦擦擦，才看到可以加访问权限密钥...

**Comment by 129duckflew** [comment]
请问如何加访问权限秘钥？

**Comment by imdingtalk** [comment]
> 请问如何加访问权限秘钥？

AUTH_SECRET_KEY 加这变量

**Comment by NeedforGit** [comment]
请问使用 Docker compose 如何加访问权限密钥？

**Comment by NeedforGit** [comment]
> > 请问使用 Docker compose 如何加访问权限密钥？
> 
> ```
> environment:
>   # 访问权限密钥，可选
>   AUTH_SECRET_KEY: xxx
> ```

感谢，但我试了一下，并没有让我输密码，docker compose 如下：

version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web:latest
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: xxxxx
      AUTH_SECRET_KEY: 0000

请问哪里出了问题？
