### ISSUE TITLE
加了端口映射后，卡死在加载页面

### ISSUE THREAD

**Issue by aephi** [Chanzhaoyu/chatgpt-web#529]
我在apache2里，将my.website/chat 映射到了 my.website:1002
通过端口 my.website:1002可以正常使用，
但是通过my.website/chat访问，会卡死在绿色小球的界面。
求原因

**Comment by CaptainYan2** [comment]
从apache2的access log可能能看到原因，我昨天也想用nginx proxy manager实现这个，怎么改都不好使，会有error找不到正确路径。后来我直接创多个dns解析实现对应多端口服务。

**Comment by aephi** [comment]
> 从apache2的access log可能能看到原因，我昨天也想用nginx proxy manager实现这个，怎么改都不好使，会有error找不到正确路径。后来我直接创多个dns解析实现对应多端口服务。

应该是已经正确映射了，access_log里面没有异常。
因为这个框架太复杂了，我没有前端经验，不知道具体卡在哪里了，没法加日志。
dns解析如何设置？是在域名服务商设置吗，我的似乎不支持映射到端口，没有腾讯云阿里云那种“显示URL”“隐式URL”的DNS记录

**Comment by aephi** [comment]
> 从apache2的access log可能能看到原因，我昨天也想用nginx proxy manager实现这个，怎么改都不好使，会有error找不到正确路径。后来我直接创多个dns解析实现对应多端口服务。

也可以，域名服务商支持的话
