### ISSUE TITLE
给 chatgpt-web 写了个 utools 插件

### ISSUE THREAD

**Issue by ChandlerVer5** [Chanzhaoyu/chatgpt-web#532]
写了个 chatgpt-web 版本的 utools 插件。本地跑，随用随走，给需要的人。
release 有 upx 下载
地址：[utools-plugin-chat](https://github.com/ChandlerVer5/utools-plugin-chat/)

> 尤其适合那些只想啪啪配置几个参数，又不想搞个网页的人

**Comment by love520222** [comment]
大佬

**Comment by chenjunhua8080** [comment]
666

**Comment by nuoooo** [comment]
niu

**Comment by tiro8183** [comment]
插件市场搜不到

**Comment by ChandlerVer5** [comment]
> 插件市场搜不到

我的所有插件，基本都不发布，一般都是自己开发自己用，当然了也全是开源的。
你可以去插件市场发布，我可以提供 编译后的包
