### ISSUE TITLE
存在乱码问题

### ISSUE THREAD

**Issue by yangyucitrus** [Chanzhaoyu/chatgpt-web#537]
输入字符超过大概50字就会出现乱码（无论中英文字符）应该不是nginx配置的问题，通过ip+端口访问问题依然存在，控制台里显示“content-type: application/json”但是我已经修改其为“text/event-stream; charset=utf-8“，并未生效，希望作者大大能解决下这个问题。
![屏幕截图 2023-03-12 212556](https://user-images.githubusercontent.com/101451798/224547862-519023f3-04e2-4aff-9f2e-358b123539b9.png)

**Comment by ludashi2020** [comment]
我也遇到乱码了。版本是2.10.5

**Comment by yangyucitrus** [comment]
兄弟你是不是修改了模型的参数了，我是修改了`service/src/chargpt/index.ts`里面模型参数设置出错导致的，你要是同样的问题可以先把修改的部分改回去再部署一次看看。
