### ISSUE TITLE
pwa无法正常工作，求指点

### ISSUE THREAD

**Issue by pzcn** [Chanzhaoyu/chatgpt-web#539]
目前是nginx反代端口，已经配置https，lighthouse提示这个问题
![image](https://user-images.githubusercontent.com/29601158/224548799-396a57f6-00fb-47bd-8117-15dd9a353bca.png)
直接访问端口，除了上述问题之外，还存在ssl问题。所以我目前没有找到问题的原因。求大佬们指点

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/224744137-7c5a7fc8-1b43-40f0-b9e5-847875721acd.png)
检查一下你的清单配置

**Comment by pzcn** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/224744137-7c5a7fc8-1b43-40f0-b9e5-847875721acd.png) 检查一下你的清单配置

这需要自己去修改吗

**Comment by chenxch** [comment]
默认是不用的，我这个就是默认的

**Comment by chenxch** [comment]
你可以发一下你的浏览器和系统信息么

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/224747562-0cd1d526-9a23-494a-9e2b-7e6c77e921eb.png)
我mac测试了下也是可以的，你把错误信息展开下

**Comment by pzcn** [comment]
![image](https://user-images.githubusercontent.com/29601158/224748656-5b51c1e4-b0e3-4218-8891-583e233551ae.png)

**Comment by chenxch** [comment]
你是部署哪个版本的chatgpt-web，没有清单还想用pwa

**Comment by pzcn** [comment]
> 你是部署哪个版本的chatgpt-web，没有清单还想用pwa

main分支啊...我也感觉到奇怪
![image](https://user-images.githubusercontent.com/29601158/224750848-9ed813a4-a605-4095-8eed-8b0156c21583.png)

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/224751875-98ff75cc-e493-4606-acae-029d602ad6bd.png)

  检查一下构建后的index.html和dist有没有我截图中的文件

**Comment by pzcn** [comment]
pnpm build以后dist里都有的

**Comment by pzcn** [comment]
> 你是不是有改什么配置导致部署上去的时候加载不到mainfest？ 你自己在一个个检查一下吧。

我突然对自己的部署方式产生了怀疑
pm2守护运行pnpm dev
然后nginx反代端口
这属于正常用法吗

**Comment by chenxch** [comment]
dev不会生成pwa相关文件，你应该是要构建后 运行 pnpm run preview， 然后代理到4173端口

**Comment by pzcn** [comment]
> dev不会生成pwa相关文件，你应该是要构建后 运行 pnpm run preview， 然后代理到4173端口

应该就是这个问题了 多谢解答

**Comment by huanle19891345** [comment]
> dev不会生成pwa相关文件，你应该是要构建后 运行 pnpm run preview， 然后代理到4173端口

请教大佬，我所有的配置都是按照ReadMe进行的，本地docker run之后index中有如下信息:
