### ISSUE TITLE
Docker 部署，Nginx反代，点设置按钮没反应。

### ISSUE THREAD

**Issue by chenyuxiangyes** [Chanzhaoyu/chatgpt-web#54]
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

nginx version: nginx/1.20.2

**Comment by plumhua** [comment]
Docker部署用ip端口访问一样，点设置没反应，arm

**Comment by Chanzhaoyu** [comment]
如果还有问题请搜索同样的问题～
