### ISSUE TITLE
2.10.4 版本 返回401错误

### ISSUE THREAD

**Issue by Andy-qinyuhai** [Chanzhaoyu/chatgpt-web#541]
Nginx 返代 Docker 3002端口，用Nginx auth_basic开启身份验证，Docker的环境变量没有启用AUTH_SECRET_KEY， 在之前的版本中使用都没问题，但今天更新到2.10.4版本后，第一次访问时会弹出用户验证对话框，但关闭浏览器再次打开后就无法访问，返回500页面，查看Status code返回了401，必须清除浏览器cookie缓存后才能正常打开

**Comment by whatwewant** [comment]
我也遇到了，貌似是 PWA 缓存了 /session
