### ISSUE TITLE
进行验证登入时，可以***屏蔽访问权限密钥吗？

### ISSUE THREAD

**Issue by bentwnghk** [Chanzhaoyu/chatgpt-web#547]
![Screenshot_20230312_230245_Samsung Internet](https://user-images.githubusercontent.com/101241940/224560362-a84c4e7a-352e-47b1-963b-1bcde6043149.jpg)

**Comment by Chanzhaoyu** [comment]
可以

**Comment by zong9805** [comment]
docker-compost刚pull的好像还是有提示这个授权，
