### ISSUE TITLE
有人遇到过在HUB无法搜索到大佬Docker的问题吗？

### ISSUE THREAD

**Issue by i-iooi-i** [Chanzhaoyu/chatgpt-web#55]
![image](https://user-images.githubusercontent.com/1827701/219682137-ba3608df-36eb-4bd6-a543-3826a7b5d186.png)

反复试了几次都无法搜索到，切换了网络也不行~ 可是HUB上的Docker是在的。

**Comment by Chanzhaoyu** [comment]
你用命令下呗

**Comment by i-iooi-i** [comment]
> 你用命令下呗

嗯嗯，我研究群晖里怎么用命令下载。 感谢。 😂
