### ISSUE TITLE
能否加入修改system prompt的功能，到现在默认参数还是You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible. 

### ISSUE THREAD

**Issue by mm519897405** [Chanzhaoyu/chatgpt-web#550]
这个困扰很久了，导致有时候AI有时候直接和你说英文

**Comment by pzcn** [comment]
这个调用的api写的了，要想修改就得换官方api，是个不小的工程。。看看开发者有没有打算换的想法吧

**Comment by mm519897405** [comment]
> 这个调用的api写的了，要想修改就得换官方api，是个不小的工程。。看看开发者有没有打算换的想法吧

有一说一，这个功能太重要了，直接影响后面chatgpt回复的趋势，现在作者新出这个所谓的promp商店，根本就不是内置的system prompt，治标不治本
system promp是直接影响后面所有对话走向的。比如安放一个性格，或者内置一段中文，都不可能出现现在偶尔会回复英文的情况。

**Comment by Chanzhaoyu** [comment]
> > 这个调用的api写的了，要想修改就得换官方api，是个不小的工程。。看看开发者有没有打算换的想法吧
> 
> 有一说一，这个功能太重要了，直接影响后面chatgpt回复的趋势，现在作者新出这个所谓的promp商店，根本就不是内置的system prompt，治标不治本 system promp是直接影响后面所有对话走向的。比如安放一个性格，或者内置一段中文，都不可能出现现在偶尔会回复英文的情况。

受 `access_token` 限制，如果整个项目直接去掉只使用官方 `API` 就好处理，先自行进行二次开发吧。

**Comment by Chanzhaoyu** [comment]
> > 这个调用的api写的了，要想修改就得换官方api，是个不小的工程。。看看开发者有没有打算换的想法吧
> 
> 有一说一，这个功能太重要了，直接影响后面chatgpt回复的趋势，现在作者新出这个所谓的promp商店，根本就不是内置的system prompt，治标不治本 system promp是直接影响后面所有对话走向的。比如安放一个性格，或者内置一段中文，都不可能出现现在偶尔会回复英文的情况。

实现起来其实也很简单，把选中的 `prompt` 添加进参数

**Comment by mm519897405** [comment]
> > > 这个调用的api写的了，要想修改就得换官方api，是个不小的工程。。看看开发者有没有打算换的想法吧
> > 
> > 
> > 有一说一，这个功能太重要了，直接影响后面chatgpt回复的趋势，现在作者新出这个所谓的promp商店，根本就不是内置的system prompt，治标不治本 system promp是直接影响后面所有对话走向的。比如安放一个性格，或者内置一段中文，都不可能出现现在偶尔会回复英文的情况。
> 
> 实现起来其实也很简单，把选中的 `prompt` 添加进参数

我是个小白产品，不是开发，能自己搞我就自己搞了😄，我尝试过在/src/chatgpt/index.ts下添加promp参数，但是失败了

**Comment by jamie0725** [comment]
> > > > 这个调用的api写的了，要想修改就得换官方api，是个不小的工程。。看看开发者有没有打算换的想法吧
> > > 
> > > 
> > > 有一说一，这个功能太重要了，直接影响后面chatgpt回复的趋势，现在作者新出这个所谓的promp商店，根本就不是内置的system prompt，治标不治本 system promp是直接影响后面所有对话走向的。比如安放一个性格，或者内置一段中文，都不可能出现现在偶尔会回复英文的情况。
> > 
> > 
> > 实现起来其实也很简单，把选中的 `prompt` 添加进参数
> 
> 我是个小白产品，不是开发，能自己搞我就自己搞了😄，我尝试过在/src/chatgpt/index.ts下添加prompt参数，但是失败了

修改 System Prompt 教程：
打开 `service/src/chatgpt/index.ts`，找到 `const response = await api.sendMessage(` 这行，按照下列格式加入 System Prompt：
```
const response = await api.sendMessage(message, {
      ...options,
      systemMessage: `You are ChatGPT, xxxxxxxxxx`,
      onProgress: (partialResponse) => {
        process?.(partialResponse)
      },
    })

```

**Comment by mm519897405** [comment]
> > > > > 这个调用的api写的了，要想修改就得换官方api，是个不小的工程。。看看开发者有没有打算换的想法吧
> > > > 
> > > > 
> > > > 有一说一，这个功能太重要了，直接影响后面chatgpt回复的趋势，现在作者新出这个所谓的promp商店，根本就不是内置的system prompt，治标不治本 system promp是直接影响后面所有对话走向的。比如安放一个性格，或者内置一段中文，都不可能出现现在偶尔会回复英文的情况。
> > > 
> > > 
> > > 实现起来其实也很简单，把选中的 `prompt` 添加进参数
> > 
> > 
> > 我是个小白产品，不是开发，能自己搞我就自己搞了😄，我尝试过在/src/chatgpt/index.ts下添加prompt参数，但是失败了
> 
> 修改 System Prompt 教程： 打开 `service/src/chatgpt/index.ts`，找到 `const response = await api.sendMessage(` 这行，按照下列格式加入 System Prompt：
> 
> ```
> const response = await api.sendMessage(message, {
>       ...options,
>       systemMessage: `You are ChatGPT, xxxxxxxxxx`,
>       onProgress: (partialResponse) => {
>         process?.(partialResponse)
>       },
>     })
> ```

感谢大佬！终于解决该问题
