### ISSUE TITLE
想用mongo存key

### ISSUE THREAD

**Issue by rhymed-liu** [Chanzhaoyu/chatgpt-web#551]
我用typeorm的框架使用mongo存了key,并且也做好了轮询,在start 和dev运行下一切正常 但是后端打包后就出现 元数据未找到,这个问题咋解决

**Comment by rhymed-liu** [comment]
感觉是打包的问题,第一次接触nodejs,不太会玩

**Comment by slieer** [comment]
mongo就存个key，太重了吧。做为issue，还是建议关闭吧。

**Comment by rhymed-liu** [comment]
后续想讲兑换内容都保存起来

**Comment by JeazW** [comment]
> mongo就存个key，太重了吧。做为issue，还是建议关闭吧。

引入mongo后，能实现的更能就更多了，不只是存key

**Comment by slieer** [comment]
其实我的意思是，先大家能聚焦到openai上，不是只有一个聊天，针对，更丰富的prompt, 语音，图片， embedding, fine ture, 多个模型方面优先用力。

**Comment by rhymed-liu** [comment]
可以关闭这个问题了,
