### ISSUE TITLE
使用access token时，报错Could not parse your authentication token. Please try signing in again

### ISSUE THREAD

**Issue by zhychen1173** [Chanzhaoyu/chatgpt-web#556]
docker compose启动的服务，配置文件中注释掉了 OPENAI_API_KEY 那行，选择的 OPENAI_ACCESS_TOKEN。
之前 access token使用正常，前两天开始报 fetch failed. 更新新版后，重新用 access token试，出现如下报错：

ChatGPTError: ChatGPT error 401: {"detail":{"message":"Could not parse your authentication token. Please try signing in again.","type":"invalid_request_error","param":null,"code":"invalid_jwt"}}
    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.0.10/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 401,
  statusText: 'Unauthorized',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 401,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Unauthorized',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

用api key正常。

**Comment by Chanzhaoyu** [comment]
换个社区反代理试试

**Comment by zhychen1173** [comment]
> 换个社区反代理试试

我的vps是美国的，并且套了cloudflare warp，ip检测是可以访问chatgpt 的，没有配反代，直接连的。
