### ISSUE TITLE
建议考虑增加AIPRM for ChatGPT插件的支持

### ISSUE THREAD

**Issue by chaoticjoy** [Chanzhaoyu/chatgpt-web#558]
最近使用AIPRM for ChatGPT插件，发现配合这个插件可以发挥更大的作用，建议开发组适配一下AIPRM for ChatGPT插件支持。

**Comment by yinliangc** [comment]
这个应该在 AIPRM 那边提需求吧

**Comment by chaoticjoy** [comment]
> 这个应该在 AIPRM 那边提需求吧

理论上是找那边，但是那边不会搭理的，只能这边做一些适配，不行就是我自己解包去改了
