### ISSUE TITLE
加载时间与什么有关

### ISSUE THREAD

**Issue by kintong3000** [Chanzhaoyu/chatgpt-web#560]
访问搭建好的web时，总有一段加载动画界面，想知道这个加载时间与什么有关，cpu？，带宽？我看我的服务器控制台的监控也没怎么用占用率。我看有一个网页用了这个仓库，访问它的加载速度很快，访问我自己的要20-30秒。

**Comment by htmljsp** [comment]
同问

**Comment by goodwisdom** [comment]
同问，按照命令一步步部署后，打开网页时，三个小球的页面会出现几秒钟，不是秒开，是不是因为登录密码验证的问题？docker部署打开要快些

**Comment by chenxch** [comment]
你打开network看一下资源加载

**Comment by Chanzhaoyu** [comment]
前端可以做 `gzip` 压缩

**Comment by goodwisdom** [comment]
![mmexport1678757012134.png](https://user-images.githubusercontent.com/94884322/224868182-d1965ecb-b455-4add-aad0-13d2c93df2a1.png)
也有可能是我域名反代理有问题吧

**Comment by NeilXue** [comment]
> 把deps下边所有文件放到cdn上，就快多了。整站加速玩不太懂，应该效果更好。

这个具体怎么做？
