### ISSUE TITLE
JSON 格式错误，请检查 JSON 格式

### ISSUE THREAD

**Issue by 0xorOne** [Chanzhaoyu/chatgpt-web#564]
导入prompts时json格式错误
![image](https://user-images.githubusercontent.com/125463022/224654062-658c06d6-d8c9-4052-b44c-ca6d523776e7.png)
直接导入json也提示格式错误
![image](https://user-images.githubusercontent.com/125463022/224654233-b3c908c1-c391-4157-b313-1f03b16858cb.png)

**Comment by simonwu53** [comment]
原因在[这](https://github.com/Chanzhaoyu/chatgpt-web/pull/521#issuecomment-1465208190)...

**Comment by Chanzhaoyu** [comment]
已修复
