### ISSUE TITLE
苹果11手机使用浏览器打开会一直处于加载状态

### ISSUE THREAD

**Issue by B1gM8c** [Chanzhaoyu/chatgpt-web#566]
无意间使用同事的苹果11，发现绿色的球一直在加载中
User-Agent为
```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) 
```
电脑上模拟会出现前面几秒钟一直在转，后面可以加载出来，不知道是不是代码哪里写的有问题导致的。应该不是网络问题，因为同一个网络下其他设备均能正常打开

**Comment by chenxch** [comment]
可能是safari版本太低了，你试试看chrome浏览器。
