### ISSUE TITLE
[注意封号]超容易被封号，大家小心

### ISSUE THREAD

**Issue by nagaki09** [Chanzhaoyu/chatgpt-web#569]
美国的vps服务器，新号，自用
刚完成搭建，问了一个问题，马上就收到官方邮件，帐号出现在非服务地区访问因此被封

没有找到规避和解封方法前，建议大家一定要谨慎尝试

**Comment by ottocsb** [comment]
服务器地址是假美国？
正常美国地址不能够被封，你访问的ip是否在服务地区内

**Comment by JuneDan** [comment]
是的，被封了两个，报了401，此密钥与未激活的帐户相关联。如果您觉得这是一个错误，请通过我们的帮助中心help.openai.com联系我们。

**Comment by xiabill** [comment]
有理~用gcp跑

**Comment by nagaki09** [comment]
>
> 服务器地址是假美国？ 正常美国地址不能够被封，你访问的ip是否在服务地区内

后端和前端都部署在北美的服务器上，通过docker compose部署的，机器的ip也是美国的，另外的应用跑到现在都很稳定
直到昨天，国内通过自己的域名访问自己的机器，提了一个问题，大概5分钟后就收到了官方 非服务地域的封禁

**Comment by nagaki09** [comment]
> railway 搭建的，稳的一批。
> 
> 他跑在GCP上面的，正宗的美国IP。
> 
> ![image](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)

我用之前消耗完额度的帐号，用railway部署了，看会不会被封，不封的话，我再搞个新号试一下

**Comment by nagaki09** [comment]
> railway 搭建的，稳的一批。
> 
> 他跑在GCP上面的，正宗的美国IP。
> 
> ![image](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)

换成railway了，确实没被封。。。

**Comment by kilvn** [comment]
> > railway 搭建的，稳的一批。
> > 他跑在GCP上面的，正宗的美国IP。
> > ![image](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)
> 
> 换成railway了，确实没被封。。。

我都用了半个月了，没任何问题

**Comment by pepsigold** [comment]
> railway 搭建的，稳的一批。
> 
> 他跑在GCP上面的，正宗的美国IP。
> 
> ![image](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)

大佬，付费求指导搭建~谢谢！给个联系方式~

**Comment by kilvn** [comment]
> > railway 搭建的，稳的一批。
> 
> > 
> 
> > 他跑在GCP上面的，正宗的美国IP。
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)
> 
> 
> 
> 大佬，付费求指导搭建~谢谢！给个联系方式~

没什么好指导的，readme 里面的链接点进去一键部署

**Comment by xiguafz** [comment]
> railway 搭建的，稳的一批。
> 
> 他跑在GCP上面的，正宗的美国IP。
> 
> ![图像](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)

你截图这个页面是啥，在哪看的

**Comment by kilvn** [comment]
> > railway 搭建的，稳的一批。
> > 他跑在GCP上面的，正宗的美国IP。
> > ![图像](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)
> 
> 你截图这个页面是啥，在哪看的

这是我在railway搭的ss代理服务，访问ip.sb的结果，你也可以ping一下你railway绑定域名的IP，看下IP归属地。

**Comment by jykSS** [comment]
我用railway搭建的会出现(POST /v1/chat/completions这个问题,参数都填了,你们有遇到这个问题吗

**Comment by omgcx1222** [comment]
> > > railway 搭建的，稳的一批。
> > > 他跑在GCP上面的，正宗的美国IP。
> > > ![图像](https://user-images.githubusercontent.com/16423601/224870709-a3f72fd3-20b6-4e9d-b9ce-75c255f7be43.png)
> > 
> > 
> > 你截图这个页面是啥，在哪看的
> 
> 这是我在railway搭的ss代理服务，访问ip.sb的结果，你也可以ping一下你railway绑定域名的IP，看下IP归属地。

我在railway部署成功后，访问接口提示 503 ，大佬知道是什么原因吗
