### ISSUE TITLE
如何部署在线上服务器，用域名并且是https访问

### ISSUE THREAD

**Issue by YellowShy** [Chanzhaoyu/chatgpt-web#57]
部署在线上，用的apache。前端https能访问到，后端提示404，后端是用pnpm start运行在同一台服务器上的

**Comment by YellowShy** [comment]
不论是http还是https  访问域名/api/chat都是404  前端可以访问到

**Comment by Chanzhaoyu** [comment]
是前端访问后端服务 `404` 还是 `node` 服务本身就 `404`，先在根目录下 `.env` 文件修改下接口成实际地址试试
提供截图最好

**Comment by lengshu** [comment]
我是docker部署,然后反代了

**Comment by YellowShy** [comment]
![QQ截图20230220102804](https://user-images.githubusercontent.com/24569603/219995898-21dd74f3-a7bf-4963-9554-c0fed6751450.png)
![QQ截图20230220102848](https://user-images.githubusercontent.com/24569603/219995914-968c2468-c195-4f9e-8e29-e31272682180.png)
前端我是用pnpm build 打包了上传到宝塔apache搭建的前端，后端跟前端是同一台服务器，后端也是打包后用 pm2运行了。
是需要配置什么伪静态吗
假如我用pnpm dev  然后用ip+端口访问  是可以访问到前端并且那个/api/chat接口也是正常  可以正常使用   打包放到正式环境用域名访问那个接口就404

**Comment by Chanzhaoyu** [comment]
> ![QQ截图20230220102804](https://user-images.githubusercontent.com/24569603/219995898-21dd74f3-a7bf-4963-9554-c0fed6751450.png) ![QQ截图20230220102848](https://user-images.githubusercontent.com/24569603/219995914-968c2468-c195-4f9e-8e29-e31272682180.png) 前端我是用pnpm build 打包了上传到宝塔apache搭建的前端，后端跟前端是同一台服务器，后端也是打包后用 pm2运行了。 是需要配置什么伪静态吗 假如我用pnpm dev 然后用ip+端口访问 是可以访问到前端并且那个/api/chat接口也是正常 可以正常使用 打包放到正式环境用域名访问那个接口就404

`http://localhost:3002/`  改成你的真实 `IP` 试一下

**Comment by ludashi2020** [comment]
http://localhost:3002/ 改成你的真实 IP，也是不行的。目前前端使用pnpm dev可以使用，打包运行后前端/api/chat会报错

**Comment by leeggco** [comment]
> /api也改成真实地址就可以生成静态页部署了

最后怎么配置可以细说下吗，也遇到这个问题
