### ISSUE TITLE
希望大佬把前后端合并成一个项目方便开发和部署

### ISSUE THREAD

**Issue by smanx** [Chanzhaoyu/chatgpt-web#578]
### 如使用Nuxt或Astro

**Comment by zhanggaolei001** [comment]
开发本身分前后端是没问题的,你想要的是一键开发脚本吧.
前后端合并一个项目那就成了开倒车了

**Comment by ChandlerVer5** [comment]
其实后端也是使用了 chatgpt库，你要不把它移到前端使用，要不然就直接把所有接口改成 使用 openai 官方的接口去请求。

**Comment by rhymed-liu** [comment]
> 其实后端也是使用了 chatgpt库，你要不把它移到前端使用，要不然就直接把所有接口改成 使用 openai 官方的接口去请求。

移动我觉得问题不大,但是key啥的不就泄露了吗
