### ISSUE TITLE
感觉发消息的按钮可以支持回车发送。。。或者shift+回车发送

### ISSUE THREAD

**Issue by ieras** [Chanzhaoyu/chatgpt-web#579]
RT

**Comment by DragonRollGH** [comment]
电脑端/宽屏模式：回车发送，Shift+回车换行。
移动端/小窗模式：回车/Shift+回车换行，Ctrl+回车发送。
但刚才测试小窗Ctrl+回车发送失效了，之前这个pr https://github.com/Chanzhaoyu/chatgpt-web/pull/363 是有效的

**Comment by ieras** [comment]
> 电脑端/宽屏模式：回车发送，Shift+回车换行。 移动端/小窗模式：回车/Shift+回车换行，Ctrl+回车发送。 但刚才测试小窗Ctrl+回车发送失效了，之前这个pr #363 是有效的

试了下 确实是！感谢 感谢！目前就是手机端按回车不好用，电脑端宽屏模式体验最好

**Comment by ieras** [comment]
主要手机端不好按 ctrl剑

**Comment by DragonRollGH** [comment]
手机端弹出来的键盘是换行，前端按钮是发送。
很正常的逻辑，否则如果弹出来键盘也是发送就没法换行了。

**Comment by ieras** [comment]
> 

哦哦 明白了！微信可以直接用回车发送是因为微信那在光标处长按可以出来回车按钮。感谢解答！
