### ISSUE TITLE
Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable

### ISSUE THREAD

**Issue by JoyTiann** [Chanzhaoyu/chatgpt-web#586]
已经填写了OPENAI_API_KEY和OPENAI_ACCESS_TOKEN，在server文件夹下执行pnpm start还是会报这个错误“Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable”

**Comment by yindahu87** [comment]
> 已经填写了OPENAI_API_KEY和OPENAI_ACCESS_TOKEN，在server文件夹下执行pnpm start还是会报这个错误“Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable”

同样遇到这个错误 求解决
