### ISSUE TITLE
railway Deploy 功能不是很清楚

### ISSUE THREAD

**Issue by s724959099** [Chanzhaoyu/chatgpt-web#590]
不知道該如何佈署，一直都是失敗的，還請幫忙，感謝

**Comment by wwlmm** [comment]
railway 最简单了 随便一弄就成功了

**Comment by s724959099** [comment]
在 build docker 的時候一直都會顯示


context: f55e199d75794a6b66bbc9be32f71d9c
#2 [internal] load .dockerignore
#2 sha256:1d6e9177124f301a4dd57f4994abdd38c40911a84bd0e3f81373847a3bc9eaa1
#2 ERROR: failed to add snapshot r4f9ewsz1ff0cvay70u4kv6x3 to lease: write /var/lib/docker/buildkit/containerdmeta.db: no space left on device
 
#1 [internal] load build definition from Dockerfile
#1 sha256:139ab3ead1d08c28c506efccb5286c891db9c6e3311b168fa492af3e9df5ea80
#1 ERROR: failed to prepare mcnoh9z8odyrhkjmweb6xg00q: mkdir /var/lib/docker/overlay2/mcnoh9z8odyrhkjmweb6xg00q: no space left on device
-----
> [internal] load build definition from Dockerfile:
-----
-----
> [internal] load .dockerignore:
-----
 
failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to prepare mcnoh9z8odyrhkjmweb6xg00q: mkdir /var/lib/docker/overlay2/mcnoh9z8odyrhkjmweb6xg00q: no space left on device

**Comment by s724959099** [comment]
我是自己部屬的，應該要直接按 deploy railway template 在 readme 上，不好意思
