### ISSUE TITLE
一个新号 用代理地址 问了三个问题，第二天醒来，我的号直接被deactive了

### ISSUE THREAD

**Issue by fireinrain** [Chanzhaoyu/chatgpt-web#595]
看readme说默认的代理地址是：https://bypass.duti.tech/api/conversation, 我在昨天晚上用自己google账号注册的chatgpt账号，accessToken填入项目，问了三个问题，第二天我没办法登录官网的chatgpt 也没办法调用这个项目。(新号的意思是在此之前这个号的api 和accessToken都没有被用来做任何的三方api调用的)
以下是截图：
![Xnip2023-03-15_09-30-29](https://user-images.githubusercontent.com/14249262/225183018-4491e0e0-42ff-46a3-a971-4d344e8cd5dd.jpg)
![Xnip2023-03-15_09-31-34](https://user-images.githubusercontent.com/14249262/225183037-1895783b-1240-4d2a-90b2-0ef6b64e9c06.jpg)
![Xnip2023-03-15_09-32-07](https://user-images.githubusercontent.com/14249262/225183051-6752b26f-3930-4ff2-a664-40dc850dce0d.jpg)
<img width="685" alt="image" src="https://user-images.githubusercontent.com/14249262/225183457-a4dc7ca8-0426-4304-a6a3-9ff8c127c625.png">

代理链接真的有鬼。。。

**Comment by kilvn** [comment]
accessToken 本来就很容易被封，我们都用 api key，这个很稳

**Comment by praiseqin** [comment]
已经连续被封5个号，accessToken和API基本上线秒封。阿里云-新加坡ECS

**Comment by fireinrain** [comment]
> accessToken 本来就很容易被封，我们都用 api key，这个很稳

我之前用apikey 也被封了 现在三个号没了 有点离谱

**Comment by fireinrain** [comment]
> accessToken 本来就很容易被封，我们都用 api key，这个很稳

我很想知道你部署的vps ip是哪里的，我部署的ip是在日本东京，ip本身是正常的 因为我之前可以访问chatgpt的官网的

**Comment by fireinrain** [comment]
> 已经连续被封5个号，accessToken和API基本上线秒封。阿里云-新加坡ECS

难受，不是买的成品号，是自己常用的号，因为之前一直不敢用自己常用的号写入这个服务的配置，就是因为前两个成品号，昨天晚上试了一下，今天早上账号就被注销了。我这个号是chatgpt刚出来就注册好了的，这下真的是试试就逝世

**Comment by wwlmm** [comment]
的确，我昨天也发疯一样的买了一个号试试，今天早上起来 自己的号和买的号都被封了

**Comment by bestmidyang** [comment]
我昨天更新2.10.5, 代理是社区的https://bypass.duti.tech/api/conversation, 然后昨天问了几个问题,刚也被封了

**Comment by praiseqin** [comment]
猜测可能和没绑定支付卡有关

**Comment by zwzsdy** [comment]
G了  同样用 https://bypass.duti.tech/api/conversation  账号已被封...

**Comment by zwzsdy** [comment]
> G了 同样用 https://bypass.duti.tech/api/conversation 账号已被封...

昨天晚上还登录了 今天早上一来发现被封了。。。

**Comment by fireinrain** [comment]
好难受啊，我这个还是个老号，甚至收到了openai chatgpt4.0 发布预览的链接给我。。。

**Comment by jigsaw-china** [comment]
充钱了吗

**Comment by fireinrain** [comment]
没有 我不是plus用户 但是账号是chatgpt刚出来就注册了的

**Comment by jigsaw-china** [comment]
充点钱是不是就不容易被封了

**Comment by fireinrain** [comment]
> 没有 我不是plus用户 但是账号是chatgpt刚出来就注册了的

新号的意思是之前都没有用这个号的api 和accessToken来做api调用

**Comment by jigsaw-china** [comment]
充点¥是不是就不容易被封

**Comment by jigsaw-china** [comment]
充点钱是不是就不容易被封了

**Comment by fireinrain** [comment]
> 充点钱是不是就不容易被封了

不清楚 充钱是要绑定信用卡买plus会员吧

**Comment by jigsaw-china** [comment]
不知道呀，我也没充过

**Comment by zwzsdy** [comment]
> 好难受啊，我这个还是个老号，甚至收到了openai chatgpt4.0 发布预览的链接给我。。。

加一  昨晚上加入了wait list  结果上午就被封了。。

**Comment by charley008** [comment]
腾讯轻量云香港。一直使用没被封

**Comment by fireinrain** [comment]
> 腾讯轻量云香港。一直使用没被封，速度很快

用的accessToken？有用代理地址吗  还是用的apiKey

**Comment by imdingtalk** [comment]
哈哈哈哈，，，我不是一个人

**Comment by wwlmm** [comment]
简直丧心病狂

**Comment by wjx888** [comment]
我也被封了，老号来的，伤心啊

**Comment by fireinrain** [comment]
> 我也被封了，老号来的，伤心啊

我也是啊 老号啊，chatgpt一出来就注册的，现在两眼一黑 痛 太痛了

**Comment by xieyusi9** [comment]
我的也封了，看来accessToken不能再用了

**Comment by kilvn** [comment]
> > accessToken 本来就很容易被封，我们都用 api key，这个很稳
> 
> 我很想知道你部署的vps ip是哪里的，我部署的ip是在日本东京，ip本身是正常的 因为我之前可以访问chatgpt的官网的

railway，跑在GPC的美国IP

**Comment by ifangyong** [comment]
我甚至还绑定了信用卡，同样老号被封

**Comment by wjx888** [comment]
> 我甚至还绑定了信用卡，同样老号被封
唉，现在好伤心，账号注册倒是简单，但是被封的是老号

**Comment by ottocsb** [comment]
这个新代理不太Ok，我的账号也被封禁了

**Comment by CaptainYan2** [comment]
被封加一，我是api和accesstoken一起用开了俩container

**Comment by baby9** [comment]
会不会是你们接码的号被人用来多次注册?

**Comment by dashug** [comment]
+1，昨天就临时接入问了两个问题，老号被封了

**Comment by charley008** [comment]
> ccessToken？有用代理地址吗 还是用的apiKey

不需要代理啊。apikey

**Comment by swxk521** [comment]
刚申请了个账号，用的OPENAI_API_KEY, 
不到一分钟就封了。不知道啥原因了。

**Comment by wwlmm** [comment]
> 会不会是你们接码的号被人用来多次注册? 印尼便宜地离谱，我猜你们接码时都选的印尼

注册的美国的号

**Comment by luuziiyoo** [comment]
封的是ip还是账号 我倒是一直用的好好地

**Comment by fireinrain** [comment]
> 封的是ip还是账号 我倒是一直用的好好地

账号直接被删除了

**Comment by cuteday** [comment]
同accessToken被封，另一个只用API_KEY的号目前还没事。

**Comment by XiaoApi** [comment]
应该是这个代理的问题.  我也是秒封

**Comment by FastSchnell** [comment]
依然坚挺，你们可以临时用下我的 https://www.postbook.xyz/read/chatGPT

**Comment by nagaki09** [comment]
你们都有海外vps了，为什么还要用代理呢？

**Comment by fireinrain** [comment]
> 你们都有海外vps了，为什么还要用代理呢？

代理可以bypass cf的，单是海外vps 如果用accessToken 用api.openai 是没法请求成功的。只能是用apiKey
其他的情况我不太了解 我用的是accessToken 被deactive了

**Comment by Hel5ing** [comment]
华为新加坡云,老号没用代理一直正常

**Comment by ludashi2020** [comment]
自建代理加plus订阅稳如老狗

**Comment by ludashi2020** [comment]
> > 自建代理加加订阅稳定如老狗
> 
> accessToken的反代你会搭建吗？

会搭建啊，必须是plus账号才可以，普通账号无解

**Comment by GH6324** [comment]
> > > 自建代理加加订阅稳定如老狗
> > 
> > 
> > accessToken的反代你会搭建吗？
> 
> 会搭建啊，必须是plus账号才可以，普通账号不行

我有plus订阅，有反代的项目地址或者教程不，有的话麻烦发下，谢谢

**Comment by Uzai-hu** [comment]
我用的阿里云海外的，一点事没有。国外别的厂家的一个主机也没事

**Comment by edsky** [comment]
搭建反向代理是这个么？https://github.com/noobnooc/noobnooc/discussions/9

cf的cookie值可不可以直接刷新页面获取然后通过浏览器插件传出来，这样是不是可以绕过

**Comment by riwigefi** [comment]
你从A国注册openai。如果你试图在不同的地方（例如B国）登录，OpenAI说你不能从B国登录。因为你是从A国注册的。
所以，我们从A国注册，并通过代理服务器（服务器位置在X国）发送请求。现在OpenAI意识到这个问题，我们从我们的国家登录，并通过代理服务器发送请求，通过access_token。这样的情况，都会被封号，我已经损失大概七八个好了

**Comment by praiseqin** [comment]
注册地IP+注册地手机号+使用地IP，三者要一致;
三方购买的token或账号，确保首次登陆后的IP未来持续可以用;
使用地IP不要出现多个token同时使用（不要公用任何形式代理），自荐代理且过CF，参考https://github.com/noobnooc/noobnooc 免费免费免费！！！

**Comment by riwigefi** [comment]
> 自9号以来累计被ban 10+的经验： 注册地IP+注册地手机号+使用地IP，三者要一致; 三方购买的token或账号，确保首次登陆后的IP未来持续可以用; 使用地IP不要出现多个token同时使用（不要公用任何形式代理），自荐代理且过CF，参考[noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9) 免费免费免费！！！

使用地IP可以使用多个不同账号的api key吗

**Comment by zhychen1173** [comment]
> 

请问一下，cloudflare worker建的代理，除了支持api key模式之外，也支持access token 方式吗？

**Comment by omgcx1222** [comment]
你们的apikey都是在哪买的，我前天的也被封了，现在又注册不了新号

**Comment by riwigefi** [comment]
> 你们的apikey都是在哪买的，我前天的也被封了，现在又注册不了新号

我可以给你api key体验

**Comment by zhychen1173** [comment]
> 请问一下，cloudflare worker建的代理，除了支持api key模式之外，也支持access token 方式吗？

请问一下，cloudflare worker建的代理，除了支持api key模式之外，也支持access token 方式吗？

**Comment by zhychen1173** [comment]
> 自9号以来累计被ban 10+的经验： 注册地IP+注册地手机号+使用地IP，三者要一致; 三方购买的token或账号，确保首次登陆后的IP未来持续可以用; 使用地IP不要出现多个token同时使用（不要公用任何形式代理），自荐代理且过CF，参考[noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9) 免费免费免费！！！

请问一下，cloudflare worker建的代理，除了支持api key模式之外，也支持access token 方式吗？

**Comment by Chanzhaoyu** [comment]
> > 自9号以来累计被ban 10+的经验： 注册地IP+注册地手机号+使用地IP，三者要一致; 三方购买的token或账号，确保首次登陆后的IP未来持续可以用; 使用地IP不要出现多个token同时使用（不要公用任何形式代理），自荐代理且过CF，参考[noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9) 免费免费免费！！！
> 
> 请问一下，cloudflare worker建的代理，除了支持api key模式之外，也支持access token 方式吗？

不支持 `access token`，你自建的代理只是翻墙

**Comment by fireinrain** [comment]
issue我关了，重新买了一个成品号。

**Comment by Chanzhaoyu** [comment]
> issue我关了，重新买了一个成品号。

买号不是被封的更快...

**Comment by praiseqin** [comment]
> > 自9号以来累计被ban 10+的经验： 注册地IP+注册地手机号+使用地IP，三者要一致; 三方购买的token或账号，确保首次登陆后的IP未来持续可以用; 使用地IP不要出现多个token同时使用（不要公用任何形式代理），自荐代理且过CF，参考[noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9) 免费免费免费！！！
> 
> 请问一下，cloudflare worker建的代理，除了支持api key模式之外，也支持access token 方式吗？

对它的worker有两层个人理解：
1、同server接入CF相关服务的，默认端到端是可信任（具体参考noobnooc#9的帖子）
2、worker自带全球分布式CDN（相当于自带梯子，可以把地址指向IP接口验证的）

所以，不论是API还是AccessToken。本质上是一样的，核心是worker的地址用的人少和它给你分配的出口IP是不是在OpenAI支持地区以内；

**Comment by fireinrain** [comment]
> > issue我关了，重新买了一个成品号。
> 
> 买号不是被封的更快...

不用做api调用和accessToken使用 只是用官网还是没问题的
不太清楚openai是那一天特备严格还是怎么的，总之先用官网算了

**Comment by Skyly119** [comment]
> 充点钱是不是就不容易被封了
不会的, 昨天我的plus账号也被秒封掉了
