### ISSUE TITLE
求问，2.8.3很稳定，更新到2.10.5后无法使用，前端报错

### ISSUE THREAD

**Issue by yjx125164194** [Chanzhaoyu/chatgpt-web#596]
```
The service was stopped: write EPIPE (x3)
/root/chatgpt-web/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1145
        return callback(new Error(error), null);
                        ^

Error: The service was stopped: write EPIPE
    at /root/chatgpt-web/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1145:25
    at Object.responseCallbacks.<computed> (/root/chatgpt-web/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:701:9)
    at afterClose (/root/chatgpt-web/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:691:28)
    at /root/chatgpt-web/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:2097:11
    at onwriteError (node:internal/streams/writable:417:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
 ELIFECYCLE  Command failed with exit code 1.
```

service和前端的包都pnpm更新了，结果启动前端以后，访问网页前端就崩了。

**Comment by Chanzhaoyu** [comment]
本地打包是否出错，2.10.0 之后不再提供 .env 文件，而是要自己创建

**Comment by yjx125164194** [comment]
> 本地打包是否出错，2.10.0 之后不再提供 .env 文件，而是要自己创建

感谢回复，我env已经自己创建了，填写了api字段。启动可以启动，但是启动后通过网页一访问就这样了。

我现在怀疑是我机器512MB内存导致的，但是我没有证据

**Comment by Chanzhaoyu** [comment]
> > 本地打包是否出错，2.10.0 之后不再提供 .env 文件，而是要自己创建
> 
> 感谢回复，我env已经自己创建了，填写了api字段。启动可以启动，但是启动后通过网页一访问就这样了。
> 
> 我现在怀疑是我机器512MB内存导致的，但是我没有证据

目前这个报错只有这一个 issues ，看起来像是 esbuild 的报错，但是这个包是打包的时候才会用到的依赖，我也无法判断。

**Comment by yjx125164194** [comment]
> > > 本地打包是否出错，2.10.0 之后不再提供 .env 文件，而是要自己创建
> > 
> > 
> > 感谢回复，我env已经自己创建了，填写了api字段。启动可以启动，但是启动后通过网页一访问就这样了。
> > 我现在怀疑是我机器512MB内存导致的，但是我没有证据
> 
> 目前这个报错只有这一个 issues ，看起来像是 esbuild 的报错，但是这个包是打包的时候才会用到的依赖，我也无法判断。

好吧...我之前2.8.3其实也很好用，只不过想加上密码之类的，再加上GPT4更新了想着还是跟着main主线，十分感谢

**Comment by jamie0725** [comment]
> GPT4

ChatGPT 4 目前并没有完全开放使用，这个 Git Repo 调用的 API 也还不支持。

**Comment by yjx125164194** [comment]
> > GPT4
> 
> ChatGPT 4 目前并没有完全开放使用==


主要是现在无法更新main的代码，估计GPT4是早晚的事情
