### ISSUE TITLE
功能建议：固定更多参数如名称描述等，以及同步记录

### ISSUE THREAD

**Issue by aoaim** [Chanzhaoyu/chatgpt-web#597]
当前版本使用时似乎会将数据缓存在本地，一旦清理缓存或者cookie后设置的头像、名称等内容都会被重置。这样的话对个人使用可能不是最友好的，可否将这些固定在docker的参数里？

同样的原因，用新浏览器打开后以前的问答记录也会消失。可否有办法能在网页中保存住，或者保存到服务器？

**Comment by Chanzhaoyu** [comment]
个人信息可以本地修改再用 docker 打包，记录保存的话这个需要自己对接数据库哦。
