### ISSUE TITLE
api可否填写多个，比如xxxx | xxxx，会随机调用一个。

### ISSUE THREAD

**Issue by CraftYouMe** [Chanzhaoyu/chatgpt-web#598]
因为是公司使用，有时候一个消耗的太快，需要多个api一起

**Comment by Chanzhaoyu** [comment]
同一个 IP 多个 key 轮巡会导致封号的概率变大

**Comment by Chanzhaoyu** [comment]
之前有过这个讨论，但是自从封号开始之后就放弃了

**Comment by CraftYouMe** [comment]
我觉得可以添加一个前端填写API的方式，增加自定义性。

**Comment by CraftYouMe** [comment]
> 之前有过这个讨论，但是自从封号开始之后就放弃了

请问，怎么把连续对话的开关设置为默认关闭。

**Comment by bestmidyang** [comment]
我也是公司使用,  我的账号申请了5个key,  然后启动了5个服务, 每个服务用不同key, 然后用nginx代理,  这样就能简单实现多个key使用
