### ISSUE TITLE
怎么把连续对话的开关设置为默认关闭。

### ISSUE THREAD

**Issue by CraftYouMe** [Chanzhaoyu/chatgpt-web#599]
告诉我一下修改路径。。。

**Comment by StereoApp** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/blob/25692f83719ffb05e06864c02c19aab7469fdb8e/src/views/chat/hooks/useUsingContext.ts#L7

改为 const usingContext = ref<boolean>(false)

**Comment by CraftYouMe** [comment]
> https://github.com/Chanzhaoyu/chatgpt-web/blob/25692f83719ffb05e06864c02c19aab7469fdb8e/src/views/chat/hooks/useUsingContext.ts#L7
> 
> 改为 const usingContext = ref(false)

谢谢QAQ
