### ISSUE TITLE
为什么配置了后端的接口域名，请求的还是localhost加端口的接口啊

### ISSUE THREAD

**Issue by wangshengli0421** [Chanzhaoyu/chatgpt-web#60]
![image](https://user-images.githubusercontent.com/100948785/219921787-78ebaf18-5947-4b4c-b724-e1760ce584cb.png)

**Comment by Chanzhaoyu** [comment]
你这个是自己打包的还是 `docker`，根目录下 `.env` 文件中修改实际接口地址

**Comment by Chanzhaoyu** [comment]
> > 你这个是自己打包的还是 `docker`，根目录下 `.env` 文件中修改实际接口地址
> 
> 请问用docker部署的话这个地址如何修改？也遇到这个问题了

`2.6.1` 已经改过这个问题了，直接修改为你自己的后端实际地址就好

**Comment by chris-ss** [comment]
同样的问题，docker compose部署后用NginxProxyManager反代的
昨天版本正常的，今天更新2.6.1版本后就 Request URL: http://localhost:3002/chat

**Comment by jkhcc11** [comment]
> 

如果你用的2.6.1的版本，可以直接进容器手动把打包好的js中的`localhost` 这个地址，改为你实际的地址，就可以了。其他加变量的方式可能需要重新打包，我昨天只能手动改，亲测有效！
