### ISSUE TITLE
请问一般一个plus账号, 多少人用不会封号?

### ISSUE THREAD

**Issue by HgLiJiahao** [Chanzhaoyu/chatgpt-web#600]
我想和几个同事共享, 但第一个账号被封了(deactivated), 用的acheon8的那个搭过服务, 我怀疑token泄漏了.现在重新建了个账号, 打算买plus.

**Comment by chnaan** [comment]
今天很多人反馈账号被封禁的问题（deactivated），我上午新搞了一个账号还没一个小时就被封了，在目前还不清楚封禁原因的情况下，建议最好先不要再测试新的账号。

**Comment by fireinrain** [comment]
对的 先不要测试新号，被deactive了 太痛苦了

**Comment by FastSchnell** [comment]
@HgLiJiahao 用我这个，免费的 https://www.postbook.xyz/read/chatGPT

**Comment by herepost** [comment]
我也是刚才被封号了，不清楚为什么

**Comment by jasonzb** [comment]
被封号提示啥呀？
我在上午还能用，下午订阅了个 plus，退出登录后，就提示Access is temporarily unavailable, please try again later.了

**Comment by wysuperfly** [comment]
plus 也封号？ 封了退钱不。。。

**Comment by HgLiJiahao** [comment]
> 被封号提示啥呀？
> 我在上午还能用，下午订阅了个 plus，退出登录后，就提示Access is temporarily unavailable, please try again later.了

提示account has been deactivated

**Comment by HgLiJiahao** [comment]
> plus 也封号？ 封了退钱不。。。

邮件都不理我的。。唉

**Comment by HgLiJiahao** [comment]
> 我也是刚才被封号了，不清楚为什么

你用了非官方的api吗？

**Comment by HgLiJiahao** [comment]
> 今天很多人反馈账号被封禁的问题（deactivated），我上午新搞了一个账号还没一个小时就被封了，在目前还不清楚封禁原因的情况下，建议最好先不要再测试新的账号。

感谢提醒，现在还是暂时只给自己用好了

**Comment by 676077263** [comment]
都是这天统一封号的，老号很少有逃脱的，只有这两天没有使用过的人才没封号，重新申请就是了

**Comment by fireinrain** [comment]
> 都是这天统一封号的，老号很少有逃脱的，只有这两天没有使用过的人才没封号，重新申请就是了

是这样的 老号都死了
