### ISSUE TITLE
部署到docker中，配置是不是配置错了，无法正常使用

### ISSUE THREAD

**Issue by jialifushi** [Chanzhaoyu/chatgpt-web#602]
<img width="1093" alt="iShot2023-03-15 14 25 14" src="https://user-images.githubusercontent.com/101686929/225224540-52da1ebf-74ab-4afe-a2ed-2ace469d0cda.png">
<img width="1041" alt="iShot2023-03-15 14 25 25" src="https://user-images.githubusercontent.com/101686929/225224642-22952068-f5a5-4f80-a6a9-6eaba1f73397.png">
无法正常交流

**Comment by fireinrain** [comment]
能给出脱敏后的配置吗

**Comment by fireinrain** [comment]
有可能是这个仓库依赖的代理地址下线了  你查看后台日志 看看具体是什么原因

**Comment by shuichang** [comment]
配置错了,我第一次也这样，可以看一下配置吗

**Comment by jialifushi** [comment]
我的配置
<img width="665" alt="iShot2023-03-15 16 30 12" src="https://user-images.githubusercontent.com/101686929/225251824-9e1f948f-d11c-4bfb-a55f-7202b7b93148.png">
<img width="904" alt="iShot2023-03-15 16 32 19" src="https://user-images.githubusercontent.com/101686929/225251833-0e562a14-f495-45af-899d-80a393ff467c.png">
麻烦大佬看下这块怎么配置

**Comment by fireinrain** [comment]
connect timeout 你的机器是访问不了 api.openai.com 吗

**Comment by shuichang** [comment]
内部依赖库 undici 在连接时无法建立连接，看样子感觉是网络问题

**Comment by jialifushi** [comment]
澄清一下：群晖在A地点，人在B地点，我用云服务进行tcp代理的，能打开网页，但是一旦进行输入就如之前的图一样报错。

**Comment by jialifushi** [comment]
所以想要使用，必须群晖的网络环境能正常访问api.openai.com吗？那需要一直保持科学的环境才能使用吗？

**Comment by fireinrain** [comment]
打开网页 只是说明你再b能访问A，不代表从A发出去的请求能到openai.com或者是到他的代理

**Comment by jialifushi** [comment]
了解，谢谢。 那现在我该如何排查？设置这块需要改动吗？

**Comment by mushanzi1216** [comment]
请问使用docker部署时 怎么查看日志的

**Comment by 1403905696** [comment]
> 我的配置
> <img alt="iShot2023-03-15 16 30 12" width="665" src="https://user-images.githubusercontent.com/101686929/225251824-9e1f948f-d11c-4bfb-a55f-7202b7b93148.png">
> <img alt="iShot2023-03-15 16 32 19" width="904" src="https://user-images.githubusercontent.com/101686929/225251833-0e562a14-f495-45af-899d-80a393ff467c.png">
> 麻烦大佬看下这块怎么配置

请问最后解决了么？

**Comment by Chanzhaoyu** [comment]
> > 我的配置
> > <img alt="iShot2023-03-15 16 30 12" width="665" src="https://user-images.githubusercontent.com/101686929/225251824-9e1f948f-d11c-4bfb-a55f-7202b7b93148.png">
> > <img alt="iShot2023-03-15 16 32 19" width="904" src="https://user-images.githubusercontent.com/101686929/225251833-0e562a14-f495-45af-899d-80a393ff467c.png">
> > 麻烦大佬看下这块怎么配置
> 
> 请问最后解决了么？

解决办法是你服务上需要建立一个能连接 `OpenAI` 的代理。

**Comment by shuichang** [comment]
在你的群晖docker下安装一个openclash就行了，具体方法自行搜索，节点最好是美国的
