### ISSUE TITLE
个人信息可以本地修改再用 docker 打包，记录保存的话这个需要自己对接数据库哦。

### ISSUE THREAD

**Issue by JeazW** [Chanzhaoyu/chatgpt-web#606]
个人信息可以本地修改再用 docker 打包，记录保存的话这个需要自己对接数据库哦。

_Originally posted by @Chanzhaoyu in https://github.com/Chanzhaoyu/chatgpt-web/issues/597#issuecomment-1469229988_

**Comment by JeazW** [comment]
老板可不可以留个数据库预留配置，默认不配置。如果写了数据库配置的话保存json的时候可以选择保存到数据库😂。

**Comment by Chanzhaoyu** [comment]
`PR` 里有，你可以看看哈
