### ISSUE TITLE
准备支持GPT-4 API。

### ISSUE THREAD

**Issue by chenyuxiangyes** [Chanzhaoyu/chatgpt-web#609]
GPT-4 API 可能马上就要开放了。

**Comment by 7noemo** [comment]
等不及了， 我用docker版反代网站上，账号这俩天被停用了。

**Comment by wangxiaobo775** [comment]
> 等不及了， 我用docker版反代网站上，账号这俩天被停用了。

你好，请教一下如何使用反代实现plus 用户调用GPT-4
