### ISSUE TITLE
建议输出答案时，使用逐字输出。

### ISSUE THREAD

**Issue by chenyuxiangyes** [Chanzhaoyu/chatgpt-web#61]
这样就比较“有感觉”了。

**Comment by Chanzhaoyu** [comment]
感谢建议

**Comment by nothinggift** [comment]
chatgpt api应使用流式输出，然后反应到前端看到的就是逐字显示了
这里关键并不在于感觉，而是解决响应延迟问题
比如一个长回答，使用流式输出，比等待整个回答要快的多，也可以避免30秒的timeout限制

**Comment by Chanzhaoyu** [comment]
> chatgpt api应使用流式输出，然后反应到前端看到的就是逐字显示了 这里关键并不在于感觉，而是解决响应延迟问题 比如一个长回答，使用流式输出，比等待整个回答要快的多，也可以避免30秒的timeout限制

`dev` 分支已经在写处理「异常结果」和「重新生成」的功能，主要是前端方面优化

关于你说的流输出，一开始其实也规划了，之后会改动后端代码，但是优先级排后

**Comment by Chanzhaoyu** [comment]
功能已添加，请测试下 `stream` 分支

**Comment by Chanzhaoyu** [comment]
`issues` 关闭，功能在 `chatgpt-playground` 项目实验中
