### ISSUE TITLE
增加查看在线用户功能

### ISSUE THREAD

**Issue by lqs2019** [Chanzhaoyu/chatgpt-web#610]
是否可以增加查看在线用户功能，这样就可以查看他人使用情况，避免key被滥用

**Comment by SizheRee** [comment]
设置密钥就行

**Comment by herepost** [comment]
> 

不行呀，除非支持为每个用户单独设置密钥欸，不然密钥到处传播。都不知道多少人在线

**Comment by lqs2019** [comment]
不用吧，可以看在在线的ip就行（如果可以看到ip调用api情况更好哈哈），管理员可以对ip拉黑等操作

**Comment by SizheRee** [comment]
可以，还要弄个控制台。
