### ISSUE TITLE
建议对接Casdoor这种专业的单点登录方案

### ISSUE THREAD

**Issue by nomeguy** [Chanzhaoyu/chatgpt-web#612]
看到不少人有认证登录的需求：https://github.com/Chanzhaoyu/chatgpt-web/search?p=2&q=%E7%99%BB%E5%BD%95&type=issues ，也看到不少相关的PR，PR里大多数都是做了用户名、密码这种简单登录。

更完善的登录功能，建议通过对接开源的Casdoor单点登录系统来解决：https://github.com/casdoor/casdoor ，支持各类邮箱、手机验证码、QQ、微信登录、图形验证码等，有效防止非授权访问、盗刷流量等问题。还集成了支付宝、微信支付接口，方便把chatgpt web做成付费的服务

这里有个演示地址：https://door.casdoor.com/

**Comment by Chanzhaoyu** [comment]
不考虑哈，感谢建议，不会添加登录或者管理这方面的内容。

**Comment by zss2341** [comment]
如何实现对接呢？
