### ISSUE TITLE
服务器是不是被黑了

### ISSUE THREAD

**Issue by zhtordinary** [Chanzhaoyu/chatgpt-web#615]
服务器是不是被黑了，我的用量昨天飙增，然后我重置了密钥，重启了docker，测试了一条，就睡了，今早起来一看，半夜无间断到现在一直在用。我确信新的密钥只在这个服务上用过。

**Comment by jikeppq163** [comment]
会不会你的网址被别人扫描出来了关键字.
建议添加 AUTH_SECRET_KEY

**Comment by zhtordinary** [comment]
> 会不会你的网址被别人扫描出来了关键字. 建议添加 AUTH_SECRET_KEY

我看了下使用记录，是完全不间断的在使用，应该是api key被盗了？如果纯粹是网址泄漏出了，不至于不间断用吧，我朋友也是同样的情况

**Comment by Chanzhaoyu** [comment]
被人扫出来了，几个开源项目都被人疯狂爆破

**Comment by zhtordinary** [comment]
> 被人扫出来了，几个开源项目都被人疯狂爆破
用AUTH_SECRET_KEY可以避免被盗吗

**Comment by zhtordinary** [comment]
> 被人扫出来了，几个开源项目都被人疯狂爆破

用AUTH_SECRET_KEY能避免被盗吗？

**Comment by Chanzhaoyu** [comment]
> > 被人扫出来了，几个开源项目都被人疯狂爆破
> 
> 用AUTH_SECRET_KEY能避免被盗吗？

`README` 里面就有写，发公网一定要设置权限啊，兄弟

**Comment by kilvn** [comment]
配置了AUTH_SECRET_KEY，请求api也要认证的，可以彻底杜绝非授权访问请求

**Comment by DKingAlpha** [comment]
我也是API Key被盗了。这个key只有网站这里使用。网站的访问量很少，应该是key被泄露了。可能得审计下docker环境。

**Comment by Chanzhaoyu** [comment]
> 我也是API Key被盗了。这个key只有网站这里使用。网站的访问量很少，应该是key被泄露了。可能得审计下docker环境。

配置访问权限，这个项目一开源就被人扫描

**Comment by DKingAlpha** [comment]
> > 我也是API Key被盗了。这个key只有网站这里使用。网站的访问量很少，应该是key被泄露了。可能得审计下docker环境。
> 
> 配置访问权限，这个项目一开源就被人扫描

刚才查本机nginx转发日志没有异常访问日志，因为nginx套了basic auth。但查了下服务器流量，跟泄露时间段吻合，大概定位到泄露原因了。
docker的端口-p是直接映射到本机0.0.0.0的，应该是http无限制接口侧漏了。

@Chanzhaoyu 建议考虑优化REAME里的docker端口转发指导
