### ISSUE TITLE
未经授权，请先进行验证

### ISSUE THREAD

**Issue by ludejun-666** [Chanzhaoyu/chatgpt-web#616]
未经授权，请先进行验证
![Uploading 123.png…]()

**Comment by ludejun-666** [comment]
![123](https://user-images.githubusercontent.com/123106415/225490999-1c1b6f6f-6e07-4eca-b402-8a632c937443.png)

**Comment by JeazW** [comment]
这是配置文件里设置了密码，去看一下，也可以自己改密码，也可以取消密码

**Comment by ludejun-666** [comment]
好的，谢谢解决了

**Comment by wxy015513** [comment]
怎么解决的，请求帮助

**Comment by Chanzhaoyu** [comment]
> 怎么解决的，请求帮助

检查你的配置文件，`AUTH_SECRET_KEY` 是否有被配置。
