### ISSUE TITLE
使用DockerFile 部署  显示 undefined [fetch failed]  怎么解决

### ISSUE THREAD

**Issue by zzdnb** [Chanzhaoyu/chatgpt-web#619]
配置文件如下：
```shell
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: FJW2QxIumOulmqd8cOfJBb
      # 二选一
      OPENAI_ACCESS_TOKEN:
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://api.openai.com
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: gpt-3.5-turbo
      # 反向代理，可选
      API_REVERSE_PROXY: https://bypass.duti.tech/api/conversation
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: 123
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST:
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT:
      # HTTPS 代理，可选，支持 http，https，socks5
      HTTPS_PROXY:

```

![](https://img1.imgtp.com/2023/03/16/y1F1Upm8.png)
![](https://img1.imgtp.com/2023/03/16/rW5jrWea.png)

**Comment by Pauluooooo** [comment]
遇到了同样的问题，但是报错不一样；使用的docker-compose部署，之前好好的，今天更新了一下就这样了
`TypeError: fetch failed
	at Object.fetch (node:internal/deps/undici/undici:11413:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    atfetchSSE(/app/node_modules/.pnpm/chatgpt5.0.10/node_modules/chatgpt/build/index.js:46:15{
   cause: Error: getaddrinfo EAI_AGAIN api.openai.com
       at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
       at __node_internal_ (node:internal/errors:712:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
     errno: -3001,
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'api.openai.com'
   }
}`

**Comment by reccrea** [comment]
看着像是网络代理的问题， 我也遇到了

**Comment by idsunb** [comment]
同样遇到问题，是什么原因导致的呢

**Comment by VectorZhao** [comment]
就刚刚用着用着就开始提示`fetch failed`
