### ISSUE TITLE
timeout30秒太少了

### ISSUE THREAD

**Issue by Pandaver** [Chanzhaoyu/chatgpt-web#62]
如题，axios 超时时间设置的太短，问题一复杂就容易导致超时，请加长
![截图_20230219155516](https://user-images.githubusercontent.com/62326552/219936029-d723d8fe-1aa8-41b7-9e3f-28649b172215.png)

**Comment by Chanzhaoyu** [comment]
可在 `axios.ts` 第 `5` 行自行修改，我加个重新提交的按钮吧

**Comment by LuckyZY** [comment]
像Docker容器如何修改这个时间？

**Comment by Chanzhaoyu** [comment]
> 像Docker容器如何修改这个时间？

这个没有添加参数，你可以暂时在本地修改 `docker build`

**Comment by mobile17682318557** [comment]
> 可在 `axios.ts` 第 `5` 行自行修改，我加个重新提交的按钮吧

我修改了这个参数，设置了1个小时，为什么前端还是2分多钟后就放弃了请求，我看后端接口最后是给出了响应的，但是前端先给了net error

**Comment by Pandaver** [comment]
> > 可在 `axios.ts` 第 `5` 行自行修改，我加个重新提交的按钮吧
> 
> 我修改了这个参数，设置了1个小时，为什么前端还是2分多钟后就放弃了请求，我看后端接口最后是给出了响应的，但是前端先给了net error

`/service/src/chatgpt.ts` 第35行 `timeoutMs` 改大

**Comment by Chanzhaoyu** [comment]
已添加环境变量 `TIMEOUT_MS`
