### ISSUE TITLE
现在新开的plus订阅都不能绕过cf了

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#620]
官方已经修复漏洞了，这意味着新的plus订阅号不能自建类似这样的（https://bypass.duti.tech/api/conversation ） 
  token web代理了
之前开了plus订阅，并且已经保存了puid信息的，现在已经是绝版号了,现在重新获取的puid都不能过cf防火墙。

**Comment by XiaoApi** [comment]
cookie有有效期.

**Comment by ludashi2020** [comment]
> cookie有有效期.

puid貌似一直有效，只要这个就可以了

**Comment by davyvision** [comment]
实测可以，可能token有有效期，到期换一个就行了。

**Comment by ludashi2020** [comment]
> 实测可以，可能token有有效期，到期换一个就行了。

确实可以，你是对的。结贴。

**Comment by wujt1084** [comment]
![image](https://user-images.githubusercontent.com/127291078/228499670-4bc9aab1-eb9a-4d7c-8674-8c674be6ce8c.png)
弱弱问下怎么配

**Comment by wujt1084** [comment]
怎么取
