### ISSUE TITLE
从昨天开始开始封号？？

### ISSUE THREAD

**Issue by w8193277** [Chanzhaoyu/chatgpt-web#621]
使用API方式部署，一开始日本服务器部署，国内访问，半小时ban掉。（我的老号。。。
今天换了一个新号，继续日本服务器部署，日本本地访问，半小时ban掉。。。
有可能是官方更新了检测机制，还在找原因中。
![image](https://user-images.githubusercontent.com/3852358/225517466-d20e55b5-3fe0-4c1a-a22b-535f1f47ea8e.png)

**Comment by jikeppq163** [comment]
有没有用过代理?我现在部署到新加坡,暂时使用良好,没有用代理,调用api key方式.

**Comment by chnaan** [comment]
我的腾讯云新加坡docker部署，api key调用，两三个号都被封了，不知道什么原因

**Comment by ChandlerVer5** [comment]
别使用 国内邮箱，使用 gmail + 美国号码

**Comment by hnuzhoulin** [comment]
同是日本服务器慌慌啊，老号是啥时候的？

**Comment by Chanzhaoyu** [comment]
封号规则：
1. 不在服务区域内
2. 同 IP 多账号
4. 和注册手机号不在同区域或 3 地

**Comment by rhymed-liu** [comment]
我也是阿里云新加坡 没任何问题

**Comment by shuncon** [comment]
我也是阿里云新加坡 没任何问题，用微软账号(老号)注册的，

**Comment by bluefrankey** [comment]
我的是美国IP nginx代理 api key 也被ban掉

**Comment by jkhcc11** [comment]
跑Api的还是用120刀的号比普通的5刀和之前18刀的稳定，现在5刀和18刀的号，寄的比较快。在供货商那边了解到的情况是这样

**Comment by bluefrankey** [comment]
120刀的号不是真的有120刀 是限额消费120刀吧

**Comment by jkhcc11** [comment]
> 

对的，是120刀额度 那种号，那种比较持久

**Comment by bluefrankey** [comment]
没用。我的就是120刀额度的 用api被ban    只能用accessToken了

**Comment by jkhcc11** [comment]
> 没用。我的就是120刀额度的 用api被ban 只能用accessToken了

单Ip 120刀  用了多少封的么？

**Comment by herepost** [comment]
> 有没有用过代理?我现在部署到新加坡,暂时使用良好,没有用代理,调用api key方式.

现在还是好的吗

**Comment by lsubaa** [comment]
美国ip，搭建好 10分钟就被封号了......

**Comment by jkhcc11** [comment]
> 



> 美国ip，搭建好 10分钟就被封号了......

还好吧，我用之前的16$的，然后也是漂亮国的服务器，用了好多天了。现在正在试120$的账号，会不会封的厉害。
测试地址：https://ai-public.kdy666.com  目前是用的120$的号。
建议不要用国内云商的vps。 dddd

**Comment by maxadc** [comment]
用accessToken 的貌似被封了界面不开看不到聊天，看控制台返回500错误。但该账号在美国服的api token还可以用！

**Comment by ShaunYeh** [comment]
请问120$的账号怎么获得？

**Comment by ShaunYeh** [comment]
> > 
> 
> > 美国ip，搭建好 10分钟就被封号了......
> 
> 还好吧，我用之前的16$的，然后也是漂亮国的服务器，用了好多天了。现在正在试120$的账号，会不会封的厉害。 测试地址：https://ai-public.kdy666.com 目前是用的120$的号。 建议不要用国内云商的vps。 dddd

请问120$的号怎么获得

**Comment by jkhcc11** [comment]
> > > 
> > 
> > 
> > > 美国ip，搭建好 10分钟就被封号了......
> > 
> > 
> > 还好吧，我用之前的16$的，然后也是漂亮国的服务器，用了好多天了。现在正在试120$的账号，会不会封的厉害。 测试地址：https://ai-public.kdy666.com 目前是用的120$的号。 建议不要用国内云商的vps。 dddd
> 
> 请问120$的号怎么获得

我用120$和16$得都试了几天，没啥毛病。在这里搞的，不晓得还有没有货。http://i6z.cn/G4es
