### ISSUE TITLE
ChatGPT error 429

### ISSUE THREAD

**Issue by taomrzhang** [Chanzhaoyu/chatgpt-web#622]
请问这是什么问题呢？该如何解决呢？
ChatGPT error 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by inowfeellonely** [comment]
我也出现了这个问题

**Comment by iamflowerdog** [comment]
我也是

**Comment by iamflowerdog** [comment]
兄弟们，我知道咋回事儿了，把 OPENAI_API_KEY 删掉，只保留OPENAI_ACCESS_TOKEN 就可以了，因为OPENAI_API_KEY 收费的，你的账号没充值或则免费额度$18过期了

**Comment by iRoZhi** [comment]
> 

用OPENAI_ACCESS_TOKEN ，提示服务器错误。。

**Comment by Chanzhaoyu** [comment]
付费提示

**Comment by MataSong** [comment]
OPENAI_ACCESS_TOKEN  如何获取呢？ @iamflowerdog

**Comment by Chanzhaoyu** [comment]
> OPENAI_ACCESS_TOKEN 如何获取呢？ @iamflowerdog

看 `README`
