### ISSUE TITLE
不用后端接口，怎么配置

### ISSUE THREAD

**Issue by wxwyes** [Chanzhaoyu/chatgpt-web#623]
我只运行了前端，不想用后端，前端运行起来了，访问报错如下错误，有遇到的吗？怎么解决？：

14:01:18 [vite] http proxy error at /session:
Error: connect ECONNREFUSED 127.0.0.1:3002
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) (x3)

**Comment by Chanzhaoyu** [comment]
因为进入页面会请求一次 seesion 这个接口，你要把前端关于 `auth` 的删除

**Comment by yinhaixiang** [comment]
我也遇到了同样的问题, 能详细说下怎么操作吗

**Comment by x-cy** [comment]
> 因为进入页面会请求一次 seesion 这个接口，你要把前端关于 `auth` 的删除

这个具体要删哪里？

**Comment by x-cy** [comment]
问题已解决，在判断是否获取到session的地方，把!去掉就行，找了半天
