### ISSUE TITLE
下载图片是空的

### ISSUE THREAD

**Issue by xinmans** [Chanzhaoyu/chatgpt-web#624]
Version - 2.10.5![image](https://user-images.githubusercontent.com/2713008/225530790-05680596-0f04-4d8d-94bf-7b6b58a5f66a.png)

**Comment by Chanzhaoyu** [comment]
保存的后缀错误

**Comment by xinmans** [comment]
ipad上默认是这个后缀，pc上是好的

**Comment by DragonRollGH** [comment]
ios上图片太长就会这样，很短就正常
