### ISSUE TITLE
[[OpenAI] 提供错误的API密钥 | Incorrect API key provided]

### ISSUE THREAD

**Issue by fastslow** [Chanzhaoyu/chatgpt-web#625]
2.10.5 railway部署返回这个未定义
undefined
[[OpenAI] 提供错误的API密钥 | Incorrect API key provided]
使用的OPENAI_ACCESS_TOKEN。重新设置变量后也不行。

**Comment by wwlmm** [comment]
你的账号被封了

**Comment by Chanzhaoyu** [comment]
token 不要再用了，今天开始封号了

**Comment by ludashi2020** [comment]
我的没有封，自建token代理，开plus订阅，服务区内ip

**Comment by alitrack** [comment]
> 

能详细些吗？

**Comment by expfukck** [comment]
> 我的没有封，自建token代理，开plus订阅，服务区内ip

哥们 能教下 怎么token代理搭建吗

**Comment by jkhcc11** [comment]
> > 我的没有封，自建token代理，开plus订阅，服务区内ip
> 
> 哥们 能教下 怎么token代理搭建吗

+1

**Comment by xiaotailang0417** [comment]
> 

+1
