### ISSUE TITLE
为大家贡献一张 chatgpt 网络访问拓扑图

### ISSUE THREAD

**Issue by mouyong** [Chanzhaoyu/chatgpt-web#626]
https://chat.hwecs.iwnweb.com/

https://github.com/zhayujie/bot-on-anything/issues/143

![image](https://user-images.githubusercontent.com/10336437/225561136-23297db4-ae50-400f-b48f-ef4aee1f15d4.png)

期望有注册登录功能，方便在不同设备之间同步聊天记录。

**Comment by ludashi2020** [comment]
注册功能在这里https://github.com/Chanzhaoyu/chatgpt-web/pull/589
