### ISSUE TITLE
railway 配置报错，帮我看一下是不是配置没有写好

### ISSUE THREAD

**Issue by iamflowerdog** [Chanzhaoyu/chatgpt-web#628]
![image](https://user-images.githubusercontent.com/27678693/225579510-e8de691f-04e9-4601-84f9-594becbc870d.png)
![image](https://user-images.githubusercontent.com/27678693/225579625-a7601426-5227-430c-a3de-0140163cd845.png)

**Comment by iamflowerdog** [comment]
![image](https://user-images.githubusercontent.com/27678693/225584818-b504b263-b880-42ef-aaba-69ac4d4bc903.png)

**Comment by iamflowerdog** [comment]
![image](https://user-images.githubusercontent.com/27678693/225586556-ec3a91c4-c8f0-42c7-af80-09fc60787c1c.png)

**Comment by iamflowerdog** [comment]
![image](https://user-images.githubusercontent.com/27678693/225588063-676b82f6-c7a8-48a7-8218-78cac90832b3.png)

**Comment by toughhou** [comment]
@iamflowerdog  请问这个问题是怎么解决的？我的也是请求到了本地代理的地址127.0.0.1:7890，但我已经把这个设置注释了。
<img width="569" alt="image" src="https://user-images.githubusercontent.com/7472236/226526825-ad569dd7-ce0a-4665-8272-1316e91fe930.png">
