### ISSUE TITLE
docker启动后老是提示api秘钥错误

### ISSUE THREAD

**Issue by yanpengfei-git** [Chanzhaoyu/chatgpt-web#629]
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/37141737/225584578-ea2e1d32-816e-4d22-a432-881f6fbd503a.png">

用的docker命令 启动后 老是提示api秘钥错误
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/37141737/225584362-c1db912f-ccda-43c3-b6db-54aa34854754.png">

**Comment by wwlmm** [comment]
出现这种 说明你的账号完蛋了

**Comment by yanpengfei-git** [comment]
> 出现这种 说明你的账号完蛋了

用了其他的开源项目，还能访问呀
