### ISSUE TITLE
使用railway搭建会出现(POST /v1/chat/completions这个问题,参数都填写了,请问怎么解决

### ISSUE THREAD

**Issue by jykSS** [Chanzhaoyu/chatgpt-web#631]
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/49031577/225598003-d27fadd2-dc09-4de2-81b7-4edd88b0e0ed.png">
<img width="520" alt="image" src="https://user-images.githubusercontent.com/49031577/225598054-d4a52355-6bdb-4de4-bd33-b79f4b59e9bd.png">

**Comment by DragonRollGH** [comment]
删去BASE_URL和MODEL变量试试

**Comment by jykSS** [comment]
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/49031577/225601450-efba339f-1bad-41d2-8176-45c471220f91.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/49031577/225601501-cf03bd67-33f4-452c-88d3-88f182d96804.png">

**Comment by Chanzhaoyu** [comment]
删除 BASEURL 和 MODEL 以后重新部署，删除浏览器缓存，Railway 的浏览器缓存很严重。

**Comment by jykSS** [comment]
还是不行,我换了个机器 换了一个浏览器重新部署还是这样

**Comment by jykSS** [comment]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/49031577/225630579-680349cf-0f51-4c5d-b768-0ef0e5f5f89b.png">

**Comment by LanQian528** [comment]
换个key就行了，我的也这样

**Comment by jykSS** [comment]
我换了key了还是这个问题,是不是要换账号

**Comment by JeazW** [comment]
我升级后也出现了这个问题

**Comment by zedpass** [comment]
我是用 docker 部署的服务，OPENAI_API_BASE_URL 使用了 cloudflare  workers 绑定的域名，今天升级到新版本后也遇到了同样的问题，回滚到 v2.10.5 版本后使用正常

**Comment by JeazW** [comment]
我删除重新部署已经好了，请浏览器缓存
![image](https://user-images.githubusercontent.com/75829171/225807530-8b6ac218-25e1-404e-9126-28f717759143.png)

**Comment by Chanzhaoyu** [comment]
> 我是用 docker 部署的服务，OPENAI_API_BASE_URL 使用了 cloudflare workers 绑定的域名，今天升级到新版本后也遇到了同样的问题，回滚到 v2.10.5 版本后使用正常

已经修复

**Comment by me4p0** [comment]
请问怎么删除BASE_URL和MODEL

**Comment by DragonRollGH** [comment]
> 请问怎么删除BASE_URL和MODEL

不添加这两个环境变量就好了

**Comment by me4p0** [comment]
谢谢

**Comment by jykSS** [comment]
确实是账号问题,换了一个账号就好了,可能代码的提示错误不明确,希望明确下错误原因,可以提供下失败账号的key,作者可以测试下
