### ISSUE TITLE
生成代码被截断的问题

### ISSUE THREAD

**Issue by ipengyo** [Chanzhaoyu/chatgpt-web#634]
当回复的代码不完整时，回复继续，此时代码的显示就乱套了。。

如图：

![image](https://user-images.githubusercontent.com/9323722/225640897-5a58e700-ace3-4482-b5ef-82f53d233f52.png)

**Comment by JeazW** [comment]
官方网页版也会发生这种事

**Comment by luojiannx** [comment]
"继续，代码请用markdown包起来。"这样可以解决

**Comment by ipengyo** [comment]
> "继续，代码请用markdown包起来。"这样可以解决

谢谢原来如此！！

**Comment by tianstephanie** [comment]
我试了好像不行，它会认为你有新的需求，又重写了编代码

**Comment by yi-ge** [comment]
开启长回复即可。

**Comment by tianstephanie** [comment]
请问怎么才能开启长回复？

**Comment by yi-ge** [comment]
@tianstephanie 请参考<https://github.com/Chanzhaoyu/chatgpt-web/pull/450>，后续会整理到README.md

**Comment by tianstephanie** [comment]
收到！太感谢了 👍👍👍👍👍

**Comment by goodwisdom** [comment]
> @tianstephanie 请参考<https://github.com/Chanzhaoyu/chatgpt-web/pull/450>，后续会整理到README.md

反馈下，在根目录.env中开启长回复后，打包doker镜像安装，功能并未生效，只有在非doker安装方式下才测试成功过，估计是有bug

**Comment by yi-ge** [comment]
@goodwisdom docker里面的前端是已经编译后的

**Comment by goodwisdom** [comment]
> @goodwisdom docker里面的前端是已经编译后的

我是复刻的项目，自己修改.env文件后，自己打包成docker镜像安装的，如果这样不行，可否指点下如何修改文件，再打包成镜像才可以呢？

**Comment by goodwisdom** [comment]
> 打包之前先编译前端，另外回退版本到上一个版本，新版本好像回退了chatgpt的版本

这个就复杂了，不太会，可否优化下，让这个功能更容易调用呢，我看不少小伙伴都需要这个功能

**Comment by yi-ge** [comment]
在优化的，正在测试接口

**Comment by goodwisdom** [comment]
> 在优化的，正在测试接口

期待中，感谢
