### ISSUE TITLE
前端打包放上服务器后报错

### ISSUE THREAD

**Issue by Laixinsz** [Chanzhaoyu/chatgpt-web#635]
服务端用独立的服务器，已修改前端.env配置文件里面的地址，本地运行正常，打包过程也正常，但放上服务器后访问报错，页面空白。
![image](https://user-images.githubusercontent.com/69241339/225685503-cc93e77c-2634-4d2a-82d2-c81f9498633a.png)

**Comment by laphylee** [comment]
@Laixinsz  您好，我也遇到了这个问题，请问是如何解决的呢？
