### ISSUE TITLE
关于chatGPT会话记录功能如何实现

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [Chanzhaoyu/chatgpt-web#638]
因为最近chatGPT官网太过卡顿，导致自己无法使用它，但是我发现用api接口还算稳定。之前部分功能已经完善。所以想完成一下会话记录功能，方便自己使用。希望大佬感到指点一下，推荐一些博客也可以。感谢

**Comment by slieer** [comment]
#604
