### ISSUE TITLE
大佬，docker部署的，一直三个小球弹来弹去

### ISSUE THREAD

**Issue by nbyy123123** [Chanzhaoyu/chatgpt-web#64]
大佬，docker部署的，一直停留在三个小球弹来弹去的界面上。

**Comment by Chanzhaoyu** [comment]
这是没部署成功，前端页面没进去

**Comment by nbyy123123** [comment]
感谢回复。电脑正常访问，并且非常赞！！！手机，三个小球撞来撞去的。

**Comment by nbyy123123** [comment]
很丢人啊！！！我手机的事，ios12的。昨晚躺床上拿小手机鼓捣的。大佬的项目很赞！！今早拿正常用的手机访问，没毛病！！界面清新，响应迅捷！！赞赞赞！！！
