### ISSUE TITLE
支持4.0了吗，大佬们

### ISSUE THREAD

**Issue by wujt1084** [Chanzhaoyu/chatgpt-web#643]

**Comment by yi-ge** [comment]
申请到API了么？

**Comment by bksy0909** [comment]
等待大佬大作

**Comment by highhhope** [comment]
![image](https://user-images.githubusercontent.com/14657224/225995524-b758ff78-7b6b-4609-9f77-eb2b6d45ece0.png)
今天收到邮件了，蹲一个更新

**Comment by bs10081** [comment]
![image](https://user-images.githubusercontent.com/38148679/226075804-3f0ebe17-bbcb-4857-a4e1-f7c715ee76fd.jpeg)

期待支持GPT-4

**Comment by WeihanLi** [comment]
期待支持GPT-4 +1

**Comment by yrz2015** [comment]
申请到了的话，应该直接把模型换了就行吧。

**Comment by chen2438** [comment]
可以的，直接换模型就行

![image](https://user-images.githubusercontent.com/53367039/226079806-8770d163-d0f2-4424-a83e-3ade60385069.png)

![image](https://user-images.githubusercontent.com/53367039/226079871-77b98d7b-8834-4587-ad6f-105b4360b925.png)

**Comment by yi-ge** [comment]
我还没有收到邮件😂

**Comment by xuzhounan** [comment]
请问这个怎么解决呀
`ChatGPT error 404: {
"error": {
"message": "The model: gpt-4-0314 does not exist",
"type": "invalid_request_error",
"param": null,
"code": "model_not_found"
}
}`

**Comment by Clearave** [comment]
> 请问这个怎么解决呀 `ChatGPT error 404: { "error": { "message": "The model: gpt-4-0314 does not exist", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }`

模型名字试试直接 gpt-4

**Comment by Colwzq** [comment]
> 可以的，直接换模型就行
> 
> ![image](https://user-images.githubusercontent.com/53367039/226079806-8770d163-d0f2-4424-a83e-3ade60385069.png)
> 
> ![image](https://user-images.githubusercontent.com/53367039/226079871-77b98d7b-8834-4587-ad6f-105b4360b925.png)

大佬方便告知如何换模型吗，是不是没通过申请GPT4的看不到你这个页面

**Comment by chen2438** [comment]
> > 可以的，直接换模型就行
> > ![image](https://user-images.githubusercontent.com/53367039/226079806-8770d163-d0f2-4424-a83e-3ade60385069.png)
> > ![image](https://user-images.githubusercontent.com/53367039/226079871-77b98d7b-8834-4587-ad6f-105b4360b925.png)
> 
> 大佬方便告知如何换模型吗，是不是没通过申请GPT4的看不到你这个页面

要先在 https://openai.com/waitlist/gpt-4-api 填写申请，通过后模型更改为 gpt-4

**Comment by Colwzq** [comment]
> > > 可以的，直接换模型就行
> > > ![image](https://user-images.githubusercontent.com/53367039/226079806-8770d163-d0f2-4424-a83e-3ade60385069.png)
> > > ![image](https://user-images.githubusercontent.com/53367039/226079871-77b98d7b-8834-4587-ad6f-105b4360b925.png)
> > 
> > 
> > 大佬方便告知如何换模型吗，是不是没通过申请GPT4的看不到你这个页面
> 
> 要先在 https://openai.com/waitlist/gpt-4-api 填写申请，通过后模型更改为 gpt-4

请问是在openai官网进行更换还是需要修改源代码（因为我看到openai官网是要自己输入model请求的），我目前是docker部署的可以操作吗。

**Comment by chen2438** [comment]
> > > > 可以的，直接换模型就行
> > > > ![image](https://user-images.githubusercontent.com/53367039/226079806-8770d163-d0f2-4424-a83e-3ade60385069.png)
> > > > ![image](https://user-images.githubusercontent.com/53367039/226079871-77b98d7b-8834-4587-ad6f-105b4360b925.png)
> > > 
> > > 
> > > 大佬方便告知如何换模型吗，是不是没通过申请GPT4的看不到你这个页面
> > 
> > 
> > 要先在 https://openai.com/waitlist/gpt-4-api 填写申请，通过后模型更改为 gpt-4
> 
> 请问是在openai官网进行更换还是需要修改源代码（因为我看到openai官网是要自己输入model请求的），我目前是docker部署的可以操作吗。

申请通过后，在docker-compose.yaml的参数中作如下改动：

```yaml
# API模型，可选，设置 OPENAI_API_KEY 时可用
OPENAI_API_MODEL: gpt-4
```

不需要任何其他操作。

**Comment by Colwzq** [comment]
> > > > > 可以的，直接换模型就行
> > > > > ![image](https://user-images.githubusercontent.com/53367039/226079806-8770d163-d0f2-4424-a83e-3ade60385069.png)
> > > > > ![image](https://user-images.githubusercontent.com/53367039/226079871-77b98d7b-8834-4587-ad6f-105b4360b925.png)
> > > > 
> > > > 
> > > > 大佬方便告知如何换模型吗，是不是没通过申请GPT4的看不到你这个页面
> > > 
> > > 
> > > 要先在 https://openai.com/waitlist/gpt-4-api 填写申请，通过后模型更改为 gpt-4
> > 
> > 
> > 请问是在openai官网进行更换还是需要修改源代码（因为我看到openai官网是要自己输入model请求的），我目前是docker部署的可以操作吗。
> 
> 申请通过后，在docker-compose.yaml的参数中作如下改动：
> 
> ```yaml
> # API模型，可选，设置 OPENAI_API_KEY 时可用
> OPENAI_API_MODEL: gpt-4
> ```
> 
> 不需要任何其他操作。

感谢您的耐心解答，我已经明白了。

**Comment by qyjgg** [comment]
4.0的api是怎么收费的
