### ISSUE TITLE
更新到2.10.6回复报错的看这里

### ISSUE THREAD

**Issue by LanQian528** [Chanzhaoyu/chatgpt-web#644]
后端api似乎有修改，因此反代地址需要加上“/v1”后方可。
![M6AWF2NYA8HCWGRNF8HCVK5](https://user-images.githubusercontent.com/5499636/225809058-eec4d7cd-9749-4efe-a2c9-b2ba058dcc41.png)
如上图即可

**Comment by Chanzhaoyu** [comment]
赞👍
