### ISSUE TITLE
有没有大佬给个配置可注册的详细教程（来自小白的请教）

### ISSUE THREAD

**Issue by DemonRR** [Chanzhaoyu/chatgpt-web#645]
有没有大佬给个配置可注册的详细教程（来自小白的请教）

**Comment by appotry** [comment]
注册教程？ 看这里 [中国区注册ChatGPT并使用全流程图解教程](https://blog.17lai.site/posts/1336c869/)

**Comment by DemonRR** [comment]
> 注册教程？ 看这里 [中国区注册ChatGPT并使用全流程图解教程](https://blog.17lai.site/posts/1336c869/)

是添加注册&登陆的教程

**Comment by ottocsb** [comment]
有个issue提到的分支有注册登录，自己翻下

**Comment by Chanzhaoyu** [comment]
如果是小白的话，就不建议开发注册登录了
