### ISSUE TITLE
是否有计划前后端分开来创建Dockerfile?

### ISSUE THREAD

**Issue by JinhuW** [Chanzhaoyu/chatgpt-web#646]
@Chanzhaoyu 想看看owner的看法 
主要是可以放在一些自带静态页面加速的免费平台部署

我可以来做 想问问意见

**Comment by Chanzhaoyu** [comment]
做倒是很简单，但是用的人比较多，而且很多都是用的 Docker，所以小版本不敢调动文件位置。一开始为了方便，但是目前看来是错误的。或者改为 Next.js 或者 Nuxt.js 会是个好选择。
