### ISSUE TITLE
加了Balance功能后，配置页面一直刷不出来

### ISSUE THREAD

**Issue by Pandoxie** [Chanzhaoyu/chatgpt-web#647]
![image](https://user-images.githubusercontent.com/4418547/225816239-1d1198e3-cb90-4e0c-bf61-a7b387943be4.png)
挂不挂vpn都刷不出来。过了好一会儿就显示空白页面。
![image](https://user-images.githubusercontent.com/4418547/225816378-d73f01ef-aa57-4f3b-b0b1-61df0cd553b3.png)

**Comment by letianpai-lpt** [comment]
跟踪一下,也是这样

**Comment by Chanzhaoyu** [comment]
部署在国内还是国外，是否自建代理，pull 下最新的 latest 再试一下。

**Comment by goodwisdom** [comment]
> 部署在国内还是国外，是否自建代理，pull 下最新的 latest 再试一下。

重新拉取后，可以刷出了

**Comment by Pandoxie** [comment]
> 部署在国内还是国外，是否自建代理，pull 下最新的 latest 再试一下。

谢谢提醒，重新pull下并且强制刷新chrome缓存后可以了。
