### ISSUE TITLE
希望大佬能支持在accessToken模式下，plus用户调用gpt 4.0模型。

### ISSUE THREAD

**Issue by wangxiaobo775** [Chanzhaoyu/chatgpt-web#649]
目前，plus用户官方已经支持了gpt 4.0，且几乎不会受到cloudflare防火墙的骚扰。
然而项目调用的还是3.5 turbo，无法调用4.0。
因此希望大佬能支持在accessToken模式下，plus用户调用gpt 4.0模型。

**Comment by eflylab** [comment]
应该是没可能了，token的方式可能快下线了，有封号的风险。

**Comment by yi-ge** [comment]
API版本马上上线了。

**Comment by FishGiter** [comment]
尽量别用，我用两天就封号了

**Comment by yeenjie123456** [comment]
> 尽量别用，我用两天就封号了

session方式个人正常使用不共享也会被封号吗😂好怕

**Comment by Chanzhaoyu** [comment]
main 分支添加了
