### ISSUE TITLE
chat-process增加鉴权

### ISSUE THREAD

**Issue by praiseqin** [Chanzhaoyu/chatgpt-web#650]
请在chat-process接口的URL或header支持鉴权，目前密码访问鉴权仅对前端界面有效，对接口无效；

**Comment by Chanzhaoyu** [comment]
你用的哪个版本？现在就是 `header` 携带 `token` 进行鉴权啊

**Comment by praiseqin** [comment]
> 

失误了，刚注意到header里是带的明文token（是不是不太好？）

**Comment by Chanzhaoyu** [comment]
> > 
> 
> 失误了，刚注意到header里是带的明文token（是不是不太好？）

明不明文没必要吧，毕竟没有注册登录这种功能。不过如果想不明文很简单，工具文件夹里面有 `CryptoJS` 的方法，自己改造下就好了。
