### ISSUE TITLE
API余额

### ISSUE THREAD

**Issue by fk-qing** [Chanzhaoyu/chatgpt-web#651]
我直接使用docker运行的，这里的API余额是指？
![image](https://user-images.githubusercontent.com/82891033/225825136-78dfec24-267f-411e-81dd-3c02f365b150.png)

**Comment by Chanzhaoyu** [comment]
你猜

**Comment by fk-qing** [comment]
> 你猜

可是我配置了api的，不应该是没有余额的嘛，我在本地和另一个服务器上是没有这个展示的，

我的启动命令是这样：
docker run --name chatgpt-web -d -p 80:3002 --env OPENAI_API_KEY=... chenzhaoyu94/chatgpt-web

我猜不到，给点新手的提示呗

**Comment by Chanzhaoyu** [comment]
这个就是你的 API 余额啊

**Comment by ggfvictor** [comment]
通过token方式连接的不会显示余额

**Comment by fk-qing** [comment]
> 这个就是你的API 余额啊

我刚刚才知道有赠送余额。我竟然以为api是免费的。我明白了。汗

**Comment by tianstephanie** [comment]
不光有余额，还有时间限制
