### ISSUE TITLE
回退版本 代理依旧不生效

### ISSUE THREAD

**Issue by Everytimeyumi** [Chanzhaoyu/chatgpt-web#652]
![image](https://user-images.githubusercontent.com/30947975/225830093-2f2f6be9-ef3d-4153-b45e-d1a7822fa699.png)
![image](https://user-images.githubusercontent.com/30947975/225830216-f0919f75-b9e4-4553-8e6d-db024ab32d4e.png)
版本回退  还是不能连接

**Comment by leo9960** [comment]
手动更新一下service/node_modules/chatgpt/build/index.js里的反代地址，apiReverseProxyUrl = "https://bypass.duti.tech/api/conversation"

**Comment by Everytimeyumi** [comment]
> apiReverseProxyUrl = " https://bypass.duti.tech/api/conversation "

版本回退了就是这个地址
