### ISSUE TITLE
配置页加载不出来

### ISSUE THREAD

**Issue by letianpai-lpt** [Chanzhaoyu/chatgpt-web#653]
2.10.7版本，也试过拉最新的代码去build，使用docker build后部署，国内服务器，自建代理，其他功能均正常，配置页一直转圈，最后各项都是  -
![Screenshot_20230317144328](https://user-images.githubusercontent.com/96228495/225831924-cae96d2c-eb1e-4e4a-9b06-7691631fce94.jpg)

**Comment by CLAY-CMD** [comment]
我也是这样，配置页一直在转圈加载

**Comment by jikeppq163** [comment]
估计是查询余额,配置页也只有这一项功能需要调用接口.

**Comment by CLAY-CMD** [comment]
我觉得应该是调用查询余额链接的时候，默认是使用的是api.openai.com，我是用的Cloudflare Worker自建的反代。所以说要是替换默认的api接口地址，应该是可以的

**Comment by letianpai-lpt** [comment]
是查询余额的时候没走代理吗还是什么原因呢

**Comment by letianpai-lpt** [comment]
解决了，是我自己的问题，没看见代理有了all-proxy，还是用的之前的socket的，导致连不上
