### ISSUE TITLE
会话输出问题

### ISSUE THREAD

**Issue by zxitedu** [Chanzhaoyu/chatgpt-web#654]
产品非常赞 但是在使用的过程中遇到了一些问题 使用的是自己的openapi 在使用的过程中，遇到了几次输出不全的问题，回答到一半就停止了，还有就是可以改成流式输出吗 这样观感上会快很多 @Chanzhaoyu

**Comment by zxitedu** [comment]
现在是不是已经就是流式输出了，但为啥会感觉一卡一卡的😂，使用 Railway 部署的

**Comment by Chanzhaoyu** [comment]
Railway 不需要代理应该不卡啊～

**Comment by zxitedu** [comment]
> Railway 不需要代理应该不卡啊～

是 按照理论上应该是不卡的，但是确实比较慢，回答着然后卡住了 突然出来一大串文字，我不知道是不是跟api有没有关系，我感觉发布了GPT4之后 3.5的就没有之前快了😂
