### ISSUE TITLE
打开几天前的会话框继续聊天，它丢失上下文关联

### ISSUE THREAD

**Issue by flyMDW** [Chanzhaoyu/chatgpt-web#655]
打开几天前的对话框，继续聊天发现它丢失了上下文关联，回答不再和以前的聊天记录有关了。

请问这个是什么原因？

**Comment by ottocsb** [comment]
如果是最新版本镜像默认下方的连续上下文开关是关闭的红色，其他版本不清楚了

**Comment by flyMDW** [comment]
是低版本的，下方没有关闭上下文的按钮

> 如果是最新版本镜像默认下方的连续上下文开关是关闭的红色，其他版本不清楚了

**Comment by Chanzhaoyu** [comment]
服务器重启了吧

**Comment by Chanzhaoyu** [comment]
还有就是接口超过最大 token 限制，会丢弃之前上下文

**Comment by flyMDW** [comment]
> 服务器重启了吧

 @Chanzhaoyu，是的是重启服务器的原因。我昨天研究了下chatgpt-api，发现如果实例化是没有messageStore，那服务器重启会丢失上下文 。
