### ISSUE TITLE
New Chat 生成对话主题

### ISSUE THREAD

**Issue by Cp0204** [Chanzhaoyu/chatgpt-web#657]
参考隔壁 [chatgpt-ui](https://github.com/WongSaang/chatgpt-ui-server/commit/a65f51635f8719edb24e027e65b3cd680d2c00bc) 项目，为 New Chat 生成一个主题：

```
    messages = [
        {"role": "user", "content": 'Generate a short title for the following content, no more than 10 words: \n\n "%s"' % message.message},
    ]
```

优化一下prompt：
> Generate your role or task for the following, no more than 10 words, using the same language, in []: \n\n xxxx

**Comment by Chanzhaoyu** [comment]
去掉 `token` 的时候会补全这些内容。
