### ISSUE TITLE
初学者好奇： 前端界面都被缓存了 只有在清理了缓存以后才会刷新新的内容 有啥设置可以改进这个问题吗？

### ISSUE THREAD

**Issue by JinhuW** [Chanzhaoyu/chatgpt-web#661]

**Comment by Cp0204** [comment]
CTRL+F5

**Comment by rzarvirov** [comment]
> CTRL+F5

what is the right way to force it without CRLT+F5?

**Comment by eflylab** [comment]
确实有这个问题，上次引入sw后，不只是缓存，如果前端自己通过nginx配置了 身份验证，nginx返回401时，前端也会出问题，会固定展示500错误页。我的方式是 通过下面的配置，让nginx禁止sw功能。
`
    # 禁止 ServiceWorker
    location ~ /(sw\.js|manifest\.webmanifest|registerSW\.js) {
        deny all;
    }
`

**Comment by eflylab** [comment]
确实有这个问题，上次引入sw后，不只是缓存，如果前端自己通过nginx配置了 身份验证，nginx返回401时，前端也会出问题，会固定展示500错误页。我的方式是 通过下面的配置，让nginx禁止sw功能。
# 禁止 ServiceWorker
    location ~ /(sw\.js|manifest\.webmanifest|registerSW\.js) {
        deny all;
    }

**Comment by shansing** [comment]
感谢楼上提供的方法。而我使用 nginx 的 sub_filter 替换字符串的方式：

```
sub_filter '<link rel="manifest" href="/manifest.webmanifest"><script id="vite-plugin-pwa:register-sw" src="/registerSW.js"></script>' '<script>window.addEventListener("DOMContentLoaded", function() { caches.keys().then(cacheNames => {  cacheNames.forEach(cacheName => {    caches.delete(cacheName);  });});   }); </script>';
```

这样可以把相关的引用变为清除缓存存储的代码。这些 JS 代码在 Firefox 实测可以清除 PWM、Service Worker 相关的缓存存储，供 @JinhuW @rzarvirov 参考。不过一般的缓存就你们就要用普通的方式解决了。

**Comment by chenxch** [comment]
如果不需要缓存功能的话可以直接注释下面这段代码构建即可。
https://github.com/Chanzhaoyu/chatgpt-web/blob/d422a805f609f20a5b5a350b28d25c62bdb35a4c/vite.config.ts#L17-L27

**Comment by zhuxindong** [comment]
> > CTRL+F5
> 
> what is the right way to force it without CRLT+F5?

maybe this pull request got work https://github.com/Chanzhaoyu/chatgpt-web/pull/700

**Comment by JinhuW** [comment]
我尝试了 添加你的PR 但是没啥作用 
> > > CTRL+F5
> 
> > 
> 
> > what is the right way to force it without CRLT+F5?
> 
> 
> 
> maybe this pull request got work https://github.com/Chanzhaoyu/chatgpt-web/pull/700
