### ISSUE TITLE
关于chatgpt回复超长内容的超时问题

### ISSUE THREAD

**Issue by bida2015** [Chanzhaoyu/chatgpt-web#662]
关于超时问题，比如让 chatgpt写一段代码，写到一半，超过30秒之后，就没数据回传了。

有什么办法解决这种长内容输出？

docker 这里设置的120秒

-e TIMEOUT_MS=120000 

nginx配置的也是120秒

      location / {
        proxy_pass http://localhost:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        proxy_buffering off;
      }

**Comment by yi-ge** [comment]
没有数据回传的报错信息是什么？

**Comment by bida2015** [comment]
你试试让它给你写个：JS MD5加解密的源码
它会输出内容，但持续到30多秒后，前端没回答完全， 再看下 POST 响应已经完成了，但响应的内容也是一半。

**Comment by yi-ge** [comment]
开启长回复即可。

**Comment by bida2015** [comment]
> 开启长回复即可。

开启长回复？ 在哪里设置？

**Comment by yi-ge** [comment]
.env变量修改后重新编译前端

**Comment by bida2015** [comment]
> .env变量修改后重新编译前端

用的是docker，是否有参数调整？

**Comment by yi-ge** [comment]
需要自行编译docker镜像
