### ISSUE TITLE
测试环境运行，配置问题？

### ISSUE THREAD

**Issue by SleepWaterGod** [Chanzhaoyu/chatgpt-web#664]
测试环境 运行起来。 请求都超时， 是哪里配置的不对么？ 我只在 .env里 配置了一个    api-key.  

sendMessage (53 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2023-03-18'
    },
    { role: 'user', content: '你好 GPT', name: undefined }
  ],
  stream: true
}

后端控制台报  TypeError: fetch failed
at fetchSSE (e:\workFolder\WebstormProjects\chatgpt-web\service\node_modules\.pnpm\chatgpt@5.0.10\node_modules\chatgpt\build\index.js:46:15) {
  cause: ConnectTimeoutError: Connect Timeout Error
  code: 'UND_ERR_CONNECT_TIMEOUT'

**Comment by Chanzhaoyu** [comment]
你网络不能访问 `OpenAI` 接口服务器，需要自建反代理

**Comment by tomray318** [comment]
我也遇到这个问题。但是我浏览器可以直接在gpt官网进行chat啊。我本地安装了vpn测试工具了。
