### ISSUE TITLE
chatgpt如果消息内容多的时候，就会出现，下面代码不能采用highlight标注

### ISSUE THREAD

**Issue by sygaton** [Chanzhaoyu/chatgpt-web#668]
![图片](https://user-images.githubusercontent.com/26806498/226077878-823ab878-0cfc-4261-8ef6-e4d11fe27a1c.png)
如上图所示，“用户对商品评分”往下的内容，就无法实现highlight识别了。

有没有什么解决办法

**Comment by yi-ge** [comment]
启用长回复即可。

**Comment by yi-ge** [comment]
参考根目录下.env文件配置。
