### ISSUE TITLE
docker安装启动报错，请问怎么解决呀？

### ISSUE THREAD

**Issue by Asunfly** [Chanzhaoyu/chatgpt-web#670]
# docker logs --tail=1000 

> chatgpt-web-service@1.0.0 prod /app
> esno ./build/index.js

Server is running on port 3002
 ELIFECYCLE  Command failed with exit code 143.

> chatgpt-web-service@1.0.0 prod /app
> esno ./build/index.js

Server is running on port 3002
 ELIFECYCLE  Command failed with exit code 143.

> chatgpt-web-service@1.0.0 prod /app
> esno ./build/index.js

Server is running on port 3002
 ELIFECYCLE  Command failed with exit code 143.

> chatgpt-web-service@1.0.0 prod /app
> esno ./build/index.js

Server is running on port 3002
[root@iZt4ngyjxppt3n46wd3x1mZ ~]#

**Comment by Yokeagoni** [comment]
同问，蹲个大佬解惑，感谢
内核为：4.18.0-348.7.1.el8_5.x86_64
发行版： CentOS Linux release 8.5.2111
docker版本为： Docker version 23.0.1, build a5ee5b1
日志：
> chatgpt-web-service@1.0.0 prod /app
> node ./build/index.mjs

Server is running on port 3002
 ELIFECYCLE  Command failed.

> chatgpt-web-service@1.0.0 prod /app
> node ./build/index.mjs

Server is running on port 3002
 ELIFECYCLE  Command failed.

> chatgpt-web-service@1.0.0 prod /app
> node ./build/index.mjs

Server is running on port 3002

**Comment by Yokeagoni** [comment]
> 同问，蹲个大佬解惑，感谢 内核为：4.18.0-348.7.1.el8_5.x86_64 发行版： CentOS Linux release 8.5.2111 docker版本为： Docker version 23.0.1, build a5ee5b1 日志：
> 
> > chatgpt-web-service@1.0.0 prod /app
> > node ./build/index.mjs
> 
> Server is running on port 3002  ELIFECYCLE  Command failed.
> 
> > chatgpt-web-service@1.0.0 prod /app
> > node ./build/index.mjs
> 
> Server is running on port 3002  ELIFECYCLE  Command failed.
> 
> > chatgpt-web-service@1.0.0 prod /app
> > node ./build/index.mjs
> 
> Server is running on port 3002

虽然不知道为啥，但是今天测试虽然日志还在报错，但是已经可以正常使用了
