### ISSUE TITLE
feat: 添加显示原文的选项

### ISSUE THREAD

**Issue by yilozt** [Chanzhaoyu/chatgpt-web#671]
### 期望的功能

* 起因是因为自己让 ChatGPT 生成数学公式时，发现只能打开菜单按钮，然后复制所有的输出。
* 自己希望能够添加一个选项来显示原文，这样就可以只复制自己需要的部分

**Comment by zmlix** [comment]
我的这个可以显示原文 https://github.com/zmlix/chatgpt-web/tree/main/ChatGPT
