### ISSUE TITLE
vercel服务器部署的时候，配置了环境变量PORT和OPENAI_API_KEY，部署好访问域名提示500错误

### ISSUE THREAD

**Issue by me4p0** [Chanzhaoyu/chatgpt-web#675]
vercel服务器部署的时候，配置了环境变量PORT和OPENAI_API_KEY，部署好访问域名提示500错误，咋回事？log里提示api/session的level是warning

**Comment by Chanzhaoyu** [comment]
不适用于 Vercel ，除非你把 service 文件夹分出来

**Comment by me4p0** [comment]
谢谢提示

**Comment by Root-FTW** [comment]
> 谢谢提示

你是否设法在Vercel中启动它？

你能向我解释一下如何在Vercel中启动它吗？
