### ISSUE TITLE
the "/app/dist" directory is not found

### ISSUE THREAD

**Issue by llc-sf** [Chanzhaoyu/chatgpt-web#676]
This error message indicates that the Docker build process is trying to copy a directory called "/app/dist" from the "builder" stage to "/app/public" in the current stage, but the "/app/dist" directory is not found.

It could be that the directory is missing in the "builder" stage, or the path to it is incorrect. To resolve this issue, you need to ensure that the "/app/dist" directory exists in the "builder" stage and the path to it is correct. If the directory is not present in the "builder" stage, you need to add the necessary steps to create it.

**Comment by Kenneth-zh** [comment]
I encountered with the same trouble
