### ISSUE TITLE
[request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established]

### ISSUE THREAD

**Issue by vr-yan** [Chanzhaoyu/chatgpt-web#677]
undefined
[request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established]

**Comment by bennywnn** [comment]
the same issue, disappear after change the socks proxy, but it happen again after awhile

**Comment by bennywnn** [comment]
the limited request limitations may cause this issue
