### ISSUE TITLE
更新到最新2.10.7后，经常报Network error

### ISSUE THREAD

**Issue by Andy-qinyuhai** [Chanzhaoyu/chatgpt-web#679]
Docker部署，服务器在境外，使用默认api.openai.com地址，没有使用任何代理，更新到最新版本2.10.7后经常出现回答超时的情况，显示Network error

**Comment by 212112111zwl** [comment]
我这里也是

**Comment by Chanzhaoyu** [comment]
没有修改过服务端的代码哦，回退版本还会有问题吗

**Comment by Andy-qinyuhai** [comment]
> 没有修改过服务端的代码哦，回退版本还会有问题吗

不好意思，刚查了openai的service status，应该是openai 服务器的问题。
`“Due to high load relative to currently available capacity, users will likely see timeouts on requests. We are currently investigating ways to mitigate this. ”`
