### ISSUE TITLE
支持Markdown, 这样就可以让ChatGPT返回图片。

### ISSUE THREAD

**Issue by chris-ss** [Chanzhaoyu/chatgpt-web#68]
用法如下
目前在官方网页是可以的
![image](https://user-images.githubusercontent.com/18467476/219999331-f44b57c0-79e9-4108-ab8c-bc356567dc6a.png)

**Comment by Chanzhaoyu** [comment]
返回 `markdown` 是支持的，但是没做解析

**Comment by cy-i** [comment]
> 返回 `markdown` 是支持的，但是没做解析

后期有计划加上解析吗？

**Comment by Chanzhaoyu** [comment]
<img width="1031" alt="1" src="https://user-images.githubusercontent.com/24789441/220234202-9cac42cb-7023-48fc-86b0-f0cb684e55e0.png">

`dev` 分支是支持的

**Comment by Chanzhaoyu** [comment]
已支持
