### ISSUE TITLE
golang 后端, 带数据库.

### ISSUE THREAD

**Issue by swuecho** [Chanzhaoyu/chatgpt-web#680]
https://github.com/swuecho/chat

**Comment by ludashi2020** [comment]
能使用这个前端吗？(https://github.com/gouguoyin/chatgpt-web)带用户登录注册的

**Comment by swuecho** [comment]
已经带了前端了, 就是这个repo 复制过去, 加了一些必要的改动.

**Comment by Chanzhaoyu** [comment]
`PR` 里面有个 `GO` 后端，你可以去看看

**Comment by mouyong** [comment]
@swuecho 不支持配置代理吗。无法请求 gpt 的 api。
