### ISSUE TITLE
docker-compose运行如何查看日志

### ISSUE THREAD

**Issue by opticalix** [Chanzhaoyu/chatgpt-web#683]
如题，sudo docker exec -it docker-compose_nginx_1 sh 进容器里什么也没看到

**Comment by opticalix** [comment]
想分析下具体原因：“request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 159.xxxx”

**Comment by Asunfly** [comment]
docker ps -a 看下容器id
docker logs -t -f 容器id
