### ISSUE TITLE
这是什么错误？

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#684]
undefined
[ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined]

web token模式，目前版本:2.10.5

**Comment by Chanzhaoyu** [comment]
你在同一个会话里面用了 API 又用了 Token

**Comment by ludashi2020** [comment]
> 你在同一个会话里使用了 API 又使用了 Token

API参数为空，没有填写过。只要token代理那里设置了。网页刷新几次又没有错误了

**Comment by Chanzhaoyu** [comment]
> > 你在同一个会话里使用了 API 又使用了 Token
> 
> API参数为空，没有填写过。只要token代理那里设置了。网页刷新几次又没有错误了

那就是上游的 `ID` 冲突了

**Comment by ludashi2020** [comment]
> 


什么原因导致的呢？基本上是自用
