### ISSUE TITLE
增加对ChatGLM-6B的支持

### ISSUE THREAD

**Issue by xzqiaochu** [Chanzhaoyu/chatgpt-web#696]
ChatGLM-6B是一个中英双语开源大模型，最低可在6G显存上运行
https://github.com/THUDM/ChatGLM-6B
该模型目前已支持流式输出，希望可以增加对其的支持

**Comment by yi-ge** [comment]
您跑起来了吗？ @xzqiaochu

**Comment by xzqiaochu** [comment]
@yi-ge 我在笔记本上跑起来了，使用4bit量化。笔记本是RTX 3060 6G
这里有一个我在实验室服务器上部署的链接：http://plusgpt.cn:7860/，您可以试试看（这个服务可能没法长期运行，因为比较占用显寸）

**Comment by yi-ge** [comment]
@xzqiaochu 感谢，我这就体验下

**Comment by Chanzhaoyu** [comment]
Mac 能跑吗...

**Comment by wnb6cf** [comment]
> Mac 能跑吗...

能

**Comment by yi-ge** [comment]
@xzqiaochu 总体来看已经非常优秀了，能在普通电脑跑更是难得。

**Comment by Chanzhaoyu** [comment]
我也去玩一玩

**Comment by NCZkevin** [comment]
https://github.com/NCZkevin/chatglm-web

我用大佬的chatgpt-web魔改了一个chatglm的，现在还比较简陋，后续会一直更新，
