### ISSUE TITLE
大佬，请问前端怎么让它流式传输，实时回复？

### ISSUE THREAD

**Issue by dfvips** [Chanzhaoyu/chatgpt-web#697]
就像官网那种效果，实时回复。

**Comment by dfvips** [comment]
我是docker-compose部署的，每次它回复都要等全部加载完，才回复

**Comment by xzqiaochu** [comment]
我也是docker-compose部署的，是可以流式输出的呀

**Comment by dfvips** [comment]
我发现了，是域名反向代理的问题。

> 我也是docker-compose部署的，是可以流式输出的呀

**Comment by dfvips** [comment]
检查下你整个过程中使用的所有后端服务器软件，例如nginx反向的话，加proxy_buffering off;Caddy2是flush_interval 0s。我之前不能解决的原因是Caddy2没配置。

**Comment by dfvips** [comment]
> > 我发现了，是域名反向代理的问题。
> > > 我也是docker-compose部署的，是可以流式输出的呀
> 
> 大佬， 请问下你是怎么解决的呀？望赐教~~

检查下你整个过程中使用的所有后端服务器软件，例如nginx反向的话，加proxy_buffering off;Caddy2是flush_interval 0s。我之前不能解决的原因是Caddy2没配置。

**Comment by PuddingJoker** [comment]
大佬能不能看一下你的Nginx文件配置啊，我也遇到这个问题了，按你说的配置了没生效
