### ISSUE TITLE
gpt 返回的内容过长，界面显示不完整

### ISSUE THREAD

**Issue by gssjl2008** [Chanzhaoyu/chatgpt-web#698]
可有参数配置

**Comment by yi-ge** [comment]
有，常见.env开启长链接

**Comment by gssjl2008** [comment]
不是长连接问题吧， 接口看到内容都返回了，但是页面显示不完整

**Comment by yi-ge** [comment]
麻烦截图

**Comment by gssjl2008** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/43020699/226181371-da015eea-09dc-4907-bb1d-35c67eb40c9a.png">
<img width="894" alt="image" src="https://user-images.githubusercontent.com/43020699/226181384-5ad291c9-0251-4a8e-80f6-0bdc9ab98275.png">

结果并未输出完整

**Comment by yi-ge** [comment]
图一是请求参数，图二是返回值。

**Comment by gssjl2008** [comment]
但是代码明确是没有写完整，你的意思是 chatgpt 自己返回的数据有限制导致？

**Comment by yi-ge** [comment]
是的，可以肯定程序本身没有问题
