### ISSUE TITLE
Model selection

### ISSUE THREAD

**Issue by rzarvirov** [Chanzhaoyu/chatgpt-web#702]
Hi guys! Great project. Since we are now seeing gpt-4 api access rollout, any plans to add functionality for model selection for individual chats? Thanks!

**Comment by jamie0725** [comment]
同问+1，类似 chat.openai.com 的方法，有个下拉框让用户选择使用哪个模型。可以避免总是使用 GPT-4 费用大幅增加和响应变慢的问题

**Comment by Chanzhaoyu** [comment]
下个大版本会把 `token` 去掉，然后 `API` 可设定
