### ISSUE TITLE
建议增加temperature值

### ISSUE THREAD

**Issue by 282919088** [Chanzhaoyu/chatgpt-web#704]
建议增加temperature属性值，要不感觉有点胡说八道。
![image](https://user-images.githubusercontent.com/4486214/226178392-ba69c499-86e8-4296-a420-78e280389f1d.png)

**Comment by Chanzhaoyu** [comment]
不敢加变量了，越来越多，如果个人定义的话还是手动改下吧。可能需要个控制页面。

**Comment by MLZC** [comment]
感觉可以把temperature和top_p这两个参数设置成动态调整会好一些？
我目前也是用类似的方法加的

**Comment by HankMo** [comment]
![image](https://user-images.githubusercontent.com/60347960/226182092-1a67327e-fa53-489b-8201-dc42beccc89b.png)
这个怎么关掉。我不想让他简洁的回答。

**Comment by ifangyong** [comment]
还是建议加个自定义temperature，多日测试下来，在对于数学问题时，默认的temperature出错概率很大，在将数值增大后，准确率大大提升
