### ISSUE TITLE
收到了GPT-4的邀请，能否增加最大MAX token的限制

### ISSUE THREAD

**Issue by mm519897405** [Chanzhaoyu/chatgpt-web#706]
看了下是3.5的两倍容量

**Comment by liusijun** [comment]
请问收到了GPT-4发来的邮件申请了但是一直没有回复，是不是必须开启plus才有资格用api啊

**Comment by bawanag** [comment]
想问一下GPT-4的key直接输入到config里面就可以直接用了吗？

**Comment by vulgatecnn** [comment]
![2efc9b51692d4dd70df1e0cb7023408](https://user-images.githubusercontent.com/20904148/226268628-d94f46b9-7af8-4a6d-b799-ee6e487b993f.jpg)


介绍说GPT-4没有API方式
