### ISSUE TITLE
有没有可能存在被偷额度的情况

### ISSUE THREAD

**Issue by dashug** [Chanzhaoyu/chatgpt-web#709]
我自己试了下，注册的账户，我这边没人用，很快额度就消耗完了，换了好几个账户了都是，有人遇到过这样的情况么

**Comment by 1c3z** [comment]
是不是暴露在公网，没设置密码。

**Comment by Chanzhaoyu** [comment]
暴露了，有人扫端口

**Comment by zhuxindong** [comment]
暴露在公网了，会有人扫描端口然后调用，建议限制速率，可以使用cloudflare的速率规则
![image](https://user-images.githubusercontent.com/24989246/226238522-f2bb291d-913f-407a-9afc-33bb145d2dcd.png)

**Comment by cheniujh** [comment]
可以增加一个类似于访问服务密码的功能吗

**Comment by 1c3z** [comment]
AUTH_SECRET_KEY  有这个环境变量，可以设置下， 文档里也有。

**Comment by dashug** [comment]
> AUTH_SECRET_KEY 有这个环境变量，可以设置下， 文档里也有。

嗯，加了。这个操作应该可以防止了

**Comment by dashug** [comment]
> 暴露在公网了，会有人扫描端口然后调用，建议限制速率，可以使用cloudflare的速率规则 ![image](https://user-images.githubusercontent.com/24989246/226238522-f2bb291d-913f-407a-9afc-33bb145d2dcd.png)

docker部署的，然后没加cloudflare，加了访问限制了
