### ISSUE TITLE
使用nginx反代而且开启http basic auth以后，会固定返回http 500

### ISSUE THREAD

**Issue by xmxs** [Chanzhaoyu/chatgpt-web#71]
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name chatgpt.baidu.com; 
    ssl_certificate      /opt/cert/chatgpt.baidu.com.cer; 
    ssl_certificate_key  /opt/cert/chatgpt.baidu.com.key; 
    client_max_body_size 50M;
    auth_basic 'chatgpt';
    auth_basic_user_file /etc/a.pw; 
    location / {
        proxy_hide_header Authorization;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }    
}
```
加上basic auth就会固定http 500，去掉就正常，即使加了proxy_hide_header Authorization也还是一样。

**Comment by jkhcc11** [comment]
> ```
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
>     server_name chatgpt.baidu.com; 
>     ssl_certificate      /opt/cert/chatgpt.baidu.com.cer; 
>     ssl_certificate_key  /opt/cert/chatgpt.baidu.com.key; 
>     client_max_body_size 50M;
>     auth_basic 'chatgpt';
>     auth_basic_user_file /etc/a.pw; 
>     location / {
>         proxy_hide_header Authorization;
>         proxy_redirect off;
>         proxy_pass http://127.0.0.1:3002;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header Host $http_host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }    
> }
> ```
> 
> 加上basic auth就会固定http 500，去掉就正常，即使加了proxy_hide_header Authorization也还是一样。

你这样试试，我用的docker方式部署2.6.2，这样是可以的，其他方式应该大同小异
![image](https://user-images.githubusercontent.com/28553032/220808031-1f647ab0-02c9-4941-a1c4-c39549fc9ea6.png)
