### ISSUE TITLE
请问会有增加封号几率吗？

### ISSUE THREAD

**Issue by string-new** [Chanzhaoyu/chatgpt-web#710]
我是直接在海外服务器搭建的，不存在用代理去请求，之前自己搭的用了一个多月没出线问题，看到这个项目做得很好，结果接入后没过多久账号被封了，当然现在也不确定是哪里的问题，所以问问

**Comment by echeverra** [comment]
请问封的是什么的号，chatgpt的账号么？

**Comment by string-new** [comment]
> 

openai的账号

**Comment by string-new** [comment]
openai的账号

**Comment by Chanzhaoyu** [comment]
用的 token ?

**Comment by string-new** [comment]
本身就是海外的服务器，直接用的apiKey

**Comment by Chanzhaoyu** [comment]
> 本身就是海外的服务器，直接用的apiKey

那应该不会啊，我自己用的是 `Railway` 部署的 `API Key`

**Comment by cheniujh** [comment]
洛杉矶服务器，我连续封了2个号，目前第三个号暂时正常。你项目这个向openai发送请求时，它会知道请求的真正来源吗（我访问我的服务器时是直接中国ip直连的）

**Comment by string-new** [comment]
>那应该不会啊，我自己用的是 Railway 部署的 API Key

我又重新注册了个，看看这次能用多久，会不会是调用api请求头或者附带参数有问题呢

**Comment by bluefrankey** [comment]
我也被ban了一个号 用access_token返回 [[OpenAI] 提供错误的API密钥 | Incorrect API key provided]

**Comment by hongfs** [comment]
你们把地址发出去让别人使用了？

**Comment by string-new** [comment]
>你们把地址发出去让别人使用了？

有给别人，但是请求都是从服务器发出去的，不存在的异地的问题
