### ISSUE TITLE
前端增加可以添加apikey功能

### ISSUE THREAD

**Issue by kainstan** [Chanzhaoyu/chatgpt-web#713]
后端与前端解耦，可以使用不同的技术栈构建后端。增加代码可复用性

另外建议增加mysql，存储前端传来的apikey，前端增加可以添加apikey功能

**Comment by Chanzhaoyu** [comment]
不会增加数据库哈，同 IP 多帐号目前封号比较严重，已经有人做不同后端的项目，可以搜索下

**Comment by kainstan** [comment]
> 不会增加数据库哈，同 IP 多帐号目前封号比较严重，已经有人做不同后端的项目，可以搜索下

可否提供一个前后端对接的文档，方便各个技术栈对接开发

**Comment by Beihaiyumao** [comment]
> 方便

同求 nodejs 有点看不明白 有没有接口文档 还是想对接java
