### ISSUE TITLE
群辉里面创建了机器人出现undefined fetch failed

### ISSUE THREAD

**Issue by bingbaicai** [Chanzhaoyu/chatgpt-web#714]
使用群辉手动创建的，按照https://github.com/Chanzhaoyu/chatgpt-web/issues/360
修改了环境变量
极其人可以打开
但是他返回的是undefined fetch failed

![Uploading iShot_2023-03-20_11.30.57.png…]()

**Comment by Asunfly** [comment]
国内ip访问，号被ban了

**Comment by bingbaicai** [comment]
> 国内ip访问，号被ban了

为什么我在网页版能弄。我软路里面挂🪜了
