### ISSUE TITLE
请求问题

### ISSUE THREAD

**Issue by lixingxing001** [Chanzhaoyu/chatgpt-web#716]
我在服务器上部署之后，如果连续对话，第一条命令是正常输出的，但是紧接着第二天命令输入后一直处于光标状态。如图:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/43061802/226265782-489d390f-a2b9-4a69-bae2-fc08941a7ee1.png">
,一定时间内出现（Request failed with status code 524）但是在点刷新的小按钮时才会正常展示。多次测试都能复现

**Comment by lixingxing001** [comment]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/43061802/226266067-caafb78f-f52e-4f28-a066-c6169456e2d5.png">

**Comment by vulgatecnn** [comment]
Error 524 error indicates that Cloudflare made a successful TCP connection to the origin web server, but the origin did not reply with an HTTP response before the connection timed out. Typically, Cloudflare waits 100 seconds for an HTTP response. If the origin doesn't respond in that time, Cloudflare closes the connection and serves Error 524.

应该是访问openai的问题

**Comment by jacywy** [comment]
刚搭建，同样的问题，但没有524，一直光标闪
