### ISSUE TITLE
希望作者可以把这个分叉项目的微调能合并进主线项目中

### ISSUE THREAD

**Issue by zhxuri** [Chanzhaoyu/chatgpt-web#722]
这个分叉项目地址是
https://github.com/WenJing95/chatgpt-web
它添加了微调功能和上下文数量
![c4](https://user-images.githubusercontent.com/11741854/226308476-e4db32d5-858d-46ac-8a2b-0ef62418aef1.png)
功能我觉得很必要合并进主线项目当中

**Comment by zhxuri** [comment]
这个分叉项目，添加完这个功能后脱离主线版本更新。大家应该更喜欢跟进主线得版本去更新。但是它这个添加的功能却很有必要

**Comment by zhxuri** [comment]
我在issue中看到很多人都在提想添加这个微调功能进去

**Comment by zhxuri** [comment]
当然，个人癖好也提一下，我问过一些盆友，他们都觉得如果默认主题是暗黑主题会感觉更好一些。虽然是可以设置，但是大多数人会忽略这个设置。都觉得默认选择黑的更酷。

**Comment by zhxuri** [comment]
issue #718 中提到的 添加客户端IP的限流参数到环境变量当中是很有必要的，因为我有提供小范围朋友分享使用，从日志情况来看，这种问题还是比较凸显的。

**Comment by cy-i** [comment]
> 当然，个人癖好也提一下，我问过一些盆友，他们都觉得如果默认主题是暗黑主题会感觉更好一些。虽然是可以设置，但是大多数人会忽略这个设置。都觉得默认选择黑的更酷。

特别讨厌默认主题是暗黑的，你见过几个大点的网站默认是暗黑哦！所以你其他的建议支持，但默认暗黑这个保留！😂

**Comment by zhxuri** [comment]
> > 当然，个人癖好也提一下，我问过一些盆友，他们都觉得如果默认主题是暗黑主题会感觉更好一些。虽然是可以设置，但是大多数人会忽略这个设置。都觉得默认选择黑的更酷。
> 
> 特别讨厌默认主题是暗黑的，你见过几个大点的网站默认是暗黑哦！所以你其他的建议支持，但默认暗黑这个保留！😂

哈哈哈，只是个人癖好而已。其他功能支持一下哈

**Comment by Chanzhaoyu** [comment]
唉，步子太大拉了跨，如果把 Token 去掉的话就好办了，不然要分开写功能加判断 😮‍💨

**Comment by Chanzhaoyu** [comment]
功能实现起来挺简单的，就是传的上下文数量还有发散能力

**Comment by Chanzhaoyu** [comment]
> 发散能力是什么原理呢？

API 有参数

**Comment by zhuxindong** [comment]
> 唉，步子太大拉了跨，如果把 Token 去掉的话就好办了，不然要分开写功能加判断 😮‍💨

chatapimodel对象的生成是在立即执行函数里的，还加了是选择token或api的判断。。。改起来挺麻烦的，

**Comment by yangyucitrus** [comment]
> 唉，步子太大拉了跨，如果把 Token 去掉的话就好办了，不然要分开写功能加判断 😮‍💨

其实作者大大已经可以考虑去除使用token的模式了，token要用反代网址速度慢不说，还有一定的泄露账号风险，现在国内机器使用自建在vercel或者zeabur上的的反代api地址也能正常使用3.5的api了，去了估计没啥大影响😽

**Comment by wwlmm** [comment]
还是不要去除token的好 留着挺好

**Comment by yangyucitrus** [comment]
> > > 唉，步子太大拉了跨，如果把 Token 去掉的话就好办了，不然要分开写功能加判断 😮‍💨
> > 
> > 
> > 其实作者大大已经可以考虑去除使用token的模式了，token要用反代网址速度慢不说，还有一定的泄露账号风险，现在国内机器使用自建在vercel或者zeabur上的的反代api地址也能正常使用3.5的api了，去了估计没啥大影响😽
> 
> 哥们怎么搭建API地址 想用4.0的token了 !
[https://github.com/imyuanx/chatgpt-proxy](url)这个项目，不过这个只能反代官方api网址，不是反代官方的chatgpt网页，你要用token的话，改下这段代码就行
`    const options: ChatGPTUnofficialProxyAPIOptions = {
      accessToken: process.env.OPENAI_ACCESS_TOKEN,
      debug: false,
      model: "gpt-4",
    }`

**Comment by expfukck** [comment]
> > > > 唉，步子太大拉了跨，如果把 Token 去掉的话就好办了，不然要分开写功能加判断 😮‍💨
> > > 
> > > 
> > > 其实作者大大已经可以考虑去除使用token的模式了，token要用反代网址速度慢不说，还有一定的泄露账号风险，现在国内机器使用自建在vercel或者zeabur上的的反代api地址也能正常使用3.5的api了，去了估计没啥大影响😽
> > 
> > 
> > 哥们怎么搭建API地址 想用4.0的token了 !
> > [https://github.com/imyuanx/chatgpt-proxy](url)这个项目，不过这个只能反代官方api网址，不是反代官方的chatgpt网页，你要用token的话，改下这段代码就行
> 
> ```
> const options: ChatGPTUnofficialProxyAPIOptions = {
>   accessToken: process.env.OPENAI_ACCESS_TOKEN,
>   debug: false,
>   model: "gpt-4",
> }
> ```
谢谢 你这段在哪修改了 想用VPS搭建 好像没看到教程 只有在其他平台部署!
