### ISSUE TITLE
收集一下，有多少用 Token 的啊？

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#723]
目前步子迈得太大，OpenAI 也是日日打鸡血，两个功能放一起，如果还用上游包的话，针对 API 已经不好扩展了。😮‍💨

**Comment by cy-i** [comment]
没再用了，我的token都没用几次，最近账号给封了

**Comment by joker-ssh** [comment]
这里 上头希望我做一个登录获取token的 搞了半天登录拿不到 不知道是什么原因

**Comment by yangyucitrus** [comment]
拆分吧，或者暂时放弃token也行，token现在除了完全免费也没有太大优势了（除非gpt4能开放免费使用）

**Comment by daiaji** [comment]
API免费是有配额吗？

**Comment by islercn** [comment]
在没有真正的反代前，目前是每人一站，每站单独一个openai账户的token，也就相当于反代了，毕竟网页版是优化过的，不单单是费用的问题

**Comment by GH6324** [comment]
我Plus订阅，用的token还没封号

**Comment by bennywnn** [comment]
免费账号，用token还没封号，但是老是反代网址不通，半瘫痪状态

**Comment by vowers** [comment]
免费配额的API就够用了，token用起来还麻烦
觉得付费麻烦还可以用这个代理[api2d](https://api2d.com/r/186802)，微信直接冲，关键还能用GPT4 ，我试了下无缝衔接
当然有条件还是直接冲官方的

**Comment by Wake-C** [comment]
用的token,挺稳定的

**Comment by Cp0204** [comment]
不敢用了，被封了个$18的号

**Comment by zhxuri** [comment]
我用API，用token的估计大部分人不稳，且这token速度也慢。不如Api快好用，消耗API余额也都还好，没有了就再注册号呗，感觉如果保留这token，给你接下来的API迭代造成不小的阻力！api和token毕竟是两条路子，如果有可能的话拆分成两个版本，别让token挡住api前进的道路毕竟API的可玩性多且路子正，用token从使用上来看算是个野路子，长期token封号也是大概率事件，还不如直接访问原版chatgpt。以上只是个人看法。

**Comment by zhxuri** [comment]
用token只是为了能够正常访问chatgpt的话，反正获取token也得出墙，弄个好用的出墙节点不就直接访问原版chatgpt了。

**Comment by cy-i** [comment]
现版本保留，不在更新！开新版本，取消token，如果想体验token的，用现在的版本！

**Comment by daiaji** [comment]
> 用token只是为了能够正常访问chatgpt的话，反正获取token也得出墙，弄个好用的出墙节点不就直接访问原版chatgpt了。

雀食，仓库留个tag就完事了，实在不懂有什么可纠结的。

**Comment by zhxuri** [comment]
目前从使用体验来看你的这个体验是最好的得继续保持，别被token绑住脚。鱼和熊掌不能兼得，况且token还不是啥好鱼。断舍离，长痛不如短痛。

**Comment by zaiMoe** [comment]
没用 token 了，看起来不是很稳定

**Comment by dqzboy** [comment]
没使用了，不稳定

**Comment by hncboy** [comment]
目前在使用 AccessToken，ChatGPT Plus 用户。

**Comment by wwlmm** [comment]
token适合自己一个用，是非常好的，不建议去除。那些需要拿出去给一群人用的人自然是不能用token的，对个人而言，token绝对是第一首选。

**Comment by loutian** [comment]
没用token,  用的api付费账号，除了能用这个外， 还能自己写些脚本用

**Comment by haydenull** [comment]
支持放弃 token

**Comment by IIllIIIlll** [comment]
支持放弃token，打个tag就行

**Comment by wangpre** [comment]
用的apikey，之前使用 https://www.openai-proxy.com 代理，现在准备自己买的国外的服务器搭建。
希望可以支持在网页上配置apikey，浏览器上直接缓存填写的apikey。
还有，前后端可以分两个仓库吗？后端我想用Java写，前端用你的UI

**Comment by gtgc2005** [comment]
支持拆分，而不是放弃。原因有如下两点

1、token的封号危险目前仅存在于免费账户，付费账户的危险性不大

2、token的用户并不少，仅仅是由于push用户的碰到的问题少，所以发声也少。

3、目前用来突破CF验证的旁路依然有效

**Comment by IIllIIIlll** [comment]
> 用的apikey，之前使用 https://www.openai-proxy.com 代理，现在准备自己买的国外的服务器搭建。 希望可以支持在网页上配置apikey，浏览器上直接缓存填写的apikey。 还有，前后端可以分两个仓库吗？后端我想用Java写，前端用你的UI

后端就在service文件夹中，可以自定义。

**Comment by mydaoyuan** [comment]
使用 token 访问 4.0

**Comment by superen7527** [comment]
token本来就比api好，api的上下文是全部文本发送，token是直接用对话id，而且也不是api能比的。更何况token还是免费的 不知道你们纠结什么。
