### ISSUE TITLE
毫无征兆地没有相应，要刷新页面，或者可能新建对话，才能再次有响应

### ISSUE THREAD

**Issue by cheniujh** [Chanzhaoyu/chatgpt-web#726]
毫无征兆地没有响应（一直没有回复），要刷新页面，或者可能新建对话，才能再次有响应，有时甚至一有上下文就卡住没有响应。
有时候又完全正常。
部署：洛杉矶服务器，centos8
客户端：国内浏览器裸访问服务器
请问有人知道怎么回事吗

**Comment by lqs2019** [comment]
![image](https://user-images.githubusercontent.com/52406708/226355113-cfda4ab9-48b8-4ea7-9078-6eef273f34f0.png)
一样  加载不出来

**Comment by cheniujh** [comment]
我的和你的不一样，我是前端界面可以加载，就是突然gpt一直在思考，不回复的那种

**Comment by lqs2019** [comment]
svg和session文件一直加载不出来，换vpn也不行，docker重新部署也不行，这是咋回事

**Comment by just2022try** [comment]
同样问题

**Comment by jurieochen** [comment]
感觉时间长了没有操作就需要刷新一下。

**Comment by OrangeNice** [comment]
会不会是server端的网络或者代理不稳定呀

**Comment by renhaihai** [comment]
有解决办法了嘛

**Comment by zixuan-chen** [comment]
同样的问题
