### ISSUE TITLE
能否接入 DALL·E 2 模型

### ISSUE THREAD

**Issue by devyujie** [Chanzhaoyu/chatgpt-web#727]
如题

**Comment by Chanzhaoyu** [comment]
界面不好放，除非改界面，而且这个接口是信用卡收费的

**Comment by jiayanguo** [comment]
https://platform.openai.com/docs/guides/images/introduction
根据官方文档 应该不收费

The Images API is in beta. During this time the API and models will evolve based on your feedback. To ensure all users can prototype comfortably, the default rate limit is 50 images per minute. If you would like to increase your rate limit, please review this [help center article](https://help.openai.com/en/articles/6696591). We will increase the default rate limit as we learn more about usage and capacity requirements.

**Comment by jiayanguo** [comment]
不太懂前端。 如果界面不好改， 能不能加一个单独的path 然后去图片的页面呢

**Comment by unikcc** [comment]
有兴趣可以单独开个project，这个专注把聊天做好就好，不然太重了。
