### ISSUE TITLE
加强下载功能

### ISSUE THREAD

**Issue by Starlento** [Chanzhaoyu/chatgpt-web#728]
现在的下载只能是png图片或者把所有的记录通过json导出。
这两种导出的结果都没有办法很好地支持复制代码这个功能。
能不能提供一个html的或者是markdown形式的导出，最好能是针对一个对话的，这样能够继续使用复制代码这些功能。

**Comment by swuecho** [comment]
你可以说是谁吧 json 给 chatgpt 让他给你生成一个 html 文件. 理论上是可以的.

然后弄个pr

**Comment by xingfanxia** [comment]
+1, 需要markdown导出

**Comment by pulller** [comment]
+1
