### ISSUE TITLE
請問高手關於搭建問題 只用UBUNTU apache2 PORT 80搭建 不用Docker 

### ISSUE THREAD

**Issue by ms2546088** [Chanzhaoyu/chatgpt-web#730]
![Image 6](https://user-images.githubusercontent.com/106522529/226505222-40363b9d-6626-4706-9b7c-f38d3475f112.jpg)

chatgpt-web v2.10.7
1.chatgpt-web index.html 請問是哪一個
/var/www/chatgpt-web-main/dist
/var/www/chatgpt-web-main
2. Apache HTTP Server 使用 80 PORT  (如圖)  
sudo sh ./start.sh
Network: http://192.168.66.243:1002/    #請問1002 要修改哪個文件
/var/www/chatgpt-web-main/.env
/var/www/chatgpt-web-main/service/.env
/var/www/chatgpt-web-main/service/.env.example

/etc/apache2/sites-available/chatgpt-web.conf
<VirtualHost *:1002>
嘗試替換  #<VirtualHost *:80>
ServerName Wu22IntranetHttpS
ServerAlias Wu22IntranetHttpS
DocumentRoot /var/www/chatgpt-web-main
嘗試替換  #    ErrorLog ${APACHE_LOG_DIR}/error.log
嘗試替換  #    CustomLog ${APACHE_LOG_DIR}/access.log combined
<Directory /var/www/chatgpt-web-main >
    AllowOverride All
    Require all granted
</Directory>
3.出現500 Server error 如圖
http://192.168.66.243:1002 -> http://192.168.66.243:1002/#/500
http://192.168.66.243:80 -> http://192.168.66.243:80/#/500

**Comment by renwofei423** [comment]
不能直接用容器么：

docker run --name chatgpt-web -d -p 80:3002 \
    --env OPENAI_API_KEY=sk-xxxxx \
    --env AUTH_SECRET_KEY=mima111 \
    --restart=always \
    chenzhaoyu94/chatgpt-web:latest

**Comment by Chanzhaoyu** [comment]
我也不太熟悉，帮不了你，抱歉。

**Comment by ms2546088** [comment]
謝謝您回復
