### ISSUE TITLE
生成过程中不能上翻

### ISSUE THREAD

**Issue by unikcc** [Chanzhaoyu/chatgpt-web#732]
在AI生成大段回答的过程中，如果想上翻查看历史对话记录，屏幕就会闪屏，然后不能往上翻，必须看着他一步一步生成完，才可以查看记录

**Comment by wwlmm** [comment]
之前记得修复过，后来不知道为什么又恢复成这样了

**Comment by goodnull** [comment]
还有不能切换到其他对话，一切换就中断了之前的请求

**Comment by Chanzhaoyu** [comment]
> 还有不能切换到其他对话，一切换就中断了之前的请求

因为切换会跳转另外的会话 `ID` ，也就是不在当前页面，所以是会中断。

**Comment by goodnull** [comment]
> > 还有不能切换到其他对话，一切换就中断了之前的请求
> 
> 因为切换会跳转另外的会话 `ID` ，也就是不在当前页面，所以是会中断。

能否让还没有响应的请求继续等待响应，就算切换到其他会话，也不会中断正在等待响应的请求呢？

**Comment by Chanzhaoyu** [comment]
> > > 还有不能切换到其他对话，一切换就中断了之前的请求
> > 
> > 
> > 因为切换会跳转另外的会话 `ID` ，也就是不在当前页面，所以是会中断。
> 
> 能否让还没有响应的请求继续等待响应，就算切换到其他会话，也不会中断正在等待响应的请求呢？

不能

**Comment by Chanzhaoyu** [comment]
主分支已修改该问提
