### ISSUE TITLE
请问什么情况之下会被封号？

### ISSUE THREAD

**Issue by JuneDan** [Chanzhaoyu/chatgpt-web#733]
已经被封了5个账号了，就是那种一提问，不到一会就被提示“This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.”，有什么好的处理方法吗？目前知道railway部署不会被封，除了这个方法之外还有哪些方法？

**Comment by chnaan** [comment]
如果使用api_key方式的话，最好部署的服务器ip和你注册openai账号的时候使用的手机号归属地是在同一个国家。

**Comment by JuneDan** [comment]
> 如果使用api_key方式的话，最好的部分服务器ip和你注册openai账号的时候使用的手机号归属地是在同一个国家。

我这边有一个奇怪的现象，本地跑用key+机场（美国，新加坡，东京）+https://openapi.ssiic.com，然后就被封了（5个），到了腾讯云，我也是用key+机场（新加坡）+https://openapi.ssiic.com，就没有被封，不过速度就不是很好。可以看出什么问题吗？

**Comment by chnaan** [comment]
#621 
可以看下这个

**Comment by JuneDan** [comment]
> 

非常感谢

**Comment by JuneDan** [comment]
> #621 可以看下这个

非常感谢

**Comment by Huanghaonan88** [comment]
我是小白。我在多台VPS中用Docker部署成功，其中RakNerd也能部署成功，但是说了一句你好就封号，时间大概15分钟。另外2个VSP供应商则不会被封，我部署的方法是一样的，所以我猜测是使用的虚拟机服务商有某种关系，大家可以换一家VSP提供商试试。

**Comment by caotao94** [comment]
这个大概率跟vps服务商有关系

**Comment by yunwuu** [comment]
最保险就是直接用readme里的railway 完全没问题 猜测应该美国IP相对安全 尽量不要用【滥用IP】 如vultr这种国人用烂的ip  云服务商理论上来说没问题（如果用API），毕竟这就是给开发者/企业用的  不是被认为是僵尸网络应该不至于封号。

最后说个容易忽视的，就是这个项目的API显然跑起来以后会请求openai的api，要么别本地调试，要么本地调试要用API镜像，我第一个号就是这么封的，也就是【非运营区域调用API】。

**Comment by Chanzhaoyu** [comment]
补充一下，绑卡可以缓解这个问题。

**Comment by JuneDan** [comment]
> 补充一下，绑卡可以缓解这个问题

感谢大佬抽空回答。
