### ISSUE TITLE
老铁，在？我调不了啊

### ISSUE THREAD

**Issue by KenNaNa** [Chanzhaoyu/chatgpt-web#734]
![image](https://user-images.githubusercontent.com/39817783/226542080-983d0f10-36ea-4b98-a7ca-bd02815c6e63.png)

**Comment by lzq932765726** [comment]
一样的问题，两个服务都启动了，正常，就是你这样子，求解

**Comment by Chanzhaoyu** [comment]
能回送这个其实是调通了，是不是本地网络不稳定？

**Comment by KenNaNa** [comment]
不清楚

**Comment by KenNaNa** [comment]
> 能回送这个其实是调通了，是不是本地网络不稳定？

我在本地就是这样的，不知道怎么解决
![image](https://user-images.githubusercontent.com/39817783/226770023-555a09df-8c45-408a-b8d0-cf0ce3d4112f.png)

**Comment by KenNaNa** [comment]
> 你本地网络是否能直连 `OpenAI` 的接口地址？如果不可以的话就需要自己搭建个反代。

大佬怎么在本地测试 openAI 接口

**Comment by Byter-s** [comment]
> > 你本地网络是否能直连 `OpenAI` 的接口地址？如果不可以的话就需要自己搭建个反代。
> 
> 大佬怎么在本地测试 openAI 接口

先确保你本地能够连通`api.openai.com`吧，测试的话像你这样从本地前端请求就行，或者写个py请求一下api看看返回了什么
