### ISSUE TITLE
Invalid URL (POST /chat/completions):  本地测试key没问题，上服务器返回

### ISSUE THREAD

**Issue by Siri-Li** [Chanzhaoyu/chatgpt-web#737]
Invalid URL (POST /chat/completions):  本地测试key没问题，上服务器返回，这个可能是什么问题导致的呢
ChatGPT error 404: {
"error": {
"message": "Invalid URL (POST /chat/completions)",
"type": "invalid_request_error",
"param": null,
"code": null
}
}

**Comment by Chef5** [comment]
检查一下服务器上node_modules/chatgpt/package.json的安装包的版本 如果是"5.1.2"，需要在baseUrl后面加个 /v1

**Comment by Chanzhaoyu** [comment]
主分支已经处理了这个问题
