### ISSUE TITLE
可以同时多个gptapi进行轮询吗？

### ISSUE THREAD

**Issue by 1378056564** [Chanzhaoyu/chatgpt-web#740]
可以同时多个gptapi进行轮询吗？
一旦某个api余额为0了，自动切换成下一个openapi

**Comment by KenNaNa** [comment]
![image](https://user-images.githubusercontent.com/39817783/226769334-82f9d095-acf5-431a-b258-327b57db4780.png)

**Comment by wangpre** [comment]
我也想要这个功能，多个apikey轮询，或者手动在页面配置apikey
