### ISSUE TITLE
请问可以增加一个可提供别人调用该网站的API吗，例如本地POST请求上去

### ISSUE THREAD

**Issue by akayedi** [Chanzhaoyu/chatgpt-web#741]
请问可以在增加一个API调用吗，我想搭建一个QQ机器人，但是目前调用的官方API并不智能，但是我发现贵人开发的网站特别的智能，请问您能增加吗，我愿意支付100美元资金！作为酬劳

**Comment by ottocsb** [comment]
有没有一种可能这里也是调用官方的api

**Comment by ottocsb** [comment]
部署此项目就有服务端，你去前端查看如何请求的向你部署的服务端发送请求就是你需要的效果

**Comment by akayedi** [comment]
> 部署此项目就有服务端，你去前端查看如何请求的向你部署的服务端发送请求就是你需要的效果

我直接调用官方的API，他的对话似乎有限制，我在该源码搭建的网站上询问，则没有任何问题，我不知道是什么情况，所以我才来询问该开发者是否愿意在开发一个API对接出来

**Comment by Cp0204** [comment]
> 

应该是连续对话的问题，QQ每次只有一问一答，你要在你服务器上以用户为单位，保存若干组对话记录，我微信应用就是这么干的。
