### ISSUE TITLE
怎么把连续对话的开关设置为默认关闭

### ISSUE THREAD

**Issue by haihaimx** [Chanzhaoyu/chatgpt-web#742]

**Comment by swuecho** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/666683/226569052-28976a4c-d170-49bd-9e45-296579ba0825.png">

true 改成 false 就可以了, 需要你自己跟着步骤重新编译一下.

**Comment by haihaimx** [comment]
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/666683/226569052-28976a4c-d170-49bd-9e45-296579ba0825.png">
> 
> true 改成 false 就可以了, 需要你自己跟着步骤重新编译一下.

这个文件在哪里啊

**Comment by baby9** [comment]
> > <img alt="image" width="617" src="https://user-images.githubusercontent.com/666683/226569052-28976a4c-d170-49bd-9e45-296579ba0825.png">
> > true 改成 false 就可以了, 需要你自己跟着步骤重新编译一下.
> 
> 这个文件在哪里啊

`./src/store/modules/chat/helper.ts:9:`

**Comment by maosancai** [comment]
如果是docker的话，有没有办法直接更改呢？

**Comment by swuecho** [comment]
> 如果是docker的话，有没有办法直接更改呢？

不好直接改, 谁有空可以改造一下, 加个参数
