### ISSUE TITLE
请问可以增加一下GPT-4的模型吗

### ISSUE THREAD

**Issue by WadeZeak** [Chanzhaoyu/chatgpt-web#745]
建议增加一下gpt的模型

**Comment by expfukck** [comment]
gpt4.0的API出来了?

**Comment by yi-ge** [comment]
想加，还没收到通过名单邮件。

**Comment by lkeai2007** [comment]
不是有web api吗，请问如何使用gpt4

**Comment by IIllIIIlll** [comment]
有api的话把模型改成gpt4就行，没有的话网页版反代用gpt4的。

**Comment by lkeai2007** [comment]
> 

请问反代用gpt4是怎么弄呢，默认是3.5

**Comment by lkeai2007** [comment]
> 有api的话把模型改成gpt4就行，没有的话网页版反代用gpt4的。



> 有api的话把模型改成gpt4就行，没有的话网页版反代用gpt4的。

请问反代用gpt4是怎么弄呢，默认是3.5

**Comment by IIllIIIlll** [comment]
> 
请参考：https://github.com/acheong08/ChatGPT-Proxy-V4
此外Issue还有一个类似的问题，有人提供了反代设置，因为Issues太多，我找不到了，也可以参考。

**Comment by IIllIIIlll** [comment]
> > 有api的话把模型改成gpt4就行，没有的话网页版反代用gpt4的。
> 
> > 有api的话把模型改成gpt4就行，没有的话网页版反代用gpt4的。
> 
> 请问反代用gpt4是怎么弄呢，默认是3.5

请参考：https://github.com/acheong08/ChatGPT-Proxy-V4
此外Issue还有一个类似的问题，有人提供了反代设置，因为Issues太多，我找不到了，也可以参考。

**Comment by Chanzhaoyu** [comment]
现在模型参数也对 `token` 生效
