### ISSUE TITLE
http://localhost:1002/api/chat-process接口超时

### ISSUE THREAD

**Issue by lzq932765726** [Chanzhaoyu/chatgpt-web#747]
![image](https://user-images.githubusercontent.com/40811376/226583707-08074eac-d3f0-456d-b548-248539009840.png)
前后端服务启动正常，接口超时导致不回答问题。

**Comment by Pinkpiglet** [comment]
后端api.openai.com加上/v1

**Comment by KenNaNa** [comment]
![image](https://user-images.githubusercontent.com/39817783/226769158-fa509e46-8acd-454b-9594-b8610ad6e2b4.png)
大佬们，这个怎么解决？

**Comment by lzq932765726** [comment]
>

**Comment by lzq932765726** [comment]
> 

加上了，不行啊

**Comment by Zwanwei** [comment]
兄弟，解决了吗，怎么解决的

**Comment by leostrong8** [comment]
docker 部署了，本地纯前端起了两个node服务，本地还有VPN，就不行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chanzhaoyu/chatgpt-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 晚上9:50
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Chanzhaoyu/chatgpt-web] http://localhost:1002/api/chat-process接口超时 (Issue #747)





 
兄弟，解决了吗，怎么解决的
