### ISSUE TITLE
在同一台服务器布署了两个chatgpt-web docker空器实例，第二个容器出现了api余额，为什么会这样呢？

### ISSUE THREAD

**Issue by sujunquan** [Chanzhaoyu/chatgpt-web#749]
![问题图片](https://raw.githubusercontent.com/sujunquan/images/main/chatapi.png)

**Comment by Chanzhaoyu** [comment]
你用 API 的话，这个版本是有余额

**Comment by sujunquan** [comment]
> 你用 API 的话，这个版本是有余额

大佬，怎样解决这个问题呢？

**Comment by zengsuyi** [comment]
不想显示  用老的版本就行了

**Comment by CaptainYan2** [comment]
> 你用 API 的话，这个版本是有余额

请问我的是余额显示不了一直在转是为什么呢，其它功能正常。
<img width="726" alt="Screenshot 2023-03-22 at 17 38 13" src="https://user-images.githubusercontent.com/122849705/226862526-fdc272aa-247e-443a-995b-27a4c682f977.png">

**Comment by Chanzhaoyu** [comment]
> > 你用 API 的话，这个版本是有余额
> 
> 请问我的是余额显示不了一直在转是为什么呢，其它功能正常。 <img alt="Screenshot 2023-03-22 at 17 38 13" width="726" src="https://user-images.githubusercontent.com/122849705/226862526-fdc272aa-247e-443a-995b-27a4c682f977.png">

请求不到 OpenAI 接口
