### ISSUE TITLE
你好拒绝访问[request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:15777]

### ISSUE THREAD

**Issue by hgaong** [Chanzhaoyu/chatgpt-web#750]
可以帮忙看下嘛，docker启动的
![32c8175e470dab08395468c9384f085](https://user-images.githubusercontent.com/29444991/226598731-33fa8539-da94-46b9-b762-729a7b5080bc.png)

代理应该是没问题的：
HTTPS_PROXY: http://127.0.0.1:15777
![b432fb27e9ffd9d4400366a6a6a6771](https://user-images.githubusercontent.com/29444991/226599081-2106a2a1-cb85-40ce-8ec6-29fe1fe52c2d.png)

**Comment by hgaong** [comment]
另外再问一句，使用阿里云国外的vps是不是不用开代理？

**Comment by KenNaNa** [comment]
老铁解决了？我本地起来就是这样

**Comment by jkhcc11** [comment]
你好像配置错了，HTTPS_PROXY不能写成你本机的，应该是你vps外网地址，你可以使用F12查看下，是不是网页直接请求了你本机的`15777`端口了

**Comment by shenyongxiaomaohu** [comment]
我也这样，上午突然好了，没一会儿又这样了。

**Comment by junjunqi** [comment]
刚刚解决了。太难了。发现我部署的时候后端service下面的.env文件中没有把这个加进去。要代理的话必须把这个加进去
HTTPS_PROXY: http://xxx:7890

**Comment by itsevin** [comment]
这个只能填外网的IP吗？我服务器开代理填127.0.0.1：7890不行，然后把代理端口打开填外网地址可以了，然后代理就被别人IP枚举爬走了被恶意盗用了，有解决办法吗？

**Comment by jkhcc11** [comment]
> 这个只能填外网的IP吗？我服务器开代理填127.0.0.1：7890不行，然后把代理端口打开填外网地址可以了，然后代理就被别人IP枚举爬走了被恶意盗用了，有解决办法吗？

先把`AUTH_SECRET_KEY ` 这个给加上，可以防一下，然后另外可以套层CDN，然后把CDN做严格一点，就算被人用了，CDN也拦的住，除非别人恶意搞你，换Ip请求你。

**Comment by itsevin** [comment]
> 这个只能填外网的IP吗？我服务器开代理填127.0.0.1：7890不行，然后把代理端口打开填外网地址可以了，然后代理就被别人IP枚举爬走了被恶意盗用了，有解决办法吗？

哦哦应该是可以填内网地址，我是用docker部署的所以没法访问我在docker外的代理，草率了没注意到

**Comment by junjunqi** [comment]
我是本地手动配置的。后端和前端单独配置，前端使用tomcat服务器配置。代理可以正常运行，比较稳定。
docker容器配置要解决网络代理弄了好久，没有成功。有哪位大神docker容器配置解决了吗

**Comment by jeff-hong** [comment]
> 我也有类似的报错，代理没有问题，因为有时候会正常，不知道是因为什么。
> 
> undefined [request to https://openapi.ssiic.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established]

我也是报这个错，老哥解决了吗
