### ISSUE TITLE
请问下手动打包部署在linux服务器上面，service后端执行了pnpm prod后，关闭xshell客户端，后端服务就停止了，请问怎么解决这个问题呢？

### ISSUE THREAD

**Issue by cy19734682** [Chanzhaoyu/chatgpt-web#752]

**Comment by Eumenides1** [comment]
要在 Node.js 项目中实现后台运行，可以使用以下几种方法：

使用 nohup 命令和 & 符号：nohup 命令用于在后台运行进程，& 符号用于将进程放入后台。例如：
`nohup node app.js &`
此命令将启动一个名为 app.js 的 Node.js 应用程序，并将其放入后台运行。

使用 pm2 进程管理工具：pm2 可以帮助您轻松地管理 Node.js 进程，包括启动、停止、重启和监控等。要在后台运行 Node.js 应用程序，可以使用以下命令：
`pm2 start app.js`
此命令将启动名为 app.js 的 Node.js 应用程序，并将其放入 pm2 进程管理器中运行。

使用 forever 模块：forever 是另一个流行的 Node.js 进程管理工具，可以在后台运行 Node.js 应用程序，并在应用程序崩溃时自动重新启动它。要使用 forever 在后台运行 Node.js 应用程序，可以使用以下命令：
`forever start app.js`
此命令将启动名为 app.js 的 Node.js 应用程序，并将其放入 forever 进程管理器中运行。

这些方法都可以在后台运行 Node.js 应用程序，并让您在终端关闭后继续运行。

**Comment by cy19734682** [comment]
#

> 要在 Node.js 项目中实现后台运行，可以使用以下几种方法：
> 
> 使用 nohup 命令和 & 符号：nohup 命令用于在后台运行进程，& 符号用于将进程放入后台。例如： `nohup node app.js &` 此命令将启动一个名为 app.js 的 Node.js 应用程序，并将其放入后台运行。
> 
> 使用 pm2 进程管理工具：pm2 可以帮助您轻松地管理 Node.js 进程，包括启动、停止、重启和监控等。要在后台运行 Node.js 应用程序，可以使用以下命令： `pm2 start app.js` 此命令将启动名为 app.js 的 Node.js 应用程序，并将其放入 pm2 进程管理器中运行。
> 
> 使用 forever 模块：forever 是另一个流行的 Node.js 进程管理工具，可以在后台运行 Node.js 应用程序，并在应用程序崩溃时自动重新启动它。要使用 forever 在后台运行 Node.js 应用程序，可以使用以下命令： `forever start app.js` 此命令将启动名为 app.js 的 Node.js 应用程序，并将其放入 forever 进程管理器中运行。
> 
> 这些方法都可以在后台运行 Node.js 应用程序，并让您在终端关闭后继续运行。

不行呢老哥，这个service是用ts编写的，代码里面是用esno模块运行的，我使用node  ./build/index.js运行报错了，报错的地方好像是require('chatgpt')的位置，不知道啥原因

**Comment by flyme6** [comment]
用这个
`nohup pnpm start &`

**Comment by cy19734682** [comment]
> 进入service用这个 `nohup pnpm start &`

还是不行，关闭shell窗口后，应用依然断开连接了

**Comment by KenNaNa** [comment]
![image](https://user-images.githubusercontent.com/39817783/226769260-0829d45c-7e5c-4016-9fa3-0c108cf1b1dd.png)
这个怎么解决？

**Comment by iamflowerdog** [comment]
蹲一个，我也发愁这个

**Comment by iamflowerdog** [comment]
> > 进入service用这个 `nohup pnpm start &`
> 
> 还是不行，关闭shell窗口后，应用依然断开连接了

你怎么确定不行的？我刚才测试了一下是可以的，你是不是一直在刷新502页面（我刚才就犯了这样的错误）？你换一个浏览器试试

**Comment by cy19734682** [comment]
> > > 进入service用这个 `nohup pnpm start &`
> > 
> > 
> > 还是不行，关闭shell窗口后，应用依然断开连接了
> 
> 你怎么确定不行的？我刚才测试了一下是可以的，你是不是一直在刷新502页面（我刚才就犯了这样的错误）？你换一个浏览器试试

关闭运行命令的xshell标签或者直接关闭xshell后，service接口报502错误

**Comment by icowan** [comment]
> ![image](https://user-images.githubusercontent.com/39817783/226769260-0829d45c-7e5c-4016-9fa3-0c108cf1b1dd.png) 这个怎么解决？

想办法走代理出去

**Comment by AHGGG** [comment]
我弄的这个：`nohup pnpm start > out.log 2>&1 &`

**Comment by LXF-DX3906** [comment]
我用了一个间接的办法，新建一个`start.sh`文件，输入`pnpm prod`，然后`chmod +x start.sh`

**Comment by iamflowerdog** [comment]
我弄的  nohup pnpm start > service.log & 这个 ，但是过几个小时就down掉了
![image](https://user-images.githubusercontent.com/27678693/227067544-7c6b8bcc-d198-4e62-aaba-eb8285b0ccb1.png)

**Comment by vinwang** [comment]
> 

直接在根目录执行
` pm2 start start.sh`
