### ISSUE TITLE
前端访问时AUTH_SECRET_KEY的值放在哪里

### ISSUE THREAD

**Issue by BruceCC** [Chanzhaoyu/chatgpt-web#754]
配置了AUTH_SECRET_KEY，但是不知道前端访问时AUTH_SECRET_KEY的值放在哪里，一直报session相关405错误

**Comment by swuecho** [comment]
打开页面的时候就应该有.

你清空缓存在试试

**Comment by jikeppq163** [comment]
清空缓存, AUTH_SECRET_KEY是第一次访问的时候需要手动输入的.

**Comment by Sichuandazhou** [comment]
配置后无效啊，前端进入没有输入呢

**Comment by Chanzhaoyu** [comment]
> 配置后无效啊，前端进入没有输入呢

配置后重启，或者清理下缓存。拉取下最新的镜像，能解决缓存的问题。

**Comment by wshze** [comment]
@Chanzhaoyu 
> 配置后重启，或者清理下缓存。拉取下最新的镜像，能解决缓存的问题。

我的AUTH_SECRET_KEY密钥都换了，服务也重启了。浏览器还是直接就进去了没让我输入最新的密钥。在不手动清除浏览器缓存下要怎么改？谢谢
