### ISSUE TITLE
请问有大佬会二开这套系统吗！想增加新功能。

### ISSUE THREAD

**Issue by zichen-fujianwangluo** [Chanzhaoyu/chatgpt-web#755]
有大佬熟悉这套源码架构能二开的可以交流交流
本人想增加一些小功能 付费有偿
再次感谢作者开源的这套系统 真的很强大！！！！

**Comment by swuecho** [comment]
你可以提需求, 如果有人感兴趣说不定就开发了

**Comment by zichen-fujianwangluo** [comment]
不知道作者接不接付费开发 有点不好意思联系

**Comment by zichen-fujianwangluo** [comment]
> 你想开发什么？



> 你想开发什么？

v：fujianwangluo

**Comment by Chanzhaoyu** [comment]
应该会出新界面，带登录、注册和用户管理等 `Admin` 功能，不过是付费的。

**Comment by KenNaNa** [comment]
大佬们，这个怎么解决？
![image](https://user-images.githubusercontent.com/39817783/226769224-0f2aafbe-3566-40a9-b131-655a44341533.png)

**Comment by daiaji** [comment]
> 应该会出新界面，带登录、注册和用户管理等 `Admin` 功能，不过可能会是付费的。

好的商业化方向。
个人用户确实会话存在本地就行了。
再不济同步到服务器也就行了。

用户管理，计费什么的，妥妥商业需求了。
个人建站只会觉得认证麻烦。
说到防止爬虫和非法访问。
能不能用cli生成一个链接或者key。
用这个链接就能当管理员。
然后管理员可以在WEBUI里创建分享用的链接。
这样感觉比设置密码优雅些。
就算是免费版感觉也有这种基础的管理需求。
防爬虫。
现有密码其实可以当作管理员的认证手段。
分享给其他人用就用生成的URL就好。
然后鉴权就用cookie。

**Comment by lsg1998** [comment]
> 有大佬熟悉这套源码架构能二开的可以交流交流 本人想增加一些小功能 付费有偿 再次感谢作者开源的这套系统 真的很强大！！！！

我就二开了一个

**Comment by zichen-fujianwangluo** [comment]
> 应该会出新界面，带登录、注册和用户管理等 `Admin` 功能，不过可能会是付费的。

这个可以的 怎么联系

**Comment by gouguoyin** [comment]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/13517412/227494457-82a60ddc-f461-45d9-b21f-4a3531ec8bb0.png">

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13517412/227494191-09896de7-089d-4bb1-8886-6e862c61b9f4.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13517412/227494240-ab3134cd-e13d-4068-95a2-5af59d7de30d.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13517412/227494302-d4b8b11c-5538-4eef-83a2-1d521a62f84c.png">

**Comment by Chocky1126** [comment]
> <img alt="image" width="1276" src="https://user-images.githubusercontent.com/13517412/227494457-82a60ddc-f461-45d9-b21f-4a3531ec8bb0.png">
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/13517412/227494191-09896de7-089d-4bb1-8886-6e862c61b9f4.png">
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/13517412/227494240-ab3134cd-e13d-4068-95a2-5af59d7de30d.png">
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/13517412/227494302-d4b8b11c-5538-4eef-83a2-1d521a62f84c.png">

酷  什么时候开放啊

**Comment by webwalker** [comment]
> 应该会出新界面，带登录、注册和用户管理等 `Admin` 功能，不过可能会是付费的。

可否增加按用户计费的功能，比如按次数、按token数量等

**Comment by maosancai** [comment]
我好像翻到大佬的链接了https://github.com/gouguoyin/chatgpt-web
小白表示不会部署，有没有大佬有纤细一点的部署教程呀
