### ISSUE TITLE
使你的项目能够在Vercel中启动

### ISSUE THREAD

**Issue by Root-FTW** [Chanzhaoyu/chatgpt-web#758]
我是vercel的用户，我想在vercel中启动你的项目，但这是不可能的。

你会很快增加对vercel的支持吗？

**Comment by Root-FTW** [comment]
如果有人设法在Vercel中发射它

能否请你详细解释一下我如何在vercel中启动它？

**Comment by Chanzhaoyu** [comment]
你需要将 `service` 文件夹分离成单独的仓库，然后分开部署它

**Comment by Root-FTW** [comment]
> 你需要将 `service` 文件夹分离成单独的仓库，然后分开部署它

有没有计划将vercel整合到这个项目中，而不必分离服务文件夹？

**Comment by Chanzhaoyu** [comment]
> 

目前是个缺陷，因为它一开始的目的是为了使用 `Docker` 快速搭建一个本地应用，也许之后会调整，不过不会是小版本更新。抱歉

**Comment by Root-FTW** [comment]
> > 
> 
> 目前是个缺陷，因为它一开始的目的是为了使用 `Docker` 快速搭建一个本地应用，也许之后会调整，不过不会是小版本更新。抱歉

谢谢你的答复和你的善意。

我愿意为获得这一更新而捐款。

目前，你可以一步一步地详细解释如何在vercel中部署它，我不明白我到底要做什么才能使它在vercel中工作。

**Comment by Chanzhaoyu** [comment]
我先部署一个测试下

**Comment by Root-FTW** [comment]
对不起，我只会说英语，但这个项目在github是目前最好的，有很多英语和其他国家的项目，但这是所有github中最完整的项目。

尊敬的主人

**Comment by Chanzhaoyu** [comment]
@Root-FTW ，我测试了下，现在的文件结构和命名并不符合 `vercel`，会请求不到 `API`。或许你可以使用 `Railway` ?

**Comment by Root-FTW** [comment]
> @Root-FTW ，我测试了下，现在的文件结构和命名并不符合 `vercel`，会请求不到 `API`。或许你可以使用 `Railway` ?

今天我开始使用铁路，但它远不如Vercel，Vercel的免费版本在各方面都远远优于它。

事实上，github上99%的使用OpenAI API进行对接的项目都喜欢使用Vercel，这可以节省很多钱，而且他们的基础设施更好。

我希望你能让你的项目在Vercel上运行，我相信如果你这么做，它在github上会变得更受欢迎。

**Comment by Chanzhaoyu** [comment]
明白，一开始本来只是个人部署的项目，并没有完整的规划，但是现在超出了预期。

**Comment by Root-FTW** [comment]
> 明白，一开始本来只是个人部署的项目，并没有完整的规划，但是现在超出了预期。

我希望你能考虑，并希望你将来能整合vercel。

**Comment by Chanzhaoyu** [comment]
> > 明白，一开始本来只是个人部署的项目，并没有完整的规划，但是现在超出了预期。
> 
> 说起来，之后的开发计划会加入在网页修改系统角色的prompt吧？ 不然砍Token也意义不大的样子。 现有的prompt商店好像也只有替代黏贴复制的作用。

会，如果只是 API 的话，直接放到请求里面，设定为角色

**Comment by echostars** [comment]
> 明白，一开始本来只是个人部署的项目，并没有完整的规划，但是现在超出了预期。

我也发issues询问过，以为vercel和railway可以一键部署，后来才知道需要前后端分离。相比于其他chatgpt的web项目，我对作者的这个项目ui和功能还是非常喜欢的。但是railway的免费额度和自定义域名步骤相比vercel更不占优势，希望作者您能增加对vercel的支持！

**Comment by LokerL** [comment]
我也更倾向于vercel，我的很多项目都是部署在vercel上。
希望出一个vercel版本的，就像[chatgpt-demo](https://github.com/ddiu8081/chatgpt-demo)和[chatgpt-vercel](https://github.com/ourongxing/chatgpt-vercel)
我也更喜欢这个项目的UI

**Comment by LokerL** [comment]
> 对不起，我只会说英语，但这个项目在github是目前最好的，有很多英语和其他国家的项目，但这是所有github中最完整的项目。
> 
> 尊敬的主人

@Root-FTW   Your translation style is like Microsoft's. Try to get ChatGPT to help you translate in Chinese. :smile:

**Comment by Root-FTW** [comment]
> > 对不起，我只会说英语，但这个项目在github是目前最好的，有很多英语和其他国家的项目，但这是所有github中最完整的项目。
> > 尊敬的主人
> 
> @Root-FTW Your translation style is like Microsoft's. Try to get ChatGPT to help you translate in Chinese. 😄

"实际上，我了解这些项目，并从一开始就使用它们，因此我熟悉 Vercel 哈哈，我过去使用 DeepL 将英语翻译成中文，我刚刚用 GPT-4 翻译了这条评论，翻译得更好了吗？"

**Comment by tianstephanie** [comment]
I thought DEEPL would be better, but it seems that the translation by GPT is better and more readable. This sentence was translated using GPT :)

**Comment by nagaki09** [comment]
> > > 对不起，我只会说英语，但这个项目在github是目前最好的，有很多英语和其他国家的项目，但这是所有github中最完整的项目。
> > > 尊敬的主人
> > 
> > 
> > @Root-FTW Your translation style is like Microsoft's. Try to get ChatGPT to help you translate in Chinese. 😄
> 
> "实际上，我了解这些项目，并从一开始就使用它们，因此我熟悉 Vercel 哈哈，我过去使用 DeepL 将英语翻译成中文，我刚刚用 GPT-4 翻译了这条评论，翻译得更好了吗？"

much better

**Comment by daiaji** [comment]
> "实际上，我了解这些项目，并从一开始就使用它们，因此我熟悉 Vercel 哈哈，我过去使用 DeepL 将英语翻译成中文，我刚刚用 GPT-4 翻译了这条评论，翻译得更好了吗？"

润色上似乎更好了。

**Comment by pzcn** [comment]
据我了解，vercel是serverless部署，每次的运行时间是毫秒级的。在这种情况下后端真能支持几秒的运行时间来获得输出吗
倒是前端部署在vercel肯定是没问题的

**Comment by baby9** [comment]
> 据我了解，vercel是serverless部署，每次的运行时间是毫秒级的。在这种情况下后端真能支持几秒的运行时间来获得输出吗 倒是前端部署在vercel肯定是没问题的

[This Project](https://github.com/ddiu8081/chatgpt-demo) is popular too and can be deployed on Vercel

**Comment by LXF-DX3906** [comment]
> 据我了解，vercel是serverless部署，每次的运行时间是毫秒级的。在这种情况下后端真能支持几秒的运行时间来获得输出吗 倒是前端部署在vercel肯定是没问题的

可以的，已经有大佬做出来了[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)

**Comment by suikodev** [comment]
因为我这边正在将一些我的服务从 k8s 迁移到 vercel, 所以我刚好有调研过将 chatgpt-web 部署到 vercel 的可能性。预计周末会在我二次开发的项目 [gpteams](https://github.com/suikodev/gpteams) 中添加 vercel 支持。

**但是这里有一点风险。**

如果部署到 vercel, 后端的服务会变成 vercel 的 serverless function，而 vercel 的 hobby plan 支持 [serverless function 最大的运行时间是 10s](https://vercel.com/docs/concepts/limits/overview#general-limits)，所以实际上后端的服务会有超时的可能。

**Comment by hswmartin** [comment]
> 因为我这边正在将一些我的服务从 k8s 迁移到 vercel, 所以我刚好有调研过将 chatgpt-web 部署到 vercel 的可能性。预计周末会在我二次开发的项目 [gpteams](https://github.com/suikodev/gpteams) 中添加 vercel 支持。
> 
> **但是这里有一点风险。**
> 
> 如果部署到 vercel, 后端的服务会变成 vercel 的 serverless function，而 vercel 的 hobby plan 支持 [serverless function 最大的运行时间是 10s](https://vercel.com/docs/concepts/limits/overview#general-limits)，所以实际上后端的服务会有超时的可能。

调用openai接口的function 使用edge function,那个超时时间是第一个响应30秒 ,后面的流式返回不限制时间了，基本不会超时了

**Comment by Root-FTW** [comment]
> > @Root-FTW ，我测试了下，现在的文件结构和命名并不符合 `vercel`，会请求不到 `API`。或许你可以使用 `Railway` ?
> 
> 我在另一个项目中看到说不建议使用除 Vercel 以外的部署方案。 除了比较慢以外，更重要的是只有 Vercel 支持设置 Edge Function 服务器的地区，其他平台会自动使用距离最近的服务器，有可能是 OpenAI 不支持的地区，从而导致封号。

就在今天，我支付了railway的开发者版本，看到每个月前5美元的消费都是免费的，我认为我可能永远用不上这5美元，所以现在我对railway非常满意

**Comment by Root-FTW** [comment]
> 就在今天，我支付了railway的开发者版本，看到每个月前5美元的消费都是免费的，我认为我可能永远用不上这5美元，所以现在我对railway非常满意

就在今天，我支付了railway的开发者版本，看到每个月前5美元的消费都是免费的，我认为我可能永远用不上这5美元，所以现在我对railway非常满意
