### ISSUE TITLE
https://zyt.im/ 改的不错谁能实现啊？

### ISSUE THREAD

**Issue by zhaohai1024** [Chanzhaoyu/chatgpt-web#761]
https://zyt.im/ 改的不错谁能实现啊？ 不留版权？

**Comment by fungoindia** [comment]
垃圾玩意儿 随便改了改了 连作者的连接都不保留了

**Comment by imdingtalk** [comment]
还改的不错，一点尊重没有

**Comment by zhaohai1024** [comment]
<img width="627" alt="iShot_2023-03-22_15 45 14" src="https://user-images.githubusercontent.com/127855845/226835522-a8749f8b-79f0-4b54-be35-5aed9254d5bb.png">
没见有你说的作者链接

**Comment by jurieo** [comment]
使用免费的来盈利，真的可耻。

**Comment by daiaji** [comment]
人间之屑

**Comment by Chanzhaoyu** [comment]
哈哈，其实我也不是很在意，如果赚了钱记得请我喝杯奶茶。
