### ISSUE TITLE
建议新增用户机制，把每次聊天的内容和用户关联

### ISSUE THREAD

**Issue by yangbinmao** [Chanzhaoyu/chatgpt-web#763]
作者你好，在使用过程中，发现聊天历史数据是缓存在浏览器的，清空浏览器后，之前的记录会丢失。所以想建议是否可以新增用户管理。将聊天的内容和用户管理，保存到服务器，而不是浏览器，这样用户在登录自己账号时可以看到自己历史记录，就像官网一样的功能。谢谢

**Comment by swuecho** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/pull/589 node 后端 + mongo
https://github.com/swuecho/chat golang后端 + postgres

**Comment by Chanzhaoyu** [comment]
这个有其他开发者做了

**Comment by yangbinmao** [comment]
这个，咱就不能合成到我们这个项目下哇。这样 才可以使我们这个项目更好，更完整晒。

**Comment by OyutianO** [comment]
想问下浏览器缓存如果满了，新的聊天记录还会存吗？

**Comment by swuecho** [comment]
> 想问下浏览器缓存如果满了，新的聊天记录还会存吗？

应该不会的
