### ISSUE TITLE
希望能增加主界面的使用提示，方便小白上手

### ISSUE THREAD

**Issue by fzucs** [Chanzhaoyu/chatgpt-web#764]
我搭了一个想给周围的朋友玩一玩，但是有些人对很多功能不怎么了解，比如prompt store这种，所以希望能在主界面增加使用提示，引导用的人了解更多实用技巧。像下图这种。作为小白只会按部就班，不会修改代码....
![tips](https://user-images.githubusercontent.com/100392795/226794975-f0886561-bbf3-4113-9fbc-183c2a40bf35.png)

**Comment by Chanzhaoyu** [comment]
实现很容易，但是我实在不想做翻译。

**Comment by fzucs** [comment]
这个我来，然后我把三个版本文本直接发您可以吗？

**Comment by luckywangxi** [comment]
> 我搭了一个想给周围的朋友玩一玩，但是有些人对很多功能不怎么了解，比如prompt store这种，所以希望能在主界面增加使用提示，引导用的人了解更多实用技巧。像下图这种。作为小白只会按部就班，不会修改代码....
> ![tips](https://user-images.githubusercontent.com/100392795/226794975-f0886561-bbf3-4113-9fbc-183c2a40bf35.png)
> 

这个网页可以发我一下吗，直接F12扒，啊哈哈哈

**Comment by fzucs** [comment]
> > 我搭了一个想给周围的朋友玩一玩，但是有些人对很多功能不怎么了解，比如prompt store这种，所以希望能在主界面增加使用提示，引导用的人了解更多实用技巧。像下图这种。作为小白只会按部就班，不会修改代码....
> > ![tips](https://user-images.githubusercontent.com/100392795/226794975-f0886561-bbf3-4113-9fbc-183c2a40bf35.png)
> 
> 这个网页可以发我一下吗，直接F12扒，啊哈哈哈

cgpt.im
