### ISSUE TITLE
预置prompt

### ISSUE THREAD

**Issue by just2022try** [Chanzhaoyu/chatgpt-web#767]
大佬您好， 想请问如何预置一些prompt，因为下载的那些调教指南并不太合适，且数量过多，然后放置时别人也不太会下载。想知道如何预置一些prompt呢？

**Comment by daiaji** [comment]
商店里的prompt确实有点过期就是了。
预置的话，感觉弄个单独的仓库然后加到商店可能会比较好。

**Comment by gouguoyin** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/13517412/227081251-fadaebc6-5602-4193-943f-21c0b0d8e404.png">

**Comment by wujt1084** [comment]
> <img alt="image" width="1277" src="https://user-images.githubusercontent.com/13517412/227081251-fadaebc6-5602-4193-943f-21c0b0d8e404.png">

这不是这个项目的界面吧

**Comment by gouguoyin** [comment]
这个项目的管理后台

**Comment by daiaji** [comment]
控制面板的入口在哪？

**Comment by wujt1084** [comment]
同问

**Comment by VectorZhao** [comment]
> <img alt="image" width="1277" src="https://user-images.githubusercontent.com/13517412/227081251-fadaebc6-5602-4193-943f-21c0b0d8e404.png">

这是哪个fork项目？

**Comment by jwdstef** [comment]
管理后台的入口地址是？
