### ISSUE TITLE
socks代理有账户密码要怎么配置？

### ISSUE THREAD

**Issue by kof8855** [Chanzhaoyu/chatgpt-web#769]
暂时用v2ray的socks代理功能，是没有密码的，但是不怎么稳定
想直接在vps上开socks代理服务，但是又不能不设置密码免得被白嫖

**Comment by wujt1084** [comment]
我前几天被白嫖了几十个G流量，你端口不对外开放就行了

**Comment by Monica-lee99** [comment]
> 暂时用v2ray的socks代理功能，是没有密码的，但是不怎么稳定 想直接在vps上开socks代理服务，但是又不能不设置密码免得被白嫖

这里怎么弄的
