### ISSUE TITLE
如何设置添加弹窗，有没有大佬提供一下思路

### ISSUE THREAD

**Issue by luckywangxi** [Chanzhaoyu/chatgpt-web#772]
添加有button的弹窗，内容可修改的，弹窗位置在右下角,手机用户在正下方

**Comment by swuecho** [comment]
NModal

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/blob/master/web/src/views/chat/index.vue#LL501-L505C16

**Comment by luckywangxi** [comment]
> https://github.com/swuecho/chat/blob/master/web/src/views/chat/index.vue#LL501-L505C16
> 
> 

谢谢，待会回宿舍看看

**Comment by luckywangxi** [comment]
> https://github.com/swuecho/chat/blob/master/web/src/views/chat/index.vue#LL501-L505C16

没看懂，啊哈哈哈哈，可以告诉我怎么引用吗，在哪个文件怎么修改，我只需要在打开网页时自动显示弹窗，电脑的弹窗位置在网页右下角，手机的在下半部分，弹窗内容为xxxxxxxx，感谢感谢

**Comment by swuecho** [comment]
> > https://github.com/swuecho/chat/blob/master/web/src/views/chat/index.vue#LL501-L505C16
> 
> 没看懂，啊哈哈哈哈，可以告诉我怎么引用吗，在哪个文件怎么修改，我只需要在打开网页时自动显示弹窗，电脑的弹窗位置在网页右下角，手机的在下半部分，弹窗内容为xxxxxxxx，感谢感谢

https://github.com/Chanzhaoyu/chatgpt-web/blob/main/src/views/chat/index.vue#LL489C13-L489C32

最简单的事你替换 aha, 改成你想要的内容. 复杂一点不会vue 短时间不好搞.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/666683/226904158-6c3f3ba5-59ef-406f-b177-b5e53add48e4.png">
