### ISSUE TITLE
默认前端访问地址端口是3002  如何改成其他端口？

### ISSUE THREAD

**Issue by panhuanghe** [Chanzhaoyu/chatgpt-web#774]
默认前端访问地址端口是3002  如何改成其他端口？

**Comment by IIllIIIlll** [comment]
如果你想要自定义后端端口，请在`./service/src/index.ts`中将最后一行的数字`3002`改成你想要的端口，随后在./.env中将监听端口改为你修改的值。
如果你想要修改前端端口，有三种方式：
- 运行时加上参数，例如`pnpm dev --port 1234`，此时`1234`为前端端口。
- 修改`./vite.config.ts`，将`1002`改为其他端口。
- 编辑`package.json`，在`pnpm dev`命令后面加上`--port 1234`，此时`1234`为前端端口。

**Comment by panhuanghe** [comment]
感谢大佬

**Comment by IIllIIIlll** [comment]
如果问题解决了的话，麻烦把这个Issues关闭，谢谢！

**Comment by adinxiang** [comment]
docker的话把 ”：”前边的3002直接改成想要的端口即可

**Comment by daiaji** [comment]
感觉之后用个统一的变量管理比较好。
