### ISSUE TITLE
请假几个问题谢谢，使用OPENAI_API_KEY，上下文不能关联

### ISSUE THREAD

**Issue by inlmcn** [Chanzhaoyu/chatgpt-web#776]
![企业微信截图_16794693904242](https://user-images.githubusercontent.com/61356473/226828887-991030aa-d870-4a49-ad86-264e33f047fd.png)
还有一个问题就是结果出来的时候打印机效果的出字效果怎么开启的

**Comment by IIllIIIlll** [comment]
请检查是否开启上下文功能，检查方式：聊天框左侧是绿色。
请检查nginx设置是否关闭缓冲设置，参阅readme：https://github.com/Chanzhaoyu/chatgpt-web#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by inlmcn** [comment]
谢谢大佬

**Comment by IIllIIIlll** [comment]
如果解决了问题，请关闭Issue，谢谢。

**Comment by inlmcn** [comment]
我用OPENAI_ACCESS_TOKEN 就没发现这个问题，OPENAI_API_KEY就出现，这个应该不是关闭的问题吧大佬

**Comment by inlmcn** [comment]
我问个问题好像没完结，如果继续，上下文就不关联了
