### ISSUE TITLE
接口数据格式化问题

### ISSUE THREAD

**Issue by Gary2018X** [Chanzhaoyu/chatgpt-web#785]
想请教一下目前后端chat-process接口返回数据能否进一步规范化 目前看着也不像json

**Comment by swuecho** [comment]
server side event.

文本自己解析的

**Comment by Gary2018X** [comment]
这个打字机的效果是不是可以在前端实现，这样还能减少请求时间

**Comment by Gary2018X** [comment]
然后我也有注意到这个格式 在service侧进行了微调 ；其实是不是没必要

**Comment by swuecho** [comment]
> 这个打字机的效果是不是可以在前端实现，这样还能减少请求时间

不能的, openai 目前的速度太慢了, 不是拿到完成答案才返回的, 而是变从openai那边获取输出,边打出来. 打字机效果事副产品

**Comment by Gary2018X** [comment]
感觉和您这前端的一样 但是前端解析不了

**Comment by Gary2018X** [comment]
已解决 返回用application/octet-stream就可以了
