### ISSUE TITLE
将key配置好之后本地启动成功，但是试图聊天却一直报错

### ISSUE THREAD

**Issue by oybalabala** [Chanzhaoyu/chatgpt-web#787]
我只配置了KEY，前后段都可以启动成功，但是聊天的时候一直报错，请问是还有什么没有配置吗？还有，不使用VPN会不会被封号呀？
机器人聊天的时候一直回复：undefined
[request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 157.240.12.5:443]
有老铁遇到么？本地启动就这样555

**Comment by Chanzhaoyu** [comment]
需要代理，接口国内访问不了

**Comment by Chanzhaoyu** [comment]
> > 需要代理，接口国内访问不了
> 
> 我还比较小白，可以问下代理如何配置么？需要租一个比如阿里云的服务器作为代理服务器么？

这个我不知道怎么解释，我帮不了你。要不你搜索引擎搜索下或者在 GitHub 上找下有没有代理教程，我记得是有的。

**Comment by oybalabala** [comment]
> > > 需要代理，接口国内访问不了
> > 
> > 
> > 我还比较小白，可以问下代理如何配置么？需要租一个比如阿里云的服务器作为代理服务器么？
> 
> 这个我不知道怎么解释，我帮不了你。要不你搜索引擎搜索下或者在 GitHub 上找下有没有代理教程，我记得是有的。

主要是如果在国内租服务器的话，应该也是访问不了国外的地址吧？

**Comment by hongfs** [comment]
直接部署在亲美国家吧。

**Comment by sucre0107** [comment]
我是部署在docker上的,vps是美国的,就没问题了

**Comment by dqzboy** [comment]
买个机场(便宜的就行，比买国外VPS划算)，然后国内有服务器，直接国内的服务器部署个clash就行了

**Comment by sucre0107** [comment]
请问机场也可以安装docker吗?

dqzboy ***@***.***> 于2023年3月22日周三 22:32写道：

**Comment by oybalabala** [comment]
> 兄弟有相关的教程么？

有机场，但是不知道怎么弄，有木有教程哇

**Comment by dqzboy** [comment]
> 

使用这个项目在你的国内服务器上安装科学上网 https://github.com/juewuy/ShellClash

**Comment by StephenHuge** [comment]
如果本地已经开启了clash之类的proxy，可以把这两行加上，我这边work了。
```env
# Socks Proxy Host
SOCKS_PROXY_HOST=127.0.0.1

# Socks Proxy Port
SOCKS_PROXY_PORT=7890
```

**Comment by oldfishoh** [comment]
> > > > 需要代理，接口国内访问不了
> > > 
> > > 
> > > 我还比较小白，可以问下代理如何配置么？需要租一个比如阿里云的服务器作为代理服务器么？
> > 
> > 这个我不知道怎么解释，我帮不了你。要不你搜索引擎搜索下或者在 GitHub 上找下有没有代理教程，我记得是有的。
> 
> 主要是如果在国内租服务器的话，应该也是访问不了国外的地址吧？

在云服务器上开🔮

**Comment by codePigPig** [comment]
> 如果本地已经开启了clash，可以把这两行加上，clash默认的代理端口是7890。
> 
> ```dotenv
> # Socks Proxy Host
> SOCKS_PROXY_HOST=127.0.0.1
> 
> # Socks Proxy Port
> SOCKS_PROXY_PORT=7890
> ```



> 如果本地已经开启了clash，可以把这两行加上，clash默认的代理端口是7890。
> 
> ```dotenv
> # Socks Proxy Host
> SOCKS_PROXY_HOST=127.0.0.1
> 
> # Socks Proxy Port
> SOCKS_PROXY_PORT=7890
> ```

感谢你的解决方法， 我试了下这个确实解决了我的问题

**Comment by boyan1010** [comment]
> 如果本地已经开启了clash，可以把这两行加上，clash默认的代理端口是7890。
> 
> ```dotenv
> # Socks Proxy Host
> SOCKS_PROXY_HOST=127.0.0.1
> 
> # Socks Proxy Port
> SOCKS_PROXY_PORT=7890
> ```

请问，这两行配置的作用是什么？让localhost走代理么？

**Comment by haobing55** [comment]
> 如果本地已经开启了clash，可以把这两行加上，clash默认的代理端口是7890。
> 
> ```dotenv
> # Socks Proxy Host
> SOCKS_PROXY_HOST=127.0.0.1
> 
> # Socks Proxy Port
> SOCKS_PROXY_PORT=7890
> ```

感谢你的回答让我解决了问题。
