### ISSUE TITLE
TS文件格式问题

### ISSUE THREAD

**Issue by MasonLiu719** [Chanzhaoyu/chatgpt-web#792]
我通过宝塔将服务器代码部署到wwwroot下后进行访问，一直卡在三个球加载的页面，查看网页元素发现是浏览器将.ts文件识别为了视频格式文件导致无法正常运行，而且当我尝试在服务器下载typescript，服务器并不能正常对其正常安装，tsc识别不到，而且通过which或者whereis均未找到下载
请问如何解决

**Comment by Chanzhaoyu** [comment]
建议打包后再部署
