### ISSUE TITLE
请问前端和后端端口问题

### ISSUE THREAD

**Issue by csu-czh** [Chanzhaoyu/chatgpt-web#793]
我的理解是service是后端，根目录是前端，而后端端口是3002，前端端口是1002
那为啥访问web的时候是输入localhost:3002 呢？
我手动打包到tomcat，但是访问localhost：8080/chatgpt 就报500错误，请教各位！

**Comment by csu-czh** [comment]
这些端口问题我弄明白了。访问3002跳转到了1002吧？ 对于新手不是很友好，于是我改掉了。只能通过前端端口访问web

**Comment by hieivip** [comment]
> 

怎么修改的？
