### ISSUE TITLE
发送消息后出现了 [request to https://api.openai.com/chat/completions failed, reason: self-signed certificate in certificate chain] 错误有大佬知道什么原因嘛？

### ISSUE THREAD

**Issue by yuantianji** [Chanzhaoyu/chatgpt-web#794]
![微信截图_20230323001720](https://user-images.githubusercontent.com/37831658/226970161-ad926338-4076-402c-b442-7fea181c742e.png)

**Comment by chukongpeng** [comment]
是的，我也碰到了这个问题

**Comment by rennai** [comment]
应该是你域名启用了https，并且是自签名的证书。你可以试试用 Let's Encrypt 的证书

**Comment by zhujunsan** [comment]
这个是不是因为 OpenAI 用的证书的根证书不被后端认识？需要更新系统的 ca 包到最新
