### ISSUE TITLE
框架建议

### ISSUE THREAD

**Issue by Canees** [Chanzhaoyu/chatgpt-web#8]
1. 加上compression 来压缩，压缩率80%左右
2. 拆分node_modules 的包
3. 框架代码格式化没必要prettier（可能方便），直接plugins: [eslint({ fix: true, include: ['**/*.ts', '**/*.vue'] })],自定义风格
4. 如果只是娱乐，全当没说

**Comment by Chanzhaoyu** [comment]
嗯，感谢建议～
