### ISSUE TITLE
中文回复有乱码问题

### ISSUE THREAD

**Issue by dh-free** [Chanzhaoyu/chatgpt-web#800]
![image](https://user-images.githubusercontent.com/48708512/227071982-967fb85a-3a99-447f-bff4-ca086dd37fef.png)

![image](https://user-images.githubusercontent.com/48708512/227072018-1bbdbf0b-6624-4271-adc9-18f6bb0ade3f.png)

**Comment by Chanzhaoyu** [comment]
是否改了模型？

**Comment by dh-free** [comment]
> 是否改了模型？

什么都没改，贴上我nginx的配置：
![image](https://user-images.githubusercontent.com/48708512/227161919-eaa81374-b27c-451c-91c4-7a191c423641.png)
