### ISSUE TITLE
建议向我一样的小白部署的时候加上密码

### ISSUE THREAD

**Issue by wuzhijie0101** [Chanzhaoyu/chatgpt-web#803]
之前的一个18刀账户用了一个月才用了不到3刀，这几天突然额度就用完了，看后后台才发现一天就给我用了13刀的额度，估计时被扫端口了，又注册了个新的发现哪怕我立马改端口，只要一启动后端狗就来了，看了日志都是翻译PDF文件，一次1000token+，真是给我恶心坏了。加了访问密码后就没有了，所以新手部署的时候一定要加上密码。文件在service/.env：# Secret key
AUTH_SECRET_KEY=后面加上你的密码重启服务就好了。

**Comment by DIYer22** [comment]
同样的遭遇加1， 都是翻译， 我一天花了 4$

**Comment by Cp0204** [comment]
作者再三强调了，并且修改主页标题，以免被扫

**Comment by expfukck** [comment]
我是加了密码 +标题修改 不然这些B一下给你用完的

**Comment by wuzhijie0101** [comment]
改了标题，加了密码，终于没被用了，特么的。

**Comment by slashinchi** [comment]
同样的遭遇，两天12刀。
如果是docker-compose部署的一定记得在environment中添加AUTH_SECRET_KEY。
另外如果需要修改index.html的title,可以加一个command，每次up -d的时候就不用手动自己改了。
给个参考：
command: sh -c "sed -i 's#<title>.*<\/title>#<title>这里随便填<\/title>#g' /app/public/index.html && npm start"

**Comment by zhuxindong** [comment]
密码还有可能被爆破，建议再加上限流参数
