### ISSUE TITLE
IAP 登录页面和前端 PWA 冲突

### ISSUE THREAD

**Issue by DIYer22** [Chanzhaoyu/chatgpt-web#805]
问题描述
在 PWA 加载到浏览器本地后， 并且 IAP（Identity Aware Proxy 身份验证代理） 过期后， PWA 客户端无法和服务器通信的情况。也由于 PWA 客户端的存在， 只会显示 Network Error， 不会跳转的到 IAP 登录界面。

目前的临时手段有：
1. 用户通过 http://iap.hh-d.brainpp.cn/ 来登录 IAP
2. 或者用户清理浏览器 PWA 缓存后重新登录 IAP

求好心人指导，怎么做科学方便？

**Comment by Chanzhaoyu** [comment]
`v2.10.8` 中 `PWA` 默认不开启。
