### ISSUE TITLE
后端服务404

### ISSUE THREAD

**Issue by rank97** [Chanzhaoyu/chatgpt-web#806]
我是前端打包部署在nginx上，后端本地起的服务，想在我的域名下增加目录
具体修改配置如下

<img width="669" alt="image" src="https://user-images.githubusercontent.com/82438695/227124545-1d4a6ebc-f961-499d-9e97-b309df359a90.png">

nginx 配置如下
<img width="484" alt="image" src="https://user-images.githubusercontent.com/82438695/227124919-8c60171e-195f-4b3e-99e2-add85ef89446.png">
但是访问服务的时候报错404
<img width="839" alt="image" src="https://user-images.githubusercontent.com/82438695/227125234-443fd0b6-e679-4e1b-9091-4d9be7fa7da7.png">
不知道我哪里设置错了，哪位老师能帮忙看看吗

**Comment by ChihyuenLi** [comment]
解决了吗？

**Comment by rank97** [comment]
/chat/api 这个路径应该转发到xxxx:3002/api   配置成这样就行了
