### ISSUE TITLE
PWA插件未生效问题

### ISSUE THREAD

**Issue by bingo235** [Chanzhaoyu/chatgpt-web#808]
这个提交中修改PWA开启逻辑https://github.com/Chanzhaoyu/chatgpt-web/commit/d2a22a3ee5d59affa7f3ca0a85491b4f6e87fc44
但未将PWA插件push到plugins数组，即使VITE_GLOB_APP_PWA配置为true也不能生效。
https://github.com/Chanzhaoyu/chatgpt-web/blob/917feec5d8f4512b26d3bcac7fba6465342e8371/vite.config.ts#L11

已经提交PR
https://github.com/Chanzhaoyu/chatgpt-web/pull/807

PS:此PR修复代码由ChatGPT生成

**Comment by Chanzhaoyu** [comment]
感谢贡献
