### ISSUE TITLE
bug：移动端点击new chat 后未收起左边栏

### ISSUE THREAD

**Issue by huangzt** [Chanzhaoyu/chatgpt-web#809]
如题所说，移动端界面点击new chat未收起左侧菜单，而鼠标焦点已聚焦在输入框，比较丑。

**Comment by Chanzhaoyu** [comment]
感谢反馈，已经修复，现在已经会自动收起侧边栏。

**Comment by Chanzhaoyu** [comment]
> 还有bug，移动端左侧栏删除一条记录后。。。不会收起，同上。

好家伙
