### ISSUE TITLE
请问修改主题色在哪个文件里？

### ISSUE THREAD

**Issue by woodchen-ink** [Chanzhaoyu/chatgpt-web#811]
主题的绿色，虽然很好用并且明显，但是我还是想要换成蓝色看看，请问在哪个文件里修改呢

**Comment by Chanzhaoyu** [comment]
请参考 [Naive UI](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme) 设定

**Comment by woodchen-ink** [comment]
> 请参考 [Naive UI](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme) 设定

好的，谢谢大佬
