### ISSUE TITLE
Azure openAI支持

### ISSUE THREAD

**Issue by cnkang** [Chanzhaoyu/chatgpt-web#812]
有没有可能支持Azure云上的openAI？谢谢
我看到了一个例子：https://github.com/xuhaoruins/azure-openai-quickstart-node

**Comment by Kele087** [comment]
https://libraries.io/npm/azure-openai  nodejs sdk在这里

**Comment by stulzq** [comment]
使用我做的 proxy 吧，https://github.com/stulzq/azure-openai-proxy

**Comment by diemus** [comment]
我也写了一个，支持代理所有模型和接口，有兴趣的可以试试：https://github.com/diemus/azure-openai-proxy。

**Comment by yi-ge** [comment]
Cool

**Comment by PeterDaveHello** [comment]
👉 #855
