### ISSUE TITLE
用accessToken  反代代理想用自己的找到大佬acheong08

### ISSUE THREAD

**Issue by expfukck** [Chanzhaoyu/chatgpt-web#814]
可惜不会搭建,那我大神会acheong08/chatgpt 部署! 弄个反向代理

https://github.com/acheong08/ChatGPT   跪求那我大神,请下如何VPS搭建 反向代理!

**Comment by expfukck** [comment]
好吧! 我本来是想用冲会员 用token 但是怕封号 一直不敢充值!  不过你的web是真好用 ! 如果能增加微调功能就完美了

**Comment by Chanzhaoyu** [comment]
记得不要用第三方的哈，第三方也是套 `acheong08` 的壳，还会收集你的信息。

**Comment by expfukck** [comment]
> 记得不要用第三方的哈，第三方也是套 `acheong08` 的壳，还会收集你的信息。

好的 不会去用第三方代理, 主要是acheong08代理是万人骑 如果我自己nginx反向代理他的话 是否能降低封号风险 这样可以吗?

**Comment by Chanzhaoyu** [comment]
> > 记得不要用第三方的哈，第三方也是套 `acheong08` 的壳，还会收集你的信息。
> 
> 好的 不会去用第三方代理, 主要是acheong08代理是万人骑 如果我自己nginx反向代理他的话 是否能降低封号风险 这样可以吗?

你反代没有区别的，还是要走他的

**Comment by expfukck** [comment]
> > > 记得不要用第三方的哈，第三方也是套 `acheong08` 的壳，还会收集你的信息。
> > 
> > 
> > 好的 不会去用第三方代理, 主要是acheong08代理是万人骑 如果我自己nginx反向代理他的话 是否能降低封号风险 这样可以吗?
> 
> 你对反代真的好执着，到处都能看到你..我不理解

本想的是弄token代理 充值会员 但是怕封号 只能考虑 国内服务器API反代   回复效率就会好一点的!
