### ISSUE TITLE
设置页高级选项消失

### ISSUE THREAD

**Issue by ottocsb** [Chanzhaoyu/chatgpt-web#815]
设置页 高级 点击重置，页面刷新后设置内 高级 消失，且版本显示为2.10.7
部署环境是railway

**Comment by ottocsb** [comment]
> 

未点击重置时显示版本为2.10.8，点击后版本就变了，需要ctrl+f5 后恢复到正常
我重新部署看下

**Comment by Chanzhaoyu** [comment]
> 

可能是 `Railway` 的缓存问题

**Comment by ottocsb** [comment]
> > 
> 
> 可能是 `Railway` 的缓存问题.

重新部署一样，本地环境没复现出，认定是 `Railway` 的缓存问题
