### ISSUE TITLE
一个小问题：获取余额没走代理，如果在国内搭建，会获取不到余额

### ISSUE THREAD

**Issue by HHhne** [Chanzhaoyu/chatgpt-web#816]

**Comment by Chanzhaoyu** [comment]
设置 `OPENAI_API_BASE_URL` 可行

**Comment by fightroad** [comment]
> 设置 `OPENAI_API_BASE_URL` 可行

我也发现了，现在已经设置了https代理的，api接口是走单独的代理吗？

**Comment by Chanzhaoyu** [comment]
> > 设置 `OPENAI_API_BASE_URL` 可行
> 
> 我也发现了，现在已经设置了https代理的，api接口是走单独的代理吗？

是分开的接口

**Comment by dopsieee** [comment]
可以明示一下怎么配置 OPENAI_API_BASE_URL 吗，没试出来
