### ISSUE TITLE
展示你的项目或功能

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#818]
1. 把你的项目展示给大家
2. 包括但不限于二开的项目或功能
3. 请在下方留言，过分的商业推广会删除

**Comment by 0xinfinitykernel** [comment]
1.https://luckrelay.com
2.修改前端(2.8.3版本)支持sse,后端使用Go实现.
3.首页保留了前端项目出处,如觉得过分使用请通知修改或去除  :)

需要特别说明的是,主要方便部分不方便使用ChatGPT的人,请误滥用,感谢。
