### ISSUE TITLE
auth_subrequest_error

### ISSUE THREAD

**Issue by Aurelius-Huang** [Chanzhaoyu/chatgpt-web#82]
ChatGPT error 500: {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}

**Comment by streetlight3316** [comment]
这会儿好像用达芬奇003模型的都不行了

**Comment by Chanzhaoyu** [comment]
官方出问题了

**Comment by dayunnas** [comment]
一模一样的错误，我用网页也不行

**Comment by streetlight3316** [comment]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/66906265/220288409-9e07a7b5-f49b-4d05-828a-10d3c1adc611.png">
