### ISSUE TITLE
功能建议：密钥支持多个，如：分号隔开，分享给别人用的时候可以直接加多个，不想给好友用了，就去掉该密钥。

### ISSUE THREAD

**Issue by huangzt** [Chanzhaoyu/chatgpt-web#821]
建议如题，等同于多账号授权，加一行代码，改一行判断即可。。。只增强功能。因为分享给好友使用时，避免他又发给他人，流量一下子少了很多，这时出于自我保护，干掉他的密钥，没钱充了。。。

**Comment by huangzt** [comment]
这个很简单的，我可以。。。

**Comment by cy-i** [comment]
这个功能不错，多个密码给多个人，不想给了就取消！可以设置密码有效期就更好了！
