### ISSUE TITLE
重新部署后无法继续之前的会话

### ISSUE THREAD

**Issue by unique-cloud** [Chanzhaoyu/chatgpt-web#823]
我是在Railway上部署的app，今天Sync了一下新的代码，然后就触发了重新部署。重新部署之后历史会话虽然还能看到（因为存在浏览器里），但是实质上并不能继续之前的会话了。如果尝试继续对话，从回复中能看出它并不记得之前的上下文。

我看了一下后台的Log，也确认了它并没有发送之前的历史消息。感觉应该是个bug？

**Comment by VectorZhao** [comment]
重启丢失上下文
