### ISSUE TITLE
能否做一个用户发消息排队的?

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#825]
类似这样的，因为token下实际上一次只能回复一个问题。多人同时提问是没有意义的，会报错。![Screenshot_20230323_192842.jpg](https://pic.shenbian.tv/2023/03/23/975552820a9f2.jpg)

**Comment by Chanzhaoyu** [comment]
没有计划，这种商业的自己做吧。
