### ISSUE TITLE
key和assets都写了，还是运行不了

### ISSUE THREAD

**Issue by reyim3487297072** [Chanzhaoyu/chatgpt-web#827]
throws：Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable

**Comment by Chanzhaoyu** [comment]
看文档，自己创建一个 .env 文件，复制进去

**Comment by reyim3487297072** [comment]
> 看文档，自己创建一个 .env 文件，复制进去

Cannot GET / 提示这个404，端口我都验证了没有用过，在线等您回复！！！

**Comment by Chanzhaoyu** [comment]
1. 404 你本地是否跑通，如果本地跑通了。
2. 部署的时候是否有暴露端口？
3. 根目录下 `.env` 接口地址为自己的实际地址
4. 不然你就搜索下 issues

**Comment by kolenj** [comment]
> 1. 404 你本地是否跑通，如果本地跑通了。
> 2. 部署的时候是否有暴露端口？
> 3. 根目录下 `.env` 接口地址为自己的实际地址
> 4. 不然你就搜索下 issues

我也有这个问题。。。，大佬，本地已跑通，服务器已开放3002端口，在根目录的.env, 地址已改为http://xxx:3002, ，nginx.conf的server里已配置proxy_pass http://127.0.0.1:3002。上边就是我基本的环境配置，请问是哪里有不对的地方吗

**Comment by reyim3487297072** [comment]
node版本改到16
