### ISSUE TITLE
为了方便大家沟通交流，建了QQ群145225165

### ISSUE THREAD

**Issue by gouguoyin** [Chanzhaoyu/chatgpt-web#83]
为了方便大家沟通交流，同步消息，建了QQ群，群号 145225165。期盼作者大佬能够入群，我可以转让群主身份。
![qrcode_1676966316491](https://user-images.githubusercontent.com/13517412/220283574-e0ec722a-ed65-4dda-b333-3f2a86674e25.jpg)

**Comment by gefeiyanga** [comment]
有wx吗...

**Comment by gouguoyin** [comment]
wx查资料和聊天记录不方便

**Comment by dayunnas** [comment]
作者大佬进去了吗？

**Comment by Chanzhaoyu** [comment]
啊哈～

不是本人建的哈，如有纠纷问题，本人概不负责～

**Comment by gouguoyin** [comment]
> 啊哈～
> 
> 不是本人建的哈，如有纠纷问题，本人概不负责～

大佬，能进群么，我可以把管理员身份转让给你

**Comment by xieccc** [comment]
建议用telegram或者discord吧。

**Comment by xinggonglie** [comment]
> 啊哈～
> 
> 不是本人建的哈，如有纠纷问题，本人概不负责～

想付费使用并做些修改，请问如何联系，1848839936@qq.com
