### ISSUE TITLE
支持此项目的Go后端项目

### ISSUE THREAD

**Issue by liut** [Chanzhaoyu/chatgpt-web#833]
重新开了一个独立的后端项目，使用 Golang 实现 https://github.com/liut/morrigan ，敬请关注

特性：
- 支持 SSE 文本/事件流，标准的哦，当然也包括这个项目service里的 `octet-stream` 那种
- 基于Redis的聊天记录历史
- RESTful API
- 可配置的初始欢迎消息和预设消息集（基于YAML）
- 使用OAuth2客户端登录以一些安全提供商

OpenAI/ChatGPT Backend with conversation and API
 
## Features
 - Support text/event-steam
 - Chat History for Conversation (based on redis)
 - RESTful API
 - Welcome message and preset messages
 - Login with OAuth2 client for general Security Provider

**Comment by Cp0204** [comment]
pr里有人做了，都在造轮子，希望一起造一个轮子

**Comment by liut** [comment]
> pr里有人做了，都在造轮子，希望一起造一个轮子

是吗，没注意呢

**Comment by liut** [comment]
> > pr里有人做了，都在造轮子，希望一起造一个轮子
> 
> 是吗，没注意呢

哦，想起来了，他用的sqlite，我这个用的是redis，计划增加对标准SQL的以及其他接口功能的支持

**Comment by helperAI** [comment]
> > > pr里有人做了，都在造轮子，希望一起造一个轮子
> > 
> > 
> > 是吗，没注意呢
> 
> 哦，想起来了，他用的sqlite，我这个用的是redis，计划增加对标准SQL的以及其他接口功能的支持

支持你

**Comment by yl0124** [comment]
额。我也做了个，用的是mysql
