### ISSUE TITLE
希望支持自动获取 OpenAI access token

### ISSUE THREAD

**Issue by yiios** [Chanzhaoyu/chatgpt-web#84]
可以参考这个项目：https://github.com/rhaym-tech/AIKey

**Comment by tangjiahua** [comment]
正好在思考这方面的东西

**Comment by yiios** [comment]
效率真高，给你点个赞@Chanzhaoyu

**Comment by ludashi2020** [comment]
使用内置邮箱和密码自动获取OpenAI access token，或者前端用户登录自己的openai账号。

**Comment by gygy** [comment]
如果session有更新，自动获取。

**Comment by rico0808** [comment]
@Chanzhaoyu
可以参考这个 https://github.com/acheong08/OpenAIAuth，可以使用 chatgpt 账号获取 access token。

**Comment by kwingart** [comment]
> @Chanzhaoyu 可以参考这个 https://github.com/acheong08/OpenAIAuth 使用 chatgpt 账号获取 access token。

大佬，具体怎么搞，能展开说说么 谢谢
