### ISSUE TITLE
docker 中修改环境变量

### ISSUE THREAD

**Issue by lihailiang3393** [Chanzhaoyu/chatgpt-web#840]
想修改docker 中的api_key，请问在哪里修改呢

**Comment by fzucs** [comment]
不是在docker-compose.yml里吗，最初设置的时候就在这里

**Comment by PaperPlaneDeemo** [comment]
> 不是在docker-compose.yml里吗，最初设置的时候就在这里

如果不是用docker-compose部署的，请问怎么修改？
