### ISSUE TITLE
单IP每小时限制，有些困惑

### ISSUE THREAD

**Issue by oabu** [Chanzhaoyu/chatgpt-web#842]
我用系统，在公网搭建了个公共服务，相当于可以提供给不同的人使用，这个单IP限制的是不同的客户IP的使用吧？
比如我设置的是200/小时
我有4个客户在同时访问
在一个小时内，分别聊了100,250,120,300次
是这四个都被限制了
还是聊了250和300的那个被限制？

另外，被限制后的提示语句，能否自定义？

**Comment by fzucs** [comment]
250和300次的到200就已经被提示了，不过换个设备或者换个节点就能接着用了。
提示语句自定义在service/src/middleware/limiter.ts里改

**Comment by zhuxindong** [comment]
只会限制250次的和300次的，某个客户使用到200次之后就会被限流了，除非他换个ip（比如重新插拔一下路由器/光猫，手机重启一下等操作都会改变ip）
