### ISSUE TITLE
本地启动报错[AbortController is not defined]

### ISSUE THREAD

**Issue by zjtt** [Chanzhaoyu/chatgpt-web#843]

**Comment by Chanzhaoyu** [comment]
检查浏览器兼容性

**Comment by zjtt** [comment]
收到啦，谢谢

**Comment by kolenj** [comment]
> 收到啦，谢谢

你好，我也碰到这个问题，解决了吗

**Comment by kolenj** [comment]
![image](https://user-images.githubusercontent.com/7897278/227495139-4794da28-3e84-4d6b-9eff-32ad69ecf23f.png)
