### ISSUE TITLE
OPENAI_ACCESS_TOKEN用不了吗

### ISSUE THREAD

**Issue by e5sub** [Chanzhaoyu/chatgpt-web#844]
填了OPENAI_ACCESS_TOKEN,用的时候报
undefined
[[OpenAI] 提供错误的API密钥 | Incorrect API key provided]

**Comment by e5sub** [comment]
用的railway部署,只填了ACCESS_TOKEN  没有填API
![1679630804560](https://user-images.githubusercontent.com/46080660/227421962-b9073095-2f91-48cd-85f9-1ad64acd3676.jpg)

**Comment by wzy2023** [comment]
你好，我也遇到了，请问该怎么解决呢
