### ISSUE TITLE
用nginx做代理，建议删除掉proxy_set_header   X-Real-IP

### ISSUE THREAD

**Issue by beingdo** [Chanzhaoyu/chatgpt-web#845]
建议把docker-compose中的 nginx.conf 里这些配置删掉。
如果你是在美国的vps，那你访问从大陆先访问美国 vps，然后美国vps访问 chatgpt。
这些配置是解决后端服务无法获取用户真实 IP，只能获取到代理的 IP的问题，所以要将用户真实 IP 传给后端服务。
但是在我们的应用场景中，正好就是为了让后端（chatgpt）不要知道访问来源地址，只需要知道代理地址（美国）即可。
不知道这是不是有些人被封号的原因。

```
proxy_set_header   X-Real-IP $remote_addr; #转发用户IP
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header REMOTE-HOST $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

**Comment by jorejia** [comment]
这个难道不是传给后端（本项目后端），用做IP请求数限制的么，后端不至于把这个再传给chatgpt吧

**Comment by zhuxindong** [comment]
真正的后端是OpenAI，不是这个项目

**Comment by Fugitive844** [comment]
用openai key的形式，代理的IP是香港可以吗，会不会被封号

**Comment by zhuxindong** [comment]
> 用openai key的形式，代理的IP是香港可以吗，会不会被封号

无可靠信息来源

**Comment by beingdo** [comment]
好的，没问题就好。
我就自己搭建，给自己用，所以想做的彻底点，也不需要限速。

**Comment by Mircc** [comment]
这个话题是 建议去除呢，还是不建议，还是即便加了，其实真实的ip是不会传给openai的对么
