### ISSUE TITLE
是否接入steamship的API

### ISSUE THREAD

**Issue by beiyaohhhc** [Chanzhaoyu/chatgpt-web#846]
目前steamship的API已经可以使用gpt-4 也无需等待 是否考虑接入

**Comment by beiyaohhhc** [comment]
目前貌似没有限制 
相关链接https://zhuanlan.zhihu.com/p/615778573?utm_id=0

**Comment by Chanzhaoyu** [comment]
不考虑这种类型的方式，抱歉
