### ISSUE TITLE
到最后一步报错，提示要安装hook，请问怎么做？

### ISSUE THREAD

**Issue by Simon-Yi** [Chanzhaoyu/chatgpt-web#847]
![微信截图_20230324125933](https://user-images.githubusercontent.com/124592768/227428632-081ca390-f8e8-4069-b1e4-b471dd41ca01.jpg)

**Comment by Chanzhaoyu** [comment]
可以用 `pnpm install` 代替

**Comment by Simon-Yi** [comment]
> 可以用 `pnpm install` 代替

好的，谢谢
