### ISSUE TITLE
项目联网回复

### ISSUE THREAD

**Issue by chengjian922708** [Chanzhaoyu/chatgpt-web#850]
https://github.com/binjie09/chatgpt-web，偶然间发现这个项目竟然可以联网回复。

![image](https://user-images.githubusercontent.com/85025495/227447827-7ce690c9-a8f6-4c94-b29c-6be718b06390.png)

能加入到这里嘛？

**Comment by fzucs** [comment]
确实，之前试了联网回复能获取到最新的信息

**Comment by wuzhijie0101** [comment]
这个功能确实可以

**Comment by zhaoying9105** [comment]
我看了下https://github.com/binjie09/chatgpt-web，没看出来作者有实现这个功能；
确实可用吗？

**Comment by xinyou199** [comment]
我试验了  居然可以用

**Comment by zhxuri** [comment]
棒棒的，强烈建议并入主线。毕竟官方版的chatgpt已经开始这么做了

**Comment by chengjian922708** [comment]
> 这个功能确实可但是
但是我发现这个，虽然使用的是自己的api，但是openai官网却没任何使用记录，看来这个项目应该还是有问题。

**Comment by gooderek** [comment]
这个项目要连作者自己的服务器
