### ISSUE TITLE
请教docker搭建的、网页加密码才能访问的话，需要在哪里加

### ISSUE THREAD

**Issue by danran12** [Chanzhaoyu/chatgpt-web#852]

**Comment by fzucs** [comment]
docker-compose.yml里的 AUTH_SECRET_KEY: xxx

**Comment by jackytj** [comment]
docker run -d --name chatgpt-web -p 3002:3002 -e AUTH_SECRET_KEY=XXX -e OPENAI_API_KEY=sk-XXXXXXXXXXXX chenzhaoyu94/chatgpt-web

**Comment by wangjueszu** [comment]
我通过添加了一个nginx服务器代理，在nginx服务器上设置了密码账户。
