### ISSUE TITLE
打包docker启动后，不能使用

### ISSUE THREAD

**Issue by xuweijie123** [Chanzhaoyu/chatgpt-web#853]
1.本地启动无问题，但是打成镜像访问报这个错误：

```
undefined
[ChatGPT error 404: {
  "error": {
    "message": "Invalid URL (POST /chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
]
```

**Comment by Bisstocuz** [comment]
可能相关：#717 

试试把 `.dockerignore` 文件中的 `.*` 删掉重新打包：
https://github.com/Chanzhaoyu/chatgpt-web/blob/902321026b1112861c19d1b5437b3ba440fb7b9a/.dockerignore#L1-L6

**Comment by xuweijie123** [comment]
因 .dockerignore 文件中的 .*，需要删掉重新打包：
