### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by caipeishen** [Chanzhaoyu/chatgpt-web#854]
1. 配置好key，启动成功
2. 翻墙成功(自测使用python请求openai接口成功)
3. 但还是出现聊天超时
![image](https://user-images.githubusercontent.com/47104943/227455539-f219ee48-794a-48bd-bc24-6aaedb1c892c.png)

**Comment by Monica-lee99** [comment]
> 1. 配置好key，启动成功
> 2. 翻墙成功(自测使用python请求openai接口成功)
> 3. 但还是出现聊天超时
>    ![image](https://user-images.githubusercontent.com/47104943/227455539-f219ee48-794a-48bd-bc24-6aaedb1c892c.png)

你在本地运行的吗

**Comment by caipeishen** [comment]
> > 1. 配置好key，启动成功
> > 2. 翻墙成功(自测使用python请求openai接口成功)
> > 3. 但还是出现聊天超时
> >    ![image](https://user-images.githubusercontent.com/47104943/227455539-f219ee48-794a-48bd-bc24-6aaedb1c892c.png)
> 
> 你在本地运行的吗

是的，本地已经翻墙了，但还是请求超时

**Comment by mm519897405** [comment]
我偶尔也会出这个提示

**Comment by fomalhaut1998** [comment]
我也是，怎么搞

**Comment by 81422972** [comment]
undefined
[ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": null
}
}
]   我也出现了这个原因咋搞

**Comment by 81422972** [comment]
> 我偶尔也会出这个提示

请问你是咋搞的，可以给个联系方式吗

**Comment by chenbo-04** [comment]
请问怎么解决的呀

**Comment by jjustwin** [comment]
我也遇到了，更新镜像即可，docker pull chenzhaoyu94/chatgpt-web
