### ISSUE TITLE
在钉钉内嵌浏览器中一直显示等待转圈

### ISSUE THREAD

**Issue by xinyou199** [Chanzhaoyu/chatgpt-web#857]
前端部署后，在钉钉内置浏览器加载页面一直是等待状态，但是在微信内嵌页和移动端浏览器都正常，这个可能是什么问题？是否是钉钉兼容导致

**Comment by assassinliujie** [comment]
感觉就是钉钉自己有防火墙，反正微信经常会拦截一些网页

**Comment by Timoshao** [comment]
我也遇到这个问题，钉钉手机端打不开，电脑端可以

**Comment by xqm2023** [comment]
手机飞书客户端也有，是手机钉钉和手机飞书客户端内置的浏览器安卓chrome webview内核版本75太低，导致不兼容。
