### ISSUE TITLE
为什么本地可以，外网用域名就不行？

### ISSUE THREAD

**Issue by yuzhuange** [Chanzhaoyu/chatgpt-web#858]
我是通过docker安装的，路由器已经科学了。
通过本地的ip http://192.168.100.1:3002/就可以使用，能回答问题。
用域名+3002可以打开页面，但是无法回答问题。就会显示undefined
[fetch failed]

**Comment by oyps** [comment]
可以 docker logs xxx 看下日志，可能是网络出问题了吧，比如 socks5 代理错误什么的

**Comment by zhuxindong** [comment]
你指的域名是通过ddns访问你内网服务器 or 内网穿透的形式？还请详细说一下你的网络拓扑

**Comment by yuzhuange** [comment]
您好，原因找到了，是因为我吧docker部署在另一台没有梯子的服务器上了，而我在另外一台服务器操作，所以导致这种结果，实际上是可以的。

**Comment by zwgh1725** [comment]
兄弟可以说下群晖nas映射目录么
