### ISSUE TITLE
多用户的功能需求

### ISSUE THREAD

**Issue by changeche01** [Chanzhaoyu/chatgpt-web#859]
很棒的chat UI。感谢
已经做成web ，带到公司同事分享使用。

那么这个需求的话，我想给公司不同的人使用， 怎么做到多个人保存不同的seesion记录？

**Comment by ludashi2020** [comment]
https://chat.openai.yt这个适合你的需求，是官网账号登录，原汁原味

**Comment by jkhcc11** [comment]
> https://chat.openai.yt 这个适合你的需求，是官网账号登录，原汁原味

这个是反代的把？有源码？

**Comment by wangpre** [comment]
> https://chat.openai.yt  这个适合你的需求，是官网账号登录，原汁原味

用这个岂不是账号密码都泄漏了

**Comment by ludashi2020** [comment]
> > https://chat.openai.yt  这个适合你的需求，是官网账号登录，原汁原味
> 
> 用这个岂不是账号密码都泄漏了

原汁原味，没有记录任何用户信息。不放心，可以用小号试试。

**Comment by assassinliujie** [comment]
> 很棒的chat UI。感谢 已经做成web ，带到公司同事分享使用。
> 
> 那么这个需求的话，我想给公司不同的人使用， 怎么做到多个人保存不同的seesion记录？

https://github.com/Kerwin1202/chatgpt-web别人pull的项目，部署这个就行，带数据库和多用户注册登录

**Comment by CraftYouMe** [comment]
> > 很棒的chat UI。感谢 已经做成web ，带到公司同事分享使用。
> > 那么这个需求的话，我想给公司不同的人使用， 怎么做到多个人保存不同的seesion记录？
> 
> [https://github.com/Kerwin1202/chatgpt-web别人pull的项目，部署这个就行，带数据库和多用户注册登录](https://github.com/Kerwin1202/chatgpt-web%E5%88%AB%E4%BA%BApull%E7%9A%84%E9%A1%B9%E7%9B%AE%EF%BC%8C%E9%83%A8%E7%BD%B2%E8%BF%99%E4%B8%AA%E5%B0%B1%E8%A1%8C%EF%BC%8C%E5%B8%A6%E6%95%B0%E6%8D%AE%E5%BA%93%E5%92%8C%E5%A4%9A%E7%94%A8%E6%88%B7%E6%B3%A8%E5%86%8C%E7%99%BB%E5%BD%95)

这个项目使用railway部署，会显示数据库连接错误
