### ISSUE TITLE
希望能添加访问控制

### ISSUE THREAD

**Issue by GH6324** [Chanzhaoyu/chatgpt-web#86]
希望能添加访问权限和鉴权，比如需要账号密码或者输入密码才能进入，不然容易被有些坏人被恶意刷api请求次数，再次感谢大佬的无私奉献（收下我的膝盖

**Comment by Chanzhaoyu** [comment]
感谢建议，可以实现，但是需要排后。

其实我本来是打算做个引子然后大家可以在这个基础上各自用自己的后端语言开发，不过现在好像都默认使用 `docker` 部署了。

**Comment by gouguoyin** [comment]
> 

建议新建个分支弄鉴权和权限控制，主版本还保持现有，方便各自用自己的后端语言做鉴权和权限控制
