### ISSUE TITLE
能否添加重试功能

### ISSUE THREAD

**Issue by chiyububaci** [Chanzhaoyu/chatgpt-web#862]
当ChatGPT因为各种各样的原因抽风了, 在回答到一半停下来的时候, 通常此时再次提问, 会丢失前面对话的上下文, 有的时候会带来不便利, 能否新增一个重试功能, 作用是让ChatGPT把刚才没说完的话继续说完, 十分感谢!

**Comment by renwofei423** [comment]
有啊，仔细观察一下，对话的右边有个小圆圈。。。

**Comment by chiyububaci** [comment]
@renwofei423 这个小圆圈在实际使用中的表现是让ChatGPT重新回答一次最后的问题, 而不是接着没说完的话继续说, 我之前在别的类似的ChatGPT应用里面体验过大概的功能, 他们的交互逻辑大概就是, 如果ChatGPT的回答中断了, 只需要发一个空消息过去, ChatGPT就会接着上次还没讲完的回答继续讲

**Comment by renwofei423** [comment]
你输入 “继续”试试？
