### ISSUE TITLE
公网访问，WIFI很慢，移动数据正常

### ISSUE THREAD

**Issue by huanle19891345** [Chanzhaoyu/chatgpt-web#864]
请教大佬，railway发布之后，公网访问，WIFI很慢但移动数据请求正常，WIFI经常慢到加载超时失败，和移动数据网络下速度差很多，这是为什么

非常感谢~

**Comment by zhuxindong** [comment]
不同的运营商线路到你服务器的速度会有很大差异，属于正常现象

**Comment by renwofei423** [comment]
有一个index文件，大约900k，railway下载慢的时候可能有30-40k，显然下载会很久。

不知道能不能优化拆分一下

**Comment by huanle19891345** [comment]
> 不同的运营商线路到你服务器的速度会有很大差异，属于正常现象

嗯嗯，目前看到三个不同地区的客户端WIFI访问都慢到超时，移动数据都正常，所以在想是不是大家都会遇到这个问题，railway上也是正常部署的

**Comment by huanle19891345** [comment]
> 有一个index文件，大约900k，railway下载慢的时候可能有30-40k，显然下载会很久。
> 
> 不知道能不能优化拆分一下

嗯嗯，看到其他同学说有个index文件1.5M，说是建议放cdn加速，要研究一下这块

**Comment by MrStub** [comment]
各位大佬，请问railway部署完并且生成好域名以后怎么访问啊，我打开生成后的域名，显示Not Found
![image](https://user-images.githubusercontent.com/37787783/227738211-d0a32bd2-4006-43a3-a978-1972b8e93e91.png)

**Comment by huanle19891345** [comment]
> 各位大佬，请问railway部署完并且生成好域名以后怎么访问啊，我打开生成后的域名，显示Not Found ![image](https://user-images.githubusercontent.com/37787783/227738211-d0a32bd2-4006-43a3-a978-1972b8e93e91.png)

railway上环境变量要配置对，PORT参数配置成3002之外的，会报这个错，其他照着ReadMe做就行了

**Comment by MrStub** [comment]
@huanle19891345 解决了，感谢老板

**Comment by AlexWeiCD** [comment]
![image](https://user-images.githubusercontent.com/1231095/232732196-ed5f99ab-433f-4a20-b3ca-10901e7eb8f7.png)
WEB第一次加载要23.02秒，微信打开更慢。
assets/index-6bf8e377.js文件有1.5M，这文件特别慢，怎么解决？
