### ISSUE TITLE
有没有大佬教一下这个怎么用啊

### ISSUE THREAD

**Issue by 1205129045x** [Chanzhaoyu/chatgpt-web#865]
用的api是不是基于3的，感觉没官网网页版的聪明

**Comment by Simon-Yi** [comment]
你如果用的是API的Key就是3.5模型

**Comment by 1205129045x** [comment]
> 你如果用的是API的Key就是3.5模型
> 
> 你如果用Token的话，就是基于GPT3

那是token比用api聪明？

**Comment by IT-NuanxinPro** [comment]
本地网络怎么访问chartgpt官网接口，怎么做代理访问

**Comment by 1205129045x** [comment]
> 本地网络怎么访问chartgpt官网接口，怎么做代理访问

需要翻墙的，我目前只是简单的本地网页运行而已，因为用官网的网页聊天，过几分钟不聊天再发信息就给我提示`Something went wrong. If this issue persists please contact us through our help center at help.openai.com.`
