### ISSUE TITLE
请教下关于持续性对话的字数限制

### ISSUE THREAD

**Issue by suwubee** [Chanzhaoyu/chatgpt-web#866]
这个代码确实很强大，但是关于chat可持续对话的parentMessageId部分不是很看得懂。
因为openai的api部分的可持续对话模式是需要将之前所有的聊天记录一起提交给api的，这就导致很快就占满了4k的容量。
请问下这个程序也是一样的逻辑吗？还是有特殊的处理方式来做可持续的对话。
谢谢！

**Comment by Chanzhaoyu** [comment]
同样会丢掉前方的内容

**Comment by yi-ge** [comment]
gpt4提供了更大的容量，也更贵。
