### ISSUE TITLE
如何选择GPT4 模型

### ISSUE THREAD

**Issue by weifeng12x** [Chanzhaoyu/chatgpt-web#869]
我尝试了gpt-4 或者gp4都不行
环境变量里面也只写了这个
OPENAI_API_MODEL 设置模型，可选，默认：gpt-3.5-turbo

**Comment by leter** [comment]
同问

**Comment by weifeng12x** [comment]
我搜了以下英文网站，这个提示是非常的有误导性的
"message": "The model: gpt-4 does not exist",
真正的原因是因为你没有权限访问gpt4的api，需要申请才可以
