### ISSUE TITLE
accesstoken回复很慢，都快1-2分钟，看看是否有优化的点

### ISSUE THREAD

**Issue by gygy** [Chanzhaoyu/chatgpt-web#87]

**Comment by Chanzhaoyu** [comment]
使用 `accesstoken` 回复是会慢，会再优化

**Comment by Siri-Li** [comment]
我开了会员，用accesstoken，自己搭建得到的答案跟chat.openai.com里面显示出的居然不一样。

**Comment by tangjiahua** [comment]
> chat.openai.com

这个项目和web chatgpt不一样的，web chatgpt没有api，这个项目是用的老的模型。

**Comment by nothinggift** [comment]
> 我开了PLUS会员，用accesstoken，自己搭建得到的答案跟chat.openai.com里面显示出的居然不一样，最后面一条没有提交成功

chatgpt同一个问题的回答并不是固定的，经常内容是一样的，表达方式会不同

想请问下PLUS会员用accesstoken还有没有速率限制，是否稳定

**Comment by Siri-Li** [comment]
> 

目前看起来还可以，有优先访问

**Comment by Chanzhaoyu** [comment]
> 目前看起来还可以，有优先访问

是 2.7.0 主分支还是 stream 呢

**Comment by gygy** [comment]
main还是很慢。官方网页端 早已返回回复了。但2.7main还是在等待，最后返回超时之类。

**Comment by gygy** [comment]
2.7main  seesion是不是有异常？一直不成功。都是很久没反应。最后超时。

api方式是正常的。

**Comment by gygy** [comment]
> > > 目前看起来还可以，有优先访问
> > 
> > 是 2.7.0 主分支还是 stream 呢
> 
> main还是很慢。官方网页端 早已返回回复了。但2.7main还是在等待，最后返回超时之类。

stream也是这样，反复多次尝试。

**Comment by gygy** [comment]
添加了回答流的版本，不管是main还是stream，都是有问题的。 切换回昨天更新流前的版本才正常。  @Chanzhaoyu

**Comment by Chanzhaoyu** [comment]
> 添加了回答流的版本，不管是main还是stream，都是有问题的。 切换回昨天更新流前的版本才正常。 @Chanzhaoyu

已回退

**Comment by Chanzhaoyu** [comment]
`2.8.0` 已优化过
