### ISSUE TITLE
有没有谁造了Java版后端的轮子

### ISSUE THREAD

**Issue by wangpre** [Chanzhaoyu/chatgpt-web#873]
有没有谁用这个UI造了Java版后端的轮子

**Comment by lixingxing001** [comment]
不建议使用java来构造。作者主打轻量，快速。java太重了

**Comment by wangpre** [comment]
商业化的话用node还是不行，Java是主流在 2023年3月25日，10:19，Sun丶 ***@***.***> 写道：﻿
不建议使用java来构造。作者主打轻量，快速。java太重了

**Comment by fzucs** [comment]
作者本意就不是做成商业化，建议自己来

**Comment by hncboy** [comment]
#836

**Comment by hncboy** [comment]
> 有没有谁用这个UI造了Java版后端的轮子

#836 Java 后端
