### ISSUE TITLE
多个用户并发访问报429 Only one message at atime

### ISSUE THREAD

**Issue by li-sen** [Chanzhaoyu/chatgpt-web#876]
![image](https://user-images.githubusercontent.com/33471335/227696523-e0899f9d-eb99-406f-9e52-b7d9220d4bcf.png)

**Comment by hncboy** [comment]
使用 AccessToken 模式时官方接口返回的，每次只允许回复一条消息

**Comment by Chanzhaoyu** [comment]
也许你可以使用 API 的方式来解除同时多个用户访问。

**Comment by li-sen** [comment]
ChatGPTError: ChatGPT error 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

    at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 429,
  statusText: 'Too Many Requests',
  [cause]: Response {
    size: 0,
    [Symbol(Body internals)]: {
      body: [PassThrough],
      stream: [PassThrough],
      boundary: null,
      disturbed: true,
      error: null
    },
    [Symbol(Response internals)]: {
      type: 'default',
      url: 'https://api.openai.com/v1/chat/completions',
      status: 429,
      statusText: 'Too Many Requests',
      headers: [Object],
      counter: 0,
      highWaterMark: 16384

**Comment by li-sen** [comment]
ChatGPTError: ChatGPT error 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

    at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 429,
  statusText: 'Too Many Requests',
  [cause]: Response {
    size: 0,
    [Symbol(Body internals)]: {
      body: [PassThrough],
      stream: [PassThrough],
      boundary: null,
      disturbed: true,
      error: null
    },
    [Symbol(Response internals)]: {
      type: 'default',
      url: 'https://api.openai.com/v1/chat/completions',
      status: 429,
      statusText: 'Too Many Requests',
      headers: [Object],
      counter: 0,
      highWaterMark: 16384

**Comment by hncboy** [comment]
> ChatGPTError: ChatGPT error 429: { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }
> 
> ```
> at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:55:19)
> at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
> ```
> 
> statusCode: 429, statusText: 'Too Many Requests', [cause]: Response { size: 0, [Symbol(Body internals)]: { body: [PassThrough], stream: [PassThrough], boundary: null, disturbed: true, error: null }, [Symbol(Response internals)]: { type: 'default', url: 'https://api.openai.com/v1/chat/completions', status: 429, statusText: 'Too Many Requests', headers: [Object], counter: 0, highWaterMark: 16384

报了这个错：You exceeded your current quota, please check your plan and billing details.。是不是额度被用完了

**Comment by li-sen** [comment]
我是plus用户，额度也需要充值？哪里看额度？

**Comment by hncboy** [comment]
> 我是plus用户，额度也需要充值？哪里看额度？

如果用的 ApiKey 模式，那么和是否是 plus 无关。前端页面上有 ApiKey 额度展示。官网这个地址 https://platform.openai.com/account/usage

**Comment by li-sen** [comment]
嗯开启扣费就行，但上下文语义理解貌似有问题。
![image](https://user-images.githubusercontent.com/33471335/228103513-8499218d-6824-4586-8e43-4f141fd5b43d.png)
显示的字数有限制？
