### ISSUE TITLE
MAX_REQUEST_PER_HOUR 这个变量是用来限制每个 IP 的请求次数吗？

### ISSUE THREAD

**Issue by Root-FTW** [Chanzhaoyu/chatgpt-web#879]
MAX_REQUEST_PER_HOUR 这个变量是用来限制每个 IP 的请求次数吗？

例如，如果我部署了您的项目并将其分享给我的朋友（5个人），如果我将每小时的请求限制设置为1,000次，那么每个 IP 地址会有1,000次请求限制吗？还是所有 IP 地址总共只能有1,000次请求限制？

**Comment by Chanzhaoyu** [comment]
Single user

**Comment by echeverra** [comment]
> MAX_REQUEST_PER_HOUR 这个变量是用来限制每个 IP 的请求次数吗？
> 
> 例如，如果我部署了您的项目并将其分享给我的朋友（5个人），如果我将每小时的请求限制设置为1,000次，那么每个 IP 地址会有1,000次请求限制吗？还是所有 IP 地址总共只能有1,000次请求限制？

请问是在evn文件加入MAX_REQUEST_PER_HOUR字段，在docker run命令加入MAX_REQUEST_PER_HOUR参数这样设置么
