### ISSUE TITLE
为啥不可以发送图片啦

### ISSUE THREAD

**Issue by luckywangxi** [Chanzhaoyu/chatgpt-web#882]

**Comment by Chanzhaoyu** [comment]
一直都可以吧，没有改过代码诶，或许你可以设定一下它的角色。

**Comment by cd547** [comment]
确实有时候这个ai就是不出图哎，同样的问题是好是坏，也许他有脾气，哈哈。经常只给了个markdown的url链接。我是在作者的代码里做了正则判断凡是会话里满足图片格式的url都让他在这次谈话的下面显示这个图片

**Comment by assassinliujie** [comment]
可以发送，发的是图床链接，自己本地挂个代理不然看不到图
