### ISSUE TITLE
各位大佬们，我发现gpt的回答比较简短，应该是限制了回复的最大字节数，这个在哪里可以改大一点？

### ISSUE THREAD

**Issue by xiaosaaaa** [Chanzhaoyu/chatgpt-web#886]

**Comment by Moximxxx** [comment]
README 里 常见问题最后一项 可以返回完整的回答

**Comment by xiaosaaaa** [comment]
谢谢谢谢

**Comment by shansing** [comment]
可能也跟默认的 systemMessage 有关系。默认的 systemMessage 大概是这样的：

```
You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.
Knowledge cutoff: 2021-09-01
Current date: 2023-03-26
```

印象中是跟官方看齐的。但里面有一句 `Answer as concisely as possible.` 可能限制了它的回答。你也许可以强行修改让它尽可能“详细”而非“简洁”地回答问题。不过受限于模型本身，效果可能不会太好。也会产生之前的“图灵斑图”这种回答质量低的问题。
