### ISSUE TITLE
如何限制会话消息的数量

### ISSUE THREAD

**Issue by weifeng12x** [Chanzhaoyu/chatgpt-web#887]
## 问题
在不清理聊天记录的情况下会把所有的上下文消息提交过去直到达到单会话token的上限，在我发现这个机制前随便发一个简单的问题会导致1000多的token消耗
![image](https://user-images.githubusercontent.com/76556787/227719280-95b1abe7-8391-4ba7-8efd-50fadb487ba7.png)

## 期望
我知道可以清理聊天记录，或者不关联上下文。但是我分享给朋友们体验，他们并不知道这个步骤，或者不会去设置。
所以我希望能有个配置节点能限制关联上下文的数量。

**Comment by weifeng12x** [comment]
![image](https://user-images.githubusercontent.com/76556787/227719446-0d7bbe1c-2df4-41dd-b4c8-f59b677c375c.png)
这一个请求直接3k tokens了，如果用了GPT 4直接破产了 555555555 @Chanzhaoyu

**Comment by xiaosaaaa** [comment]
聊天框左边的有个绿色的类似钟表的小图标，关了就不会携带之前的聊天记录了

**Comment by weifeng12x** [comment]
> 聊天框左边的有个绿色的类似钟表的小图标，关了就不会携带之前的聊天记录了

你看我的描述，我知道有个地方可以设置。大多数时候我还是想关联上下文的，但是我只需要3-4条上下文就行了。token的消耗量可以控制在一两百，但是现在token一条消息近3K。

我发现这个事情是因为我用了别人做的客户端，里面就有设置上下文的数量，然后我去查日志才发现这个问题。

**Comment by renwofei423** [comment]
感觉确实有点必要，或者从前端控制？

**Comment by renwofei423** [comment]
刚刚查了一下，一次请求上万。。。。

04:35
Local time: 2023年3月22日 12:35
gpt-3.5-turbo-0301, 5 requests
11,067 prompt + 4,052 completion = 15,119 tokens

**Comment by weifeng12x** [comment]
> 刚刚查了一下，一次请求上万。。。。
> 
> 
> 
> 04:35
> 
> Local time: 2023年3月22日 12:35
> 
> gpt-3.5-turbo-0301, 5 requests
> 
> 11,067 prompt + 4,052 completion = 15,119 tokens
> 
> 
> 
> 
> 
> 

这是五个请求，平均下来也3k了。应该到了3.5最大tokens的限制了 如果换成4.0 一次6，7毛😂

**Comment by zhangweizi** [comment]
不会Nodejs，研究了半天，发现是引用chatgpt-api导致了，只要带了parentMessageID,就会把所有内容全部提交过去，chatgpt-api把消息是默认保存在服务器内存里的。想要限制只提交几个，可以修改chatgpt-api的源码，再编译。 可惜我不会。我用了一个比较恶心办法实现了，我直接改了/service/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js的代码，在一个do while循环里，把循环次数改了就可以了。 想提交三条就 循环3次。祝你成功！

**Comment by weifeng12x** [comment]
> 

谢谢你的详细教程,我已经几年没有写代码了. 看大佬什么时候有空修复吧,我懒得折腾了. 主要搭起来给朋友玩玩的,给他们开的3.5 反正也用不了多少钱.
