### ISSUE TITLE
如何安装证书？

### ISSUE THREAD

**Issue by SiMPlerMeta** [Chanzhaoyu/chatgpt-web#888]
请问怎么安装证书，使用https协议访问

**Comment by assassinliujie** [comment]
用nginx

**Comment by ycvk** [comment]
最简单的，docker安装acme-companion镜像，配置好变量就行

**Comment by Cp0204** [comment]
参考 https://github.com/Chanzhaoyu/chatgpt-web/pull/658#issuecomment-1480689428

**Comment by SiMPlerMeta** [comment]
按照#658的配置试了下，不行，nginx安装证书后，前台访问可以开启https，但是访问的是项目根目录下的index.html，这个界面打开后，只有一个简单的动画，没有打开会话窗口，项目用ip+端口的方式访问时，可以访问client 接口，但是用nginx反向代理到1002端口，就访问不了vite client接口了

**Comment by assassinliujie** [comment]
> 按照#658的配置试了下，不行，nginx安装证书后，前台访问可以开启https，但是访问的是项目根目录下的index.html，这个界面打开后，只有一个简单的动画，没有打开会话窗口，项目用ip+端口的方式访问时，可以访问client 接口，但是用nginx反向代理到1002端口，就访问不了vite client接口了

load_module /usr/lib/nginx/modules/ngx_stream_module.so;
worker_processes auto;
events {
    worker_connections  1024;
    accept_mutex on;
  }
http {
  include mime.types;
  default_type application/octet-stream;
  server {
    server_name yourserverdomin.com;#换成自己域名
    listen 443 ssl http2;
    proxy_buffering off;
    ssl_certificate /path/yourcert.pem;#换成自己的证书位置
    ssl_certificate_key /path/yourcert.key;#换成自己的证书位置
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    listen 80;
    if ($scheme = http) {
      return 301 https://$host:443$request_uri;
    }
    location / {
      proxy_pass http://127.0.0.1:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_redirect http:// https://;
    }
  }
}

**Comment by assassinliujie** [comment]
> 按照#658的配置试了下，不行，nginx安装证书后，前台访问可以开启https，但是访问的是项目根目录下的index.html，这个界面打开后，只有一个简单的动画，没有打开会话窗口，项目用ip+端口的方式访问时，可以访问client 接口，但是用nginx反向代理到1002端口，就访问不了vite client接口了

不需要动nginx里面的文件，配置下反代就好了，该配哪个端口就哪个端口

**Comment by z1073** [comment]
> 最简单的，docker安装acme-companion镜像，配置好变量就行

大哥你这个真棒，又学到新东西了 哈哈，还有好玩的介绍下吗

**Comment by SiMPlerMeta** [comment]
> 

又重新配置了下nginx，client请求成功了，但是界面还是没打开对话窗口，一直停留在加载动画的界面，然后看见console里面提示wss连接失败，使用域名的话，wss需要配置什么吗。目前使用IP+端口是没问题的

**Comment by z1073** [comment]
> > 
> 
> 又重新配置了下nginx，client请求成功了，但是界面还是没打开对话窗口，一直停留在加载动画的界面，然后看见console里面提示wss连接失败，使用域名的话，wss需要配置什么吗。目前使用IP+端口是没问题的

兄弟试试三楼大哥说的nginx-proxy镜像和acme-companion镜像组合

**Comment by SiMPlerMeta** [comment]
好的，我试试，这两个镜像直接pull下来就行了吧，还有其他额外的配置吗

**Comment by z1073** [comment]
> 好的，我试试，这两个镜像直接pull下来就行了吧，还有其他额外的配置吗

我也在学习 哈哈，但看了下介绍挺简单的

**Comment by ycvk** [comment]
> 好的，我试试，这两个镜像直接pull下来就行了吧，还有其他额外的配置吗

如果没装nginx，可以先安装nginx镜像

`docker run --detach \
    --name nginx-proxy \
    --publish 80:80 \
    --publish 443:443 \
    --volume /data/nginx/certs:/etc/nginx/certs \
    --volume /data/nginx/vhost:/etc/nginx/vhost.d \
    --volume /data/nginx/html:/usr/share/nginx/html \
    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
    nginxproxy/nginx-proxy`

安装完成后安装acme镜像来自动安装证书
`docker run --detach \
    --name nginx-proxy-acme \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --volume acme:/etc/acme.sh \
    --env "DEFAULT_EMAIL=你自己的邮箱" \
    nginxproxy/acme-companion`

然后安装你的ChatGPT项目
`docker run --detach \
   --name chatgpt-web \
   --env "VIRTUAL_HOST=你的域名，指已经dns解析到此服务器的域名" \
   --env OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxx \
   --env "VIRTUAL_PORT=3002" \
   --env AUTH_SECRET_KEY=这项目设置的访问密码 \
   --env "LETSENCRYPT_HOST=你的域名，指已经dns解析到此服务器的域名" \
   chenzhaoyu94/chatgpt-web`

然后等待证书安好就行，很快就能通过域名访问你的网站了，上面就是简单做个例子，详细的参数可以自己加或者改

**Comment by SiMPlerMeta** [comment]
今天搞了一天终于成功了，接上一个问题，配置好nginx反向代理之后，console里面报wss连接失败，目前直接用前端部署的方式不成功，于是改用docker部署，使用了nginx-proxy-manager（感谢3F大佬的指点），使用这个是因为manager有一个前端的配置界面（可以使用ip+端口的方式访问），比起在文件中修改要简单很多，另外在manager里面可以直接用Let's Encrypt 申请证书，还能自动续期。在manager里面，配置反向代理时，直接勾选 websockets support ，配置好之后，就可以用https访问了，浏览器也不会弹不安全的提示，写到这里，希望能给后面的兄弟一点帮助！

**Comment by tsy19900929** [comment]
> > 
> 
> 又重新配置了下nginx，client请求成功了，但是界面还是没打开对话窗口，一直停留在加载动画的界面，然后看见console里面提示wss连接失败，使用域名的话，wss需要配置什么吗。目前使用IP+端口是没问题的

https://github.com/Chanzhaoyu/chatgpt-web/issues/147#issuecomment-1486534201

**Comment by HOMHOG** [comment]
> 用nginx

nginx反代 路径为/可以成功，设置其他路径就一直loading，有两个js文件404,怎么才能设置路径
