### ISSUE TITLE
单ip每小时限制功能或许存在bug

### ISSUE THREAD

**Issue by baoqihui** [Chanzhaoyu/chatgpt-web#893]
场景描述。
两个相同服务部署在相同服务器，都限制10次每小时。

1服务只使用http端口访问:流量可用10次，wifi可再10次，开启代理也可10次。测试结果预期，正常

但2服务使用nginx配置https。出现情况，开启10次，实际访问6-8次就限制了，而且所有用户均无法访问，全部显示ip访问频繁。

两组源码版本，内容完全一致。除docker映射端口不同外。一个使用了nginx配置了证书及打字机效果。另一个直接裸端口号访问

**Comment by JinhuW** [comment]
我也遇到同样的问题 似乎限制的所有用户 而不是单个ip 用户

**Comment by baoqihui** [comment]
> 我也遇到同样的问题 似乎限制的所有用户 而不是单个ip 用户

这应该不是预期的结果，但同样镜像的裸端口号访问测试很正常。只是对于ip做限制

**Comment by baoqihui** [comment]
找到原因：因为采用了反向代理，所有用户ip被代理转发。变成一个ip。
解决方案：rateLimit 中添加 ：trustProxy: true //获取真实ip
望采纳

**Comment by zhuxindong** [comment]
这个代码已经合入主分支了https://github.com/Chanzhaoyu/chatgpt-web/pull/863 除此之外，建议NGINX反代配置中透传ip:
`proxy_set_header X-Real-IP $remote_addr; 
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
