### ISSUE TITLE
可以把这个接口集成进去嘛？我试了下很快

### ISSUE THREAD

**Issue by xiexuliunian** [Chanzhaoyu/chatgpt-web#90]
https://github.com/acheong08/ChatGPT

**Comment by Chanzhaoyu** [comment]
这个项目是基于 `python` 的，速度是很快，不过核心反代怎么实现的他没有透露

**Comment by xiexuliunian** [comment]
哦哦哦，这样呀，看来我只能包一层flask，写个丑陋的前端玩了。

**Comment by tangjiahua** [comment]
这个是不是web chatgpt的？咱们这个是基于非web chatgpt的openai api版本
