### ISSUE TITLE
当回答字数超限时，回复“继续”并不能输出之后的内容，且会丢失上文

### ISSUE THREAD

**Issue by Pollo3470** [Chanzhaoyu/chatgpt-web#902]
已开启上下文功能并测试正常，只有在回答字数超限时会出现丢失上文的情况。也就是说“继续”这个功能失效
![image](https://user-images.githubusercontent.com/90445326/227776729-1356431e-d922-4f49-85a3-fdc58610e50d.png)

**Comment by yi-ge** [comment]
可以选择开启长回复。或者检查是否开启关联上下文功能，在输入框左侧图标。

**Comment by Pollo3470** [comment]
> 可以选择开启长回复。或者检查是否开启关联上下文功能，在输入框左侧图标。

已开启上下文功能，只有在回答超过字数时才失效
请问docker版如何开启长回复功能？

**Comment by yi-ge** [comment]
程序开启还需要UI也开启，docker版本先参考.env开启后，编译前端，然后自行build镜像。

**Comment by jlguochn** [comment]
请问解决了吗，我开启了长回复和上下文功能还是存在这个问题。

**Comment by Root-FTW** [comment]
我有完全相同的问题，我已经启用了长回答选项。

![image](https://user-images.githubusercontent.com/108767514/227808809-2a141e2b-8e41-4d1a-9d6d-557f90dc5e5e.png)

**Comment by orwithout** [comment]
我也遇到同样的问题：

**Comment by orwithout** [comment]
版本：2.10.8

**Comment by orwithout** [comment]
版本：2.10.8
我也遇到同样的问题：【当回答字数超限时，回复“继续”并不能输出之后的内容，且会丢失上文】
开启VITE_GLOB_OPEN_LONG_REPLY   问题仍然存在吗？
（VITE_GLOB_OPEN_LONG_REPLY 选项相关配置是在哪个文件里？）

> 我有完全相同的问题，我已经启用了长回答选项。
> 
> ![image](https://user-images.githubusercontent.com/108767514/227808809-2a141e2b-8e41-4d1a-9d6d-557f90dc5e5e.png)

**Comment by yi-ge** [comment]
启用VITE_GLOB_OPEN_LONG_REPLY后需要自行编译。

**Comment by li-sen** [comment]
有提供相关的镜像吗？自行编译比较麻烦
