### ISSUE TITLE
长回复功能失效。

### ISSUE THREAD

**Issue by jlguochn** [Chanzhaoyu/chatgpt-web#912]
index.vue中，长回复判断表达式失效。
“data.detail.choices[0].finish_reason === 'length'”，该表达式失效。
在运行中若因为字数限制中断对话，finish_reason的值为null而非length，故无法触发长回复的判断语句，导致上下文丢失。

**Comment by Root-FTW** [comment]
> index.vue中，长回复判断表达式失效。
> “data.detail.choices[0].finish_reason === 'length'”，该表达式失效。
> 在运行中若因为字数限制中断对话，finish_reason的值为null而非length，故无法触发长回复的判断语句，导致上下文丢失。

这是一个惊人的发现，我注意到在使用这个项目时总是会失去上下文，但从未知道原因。

能修复吗？

**Comment by yi-ge** [comment]
@jlguochn 为null说明数据就没有传输完成，自然无法触发长回复。

**Comment by choury** [comment]
上下文关联这里bug比较多，只要点重试，到第三次，上下文就丢失了

**Comment by jlguochn** [comment]
@yi-ge 我也不清楚为何收到null，对话正常结束时收到的finish_reason === 'stop'，超出文字长度限制中断时收到的是null，没有像预期的那样收到 'length'。我在OPENAI_API_KEY模式时遇到这个问题，当我切换成OPENAI_ACCESS_TOKEN模式时，长回复功能正常使用。

**Comment by jlguochn** [comment]
> @jlguochn 为null说明数据就没有传输完成，自然无法触发长回复。

我也不清楚为何收到null，对话正常结束时收到的finish_reason === 'stop'，超出文字长度限制中断时收到的是null，没有像预期的那样收到 'length'。我在OPENAI_API_KEY模式时遇到这个问题，当我切换成OPENAI_ACCESS_TOKEN模式时，长回复功能正常使用。

**Comment by jlguochn** [comment]
> @jlguochn 为null说明数据就没有传输完成，自然无法触发长回复。

@yi-ge 我也不清楚为何收到null，对话正常结束时收到的finish_reason === 'stop'，超出文字长度限制中断时收到的是null，没有像预期的那样收到 'length'。我在OPENAI_API_KEY模式时遇到这个问题，当我切换成OPENAI_ACCESS_TOKEN模式时，长回复功能正常使用。

**Comment by yi-ge** [comment]
@jlguochn 如果和服务器的连接中断了，就可能收不到length，可以肯定的是，官方API回复的是有'length‘的

**Comment by jlguochn** [comment]
@Root-FTW 解决了这个问题，是因为网络不稳定，把环境变量TIMEOUT_MS调高就好了。

**Comment by Root-FTW** [comment]
> @Root-FTW 解决了这个问题，是因为网络不稳定，把环境变量TIMEOUT_MS调高就好了。

将变量提高到多高是明智之举？

你给该变量分配了什么值？
