### ISSUE TITLE
文件占用怎么这么大

### ISSUE THREAD

**Issue by 1205129045x** [Chanzhaoyu/chatgpt-web#913]
今天看了下项目的文件夹大小，发现有400多MB，怎么会这么大，有没有大佬知道
![image](https://user-images.githubusercontent.com/50540240/227820011-fd6e5c07-118e-454f-8522-c9632c74f0f0.png)

**Comment by hncboy** [comment]
node_modules 包大

**Comment by Nriver** [comment]
正常，应该说有两份node_modules才这么点大

**Comment by Chanzhaoyu** [comment]
大部份是依赖文件，`node_modules` 文件夹不需要管。
