### ISSUE TITLE
传输内容传输传输着就断开了必须发继续 能不能做到自动继续啊

### ISSUE THREAD

**Issue by feiyu201** [Chanzhaoyu/chatgpt-web#916]
哪位大神出一个宝塔创建教程
还有我发现一个问题 就是传输内容传输传输着就断开了必须发继续 能不能做到自动继续啊,否则界面太难看了 代码断层不方便复制

**Comment by misszhangzhihui** [comment]
https://www.iculture.cc/knowledge/pig=32445 你试下这个。

**Comment by feiyu201** [comment]
@misszhangzhihui 宝塔这个会 其他不知道怎么解决 很难受 哎

**Comment by misszhangzhihui** [comment]
输出会断正常，chat.openai.com也会断。
