### ISSUE TITLE
快速按下删除会话确认按钮导致删除多个会话

### ISSUE THREAD

**Issue by kiritosan** [Chanzhaoyu/chatgpt-web#917]
## 问题描述

删除会话的时候，短时间内高频按下confirm按钮会导致除当前会话外的其他会话的删除

![image](https://user-images.githubusercontent.com/4273631/227835891-a2c11a62-010d-4c5a-b030-fcc98ae9f7b8.png)

**Comment by Chanzhaoyu** [comment]
已修复
