### ISSUE TITLE
这个思考等待的按钮可以改成官网哪种吗？

### ISSUE THREAD

**Issue by ludashi2020** [Chanzhaoyu/chatgpt-web#92]
![smrEs.png](https://pic.shenbian.tv/2023/02/22/04d80ac15b2b5.png)

**Comment by Chanzhaoyu** [comment]
需要更详细的信息

**Comment by Siri-Li** [comment]
如果返回得太慢，可以给一些提示词，比如ai正在思考中，请耐心等待

**Comment by Chanzhaoyu** [comment]
> 如果返回得太慢，可以给一些提示词，比如ai正在思考中，请耐心等待

刚刚发布的 `2.7.0` 应该不会出现这种情况

**Comment by lzxlin** [comment]
能否改成官网那种模拟打字机的形式实时输出呢，而不是返回所有结果再输出

**Comment by Chanzhaoyu** [comment]
> 能否改成官网那种模拟打字机的形式实时输出呢，而不是返回所有结果再输出

这个使用 `accessToken` 时仍有解析问题没解决
