### ISSUE TITLE
让其写代码时，代码过长，请求继续时，返回的下一段代码没有被正确格式化

### ISSUE THREAD

**Issue by lvyi21** [Chanzhaoyu/chatgpt-web#921]
让GPT给写一个门户网站首页，返回的代码过长，让它继续后，在下一段返回的代码没有被正确格式化

**Comment by assassinliujie** [comment]
async function chatReplyProcess(options: RequestOptions) {
  const { message, lastContext, process, systemMessage } = options
  try {
    const timeoutMs = (await getCacheConfig()).timeoutMs
    let options: SendMessageOptions = { timeoutMs }

    if (apiModel === 'ChatGPTAPI') {
      if (isNotEmptyString(systemMessage))
        options.systemMessage = systemMessage
    }

    if (lastContext != null) {
      if (apiModel === 'ChatGPTAPI')
        options.parentMessageId = lastContext.parentMessageId
      else
        options = { ...lastContext }
    }

    const response = await api.sendMessage(message, {
      ...options,
      onProgress: (partialResponse) => {
        process?.(partialResponse)
      },
    })

    return sendResponse({ type: 'Success', data: response })
  }
  catch (error: any) {
    const code = error.statusCode
    global.console.log(error)
    if (Reflect.has(ErrorCodeMessage, code))
      return sendResponse({ type: 'Fail', message: ErrorCodeMessage[code] })
    return sendResponse({ type: 'Fail', message: error.message ?? 'Please check the back-end console' })
  }
}

后端的这一段代码应该是没有处理过，直接每个openai的回复都作为快照发给用户了，对于AWS EC2来说流量还是很宝贵的，能麻烦加个map修改一下嘛

**Comment by assassinliujie** [comment]
// 在文件开头声明 Map 变量
const contextMap: Map<string, ChatContext | ChatMessage> = new Map()

// 修改 chatReplyProcess 函数，将上下文作为参数传递
async function chatReplyProcess(options: RequestOptions, context?: ChatContext | ChatMessage) {
  const { message, process, systemMessage } = options
  const lastContext = context ?? contextMap.get(message.user_id)
  try {
    // ... 在这里省略原始代码的其余部分 ...
    if (lastContext != null) {
      if (apiModel === 'ChatGPTAPI')
        options.parentMessageId = lastContext.parentMessageId
      else
        options = { ...lastContext }
    }

    const response = await api.sendMessage(message, {
      ...options,
      onProgress: (partialResponse) => {
        process?.(partialResponse)
      },
    })

    // 保存聊天上下文或最后一条消息
    contextMap.set(message.user_id, response.context || response.message)

    return sendResponse({ type: 'Success', data: response })
  }
  catch (error: any) {
    // ... 省略错误处理代码 ...
  }
}

// 修改路由处理程序，在调用 chatReplyProcess 函数时传递上下文
router.post('/chat', auth, async (req, res) => {
  const { roomId, uuid, regenerate, prompt, options = {} } = req.body as {
    roomId: number
    uuid: number
    regenerate: boolean
    prompt: string
    options?: ChatContext
  }
  const lastMessage = regenerate ? await getChat(roomId, uuid) : null
  const message = regenerate
    ? lastMessage?.prompt ?? ''
    : prompt || ''

  const context = lastMessage ?? contextMap.get(req.body.user_id)

  const response = await chatReplyProcess({ message, process: null, systemMessage: null }, context)
  if (response.type === 'Success' && lastMessage == null) {
    // ... 如果是新消息且成功发送，更新数据库中的聊天记录 ...
  }
  res.send(response)
})
这是chatgpt给出的处理方案

**Comment by lvyi21** [comment]
这应该是Markdown组件的Bug

**Comment by Root-FTW** [comment]
我有完全相同的问题

**Comment by yi-ge** [comment]
启用VITE_GLOB_OPEN_LONG_REPLY，需要自行编译。
