### ISSUE TITLE
如何对网站图标进行更换，以及chatgpt图标

### ISSUE THREAD

**Issue by luckywangxi** [Chanzhaoyu/chatgpt-web#922]
![image](https://user-images.githubusercontent.com/112324550/227855007-f9822b2b-19ee-40f8-88d8-1752854e2318.png)
![image](https://user-images.githubusercontent.com/112324550/227855151-99153e0c-62a7-4bf4-ae42-9a7bbdeb5bd3.png)

**Comment by luckywangxi** [comment]
我换了public的图标，似乎不生效

**Comment by zhengqingming85** [comment]
> ![image](https://user-images.githubusercontent.com/112324550/227855007-f9822b2b-19ee-40f8-88d8-1752854e2318.png) ![image](https://user-images.githubusercontent.com/112324550/227855151-99153e0c-62a7-4bf4-ae42-9a7bbdeb5bd3.png)



> 我换了public的图标，似乎不生效

是不生效，请问知道在哪里改chatgpt图标了吗

**Comment by luckywangxi** [comment]
> > ![image](https://user-images.githubusercontent.com/112324550/227855007-f9822b2b-19ee-40f8-88d8-1752854e2318.png) ![image](https://user-images.githubusercontent.com/112324550/227855151-99153e0c-62a7-4bf4-ae42-9a7bbdeb5bd3.png)
> 
> > 我换了public的图标，似乎不生效
> 
> 是不生效，请问知道在哪里改chatgpt图标了吗

知道，已改了

**Comment by zhengqingming85** [comment]
> > > ![image](https://user-images.githubusercontent.com/112324550/227855007-f9822b2b-19ee-40f8-88d8-1752854e2318.png) ![image](https://user-images.githubusercontent.com/112324550/227855151-99153e0c-62a7-4bf4-ae42-9a7bbdeb5bd3.png)
> > 
> > 
> > > 我换了public的图标，似乎不生效
> > 
> > 
> > 是不生效，请问知道在哪里改chatgpt图标了吗
> 
> 知道，已改了

能告诉我方法吗 我也想改一下，感谢！

**Comment by luckywangxi** [comment]
> 网页图标就是在public文件夹里面替换的

**Comment by zhengqingming85** [comment]
> > 网页图标就是在public文件夹里面替换的

我也替换了，可是没生效，还是黑白chatgpt的图标。还需要改哪里呢

**Comment by luckywangxi** [comment]
> > > 网页图标就是在public文件夹里面替换的
> 
> 我也替换了，可是没生效，还是黑白chatgpt的图标。还需要改哪里呢

PUBLIC里面的图标你要对应图像大小去修改替换，GPT图标需要你转换为SVG再复制到src\views\chat\components\Message\avater.vue中的
![image](https://user-images.githubusercontent.com/112324550/230364947-47222234-e0b4-4002-aee9-32fe164e249f.png)

**Comment by zhengqingming85** [comment]
> > > > 网页图标就是在public文件夹里面替换的
> > 
> > 
> > 我也替换了，可是没生效，还是黑白chatgpt的图标。还需要改哪里呢
> 
> PUBLIC里面的图标你要对应图像大小去修改替换，GPT图标需要你转换为SVG再复制到src\views\chat\components\Message\avater.vue中的 ![image](https://user-images.githubusercontent.com/112324550/230364947-47222234-e0b4-4002-aee9-32fe164e249f.png)

好的 我试试
