### ISSUE TITLE
server error ：UND_ERR_CONNECT_TIMEOUT

### ISSUE THREAD

**Issue by xietianyue** [Chanzhaoyu/chatgpt-web#924]
我用了自建的代理也不行。用作者提供的两个代理，都尝试过了，本地运行还是报链接超时，请问你们有什么方法解决呢
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)   
    at fetchSSE (e:\xampp\htdocs\chatgpt-web\service\node_modules\.pnpm\chatgpt@5.1.2\node_modules\chatgpt\build\index.js:46:15) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8367:37)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

**Comment by misszhangzhihui** [comment]
SOCKS可以啊。

**Comment by misszhangzhihui** [comment]
docker部署，然后国外服务器搭建socks，然后添加到 --env 就可以了

**Comment by wangcp411512** [comment]
> docker部署，然后国外服务器搭建socks，然后添加到 --env 就可以了

这个还要买一个国外服务器吗

**Comment by misszhangzhihui** [comment]
我是买的国外服务器，其他人怎么搭的，我不太清楚。

**Comment by xietianyue** [comment]
@misszhangzhihui 
你好 作者不是说了可以添加 service/.env  里 添加API_REVERSE_PROXY参数 实现代理转跳么
我本地运行，用了自建的代理-新加坡节点  也用了昨天readme里 提供的两个代理地址  也是不行
现在打算用国内的服务器安装docker试试。实在不行在用新加坡那台服务器试试看

**Comment by misszhangzhihui** [comment]
![图片](https://user-images.githubusercontent.com/92838079/227872911-17a48451-be31-46a0-ad9d-d07d2f0929e0.png)

**Comment by misszhangzhihui** [comment]
> @misszhangzhihui 你好 作者不是说了可以添加 service/.env 里 添加API_REVERSE_PROXY参数 实现代理转跳么 我本地运行，用了自建的代理-新加坡节点 也用了昨天readme里 提供的两个代理地址 也是不行 现在打算用国内的服务器安装docker试试。实在不行在用新加坡那台服务器试试看

我是上图那样添加的docker运行的

**Comment by xietianyue** [comment]
@misszhangzhihui

**Comment by xietianyue** [comment]
@misszhangzhihui   你好，你用境外服务器 还需要额外搭建代理么，他们说容易被封，是封chatgpt的账号 还是将服务器的公网ip拉入黑名单？

**Comment by misszhangzhihui** [comment]
那我暂时不清楚为什么封、也不知道封的什么。境外服务器直接一键搭socks就可以。github有一键搭的

**Comment by xietianyue** [comment]
@misszhangzhihui     本地测试不行，境内服务器不行，配置了代理转跳也不行，  境外服务器搭建 成功了    谢谢

**Comment by yexm** [comment]
大佬试试这个
