### ISSUE TITLE
可以在readme里醒目位置添加这个项目的用途介绍，适用人群，和官方web、API的不同吗？

### ISSUE THREAD

**Issue by hiyoungshen** [Chanzhaoyu/chatgpt-web#926]
可以在readme里醒目位置添加这个项目的用途介绍，适用人群，和官方web、API的不同吗？

**Comment by hiyoungshen** [comment]
起因是，看到了这个项目，但是看了半天readme并不知道这个项目的用途，感觉很疑惑，希望解答！

**Comment by eflylab** [comment]
你可以理解为私有化部署chatgpt，底层还是官方的接口。如果你觉得使用官方chatgpt网页没啥问题，那这就不需要这个项目。
