### ISSUE TITLE
腾讯云云函数代理chatgpt无法支持stream

### ISSUE THREAD

**Issue by Monica-lee99** [Chanzhaoyu/chatgpt-web#929]
腾讯云云函数代理chatgpt无法支持stream，老哥们这种情况有黑科技可以解决吗

**Comment by daniel-8642** [comment]
我这里也出现了，聊天没有打字机效果，只有在返回的数据很长一段的时候会分成两段返回出来，猜测可能是腾讯云云函数的网关开启了缓存

**Comment by cloud2303** [comment]
腾讯云函数不支持steam，用的是buffer，会把内容缓存起来再返回

**Comment by Monica-lee99** [comment]
> 腾讯云函数不支持steam，用的是buffer，会把内容缓存起来再返回
有解决办法吗老哥

**Comment by fangyuan99** [comment]
请问一下怎么用腾讯云部署这个项目啊

**Comment by daniel-8642** [comment]
> 请问一下怎么用腾讯云部署这个项目啊

我在用Ice-Hazymoon/openai-scf-proxy 这个项目直接代理openai的服务 请求的格式和官方是一样的，直接替换OPENAI_API_BASE_URL即可

**Comment by qsc19971022** [comment]
有解决的办法嘛

**Comment by cloud2303** [comment]
https://cloud.tencent.com/document/product/583/90617 腾讯云函数已经支持SSE @Monica-lee99
