### ISSUE TITLE
docker方式部署后能运行，但聊天后服务器后台老是报"CONNECT_TIMEOUT",是墙的原因么？

### ISSUE THREAD

**Issue by ahboer** [Chanzhaoyu/chatgpt-web#931]
![5](https://user-images.githubusercontent.com/23441968/227904375-ffcaeedb-6830-4159-997c-26bd618a9ec4.png)
docker-compose配置如下：
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web:v2.10.8 # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 80:3002
    environment:
      # 二选一
      OPENAI_API_KEY: sk-ketqktqketqket(此处省略...)
      # 二选一
      #OPENAI_ACCESS_TOKEN: xxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://api.openai.com
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: text-davinci-003
      #gpt-3.5-turbo
      # 反向代理，可选
      #API_REVERSE_PROXY: https://bypass.duti.tech/api/conversation
      # 访问权限密钥，可选
      #AUTH_SECRET_KEY: xxx
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      #SOCKS_PROXY_HOST: xxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      #SOCKS_PROXY_PORT: xxx
      # HTTPS 代理，可选，支持 http，https，socks5
      #HTTPS_PROXY: http://xxx:7890

**Comment by Chanzhaoyu** [comment]
把示例的 xxx 都删了，而且接口是被墙的。

**Comment by ahboer** [comment]
我在那台服务器上装了expressvpn，且connect成功了，还是不行。难道是docker的原因？

**Comment by ahboer** [comment]
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web:v2.10.8
    ports:
      - 80:3002
    environment:
      OPENAI_API_KEY: sk-feO37z2wXXX(省略....)
      OPENAI_API_BASE_URL: https://api.openai.com
      OPENAI_API_MODEL: gpt-3.5-turbo
      MAX_REQUEST_PER_HOUR: 0
      TIMEOUT_MS: 60000
      
----------------------------------
root@chant-gpt:~# ping api.openai.com
PING api.openai.com (52.152.96.252) 56(84) bytes of data.
^C
--- api.openai.com ping statistics ---
23 packets transmitted, 0 received, 100% packet loss, time 22517ms

root@chant-gpt:~# telnet
telnet> open api.openai.com 80
Trying 52.152.96.252...
Connected to api.openai.com.
Escape character is '^]'.
^CConnection closed by foreign host.
确实能访问服务器了啊，而且g-o-o-gle这个网站也能访问

**Comment by jkhcc11** [comment]
docker你只需配置`OPENAI_API_KEY: sk-feO37z2wXXX(省略....)` 这一个就行了，其他都不要，那个`OPENAI_API_BASE_URL`是代理的地址。如果你没有代理的话就不用填。还有一点，你的服务器可以访问外网才可以，否则不行。。

**Comment by jkhcc11** [comment]
> 谢谢各位，docker版照你们说的都试了，还是报连接超时。最后还是把源码编译，分别搭了前端和后端，就可以提问了。不容易啊，主要是我不是搞前端VUE的，整了两天。如果稍微懂点前端VUE，应该很快搞定。

不用哦，直接拉镜像的话，然后直接使用的ApiKey的方式，那么啥都不用配置，就可以了，直接外网访问了，除非你外面挂了层nginx，这个时候Nginx需要特殊设置（设置成支持流式返回）。

**Comment by jkhcc11** [comment]
你把环境变量`OPENAI_API_BASE_URL`  这个去掉。应该就可以了

**Comment by ahboer** [comment]
所以这就是程序员写说明文档的通病，特别是在有多种选择的时候，还真不是谁都能看懂的。哈哈，我以前也是，还抱怨客户有时提出按角色写操作使用文档是刁难咱程序员，其实还真不是，谁都想拿来即用，不用研究半天文档里的语义、上下文什么的。感谢楼上和作者的热心解答。

**Comment by aaronyyan** [comment]
> 

我是直接拉取的镜像，能删掉吗
