### ISSUE TITLE
OPENAI_ACCESS_TOKEN 没生效

### ISSUE THREAD

**Issue by fanzhefanzhe** [Chanzhaoyu/chatgpt-web#932]
OPENAI_ACCESS_TOKEN和OPENAI_API_KEY不是二选一吗，我选择了OPENAI_ACCESS_TOKEN，为什么还要去校验key呢

**Comment by wocswang** [comment]
> OPENAI_ACCESS_TOKEN和OPENAI_API_KEY不是二选一吗，我选了OPENAI_ACCESS_TOKEN，为什么还要去校试key呢

大佬我也遇到了相同得问题，你解决了吗

**Comment by assassinliujie** [comment]
你apikey是为空吗，apikey不为空的时候默认apikey
