### ISSUE TITLE
403未经授权，请先进行验证。是什么情况？？？

### ISSUE THREAD

**Issue by 52eraja** [Chanzhaoyu/chatgpt-web#933]
![Screenshot_2023-03-27-18-43-29-87_8b7aa5be40a89c6a7df806c347da652a.jpg](https://user-images.githubusercontent.com/122664422/227919928-d5918a88-0936-4ed5-95f0-4b13180e3497.jpg)

**Comment by xiaosaaaa** [comment]
你自己设的密码...

**Comment by 52eraja** [comment]
> 你自己设的密码...
> 

我好像没设置密码呀 😂这去哪儿查密码呀

**Comment by Grey0520** [comment]
docker-compose的吗？AUTH_SECRET_KEY 那个就是密码，在示例中是 xxx ，所以试一下输入三个字母 xxx

**Comment by 52eraja** [comment]
> docker-compose的吗？AUTH_SECRET_KEY 那个就是密码，在示例中是 xxx ，所以试一下输入三个字母 xxx
还真是 有个xxx 压根没注意  谢谢
