### ISSUE TITLE
[免费的公共代理转发API] https://api.openai-proxy.com

### ISSUE THREAD

**Issue by CaoYunzhou** [Chanzhaoyu/chatgpt-web#934]
- https://www.openai-proxy.com/
- 该网址提供了免费的代理转发，但是我看代码运行里面带了https://api.openai-proxy.com/pro/chat/completions/v1/chat/completion
- 可否支持这种公开的代理转发的功能
- 国内也有很多翻不了墙的同学

**Comment by pepperdog999** [comment]
这个代理转发很扯，它强行包装了一层，导致不能用在这个项目中作为api_base_url

**Comment by wangpre** [comment]
> 这个代理转发很扯，它强行包装了一层，导致不能用在这个项目中作为api_base_url

直接封装了连续对话能力对那些小白用户挺友好的，看文档里面写的，后面好像可以直接用https://api.openai-proxy.com替换https://api.openai.com

**Comment by wangpre** [comment]
> 接口转发可能导致api key泄露，我是用 Ice-Hazymoon/openai-scf-proxy 这个在腾讯云云函数（地域硅谷）上搭建的转发。

云函数的方式对并发和流量都有限制吧？

**Comment by CaoYunzhou** [comment]
> > 接口转发可能导致api key泄露，我是用 Ice-Hazymoon/openai-scf-proxy 这个在腾讯云云函数（地域硅谷）上搭建的转发。
> 
> 云函数的方式对并发和流量都有限制吧？

![image](https://user-images.githubusercontent.com/28099773/228739620-63be67a3-030c-4e39-bffc-d1bd17256a5d.png)
用这种serverless的方式，不贵，国内的云平台基本都会送一点免费额度给你，实在不行你就充点钱

**Comment by CaoYunzhou** [comment]
云函数的方式对并发和流量都有限制吧？

这个限制是看你的配置里面，包括并发，实例大小等

**Comment by CaoYunzhou** [comment]
用这个项目去部署一个转发服务，响应很快
https://github.com/Ice-Hazymoon/openai-scf-proxy
下面是我这边实际用下来的效果
![image](https://user-images.githubusercontent.com/28099773/228740264-9a375d7b-cb48-46fb-bdc2-4c9a34a07e37.png)
地址尽量选择美国硅谷，基本秒回答

**Comment by ssc7618** [comment]
> 用这个项目去部署一个转发服务，响应很快 https://github.com/Ice-Hazymoon/openai-scf-proxy 下面是我这边实际用下来的效果 ![image](https://user-images.githubusercontent.com/28099773/228740264-9a375d7b-cb48-46fb-bdc2-4c9a34a07e37.png) 地址尽量选择美国硅谷，基本秒回答

大佬，云函数部署后，怎么在项目里配置云函数的地址呢？我.env文件里覆盖了API_REVERSE_PROXY参数，请求报404

**Comment by CaoYunzhou** [comment]
> > 用这个项目去部署一个转发服务，响应很快 https://github.com/Ice-Hazymoon/openai-scf-proxy 下面是我这边实际用下来的效果 ![image](https://user-images.githubusercontent.com/28099773/228740264-9a375d7b-cb48-46fb-bdc2-4c9a34a07e37.png) 地址尽量选择美国硅谷，基本秒回答
> 
> 大佬，云函数部署后，怎么在项目里配置云函数的地址呢？我.env文件里覆盖了API_REVERSE_PROXY参数，请求报404

------------
是更改这个地址，不是cloudfare的反代的地址
          - name: OPENAI_API_BASE_URL
改这个为你的serverless的公网触发器的地址，另外一个项目说的很详细

**Comment by qsc19971022** [comment]
> 接口转发可能导致api key泄露，我是用 Ice-Hazymoon/openai-scf-proxy 这个在腾讯云云函数（地域硅谷）上搭建的转发。

大佬，云函数怎么解决无法stream的问题
