### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by Appleaihk** [Chanzhaoyu/chatgpt-web#936]
![001](https://user-images.githubusercontent.com/126216941/227949701-af53dbe7-9aab-400a-a330-610a88a3dbaf.png)

代码小白，完全按照步骤一步步来的，但是不管用Docker还是用Apache 2手动打包，运行完，浏览器链接服务器都是这个页面，是什么哪里没有设置对么？我基本啥都没改，完全照着说明，仅仅修改了.env文件填入了自己的API，（我是安装的google云的美国区云服务器上，不会存在IP需要翻墙的问题。

**Comment by daniel-8642** [comment]
看一下浏览器的网络面板和命令面板，可能是跨域没有配置好，卡在这里大概是/session接口一直没有返回

**Comment by Appleaihk** [comment]
> 看一下浏览器的网络面板和命令面板，可能是跨域没有配置好，卡在这里大概是/session接口一直没有返回

感谢回复，那么跨域和这个Session应该如何配置？有说明么？

**Comment by daniel-8642** [comment]
你需要先查看一下浏览器的错误提示，一般会指出是什么问题。

**Comment by Appleaihk** [comment]
> 你需要先查看一下浏览器的错误提示，一般会指出是什么问题。

我试了下，我连前端和后端显示得页面不同，我改一个文件得端口，错误不同了。

![500](https://user-images.githubusercontent.com/126216941/228221021-ddb4b7a2-b582-48de-a6c7-468b84e75357.png)
链接前端是这个错误了现在，

![cannot](https://user-images.githubusercontent.com/126216941/228221315-c583a70b-801d-48e4-9c77-7817543df0bd.png)
然后链接后端地址是这么个页面
