### ISSUE TITLE
使用api接口无法完整回答

### ISSUE THREAD

**Issue by huahuazi** [Chanzhaoyu/chatgpt-web#937]
如果使用api来回答的时候只能显示部分答案![Screenshot_2023-03-27-22-25-26-916_com.microsoft.emmx-edit.jpg](https://user-images.githubusercontent.com/20952620/227969355-97deacee-75e5-4a6d-b065-6f51c9b5be57.jpg)

但是使用token则能够完整回答。
使用以前版本的时候api也能够完整回答。

**Comment by lsCoding666** [comment]
输入“继续”
 试试

**Comment by assassinliujie** [comment]
看一下后端回复的内容完整吗
