### ISSUE TITLE
长文回复问题依然存在bug（已经在.env设置VITE_GLOB_OPEN_LONG_REPLY=true 并重新打docker镜像）

### ISSUE THREAD

**Issue by baoqihui** [Chanzhaoyu/chatgpt-web#939]
长文回复问题依然存在bug（已经在.env设置VITE_GLOB_OPEN_LONG_REPLY=true 并重新打docker镜像），但实际测试效果还是中断且无法继续
版本：2.10.8

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/50536515/227974442-bf7d6ee4-e2df-4c9f-a1f7-304ca2d882aa.png">

**Comment by Cp0204** [comment]
写代码更加没法用，老断

**Comment by zichen-fujianwangluo** [comment]
这个有大佬解决了吗

**Comment by baoqihui** [comment]
目前我只能通过版本回退到一周前，能好一点，不容易断掉

**Comment by Fazich** [comment]
回退版本解决了，暂时不升级了

**Comment by inlmcn** [comment]
回退也是不行，你们回退到哪个版本

**Comment by koalawangyang** [comment]
最新版本存在同样的问题，还解决方案了么？

**Comment by jwdstef** [comment]
我的也存在这个问题，回退到之前版本了
