### ISSUE TITLE
流式输出内容功能已合并 `main` 分支，欢迎大家拉取代码测试和反馈

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#94]
测试范围

- 使用  `API Key` 的情形
- 使用 `accessToken` 的情形
- 正常回答情况
- 异常回答情况

问题请在评论区留言，谢谢

**Comment by Jason6111** [comment]
Network Error

**Comment by Chanzhaoyu** [comment]
> Network Error

不好意思，问题已修复

**Comment by Jason6111** [comment]
> > Network Error
> 
> 不好意思，问题已修复

2.7.0貌似一直卡在机器人回复 一直是光标闪烁不输出回复内容

**Comment by ludashi2020** [comment]
2.7.0一直卡在机器人回复，没有结果输出。

**Comment by gygy** [comment]
> > Network Error
> 
> 不好意思，问题已修复

测试api可以，但session还有问题。测试过多次2.7版本，session就对话成功过一次。其他都是光标在闪。这个流方式是和官网的流是同步的吗？还是先取得全部结果，然后再流输出，如果是这样，会导致时间更长了。

**Comment by gygy** [comment]
> > > Network Error
> > 
> > 不好意思，问题已修复
> 
> 测试api可以，但session还有问题。测试过多次2.7版本，session就对话成功过一次。其他都是光标在闪。这个流方式是和官网的流是同步的吗？还是先取得全部结果，然后再流输出，如果是这样，会导致时间更长了。

@Chanzhaoyu

**Comment by Jason6111** [comment]
> > > Network Error
> > 
> > 
> > 不好意思，问题已修复
> 
> 测试api可以，但session还有问题。测试过多次2.7版本，session就对话成功过一次。其他都是光标在闪。这个流方式是和官网的流是同步的吗？还是先取得全部结果，然后再流输出，如果是这样，会导致时间更长了。

确实用api速度极快 用accessToken就卡住

**Comment by Chanzhaoyu** [comment]
`accessToken` 已确认问题

**Comment by Chanzhaoyu** [comment]
因为消息流在 `accessToken` 中存在解析失败和消息不完整等一系列的问题，现在调整回正常消息形式。
这个功能在返回速度是明显有提升，但是不稳定性只能先让它存在单独分支中，测试完善之后再更新进来。
