### ISSUE TITLE
用户名字一栏怎么永久自定义，需要修改哪部分配置文件

### ISSUE THREAD

**Issue by Gao-yu-1214** [Chanzhaoyu/chatgpt-web#940]
![image](https://user-images.githubusercontent.com/64946812/227976284-4d1f4f95-f51e-45df-8da7-b76b9b4d6ce4.png)

**Comment by Kosette** [comment]
搜索文件的结果 `src/store/modules/user/helper.ts:19` 和 `src/components/common/UserAvatar/index.vue:30` ，编译前修改应该可以，没有尝试过😺

**Comment by Kosette** [comment]
> > 搜索文件的结果 `src/store/modules/user/helper.ts:19` 和 `src/components/common/UserAvatar/index.vue:30` ，编译前修改应该可以，没有尝试过😺
> 
> docker-compose 部的。修改只对当前浏览器生效😄

自己重新编译镜像，再部署

**Comment by fzucs** [comment]
docker-compose部署的可以改，但是每次pull完就得重改一次，很麻烦，我现在就是这样，因为小鸡1G内存build的话会爆内存。可以的话还是自己build，在src/store/modules/user/helper.ts，改完自己docker build。

**Comment by Kosette** [comment]
> docker-compose部署的可以改，但是每次pull完就得重改一次，很麻烦，我现在就是这样，因为小鸡1G内存build的话会爆内存。可以的话还是自己build，在src/store/modules/user/helper.ts，改完自己docker build。

fork仓库，自带workflow，使用github action编译上传到docker hub就可以了。具体细节可以搜索。

**Comment by fzucs** [comment]
> > docker-compose部署的可以改，但是每次pull完就得重改一次，很麻烦，我现在就是这样，因为小鸡1G内存build的话会爆内存。可以的话还是自己build，在src/store/modules/user/helper.ts，改完自己docker build。
> 
> fork仓库，自带workflow，使用github action编译上传到docker hub就可以了。具体细节可以搜索。

还有这操作，感谢！
