### ISSUE TITLE
疑似存在后门

### ISSUE THREAD

**Issue by NoSuchField** [Chanzhaoyu/chatgpt-web#942]
<img width="1732" alt="CleanShot 2023-03-27 at 23 56 06@2x" src="https://user-images.githubusercontent.com/25945825/227996405-3e10bd06-d730-47ce-8efb-78b21b0b6635.png">

如图，访问部署好的站点，会自动在后台加载 YouTube 视频

使用 accessToken 模式，默认的代理服务器。

**Comment by daniel-8642** [comment]
![image](https://user-images.githubusercontent.com/42102561/228005474-4b824419-4cc2-4d2b-af56-78c74ce0e8e9.png)
同学可以参考一下我这里部署好的网络面板。

**Comment by NoSuchField** [comment]
@daniel-8642 感谢大佬🙏 确实乌龙了。。。经排查系浏览器插件所为，已经上报 Chrome Store
