### ISSUE TITLE
号被封了，QQ邮箱、163邮箱都没办法注册了，啥情况

### ISSUE THREAD

**Issue by kuxingdu** [Chanzhaoyu/chatgpt-web#943]

**Comment by UPman24** [comment]
现在只有谷歌账号能注册，其他的邮箱包括outlook也不能注册

**Comment by jkhcc11** [comment]
早就屏蔽国内的了，我之前的qq邮箱号，也寄了。后来用的微软登录的。现在都不敢开大号，畏畏缩缩的，干啥都是用买的成品号。

**Comment by fzucs** [comment]
我现在守着我的两个之前买的18刀账号瑟瑟发抖，希望能安全用完。大号谷歌邮箱注册的暂时也不打算用了

**Comment by jkhcc11** [comment]
> 

哈哈哈哈 18刀的 应该还好，我弄的`ai.kdy666.com` 这个，还挺耐用的。

**Comment by okrc** [comment]
试了下，域名邮箱可以注册。有域名的话，不就有~~无限~~个邮箱了么

**Comment by UPman24** [comment]
> 试了下，域名邮箱可以注册。有域名的话，不就有~无限~个邮箱了么

现在注册新用户已经没有免费额度了
