### ISSUE TITLE
docker安装使用chatgpt4模型出错

### ISSUE THREAD

**Issue by qstzs** [Chanzhaoyu/chatgpt-web#945]
![image](https://user-images.githubusercontent.com/40130765/228098612-6e23d85e-0227-4651-910e-1fa7f396976c.png)

出错
undefined
[ChatGPT error 404: {
"error": {
"message": "The model: gpt-4 does not exist",
"type": "invalid_request_error",
"param": null,
"code": "model_not_found"
}
}
]

**Comment by daniel-8642** [comment]
现在接口可以调用的模型列表中没有gpt-4哦，目前有的是 gpt-3.5-turbo-0301 ， gpt-3.5-turbo

**Comment by daniel-8642** [comment]
gpt-4是需要专门申请的

**Comment by assassinliujie** [comment]
你waitlist过了吗
