### ISSUE TITLE
公众号提供出来使用，被一天消耗了$10+的tokens，没有消息记录，无法追溯谁提问的内容与恶意消耗来源。

### ISSUE THREAD

**Issue by mouyong** [Chanzhaoyu/chatgpt-web#946]
![image](https://user-images.githubusercontent.com/10336437/228102266-8f5f4449-27ee-4748-9005-352f3bf2613a.png)

![image](https://user-images.githubusercontent.com/10336437/228102292-799990d6-4229-4a12-9dbb-d5bb62452ff0.png)

**Comment by lsCoding666** [comment]
没啥特别好的办法，有一个办法就是限制返回的字数，有的开源项目能设置，是api接口参数之一。不过缺点就是其他正常用户也得不到详细的回答了。
不过也有可能不是恶意用户，因为周围人都拿他写论文，一开口就是生成5000字的xxx文章，或者论述xx 不少于xxx字。

**Comment by assassinliujie** [comment]
或者pull request 里面有一个关闭的项目是有账号注册系统的

**Comment by jkhcc11** [comment]
还是更新到最新版，加Ip限流吧。如果在意额度的话。

**Comment by lsCoding666** [comment]
> 没啥特别好的办法，有一个办法就是限制返回的字数，有的开源项目能设置，是api接口参数之一。不过缺点就是其他正常用户也得不到详细的回答了。 不过也有可能不是恶意用户，因为周围人都拿他写论文，一开口就是生成5000字的xxx文章，或者论述xx 不少于xxx字。

然后他们还不满意 经常说在生成一份或者是做修改，由于要携带上下文提交，所以token会成倍增加 所以我觉得应该不是恶意用户

**Comment by icy37785** [comment]
公開出去一天$10+感覺挺正常，應該並不是惡意刷。

**Comment by mouyong** [comment]
产生原因：有人用来翻译，会话消息携带了历史上下文。单次的会话越多，消耗越大。

**Comment by mouyong** [comment]
> > 没啥特别好的办法，有一个办法就是限制返回的字数，有的开源项目能设置，是api接口参数之一。不过缺点就是其他正常用户也得不到详细的回答了。 不过也有可能不是恶意用户，因为周围人都拿他写论文，一开口就是生成5000字的xxx文章，或者论述xx 不少于xxx字。
> 
> 然后他们还不满意 经常说在生成一份或者是做修改，由于要携带上下文提交，所以token会成倍增加 所以我觉得应该不是恶意用户

对的。类似这种情况。

**Comment by xccloveny** [comment]
限定字数吧

**Comment by mcqnby** [comment]
先笑为敬，限制字数和每小时提问次数吧

**Comment by znsoooo** [comment]
> 没啥特别好的办法，有一个办法就是限制返回的字数，有的开源项目能设置，是api接口参数之一。不过缺点就是其他正常用户也得不到详细的回答了。 不过也有可能不是恶意用户，因为周围人都拿他写论文，一开口就是生成5000字的xxx文章，或者论述xx 不少于xxx字。

没人早上6点钟起来肝论文吧，567/h，6秒钟生成一篇了，看都看不过来。如果是一个人肯定是刷的，如果是多个人，不能都6点钟起床吧。
