### ISSUE TITLE
关于token消耗的

### ISSUE THREAD

**Issue by Timoshao** [Chanzhaoyu/chatgpt-web#947]
![image](https://user-images.githubusercontent.com/108260847/228107697-ce11d4ec-8ea4-4cb7-b505-f3812c7866d0.png)

![image](https://user-images.githubusercontent.com/108260847/228108071-56a5cc12-280e-4163-ba5c-ae4c9da21e73.png)

大佬好，对比了两个项目同样的问题token消耗发现差别很大 啥原因呢？

**Comment by ottocsb** [comment]
你自己描述的很清楚，带上下文的回复是每次会携带此会话的聊天数据进行请求，消耗的token是成倍增加的，但使用体验更优，不携带上下文，等于每次提问回答都是新的开始，它没有记忆功能，好比你让它重复你上一句话它肯定说你上面没有说过话

**Comment by Timoshao** [comment]
> 你自己描述的很清楚，带上下文的回复是每次会携带此会话的聊天数据进行请求，消耗的token是成倍增加的，但使用体验更优，不携带上下文，等于每次提问回答都是新的开始，它没有记忆功能，好比你让它重复你上一句话它肯定说你上面没有说过话

不不 同样的问题 其他的项目带上下文比这个消耗少了一倍的token.你看下绿线框起来的部分

**Comment by fzucs** [comment]
我是这么理解的，如果你发的那两张图是两个项目的话，他们回答的内容字数也不一样呀，字数多的肯定消耗token多，再带上上下文到后面肯定会更多。就算你一个项目里开两个聊天会话问两次相同的问题，它返回的内容也不同呀，字数多的消耗的token肯定多。

**Comment by ottocsb** [comment]
方便发下其他项目链接吗，我使用两个key让它回答一样的内容试试

**Comment by zhanggaolei001** [comment]
对比项目的连接能发一下不?这样好区别异同

**Comment by Timoshao** [comment]
> ，我使用两个key让它回答一样的内容试试
这是一个对接钉钉机器人的项目，
https://github.com/eryajf/chatgpt-dingtalk

**Comment by Timoshao** [comment]
> 对比项目的连接能发一下不?这样好区别异同

这是一个对接钉钉机器人的项目，
https://github.com/eryajf/chatgpt-dingtalk
