### ISSUE TITLE
后端提示 timed out 前端无提示一直在等待中

### ISSUE THREAD

**Issue by zhangzq** [Chanzhaoyu/chatgpt-web#948]
后端已出现提示：TimeoutError: OpenAI timed out waiting for response。

前端无提示，curser一直在闪烁傻等。

建议：前端提示错误 timeout。

**Comment by wocswang** [comment]
> 后端已出现提示：TimeoutError: OpenAI timed out waiting for response。
> 
> 前端无提示，curser一直在闪烁傻等。
> 
> 建议：前端提示错误 timeout。

我也是这个问题，你解决了吗

**Comment by saoman** [comment]
同上

**Comment by JoshuaYang2001** [comment]
同样是这样的问题节点已经换了好几个仍然为解决

**Comment by stemyonfc** [comment]
我也遇到一模一样的问题, 还没解决
