### ISSUE TITLE
【需求】前端上可以为每个会话选择API模型或unofficalapi

### ISSUE THREAD

**Issue by zhangzq** [Chanzhaoyu/chatgpt-web#949]
不用到后端去修改配置和重启。

**Comment by pepperdog999** [comment]
在每个对话前可以选择使用的模型就很好了。

**Comment by assassinliujie** [comment]
有一个PR可以，那个带登录系统的那个

**Comment by jiangshuo1930** [comment]
> Contributor

哪个系统

**Comment by assassinliujie** [comment]
> > Contributor
> 
> 哪个系统

https://github.com/Chanzhaoyu/chatgpt-web/pull/589
