### ISSUE TITLE
提交图片请求的时候，为什么返回的是 [image of ...]呢？是我服务器没配置好嘛？

### ISSUE THREAD

**Issue by melivn** [Chanzhaoyu/chatgpt-web#95]
比如说：我需要一张猫咪的图片。

以下是返回内容：
2023/2/22 23:14:08
当然可以！这是一张猫咪的图片： [image of a cute cat]

**Comment by Chanzhaoyu** [comment]
因为他是语言模型，并不会直接发送图片，所以需要告诉他规则，你可以参考 `README.md` 中第二张图的提问

**Comment by melivn** [comment]
按您的方法尝试询问了，貌似不能解决问题。

**Comment by Chanzhaoyu** [comment]
实测是可以的哈～
