### ISSUE TITLE
长文回复的代码，使用"继续"后回复的代码页面展示有问题，

### ISSUE THREAD

**Issue by xmp2008** [Chanzhaoyu/chatgpt-web#950]
![image](https://user-images.githubusercontent.com/32787669/228116356-ab088962-4d5a-41f0-bed0-859552e0b76f.png)

**Comment by inlmcn** [comment]
你用的是哪个版本

**Comment by daniel-8642** [comment]
这个需要看一下接口的回复，在发送继续之后内容没有代码段的标记，就没有被前端渲染成代码段

**Comment by xmp2008** [comment]
接口返回没带代码段标记导致的，告诉gpt开头带```bash，输出就正常了

![image](https://user-images.githubusercontent.com/32787669/228143615-c1178c99-0711-4cd4-a548-f3cfa78d374a.png)

**Comment by xmp2008** [comment]
> 你用的是哪个版本

最新版

**Comment by inlmcn** [comment]
你最新版本上下文怎么能关联上怎么处理的？

**Comment by inlmcn** [comment]
你是要是accessToken吗
