### ISSUE TITLE
[正在进行]为chatgpt添加google search api支持，让chatgpt联网

### ISSUE THREAD

**Issue by assassinliujie** [Chanzhaoyu/chatgpt-web#951]
目前的思路是为chatreplyprocess添加了system角色。将新建一个nlp.ts脚本用于将user发送的信息进行关键字提取（使用腾讯的nlp），然后发送给Google api进行搜索，得到information信息然后回传给system角色，将user+system的信息都发给openai，这样就可以实现联网的chatgpt，同时不显示正在搜索等进度，让聊天更自然
前端添加开关，回传给后端进行if的切换是否使用nlp.ts
但是目前有一个困难，项目中对openai的请求不包含role这个类，请问作者可以解释chatreplyprocess这段代码吗

**Comment by assassinliujie** [comment]
因为对nodejs的请求不是很熟悉，openai的官方文档也只有pythone的请求示例

**Comment by daniel-8642** [comment]
这个想法挺好，不过我之前测试的时候，它好像会忽略system的消息，官方让chatgpt联网的方法是插件。个人感觉在之后使用插件实现效果会更好。

**Comment by assassinliujie** [comment]
如果忽略system消息的话，采用字符串连接，然后让每次请求看起来像这样“内容包括fact和user两部分，请根据user部分，结合fact部分回复，user:xxx fact:   ”

**Comment by LinLin00000000** [comment]
![image](https://user-images.githubusercontent.com/51076594/228155295-9d1b9742-461d-4b38-b85d-2547de27eb65.png)
在后端接口里，prompt 和 systemMessage 分别就是 user 和 system 的 role，你可以在 chatReplyProcess 方法前把 prompt 做关键字处理提取信息，然后将 Google 搜索的信息字符串拼接在 systemMessage 后面应该就可以实现了

**Comment by assassinliujie** [comment]
https://github.com/assassinliujie/chatgpt-web/commit/f31b612d4c8cc705ddb47777adc0278845a9c96e#diff-545b64dda2c9829641b013b26196a5a504536d859d562eb3273c2d475b5c6e52
代码大概是写完了，不过出现了一些bug，使用tencentNLP进行关键词提取搜索

**Comment by assassinliujie** [comment]
可以运行的出版写好了，要再对收集到的信息处理进行优化，可以查看我fork的分支

**Comment by assassinliujie** [comment]
![CBEFD7A4BD0D5F400147F585A0A83754](https://user-images.githubusercontent.com/68693675/228449728-42122057-be4f-4ceb-ba02-5129597b6e86.jpg)
![))@KUX 0HB45T(66Y%CB{ R](https://user-images.githubusercontent.com/68693675/228449753-f127f17f-32c2-4723-bbbc-5c5df2874b4f.png)

**Comment by lkeai2007** [comment]
腾讯的nlp收费吗

**Comment by assassinliujie** [comment]
> 腾讯的nlp收费吗

收，倒是不贵。
