### ISSUE TITLE
关于使用ACCESS_TOKEN和API_KEY遇到的一些问题

### ISSUE THREAD

**Issue by inlmcn** [Chanzhaoyu/chatgpt-web#953]
使用ACCESS_TOKEN无法多人使用，如果同时使用会出现429报错
![企业微信截图_1679977557922](https://user-images.githubusercontent.com/61356473/228128188-f9d4629d-750a-4be4-b539-0a41a63f5c38.png)
使用API_KEY模式可以多人使用，但是会出现长回复无法使用，上下文不能关联，失效的问题，不知道有遇到这种情况的，请问是如何解决这个问题的谢谢

**Comment by assassinliujie** [comment]
accesstoken无法多人使用是官方限制没办法解决，api也是官方限制4096个tokens为最长

**Comment by Chanzhaoyu** [comment]
这个没办法的
