### ISSUE TITLE
【需求】显示每个回答消耗多少钱

### ISSUE THREAD

**Issue by zhangzq** [Chanzhaoyu/chatgpt-web#956]
这样心里有数~

**Comment by Grey0520** [comment]
你可以测试一下嘛。你先问它，他会告诉你一个请求意味着一段时间内的多次问答，并且每次回答间隔超过30s，会被视为下一次请求。然后你测试一下请求与余额的关系。我这边显示好像是0.02一次。
GPT说每月余额会刷新

**Comment by zhangzq** [comment]
> 你可以测试一下嘛。你先问它，他会告诉你一个请求意味着一段时间内的多次问答，并且每次回答间隔超过30s，会被视为下一次请求。然后你测试一下请求与余额的关系。我这边显示好像是0.02一次。 GPT说每月余额会刷新

余额倒是能实时看到，就是每次点进去看不是麻烦吗。

每个回答消耗多少钱，能给一个直观的感受。
