### ISSUE TITLE
想部署在子目录，请问项目以及nginx如何设置？

### ISSUE THREAD

**Issue by zhangzq** [Chanzhaoyu/chatgpt-web#957]
目前项目在根目录，使用非标准端口。请问子目录如何实现呢？

**Comment by assassinliujie** [comment]
没看懂你这个描述啥意思，子目录就wget到文件夹里解压就好了，不影响，非标准端口配置nginx反代。

**Comment by zhangzq** [comment]
> 没看懂你这个描述啥意思，子目录就wget到文件夹里解压就好了，不影响，非标准端口配置nginx反代。

比如通过 http://foo.com/chat 访问。现在只能通过根目录访问。

**Comment by Beihaiyumao** [comment]
> /
> 
> > 没看懂你这个描述啥意思，子目录就wget到文件夹里解压就好了，不影响，非标准端口配置nginx反代。
> 
> 比如我想通过 http://foo.com/chat 访问。现在只能通过http://foo.com:1002 这样的访问。

nginx配置 拦截 /chat 的请求 转发到 http://foo.com:1002/

**Comment by zhangzq** [comment]
> > /
> > > 没看懂你这个描述啥意思，子目录就wget到文件夹里解压就好了，不影响，非标准端口配置nginx反代。
> > 
> > 
> > 比如我想通过 http://foo.com/chat 访问。现在只能通过http://foo.com:1002 这样的访问。
> 
> nginx配置 拦截 /chat 的请求 转发到 http://foo.com:1002/

单纯这样试过并不行，能给个完整的配置吗？我感觉前端项目哪里也要配置子目录才行。

**Comment by assassinliujie** [comment]
> > > /
> > > > 没看懂你这个描述啥意思，子目录就wget到文件夹里解压就好了，不影响，非标准端口配置nginx反代。
> > > 
> > > 
> > > 比如我想通过 http://foo.com/chat 访问。现在只能通过http://foo.com:1002 这样的访问。
> > 
> > 
> > nginx配置 拦截 /chat 的请求 转发到 http://foo.com:1002/
> 
> 单纯这样试过并不行，能给个完整的配置吗？我感觉前端项目哪里也要配置子目录才行。

location /chat {
    proxy_pass http://127.0.0.1:1002;
}
这样应该可以吧，你修改完后重启nginx了吗

**Comment by zhangzq** [comment]
> > > > /
> > > > > 没看懂你这个描述啥意思，子目录就wget到文件夹里解压就好了，不影响，非标准端口配置nginx反代。
> > > > 
> > > > 
> > > > 比如我想通过 http://foo.com/chat 访问。现在只能通过http://foo.com:1002 这样的访问。
> > > 
> > > 
> > > nginx配置 拦截 /chat 的请求 转发到 http://foo.com:1002/
> > 
> > 
> > 单纯这样试过并不行，能给个完整的配置吗？我感觉前端项目哪里也要配置子目录才行。
> 
> location /chat { proxy_pass http://127.0.0.1:1002; } 这样应该可以吧，你修改完后重启nginx了吗

不行。js/css都404。应该是前端项目需要配置部署到子目录。

**Comment by zhangzq** [comment]
我知道了。直接build然后把文件复制到网站目录下，都不需要配置nginx。
