### ISSUE TITLE
更新版本为 `2.6.1` 导致发生错误的请更新到 `2.6.2` 或最新版本

### ISSUE THREAD

**Issue by Chanzhaoyu** [Chanzhaoyu/chatgpt-web#96]
由于发布了错误的内容导致不兼容

**Comment by melivn** [comment]
大佬辛苦了，这么晚还在忙。跟着你更新的2.61，好像也没发现什么BUG...

**Comment by Chanzhaoyu** [comment]
> docker部署测试了一下，普通回答和长回答都没发现问题，另外docker镜像最好加下版本号标签和latest标签

使用的是 2.7.0 版本吗？

**Comment by nothinggift** [comment]
> 使用的是 2.7.0 版本吗？

是的

**Comment by ludashi2020** [comment]
静态打包问题复现

**Comment by chris-ss** [comment]
docker compose + 反代部署的，昨天更新2.6.1后请求地址为 localhost:3002 导致Network Error。
更新 2.7.0 后已恢复正常。
辛苦大佬，昨天这么晚还在修复。

**Comment by jkhcc11** [comment]
> docker compose + 反代部署的，昨天更新2.6.1后请求地址为 localhost:3002 导致Network Error。 更新 2.7.0 后已恢复正常。 辛苦大佬，昨天这么晚还在修复。

你用docker compose 成功了么？我升级到2.7.0后，可以看到返回内容，但是那个光标就一直闪烁没有输出。
![image](https://user-images.githubusercontent.com/28553032/220805511-9f02cc84-fbc0-4945-b060-db14800a4229.png)
![image](https://user-images.githubusercontent.com/28553032/220805552-399d8f2c-24cf-49c1-9191-8b04b76c79ca.png)

**Comment by Chanzhaoyu** [comment]
> > docker compose + 反代部署的，昨天更新2.6.1后请求地址为 localhost:3002 导致Network Error。 更新 2.7.0 后已恢复正常。 辛苦大佬，昨天这么晚还在修复。
> 
> 你用docker compose 成功了么？我升级到2.7.0后，可以看到返回内容，但是那个光标就一直闪烁没有输出。 ![image](https://user-images.githubusercontent.com/28553032/220805511-9f02cc84-fbc0-4945-b060-db14800a4229.png) ![image](https://user-images.githubusercontent.com/28553032/220805552-399d8f2c-24cf-49c1-9191-8b04b76c79ca.png)

使用 `access_token` 还有解析问题，降版本或者使用 `api key`

**Comment by jkhcc11** [comment]
当前是api key 就很神奇
![image](https://user-images.githubusercontent.com/28553032/220806994-6ec44ddf-012f-412f-9209-fa072a2ed25b.png)

**Comment by jkhcc11** [comment]
> > > docker compose + 反代部署的，昨天更新2.6.1后请求地址为 localhost:3002 导致Network Error。 更新 2.7.0 后已恢复正常。 辛苦大佬，昨天这么晚还在修复。
> > 
> > 
> > 你用docker compose 成功了么？我升级到2.7.0后，可以看到返回内容，但是那个光标就一直闪烁没有输出。 ![image](https://user-images.githubusercontent.com/28553032/220805511-9f02cc84-fbc0-4945-b060-db14800a4229.png) ![image](https://user-images.githubusercontent.com/28553032/220805552-399d8f2c-24cf-49c1-9191-8b04b76c79ca.png)
> 
> 使用 `access_token` 还有解析问题，降版本或者使用 `api key`

建议大佬发布docker hub时使用下版本标签，现在的tag都是main，导致直接拉取对应版本镜像有点麻烦。

**Comment by sevilx** [comment]
确实，更新新版本后，用ChatGPTAPI没问题，但是用ChatGPTUnofficialProxyAPI，光标会一直闪烁给不出答案

**Comment by Chanzhaoyu** [comment]
因为消息流在 `accessToken` 中存在解析失败和消息不完整等一系列的问题，现在调整回正常消息形式。
这个功能在返回速度是明显有提升，但是不稳定性只能先让它存在单独分支中，测试完善之后再更新进来。
