### ISSUE TITLE
fetch failed怎么解决？腾讯云国内的服务器，想要用Docker部署chatgpt-web，我还要填写什么？代理？

### ISSUE THREAD

**Issue by shalom-lab** [Chanzhaoyu/chatgpt-web#970]
![image](https://user-images.githubusercontent.com/49271035/228177440-b0bbb575-011c-4ce4-8360-694e618c9ae5.png)
目前是这样的：
![image](https://user-images.githubusercontent.com/49271035/228177666-0f7de7b3-c883-4f27-802a-1350ade11985.png)

**Comment by Chanzhaoyu** [comment]
你需要一个反代，搜索 issues ，很多答案

**Comment by mcqnby** [comment]
需要部署shellclash以及购买节点，pull命令：
`export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' && wget -q --no-check-certificate -O /tmp/install.sh $url/install.sh  && bash /tmp/install.sh && source /etc/profile &> /dev/null`
剩下的自己配置就可以了
