### ISSUE TITLE
调用后端示例代理

### ISSUE THREAD

**Issue by 18639522576** [Chanzhaoyu/chatgpt-web#971]
我不想使用这个前端页面，我仅想使用后端服务，能否给出http访问后端接口示例代码吗？JAVA Net 都可以

**Comment by Chanzhaoyu** [comment]
那你还不如直接调用官方接口，几十行代码的事情。

**Comment by 18639522576** [comment]
我想使用后端那个 token  不想用那个Key,能否给下示例代码呢？

**Comment by Beihaiyumao** [comment]
> 我主要学net 所以只看懂 JAVA 和C# 代码 JS 看不懂

https://github.com/hncboy/chatgpt-web-java
