### ISSUE TITLE
为什么我提问问题答案不是流式输出的，而是等了好久一下子都出来了

### ISSUE THREAD

**Issue by M0Cube** [Chanzhaoyu/chatgpt-web#972]
是该程序就是这么设定的吗，还是我这边出现了问题，我得后端部署在了美国，前端在国内。

**Comment by itwanggj** [comment]
参考这条Issue修改下Nginx配置就可以实现流式输出了，如果后端也有Nginx配置，后端也需要对应修改下。

参考：https://github.com/Chanzhaoyu/chatgpt-web/issues/402

**Comment by starmoon-1134** [comment]
nginx 代理也需要开启流式输出
```
proxy_buffering off;
chunked_transfer_encoding on;
```

**Comment by devyujie** [comment]
> nginx 代理也需要开启流式输出
> 
> ```
> proxy_buffering off;
> chunked_transfer_encoding on;
> ```

大佬，这样对吗
![image](https://user-images.githubusercontent.com/48620527/228485745-121d191f-10b4-4a50-816a-5a8f1b94db9f.png)

**Comment by M0Cube** [comment]
确实可以了， 真牛啊大佬们

**Comment by dokhyi** [comment]
你好~我把docker部署到美国服务器上，用了一段时间后陷入了被墙的状态。这方面比较小白，请教一下如何做到前后端分离呀，需要两个服务器吗
