### ISSUE TITLE
运行后端服务出错

### ISSUE THREAD

**Issue by liangjiacun** [Chanzhaoyu/chatgpt-web#975]
进入文件夹 /service 运行 pnpm start  后报错

f:\chatgpt-web\service\src\chatgpt\index.ts:32
  throw new Error('Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable')
        ^

Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable

**Comment by Beihaiyumao** [comment]
> 进入文件夹 /service 运行 pnpm start 后报错
> 
> f:\chatgpt-web\service\src\chatgpt\index.ts:32 throw new Error('Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable') ^
> 
> Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable

没有配置环境变量

**Comment by mcqnby** [comment]
你需要把/service中的.env.example文件重命名为.env
