### ISSUE TITLE
密码咋输都不对

### ISSUE THREAD

**Issue by p6oy** [Chanzhaoyu/chatgpt-web#976]
![image](https://user-images.githubusercontent.com/125939314/228217027-3abd006a-2d06-43c8-ae55-879c2100b78c.png)
![image](https://user-images.githubusercontent.com/125939314/228217094-f3cd5269-b2e0-4ec8-9a0c-ec91c3617a53.png)
怎么办

**Comment by hncboy** [comment]
换个密码试试重启试试，看下前端接口请求头传的密码。

**Comment by p6oy** [comment]
> 换个密码试试重启试试，看下前端接口请求头传的密码。

![image](https://user-images.githubusercontent.com/125939314/228227182-7265dcb6-5784-45e7-8dd9-117bf39095c6.png)
![image](https://user-images.githubusercontent.com/125939314/228227213-6610ee9a-75e9-45a6-8a26-4aef7b240af4.png)

**Comment by p6oy** [comment]
我现在把密码删了，他还是显示有密码

**Comment by hncboy** [comment]
> Reference in ne

强制刷新清除缓存试试。

**Comment by p6oy** [comment]
> > Reference in ne
> 
> 强制刷新清除缓存试试。

我换了别的浏览器的隐私模式，还是这样

**Comment by hncboy** [comment]
> 

后端可能没重启好

**Comment by cd547** [comment]
我是在环境变量里添加的
![image](https://user-images.githubusercontent.com/17153612/228407871-2742e923-6c7d-46c9-8bb8-5364af86bd7b.png)
