### ISSUE TITLE
https://bypass.duti.tech/api/conversation 这个代理是失效了么？

### ISSUE THREAD

**Issue by imimpossib1e** [Chanzhaoyu/chatgpt-web#977]
用的ACCESS_TOKEN形式，后端一直500

**Comment by hncboy** [comment]
我刚刚试了还可以回复。

**Comment by imimpossib1e** [comment]
> {
  statusCode: 500,
  statusText: 'Internal Server Error',
  [cause]: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://bypass.duti.tech/api/conversation',
      status: 500,
      statusText: 'Internal Server Error',
      headers: [Headers],
      counter: 0
    }
  }
}

**Comment by imimpossib1e** [comment]
> 我刚刚试了还可以回复。

是access_token形式么？

**Comment by appotry** [comment]
ACCESS_TOKEN 模式，切换到另一个推荐的代理，同样不可用了
cloudflare bypass失败？

**Comment by imimpossib1e** [comment]
> ACCESS_TOKEN 模式，切换到另一个推荐的代理，同样不可用了 cloudflare bypass失败？
是的呢

**Comment by hncboy** [comment]
> > 我刚刚试了还可以回复。
> 
> 是access_token形式么？

是的。没手动配代理地址，用的默认的代理地址。

**Comment by imimpossib1e** [comment]
> > > 我刚刚试了还可以回复。
> > 
> > 
> > 是access_token形式么？
> 
> 是的。没手动配代理地址，用的默认的代理地址。

我是本地起的后端，是由于这个原因么？感觉很奇怪

**Comment by hncboy** [comment]
> > > > 我刚刚试了还可以回复。
> > > 
> > > 
> > > 是access_token形式么？
> > 
> > 
> > 是的。没手动配代理地址，用的默认的代理地址。
> 
> 我是本地起的后端，是由于这个原因么？感觉很奇怪

我本地启动，也是这个代理地址，accssToken 也可以通。

**Comment by appotry** [comment]
这个代理自建一个，有人研究过没，找过bypass.duti.tech 作者的github仓库，发现了bypass大代码仓库，没有验证是否可用，还是需要付费

**Comment by appotry** [comment]
https://github.com/acheong08/ChatGPT-Proxy-V4
内置的是这个代理，看到issues同样有人500报错

https://github.com/FlareSolverr/FlareSolverr 
不知道这个项目能否用在这里

**Comment by imimpossib1e** [comment]
> https://github.com/acheong08/ChatGPT-Proxy-V4 内置的是这个代理，看到issues同样有人500报错
> 
> https://github.com/FlareSolverr/FlareSolverr 不知道这个项目能否用在这里

代理相关的知识我也不太清楚..

**Comment by 0xinfinitykernel** [comment]
使用要求不高,可以用这个 https://luckrelay.com ,省事。:)

**Comment by appotry** [comment]
@imimpossib1e 我升级了docker版本后发现可用了 
docker pull chenzhaoyu94/chatgpt-web:v2.10.8

**Comment by expfukck** [comment]
accssToken  这个很容易封号 可惜大佬又没开源  开源感觉估计安全性高

**Comment by h3z** [comment]
> accssToken 这个很容易封号 可惜大佬又没开源 开源感觉估计安全性高

为什么容易封号

**Comment by cooolr** [comment]
> > accssToken 这个很容易封号 可惜大佬又没开源 开源感觉估计安全性高
> 
> 为什么容易封号

免费账号企图绕过Cloudflare验证在第三方客户端使用chatgpt，被检测到肯定会封号。代理的那个项目用的是付费账号的puid参数帮免费账号绕过了，应该被检测了。

**Comment by wujt1084** [comment]
> 

PUID是啥啊
![image](https://user-images.githubusercontent.com/127291078/228498489-0e3b2a25-757f-439f-9876-4c9b1394e966.png)
怎么配啊

**Comment by wujt1084** [comment]
> > > 
> > 
> > 
> > PUID是啥啊 ![image](https://user-images.githubusercontent.com/127291078/228498489-0e3b2a25-757f-439f-9876-4c9b1394e966.png) 怎么配啊
> 
> PUID 需要plus账号才有
> 
> ```shell
> export  ACCESS_TOKEN=***
> export  PUID=***
> ./ChatGPT-Proxy-V4
> ```

大佬这个代理怎么用的？需要梯子吗?我使用的时候一直未响应

**Comment by h3z** [comment]
> > > PUID是啥啊 ![image](https://user-images.githubusercontent.com/127291078/228498489-0e3b2a25-757f-439f-9876-4c9b1394e966.png) 怎么配啊
> > 
> > 
> > PUID 需要plus账号才有
> > ```shell
> > export  ACCESS_TOKEN=***
> > export  PUID=***
> > ./ChatGPT-Proxy-V4
> > ```
> 
> 大佬这个代理怎么用的？需要梯子吗?我使用的时候一直未响应

试试 `    client.SetProxy("http://ip:port")`
