### ISSUE TITLE
当用gpt-4的API时增加可用的Max Tokens

### ISSUE THREAD

**Issue by oabu** [Chanzhaoyu/chatgpt-web#979]
我用的docker
这个在哪里配置？是环境变量吗？变量名是什么？

**Comment by zhangzq** [comment]
你们gpt4的api已经审批了？

**Comment by loutian** [comment]
OPENAI_API_MODEL   应该是这个变量名， 但是我的gpt4的api审批没过没测， 我用plus的accessToken是可以的。 顺带问下，怎么加速gpt4的api审😂
