### ISSUE TITLE
前端nginx反代+node使用apikey网页光标一直闪烁,版本2.7.0

### ISSUE THREAD

**Issue by bestmidyang** [Chanzhaoyu/chatgpt-web#98]
大佬, 我这边下载了最新版本2.7.0, 使用的apikey的方式, nginx对前端做了反向代理, 浏览器访问光标一直闪烁,但是F12看结果已经拿到了
服务端如下:
   
![image](https://user-images.githubusercontent.com/28892378/220812473-6f8d0022-4e9a-4fe9-ad72-2a90691b7d7d.png)

前端: 通过pnpm build 打成dist目录

nginx配置如下:
  
![image](https://user-images.githubusercontent.com/28892378/220812597-da9ef2b7-63ae-45f7-b5af-11a9d15ea39a.png)

网页访问如下:
  
![image](https://user-images.githubusercontent.com/28892378/220812651-36256bc4-f070-43f6-a56a-8f22e83ce7a9.png)

**Comment by Chanzhaoyu** [comment]
用 `apiKey` 也会出问题吗

**Comment by bestmidyang** [comment]
是的, 刚测试了, 我下的release里面的source

**Comment by bestmidyang** [comment]
大佬,没想到你竟然秒回, 爱了爱了

**Comment by Chanzhaoyu** [comment]
我测试下

**Comment by chch455** [comment]
大部分人的光标一直闪烁无法输出答案是因为没有使用反向代理，加上反向代理就可以了

**Comment by youfu9527** [comment]
> 我测试下

大佬，我这边遇到了相同情况，查了一下api/chat-process这个返回，输出的是n个json对象，是不是这个原因导致无法序列化？
![image](https://user-images.githubusercontent.com/24789121/220822917-4d64da5a-abd3-4f2c-b9bc-8d5c7baf8d02.png)

**Comment by Chanzhaoyu** [comment]
> > 我测试下
> 
> 大佬，我这边遇到了相同情况，查了一下api/chat-process这个返回，输出的是n个json对象，是不是这个原因导致无法序列化？ ![image](https://user-images.githubusercontent.com/24789121/220822917-4d64da5a-abd3-4f2c-b9bc-8d5c7baf8d02.png)

是的，消息解析然后转成 `onDownloadProgress` 中字符的形式再显示，现在遇到一些问题，刚 `2.7.1` 已经回退版本并增加了新功能，如果是 `docker` 镜像部署的可能要等半个小时才会更新到最新。

**Comment by youfu9527** [comment]
ok，我重新build个镜像

**Comment by Chanzhaoyu** [comment]
因为消息流在 `accessToken` 中存在解析失败和消息不完整等一系列的问题，现在调整回正常消息形式。
这个功能在返回速度是明显有提升，但是不稳定性只能先让它存在单独分支中，测试完善之后再更新进来。

**Comment by youfu9527** [comment]
可以考虑一下搞个websocket之类的来流式传输？

**Comment by Chanzhaoyu** [comment]
> 

`websocket` 的话没必要，不过我一直都没弄清楚官网是怎么实现的，如果有知道的可以提示下。

**Comment by youfu9527** [comment]
用的event-stream这个头，简称sse技术。 可以建立单向服务器下推消息。

**Comment by Chanzhaoyu** [comment]
> 用的event-stream这个头，简称sse技术。 可以建立单向服务器下推消息。

好的，感谢，我去了解下

**Comment by Chanzhaoyu** [comment]
测试

<img width="957" alt="code" src="https://user-images.githubusercontent.com/24789441/220829520-0bf9a41c-13ab-4db4-80ea-5b384c8e468b.png">
<img width="922" alt="cat" src="https://user-images.githubusercontent.com/24789441/220829535-52438ea0-eade-44d3-abc4-9771f4eeda90.png">

**Comment by Siri-Li** [comment]
本地测试目前没有发现问题
