### ISSUE TITLE
nginx反向代理，IP限制对话次数那个会失效

### ISSUE THREAD

**Issue by oabu** [Chanzhaoyu/chatgpt-web#980]
nginx上已经设置好了
`proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;`
但还是一到限制量，全部用户都被限制
怀疑是js的代码，获取真实IP的代码没写对。

**Comment by fzucs** [comment]
参考#863
