### ISSUE TITLE
项目回答跟官方的差距为啥这么大？

### ISSUE THREAD

**Issue by li-sen** [Chanzhaoyu/chatgpt-web#981]
```sql
select
  mingCheng,
  sum(shuLiang) shuLiang,
  sum(fenMu) fenMu,
  if(round(shuLiang / nullif(fenMu, 0) * 100, 2) is null,
  0,
  round(shuLiang / nullif(fenMu, 0) * 100, 2)) zhanBi
from
  (
  select
    yuanqumc mingCheng,
    count(1) shuLiang,
    0 fenMu
  from
    yl_zhuyuanjzjl
  where
    zaiyuanzt = '1'
  group by
    yuanqumc
union all
  select
    yuanqumc mingCheng,
    0 shuLiang,
    count(1) fenMu
  from
    yl_chuangweixx
  group by
    yuanqumc)
group by
  mingCheng
order by
  shuLiang desc
分析这个sql
```

**Comment by li-sen** [comment]
![image](https://user-images.githubusercontent.com/33471335/228252461-8351d2ac-cba5-44a7-bc0d-db2e1e94bac5.png)
chatgpt-web-API回答

**Comment by fzucs** [comment]
首先api和网页版本来就不一样：
![image](https://user-images.githubusercontent.com/100392795/228406711-c12af2ef-ac7f-481b-8e11-4079368648dc.png)
其次，我用官方网页版问他，他自己回答的也和你的不一样：
![image](https://user-images.githubusercontent.com/100392795/228407549-3f63cbc5-e588-440a-b321-c359105b6d72.png)
最后，你可以让它详细分析：
![image](https://user-images.githubusercontent.com/100392795/228407730-811d369f-aa60-4240-83ac-5005995ac7ae.png)
