### ISSUE TITLE
把提示词json链接换成gitee国内源，下载显示302重定向

### ISSUE THREAD

**Issue by mcqnby** [Chanzhaoyu/chatgpt-web#982]
这样怎么解决呢？
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/70184446/228258437-2de47e0b-e170-44d7-8e22-07d72c9da0ea.png">

**Comment by mcqnby** [comment]
用了国内七牛云就好了，gitee有防盗链- -好麻烦，直接给我重定向到gitee的logo了

**Comment by xueguizheng** [comment]
> 用了国内七牛云就好了，gitee有防盗链- -好麻烦，直接给我重定向到gitee的logo了

兄弟，国内的在哪搞得能把下载地址贴出来不？
