### ISSUE TITLE
回答生成速度有点慢

### ISSUE THREAD

**Issue by 1205129045x** [Chanzhaoyu/chatgpt-web#983]
我都是在本地运行的，感觉回答我问题的速度有点慢，是作者给的默认代理网址不太行的原因吗？
同样的在浏览器直接运行`https://chatbot.theb.ai/#/chat/1002`这个免费的问答网址，它的回答速度就快一点

**Comment by wobushitiegan** [comment]
请问是  后端和前端都需要 部署 之后才可以启动吗

**Comment by 1205129045x** [comment]
> 请问是 后端和前端都需要 部署 之后才可以启动吗

好像是的

**Comment by assassinliujie** [comment]
因为他使用的是api你使用的是accesstoken。accesstoken确实是比api慢很多
