### ISSUE TITLE
有大佬能提供一份/api/chat-process接口的响应(json)示例么？

### ISSUE THREAD

**Issue by x-cy** [Chanzhaoyu/chatgpt-web#989]

**Comment by 18639522576** [comment]
你post 内容格式是啥样，能否贴下图

**Comment by hncboy** [comment]
控制台看下就知道了

**Comment by 18639522576** [comment]
> 控制台看下就知道了

有没有POST内容格式啊 我写的总是提示服务器错误

**Comment by hncboy** [comment]
content-type: application/octet-stream
{"role":null,"id":"xxx","parentMessageId":"xxx","conversationId":"xxx","text":"Hello"}
{"role":null,"id":"xxx","parentMessageId":"xxx","conversationId":"xxx","text":"World"}
![image](https://user-images.githubusercontent.com/27755574/228406027-e350c2a5-9892-4c3e-aed2-221754d8431c.png)

**Comment by hncboy** [comment]
> > content-type: application/octet-stream {"role":null,"id":"xxx","parentMessageId":"xxx","conversationId":"xxx","text":"Hello"} {"role":null,"id":"xxx","parentMessageId":"xxx","conversationId":"xxx","text":"World"} ![image](https://user-images.githubusercontent.com/27755574/228406027-e350c2a5-9892-4c3e-aed2-221754d8431c.png)
> 
> 你这个是返回数据格式吧？我想要POST 提交的那个格式
{
	"prompt": "hello",
	"options": {
		"parentMessageId": "xxx",
		"conversationId": "xxx"
	},
	"systemMessage": "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\nKnowledge cutoff: 2021-09-01\nCurrent date: 2023-03-29"
}

**Comment by x-cy** [comment]
> 

这个是不是还差了一个detail参数
<img width="803" alt="image" src="https://user-images.githubusercontent.com/8860492/228429186-82beb84b-2c66-4ad9-8458-1cd5f740caa2.png">

**Comment by x-cy** [comment]
> content-type: application/octet-stream {"role":null,"id":"xxx","parentMessageId":"xxx","conversationId":"xxx","text":"Hello"} {"role":null,"id":"xxx","parentMessageId":"xxx","conversationId":"xxx","text":"World"} ![image](https://user-images.githubusercontent.com/27755574/228406027-e350c2a5-9892-4c3e-aed2-221754d8431c.png)

<img width="803" alt="image" src="https://user-images.githubusercontent.com/8860492/228429295-93e422fc-68bd-4793-a5a1-4d341131dbd8.png">
这些返回数据是不是还差了一个detail参数
