### ISSUE TITLE
增加语音对话

### ISSUE THREAD

**Issue by Mpynl** [Chanzhaoyu/chatgpt-web#990]
想增加一个语音对话的聊天功能，现在的想法是通过Azure的speech API对chatgpt的回复进行语音合成，现在的问题是如何监听回复的内容，然后自动播放该段内容

**Comment by cd547** [comment]
如果只是pc平台用的话，完全可以通过浏览自带的api，实现这个功能
![11111](https://user-images.githubusercontent.com/17153612/228407116-4d515503-a1cd-437a-ace9-7df0afc2d206.png)

**Comment by Mpynl** [comment]
那如果是想做在手机上也实现这个功能的话，有什么推荐的操作吗

**Comment by cd547** [comment]
我之前没考虑到，后来人家提醒不是有语音输入法了吗？我感觉做这个功能有点多余了

**Comment by cd547** [comment]
我这个功能iPhone可以用，但是华为就是不行。主要还是Google框架服务问题

**Comment by nagaki09** [comment]
> 只是pc平台用的话，完全可以通过浏览自带的api，实现这

大佬可以指个路吗？初学者不是太懂

**Comment by cd547** [comment]
问chatgpt呀，我也是不懂，之前还考虑科大讯飞的，太麻烦，问了chatgpt，他就给了案列
