### ISSUE TITLE
我是使用的 session token  为什么还是提示 服务器繁忙，请稍后再试

### ISSUE THREAD

**Issue by 18639522576** [Chanzhaoyu/chatgpt-web#991]
错误信息：
{"message":"[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error","data":null,"status":"Fail"}

**Comment by cy-i** [comment]
账号被封了也是这种提示……你看看你的账号是不是被封了！

**Comment by 18639522576** [comment]
![image](https://user-images.githubusercontent.com/60860618/228397579-6d605b5f-12e6-4d60-9d80-675e192b948f.png)
POST 访问
数据内容
![image](https://user-images.githubusercontent.com/60860618/228397647-919800fa-a087-43b3-9f7c-e025f5966acb.png)

返回错误
{"message":"[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error","data":null,"status":"Fail"}

**Comment by sdlkhfksl** [comment]
[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error
