### ISSUE TITLE
[request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 45.114.11.238:443]`

### ISSUE THREAD

**Issue by lvbin0827** [Chanzhaoyu/chatgpt-web#993]
一直报这个错误
`undefined
[request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 45.114.11.238:443]`

**Comment by daniel-8642** [comment]
#787 看下这个issue，国内无法直接访问openai的接口
