### ISSUE TITLE
请问一下有没有会话排队机制，公司太多人同一时间发起会话 导致被限制了

### ISSUE THREAD

**Issue by shuncon** [Chanzhaoyu/chatgpt-web#995]
同一时间，发起会话询问，导致被限制：
ChatGPT error 429: {"detail":"Too many requests in 1 hour. Try again later

**Comment by assassinliujie** [comment]
如果是API请求的话有限制每小时单个IP流量功能，排毒功能意义不大吧

**Comment by shuncon** [comment]
> 如果是API请求的话有限制每小时单个IP流量功能，排队功能意义不大吧，那样不如去用accesstokens

用的accesstokens，瞬间炸了

**Comment by assassinliujie** [comment]
accesstokens本来同一个时间就只能同一个人回复哇，你是想加个提示功能显示当前有人在使用？

**Comment by assassinliujie** [comment]
商业公司人比较多的话还是买个API比较合适，虽然也不便宜

**Comment by shuncon** [comment]
> > > 如果是API请求的话有限制每小时单个IP流量功能，排队功能意义不大吧，那样不如去用accesstokens
> > 
> > 
> > 用的accesstokens，瞬间炸了
> 
> accesstokens本来同一个时间就只能同一个人回复哇，你是想加个提示功能显示当前有人在使用？

也可以吧

**Comment by shuncon** [comment]
> 商业公司人比较多的话还是买个API比较合适，虽然也不便宜

或者排队发送询问chat

**Comment by assassinliujie** [comment]
在chatreplyprocess之前加一个队列呗，然后不直接接受前端的请求，让队列按顺序发送
