### ISSUE TITLE
docker-compose 部署,域名访问异常

### ISSUE THREAD

**Issue by wujt1084** [Chanzhaoyu/chatgpt-web#997]
![image](https://user-images.githubusercontent.com/127291078/228407081-b88c7a9b-ea67-4382-9b83-f92fbd45b5a4.png)
如图，配置域名，使用docker-compose up -d,启动应用，自带nginx 镜像的nginx配置文件域名配置如下
![image](https://user-images.githubusercontent.com/127291078/228407616-3f1b1579-658b-494f-bfc4-8785987d0280.png)
求大佬解答

**Comment by wujt1084** [comment]
解决了

**Comment by Annihilater** [comment]
> 解决了

怎么解决的？
